Physical Quantities (PhQ): PhQ::Internal::Conversions< Unit, UnitValue > Class Template Reference
PhQ::Internal::Conversions< Unit, UnitValue > Class Template Reference
Abstract class for converting a series of values expressed in a unit of measure to or from the standard unit of measure of that type. Internal implementation detail not intended to be used outside of the PhQ::Convert, PhQ::ConvertCopy, and PhQ::StaticConvertCopy functions.
#include "Unit.hpp"
Static Public Member Functions
template<typename Number >
static constexpr void FromStandard (Number *values, const std::size_t size) noexcept
Converts a series of values expressed in the standard unit of measure of a given unit type to any given unit of measure of that type. Internal implementation detail not intended to be used outside of the PhQ::Convert, PhQ::ConvertCopy, and PhQ::StaticConvertCopy functions.
template<typename Number >
static constexpr void ToStandard (Number *values, const std::size_t size) noexcept
Converts a series of values expressed in any given unit of measure of a given unit type to the standard unit of measure of that type. Internal implementation detail not intended to be used outside of the PhQ::Convert, PhQ::ConvertCopy, and PhQ::StaticConvertCopy functions.
Detailed Description
template<typename Unit, Unit UnitValue>
class PhQ::Internal::Conversions< Unit, UnitValue >
Abstract class for converting a series of values expressed in a unit of measure to or from the standard unit of measure of that type. Internal implementation detail not intended to be used outside of the PhQ::Convert, PhQ::ConvertCopy, and PhQ::StaticConvertCopy functions.
Definition at line 75 of file Unit.hpp.
Member Function Documentation
FromStandard()
template<typename Unit , Unit UnitValue> template<typename Number > static constexpr void PhQ::Internal::Conversions< Unit, UnitValue >::FromStandard (Number * values, const std::size_t size) inline static constexpr noexcept
Converts a series of values expressed in the standard unit of measure of a given unit type to any given unit of measure of that type. Internal implementation detail not intended to be used outside of the PhQ::Convert, PhQ::ConvertCopy, and PhQ::StaticConvertCopy functions.
Definition at line 81 of file Unit.hpp.
References PhQ::Internal::Conversion< Unit, UnitValue >::FromStandard().
Referenced by PhQ::StaticConvertCopy().
ToStandard()
template<typename Unit , Unit UnitValue> template<typename Number > static constexpr void PhQ::Internal::Conversions< Unit, UnitValue >::ToStandard (Number * values, const std::size_t size) inline static constexpr noexcept
Converts a series of values expressed in any given unit of measure of a given unit type to the standard unit of measure of that type. Internal implementation detail not intended to be used outside of the PhQ::Convert, PhQ::ConvertCopy, and PhQ::StaticConvertCopy functions.
Definition at line 95 of file Unit.hpp.
References PhQ::Internal::Conversion< Unit, UnitValue >::ToStandard().
Referenced by PhQ::StaticConvertCopy().
The documentation for this class was generated from the following file:
PhQ/Unit.hpp