Physical Quantities: PhQ::PlanarVelocity< NumericType > Class Template Reference
PhQ::PlanarVelocity< NumericType > Class Template Reference
Two-dimensional Euclidean velocity vector in the XY plane. Contains two components in Cartesian coordinates: x and y. For a three-dimensional Euclidean velocity vector, see PhQ::Velocity. For scalar velocity components or for the magnitude of a velocity vector, see PhQ::Speed.
#include "PlanarVelocity.hpp"
Public Member Functions
PlanarVelocity ()=default
Default constructor. Constructs a planar velocity vector with an uninitialized value.
PlanarVelocity (const PlanarVector< NumericType > &value, const Unit::Speed unit)
Constructor. Constructs a planar velocity vector with a given value expressed in a given speed unit.
PlanarVelocity (const Speed< NumericType > &x, const Speed< NumericType > &y)
Constructor. Constructs a planar velocity vector from a given set of speed components.
constexpr PlanarVelocity (const Speed< NumericType > &speed, const PlanarDirection< NumericType > &planar_direction)
Constructor. Constructs a planar velocity vector from a given speed and planar direction.
constexpr PlanarVelocity (const Velocity< NumericType > &velocity)
Constructor. Constructs a planar velocity vector from a given velocity vector by projecting the velocity vector onto the XY plane.
constexpr PlanarVelocity (const PlanarDisplacement< NumericType > &planar_displacement, const Time< NumericType > &time)
Constructor. Constructs a planar velocity vector from a given planar displacement vector and time using the definition of velocity.
constexpr PlanarVelocity (const PlanarDisplacement< NumericType > &planar_displacement, const Frequency< NumericType > &frequency)
Constructor. Constructs a planar velocity vector from a given planar displacement vector and frequency using the definition of velocity.
constexpr PlanarVelocity (const PlanarAcceleration< NumericType > &planar_acceleration, const Time< NumericType > &time)
Constructor. Constructs a planar velocity vector from a given planar acceleration vector and time using the definition of acceleration.
constexpr PlanarVelocity (const PlanarAcceleration< NumericType > &planar_acceleration, const Frequency< NumericType > &frequency)
Constructor. Constructs a planar velocity vector from a given planar acceleration vector and frequency using the definition of acceleration.
~PlanarVelocity () noexcept=default
Destructor. Destroys this planar velocity vector.
constexpr PlanarVelocity (const PlanarVelocity< NumericType > &other)=default
Copy constructor. Constructs a planar velocity vector by copying another one.
template<typename OtherNumericType >
constexpr PlanarVelocity (const PlanarVelocity< OtherNumericType > &other)
Copy constructor. Constructs a planar velocity by copying another one.
constexpr PlanarVelocity (PlanarVelocity< NumericType > &&other) noexcept=default
Move constructor. Constructs a planar velocity vector by moving another one.
constexpr PlanarVelocity< NumericType > & operator= (const PlanarVelocity< NumericType > &other)=default
Copy assignment operator. Assigns this planar velocity vector by copying another one.
template<typename OtherNumericType >
constexpr PlanarVelocity< NumericType > & operator= (const PlanarVelocity< OtherNumericType > &other)
Copy assignment operator. Assigns this planar velocity by copying another one.
constexpr PlanarVelocity< NumericType > & operator= (PlanarVelocity< NumericType > &&other) noexcept=default
Move assignment operator. Assigns this planar velocity vector by moving another one.
constexpr Speed< NumericType > x () const noexcept
Returns the x Cartesian component of this planar velocity vector.
constexpr Speed< NumericType > y () const noexcept
Returns the y Cartesian component of this planar velocity vector.
Speed< NumericType > Magnitude () const
Returns the magnitude of this planar velocity vector.
PhQ::PlanarDirection< NumericType > PlanarDirection () const
Returns the planar direction of this planar velocity vector.
PhQ::Angle< NumericType > Angle (const PlanarVelocity< NumericType > &planar_velocity) const
Returns the angle between this planar velocity vector and another one.
constexpr PlanarVelocity< NumericType > operator+ (const PlanarVelocity< NumericType > &planar_velocity) const
constexpr PlanarVelocity< NumericType > operator- (const PlanarVelocity< NumericType > &planar_velocity) const
constexpr PlanarVelocity< NumericType > operator* (const NumericType number) const
constexpr PlanarDisplacement< NumericType > operator* (const Time< NumericType > &time) const
constexpr PlanarAcceleration< NumericType > operator* (const Frequency< NumericType > &frequency) const
constexpr PlanarVelocity< NumericType > operator/ (const NumericType number) const
constexpr PlanarAcceleration< NumericType > operator/ (const Time< NumericType > &time) const
constexpr PlanarDisplacement< NumericType > operator/ (const Frequency< NumericType > &frequency) const
constexpr void operator+= (const PlanarVelocity< NumericType > &planar_velocity) noexcept
constexpr void operator-= (const PlanarVelocity< NumericType > &planar_velocity) noexcept
constexpr void operator*= (const NumericType number) noexcept
constexpr void operator/= (const NumericType number) noexcept
constexpr const PhQ::PlanarVector< NumericType > & Value () const noexcept
Value of this physical quantity expressed in its standard unit of measure.
PhQ::PlanarVector< NumericType > Value (const UnitType unit) const
Value of this physical quantity expressed in a given unit of measure.
template<UnitType NewUnit>
constexpr PhQ::PlanarVector< NumericType > StaticValue () const
Value of this physical quantity expressed in a given unit of measure. This method can be evaluated statically at compile-time.
constexpr PhQ::PlanarVector< NumericType > & MutableValue () noexcept
Returns the value of this physical quantity expressed in its standard unit of measure as a mutable value.
constexpr void SetValue (const PhQ::PlanarVector< NumericType > &value) noexcept
Sets the value of this physical quantity expressed in its standard unit of measure to the given value.
std::string Print () const
Prints this physical quantity as a string. This physical quantity's value is expressed in its standard unit of measure.
std::string Print (const UnitType unit) const
Prints this physical quantity as a string. This physical quantity's value is expressed in the given unit of measure.
std::string JSON () const
Serializes this physical quantity as a JSON message. This physical quantity's value is expressed in its standard unit of measure.
std::string JSON (const UnitType unit) const
Serializes this physical quantity as a JSON message. This physical quantity's value is expressed in the given unit of measure.
std::string XML () const
Serializes this physical quantity as an XML message. This physical quantity's value is expressed in its standard unit of measure.
std::string XML (const UnitType unit) const
Serializes this physical quantity as an XML message. This physical quantity's value is expressed in the given unit of measure.
std::string YAML () const
Serializes this physical quantity as a YAML message. This physical quantity's value is expressed in its standard unit of measure.
std::string YAML (const UnitType unit) const
Serializes this physical quantity as a YAML message. This physical quantity's value is expressed in the given unit of measure.
Static Public Member Functions
static constexpr PlanarVelocity< NumericType > Zero ()
Statically creates a planar velocity vector of zero.
template<Unit::Speed Unit>
static constexpr PlanarVelocity< NumericType > Create (const NumericType x, const NumericType y)
Statically creates a planar velocity vector from the given x and y Cartesian components expressed in a given speed unit.
template<Unit::Speed Unit>
static constexpr PlanarVelocity< NumericType > Create (const std::array< NumericType, 2 > &x_y)
Statically creates a planar velocity vector from the given x and y Cartesian components expressed in a given speed unit.
template<Unit::Speed Unit>
static constexpr PlanarVelocity< NumericType > Create (const PlanarVector< NumericType > &value)
Statically creates a planar velocity vector with a given value expressed in a given speed unit.
static constexpr const PhQ::Dimensions & Dimensions ()
Physical dimension set of this physical quantity.
static constexpr UnitType Unit ()
Standard unit of measure for this physical quantity. This physical quantity's value is stored internally in this unit of measure.
Protected Attributes
PhQ::PlanarVector< NumericType > value
Value of this physical quantity expressed in its standard unit of measure.
Private Member Functions
constexpr PlanarVelocity (const PlanarVector< NumericType > &value)
Constructor. Constructs a planar velocity vector with a given value expressed in the standard speed unit.
Detailed Description
template<typename NumericType = double>
class PhQ::PlanarVelocity< NumericType >
Two-dimensional Euclidean velocity vector in the XY plane. Contains two components in Cartesian coordinates: x and y. For a three-dimensional Euclidean velocity vector, see PhQ::Velocity. For scalar velocity components or for the magnitude of a velocity vector, see PhQ::Speed.
Definition at line 54 of file PlanarVelocity.hpp.
Constructor & Destructor Documentation
PlanarVelocity() [1/13]
template<typename NumericType = double> PhQ::PlanarVelocity< NumericType >::PlanarVelocity () default
Default constructor. Constructs a planar velocity vector with an uninitialized value.
PlanarVelocity() [2/13]
template<typename NumericType = double> PhQ::PlanarVelocity< NumericType >::PlanarVelocity (const PlanarVector< NumericType > & value, const Unit::Speed unit) inline
Constructor. Constructs a planar velocity vector with a given value expressed in a given speed unit.
Definition at line 61 of file PlanarVelocity.hpp.
PlanarVelocity() [3/13]
template<typename NumericType = double> PhQ::PlanarVelocity< NumericType >::PlanarVelocity (const Speed< NumericType > & x, const Speed< NumericType > & y) inline
Constructor. Constructs a planar velocity vector from a given set of speed components.
Definition at line 65 of file PlanarVelocity.hpp.
References PhQ::PlanarVelocity< NumericType >::x(), and PhQ::PlanarVelocity< NumericType >::y().
PlanarVelocity() [4/13]
template<typename NumericType = double> constexpr PhQ::PlanarVelocity< NumericType >::PlanarVelocity (const Speed< NumericType > & speed, const PlanarDirection< NumericType > & planar_direction) inline constexpr
Constructor. Constructs a planar velocity vector from a given speed and planar direction.
Definition at line 70 of file PlanarVelocity.hpp.
PlanarVelocity() [5/13]
template<typename NumericType > constexpr PhQ::PlanarVelocity< NumericType >::PlanarVelocity (const Velocity< NumericType > & velocity) inline explicit constexpr
Constructor. Constructs a planar velocity vector from a given velocity vector by projecting the velocity vector onto the XY plane.
Definition at line 305 of file Velocity.hpp.
References PhQ::DimensionalVector< UnitType, NumericType >::Value().
PlanarVelocity() [6/13]
template<typename NumericType = double> constexpr PhQ::PlanarVelocity< NumericType >::PlanarVelocity (const PlanarDisplacement< NumericType > & planar_displacement, const Time< NumericType > & time) inline constexpr
Constructor. Constructs a planar velocity vector from a given planar displacement vector and time using the definition of velocity.
Definition at line 80 of file PlanarVelocity.hpp.
PlanarVelocity() [7/13]
template<typename NumericType = double> constexpr PhQ::PlanarVelocity< NumericType >::PlanarVelocity (const PlanarDisplacement< NumericType > & planar_displacement, const Frequency< NumericType > & frequency) inline constexpr
Constructor. Constructs a planar velocity vector from a given planar displacement vector and frequency using the definition of velocity.
Definition at line 86 of file PlanarVelocity.hpp.
PlanarVelocity() [8/13]
template<typename NumericType > constexpr PhQ::PlanarVelocity< NumericType >::PlanarVelocity (const PlanarAcceleration< NumericType > & planar_acceleration, const Time< NumericType > & time) inline constexpr
Constructor. Constructs a planar velocity vector from a given planar acceleration vector and time using the definition of acceleration.
Definition at line 287 of file PlanarAcceleration.hpp.
PlanarVelocity() [9/13]
template<typename NumericType > constexpr PhQ::PlanarVelocity< NumericType >::PlanarVelocity (const PlanarAcceleration< NumericType > & planar_acceleration, const Frequency< NumericType > & frequency) inline constexpr
Constructor. Constructs a planar velocity vector from a given planar acceleration vector and frequency using the definition of acceleration.
Definition at line 292 of file PlanarAcceleration.hpp.
~PlanarVelocity()
template<typename NumericType = double> PhQ::PlanarVelocity< NumericType >::~PlanarVelocity () default noexcept
Destructor. Destroys this planar velocity vector.
PlanarVelocity() [10/13]
template<typename NumericType = double> constexpr PhQ::PlanarVelocity< NumericType >::PlanarVelocity (const PlanarVelocity< NumericType > & other) constexpr default
Copy constructor. Constructs a planar velocity vector by copying another one.
PlanarVelocity() [11/13]
template<typename NumericType = double> template<typename OtherNumericType > constexpr PhQ::PlanarVelocity< NumericType >::PlanarVelocity (const PlanarVelocity< OtherNumericType > & other) inline explicit constexpr
Copy constructor. Constructs a planar velocity by copying another one.
Definition at line 108 of file PlanarVelocity.hpp.
PlanarVelocity() [12/13]
template<typename NumericType = double> constexpr PhQ::PlanarVelocity< NumericType >::PlanarVelocity (PlanarVelocity< NumericType > && other) constexpr default noexcept
Move constructor. Constructs a planar velocity vector by moving another one.
PlanarVelocity() [13/13]
template<typename NumericType = double> constexpr PhQ::PlanarVelocity< NumericType >::PlanarVelocity (const PlanarVector< NumericType > & value) inline explicit constexpr private
Constructor. Constructs a planar velocity vector with a given value expressed in the standard speed unit.
Definition at line 238 of file PlanarVelocity.hpp.
Member Function Documentation
Angle()
template<typename NumericType = double> PhQ::Angle< NumericType > PhQ::PlanarVelocity< NumericType >::Angle (const PlanarVelocity< NumericType > & planar_velocity) const inline
Returns the angle between this planar velocity vector and another one.
Definition at line 182 of file PlanarVelocity.hpp.
Create() [1/3]
template<typename NumericType = double> template<Unit::Speed Unit> static constexpr PlanarVelocity< NumericType > PhQ::PlanarVelocity< NumericType >::Create (const NumericType x, const NumericType y) inline static constexpr
Statically creates a planar velocity vector from the given x and y Cartesian components expressed in a given speed unit.
Definition at line 137 of file PlanarVelocity.hpp.
References PhQ::PlanarVelocity< NumericType >::x(), and PhQ::PlanarVelocity< NumericType >::y().
Create() [2/3]
template<typename NumericType = double> template<Unit::Speed Unit> static constexpr PlanarVelocity< NumericType > PhQ::PlanarVelocity< NumericType >::Create (const PlanarVector< NumericType > & value) inline static constexpr
Statically creates a planar velocity vector with a given value expressed in a given speed unit.
Definition at line 155 of file PlanarVelocity.hpp.
References PhQ::DimensionalPlanarVector< UnitType, NumericType >::value.
Create() [3/3]
template<typename NumericType = double> template<Unit::Speed Unit> static constexpr PlanarVelocity< NumericType > PhQ::PlanarVelocity< NumericType >::Create (const std::array< NumericType, 2 > & x_y) inline static constexpr
Statically creates a planar velocity vector from the given x and y Cartesian components expressed in a given speed unit.
Definition at line 146 of file PlanarVelocity.hpp.
Dimensions()
template<typename UnitType , typename NumericType = double> static constexpr const PhQ::Dimensions & PhQ::DimensionalPlanarVector< UnitType, NumericType >::Dimensions () inline static constexpr inherited
Physical dimension set of this physical quantity.
Definition at line 50 of file DimensionalPlanarVector.hpp.
JSON() [1/2]
template<typename UnitType , typename NumericType = double> std::string PhQ::DimensionalPlanarVector< UnitType, NumericType >::JSON () const inline inherited
Serializes this physical quantity as a JSON message. This physical quantity's value is expressed in its standard unit of measure.
Definition at line 103 of file DimensionalPlanarVector.hpp.
References PhQ::Abbreviation(), and PhQ::DimensionalPlanarVector< UnitType, NumericType >::value.
Referenced by PhQ::DimensionalPlanarVector< UnitType, NumericType >::JSON().
JSON() [2/2]
template<typename UnitType , typename NumericType = double> std::string PhQ::DimensionalPlanarVector< UnitType, NumericType >::JSON (const UnitType unit) const inline inherited
Serializes this physical quantity as a JSON message. This physical quantity's value is expressed in the given unit of measure.
Definition at line 113 of file DimensionalPlanarVector.hpp.
References PhQ::Abbreviation(), PhQ::DimensionalPlanarVector< UnitType, NumericType >::JSON(), and PhQ::DimensionalPlanarVector< UnitType, NumericType >::Value().
Magnitude()
template<typename NumericType = double> Speed< NumericType > PhQ::PlanarVelocity< NumericType >::Magnitude () const inline
Returns the magnitude of this planar velocity vector.
Definition at line 172 of file PlanarVelocity.hpp.
References PhQ::DimensionalPlanarVector< UnitType, NumericType >::value.
MutableValue()
template<typename UnitType , typename NumericType = double> constexpr PhQ::PlanarVector< NumericType > & PhQ::DimensionalPlanarVector< UnitType, NumericType >::MutableValue () inline constexpr noexcept inherited
Returns the value of this physical quantity expressed in its standard unit of measure as a mutable value.
Definition at line 79 of file DimensionalPlanarVector.hpp.
References PhQ::DimensionalPlanarVector< UnitType, NumericType >::value.
operator*() [1/3]
template<typename NumericType > constexpr PlanarAcceleration< NumericType > PhQ::PlanarVelocity< NumericType >::operator* (const Frequency< NumericType > & frequency) const inline constexpr
Definition at line 316 of file PlanarAcceleration.hpp.
operator*() [2/3]
template<typename NumericType = double> constexpr PlanarVelocity< NumericType > PhQ::PlanarVelocity< NumericType >::operator* (const NumericType number) const inline constexpr
Definition at line 197 of file PlanarVelocity.hpp.
References PhQ::DimensionalPlanarVector< UnitType, NumericType >::value.
operator*() [3/3]
template<typename NumericType = double> constexpr PlanarDisplacement< NumericType > PhQ::PlanarVelocity< NumericType >::operator* (const Time< NumericType > & time) const inline constexpr
Definition at line 201 of file PlanarVelocity.hpp.
operator*=()
template<typename NumericType = double> constexpr void PhQ::PlanarVelocity< NumericType >::operator*= (const NumericType number) inline constexpr noexcept
Definition at line 227 of file PlanarVelocity.hpp.
References PhQ::DimensionalPlanarVector< UnitType, NumericType >::value.
operator+()
template<typename NumericType = double> constexpr PlanarVelocity< NumericType > PhQ::PlanarVelocity< NumericType >::operator+ (const PlanarVelocity< NumericType > & planar_velocity) const inline constexpr
Definition at line 187 of file PlanarVelocity.hpp.
References PhQ::DimensionalPlanarVector< UnitType, NumericType >::value.
operator+=()
template<typename NumericType = double> constexpr void PhQ::PlanarVelocity< NumericType >::operator+= (const PlanarVelocity< NumericType > & planar_velocity) inline constexpr noexcept
Definition at line 219 of file PlanarVelocity.hpp.
References PhQ::DimensionalPlanarVector< UnitType, NumericType >::value.
operator-()
template<typename NumericType = double> constexpr PlanarVelocity< NumericType > PhQ::PlanarVelocity< NumericType >::operator- (const PlanarVelocity< NumericType > & planar_velocity) const inline constexpr
Definition at line 192 of file PlanarVelocity.hpp.
References PhQ::DimensionalPlanarVector< UnitType, NumericType >::value.
operator-=()
template<typename NumericType = double> constexpr void PhQ::PlanarVelocity< NumericType >::operator-= (const PlanarVelocity< NumericType > & planar_velocity) inline constexpr noexcept
Definition at line 223 of file PlanarVelocity.hpp.
References PhQ::DimensionalPlanarVector< UnitType, NumericType >::value.
operator/() [1/3]
template<typename NumericType = double> constexpr PlanarDisplacement< NumericType > PhQ::PlanarVelocity< NumericType >::operator/ (const Frequency< NumericType > & frequency) const inline constexpr
Definition at line 214 of file PlanarVelocity.hpp.
operator/() [2/3]
template<typename NumericType = double> constexpr PlanarVelocity< NumericType > PhQ::PlanarVelocity< NumericType >::operator/ (const NumericType number) const inline constexpr
Definition at line 208 of file PlanarVelocity.hpp.
References PhQ::DimensionalPlanarVector< UnitType, NumericType >::value.
operator/() [3/3]
template<typename NumericType > constexpr PlanarAcceleration< NumericType > PhQ::PlanarVelocity< NumericType >::operator/ (const Time< NumericType > & time) const inline constexpr
Definition at line 328 of file PlanarAcceleration.hpp.
operator/=()
template<typename NumericType = double> constexpr void PhQ::PlanarVelocity< NumericType >::operator/= (const NumericType number) inline constexpr noexcept
Definition at line 231 of file PlanarVelocity.hpp.
References PhQ::DimensionalPlanarVector< UnitType, NumericType >::value.
operator=() [1/3]
template<typename NumericType = double> constexpr PlanarVelocity< NumericType > & PhQ::PlanarVelocity< NumericType >::operator= (const PlanarVelocity< NumericType > & other) constexpr default
Copy assignment operator. Assigns this planar velocity vector by copying another one.
operator=() [2/3]
template<typename NumericType = double> template<typename OtherNumericType > constexpr PlanarVelocity< NumericType > & PhQ::PlanarVelocity< NumericType >::operator= (const PlanarVelocity< OtherNumericType > & other) inline constexpr
Copy assignment operator. Assigns this planar velocity by copying another one.
Definition at line 120 of file PlanarVelocity.hpp.
References PhQ::DimensionalPlanarVector< UnitType, NumericType >::Value(), and PhQ::DimensionalPlanarVector< UnitType, NumericType >::value.
operator=() [3/3]
template<typename NumericType = double> constexpr PlanarVelocity< NumericType > & PhQ::PlanarVelocity< NumericType >::operator= (PlanarVelocity< NumericType > && other) constexpr default noexcept
Move assignment operator. Assigns this planar velocity vector by moving another one.
PlanarDirection()
template<typename NumericType = double> PhQ::PlanarDirection< NumericType > PhQ::PlanarVelocity< NumericType >::PlanarDirection () const inline
Returns the planar direction of this planar velocity vector.
Definition at line 177 of file PlanarVelocity.hpp.
References PhQ::DimensionalPlanarVector< UnitType, NumericType >::value.
Print() [1/2]
template<typename UnitType , typename NumericType = double> std::string PhQ::DimensionalPlanarVector< UnitType, NumericType >::Print () const inline inherited
Prints this physical quantity as a string. This physical quantity's value is expressed in its standard unit of measure.
Definition at line 91 of file DimensionalPlanarVector.hpp.
References PhQ::Abbreviation(), and PhQ::DimensionalPlanarVector< UnitType, NumericType >::value.
Referenced by PhQ::operator<<(), PhQ::operator<<(), PhQ::operator<<(), PhQ::operator<<(), PhQ::operator<<(), PhQ::operator<<(), PhQ::operator<<(), and PhQ::operator<<().
Print() [2/2]
template<typename UnitType , typename NumericType = double> std::string PhQ::DimensionalPlanarVector< UnitType, NumericType >::Print (const UnitType unit) const inline inherited
Prints this physical quantity as a string. This physical quantity's value is expressed in the given unit of measure.
Definition at line 97 of file DimensionalPlanarVector.hpp.
References PhQ::Abbreviation(), and PhQ::DimensionalPlanarVector< UnitType, NumericType >::Value().
SetValue()
template<typename UnitType , typename NumericType = double> constexpr void PhQ::DimensionalPlanarVector< UnitType, NumericType >::SetValue (const PhQ::PlanarVector< NumericType > & value) inline constexpr noexcept inherited
Sets the value of this physical quantity expressed in its standard unit of measure to the given value.
Definition at line 85 of file DimensionalPlanarVector.hpp.
References PhQ::DimensionalPlanarVector< UnitType, NumericType >::value.
StaticValue()
template<typename UnitType , typename NumericType = double> template<UnitType NewUnit> constexpr PhQ::PlanarVector< NumericType > PhQ::DimensionalPlanarVector< UnitType, NumericType >::StaticValue () const inline constexpr inherited
Value of this physical quantity expressed in a given unit of measure. This method can be evaluated statically at compile-time.
Definition at line 73 of file DimensionalPlanarVector.hpp.
References PhQ::DimensionalPlanarVector< UnitType, NumericType >::value.
Unit()
template<typename UnitType , typename NumericType = double> static constexpr UnitType PhQ::DimensionalPlanarVector< UnitType, NumericType >::Unit () inline static constexpr inherited
Standard unit of measure for this physical quantity. This physical quantity's value is stored internally in this unit of measure.
Definition at line 56 of file DimensionalPlanarVector.hpp.
Value() [1/2]
template<typename UnitType , typename NumericType = double> constexpr const PhQ::PlanarVector< NumericType > & PhQ::DimensionalPlanarVector< UnitType, NumericType >::Value () const inline constexpr noexcept inherited
Value of this physical quantity expressed in its standard unit of measure.
Definition at line 61 of file DimensionalPlanarVector.hpp.
References PhQ::DimensionalPlanarVector< UnitType, NumericType >::value.
Referenced by PhQ::Acceleration< NumericType >::Acceleration(), PhQ::Displacement< NumericType >::Displacement(), PhQ::Force< NumericType >::Force(), PhQ::HeatFlux< NumericType >::HeatFlux(), PhQ::DimensionalPlanarVector< UnitType, NumericType >::JSON(), PhQ::PlanarPosition< NumericType >::operator+(), PhQ::PlanarDisplacement< NumericType >::operator+(), PhQ::PlanarPosition< NumericType >::operator-(), PhQ::PlanarDisplacement< NumericType >::operator-(), PhQ::DimensionalPlanarVector< UnitType, NumericType >::operator=(), PhQ::PlanarAcceleration< NumericType >::operator=(), PhQ::PlanarDisplacement< NumericType >::operator=(), PhQ::PlanarForce< NumericType >::operator=(), PhQ::PlanarHeatFlux< NumericType >::operator=(), PhQ::PlanarPosition< NumericType >::operator=(), PhQ::PlanarTemperatureGradient< NumericType >::operator=(), PhQ::PlanarTraction< NumericType >::operator=(), PhQ::PlanarVelocity< NumericType >::operator=(), PhQ::operator==(), PhQ::operator==(), PhQ::PlanarHeatFlux< NumericType >::PlanarHeatFlux(), PhQ::Position< NumericType >::Position(), PhQ::DimensionalPlanarVector< UnitType, NumericType >::Print(), PhQ::TemperatureGradient< NumericType >::TemperatureGradient(), PhQ::Traction< NumericType >::Traction(), PhQ::Velocity< NumericType >::Velocity(), PhQ::DimensionalPlanarVector< UnitType, NumericType >::XML(), and PhQ::DimensionalPlanarVector< UnitType, NumericType >::YAML().
Value() [2/2]
template<typename UnitType , typename NumericType = double> PhQ::PlanarVector< NumericType > PhQ::DimensionalPlanarVector< UnitType, NumericType >::Value (const UnitType unit) const inline inherited
Value of this physical quantity expressed in a given unit of measure.
Definition at line 66 of file DimensionalPlanarVector.hpp.
References PhQ::Convert(), and PhQ::DimensionalPlanarVector< UnitType, NumericType >::value.
x()
template<typename NumericType = double> constexpr Speed< NumericType > PhQ::PlanarVelocity< NumericType >::x () const inline constexpr noexcept
Returns the x Cartesian component of this planar velocity vector.
Definition at line 162 of file PlanarVelocity.hpp.
References PhQ::DimensionalPlanarVector< UnitType, NumericType >::value.
Referenced by PhQ::PlanarVelocity< NumericType >::Create(), and PhQ::PlanarVelocity< NumericType >::PlanarVelocity().
XML() [1/2]
template<typename UnitType , typename NumericType = double> std::string PhQ::DimensionalPlanarVector< UnitType, NumericType >::XML () const inline inherited
Serializes this physical quantity as an XML message. This physical quantity's value is expressed in its standard unit of measure.
Definition at line 123 of file DimensionalPlanarVector.hpp.
References PhQ::Abbreviation(), and PhQ::DimensionalPlanarVector< UnitType, NumericType >::value.
Referenced by PhQ::DimensionalPlanarVector< UnitType, NumericType >::XML().
XML() [2/2]
template<typename UnitType , typename NumericType = double> std::string PhQ::DimensionalPlanarVector< UnitType, NumericType >::XML (const UnitType unit) const inline inherited
Serializes this physical quantity as an XML message. This physical quantity's value is expressed in the given unit of measure.
Definition at line 133 of file DimensionalPlanarVector.hpp.
References PhQ::Abbreviation(), PhQ::DimensionalPlanarVector< UnitType, NumericType >::Value(), and PhQ::DimensionalPlanarVector< UnitType, NumericType >::XML().
y()
template<typename NumericType = double> constexpr Speed< NumericType > PhQ::PlanarVelocity< NumericType >::y () const inline constexpr noexcept
Returns the y Cartesian component of this planar velocity vector.
Definition at line 167 of file PlanarVelocity.hpp.
References PhQ::DimensionalPlanarVector< UnitType, NumericType >::value.
Referenced by PhQ::PlanarVelocity< NumericType >::Create(), and PhQ::PlanarVelocity< NumericType >::PlanarVelocity().
YAML() [1/2]
template<typename UnitType , typename NumericType = double> std::string PhQ::DimensionalPlanarVector< UnitType, NumericType >::YAML () const inline inherited
Serializes this physical quantity as a YAML message. This physical quantity's value is expressed in its standard unit of measure.
Definition at line 143 of file DimensionalPlanarVector.hpp.
References PhQ::Abbreviation(), and PhQ::DimensionalPlanarVector< UnitType, NumericType >::value.
Referenced by PhQ::DimensionalPlanarVector< UnitType, NumericType >::YAML().
YAML() [2/2]
template<typename UnitType , typename NumericType = double> std::string PhQ::DimensionalPlanarVector< UnitType, NumericType >::YAML (const UnitType unit) const inline inherited
Serializes this physical quantity as a YAML message. This physical quantity's value is expressed in the given unit of measure.
Definition at line 153 of file DimensionalPlanarVector.hpp.
References PhQ::Abbreviation(), PhQ::DimensionalPlanarVector< UnitType, NumericType >::Value(), and PhQ::DimensionalPlanarVector< UnitType, NumericType >::YAML().
Zero()
template<typename NumericType = double> static constexpr PlanarVelocity< NumericType > PhQ::PlanarVelocity< NumericType >::Zero () inline static constexpr
Statically creates a planar velocity vector of zero.
Definition at line 130 of file PlanarVelocity.hpp.
References PhQ::PlanarVector< NumericType >::Zero().
Member Data Documentation
value
template<typename UnitType , typename NumericType = double> PhQ::PlanarVector<NumericType> PhQ::DimensionalPlanarVector< UnitType, NumericType >::value protected inherited
Value of this physical quantity expressed in its standard unit of measure.
Definition at line 222 of file DimensionalPlanarVector.hpp.
Referenced by PhQ::PlanarAcceleration< NumericType >::Create(), PhQ::PlanarDisplacement< NumericType >::Create(), PhQ::PlanarForce< NumericType >::Create(), PhQ::PlanarHeatFlux< NumericType >::Create(), PhQ::PlanarPosition< NumericType >::Create(), PhQ::PlanarTemperatureGradient< NumericType >::Create(), PhQ::PlanarTraction< NumericType >::Create(), PhQ::PlanarVelocity< NumericType >::Create(), PhQ::DimensionalPlanarVector< UnitType, NumericType >::JSON(), PhQ::PlanarAcceleration< NumericType >::Magnitude(), PhQ::PlanarDisplacement< NumericType >::Magnitude(), PhQ::PlanarForce< NumericType >::Magnitude(), PhQ::PlanarHeatFlux< NumericType >::Magnitude(), PhQ::PlanarPosition< NumericType >::Magnitude(), PhQ::PlanarTemperatureGradient< NumericType >::Magnitude(), PhQ::PlanarTraction< NumericType >::Magnitude(), PhQ::PlanarVelocity< NumericType >::Magnitude(), PhQ::DimensionalPlanarVector< UnitType, NumericType >::MutableValue(), PhQ::PlanarAcceleration< NumericType >::operator*(), PhQ::PlanarDisplacement< NumericType >::operator*(), PhQ::PlanarForce< NumericType >::operator*(), PhQ::PlanarHeatFlux< NumericType >::operator*(), PhQ::PlanarPosition< NumericType >::operator*(), PhQ::PlanarTemperatureGradient< NumericType >::operator*(), PhQ::PlanarTraction< NumericType >::operator*(), PhQ::PlanarVelocity< NumericType >::operator*(), PhQ::PlanarAcceleration< NumericType >::operator*=(), PhQ::PlanarDisplacement< NumericType >::operator*=(), PhQ::PlanarForce< NumericType >::operator*=(), PhQ::PlanarHeatFlux< NumericType >::operator*=(), PhQ::PlanarPosition< NumericType >::operator*=(), PhQ::PlanarTemperatureGradient< NumericType >::operator*=(), PhQ::PlanarTraction< NumericType >::operator*=(), PhQ::PlanarVelocity< NumericType >::operator*=(), PhQ::PlanarAcceleration< NumericType >::operator+(), PhQ::PlanarDisplacement< NumericType >::operator+(), PhQ::PlanarPosition< NumericType >::operator+(), PhQ::PlanarForce< NumericType >::operator+(), PhQ::PlanarHeatFlux< NumericType >::operator+(), PhQ::PlanarPosition< NumericType >::operator+(), PhQ::PlanarTemperatureGradient< NumericType >::operator+(), PhQ::PlanarTraction< NumericType >::operator+(), PhQ::PlanarVelocity< NumericType >::operator+(), PhQ::PlanarAcceleration< NumericType >::operator+=(), PhQ::PlanarDisplacement< NumericType >::operator+=(), PhQ::PlanarPosition< NumericType >::operator+=(), PhQ::PlanarForce< NumericType >::operator+=(), PhQ::PlanarHeatFlux< NumericType >::operator+=(), PhQ::PlanarPosition< NumericType >::operator+=(), PhQ::PlanarTemperatureGradient< NumericType >::operator+=(), PhQ::PlanarTraction< NumericType >::operator+=(), PhQ::PlanarVelocity< NumericType >::operator+=(), PhQ::PlanarAcceleration< NumericType >::operator-(), PhQ::PlanarDisplacement< NumericType >::operator-(), PhQ::PlanarPosition< NumericType >::operator-(), PhQ::PlanarForce< NumericType >::operator-(), PhQ::PlanarHeatFlux< NumericType >::operator-(), PhQ::PlanarPosition< NumericType >::operator-(), PhQ::PlanarTemperatureGradient< NumericType >::operator-(), PhQ::PlanarTraction< NumericType >::operator-(), PhQ::PlanarVelocity< NumericType >::operator-(), PhQ::PlanarAcceleration< NumericType >::operator-=(), PhQ::PlanarDisplacement< NumericType >::operator-=(), PhQ::PlanarPosition< NumericType >::operator-=(), PhQ::PlanarForce< NumericType >::operator-=(), PhQ::PlanarHeatFlux< NumericType >::operator-=(), PhQ::PlanarPosition< NumericType >::operator-=(), PhQ::PlanarTemperatureGradient< NumericType >::operator-=(), PhQ::PlanarTraction< NumericType >::operator-=(), PhQ::PlanarVelocity< NumericType >::operator-=(), PhQ::PlanarAcceleration< NumericType >::operator/(), PhQ::PlanarDisplacement< NumericType >::operator/(), PhQ::PlanarForce< NumericType >::operator/(), PhQ::PlanarHeatFlux< NumericType >::operator/(), PhQ::PlanarPosition< NumericType >::operator/(), PhQ::PlanarTemperatureGradient< NumericType >::operator/(), PhQ::PlanarTraction< NumericType >::operator/(), PhQ::PlanarVelocity< NumericType >::operator/(), PhQ::PlanarAcceleration< NumericType >::operator/=(), PhQ::PlanarDisplacement< NumericType >::operator/=(), PhQ::PlanarForce< NumericType >::operator/=(), PhQ::PlanarHeatFlux< NumericType >::operator/=(), PhQ::PlanarPosition< NumericType >::operator/=(), PhQ::PlanarTemperatureGradient< NumericType >::operator/=(), PhQ::PlanarTraction< NumericType >::operator/=(), PhQ::PlanarVelocity< NumericType >::operator/=(), PhQ::DimensionalPlanarVector< UnitType, NumericType >::operator=(), PhQ::PlanarAcceleration< NumericType >::operator=(), PhQ::PlanarDisplacement< NumericType >::operator=(), PhQ::PlanarForce< NumericType >::operator=(), PhQ::PlanarHeatFlux< NumericType >::operator=(), PhQ::PlanarPosition< NumericType >::operator=(), PhQ::PlanarTemperatureGradient< NumericType >::operator=(), PhQ::PlanarTraction< NumericType >::operator=(), PhQ::PlanarVelocity< NumericType >::operator=(), PhQ::PlanarAcceleration< NumericType >::PlanarDirection(), PhQ::PlanarDisplacement< NumericType >::PlanarDirection(), PhQ::PlanarForce< NumericType >::PlanarDirection(), PhQ::PlanarHeatFlux< NumericType >::PlanarDirection(), PhQ::PlanarPosition< NumericType >::PlanarDirection(), PhQ::PlanarTemperatureGradient< NumericType >::PlanarDirection(), PhQ::PlanarTraction< NumericType >::PlanarDirection(), PhQ::PlanarVelocity< NumericType >::PlanarDirection(), PhQ::DimensionalPlanarVector< UnitType, NumericType >::Print(), PhQ::DimensionalPlanarVector< UnitType, NumericType >::SetValue(), PhQ::DimensionalPlanarVector< UnitType, NumericType >::StaticValue(), PhQ::DimensionalPlanarVector< UnitType, NumericType >::Value(), PhQ::DimensionalPlanarVector< UnitType, NumericType >::Value(), PhQ::PlanarAcceleration< NumericType >::x(), PhQ::PlanarDisplacement< NumericType >::x(), PhQ::PlanarForce< NumericType >::x(), PhQ::PlanarHeatFlux< NumericType >::x(), PhQ::PlanarPosition< NumericType >::x(), PhQ::PlanarTemperatureGradient< NumericType >::x(), PhQ::PlanarTraction< NumericType >::x(), PhQ::PlanarVelocity< NumericType >::x(), PhQ::DimensionalPlanarVector< UnitType, NumericType >::XML(), PhQ::PlanarAcceleration< NumericType >::y(), PhQ::PlanarDisplacement< NumericType >::y(), PhQ::PlanarForce< NumericType >::y(), PhQ::PlanarHeatFlux< NumericType >::y(), PhQ::PlanarPosition< NumericType >::y(), PhQ::PlanarTemperatureGradient< NumericType >::y(), PhQ::PlanarTraction< NumericType >::y(), PhQ::PlanarVelocity< NumericType >::y(), PhQ::DimensionalPlanarVector< UnitType, NumericType >::YAML(), and PhQ::PlanarDisplacement< NumericType >::z().
The documentation for this class was generated from the following files:
PhQ/Angle.hpp
PhQ/PlanarVelocity.hpp
PhQ/PlanarAcceleration.hpp
PhQ/Velocity.hpp