Physical Quantities: PhQ::PlanarTraction< NumericType > Class Template Reference
PhQ::PlanarTraction< NumericType > Class Template Reference
Two-dimensional Euclidean traction vector in the XY plane. Contains two components in Cartesian coordinates: x and y. Traction is similar to pressure; however, traction can act in any direction, whereas pressure always acts compressively perpendicular to a surface. For a three-dimensional Euclidean traction vector, see PhQ::Traction. For scalar traction components or for the magnitude of a traction vector, see PhQ::ScalarTraction.
#include "PlanarTraction.hpp"
Public Member Functions
PlanarTraction ()=default
Default constructor. Constructs a planar traction vector with an uninitialized value.
PlanarTraction (const PlanarVector< NumericType > &value, const Unit::Pressure unit)
Constructor. Constructs a planar traction vector with a given value expressed in a given pressure unit.
PlanarTraction (const ScalarTraction< NumericType > &x, const ScalarTraction< NumericType > &y)
Constructor. Constructs a planar traction vector from a given set of scalar traction components.
constexpr PlanarTraction (const ScalarTraction< NumericType > &scalar_traction, const PlanarDirection< NumericType > &planar_direction)
Constructor. Constructs a planar traction vector from a given scalar traction and planar direction.
constexpr PlanarTraction (const Traction< NumericType > &traction)
Constructor. Constructs a planar traction vector from a given traction vector by projecting the traction vector onto the XY plane.
constexpr PlanarTraction (const PlanarForce< NumericType > &planar_force, const Area< NumericType > &area)
Constructor. Constructs a planar traction vector from a given planar force and area using the definition of traction.
constexpr PlanarTraction (const Stress< NumericType > &stress, const PlanarDirection< NumericType > &planar_direction)
Constructor. Constructs a planar traction vector from a given stress and direction using the definition of traction.
~PlanarTraction () noexcept=default
Destructor. Destroys this planar traction vector.
constexpr PlanarTraction (const PlanarTraction< NumericType > &other)=default
Copy constructor. Constructs a planar traction vector by copying another one.
template<typename OtherNumericType >
constexpr PlanarTraction (const PlanarTraction< OtherNumericType > &other)
Copy constructor. Constructs a planar traction vector by copying another one.
constexpr PlanarTraction (PlanarTraction< NumericType > &&other) noexcept=default
Move constructor. Constructs a planar traction vector by moving another one.
constexpr PlanarTraction< NumericType > & operator= (const PlanarTraction< NumericType > &other)=default
Copy assignment operator. Assigns this planar traction vector by copying another one.
template<typename OtherNumericType >
constexpr PlanarTraction< NumericType > & operator= (const PlanarTraction< OtherNumericType > &other)
Copy assignment operator. Assigns this planar traction vector by copying another one.
constexpr PlanarTraction< NumericType > & operator= (PlanarTraction< NumericType > &&other) noexcept=default
Move assignment operator. Assigns this planar traction vector by moving another one.
constexpr ScalarTraction< NumericType > x () const noexcept
Returns the x Cartesian component of this planar traction vector.
constexpr ScalarTraction< NumericType > y () const noexcept
Returns the y Cartesian component of this planar traction vector.
ScalarTraction< NumericType > Magnitude () const
Returns the magnitude of this planar traction vector.
PhQ::PlanarDirection< NumericType > PlanarDirection () const
Returns the direction of this planar traction vector.
PhQ::Angle< NumericType > Angle (const PlanarTraction< NumericType > &planar_traction) const
Returns the angle between this planar traction vector and another one.
constexpr PlanarTraction< NumericType > operator+ (const PlanarTraction< NumericType > &planar_traction) const
constexpr PlanarTraction< NumericType > operator- (const PlanarTraction< NumericType > &planar_traction) const
constexpr PlanarTraction< NumericType > operator* (const NumericType number) const
constexpr PlanarForce< NumericType > operator* (const Area< NumericType > &area) const
constexpr PlanarTraction< NumericType > operator/ (const NumericType number) const
constexpr void operator+= (const PlanarTraction< NumericType > &planar_traction) noexcept
constexpr void operator-= (const PlanarTraction< NumericType > &planar_traction) noexcept
constexpr void operator*= (const NumericType number) noexcept
constexpr void operator/= (const NumericType number) noexcept
constexpr const PhQ::PlanarVector< NumericType > & Value () const noexcept
Value of this physical quantity expressed in its standard unit of measure.
PhQ::PlanarVector< NumericType > Value (const UnitType unit) const
Value of this physical quantity expressed in a given unit of measure.
template<UnitType NewUnit>
constexpr PhQ::PlanarVector< NumericType > StaticValue () const
Value of this physical quantity expressed in a given unit of measure. This method can be evaluated statically at compile-time.
constexpr PhQ::PlanarVector< NumericType > & MutableValue () noexcept
Returns the value of this physical quantity expressed in its standard unit of measure as a mutable value.
constexpr void SetValue (const PhQ::PlanarVector< NumericType > &value) noexcept
Sets the value of this physical quantity expressed in its standard unit of measure to the given value.
std::string Print () const
Prints this physical quantity as a string. This physical quantity's value is expressed in its standard unit of measure.
std::string Print (const UnitType unit) const
Prints this physical quantity as a string. This physical quantity's value is expressed in the given unit of measure.
std::string JSON () const
Serializes this physical quantity as a JSON message. This physical quantity's value is expressed in its standard unit of measure.
std::string JSON (const UnitType unit) const
Serializes this physical quantity as a JSON message. This physical quantity's value is expressed in the given unit of measure.
std::string XML () const
Serializes this physical quantity as an XML message. This physical quantity's value is expressed in its standard unit of measure.
std::string XML (const UnitType unit) const
Serializes this physical quantity as an XML message. This physical quantity's value is expressed in the given unit of measure.
std::string YAML () const
Serializes this physical quantity as a YAML message. This physical quantity's value is expressed in its standard unit of measure.
std::string YAML (const UnitType unit) const
Serializes this physical quantity as a YAML message. This physical quantity's value is expressed in the given unit of measure.
Static Public Member Functions
static constexpr PlanarTraction< NumericType > Zero ()
Statically creates a planar traction vector of zero.
template<Unit::Pressure Unit>
static constexpr PlanarTraction< NumericType > Create (const NumericType x, const NumericType y)
Statically creates a planar traction vector from the given x and y Cartesian components expressed in a given pressure unit.
template<Unit::Pressure Unit>
static constexpr PlanarTraction< NumericType > Create (const std::array< NumericType, 2 > &x_y)
Statically creates a planar traction vector from the given x and y Cartesian components expressed in a given pressure unit.
template<Unit::Pressure Unit>
static constexpr PlanarTraction< NumericType > Create (const PlanarVector< NumericType > &value)
Statically creates a planar traction vector with a given value expressed in a given pressure unit.
static constexpr const PhQ::Dimensions & Dimensions ()
Physical dimension set of this physical quantity.
static constexpr UnitType Unit ()
Standard unit of measure for this physical quantity. This physical quantity's value is stored internally in this unit of measure.
Protected Attributes
PhQ::PlanarVector< NumericType > value
Value of this physical quantity expressed in its standard unit of measure.
Private Member Functions
constexpr PlanarTraction (const PlanarVector< NumericType > &value)
Constructor. Constructs a planar traction vector with a given value expressed in the standard pressure unit.
Detailed Description
template<typename NumericType = double>
class PhQ::PlanarTraction< NumericType >
Two-dimensional Euclidean traction vector in the XY plane. Contains two components in Cartesian coordinates: x and y. Traction is similar to pressure; however, traction can act in any direction, whereas pressure always acts compressively perpendicular to a surface. For a three-dimensional Euclidean traction vector, see PhQ::Traction. For scalar traction components or for the magnitude of a traction vector, see PhQ::ScalarTraction.
Definition at line 53 of file PlanarTraction.hpp.
Constructor & Destructor Documentation
PlanarTraction() [1/11]
template<typename NumericType = double> PhQ::PlanarTraction< NumericType >::PlanarTraction () default
Default constructor. Constructs a planar traction vector with an uninitialized value.
PlanarTraction() [2/11]
template<typename NumericType = double> PhQ::PlanarTraction< NumericType >::PlanarTraction (const PlanarVector< NumericType > & value, const Unit::Pressure unit) inline
Constructor. Constructs a planar traction vector with a given value expressed in a given pressure unit.
Definition at line 60 of file PlanarTraction.hpp.
PlanarTraction() [3/11]
template<typename NumericType = double> PhQ::PlanarTraction< NumericType >::PlanarTraction (const ScalarTraction< NumericType > & x, const ScalarTraction< NumericType > & y) inline
Constructor. Constructs a planar traction vector from a given set of scalar traction components.
Definition at line 65 of file PlanarTraction.hpp.
References PhQ::PlanarTraction< NumericType >::x(), and PhQ::PlanarTraction< NumericType >::y().
PlanarTraction() [4/11]
template<typename NumericType = double> constexpr PhQ::PlanarTraction< NumericType >::PlanarTraction (const ScalarTraction< NumericType > & scalar_traction, const PlanarDirection< NumericType > & planar_direction) inline constexpr
Constructor. Constructs a planar traction vector from a given scalar traction and planar direction.
Definition at line 70 of file PlanarTraction.hpp.
PlanarTraction() [5/11]
template<typename NumericType > constexpr PhQ::PlanarTraction< NumericType >::PlanarTraction (const Traction< NumericType > & traction) inline explicit constexpr
Constructor. Constructs a planar traction vector from a given traction vector by projecting the traction vector onto the XY plane.
Definition at line 301 of file Traction.hpp.
References PhQ::DimensionalVector< UnitType, NumericType >::Value().
PlanarTraction() [6/11]
template<typename NumericType = double> constexpr PhQ::PlanarTraction< NumericType >::PlanarTraction (const PlanarForce< NumericType > & planar_force, const Area< NumericType > & area) inline constexpr
Constructor. Constructs a planar traction vector from a given planar force and area using the definition of traction.
Definition at line 80 of file PlanarTraction.hpp.
PlanarTraction() [7/11]
template<typename NumericType > constexpr PhQ::PlanarTraction< NumericType >::PlanarTraction (const Stress< NumericType > & stress, const PlanarDirection< NumericType > & planar_direction) inline constexpr
Constructor. Constructs a planar traction vector from a given stress and direction using the definition of traction.
Definition at line 297 of file Stress.hpp.
References PhQ::DimensionalSymmetricDyad< UnitType, NumericType >::Value().
~PlanarTraction()
template<typename NumericType = double> PhQ::PlanarTraction< NumericType >::~PlanarTraction () default noexcept
Destructor. Destroys this planar traction vector.
PlanarTraction() [8/11]
template<typename NumericType = double> constexpr PhQ::PlanarTraction< NumericType >::PlanarTraction (const PlanarTraction< NumericType > & other) constexpr default
Copy constructor. Constructs a planar traction vector by copying another one.
PlanarTraction() [9/11]
template<typename NumericType = double> template<typename OtherNumericType > constexpr PhQ::PlanarTraction< NumericType >::PlanarTraction (const PlanarTraction< OtherNumericType > & other) inline explicit constexpr
Copy constructor. Constructs a planar traction vector by copying another one.
Definition at line 97 of file PlanarTraction.hpp.
PlanarTraction() [10/11]
template<typename NumericType = double> constexpr PhQ::PlanarTraction< NumericType >::PlanarTraction (PlanarTraction< NumericType > && other) constexpr default noexcept
Move constructor. Constructs a planar traction vector by moving another one.
PlanarTraction() [11/11]
template<typename NumericType = double> constexpr PhQ::PlanarTraction< NumericType >::PlanarTraction (const PlanarVector< NumericType > & value) inline explicit constexpr private
Constructor. Constructs a planar traction vector with a given value expressed in the standard pressure unit.
Definition at line 219 of file PlanarTraction.hpp.
Member Function Documentation
Angle()
template<typename NumericType = double> PhQ::Angle< NumericType > PhQ::PlanarTraction< NumericType >::Angle (const PlanarTraction< NumericType > & planar_traction) const inline
Returns the angle between this planar traction vector and another one.
Definition at line 173 of file PlanarTraction.hpp.
Create() [1/3]
template<typename NumericType = double> template<Unit::Pressure Unit> static constexpr PlanarTraction< NumericType > PhQ::PlanarTraction< NumericType >::Create (const NumericType x, const NumericType y) inline static constexpr
Statically creates a planar traction vector from the given x and y Cartesian components expressed in a given pressure unit.
Definition at line 126 of file PlanarTraction.hpp.
References PhQ::PlanarTraction< NumericType >::x(), and PhQ::PlanarTraction< NumericType >::y().
Create() [2/3]
template<typename NumericType = double> template<Unit::Pressure Unit> static constexpr PlanarTraction< NumericType > PhQ::PlanarTraction< NumericType >::Create (const PlanarVector< NumericType > & value) inline static constexpr
Statically creates a planar traction vector with a given value expressed in a given pressure unit.
Definition at line 146 of file PlanarTraction.hpp.
References PhQ::DimensionalPlanarVector< UnitType, NumericType >::value.
Create() [3/3]
template<typename NumericType = double> template<Unit::Pressure Unit> static constexpr PlanarTraction< NumericType > PhQ::PlanarTraction< NumericType >::Create (const std::array< NumericType, 2 > & x_y) inline static constexpr
Statically creates a planar traction vector from the given x and y Cartesian components expressed in a given pressure unit.
Definition at line 136 of file PlanarTraction.hpp.
Dimensions()
template<typename UnitType , typename NumericType = double> static constexpr const PhQ::Dimensions & PhQ::DimensionalPlanarVector< UnitType, NumericType >::Dimensions () inline static constexpr inherited
Physical dimension set of this physical quantity.
Definition at line 50 of file DimensionalPlanarVector.hpp.
JSON() [1/2]
template<typename UnitType , typename NumericType = double> std::string PhQ::DimensionalPlanarVector< UnitType, NumericType >::JSON () const inline inherited
Serializes this physical quantity as a JSON message. This physical quantity's value is expressed in its standard unit of measure.
Definition at line 103 of file DimensionalPlanarVector.hpp.
References PhQ::Abbreviation(), and PhQ::DimensionalPlanarVector< UnitType, NumericType >::value.
Referenced by PhQ::DimensionalPlanarVector< UnitType, NumericType >::JSON().
JSON() [2/2]
template<typename UnitType , typename NumericType = double> std::string PhQ::DimensionalPlanarVector< UnitType, NumericType >::JSON (const UnitType unit) const inline inherited
Serializes this physical quantity as a JSON message. This physical quantity's value is expressed in the given unit of measure.
Definition at line 113 of file DimensionalPlanarVector.hpp.
References PhQ::Abbreviation(), PhQ::DimensionalPlanarVector< UnitType, NumericType >::JSON(), and PhQ::DimensionalPlanarVector< UnitType, NumericType >::Value().
Magnitude()
template<typename NumericType = double> ScalarTraction< NumericType > PhQ::PlanarTraction< NumericType >::Magnitude () const inline
Returns the magnitude of this planar traction vector.
Definition at line 163 of file PlanarTraction.hpp.
References PhQ::DimensionalPlanarVector< UnitType, NumericType >::value.
MutableValue()
template<typename UnitType , typename NumericType = double> constexpr PhQ::PlanarVector< NumericType > & PhQ::DimensionalPlanarVector< UnitType, NumericType >::MutableValue () inline constexpr noexcept inherited
Returns the value of this physical quantity expressed in its standard unit of measure as a mutable value.
Definition at line 79 of file DimensionalPlanarVector.hpp.
References PhQ::DimensionalPlanarVector< UnitType, NumericType >::value.
operator*() [1/2]
template<typename NumericType = double> constexpr PlanarForce< NumericType > PhQ::PlanarTraction< NumericType >::operator* (const Area< NumericType > & area) const inline constexpr
Definition at line 192 of file PlanarTraction.hpp.
operator*() [2/2]
template<typename NumericType = double> constexpr PlanarTraction< NumericType > PhQ::PlanarTraction< NumericType >::operator* (const NumericType number) const inline constexpr
Definition at line 188 of file PlanarTraction.hpp.
References PhQ::DimensionalPlanarVector< UnitType, NumericType >::value.
operator*=()
template<typename NumericType = double> constexpr void PhQ::PlanarTraction< NumericType >::operator*= (const NumericType number) inline constexpr noexcept
Definition at line 208 of file PlanarTraction.hpp.
References PhQ::DimensionalPlanarVector< UnitType, NumericType >::value.
operator+()
template<typename NumericType = double> constexpr PlanarTraction< NumericType > PhQ::PlanarTraction< NumericType >::operator+ (const PlanarTraction< NumericType > & planar_traction) const inline constexpr
Definition at line 178 of file PlanarTraction.hpp.
References PhQ::DimensionalPlanarVector< UnitType, NumericType >::value.
operator+=()
template<typename NumericType = double> constexpr void PhQ::PlanarTraction< NumericType >::operator+= (const PlanarTraction< NumericType > & planar_traction) inline constexpr noexcept
Definition at line 200 of file PlanarTraction.hpp.
References PhQ::DimensionalPlanarVector< UnitType, NumericType >::value.
operator-()
template<typename NumericType = double> constexpr PlanarTraction< NumericType > PhQ::PlanarTraction< NumericType >::operator- (const PlanarTraction< NumericType > & planar_traction) const inline constexpr
Definition at line 183 of file PlanarTraction.hpp.
References PhQ::DimensionalPlanarVector< UnitType, NumericType >::value.
operator-=()
template<typename NumericType = double> constexpr void PhQ::PlanarTraction< NumericType >::operator-= (const PlanarTraction< NumericType > & planar_traction) inline constexpr noexcept
Definition at line 204 of file PlanarTraction.hpp.
References PhQ::DimensionalPlanarVector< UnitType, NumericType >::value.
operator/()
template<typename NumericType = double> constexpr PlanarTraction< NumericType > PhQ::PlanarTraction< NumericType >::operator/ (const NumericType number) const inline constexpr
Definition at line 196 of file PlanarTraction.hpp.
References PhQ::DimensionalPlanarVector< UnitType, NumericType >::value.
operator/=()
template<typename NumericType = double> constexpr void PhQ::PlanarTraction< NumericType >::operator/= (const NumericType number) inline constexpr noexcept
Definition at line 212 of file PlanarTraction.hpp.
References PhQ::DimensionalPlanarVector< UnitType, NumericType >::value.
operator=() [1/3]
template<typename NumericType = double> constexpr PlanarTraction< NumericType > & PhQ::PlanarTraction< NumericType >::operator= (const PlanarTraction< NumericType > & other) constexpr default
Copy assignment operator. Assigns this planar traction vector by copying another one.
operator=() [2/3]
template<typename NumericType = double> template<typename OtherNumericType > constexpr PlanarTraction< NumericType > & PhQ::PlanarTraction< NumericType >::operator= (const PlanarTraction< OtherNumericType > & other) inline constexpr
Copy assignment operator. Assigns this planar traction vector by copying another one.
Definition at line 109 of file PlanarTraction.hpp.
References PhQ::DimensionalPlanarVector< UnitType, NumericType >::Value(), and PhQ::DimensionalPlanarVector< UnitType, NumericType >::value.
operator=() [3/3]
template<typename NumericType = double> constexpr PlanarTraction< NumericType > & PhQ::PlanarTraction< NumericType >::operator= (PlanarTraction< NumericType > && other) constexpr default noexcept
Move assignment operator. Assigns this planar traction vector by moving another one.
PlanarDirection()
template<typename NumericType = double> PhQ::PlanarDirection< NumericType > PhQ::PlanarTraction< NumericType >::PlanarDirection () const inline
Returns the direction of this planar traction vector.
Definition at line 168 of file PlanarTraction.hpp.
References PhQ::DimensionalPlanarVector< UnitType, NumericType >::value.
Print() [1/2]
template<typename UnitType , typename NumericType = double> std::string PhQ::DimensionalPlanarVector< UnitType, NumericType >::Print () const inline inherited
Prints this physical quantity as a string. This physical quantity's value is expressed in its standard unit of measure.
Definition at line 91 of file DimensionalPlanarVector.hpp.
References PhQ::Abbreviation(), and PhQ::DimensionalPlanarVector< UnitType, NumericType >::value.
Referenced by PhQ::operator<<(), PhQ::operator<<(), PhQ::operator<<(), PhQ::operator<<(), PhQ::operator<<(), PhQ::operator<<(), PhQ::operator<<(), and PhQ::operator<<().
Print() [2/2]
template<typename UnitType , typename NumericType = double> std::string PhQ::DimensionalPlanarVector< UnitType, NumericType >::Print (const UnitType unit) const inline inherited
Prints this physical quantity as a string. This physical quantity's value is expressed in the given unit of measure.
Definition at line 97 of file DimensionalPlanarVector.hpp.
References PhQ::Abbreviation(), and PhQ::DimensionalPlanarVector< UnitType, NumericType >::Value().
SetValue()
template<typename UnitType , typename NumericType = double> constexpr void PhQ::DimensionalPlanarVector< UnitType, NumericType >::SetValue (const PhQ::PlanarVector< NumericType > & value) inline constexpr noexcept inherited
Sets the value of this physical quantity expressed in its standard unit of measure to the given value.
Definition at line 85 of file DimensionalPlanarVector.hpp.
References PhQ::DimensionalPlanarVector< UnitType, NumericType >::value.
StaticValue()
template<typename UnitType , typename NumericType = double> template<UnitType NewUnit> constexpr PhQ::PlanarVector< NumericType > PhQ::DimensionalPlanarVector< UnitType, NumericType >::StaticValue () const inline constexpr inherited
Value of this physical quantity expressed in a given unit of measure. This method can be evaluated statically at compile-time.
Definition at line 73 of file DimensionalPlanarVector.hpp.
References PhQ::DimensionalPlanarVector< UnitType, NumericType >::value.
Unit()
template<typename UnitType , typename NumericType = double> static constexpr UnitType PhQ::DimensionalPlanarVector< UnitType, NumericType >::Unit () inline static constexpr inherited
Standard unit of measure for this physical quantity. This physical quantity's value is stored internally in this unit of measure.
Definition at line 56 of file DimensionalPlanarVector.hpp.
Value() [1/2]
template<typename UnitType , typename NumericType = double> constexpr const PhQ::PlanarVector< NumericType > & PhQ::DimensionalPlanarVector< UnitType, NumericType >::Value () const inline constexpr noexcept inherited
Value of this physical quantity expressed in its standard unit of measure.
Definition at line 61 of file DimensionalPlanarVector.hpp.
References PhQ::DimensionalPlanarVector< UnitType, NumericType >::value.
Referenced by PhQ::Acceleration< NumericType >::Acceleration(), PhQ::Displacement< NumericType >::Displacement(), PhQ::Force< NumericType >::Force(), PhQ::HeatFlux< NumericType >::HeatFlux(), PhQ::DimensionalPlanarVector< UnitType, NumericType >::JSON(), PhQ::PlanarPosition< NumericType >::operator+(), PhQ::PlanarDisplacement< NumericType >::operator+(), PhQ::PlanarPosition< NumericType >::operator-(), PhQ::PlanarDisplacement< NumericType >::operator-(), PhQ::DimensionalPlanarVector< UnitType, NumericType >::operator=(), PhQ::PlanarAcceleration< NumericType >::operator=(), PhQ::PlanarDisplacement< NumericType >::operator=(), PhQ::PlanarForce< NumericType >::operator=(), PhQ::PlanarHeatFlux< NumericType >::operator=(), PhQ::PlanarPosition< NumericType >::operator=(), PhQ::PlanarTemperatureGradient< NumericType >::operator=(), PhQ::PlanarTraction< NumericType >::operator=(), PhQ::PlanarVelocity< NumericType >::operator=(), PhQ::operator==(), PhQ::operator==(), PhQ::PlanarHeatFlux< NumericType >::PlanarHeatFlux(), PhQ::Position< NumericType >::Position(), PhQ::DimensionalPlanarVector< UnitType, NumericType >::Print(), PhQ::TemperatureGradient< NumericType >::TemperatureGradient(), PhQ::Traction< NumericType >::Traction(), PhQ::Velocity< NumericType >::Velocity(), PhQ::DimensionalPlanarVector< UnitType, NumericType >::XML(), and PhQ::DimensionalPlanarVector< UnitType, NumericType >::YAML().
Value() [2/2]
template<typename UnitType , typename NumericType = double> PhQ::PlanarVector< NumericType > PhQ::DimensionalPlanarVector< UnitType, NumericType >::Value (const UnitType unit) const inline inherited
Value of this physical quantity expressed in a given unit of measure.
Definition at line 66 of file DimensionalPlanarVector.hpp.
References PhQ::Convert(), and PhQ::DimensionalPlanarVector< UnitType, NumericType >::value.
x()
template<typename NumericType = double> constexpr ScalarTraction< NumericType > PhQ::PlanarTraction< NumericType >::x () const inline constexpr noexcept
Returns the x Cartesian component of this planar traction vector.
Definition at line 153 of file PlanarTraction.hpp.
References PhQ::DimensionalPlanarVector< UnitType, NumericType >::value.
Referenced by PhQ::PlanarTraction< NumericType >::Create(), and PhQ::PlanarTraction< NumericType >::PlanarTraction().
XML() [1/2]
template<typename UnitType , typename NumericType = double> std::string PhQ::DimensionalPlanarVector< UnitType, NumericType >::XML () const inline inherited
Serializes this physical quantity as an XML message. This physical quantity's value is expressed in its standard unit of measure.
Definition at line 123 of file DimensionalPlanarVector.hpp.
References PhQ::Abbreviation(), and PhQ::DimensionalPlanarVector< UnitType, NumericType >::value.
Referenced by PhQ::DimensionalPlanarVector< UnitType, NumericType >::XML().
XML() [2/2]
template<typename UnitType , typename NumericType = double> std::string PhQ::DimensionalPlanarVector< UnitType, NumericType >::XML (const UnitType unit) const inline inherited
Serializes this physical quantity as an XML message. This physical quantity's value is expressed in the given unit of measure.
Definition at line 133 of file DimensionalPlanarVector.hpp.
References PhQ::Abbreviation(), PhQ::DimensionalPlanarVector< UnitType, NumericType >::Value(), and PhQ::DimensionalPlanarVector< UnitType, NumericType >::XML().
y()
template<typename NumericType = double> constexpr ScalarTraction< NumericType > PhQ::PlanarTraction< NumericType >::y () const inline constexpr noexcept
Returns the y Cartesian component of this planar traction vector.
Definition at line 158 of file PlanarTraction.hpp.
References PhQ::DimensionalPlanarVector< UnitType, NumericType >::value.
Referenced by PhQ::PlanarTraction< NumericType >::Create(), and PhQ::PlanarTraction< NumericType >::PlanarTraction().
YAML() [1/2]
template<typename UnitType , typename NumericType = double> std::string PhQ::DimensionalPlanarVector< UnitType, NumericType >::YAML () const inline inherited
Serializes this physical quantity as a YAML message. This physical quantity's value is expressed in its standard unit of measure.
Definition at line 143 of file DimensionalPlanarVector.hpp.
References PhQ::Abbreviation(), and PhQ::DimensionalPlanarVector< UnitType, NumericType >::value.
Referenced by PhQ::DimensionalPlanarVector< UnitType, NumericType >::YAML().
YAML() [2/2]
template<typename UnitType , typename NumericType = double> std::string PhQ::DimensionalPlanarVector< UnitType, NumericType >::YAML (const UnitType unit) const inline inherited
Serializes this physical quantity as a YAML message. This physical quantity's value is expressed in the given unit of measure.
Definition at line 153 of file DimensionalPlanarVector.hpp.
References PhQ::Abbreviation(), PhQ::DimensionalPlanarVector< UnitType, NumericType >::Value(), and PhQ::DimensionalPlanarVector< UnitType, NumericType >::YAML().
Zero()
template<typename NumericType = double> static constexpr PlanarTraction< NumericType > PhQ::PlanarTraction< NumericType >::Zero () inline static constexpr
Statically creates a planar traction vector of zero.
Definition at line 119 of file PlanarTraction.hpp.
References PhQ::PlanarVector< NumericType >::Zero().
Member Data Documentation
value
template<typename UnitType , typename NumericType = double> PhQ::PlanarVector<NumericType> PhQ::DimensionalPlanarVector< UnitType, NumericType >::value protected inherited
Value of this physical quantity expressed in its standard unit of measure.
Definition at line 222 of file DimensionalPlanarVector.hpp.
Referenced by PhQ::PlanarAcceleration< NumericType >::Create(), PhQ::PlanarDisplacement< NumericType >::Create(), PhQ::PlanarForce< NumericType >::Create(), PhQ::PlanarHeatFlux< NumericType >::Create(), PhQ::PlanarPosition< NumericType >::Create(), PhQ::PlanarTemperatureGradient< NumericType >::Create(), PhQ::PlanarTraction< NumericType >::Create(), PhQ::PlanarVelocity< NumericType >::Create(), PhQ::DimensionalPlanarVector< UnitType, NumericType >::JSON(), PhQ::PlanarAcceleration< NumericType >::Magnitude(), PhQ::PlanarDisplacement< NumericType >::Magnitude(), PhQ::PlanarForce< NumericType >::Magnitude(), PhQ::PlanarHeatFlux< NumericType >::Magnitude(), PhQ::PlanarPosition< NumericType >::Magnitude(), PhQ::PlanarTemperatureGradient< NumericType >::Magnitude(), PhQ::PlanarTraction< NumericType >::Magnitude(), PhQ::PlanarVelocity< NumericType >::Magnitude(), PhQ::DimensionalPlanarVector< UnitType, NumericType >::MutableValue(), PhQ::PlanarAcceleration< NumericType >::operator*(), PhQ::PlanarDisplacement< NumericType >::operator*(), PhQ::PlanarForce< NumericType >::operator*(), PhQ::PlanarHeatFlux< NumericType >::operator*(), PhQ::PlanarPosition< NumericType >::operator*(), PhQ::PlanarTemperatureGradient< NumericType >::operator*(), PhQ::PlanarTraction< NumericType >::operator*(), PhQ::PlanarVelocity< NumericType >::operator*(), PhQ::PlanarAcceleration< NumericType >::operator*=(), PhQ::PlanarDisplacement< NumericType >::operator*=(), PhQ::PlanarForce< NumericType >::operator*=(), PhQ::PlanarHeatFlux< NumericType >::operator*=(), PhQ::PlanarPosition< NumericType >::operator*=(), PhQ::PlanarTemperatureGradient< NumericType >::operator*=(), PhQ::PlanarTraction< NumericType >::operator*=(), PhQ::PlanarVelocity< NumericType >::operator*=(), PhQ::PlanarAcceleration< NumericType >::operator+(), PhQ::PlanarDisplacement< NumericType >::operator+(), PhQ::PlanarPosition< NumericType >::operator+(), PhQ::PlanarForce< NumericType >::operator+(), PhQ::PlanarHeatFlux< NumericType >::operator+(), PhQ::PlanarPosition< NumericType >::operator+(), PhQ::PlanarTemperatureGradient< NumericType >::operator+(), PhQ::PlanarTraction< NumericType >::operator+(), PhQ::PlanarVelocity< NumericType >::operator+(), PhQ::PlanarAcceleration< NumericType >::operator+=(), PhQ::PlanarDisplacement< NumericType >::operator+=(), PhQ::PlanarPosition< NumericType >::operator+=(), PhQ::PlanarForce< NumericType >::operator+=(), PhQ::PlanarHeatFlux< NumericType >::operator+=(), PhQ::PlanarPosition< NumericType >::operator+=(), PhQ::PlanarTemperatureGradient< NumericType >::operator+=(), PhQ::PlanarTraction< NumericType >::operator+=(), PhQ::PlanarVelocity< NumericType >::operator+=(), PhQ::PlanarAcceleration< NumericType >::operator-(), PhQ::PlanarDisplacement< NumericType >::operator-(), PhQ::PlanarPosition< NumericType >::operator-(), PhQ::PlanarForce< NumericType >::operator-(), PhQ::PlanarHeatFlux< NumericType >::operator-(), PhQ::PlanarPosition< NumericType >::operator-(), PhQ::PlanarTemperatureGradient< NumericType >::operator-(), PhQ::PlanarTraction< NumericType >::operator-(), PhQ::PlanarVelocity< NumericType >::operator-(), PhQ::PlanarAcceleration< NumericType >::operator-=(), PhQ::PlanarDisplacement< NumericType >::operator-=(), PhQ::PlanarPosition< NumericType >::operator-=(), PhQ::PlanarForce< NumericType >::operator-=(), PhQ::PlanarHeatFlux< NumericType >::operator-=(), PhQ::PlanarPosition< NumericType >::operator-=(), PhQ::PlanarTemperatureGradient< NumericType >::operator-=(), PhQ::PlanarTraction< NumericType >::operator-=(), PhQ::PlanarVelocity< NumericType >::operator-=(), PhQ::PlanarAcceleration< NumericType >::operator/(), PhQ::PlanarDisplacement< NumericType >::operator/(), PhQ::PlanarForce< NumericType >::operator/(), PhQ::PlanarHeatFlux< NumericType >::operator/(), PhQ::PlanarPosition< NumericType >::operator/(), PhQ::PlanarTemperatureGradient< NumericType >::operator/(), PhQ::PlanarTraction< NumericType >::operator/(), PhQ::PlanarVelocity< NumericType >::operator/(), PhQ::PlanarAcceleration< NumericType >::operator/=(), PhQ::PlanarDisplacement< NumericType >::operator/=(), PhQ::PlanarForce< NumericType >::operator/=(), PhQ::PlanarHeatFlux< NumericType >::operator/=(), PhQ::PlanarPosition< NumericType >::operator/=(), PhQ::PlanarTemperatureGradient< NumericType >::operator/=(), PhQ::PlanarTraction< NumericType >::operator/=(), PhQ::PlanarVelocity< NumericType >::operator/=(), PhQ::DimensionalPlanarVector< UnitType, NumericType >::operator=(), PhQ::PlanarAcceleration< NumericType >::operator=(), PhQ::PlanarDisplacement< NumericType >::operator=(), PhQ::PlanarForce< NumericType >::operator=(), PhQ::PlanarHeatFlux< NumericType >::operator=(), PhQ::PlanarPosition< NumericType >::operator=(), PhQ::PlanarTemperatureGradient< NumericType >::operator=(), PhQ::PlanarTraction< NumericType >::operator=(), PhQ::PlanarVelocity< NumericType >::operator=(), PhQ::PlanarAcceleration< NumericType >::PlanarDirection(), PhQ::PlanarDisplacement< NumericType >::PlanarDirection(), PhQ::PlanarForce< NumericType >::PlanarDirection(), PhQ::PlanarHeatFlux< NumericType >::PlanarDirection(), PhQ::PlanarPosition< NumericType >::PlanarDirection(), PhQ::PlanarTemperatureGradient< NumericType >::PlanarDirection(), PhQ::PlanarTraction< NumericType >::PlanarDirection(), PhQ::PlanarVelocity< NumericType >::PlanarDirection(), PhQ::DimensionalPlanarVector< UnitType, NumericType >::Print(), PhQ::DimensionalPlanarVector< UnitType, NumericType >::SetValue(), PhQ::DimensionalPlanarVector< UnitType, NumericType >::StaticValue(), PhQ::DimensionalPlanarVector< UnitType, NumericType >::Value(), PhQ::DimensionalPlanarVector< UnitType, NumericType >::Value(), PhQ::PlanarAcceleration< NumericType >::x(), PhQ::PlanarDisplacement< NumericType >::x(), PhQ::PlanarForce< NumericType >::x(), PhQ::PlanarHeatFlux< NumericType >::x(), PhQ::PlanarPosition< NumericType >::x(), PhQ::PlanarTemperatureGradient< NumericType >::x(), PhQ::PlanarTraction< NumericType >::x(), PhQ::PlanarVelocity< NumericType >::x(), PhQ::DimensionalPlanarVector< UnitType, NumericType >::XML(), PhQ::PlanarAcceleration< NumericType >::y(), PhQ::PlanarDisplacement< NumericType >::y(), PhQ::PlanarForce< NumericType >::y(), PhQ::PlanarHeatFlux< NumericType >::y(), PhQ::PlanarPosition< NumericType >::y(), PhQ::PlanarTemperatureGradient< NumericType >::y(), PhQ::PlanarTraction< NumericType >::y(), PhQ::PlanarVelocity< NumericType >::y(), PhQ::DimensionalPlanarVector< UnitType, NumericType >::YAML(), and PhQ::PlanarDisplacement< NumericType >::z().
The documentation for this class was generated from the following files:
PhQ/Angle.hpp
PhQ/PlanarTraction.hpp
PhQ/Stress.hpp
PhQ/Traction.hpp