Physical Quantities: PhQ::Force< NumericType > Class Template Reference
PhQ::Force< NumericType > Class Template Reference
Three-dimensional Euclidean force vector. Contains three components in Cartesian coordinates: x, y, and z. For a two-dimensional Euclidean force vector in the XY plane, see PhQ::PlanarForce. For scalar force components or for the magnitude of a force vector, see PhQ::ScalarForce.
#include "Force.hpp"
Public Member Functions
Force ()=default
Default constructor. Constructs a force vector with an uninitialized value.
Force (const Vector< NumericType > &value, const Unit::Force unit)
Constructor. Constructs a force vector with a given value expressed in a given force unit.
Force (const ScalarForce< NumericType > &x, const ScalarForce< NumericType > &y, const ScalarForce< NumericType > &z)
Constructor. Constructs a force vector from a given set of scalar force components.
constexpr Force (const ScalarForce< NumericType > &scalar_force, const Direction< NumericType > &direction)
Constructor. Constructs a force vector from a given scalar force magnitude and direction.
constexpr Force (const PlanarForce< NumericType > &planar_force)
Constructor. Constructs a force vector from a given planar force vector in the XY plane. This force vector's z-component is initialized to zero.
constexpr Force (const Traction< NumericType > &traction, const Area< NumericType > &area)
Constructor. Constructs a force vector from a given traction and area using the definition of traction.
~Force () noexcept=default
Destructor. Destroys this force vector.
constexpr Force (const Force< NumericType > &other)=default
Copy constructor. Constructs a force vector by copying another one.
template<typename OtherNumericType >
constexpr Force (const Force< OtherNumericType > &other)
Copy constructor. Constructs a force vector by copying another one.
constexpr Force (Force< NumericType > &&other) noexcept=default
Move constructor. Constructs a force vector by moving another one.
constexpr Force< NumericType > & operator= (const Force< NumericType > &other)=default
Copy assignment operator. Assigns this force vector by copying another one.
template<typename OtherNumericType >
constexpr Force< NumericType > & operator= (const Force< OtherNumericType > &other)
Copy assignment operator. Assigns this force vector by copying another one.
constexpr Force< NumericType > & operator= (Force< NumericType > &&other) noexcept=default
Move assignment operator. Assigns this force vector by moving another one.
constexpr ScalarForce< NumericType > x () const noexcept
Returns the x Cartesian component of this force vector.
constexpr ScalarForce< NumericType > y () const noexcept
Returns the y Cartesian component of this force vector.
constexpr ScalarForce< NumericType > z () const noexcept
Returns the z Cartesian component of this force vector.
ScalarForce< NumericType > Magnitude () const
Returns the magnitude of this force vector.
PhQ::Direction< NumericType > Direction () const
Returns the direction of this force vector.
PhQ::Angle< NumericType > Angle (const Force< NumericType > &force) const
Returns the angle between this force vector and another one.
constexpr Force< NumericType > operator+ (const Force< NumericType > &force) const
constexpr Force< NumericType > operator- (const Force< NumericType > &force) const
constexpr Force< NumericType > operator* (const NumericType number) const
constexpr Force< NumericType > operator/ (const NumericType number) const
constexpr Traction< NumericType > operator/ (const Area< NumericType > &area) const
constexpr void operator+= (const Force< NumericType > &force) noexcept
constexpr void operator-= (const Force< NumericType > &force) noexcept
constexpr void operator*= (const NumericType number) noexcept
constexpr void operator/= (const NumericType number) noexcept
constexpr const PhQ::Vector< NumericType > & Value () const noexcept
Value of this physical quantity expressed in its standard unit of measure.
PhQ::Vector< NumericType > Value (const UnitType unit) const
Value of this physical quantity expressed in a given unit of measure.
template<UnitType NewUnit>
constexpr PhQ::Vector< NumericType > StaticValue () const
Value of this physical quantity expressed in a given unit of measure. This method can be evaluated statically at compile-time.
constexpr PhQ::Vector< NumericType > & MutableValue () noexcept
Returns the value of this physical quantity expressed in its standard unit of measure as a mutable value.
constexpr void SetValue (const PhQ::Vector< NumericType > &value) noexcept
Sets the value of this physical quantity expressed in its standard unit of measure to the given value.
std::string Print () const
Prints this physical quantity as a string. This physical quantity's value is expressed in its standard unit of measure.
std::string Print (const UnitType unit) const
Prints this physical quantity as a string. This physical quantity's value is expressed in the given unit of measure.
std::string JSON () const
Serializes this physical quantity as a JSON message. This physical quantity's value is expressed in its standard unit of measure.
std::string JSON (const UnitType unit) const
Serializes this physical quantity as a JSON message. This physical quantity's value is expressed in the given unit of measure.
std::string XML () const
Serializes this physical quantity as an XML message. This physical quantity's value is expressed in its standard unit of measure.
std::string XML (const UnitType unit) const
Serializes this physical quantity as an XML message. This physical quantity's value is expressed in the given unit of measure.
std::string YAML () const
Serializes this physical quantity as a YAML message. This physical quantity's value is expressed in its standard unit of measure.
std::string YAML (const UnitType unit) const
Serializes this physical quantity as a YAML message. This physical quantity's value is expressed in the given unit of measure.
Static Public Member Functions
static constexpr Force< NumericType > Zero ()
Statically creates a force vector of zero.
template<Unit::Force Unit>
static constexpr Force< NumericType > Create (const NumericType x, const NumericType y, const NumericType z)
Statically creates a force vector from the given x, y, and z Cartesian components expressed in a given force unit.
template<Unit::Force Unit>
static constexpr Force< NumericType > Create (const std::array< NumericType, 3 > &x_y_z)
Statically creates a force vector from the given x, y, and z Cartesian components expressed in a given force unit.
template<Unit::Force Unit>
static constexpr Force< NumericType > Create (const Vector< NumericType > &value)
Statically creates a force vector with a given value expressed in a given force unit.
static constexpr const PhQ::Dimensions & Dimensions ()
Physical dimension set of this physical quantity.
static constexpr UnitType Unit ()
Standard unit of measure for this physical quantity. This physical quantity's value is stored internally in this unit of measure.
Protected Attributes
PhQ::Vector< NumericType > value
Value of this physical quantity expressed in its standard unit of measure.
Private Member Functions
constexpr Force (const Vector< NumericType > &value)
Constructor. Constructs a force vector with a given value expressed in the standard force unit.
Detailed Description
template<typename NumericType = double>
class PhQ::Force< NumericType >
Three-dimensional Euclidean force vector. Contains three components in Cartesian coordinates: x, y, and z. For a two-dimensional Euclidean force vector in the XY plane, see PhQ::PlanarForce. For scalar force components or for the magnitude of a force vector, see PhQ::ScalarForce.
Definition at line 52 of file Force.hpp.
Constructor & Destructor Documentation
Force() [1/10]
template<typename NumericType = double> PhQ::Force< NumericType >::Force () default
Default constructor. Constructs a force vector with an uninitialized value.
Force() [2/10]
template<typename NumericType = double> PhQ::Force< NumericType >::Force (const Vector< NumericType > & value, const Unit::Force< NumericType > unit) inline
Constructor. Constructs a force vector with a given value expressed in a given force unit.
Definition at line 59 of file Force.hpp.
Force() [3/10]
template<typename NumericType = double> PhQ::Force< NumericType >::Force (const ScalarForce< NumericType > & x, const ScalarForce< NumericType > & y, const ScalarForce< NumericType > & z) inline
Constructor. Constructs a force vector from a given set of scalar force components.
Definition at line 63 of file Force.hpp.
References PhQ::Force< NumericType >::x(), PhQ::Force< NumericType >::y(), and PhQ::Force< NumericType >::z().
Force() [4/10]
template<typename NumericType = double> constexpr PhQ::Force< NumericType >::Force (const ScalarForce< NumericType > & scalar_force, const Direction< NumericType > & direction) inline constexpr
Constructor. Constructs a force vector from a given scalar force magnitude and direction.
Definition at line 69 of file Force.hpp.
Force() [5/10]
template<typename NumericType = double> constexpr PhQ::Force< NumericType >::Force (const PlanarForce< NumericType > & planar_force) inline explicit constexpr
Constructor. Constructs a force vector from a given planar force vector in the XY plane. This force vector's z-component is initialized to zero.
Definition at line 75 of file Force.hpp.
References PhQ::DimensionalPlanarVector< UnitType, NumericType >::Value().
Force() [6/10]
template<typename NumericType > constexpr PhQ::Force< NumericType >::Force (const Traction< NumericType > & traction, const Area< NumericType > & area) inline constexpr
Constructor. Constructs a force vector from a given traction and area using the definition of traction.
Definition at line 278 of file Traction.hpp.
~Force()
template<typename NumericType = double> PhQ::Force< NumericType >::~Force () default noexcept
Destructor. Destroys this force vector.
Force() [7/10]
template<typename NumericType = double> constexpr PhQ::Force< NumericType >::Force (const Force< NumericType > & other) constexpr default
Copy constructor. Constructs a force vector by copying another one.
Force() [8/10]
template<typename NumericType = double> template<typename OtherNumericType > constexpr PhQ::Force< NumericType >::Force (const Force< OtherNumericType > & other) inline explicit constexpr
Copy constructor. Constructs a force vector by copying another one.
Definition at line 90 of file Force.hpp.
Force() [9/10]
template<typename NumericType = double> constexpr PhQ::Force< NumericType >::Force (Force< NumericType > && other) constexpr default noexcept
Move constructor. Constructs a force vector by moving another one.
Force() [10/10]
template<typename NumericType = double> constexpr PhQ::Force< NumericType >::Force (const Vector< NumericType > & value) inline explicit constexpr private
Constructor. Constructs a force vector with a given value expressed in the standard force unit.
Definition at line 205 of file Force.hpp.
Member Function Documentation
Angle()
template<typename NumericType = double> PhQ::Angle< NumericType > PhQ::Force< NumericType >::Angle (const Force< NumericType > & force) const inline
Returns the angle between this force vector and another one.
Definition at line 164 of file Force.hpp.
Create() [1/3]
template<typename NumericType = double> template<Unit::Force Unit> static constexpr Force< NumericType > PhQ::Force< NumericType >::Create (const NumericType x, const NumericType y, const NumericType z) inline static constexpr
Statically creates a force vector from the given x, y, and z Cartesian components expressed in a given force unit.
Definition at line 117 of file Force.hpp.
References PhQ::Force< NumericType >::x(), PhQ::Force< NumericType >::y(), and PhQ::Force< NumericType >::z().
Create() [2/3]
template<typename NumericType = double> template<Unit::Force Unit> static constexpr Force< NumericType > PhQ::Force< NumericType >::Create (const std::array< NumericType, 3 > & x_y_z) inline static constexpr
Statically creates a force vector from the given x, y, and z Cartesian components expressed in a given force unit.
Definition at line 126 of file Force.hpp.
Create() [3/3]
template<typename NumericType = double> template<Unit::Force Unit> static constexpr Force< NumericType > PhQ::Force< NumericType >::Create (const Vector< NumericType > & value) inline static constexpr
Statically creates a force vector with a given value expressed in a given force unit.
Definition at line 134 of file Force.hpp.
References PhQ::DimensionalVector< UnitType, NumericType >::value.
Dimensions()
template<typename UnitType , typename NumericType = double> static constexpr const PhQ::Dimensions & PhQ::DimensionalVector< UnitType, NumericType >::Dimensions () inline static constexpr inherited
Physical dimension set of this physical quantity.
Definition at line 50 of file DimensionalVector.hpp.
Direction()
template<typename NumericType = double> PhQ::Direction< NumericType > PhQ::Force< NumericType >::Direction () const inline
Returns the direction of this force vector.
Definition at line 159 of file Force.hpp.
References PhQ::DimensionalVector< UnitType, NumericType >::value.
JSON() [1/2]
template<typename UnitType , typename NumericType = double> std::string PhQ::DimensionalVector< UnitType, NumericType >::JSON () const inline inherited
Serializes this physical quantity as a JSON message. This physical quantity's value is expressed in its standard unit of measure.
Definition at line 103 of file DimensionalVector.hpp.
References PhQ::Abbreviation(), and PhQ::DimensionalVector< UnitType, NumericType >::value.
Referenced by PhQ::DimensionalVector< UnitType, NumericType >::JSON().
JSON() [2/2]
template<typename UnitType , typename NumericType = double> std::string PhQ::DimensionalVector< UnitType, NumericType >::JSON (const UnitType unit) const inline inherited
Serializes this physical quantity as a JSON message. This physical quantity's value is expressed in the given unit of measure.
Definition at line 113 of file DimensionalVector.hpp.
References PhQ::Abbreviation(), PhQ::DimensionalVector< UnitType, NumericType >::JSON(), and PhQ::DimensionalVector< UnitType, NumericType >::Value().
Magnitude()
template<typename NumericType = double> ScalarForce< NumericType > PhQ::Force< NumericType >::Magnitude () const inline
Returns the magnitude of this force vector.
Definition at line 154 of file Force.hpp.
References PhQ::DimensionalVector< UnitType, NumericType >::value.
MutableValue()
template<typename UnitType , typename NumericType = double> constexpr PhQ::Vector< NumericType > & PhQ::DimensionalVector< UnitType, NumericType >::MutableValue () inline constexpr noexcept inherited
Returns the value of this physical quantity expressed in its standard unit of measure as a mutable value.
Definition at line 79 of file DimensionalVector.hpp.
References PhQ::DimensionalVector< UnitType, NumericType >::value.
operator*()
template<typename NumericType = double> constexpr Force< NumericType > PhQ::Force< NumericType >::operator* (const NumericType number) const inline constexpr
Definition at line 176 of file Force.hpp.
References PhQ::DimensionalVector< UnitType, NumericType >::value.
operator*=()
template<typename NumericType = double> constexpr void PhQ::Force< NumericType >::operator*= (const NumericType number) inline constexpr noexcept
Definition at line 194 of file Force.hpp.
References PhQ::DimensionalVector< UnitType, NumericType >::value.
operator+()
template<typename NumericType = double> constexpr Force< NumericType > PhQ::Force< NumericType >::operator+ (const Force< NumericType > & force) const inline constexpr
Definition at line 168 of file Force.hpp.
References PhQ::DimensionalVector< UnitType, NumericType >::value.
operator+=()
template<typename NumericType = double> constexpr void PhQ::Force< NumericType >::operator+= (const Force< NumericType > & force) inline constexpr noexcept
Definition at line 186 of file Force.hpp.
References PhQ::DimensionalVector< UnitType, NumericType >::value.
operator-()
template<typename NumericType = double> constexpr Force< NumericType > PhQ::Force< NumericType >::operator- (const Force< NumericType > & force) const inline constexpr
Definition at line 172 of file Force.hpp.
References PhQ::DimensionalVector< UnitType, NumericType >::value.
operator-=()
template<typename NumericType = double> constexpr void PhQ::Force< NumericType >::operator-= (const Force< NumericType > & force) inline constexpr noexcept
Definition at line 190 of file Force.hpp.
References PhQ::DimensionalVector< UnitType, NumericType >::value.
operator/() [1/2]
template<typename NumericType > constexpr Traction< NumericType > PhQ::Force< NumericType >::operator/ (const Area< NumericType > & area) const inline constexpr
Definition at line 295 of file Traction.hpp.
operator/() [2/2]
template<typename NumericType = double> constexpr Force< NumericType > PhQ::Force< NumericType >::operator/ (const NumericType number) const inline constexpr
Definition at line 180 of file Force.hpp.
References PhQ::DimensionalVector< UnitType, NumericType >::value.
operator/=()
template<typename NumericType = double> constexpr void PhQ::Force< NumericType >::operator/= (const NumericType number) inline constexpr noexcept
Definition at line 198 of file Force.hpp.
References PhQ::DimensionalVector< UnitType, NumericType >::value.
operator=() [1/3]
template<typename NumericType = double> constexpr Force< NumericType > & PhQ::Force< NumericType >::operator= (const Force< NumericType > & other) constexpr default
Copy assignment operator. Assigns this force vector by copying another one.
operator=() [2/3]
template<typename NumericType = double> template<typename OtherNumericType > constexpr Force< NumericType > & PhQ::Force< NumericType >::operator= (const Force< OtherNumericType > & other) inline constexpr
Copy assignment operator. Assigns this force vector by copying another one.
Definition at line 101 of file Force.hpp.
References PhQ::DimensionalVector< UnitType, NumericType >::Value(), and PhQ::DimensionalVector< UnitType, NumericType >::value.
operator=() [3/3]
template<typename NumericType = double> constexpr Force< NumericType > & PhQ::Force< NumericType >::operator= (Force< NumericType > && other) constexpr default noexcept
Move assignment operator. Assigns this force vector by moving another one.
Print() [1/2]
template<typename UnitType , typename NumericType = double> std::string PhQ::DimensionalVector< UnitType, NumericType >::Print () const inline inherited
Prints this physical quantity as a string. This physical quantity's value is expressed in its standard unit of measure.
Definition at line 91 of file DimensionalVector.hpp.
References PhQ::Abbreviation(), and PhQ::DimensionalVector< UnitType, NumericType >::value.
Referenced by PhQ::operator<<(), PhQ::operator<<(), PhQ::operator<<(), PhQ::operator<<(), PhQ::operator<<(), PhQ::operator<<(), PhQ::operator<<(), PhQ::operator<<(), and PhQ::operator<<().
Print() [2/2]
template<typename UnitType , typename NumericType = double> std::string PhQ::DimensionalVector< UnitType, NumericType >::Print (const UnitType unit) const inline inherited
Prints this physical quantity as a string. This physical quantity's value is expressed in the given unit of measure.
Definition at line 97 of file DimensionalVector.hpp.
References PhQ::Abbreviation(), and PhQ::DimensionalVector< UnitType, NumericType >::Value().
SetValue()
template<typename UnitType , typename NumericType = double> constexpr void PhQ::DimensionalVector< UnitType, NumericType >::SetValue (const PhQ::Vector< NumericType > & value) inline constexpr noexcept inherited
Sets the value of this physical quantity expressed in its standard unit of measure to the given value.
Definition at line 85 of file DimensionalVector.hpp.
References PhQ::DimensionalVector< UnitType, NumericType >::value.
StaticValue()
template<typename UnitType , typename NumericType = double> template<UnitType NewUnit> constexpr PhQ::Vector< NumericType > PhQ::DimensionalVector< UnitType, NumericType >::StaticValue () const inline constexpr inherited
Value of this physical quantity expressed in a given unit of measure. This method can be evaluated statically at compile-time.
Definition at line 73 of file DimensionalVector.hpp.
References PhQ::DimensionalVector< UnitType, NumericType >::value.
Unit()
template<typename UnitType , typename NumericType = double> static constexpr UnitType PhQ::DimensionalVector< UnitType, NumericType >::Unit () inline static constexpr inherited
Standard unit of measure for this physical quantity. This physical quantity's value is stored internally in this unit of measure.
Definition at line 56 of file DimensionalVector.hpp.
Value() [1/2]
template<typename UnitType , typename NumericType = double> constexpr const PhQ::Vector< NumericType > & PhQ::DimensionalVector< UnitType, NumericType >::Value () const inline constexpr noexcept inherited
Value of this physical quantity expressed in its standard unit of measure.
Definition at line 61 of file DimensionalVector.hpp.
References PhQ::DimensionalVector< UnitType, NumericType >::value.
Referenced by PhQ::DimensionalVector< UnitType, NumericType >::JSON(), PhQ::Position< NumericType >::operator+(), PhQ::Displacement< NumericType >::operator+(), PhQ::Position< NumericType >::operator-(), PhQ::Displacement< NumericType >::operator-(), PhQ::Acceleration< NumericType >::operator=(), PhQ::DimensionalVector< UnitType, NumericType >::operator=(), PhQ::Displacement< NumericType >::operator=(), PhQ::Force< NumericType >::operator=(), PhQ::HeatFlux< NumericType >::operator=(), PhQ::Position< NumericType >::operator=(), PhQ::TemperatureGradient< NumericType >::operator=(), PhQ::Traction< NumericType >::operator=(), PhQ::VectorArea< NumericType >::operator=(), PhQ::Velocity< NumericType >::operator=(), PhQ::operator==(), PhQ::operator==(), PhQ::operator==(), PhQ::operator==(), PhQ::operator==(), PhQ::operator==(), PhQ::operator==(), PhQ::operator==(), PhQ::operator==(), PhQ::operator==(), PhQ::operator==(), PhQ::operator==(), PhQ::operator==(), PhQ::operator==(), PhQ::operator==(), PhQ::operator==(), PhQ::PlanarAcceleration< NumericType >::PlanarAcceleration(), PhQ::PlanarDisplacement< NumericType >::PlanarDisplacement(), PhQ::PlanarForce< NumericType >::PlanarForce(), PhQ::PlanarHeatFlux< NumericType >::PlanarHeatFlux(), PhQ::PlanarPosition< NumericType >::PlanarPosition(), PhQ::PlanarTemperatureGradient< NumericType >::PlanarTemperatureGradient(), PhQ::PlanarTraction< NumericType >::PlanarTraction(), PhQ::PlanarVelocity< NumericType >::PlanarVelocity(), PhQ::DimensionalVector< UnitType, NumericType >::Print(), PhQ::DimensionalVector< UnitType, NumericType >::XML(), and PhQ::DimensionalVector< UnitType, NumericType >::YAML().
Value() [2/2]
template<typename UnitType , typename NumericType = double> PhQ::Vector< NumericType > PhQ::DimensionalVector< UnitType, NumericType >::Value (const UnitType unit) const inline inherited
Value of this physical quantity expressed in a given unit of measure.
Definition at line 66 of file DimensionalVector.hpp.
References PhQ::Convert(), and PhQ::DimensionalVector< UnitType, NumericType >::value.
x()
template<typename NumericType = double> constexpr ScalarForce< NumericType > PhQ::Force< NumericType >::x () const inline constexpr noexcept
Returns the x Cartesian component of this force vector.
Definition at line 139 of file Force.hpp.
References PhQ::DimensionalVector< UnitType, NumericType >::value.
Referenced by PhQ::Force< NumericType >::Create(), and PhQ::Force< NumericType >::Force().
XML() [1/2]
template<typename UnitType , typename NumericType = double> std::string PhQ::DimensionalVector< UnitType, NumericType >::XML () const inline inherited
Serializes this physical quantity as an XML message. This physical quantity's value is expressed in its standard unit of measure.
Definition at line 123 of file DimensionalVector.hpp.
References PhQ::Abbreviation(), and PhQ::DimensionalVector< UnitType, NumericType >::value.
Referenced by PhQ::DimensionalVector< UnitType, NumericType >::XML().
XML() [2/2]
template<typename UnitType , typename NumericType = double> std::string PhQ::DimensionalVector< UnitType, NumericType >::XML (const UnitType unit) const inline inherited
Serializes this physical quantity as an XML message. This physical quantity's value is expressed in the given unit of measure.
Definition at line 133 of file DimensionalVector.hpp.
References PhQ::Abbreviation(), PhQ::DimensionalVector< UnitType, NumericType >::Value(), and PhQ::DimensionalVector< UnitType, NumericType >::XML().
y()
template<typename NumericType = double> constexpr ScalarForce< NumericType > PhQ::Force< NumericType >::y () const inline constexpr noexcept
Returns the y Cartesian component of this force vector.
Definition at line 144 of file Force.hpp.
References PhQ::DimensionalVector< UnitType, NumericType >::value.
Referenced by PhQ::Force< NumericType >::Create(), and PhQ::Force< NumericType >::Force().
YAML() [1/2]
template<typename UnitType , typename NumericType = double> std::string PhQ::DimensionalVector< UnitType, NumericType >::YAML () const inline inherited
Serializes this physical quantity as a YAML message. This physical quantity's value is expressed in its standard unit of measure.
Definition at line 143 of file DimensionalVector.hpp.
References PhQ::Abbreviation(), and PhQ::DimensionalVector< UnitType, NumericType >::value.
Referenced by PhQ::DimensionalVector< UnitType, NumericType >::YAML().
YAML() [2/2]
template<typename UnitType , typename NumericType = double> std::string PhQ::DimensionalVector< UnitType, NumericType >::YAML (const UnitType unit) const inline inherited
Serializes this physical quantity as a YAML message. This physical quantity's value is expressed in the given unit of measure.
Definition at line 153 of file DimensionalVector.hpp.
References PhQ::Abbreviation(), PhQ::DimensionalVector< UnitType, NumericType >::Value(), and PhQ::DimensionalVector< UnitType, NumericType >::YAML().
z()
template<typename NumericType = double> constexpr ScalarForce< NumericType > PhQ::Force< NumericType >::z () const inline constexpr noexcept
Returns the z Cartesian component of this force vector.
Definition at line 149 of file Force.hpp.
References PhQ::DimensionalVector< UnitType, NumericType >::value.
Referenced by PhQ::Force< NumericType >::Create(), and PhQ::Force< NumericType >::Force().
Zero()
template<typename NumericType = double> static constexpr Force< NumericType > PhQ::Force< NumericType >::Zero () inline static constexpr
Statically creates a force vector of zero.
Definition at line 110 of file Force.hpp.
References PhQ::Vector< NumericType >::Zero().
Member Data Documentation
value
template<typename UnitType , typename NumericType = double> PhQ::Vector<NumericType> PhQ::DimensionalVector< UnitType, NumericType >::value protected inherited
Value of this physical quantity expressed in its standard unit of measure.
Definition at line 217 of file DimensionalVector.hpp.
Referenced by PhQ::Acceleration< NumericType >::Create(), PhQ::Displacement< NumericType >::Create(), PhQ::Force< NumericType >::Create(), PhQ::HeatFlux< NumericType >::Create(), PhQ::Position< NumericType >::Create(), PhQ::TemperatureGradient< NumericType >::Create(), PhQ::Traction< NumericType >::Create(), PhQ::VectorArea< NumericType >::Create(), PhQ::Velocity< NumericType >::Create(), PhQ::Acceleration< NumericType >::Direction(), PhQ::Displacement< NumericType >::Direction(), PhQ::Force< NumericType >::Direction(), PhQ::HeatFlux< NumericType >::Direction(), PhQ::Position< NumericType >::Direction(), PhQ::TemperatureGradient< NumericType >::Direction(), PhQ::Traction< NumericType >::Direction(), PhQ::VectorArea< NumericType >::Direction(), PhQ::Velocity< NumericType >::Direction(), PhQ::DimensionalVector< UnitType, NumericType >::JSON(), PhQ::Acceleration< NumericType >::Magnitude(), PhQ::Displacement< NumericType >::Magnitude(), PhQ::Force< NumericType >::Magnitude(), PhQ::HeatFlux< NumericType >::Magnitude(), PhQ::Position< NumericType >::Magnitude(), PhQ::TemperatureGradient< NumericType >::Magnitude(), PhQ::Traction< NumericType >::Magnitude(), PhQ::VectorArea< NumericType >::Magnitude(), PhQ::Velocity< NumericType >::Magnitude(), PhQ::DimensionalVector< UnitType, NumericType >::MutableValue(), PhQ::Acceleration< NumericType >::operator*(), PhQ::Displacement< NumericType >::operator*(), PhQ::Force< NumericType >::operator*(), PhQ::HeatFlux< NumericType >::operator*(), PhQ::Position< NumericType >::operator*(), PhQ::TemperatureGradient< NumericType >::operator*(), PhQ::Traction< NumericType >::operator*(), PhQ::VectorArea< NumericType >::operator*(), PhQ::Velocity< NumericType >::operator*(), PhQ::Acceleration< NumericType >::operator*=(), PhQ::Displacement< NumericType >::operator*=(), PhQ::Force< NumericType >::operator*=(), PhQ::HeatFlux< NumericType >::operator*=(), PhQ::Position< NumericType >::operator*=(), PhQ::TemperatureGradient< NumericType >::operator*=(), PhQ::Traction< NumericType >::operator*=(), PhQ::VectorArea< NumericType >::operator*=(), PhQ::Velocity< NumericType >::operator*=(), PhQ::Acceleration< NumericType >::operator+(), PhQ::Displacement< NumericType >::operator+(), PhQ::Position< NumericType >::operator+(), PhQ::Force< NumericType >::operator+(), PhQ::HeatFlux< NumericType >::operator+(), PhQ::Position< NumericType >::operator+(), PhQ::TemperatureGradient< NumericType >::operator+(), PhQ::Traction< NumericType >::operator+(), PhQ::VectorArea< NumericType >::operator+(), PhQ::Velocity< NumericType >::operator+(), PhQ::Acceleration< NumericType >::operator+=(), PhQ::Displacement< NumericType >::operator+=(), PhQ::Position< NumericType >::operator+=(), PhQ::Force< NumericType >::operator+=(), PhQ::HeatFlux< NumericType >::operator+=(), PhQ::Position< NumericType >::operator+=(), PhQ::TemperatureGradient< NumericType >::operator+=(), PhQ::Traction< NumericType >::operator+=(), PhQ::VectorArea< NumericType >::operator+=(), PhQ::Velocity< NumericType >::operator+=(), PhQ::Acceleration< NumericType >::operator-(), PhQ::Displacement< NumericType >::operator-(), PhQ::Position< NumericType >::operator-(), PhQ::Force< NumericType >::operator-(), PhQ::HeatFlux< NumericType >::operator-(), PhQ::Position< NumericType >::operator-(), PhQ::TemperatureGradient< NumericType >::operator-(), PhQ::Traction< NumericType >::operator-(), PhQ::VectorArea< NumericType >::operator-(), PhQ::Velocity< NumericType >::operator-(), PhQ::Acceleration< NumericType >::operator-=(), PhQ::Displacement< NumericType >::operator-=(), PhQ::Position< NumericType >::operator-=(), PhQ::Force< NumericType >::operator-=(), PhQ::HeatFlux< NumericType >::operator-=(), PhQ::Position< NumericType >::operator-=(), PhQ::TemperatureGradient< NumericType >::operator-=(), PhQ::Traction< NumericType >::operator-=(), PhQ::VectorArea< NumericType >::operator-=(), PhQ::Velocity< NumericType >::operator-=(), PhQ::Acceleration< NumericType >::operator/(), PhQ::Displacement< NumericType >::operator/(), PhQ::Force< NumericType >::operator/(), PhQ::HeatFlux< NumericType >::operator/(), PhQ::Position< NumericType >::operator/(), PhQ::TemperatureGradient< NumericType >::operator/(), PhQ::Traction< NumericType >::operator/(), PhQ::VectorArea< NumericType >::operator/(), PhQ::Velocity< NumericType >::operator/(), PhQ::Acceleration< NumericType >::operator/=(), PhQ::Displacement< NumericType >::operator/=(), PhQ::Force< NumericType >::operator/=(), PhQ::HeatFlux< NumericType >::operator/=(), PhQ::Position< NumericType >::operator/=(), PhQ::TemperatureGradient< NumericType >::operator/=(), PhQ::Traction< NumericType >::operator/=(), PhQ::VectorArea< NumericType >::operator/=(), PhQ::Velocity< NumericType >::operator/=(), PhQ::Acceleration< NumericType >::operator=(), PhQ::DimensionalVector< UnitType, NumericType >::operator=(), PhQ::Displacement< NumericType >::operator=(), PhQ::Force< NumericType >::operator=(), PhQ::HeatFlux< NumericType >::operator=(), PhQ::Position< NumericType >::operator=(), PhQ::TemperatureGradient< NumericType >::operator=(), PhQ::Traction< NumericType >::operator=(), PhQ::VectorArea< NumericType >::operator=(), PhQ::Velocity< NumericType >::operator=(), PhQ::DimensionalVector< UnitType, NumericType >::Print(), PhQ::DimensionalVector< UnitType, NumericType >::SetValue(), PhQ::DimensionalVector< UnitType, NumericType >::StaticValue(), PhQ::DimensionalVector< UnitType, NumericType >::Value(), PhQ::DimensionalVector< UnitType, NumericType >::Value(), PhQ::Acceleration< NumericType >::x(), PhQ::Displacement< NumericType >::x(), PhQ::Force< NumericType >::x(), PhQ::HeatFlux< NumericType >::x(), PhQ::Position< NumericType >::x(), PhQ::TemperatureGradient< NumericType >::x(), PhQ::Traction< NumericType >::x(), PhQ::VectorArea< NumericType >::x(), PhQ::Velocity< NumericType >::x(), PhQ::DimensionalVector< UnitType, NumericType >::XML(), PhQ::Acceleration< NumericType >::y(), PhQ::Displacement< NumericType >::y(), PhQ::Force< NumericType >::y(), PhQ::HeatFlux< NumericType >::y(), PhQ::Position< NumericType >::y(), PhQ::TemperatureGradient< NumericType >::y(), PhQ::Traction< NumericType >::y(), PhQ::VectorArea< NumericType >::y(), PhQ::Velocity< NumericType >::y(), PhQ::DimensionalVector< UnitType, NumericType >::YAML(), PhQ::Acceleration< NumericType >::z(), PhQ::Displacement< NumericType >::z(), PhQ::Force< NumericType >::z(), PhQ::HeatFlux< NumericType >::z(), PhQ::Position< NumericType >::z(), PhQ::TemperatureGradient< NumericType >::z(), PhQ::Traction< NumericType >::z(), PhQ::VectorArea< NumericType >::z(), and PhQ::Velocity< NumericType >::z().
The documentation for this class was generated from the following files:
PhQ/Angle.hpp
PhQ/Force.hpp
PhQ/Traction.hpp