Physical Quantities (PhQ): PhQ::DimensionalDyad< UnitType, NumericType > Class Template Reference
PhQ::DimensionalDyad< UnitType, NumericType > Class Template Reference
Abstract base class that represents any dimensional dyadic tensor physical quantity. Such a physical quantity is composed of a value and a unit of measure where the value is a three-dimensional dyadic tensor. The tensor may be non-symmetric.
#include "DimensionalDyad.hpp"
Public Member Functions
constexpr const PhQ::Dyad< NumericType > & Value () const noexcept
Value of this physical quantity expressed in its standard unit of measure.
PhQ::Dyad< NumericType > Value (const UnitType unit) const
Value of this physical quantity expressed in a given unit of measure.
template<UnitType NewUnit>
constexpr PhQ::Dyad< NumericType > StaticValue () const
Value of this physical quantity expressed in a given unit of measure. This method can be evaluated statically at compile-time.
constexpr PhQ::Dyad< NumericType > & MutableValue () noexcept
Returns the value of this physical quantity expressed in its standard unit of measure as a mutable value.
constexpr void SetValue (const PhQ::Dyad< NumericType > &value) noexcept
Sets the value of this physical quantity expressed in its standard unit of measure to the given value.
std::string Print () const
Prints this physical quantity as a string. This physical quantity's value is expressed in its standard unit of measure.
std::string Print (const UnitType unit) const
Prints this physical quantity as a string. This physical quantity's value is expressed in the given unit of measure.
std::string JSON () const
Serializes this physical quantity as a JSON message. This physical quantity's value is expressed in its standard unit of measure.
std::string JSON (const UnitType unit) const
Serializes this physical quantity as a JSON message. This physical quantity's value is expressed in the given unit of measure.
std::string XML () const
Serializes this physical quantity as an XML message. This physical quantity's value is expressed in its standard unit of measure.
std::string XML (const UnitType unit) const
Serializes this physical quantity as an XML message. This physical quantity's value is expressed in the given unit of measure.
std::string YAML () const
Serializes this physical quantity as a YAML message. This physical quantity's value is expressed in its standard unit of measure.
std::string YAML (const UnitType unit) const
Serializes this physical quantity as a YAML message. This physical quantity's value is expressed in the given unit of measure.
Static Public Member Functions
static constexpr const PhQ::Dimensions & Dimensions ()
Physical dimension set of this physical quantity.
static constexpr UnitType Unit ()
Standard unit of measure for this physical quantity. This physical quantity's value is stored internally in this unit of measure.
Protected Member Functions
DimensionalDyad ()=default
Default constructor. Constructs a dimensional dyadic tensor physical quantity with an uninitialized value.
constexpr DimensionalDyad (const PhQ::Dyad< NumericType > &value)
Constructor. Constructs a dimensional dyadic tensor physical quantity with a given value expressed in its standard unit of measure.
DimensionalDyad (const PhQ::Dyad< NumericType > &value, const UnitType unit)
Constructor. Constructs a dimensional dimensional dyadic tensor physical quantity with a given value expressed in a given unit of measure.
~DimensionalDyad () noexcept=default
Destructor. Destroys this dimensional dyadic tensor physical quantity.
constexpr DimensionalDyad (const DimensionalDyad< UnitType, NumericType > &other)=default
Copy constructor. Constructs a dimensional dyadic tensor physical quantity by copying another one.
template<typename OtherNumericType >
constexpr DimensionalDyad (const DimensionalDyad< UnitType, OtherNumericType > &other)
Copy constructor. Constructs a dimensional dyadic tensor physical quantity by copying another one.
constexpr DimensionalDyad (DimensionalDyad< UnitType, NumericType > &&other) noexcept=default
Move constructor. Constructs a dimensional dyadic tensor physical quantity by moving another one.
constexpr DimensionalDyad< UnitType, NumericType > & operator= (const DimensionalDyad< UnitType, NumericType > &other)=default
Copy assignment operator. Assigns this dimensional dyadic tensor physical quantity by copying another one.
template<typename OtherNumericType >
constexpr DimensionalDyad< UnitType, NumericType > & operator= (const DimensionalDyad< UnitType, OtherNumericType > &other)
Copy assignment operator. Assigns this dimensional dyadic tensor physical quantity by copying another one.
constexpr DimensionalDyad< UnitType, NumericType > & operator= (DimensionalDyad< UnitType, NumericType > &&other) noexcept=default
Move assignment operator. Assigns this dimensional dyadic tensor physical quantity by moving another one.
Protected Attributes
PhQ::Dyad< NumericType > value
Value of this physical quantity expressed in its standard unit of measure.
Detailed Description
template<typename UnitType, typename NumericType = double>
class PhQ::DimensionalDyad< UnitType, NumericType >
Abstract base class that represents any dimensional dyadic tensor physical quantity. Such a physical quantity is composed of a value and a unit of measure where the value is a three-dimensional dyadic tensor. The tensor may be non-symmetric.
Definition at line 46 of file DimensionalDyad.hpp.
Constructor & Destructor Documentation
DimensionalDyad() [1/6]
template<typename UnitType , typename NumericType = double> PhQ::DimensionalDyad< UnitType, NumericType >::DimensionalDyad () protected default
Default constructor. Constructs a dimensional dyadic tensor physical quantity with an uninitialized value.
DimensionalDyad() [2/6]
template<typename UnitType , typename NumericType = double> constexpr PhQ::DimensionalDyad< UnitType, NumericType >::DimensionalDyad (const PhQ::Dyad< NumericType > & value) inline explicit constexpr protected
Constructor. Constructs a dimensional dyadic tensor physical quantity with a given value expressed in its standard unit of measure.
Definition at line 167 of file DimensionalDyad.hpp.
DimensionalDyad() [3/6]
template<typename UnitType , typename NumericType = double> PhQ::DimensionalDyad< UnitType, NumericType >::DimensionalDyad (const PhQ::Dyad< NumericType > & value, const UnitType unit) inline protected
Constructor. Constructs a dimensional dimensional dyadic tensor physical quantity with a given value expressed in a given unit of measure.
Definition at line 171 of file DimensionalDyad.hpp.
References PhQ::ConvertInPlace().
~DimensionalDyad()
template<typename UnitType , typename NumericType = double> PhQ::DimensionalDyad< UnitType, NumericType >::~DimensionalDyad () protected default noexcept
Destructor. Destroys this dimensional dyadic tensor physical quantity.
DimensionalDyad() [4/6]
template<typename UnitType , typename NumericType = double> constexpr PhQ::DimensionalDyad< UnitType, NumericType >::DimensionalDyad (const DimensionalDyad< UnitType, NumericType > & other) constexpr protected default
Copy constructor. Constructs a dimensional dyadic tensor physical quantity by copying another one.
DimensionalDyad() [5/6]
template<typename UnitType , typename NumericType = double> template<typename OtherNumericType > constexpr PhQ::DimensionalDyad< UnitType, NumericType >::DimensionalDyad (const DimensionalDyad< UnitType, OtherNumericType > & other) inline explicit constexpr protected
Copy constructor. Constructs a dimensional dyadic tensor physical quantity by copying another one.
Definition at line 185 of file DimensionalDyad.hpp.
DimensionalDyad() [6/6]
template<typename UnitType , typename NumericType = double> constexpr PhQ::DimensionalDyad< UnitType, NumericType >::DimensionalDyad (DimensionalDyad< UnitType, NumericType > && other) constexpr protected default noexcept
Move constructor. Constructs a dimensional dyadic tensor physical quantity by moving another one.
Member Function Documentation
Dimensions()
template<typename UnitType , typename NumericType = double> static constexpr const PhQ::Dimensions& PhQ::DimensionalDyad< UnitType, NumericType >::Dimensions () inline static constexpr
Physical dimension set of this physical quantity.
Definition at line 49 of file DimensionalDyad.hpp.
JSON() [1/2]
template<typename UnitType , typename NumericType = double> std::string PhQ::DimensionalDyad< UnitType, NumericType >::JSON () const inline
Serializes this physical quantity as a JSON message. This physical quantity's value is expressed in its standard unit of measure.
Definition at line 102 of file DimensionalDyad.hpp.
References PhQ::Abbreviation(), and PhQ::DimensionalDyad< UnitType, NumericType >::value.
Referenced by PhQ::DimensionalDyad< UnitType, NumericType >::JSON().
JSON() [2/2]
template<typename UnitType , typename NumericType = double> std::string PhQ::DimensionalDyad< UnitType, NumericType >::JSON (const UnitType unit) const inline
Serializes this physical quantity as a JSON message. This physical quantity's value is expressed in the given unit of measure.
Definition at line 112 of file DimensionalDyad.hpp.
References PhQ::Abbreviation(), PhQ::DimensionalDyad< UnitType, NumericType >::JSON(), and PhQ::DimensionalDyad< UnitType, NumericType >::Value().
MutableValue()
template<typename UnitType , typename NumericType = double> constexpr PhQ::Dyad<NumericType>& PhQ::DimensionalDyad< UnitType, NumericType >::MutableValue () inline constexpr noexcept
Returns the value of this physical quantity expressed in its standard unit of measure as a mutable value.
Definition at line 78 of file DimensionalDyad.hpp.
References PhQ::DimensionalDyad< UnitType, NumericType >::value.
operator=() [1/3]
template<typename UnitType , typename NumericType = double> constexpr DimensionalDyad<UnitType, NumericType>& PhQ::DimensionalDyad< UnitType, NumericType >::operator= (const DimensionalDyad< UnitType, NumericType > & other) constexpr protected default
Copy assignment operator. Assigns this dimensional dyadic tensor physical quantity by copying another one.
operator=() [2/3]
template<typename UnitType , typename NumericType = double> template<typename OtherNumericType > constexpr DimensionalDyad<UnitType, NumericType>& PhQ::DimensionalDyad< UnitType, NumericType >::operator= (const DimensionalDyad< UnitType, OtherNumericType > & other) inline constexpr protected
Copy assignment operator. Assigns this dimensional dyadic tensor physical quantity by copying another one.
Definition at line 200 of file DimensionalDyad.hpp.
References PhQ::DimensionalDyad< UnitType, NumericType >::Value(), and PhQ::DimensionalDyad< UnitType, NumericType >::value.
operator=() [3/3]
template<typename UnitType , typename NumericType = double> constexpr DimensionalDyad<UnitType, NumericType>& PhQ::DimensionalDyad< UnitType, NumericType >::operator= (DimensionalDyad< UnitType, NumericType > && other) constexpr protected default noexcept
Move assignment operator. Assigns this dimensional dyadic tensor physical quantity by moving another one.
Print() [1/2]
template<typename UnitType , typename NumericType = double> std::string PhQ::DimensionalDyad< UnitType, NumericType >::Print () const inline
Prints this physical quantity as a string. This physical quantity's value is expressed in its standard unit of measure.
Definition at line 90 of file DimensionalDyad.hpp.
References PhQ::Abbreviation(), and PhQ::DimensionalDyad< UnitType, NumericType >::value.
Referenced by PhQ::operator<<().
Print() [2/2]
template<typename UnitType , typename NumericType = double> std::string PhQ::DimensionalDyad< UnitType, NumericType >::Print (const UnitType unit) const inline
Prints this physical quantity as a string. This physical quantity's value is expressed in the given unit of measure.
Definition at line 96 of file DimensionalDyad.hpp.
References PhQ::Abbreviation(), and PhQ::DimensionalDyad< UnitType, NumericType >::Value().
SetValue()
template<typename UnitType , typename NumericType = double> constexpr void PhQ::DimensionalDyad< UnitType, NumericType >::SetValue (const PhQ::Dyad< NumericType > & value) inline constexpr noexcept
Sets the value of this physical quantity expressed in its standard unit of measure to the given value.
Definition at line 84 of file DimensionalDyad.hpp.
References PhQ::DimensionalDyad< UnitType, NumericType >::value.
StaticValue()
template<typename UnitType , typename NumericType = double> template<UnitType NewUnit> constexpr PhQ::Dyad<NumericType> PhQ::DimensionalDyad< UnitType, NumericType >::StaticValue () const inline constexpr
Value of this physical quantity expressed in a given unit of measure. This method can be evaluated statically at compile-time.
Definition at line 72 of file DimensionalDyad.hpp.
References PhQ::DimensionalDyad< UnitType, NumericType >::value.
Unit()
template<typename UnitType , typename NumericType = double> static constexpr UnitType PhQ::DimensionalDyad< UnitType, NumericType >::Unit () inline static constexpr
Standard unit of measure for this physical quantity. This physical quantity's value is stored internally in this unit of measure.
Definition at line 55 of file DimensionalDyad.hpp.
Value() [1/2]
template<typename UnitType , typename NumericType = double> constexpr const PhQ::Dyad<NumericType>& PhQ::DimensionalDyad< UnitType, NumericType >::Value () const inline constexpr noexcept
Value of this physical quantity expressed in its standard unit of measure.
Definition at line 60 of file DimensionalDyad.hpp.
References PhQ::DimensionalDyad< UnitType, NumericType >::value.
Referenced by PhQ::DimensionalDyad< UnitType, NumericType >::JSON(), PhQ::DimensionalDyad< UnitType, NumericType >::operator=(), PhQ::VelocityGradient< NumericType >::operator=(), PhQ::DimensionalDyad< UnitType, NumericType >::Print(), PhQ::StrainRate< NumericType >::StrainRate(), PhQ::DimensionalDyad< UnitType, NumericType >::XML(), and PhQ::DimensionalDyad< UnitType, NumericType >::YAML().
Value() [2/2]
template<typename UnitType , typename NumericType = double> PhQ::Dyad<NumericType> PhQ::DimensionalDyad< UnitType, NumericType >::Value (const UnitType unit) const inline
Value of this physical quantity expressed in a given unit of measure.
Definition at line 65 of file DimensionalDyad.hpp.
References PhQ::Convert(), and PhQ::DimensionalDyad< UnitType, NumericType >::value.
XML() [1/2]
template<typename UnitType , typename NumericType = double> std::string PhQ::DimensionalDyad< UnitType, NumericType >::XML () const inline
Serializes this physical quantity as an XML message. This physical quantity's value is expressed in its standard unit of measure.
Definition at line 122 of file DimensionalDyad.hpp.
References PhQ::Abbreviation(), and PhQ::DimensionalDyad< UnitType, NumericType >::value.
Referenced by PhQ::DimensionalDyad< UnitType, NumericType >::XML().
XML() [2/2]
template<typename UnitType , typename NumericType = double> std::string PhQ::DimensionalDyad< UnitType, NumericType >::XML (const UnitType unit) const inline
Serializes this physical quantity as an XML message. This physical quantity's value is expressed in the given unit of measure.
Definition at line 132 of file DimensionalDyad.hpp.
References PhQ::Abbreviation(), PhQ::DimensionalDyad< UnitType, NumericType >::Value(), and PhQ::DimensionalDyad< UnitType, NumericType >::XML().
YAML() [1/2]
template<typename UnitType , typename NumericType = double> std::string PhQ::DimensionalDyad< UnitType, NumericType >::YAML () const inline
Serializes this physical quantity as a YAML message. This physical quantity's value is expressed in its standard unit of measure.
Definition at line 142 of file DimensionalDyad.hpp.
References PhQ::Abbreviation(), and PhQ::DimensionalDyad< UnitType, NumericType >::value.
Referenced by PhQ::DimensionalDyad< UnitType, NumericType >::YAML().
YAML() [2/2]
template<typename UnitType , typename NumericType = double> std::string PhQ::DimensionalDyad< UnitType, NumericType >::YAML (const UnitType unit) const inline
Serializes this physical quantity as a YAML message. This physical quantity's value is expressed in the given unit of measure.
Definition at line 152 of file DimensionalDyad.hpp.
References PhQ::Abbreviation(), PhQ::DimensionalDyad< UnitType, NumericType >::Value(), and PhQ::DimensionalDyad< UnitType, NumericType >::YAML().
Member Data Documentation
value
template<typename UnitType , typename NumericType = double> PhQ::Dyad<NumericType> PhQ::DimensionalDyad< UnitType, NumericType >::value protected
Value of this physical quantity expressed in its standard unit of measure.
Definition at line 212 of file DimensionalDyad.hpp.
Referenced by PhQ::DimensionalDyad< UnitType, NumericType >::JSON(), PhQ::DimensionalDyad< UnitType, NumericType >::MutableValue(), PhQ::VelocityGradient< NumericType >::operator+(), PhQ::VelocityGradient< NumericType >::operator-(), PhQ::DimensionalDyad< UnitType, NumericType >::operator=(), PhQ::DimensionalDyad< UnitType, NumericType >::Print(), PhQ::DimensionalDyad< UnitType, NumericType >::SetValue(), PhQ::DimensionalDyad< UnitType, NumericType >::StaticValue(), PhQ::DimensionalDyad< UnitType, NumericType >::Value(), PhQ::DimensionalDyad< UnitType, NumericType >::XML(), and PhQ::DimensionalDyad< UnitType, NumericType >::YAML().
The documentation for this class was generated from the following file:
PhQ/DimensionalDyad.hpp