Physical Quantities (PhQ): PhQ::DimensionlessVector< NumericType > Class Template Reference
PhQ::DimensionlessVector< NumericType > Class Template Reference
Abstract base class that represents any dimensionless vector physical quantity. Such a physical quantity is composed only of a value where the value is a three-dimensional vector. Such a physical quantity has no unit of measure and no dimension set.
#include "DimensionlessVector.hpp"
Public Member Functions
constexpr const PhQ::Vector< NumericType > & Value () const noexcept
Value of this physical quantity.
std::string Print () const
Prints this physical quantity as a string.
std::string JSON () const
Serializes this physical quantity as a JSON message.
std::string XML () const
Serializes this physical quantity as an XML message.
std::string YAML () const
Serializes this physical quantity as a YAML message.
Static Public Member Functions
static constexpr PhQ::Dimensions Dimensions ()
Physical dimension set of this physical quantity. Since this physical quantity is dimensionless, its physical dimension set is simply the null set.
Protected Member Functions
DimensionlessVector ()=default
Default constructor. Constructs a dimensionless vector physical quantity with an uninitialized value.
constexpr DimensionlessVector (const NumericType x, const NumericType y, const NumericType z)
Constructor. Constructs a dimensionless vector physical quantity whose value has the given x, y, and z Cartesian components.
constexpr DimensionlessVector (const std::array< NumericType, 3 > &x_y_z)
Constructor. Constructs a dimensionless vector physical quantity from a given array representing its value's x, y, and z Cartesian components.
constexpr DimensionlessVector (const PhQ::Vector< NumericType > &value)
Constructor. Constructs a dimensionless vector physical quantity with a given value.
~DimensionlessVector () noexcept=default
Destructor. Destroys this dimensionless vector physical quantity.
constexpr DimensionlessVector (const DimensionlessVector< NumericType > &other)=default
Copy constructor. Constructs a dimensionless vector physical quantity by copying another one.
template<typename OtherNumericType >
constexpr DimensionlessVector (const DimensionlessVector< OtherNumericType > &other)
Copy constructor. Constructs a dimensionless vector physical quantity by copying another one.
constexpr DimensionlessVector (DimensionlessVector< NumericType > &&other) noexcept=default
Move constructor. Constructs a dimensionless vector physical quantity by moving another one.
constexpr DimensionlessVector< NumericType > & operator= (const DimensionlessVector< NumericType > &other)=default
Copy assignment operator. Assigns this dimensionless vector physical quantity by copying another one.
template<typename OtherNumericType >
constexpr DimensionlessVector< NumericType > & operator= (const DimensionlessVector< OtherNumericType > &other)
Copy assignment operator. Assigns this dimensionless vector physical quantity by copying another one.
constexpr DimensionlessVector< NumericType > & operator= (DimensionlessVector< NumericType > &&other) noexcept=default
Move assignment operator. Assigns this dimensionless vector physical quantity by moving another one.
Protected Attributes
PhQ::Vector< NumericType > value
Value of this physical quantity.
Detailed Description
template<typename NumericType = double>
class PhQ::DimensionlessVector< NumericType >
Abstract base class that represents any dimensionless vector physical quantity. Such a physical quantity is composed only of a value where the value is a three-dimensional vector. Such a physical quantity has no unit of measure and no dimension set.
Definition at line 45 of file DimensionlessVector.hpp.
Constructor & Destructor Documentation
DimensionlessVector() [1/7]
template<typename NumericType = double> PhQ::DimensionlessVector< NumericType >::DimensionlessVector () protected default
Default constructor. Constructs a dimensionless vector physical quantity with an uninitialized value.
DimensionlessVector() [2/7]
template<typename NumericType = double> constexpr PhQ::DimensionlessVector< NumericType >::DimensionlessVector (const NumericType x, const NumericType y, const NumericType z) inline constexpr protected
Constructor. Constructs a dimensionless vector physical quantity whose value has the given x, y, and z Cartesian components.
Definition at line 89 of file DimensionlessVector.hpp.
DimensionlessVector() [3/7]
template<typename NumericType = double> constexpr PhQ::DimensionlessVector< NumericType >::DimensionlessVector (const std::array< NumericType, 3 > & x_y_z) inline explicit constexpr protected
Constructor. Constructs a dimensionless vector physical quantity from a given array representing its value's x, y, and z Cartesian components.
Definition at line 94 of file DimensionlessVector.hpp.
DimensionlessVector() [4/7]
template<typename NumericType = double> constexpr PhQ::DimensionlessVector< NumericType >::DimensionlessVector (const PhQ::Vector< NumericType > & value) inline explicit constexpr protected
Constructor. Constructs a dimensionless vector physical quantity with a given value.
Definition at line 97 of file DimensionlessVector.hpp.
~DimensionlessVector()
template<typename NumericType = double> PhQ::DimensionlessVector< NumericType >::~DimensionlessVector () protected default noexcept
Destructor. Destroys this dimensionless vector physical quantity.
DimensionlessVector() [5/7]
template<typename NumericType = double> constexpr PhQ::DimensionlessVector< NumericType >::DimensionlessVector (const DimensionlessVector< NumericType > & other) constexpr protected default
Copy constructor. Constructs a dimensionless vector physical quantity by copying another one.
DimensionlessVector() [6/7]
template<typename NumericType = double> template<typename OtherNumericType > constexpr PhQ::DimensionlessVector< NumericType >::DimensionlessVector (const DimensionlessVector< OtherNumericType > & other) inline explicit constexpr protected
Copy constructor. Constructs a dimensionless vector physical quantity by copying another one.
Definition at line 109 of file DimensionlessVector.hpp.
DimensionlessVector() [7/7]
template<typename NumericType = double> constexpr PhQ::DimensionlessVector< NumericType >::DimensionlessVector (DimensionlessVector< NumericType > && other) constexpr protected default noexcept
Move constructor. Constructs a dimensionless vector physical quantity by moving another one.
Member Function Documentation
Dimensions()
template<typename NumericType = double> static constexpr PhQ::Dimensions PhQ::DimensionlessVector< NumericType >::Dimensions () inline static constexpr
Physical dimension set of this physical quantity. Since this physical quantity is dimensionless, its physical dimension set is simply the null set.
Definition at line 53 of file DimensionlessVector.hpp.
References PhQ::Dimensionless.
JSON()
template<typename NumericType = double> std::string PhQ::DimensionlessVector< NumericType >::JSON () const inline
Serializes this physical quantity as a JSON message.
Definition at line 68 of file DimensionlessVector.hpp.
References PhQ::DimensionlessVector< NumericType >::value.
operator=() [1/3]
template<typename NumericType = double> constexpr DimensionlessVector<NumericType>& PhQ::DimensionlessVector< NumericType >::operator= (const DimensionlessVector< NumericType > & other) constexpr protected default
Copy assignment operator. Assigns this dimensionless vector physical quantity by copying another one.
operator=() [2/3]
template<typename NumericType = double> template<typename OtherNumericType > constexpr DimensionlessVector<NumericType>& PhQ::DimensionlessVector< NumericType >::operator= (const DimensionlessVector< OtherNumericType > & other) inline constexpr protected
Copy assignment operator. Assigns this dimensionless vector physical quantity by copying another one.
Definition at line 124 of file DimensionlessVector.hpp.
References PhQ::DimensionlessVector< NumericType >::Value(), and PhQ::DimensionlessVector< NumericType >::value.
operator=() [3/3]
template<typename NumericType = double> constexpr DimensionlessVector<NumericType>& PhQ::DimensionlessVector< NumericType >::operator= (DimensionlessVector< NumericType > && other) constexpr protected default noexcept
Move assignment operator. Assigns this dimensionless vector physical quantity by moving another one.
Print()
template<typename NumericType = double> std::string PhQ::DimensionlessVector< NumericType >::Print () const inline
Prints this physical quantity as a string.
Definition at line 63 of file DimensionlessVector.hpp.
References PhQ::DimensionlessVector< NumericType >::value.
Referenced by PhQ::operator<<().
Value()
template<typename NumericType = double> constexpr const PhQ::Vector<NumericType>& PhQ::DimensionlessVector< NumericType >::Value () const inline constexpr noexcept
Value of this physical quantity.
Definition at line 58 of file DimensionlessVector.hpp.
References PhQ::DimensionlessVector< NumericType >::value.
Referenced by PhQ::Vector< NumericType >::Cross(), PhQ::Vector< NumericType >::Dyadic(), PhQ::operator*(), PhQ::DimensionlessVector< NumericType >::operator=(), PhQ::Direction< NumericType >::operator=(), PhQ::PlanarDirection< NumericType >::PlanarDirection(), and PhQ::Vector< NumericType >::Vector().
XML()
template<typename NumericType = double> std::string PhQ::DimensionlessVector< NumericType >::XML () const inline
Serializes this physical quantity as an XML message.
Definition at line 73 of file DimensionlessVector.hpp.
References PhQ::DimensionlessVector< NumericType >::value.
YAML()
template<typename NumericType = double> std::string PhQ::DimensionlessVector< NumericType >::YAML () const inline
Serializes this physical quantity as a YAML message.
Definition at line 78 of file DimensionlessVector.hpp.
References PhQ::DimensionlessVector< NumericType >::value.
Member Data Documentation
value
template<typename NumericType = double> PhQ::Vector<NumericType> PhQ::DimensionlessVector< NumericType >::value protected
Value of this physical quantity.
Definition at line 136 of file DimensionlessVector.hpp.
Referenced by PhQ::Direction< NumericType >::Cross(), PhQ::Direction< NumericType >::Dyadic(), PhQ::DimensionlessVector< NumericType >::JSON(), PhQ::DimensionlessVector< NumericType >::operator=(), PhQ::DimensionlessVector< NumericType >::Print(), PhQ::DimensionlessVector< NumericType >::Value(), PhQ::DimensionlessVector< NumericType >::XML(), and PhQ::DimensionlessVector< NumericType >::YAML().
The documentation for this class was generated from the following file:
PhQ/DimensionlessVector.hpp