Physical Quantities (PhQ): PhQ::SymmetricDyad< NumericType > Class Template Reference
PhQ::SymmetricDyad< NumericType > Class Template Reference
Symmetric three-dimensional Euclidean dyadic tensor. Contains six components in Cartesian coordinates: xx, xy = yx, xz = zx, yy, yz = zy, and zz. For the general case of a three-dimensional Euclidean dyadic tensor which may be symmetric or asymmetric, see PhQ::Dyad. For a three-dimensional Euclidean vector, see PhQ::Vector. For a two-dimensional Euclidean vector in the XY plane, see PhQ::PlanarVector.
#include "SymmetricDyad.hpp"
Public Member Functions
SymmetricDyad ()=default
Default constructor. Constructs a three-dimensional symmetric dyadic tensor with uninitialized xx, xy, xz, yy, yz, and zz Cartesian components.
constexpr SymmetricDyad (const NumericType xx, const NumericType xy, const NumericType xz, const NumericType yy, const NumericType yz, const NumericType zz)
Constructor. Constructs a three-dimensional symmetric dyadic tensor from the given xx, xy, xz, yy, yz, and zz Cartesian components.
constexpr SymmetricDyad (const std::array< NumericType, 6 > &xx_xy_xz_yy_yz_zz)
Constructor. Constructs a three-dimensional symmetric dyadic tensor from a given array representing its xx, xy, xz, yy, yz, and zz Cartesian components.
~SymmetricDyad () noexcept=default
Destructor. Destroys this three-dimensional symmetric dyadic tensor.
constexpr SymmetricDyad (const SymmetricDyad< NumericType > &other)=default
Copy constructor. Constructs a three-dimensional symmetric dyadic tensor by copying another one.
template<typename OtherNumericType >
constexpr SymmetricDyad (const SymmetricDyad< OtherNumericType > &other)
Copy constructor. Constructs a three-dimensional symmetric dyadic tensor by copying another one.
constexpr SymmetricDyad (SymmetricDyad< NumericType > &&other) noexcept=default
Move constructor. Constructs a three-dimensional symmetric dyadic tensor by moving another one.
constexpr SymmetricDyad< NumericType > & operator= (const SymmetricDyad< NumericType > &other)=default
Copy assignment operator. Assigns this three-dimensional symmetric dyadic tensor by copying another one.
template<typename OtherNumericType >
constexpr SymmetricDyad< NumericType > & operator= (const SymmetricDyad< OtherNumericType > &other)
Copy assignment operator. Assigns this three-dimensional symmetric dyadic tensor by copying another one.
constexpr SymmetricDyad< NumericType > & operator= (SymmetricDyad< NumericType > &&other) noexcept=default
Move assignment operator. Assigns this three-dimensional symmetric dyadic tensor by moving another one.
constexpr SymmetricDyad< NumericType > & operator= (const std::array< NumericType, 6 > &xx_xy_xz_yy_yz_zz)
Assignment operator. Assigns this three-dimensional symmetric dyadic tensor by copying a given array representing its xx, xy, xz, yy, yz, and zz Cartesian components.
constexpr const std::array< NumericType, 6 > & xx_xy_xz_yy_yz_zz () const noexcept
Returns this three-dimensional symmetric dyadic tensor's xx, xy, xz, yy, yz, and zz Cartesian components as an array.
constexpr NumericType xx () const noexcept
Returns this three-dimensional symmetric dyadic tensor's xx Cartesian component.
constexpr NumericType xy () const noexcept
Returns this three-dimensional symmetric dyadic tensor's xy = yx Cartesian component.
constexpr NumericType xz () const noexcept
Returns this three-dimensional symmetric dyadic tensor's xz = zx Cartesian component.
constexpr NumericType yx () const noexcept
Returns this three-dimensional symmetric dyadic tensor's yx = xy Cartesian component.
constexpr NumericType yy () const noexcept
Returns this three-dimensional symmetric dyadic tensor's yy Cartesian component.
constexpr NumericType yz () const noexcept
Returns this three-dimensional symmetric dyadic tensor's yz = zy Cartesian component.
constexpr NumericType zx () const noexcept
Returns this three-dimensional symmetric dyadic tensor's zx = xz Cartesian component.
constexpr NumericType zy () const noexcept
Returns this three-dimensional symmetric dyadic tensor's zy = yz Cartesian component.
constexpr NumericType zz () const noexcept
Returns this three-dimensional symmetric dyadic tensor's zz Cartesian component.
constexpr std::array< NumericType, 6 > & Mutable_xx_xy_xz_yy_yz_zz () noexcept
Returns this three-dimensional symmetric dyadic tensor's xx, xy, xz, yy, yz, and zz Cartesian components as a mutable array.
constexpr NumericType & Mutable_xx () noexcept
Returns this three-dimensional symmetric dyadic tensor's xx Cartesian component as a mutable value.
constexpr NumericType & Mutable_xy () noexcept
Returns this three-dimensional symmetric dyadic tensor's xy = yx Cartesian component as a mutable value.
constexpr NumericType & Mutable_xz () noexcept
Returns this three-dimensional symmetric dyadic tensor's xz = zx Cartesian component as a mutable value.
constexpr NumericType & Mutable_yx () noexcept
Returns this three-dimensional symmetric dyadic tensor's yx = xy Cartesian component as a mutable value.
constexpr NumericType & Mutable_yy () noexcept
Returns this three-dimensional symmetric dyadic tensor's yy Cartesian component as a mutable value.
constexpr NumericType & Mutable_yz () noexcept
Returns this three-dimensional symmetric dyadic tensor's yz = zy Cartesian component as a mutable value.
constexpr NumericType & Mutable_zx () noexcept
Returns this three-dimensional symmetric dyadic tensor's zx = xz Cartesian component as a mutable value.
constexpr NumericType & Mutable_zy () noexcept
Returns this three-dimensional symmetric dyadic tensor's zy = yz Cartesian component as a mutable value.
constexpr NumericType & Mutable_zz () noexcept
Returns this three-dimensional symmetric dyadic tensor's zz Cartesian component as a mutable value.
constexpr void Set_xx_xy_xz_yy_yz_zz (const std::array< NumericType, 6 > &xx_xy_xz_yy_yz_zz) noexcept
Sets this three-dimensional symmetric dyadic tensor's xx, xy, xz, yy, yz, and zz Cartesian components to the given values.
constexpr void Set_xx_xy_xz_yy_yz_zz (const NumericType xx, const NumericType xy, const NumericType xz, const NumericType yy, const NumericType yz, const NumericType zz) noexcept
Sets this three-dimensional symmetric dyadic tensor's xx, xy, xz, yy, yz, and zz Cartesian components to the given values.
constexpr void Set_xx (const NumericType xx) noexcept
Sets this three-dimensional symmetric dyadic tensor's xx Cartesian component to a given value.
constexpr void Set_xy (const NumericType xy) noexcept
Sets this three-dimensional symmetric dyadic tensor's xy = yx Cartesian component to a given value.
constexpr void Set_xz (const NumericType xz) noexcept
Sets this three-dimensional symmetric dyadic tensor's xz = zx Cartesian component to a given value.
constexpr void Set_yx (const NumericType yx) noexcept
Sets this three-dimensional symmetric dyadic tensor's yx = xy Cartesian component to a given value.
constexpr void Set_yy (const NumericType yy) noexcept
Sets this three-dimensional symmetric dyadic tensor's yy Cartesian component to a given value.
constexpr void Set_yz (const NumericType yz) noexcept
Sets this three-dimensional symmetric dyadic tensor's yz = zy Cartesian component to a given value.
constexpr void Set_zx (const NumericType zx) noexcept
Sets this three-dimensional symmetric dyadic tensor's zx = xz Cartesian component to a given value.
constexpr void Set_zy (const NumericType zy) noexcept
Sets this three-dimensional symmetric dyadic tensor's zy = yz Cartesian component to a given value.
constexpr void Set_zz (const NumericType zz) noexcept
Sets this three-dimensional symmetric dyadic tensor's zz Cartesian component to a given value.
constexpr NumericType Trace () const noexcept
Returns the trace of this three-dimensional symmetric dyadic tensor.
constexpr NumericType Determinant () const noexcept
Returns the determinant of this three-dimensional symmetric dyadic tensor.
constexpr const SymmetricDyad< NumericType > & Transpose () const noexcept
Returns the transpose of this three-dimensional symmetric dyadic tensor.
constexpr SymmetricDyad< NumericType > Cofactors () const
Returns the cofactors of this three-dimensional symmetric dyadic tensor.
constexpr SymmetricDyad< NumericType > Adjugate () const
Returns the adjugate of this three-dimensional symmetric dyadic tensor.
std::optional< SymmetricDyad< NumericType > > Inverse () const
Returns the inverse of this three-dimensional symmetric dyadic tensor if it exists, or std::nullopt otherwise.
std::string Print () const
Prints this three-dimensional symmetric dyadic tensor as a string.
std::string JSON () const
Serializes this three-dimensional symmetric dyadic tensor as a JSON message.
std::string XML () const
Serializes this three-dimensional symmetric dyadic tensor as an XML message.
std::string YAML () const
Serializes this three-dimensional symmetric dyadic tensor as a YAML message.
constexpr void operator+= (const SymmetricDyad< NumericType > &symmetric_dyad) noexcept
constexpr void operator-= (const SymmetricDyad< NumericType > &symmetric_dyad) noexcept
template<typename OtherNumericType >
constexpr void operator*= (const OtherNumericType number) noexcept
template<typename OtherNumericType >
constexpr void operator/= (const OtherNumericType number) noexcept
Static Public Member Functions
static constexpr SymmetricDyad< NumericType > Zero ()
Statically creates a three-dimensional symmetric dyadic tensor with its xx, xy, xz, yy, yz, and zz Cartesian components initialized to zero.
Private Attributes
std::array< NumericType, 6 > xx_xy_xz_yy_yz_zz_
Cartesian components of this three-dimensional symmetric dyadic tensor.
Detailed Description
template<typename NumericType = double>
class PhQ::SymmetricDyad< NumericType >
Symmetric three-dimensional Euclidean dyadic tensor. Contains six components in Cartesian coordinates: xx, xy = yx, xz = zx, yy, yz = zy, and zz. For the general case of a three-dimensional Euclidean dyadic tensor which may be symmetric or asymmetric, see PhQ::Dyad. For a three-dimensional Euclidean vector, see PhQ::Vector. For a two-dimensional Euclidean vector in the XY plane, see PhQ::PlanarVector.
Definition at line 48 of file SymmetricDyad.hpp.
Constructor & Destructor Documentation
SymmetricDyad() [1/6]
template<typename NumericType = double> PhQ::SymmetricDyad< NumericType >::SymmetricDyad () default
Default constructor. Constructs a three-dimensional symmetric dyadic tensor with uninitialized xx, xy, xz, yy, yz, and zz Cartesian components.
SymmetricDyad() [2/6]
template<typename NumericType = double> constexpr PhQ::SymmetricDyad< NumericType >::SymmetricDyad (const NumericType xx, const NumericType xy, const NumericType xz, const NumericType yy, const NumericType yz, const NumericType zz) inline constexpr
Constructor. Constructs a three-dimensional symmetric dyadic tensor from the given xx, xy, xz, yy, yz, and zz Cartesian components.
Definition at line 60 of file SymmetricDyad.hpp.
References PhQ::SymmetricDyad< NumericType >::xx(), PhQ::SymmetricDyad< NumericType >::xy(), PhQ::SymmetricDyad< NumericType >::xz(), PhQ::SymmetricDyad< NumericType >::yy(), PhQ::SymmetricDyad< NumericType >::yz(), and PhQ::SymmetricDyad< NumericType >::zz().
SymmetricDyad() [3/6]
template<typename NumericType = double> constexpr PhQ::SymmetricDyad< NumericType >::SymmetricDyad (const std::array< NumericType, 6 > & xx_xy_xz_yy_yz_zz) inline explicit constexpr
Constructor. Constructs a three-dimensional symmetric dyadic tensor from a given array representing its xx, xy, xz, yy, yz, and zz Cartesian components.
Definition at line 66 of file SymmetricDyad.hpp.
~SymmetricDyad()
template<typename NumericType = double> PhQ::SymmetricDyad< NumericType >::~SymmetricDyad () default noexcept
Destructor. Destroys this three-dimensional symmetric dyadic tensor.
SymmetricDyad() [4/6]
template<typename NumericType = double> constexpr PhQ::SymmetricDyad< NumericType >::SymmetricDyad (const SymmetricDyad< NumericType > & other) constexpr default
Copy constructor. Constructs a three-dimensional symmetric dyadic tensor by copying another one.
SymmetricDyad() [5/6]
template<typename NumericType = double> template<typename OtherNumericType > constexpr PhQ::SymmetricDyad< NumericType >::SymmetricDyad (const SymmetricDyad< OtherNumericType > & other) inline explicit constexpr
Copy constructor. Constructs a three-dimensional symmetric dyadic tensor by copying another one.
Definition at line 74 of file SymmetricDyad.hpp.
SymmetricDyad() [6/6]
template<typename NumericType = double> constexpr PhQ::SymmetricDyad< NumericType >::SymmetricDyad (SymmetricDyad< NumericType > && other) constexpr default noexcept
Move constructor. Constructs a three-dimensional symmetric dyadic tensor by moving another one.
Member Function Documentation
Adjugate()
template<typename NumericType = double> constexpr SymmetricDyad<NumericType> PhQ::SymmetricDyad< NumericType >::Adjugate () const inline constexpr
Returns the adjugate of this three-dimensional symmetric dyadic tensor.
Definition at line 344 of file SymmetricDyad.hpp.
References PhQ::SymmetricDyad< NumericType >::Cofactors().
Cofactors()
template<typename NumericType = double> constexpr SymmetricDyad<NumericType> PhQ::SymmetricDyad< NumericType >::Cofactors () const inline constexpr
Returns the cofactors of this three-dimensional symmetric dyadic tensor.
Definition at line 332 of file SymmetricDyad.hpp.
References PhQ::SymmetricDyad< NumericType >::xx(), PhQ::SymmetricDyad< NumericType >::xy(), PhQ::SymmetricDyad< NumericType >::xz(), PhQ::SymmetricDyad< NumericType >::yy(), PhQ::SymmetricDyad< NumericType >::yz(), and PhQ::SymmetricDyad< NumericType >::zz().
Referenced by PhQ::SymmetricDyad< NumericType >::Adjugate().
Determinant()
template<typename NumericType = double> constexpr NumericType PhQ::SymmetricDyad< NumericType >::Determinant () const inline constexpr noexcept
Returns the determinant of this three-dimensional symmetric dyadic tensor.
Definition at line 321 of file SymmetricDyad.hpp.
References PhQ::SymmetricDyad< NumericType >::xx(), PhQ::SymmetricDyad< NumericType >::xy(), PhQ::SymmetricDyad< NumericType >::xz(), PhQ::SymmetricDyad< NumericType >::yx(), PhQ::SymmetricDyad< NumericType >::yy(), PhQ::SymmetricDyad< NumericType >::yz(), PhQ::SymmetricDyad< NumericType >::zx(), PhQ::SymmetricDyad< NumericType >::zy(), and PhQ::SymmetricDyad< NumericType >::zz().
Inverse()
template<typename NumericType > std::optional< SymmetricDyad< NumericType > > PhQ::SymmetricDyad< NumericType >::Inverse inline
Returns the inverse of this three-dimensional symmetric dyadic tensor if it exists, or std::nullopt otherwise.
Definition at line 574 of file SymmetricDyad.hpp.
JSON()
template<typename NumericType = double> std::string PhQ::SymmetricDyad< NumericType >::JSON () const inline
Serializes this three-dimensional symmetric dyadic tensor as a JSON message.
Definition at line 362 of file SymmetricDyad.hpp.
References PhQ::Print(), and PhQ::SymmetricDyad< NumericType >::xx_xy_xz_yy_yz_zz_.
Mutable_xx()
template<typename NumericType = double> constexpr NumericType& PhQ::SymmetricDyad< NumericType >::Mutable_xx () inline constexpr noexcept
Returns this three-dimensional symmetric dyadic tensor's xx Cartesian component as a mutable value.
Definition at line 189 of file SymmetricDyad.hpp.
References PhQ::SymmetricDyad< NumericType >::xx_xy_xz_yy_yz_zz_.
Mutable_xx_xy_xz_yy_yz_zz()
template<typename NumericType = double> constexpr std::array<NumericType, 6>& PhQ::SymmetricDyad< NumericType >::Mutable_xx_xy_xz_yy_yz_zz () inline constexpr noexcept
Returns this three-dimensional symmetric dyadic tensor's xx, xy, xz, yy, yz, and zz Cartesian components as a mutable array.
Definition at line 183 of file SymmetricDyad.hpp.
References PhQ::SymmetricDyad< NumericType >::xx_xy_xz_yy_yz_zz_.
Referenced by PhQ::ConvertInPlace().
Mutable_xy()
template<typename NumericType = double> constexpr NumericType& PhQ::SymmetricDyad< NumericType >::Mutable_xy () inline constexpr noexcept
Returns this three-dimensional symmetric dyadic tensor's xy = yx Cartesian component as a mutable value.
Definition at line 195 of file SymmetricDyad.hpp.
References PhQ::SymmetricDyad< NumericType >::xx_xy_xz_yy_yz_zz_.
Mutable_xz()
template<typename NumericType = double> constexpr NumericType& PhQ::SymmetricDyad< NumericType >::Mutable_xz () inline constexpr noexcept
Returns this three-dimensional symmetric dyadic tensor's xz = zx Cartesian component as a mutable value.
Definition at line 201 of file SymmetricDyad.hpp.
References PhQ::SymmetricDyad< NumericType >::xx_xy_xz_yy_yz_zz_.
Mutable_yx()
template<typename NumericType = double> constexpr NumericType& PhQ::SymmetricDyad< NumericType >::Mutable_yx () inline constexpr noexcept
Returns this three-dimensional symmetric dyadic tensor's yx = xy Cartesian component as a mutable value.
Definition at line 207 of file SymmetricDyad.hpp.
References PhQ::SymmetricDyad< NumericType >::xx_xy_xz_yy_yz_zz_.
Mutable_yy()
template<typename NumericType = double> constexpr NumericType& PhQ::SymmetricDyad< NumericType >::Mutable_yy () inline constexpr noexcept
Returns this three-dimensional symmetric dyadic tensor's yy Cartesian component as a mutable value.
Definition at line 213 of file SymmetricDyad.hpp.
References PhQ::SymmetricDyad< NumericType >::xx_xy_xz_yy_yz_zz_.
Mutable_yz()
template<typename NumericType = double> constexpr NumericType& PhQ::SymmetricDyad< NumericType >::Mutable_yz () inline constexpr noexcept
Returns this three-dimensional symmetric dyadic tensor's yz = zy Cartesian component as a mutable value.
Definition at line 219 of file SymmetricDyad.hpp.
References PhQ::SymmetricDyad< NumericType >::xx_xy_xz_yy_yz_zz_.
Mutable_zx()
template<typename NumericType = double> constexpr NumericType& PhQ::SymmetricDyad< NumericType >::Mutable_zx () inline constexpr noexcept
Returns this three-dimensional symmetric dyadic tensor's zx = xz Cartesian component as a mutable value.
Definition at line 225 of file SymmetricDyad.hpp.
References PhQ::SymmetricDyad< NumericType >::xx_xy_xz_yy_yz_zz_.
Mutable_zy()
template<typename NumericType = double> constexpr NumericType& PhQ::SymmetricDyad< NumericType >::Mutable_zy () inline constexpr noexcept
Returns this three-dimensional symmetric dyadic tensor's zy = yz Cartesian component as a mutable value.
Definition at line 231 of file SymmetricDyad.hpp.
References PhQ::SymmetricDyad< NumericType >::xx_xy_xz_yy_yz_zz_.
Mutable_zz()
template<typename NumericType = double> constexpr NumericType& PhQ::SymmetricDyad< NumericType >::Mutable_zz () inline constexpr noexcept
Returns this three-dimensional symmetric dyadic tensor's zz Cartesian component as a mutable value.
Definition at line 237 of file SymmetricDyad.hpp.
References PhQ::SymmetricDyad< NumericType >::xx_xy_xz_yy_yz_zz_.
operator*=()
template<typename NumericType = double> template<typename OtherNumericType > constexpr void PhQ::SymmetricDyad< NumericType >::operator*= (const OtherNumericType number) inline constexpr noexcept
Definition at line 406 of file SymmetricDyad.hpp.
References PhQ::SymmetricDyad< NumericType >::xx_xy_xz_yy_yz_zz_.
operator+=()
template<typename NumericType = double> constexpr void PhQ::SymmetricDyad< NumericType >::operator+= (const SymmetricDyad< NumericType > & symmetric_dyad) inline constexpr noexcept
Definition at line 387 of file SymmetricDyad.hpp.
References PhQ::SymmetricDyad< NumericType >::xx_xy_xz_yy_yz_zz_.
operator-=()
template<typename NumericType = double> constexpr void PhQ::SymmetricDyad< NumericType >::operator-= (const SymmetricDyad< NumericType > & symmetric_dyad) inline constexpr noexcept
Definition at line 396 of file SymmetricDyad.hpp.
References PhQ::SymmetricDyad< NumericType >::xx_xy_xz_yy_yz_zz_.
operator/=()
template<typename NumericType = double> template<typename OtherNumericType > constexpr void PhQ::SymmetricDyad< NumericType >::operator/= (const OtherNumericType number) inline constexpr noexcept
Definition at line 416 of file SymmetricDyad.hpp.
References PhQ::SymmetricDyad< NumericType >::xx_xy_xz_yy_yz_zz_.
operator=() [1/4]
template<typename NumericType = double> constexpr SymmetricDyad<NumericType>& PhQ::SymmetricDyad< NumericType >::operator= (const std::array< NumericType, 6 > & xx_xy_xz_yy_yz_zz) inline constexpr
Assignment operator. Assigns this three-dimensional symmetric dyadic tensor by copying a given array representing its xx, xy, xz, yy, yz, and zz Cartesian components.
Definition at line 114 of file SymmetricDyad.hpp.
References PhQ::SymmetricDyad< NumericType >::xx_xy_xz_yy_yz_zz(), and PhQ::SymmetricDyad< NumericType >::xx_xy_xz_yy_yz_zz_.
operator=() [2/4]
template<typename NumericType = double> constexpr SymmetricDyad<NumericType>& PhQ::SymmetricDyad< NumericType >::operator= (const SymmetricDyad< NumericType > & other) constexpr default
Copy assignment operator. Assigns this three-dimensional symmetric dyadic tensor by copying another one.
operator=() [3/4]
template<typename NumericType = double> template<typename OtherNumericType > constexpr SymmetricDyad<NumericType>& PhQ::SymmetricDyad< NumericType >::operator= (const SymmetricDyad< OtherNumericType > & other) inline constexpr
Copy assignment operator. Assigns this three-dimensional symmetric dyadic tensor by copying another one.
Definition at line 97 of file SymmetricDyad.hpp.
References PhQ::SymmetricDyad< NumericType >::xx(), PhQ::SymmetricDyad< NumericType >::xx_xy_xz_yy_yz_zz_, PhQ::SymmetricDyad< NumericType >::xy(), PhQ::SymmetricDyad< NumericType >::xz(), PhQ::SymmetricDyad< NumericType >::yy(), PhQ::SymmetricDyad< NumericType >::yz(), and PhQ::SymmetricDyad< NumericType >::zz().
operator=() [4/4]
template<typename NumericType = double> constexpr SymmetricDyad<NumericType>& PhQ::SymmetricDyad< NumericType >::operator= (SymmetricDyad< NumericType > && other) constexpr default noexcept
Move assignment operator. Assigns this three-dimensional symmetric dyadic tensor by moving another one.
Print()
template<typename NumericType = double> std::string PhQ::SymmetricDyad< NumericType >::Print () const inline
Prints this three-dimensional symmetric dyadic tensor as a string.
Definition at line 355 of file SymmetricDyad.hpp.
References PhQ::Print(), and PhQ::SymmetricDyad< NumericType >::xx_xy_xz_yy_yz_zz_.
Referenced by PhQ::operator<<().
Set_xx()
template<typename NumericType = double> constexpr void PhQ::SymmetricDyad< NumericType >::Set_xx (const NumericType xx) inline constexpr noexcept
Sets this three-dimensional symmetric dyadic tensor's xx Cartesian component to a given value.
Definition at line 263 of file SymmetricDyad.hpp.
References PhQ::SymmetricDyad< NumericType >::xx(), and PhQ::SymmetricDyad< NumericType >::xx_xy_xz_yy_yz_zz_.
Set_xx_xy_xz_yy_yz_zz() [1/2]
template<typename NumericType = double> constexpr void PhQ::SymmetricDyad< NumericType >::Set_xx_xy_xz_yy_yz_zz (const NumericType xx, const NumericType xy, const NumericType xz, const NumericType yy, const NumericType yz, const NumericType zz) inline constexpr noexcept
Sets this three-dimensional symmetric dyadic tensor's xx, xy, xz, yy, yz, and zz Cartesian components to the given values.
Definition at line 250 of file SymmetricDyad.hpp.
References PhQ::SymmetricDyad< NumericType >::xx(), PhQ::SymmetricDyad< NumericType >::xx_xy_xz_yy_yz_zz_, PhQ::SymmetricDyad< NumericType >::xy(), PhQ::SymmetricDyad< NumericType >::xz(), PhQ::SymmetricDyad< NumericType >::yy(), PhQ::SymmetricDyad< NumericType >::yz(), and PhQ::SymmetricDyad< NumericType >::zz().
Set_xx_xy_xz_yy_yz_zz() [2/2]
template<typename NumericType = double> constexpr void PhQ::SymmetricDyad< NumericType >::Set_xx_xy_xz_yy_yz_zz (const std::array< NumericType, 6 > & xx_xy_xz_yy_yz_zz) inline constexpr noexcept
Sets this three-dimensional symmetric dyadic tensor's xx, xy, xz, yy, yz, and zz Cartesian components to the given values.
Definition at line 243 of file SymmetricDyad.hpp.
References PhQ::SymmetricDyad< NumericType >::xx_xy_xz_yy_yz_zz(), and PhQ::SymmetricDyad< NumericType >::xx_xy_xz_yy_yz_zz_.
Set_xy()
template<typename NumericType = double> constexpr void PhQ::SymmetricDyad< NumericType >::Set_xy (const NumericType xy) inline constexpr noexcept
Sets this three-dimensional symmetric dyadic tensor's xy = yx Cartesian component to a given value.
Definition at line 269 of file SymmetricDyad.hpp.
References PhQ::SymmetricDyad< NumericType >::xx_xy_xz_yy_yz_zz_, and PhQ::SymmetricDyad< NumericType >::xy().
Set_xz()
template<typename NumericType = double> constexpr void PhQ::SymmetricDyad< NumericType >::Set_xz (const NumericType xz) inline constexpr noexcept
Sets this three-dimensional symmetric dyadic tensor's xz = zx Cartesian component to a given value.
Definition at line 275 of file SymmetricDyad.hpp.
References PhQ::SymmetricDyad< NumericType >::xx_xy_xz_yy_yz_zz_, and PhQ::SymmetricDyad< NumericType >::xz().
Set_yx()
template<typename NumericType = double> constexpr void PhQ::SymmetricDyad< NumericType >::Set_yx (const NumericType yx) inline constexpr noexcept
Sets this three-dimensional symmetric dyadic tensor's yx = xy Cartesian component to a given value.
Definition at line 281 of file SymmetricDyad.hpp.
References PhQ::SymmetricDyad< NumericType >::xx_xy_xz_yy_yz_zz_, and PhQ::SymmetricDyad< NumericType >::yx().
Set_yy()
template<typename NumericType = double> constexpr void PhQ::SymmetricDyad< NumericType >::Set_yy (const NumericType yy) inline constexpr noexcept
Sets this three-dimensional symmetric dyadic tensor's yy Cartesian component to a given value.
Definition at line 287 of file SymmetricDyad.hpp.
References PhQ::SymmetricDyad< NumericType >::xx_xy_xz_yy_yz_zz_, and PhQ::SymmetricDyad< NumericType >::yy().
Set_yz()
template<typename NumericType = double> constexpr void PhQ::SymmetricDyad< NumericType >::Set_yz (const NumericType yz) inline constexpr noexcept
Sets this three-dimensional symmetric dyadic tensor's yz = zy Cartesian component to a given value.
Definition at line 293 of file SymmetricDyad.hpp.
References PhQ::SymmetricDyad< NumericType >::xx_xy_xz_yy_yz_zz_, and PhQ::SymmetricDyad< NumericType >::yz().
Set_zx()
template<typename NumericType = double> constexpr void PhQ::SymmetricDyad< NumericType >::Set_zx (const NumericType zx) inline constexpr noexcept
Sets this three-dimensional symmetric dyadic tensor's zx = xz Cartesian component to a given value.
Definition at line 299 of file SymmetricDyad.hpp.
References PhQ::SymmetricDyad< NumericType >::xx_xy_xz_yy_yz_zz_, and PhQ::SymmetricDyad< NumericType >::zx().
Set_zy()
template<typename NumericType = double> constexpr void PhQ::SymmetricDyad< NumericType >::Set_zy (const NumericType zy) inline constexpr noexcept
Sets this three-dimensional symmetric dyadic tensor's zy = yz Cartesian component to a given value.
Definition at line 305 of file SymmetricDyad.hpp.
References PhQ::SymmetricDyad< NumericType >::xx_xy_xz_yy_yz_zz_, and PhQ::SymmetricDyad< NumericType >::zy().
Set_zz()
template<typename NumericType = double> constexpr void PhQ::SymmetricDyad< NumericType >::Set_zz (const NumericType zz) inline constexpr noexcept
Sets this three-dimensional symmetric dyadic tensor's zz Cartesian component to a given value.
Definition at line 311 of file SymmetricDyad.hpp.
References PhQ::SymmetricDyad< NumericType >::xx_xy_xz_yy_yz_zz_, and PhQ::SymmetricDyad< NumericType >::zz().
Trace()
template<typename NumericType = double> constexpr NumericType PhQ::SymmetricDyad< NumericType >::Trace () const inline constexpr noexcept
Returns the trace of this three-dimensional symmetric dyadic tensor.
Definition at line 316 of file SymmetricDyad.hpp.
References PhQ::SymmetricDyad< NumericType >::xx(), PhQ::SymmetricDyad< NumericType >::yy(), and PhQ::SymmetricDyad< NumericType >::zz().
Referenced by PhQ::ConstitutiveModel::ElasticIsotropicSolid< NumericType >::Strain(), PhQ::ConstitutiveModel::CompressibleNewtonianFluid< NumericType >::StrainRate(), PhQ::ConstitutiveModel::ElasticIsotropicSolid< NumericType >::Stress(), and PhQ::ConstitutiveModel::CompressibleNewtonianFluid< NumericType >::Stress().
Transpose()
template<typename NumericType = double> constexpr const SymmetricDyad<NumericType>& PhQ::SymmetricDyad< NumericType >::Transpose () const inline constexpr noexcept
Returns the transpose of this three-dimensional symmetric dyadic tensor.
Definition at line 327 of file SymmetricDyad.hpp.
XML()
template<typename NumericType = double> std::string PhQ::SymmetricDyad< NumericType >::XML () const inline
Serializes this three-dimensional symmetric dyadic tensor as an XML message.
Definition at line 371 of file SymmetricDyad.hpp.
References PhQ::Print(), and PhQ::SymmetricDyad< NumericType >::xx_xy_xz_yy_yz_zz_.
xx()
template<typename NumericType = double> constexpr NumericType PhQ::SymmetricDyad< NumericType >::xx () const inline constexpr noexcept
Returns this three-dimensional symmetric dyadic tensor's xx Cartesian component.
Definition at line 137 of file SymmetricDyad.hpp.
References PhQ::SymmetricDyad< NumericType >::xx_xy_xz_yy_yz_zz_.
Referenced by PhQ::SymmetricDyad< NumericType >::Cofactors(), PhQ::SymmetricDyad< NumericType >::Determinant(), PhQ::Dyad< NumericType >::Dyad(), PhQ::operator*(), PhQ::operator+(), PhQ::operator-(), PhQ::operator/(), PhQ::Dyad< NumericType >::operator=(), PhQ::SymmetricDyad< NumericType >::operator=(), PhQ::SymmetricDyad< NumericType >::Set_xx(), PhQ::SymmetricDyad< NumericType >::Set_xx_xy_xz_yy_yz_zz(), PhQ::SymmetricDyad< NumericType >::SymmetricDyad(), PhQ::SymmetricDyad< NumericType >::Trace(), PhQ::Strain< NumericType >::xx(), PhQ::StrainRate< NumericType >::xx(), PhQ::Stress< NumericType >::xx(), and PhQ::ThermalConductivity< NumericType >::xx().
xx_xy_xz_yy_yz_zz()
template<typename NumericType = double> constexpr const std::array<NumericType, 6>& PhQ::SymmetricDyad< NumericType >::xx_xy_xz_yy_yz_zz () const inline constexpr noexcept
Returns this three-dimensional symmetric dyadic tensor's xx, xy, xz, yy, yz, and zz Cartesian components as an array.
Definition at line 132 of file SymmetricDyad.hpp.
References PhQ::SymmetricDyad< NumericType >::xx_xy_xz_yy_yz_zz_.
Referenced by PhQ::Convert(), PhQ::ConvertStatically(), PhQ::SymmetricDyad< NumericType >::operator=(), and PhQ::SymmetricDyad< NumericType >::Set_xx_xy_xz_yy_yz_zz().
xy()
template<typename NumericType = double> constexpr NumericType PhQ::SymmetricDyad< NumericType >::xy () const inline constexpr noexcept
Returns this three-dimensional symmetric dyadic tensor's xy = yx Cartesian component.
Definition at line 142 of file SymmetricDyad.hpp.
References PhQ::SymmetricDyad< NumericType >::xx_xy_xz_yy_yz_zz_.
Referenced by PhQ::SymmetricDyad< NumericType >::Cofactors(), PhQ::SymmetricDyad< NumericType >::Determinant(), PhQ::Dyad< NumericType >::Dyad(), PhQ::operator*(), PhQ::operator+(), PhQ::operator-(), PhQ::operator/(), PhQ::Dyad< NumericType >::operator=(), PhQ::SymmetricDyad< NumericType >::operator=(), PhQ::SymmetricDyad< NumericType >::Set_xx_xy_xz_yy_yz_zz(), PhQ::SymmetricDyad< NumericType >::Set_xy(), PhQ::SymmetricDyad< NumericType >::SymmetricDyad(), PhQ::Strain< NumericType >::xy(), PhQ::StrainRate< NumericType >::xy(), PhQ::Stress< NumericType >::xy(), and PhQ::ThermalConductivity< NumericType >::xy().
xz()
template<typename NumericType = double> constexpr NumericType PhQ::SymmetricDyad< NumericType >::xz () const inline constexpr noexcept
Returns this three-dimensional symmetric dyadic tensor's xz = zx Cartesian component.
Definition at line 147 of file SymmetricDyad.hpp.
References PhQ::SymmetricDyad< NumericType >::xx_xy_xz_yy_yz_zz_.
Referenced by PhQ::SymmetricDyad< NumericType >::Cofactors(), PhQ::SymmetricDyad< NumericType >::Determinant(), PhQ::Dyad< NumericType >::Dyad(), PhQ::operator*(), PhQ::operator+(), PhQ::operator-(), PhQ::operator/(), PhQ::Dyad< NumericType >::operator=(), PhQ::SymmetricDyad< NumericType >::operator=(), PhQ::SymmetricDyad< NumericType >::Set_xx_xy_xz_yy_yz_zz(), PhQ::SymmetricDyad< NumericType >::Set_xz(), PhQ::SymmetricDyad< NumericType >::SymmetricDyad(), PhQ::Strain< NumericType >::xz(), PhQ::StrainRate< NumericType >::xz(), PhQ::Stress< NumericType >::xz(), and PhQ::ThermalConductivity< NumericType >::xz().
YAML()
template<typename NumericType = double> std::string PhQ::SymmetricDyad< NumericType >::YAML () const inline
Serializes this three-dimensional symmetric dyadic tensor as a YAML message.
Definition at line 380 of file SymmetricDyad.hpp.
References PhQ::Print(), and PhQ::SymmetricDyad< NumericType >::xx_xy_xz_yy_yz_zz_.
yx()
template<typename NumericType = double> constexpr NumericType PhQ::SymmetricDyad< NumericType >::yx () const inline constexpr noexcept
Returns this three-dimensional symmetric dyadic tensor's yx = xy Cartesian component.
Definition at line 152 of file SymmetricDyad.hpp.
References PhQ::SymmetricDyad< NumericType >::xx_xy_xz_yy_yz_zz_.
Referenced by PhQ::SymmetricDyad< NumericType >::Determinant(), PhQ::Dyad< NumericType >::Dyad(), PhQ::operator*(), PhQ::Dyad< NumericType >::operator=(), PhQ::SymmetricDyad< NumericType >::Set_yx(), PhQ::Strain< NumericType >::yx(), PhQ::StrainRate< NumericType >::yx(), PhQ::Stress< NumericType >::yx(), and PhQ::ThermalConductivity< NumericType >::yx().
yy()
template<typename NumericType = double> constexpr NumericType PhQ::SymmetricDyad< NumericType >::yy () const inline constexpr noexcept
Returns this three-dimensional symmetric dyadic tensor's yy Cartesian component.
Definition at line 157 of file SymmetricDyad.hpp.
References PhQ::SymmetricDyad< NumericType >::xx_xy_xz_yy_yz_zz_.
Referenced by PhQ::SymmetricDyad< NumericType >::Cofactors(), PhQ::SymmetricDyad< NumericType >::Determinant(), PhQ::Dyad< NumericType >::Dyad(), PhQ::operator*(), PhQ::operator+(), PhQ::operator-(), PhQ::operator/(), PhQ::Dyad< NumericType >::operator=(), PhQ::SymmetricDyad< NumericType >::operator=(), PhQ::SymmetricDyad< NumericType >::Set_xx_xy_xz_yy_yz_zz(), PhQ::SymmetricDyad< NumericType >::Set_yy(), PhQ::SymmetricDyad< NumericType >::SymmetricDyad(), PhQ::SymmetricDyad< NumericType >::Trace(), PhQ::Strain< NumericType >::yy(), PhQ::StrainRate< NumericType >::yy(), PhQ::Stress< NumericType >::yy(), and PhQ::ThermalConductivity< NumericType >::yy().
yz()
template<typename NumericType = double> constexpr NumericType PhQ::SymmetricDyad< NumericType >::yz () const inline constexpr noexcept
Returns this three-dimensional symmetric dyadic tensor's yz = zy Cartesian component.
Definition at line 162 of file SymmetricDyad.hpp.
References PhQ::SymmetricDyad< NumericType >::xx_xy_xz_yy_yz_zz_.
Referenced by PhQ::SymmetricDyad< NumericType >::Cofactors(), PhQ::SymmetricDyad< NumericType >::Determinant(), PhQ::Dyad< NumericType >::Dyad(), PhQ::operator*(), PhQ::operator+(), PhQ::operator-(), PhQ::operator/(), PhQ::Dyad< NumericType >::operator=(), PhQ::SymmetricDyad< NumericType >::operator=(), PhQ::SymmetricDyad< NumericType >::Set_xx_xy_xz_yy_yz_zz(), PhQ::SymmetricDyad< NumericType >::Set_yz(), PhQ::SymmetricDyad< NumericType >::SymmetricDyad(), PhQ::Strain< NumericType >::yz(), PhQ::StrainRate< NumericType >::yz(), PhQ::Stress< NumericType >::yz(), and PhQ::ThermalConductivity< NumericType >::yz().
Zero()
template<typename NumericType = double> static constexpr SymmetricDyad<NumericType> PhQ::SymmetricDyad< NumericType >::Zero () inline static constexpr
Statically creates a three-dimensional symmetric dyadic tensor with its xx, xy, xz, yy, yz, and zz Cartesian components initialized to zero.
Definition at line 122 of file SymmetricDyad.hpp.
Referenced by PhQ::Strain< NumericType >::Zero(), PhQ::StrainRate< NumericType >::Zero(), PhQ::Stress< NumericType >::Zero(), and PhQ::ThermalConductivity< NumericType >::Zero().
zx()
template<typename NumericType = double> constexpr NumericType PhQ::SymmetricDyad< NumericType >::zx () const inline constexpr noexcept
Returns this three-dimensional symmetric dyadic tensor's zx = xz Cartesian component.
Definition at line 167 of file SymmetricDyad.hpp.
References PhQ::SymmetricDyad< NumericType >::xx_xy_xz_yy_yz_zz_.
Referenced by PhQ::SymmetricDyad< NumericType >::Determinant(), PhQ::Dyad< NumericType >::Dyad(), PhQ::operator*(), PhQ::Dyad< NumericType >::operator=(), PhQ::SymmetricDyad< NumericType >::Set_zx(), PhQ::Strain< NumericType >::zx(), PhQ::StrainRate< NumericType >::zx(), PhQ::Stress< NumericType >::zx(), and PhQ::ThermalConductivity< NumericType >::zx().
zy()
template<typename NumericType = double> constexpr NumericType PhQ::SymmetricDyad< NumericType >::zy () const inline constexpr noexcept
Returns this three-dimensional symmetric dyadic tensor's zy = yz Cartesian component.
Definition at line 172 of file SymmetricDyad.hpp.
References PhQ::SymmetricDyad< NumericType >::xx_xy_xz_yy_yz_zz_.
Referenced by PhQ::SymmetricDyad< NumericType >::Determinant(), PhQ::Dyad< NumericType >::Dyad(), PhQ::operator*(), PhQ::Dyad< NumericType >::operator=(), PhQ::SymmetricDyad< NumericType >::Set_zy(), PhQ::Strain< NumericType >::zy(), PhQ::StrainRate< NumericType >::zy(), PhQ::Stress< NumericType >::zy(), and PhQ::ThermalConductivity< NumericType >::zy().
zz()
template<typename NumericType = double> constexpr NumericType PhQ::SymmetricDyad< NumericType >::zz () const inline constexpr noexcept
Returns this three-dimensional symmetric dyadic tensor's zz Cartesian component.
Definition at line 177 of file SymmetricDyad.hpp.
References PhQ::SymmetricDyad< NumericType >::xx_xy_xz_yy_yz_zz_.
Referenced by PhQ::SymmetricDyad< NumericType >::Cofactors(), PhQ::SymmetricDyad< NumericType >::Determinant(), PhQ::Dyad< NumericType >::Dyad(), PhQ::operator*(), PhQ::operator+(), PhQ::operator-(), PhQ::operator/(), PhQ::Dyad< NumericType >::operator=(), PhQ::SymmetricDyad< NumericType >::operator=(), PhQ::SymmetricDyad< NumericType >::Set_xx_xy_xz_yy_yz_zz(), PhQ::SymmetricDyad< NumericType >::Set_zz(), PhQ::SymmetricDyad< NumericType >::SymmetricDyad(), PhQ::SymmetricDyad< NumericType >::Trace(), PhQ::Strain< NumericType >::zz(), PhQ::StrainRate< NumericType >::zz(), PhQ::Stress< NumericType >::zz(), and PhQ::ThermalConductivity< NumericType >::zz().
Member Data Documentation
xx_xy_xz_yy_yz_zz_
template<typename NumericType = double> std::array<NumericType, 6> PhQ::SymmetricDyad< NumericType >::xx_xy_xz_yy_yz_zz_ private
Cartesian components of this three-dimensional symmetric dyadic tensor.
Definition at line 427 of file SymmetricDyad.hpp.
Referenced by PhQ::SymmetricDyad< NumericType >::JSON(), PhQ::SymmetricDyad< NumericType >::Mutable_xx(), PhQ::SymmetricDyad< NumericType >::Mutable_xx_xy_xz_yy_yz_zz(), PhQ::SymmetricDyad< NumericType >::Mutable_xy(), PhQ::SymmetricDyad< NumericType >::Mutable_xz(), PhQ::SymmetricDyad< NumericType >::Mutable_yx(), PhQ::SymmetricDyad< NumericType >::Mutable_yy(), PhQ::SymmetricDyad< NumericType >::Mutable_yz(), PhQ::SymmetricDyad< NumericType >::Mutable_zx(), PhQ::SymmetricDyad< NumericType >::Mutable_zy(), PhQ::SymmetricDyad< NumericType >::Mutable_zz(), PhQ::SymmetricDyad< NumericType >::operator*=(), PhQ::SymmetricDyad< NumericType >::operator+=(), PhQ::SymmetricDyad< NumericType >::operator-=(), PhQ::SymmetricDyad< NumericType >::operator/=(), PhQ::SymmetricDyad< NumericType >::operator=(), PhQ::SymmetricDyad< NumericType >::Print(), PhQ::SymmetricDyad< NumericType >::Set_xx(), PhQ::SymmetricDyad< NumericType >::Set_xx_xy_xz_yy_yz_zz(), PhQ::SymmetricDyad< NumericType >::Set_xy(), PhQ::SymmetricDyad< NumericType >::Set_xz(), PhQ::SymmetricDyad< NumericType >::Set_yx(), PhQ::SymmetricDyad< NumericType >::Set_yy(), PhQ::SymmetricDyad< NumericType >::Set_yz(), PhQ::SymmetricDyad< NumericType >::Set_zx(), PhQ::SymmetricDyad< NumericType >::Set_zy(), PhQ::SymmetricDyad< NumericType >::Set_zz(), PhQ::SymmetricDyad< NumericType >::XML(), PhQ::SymmetricDyad< NumericType >::xx(), PhQ::SymmetricDyad< NumericType >::xx_xy_xz_yy_yz_zz(), PhQ::SymmetricDyad< NumericType >::xy(), PhQ::SymmetricDyad< NumericType >::xz(), PhQ::SymmetricDyad< NumericType >::YAML(), PhQ::SymmetricDyad< NumericType >::yx(), PhQ::SymmetricDyad< NumericType >::yy(), PhQ::SymmetricDyad< NumericType >::yz(), PhQ::SymmetricDyad< NumericType >::zx(), PhQ::SymmetricDyad< NumericType >::zy(), and PhQ::SymmetricDyad< NumericType >::zz().
The documentation for this class was generated from the following file:
PhQ/SymmetricDyad.hpp