Physical Quantities (PhQ): PhQ::PlanarDirection< NumericType > Class Template Reference
PhQ::PlanarDirection< NumericType > Class Template Reference
two-dimensional Euclidean direction vector in the XY plane. Contains two components in Cartesian coordinates: x and y. Guaranteed to be either a unit vector or the zero vector (0, 0). For a three-dimensional Euclidean direction vector, see PhQ::Direction.
#include "PlanarDirection.hpp"
Public Member Functions
constexpr PlanarDirection ()
Default constructor. Initializes a planar direction to the zero planar vector.
PlanarDirection (const NumericType x, const NumericType y)
Constructor. Constructs a planar direction by normalizing the given x and y Cartesian components to a unit planar vector. If x = 0 and y = 0, initializes the planar direction to the zero planar vector.
PlanarDirection (const std::array< NumericType, 2 > &x_y)
Constructor. Constructs a planar direction by normalizing a given array representing x and y Cartesian components to a unit planar vector. If x = 0 and y = 0, initializes the planar direction to the zero planar vector.
PlanarDirection (const PlanarVector< NumericType > &value)
Constructor. Constructs a planar direction by normalizing the given planar vector to a unit planar vector. If the given planar vector is the zero planar vector, initializes the planar direction to the zero planar vector.
constexpr PlanarDirection (const Direction< NumericType > &direction)
Constructor. Constructs a planar direction from a given direction by projecting the direction onto the XY plane.
PlanarDirection (const PlanarAcceleration< NumericType > &planar_acceleration)
Constructor. Constructs a planar direction from a planar acceleration.
PlanarDirection (const PlanarDisplacement< NumericType > &planar_displacement)
Constructor. Constructs a planar direction from a planar displacement.
PlanarDirection (const PlanarForce< NumericType > &planar_force)
Constructor. Constructs a planar direction from a planar force.
PlanarDirection (const PlanarHeatFlux< NumericType > &planar_heat_flux)
Constructor. Constructs a planar direction from a planar heat flux.
PlanarDirection (const PlanarPosition< NumericType > &planar_position)
Constructor. Constructs a planar direction from a planar position.
PlanarDirection (const PlanarTemperatureGradient< NumericType > &planar_temperature_gradient)
Constructor. Constructs a planar direction from a planar temperature gradient.
PlanarDirection (const PlanarTraction< NumericType > &planar_traction)
Constructor. Constructs a planar direction from a planar traction.
PlanarDirection (const PlanarVectorArea< NumericType > &planar_vector_area)
Constructor. Constructs a planar direction from a planar vector area.
PlanarDirection (const PlanarVelocity< NumericType > &planar_velocity)
Constructor. Constructs a planar direction from a planar velocity.
~PlanarDirection () noexcept=default
Destructor. Destroys this planar direction.
constexpr PlanarDirection (const PlanarDirection< NumericType > &other)=default
Copy constructor. Constructs a planar direction by copying another one.
template<typename OtherNumericType >
constexpr PlanarDirection (const PlanarDirection< OtherNumericType > &other)
Copy constructor. Constructs a planar direction by copying another one.
constexpr PlanarDirection (PlanarDirection< NumericType > &&other) noexcept=default
Move constructor. Constructs a planar direction by moving another one.
constexpr PlanarDirection< NumericType > & operator= (const PlanarDirection< NumericType > &other)=default
Copy assignment operator. Assigns this planar direction by copying another one.
template<typename OtherNumericType >
constexpr PlanarDirection< NumericType > & operator= (const PlanarDirection< OtherNumericType > &other)
Copy assignment operator. Assigns this planar direction by copying another one.
constexpr PlanarDirection< NumericType > & operator= (PlanarDirection< NumericType > &&other) noexcept=default
Move assignment operator. Assigns the value of this planar direction by moving another one.
constexpr NumericType x () const noexcept
Returns the x Cartesian component of this planar direction.
constexpr NumericType y () const noexcept
Returns the y Cartesian component of this planar direction.
constexpr void Set (const NumericType x, const NumericType y)
Sets the value of this planar direction by normalizing the given x and y Cartesian components to a unit planar vector. If x = 0 and y = 0, sets the planar direction to the zero planar vector.
constexpr void Set (const std::array< NumericType, 2 > &x_y)
Sets the value of this planar direction by normalizing the given x and y Cartesian components to a unit planar vector. If x = 0 and y = 0, sets the planar direction to the zero planar vector.
constexpr void Set (const PlanarVector< NumericType > &value)
Sets the value of this planar direction by normalizing the given planar vector to a unit planar vector. If the given planar vector is the zero planar vector, sets the planar direction to the zero planar vector.
constexpr NumericType MagnitudeSquared () const noexcept
Returns the square of the magnitude of this planar direction. This is guaranteed to be exactly 1 if the planar direction is not the zero planar vector, or 0 if the planar direction is the zero planar vector.
NumericType Magnitude () const noexcept
Returns the magnitude of this planar direction. This is guaranteed to be exactly 1 if the planar direction is not the zero planar vector, or 0 if the planar direction is the zero planar vector.
constexpr NumericType Dot (const PlanarVector< NumericType > &planar_vector) const noexcept
Returns the dot product (also known as the scalar product or the inner product) of this planar direction with the given planar vector.
constexpr NumericType Dot (const PlanarDirection< NumericType > &planar_direction) const noexcept
Returns the dot product (also known as the scalar product or the inner product) of this planar direction with the given other planar direction.
constexpr Vector< NumericType > Cross (const PlanarVector< NumericType > &planar_vector) const
Returns the cross product of this planar direction with the given planar vector.
Direction< NumericType > Cross (const PlanarDirection< NumericType > &planar_direction) const
Returns the cross product of this planar direction with the given other planar direction.
constexpr Dyad< NumericType > Dyadic (const PlanarVector< NumericType > &planar_vector) const
Returns the dyadic product of this planar direction with the given planar vector.
constexpr Dyad< NumericType > Dyadic (const PlanarDirection< NumericType > &planar_direction) const
Returns the dyadic product of this planar direction with the given other planar direction.
PhQ::Angle< NumericType > Angle (const PlanarVector< NumericType > &planar_vector) const
Returns the angle between this planar direction and the given planar vector.
PhQ::Angle< NumericType > Angle (const PlanarDirection< NumericType > &planar_direction) const
Returns the angle between this planar direction and the given other planar direction.
constexpr PlanarAcceleration< NumericType > operator* (const ScalarAcceleration< NumericType > &scalar_acceleration) const
constexpr PlanarVectorArea< NumericType > operator* (const Area< NumericType > &area) const
constexpr PlanarPosition< NumericType > operator* (const Length< NumericType > &length) const
constexpr PlanarForce< NumericType > operator* (const ScalarForce< NumericType > &scalar_force) const
constexpr PlanarHeatFlux< NumericType > operator* (const ScalarHeatFlux< NumericType > &scalar_heat_flux) const
constexpr PlanarTemperatureGradient< NumericType > operator* (const ScalarTemperatureGradient< NumericType > &scalar_temperature_gradient) const
constexpr PlanarTraction< NumericType > operator* (const ScalarTraction< NumericType > &scalar_traction) const
constexpr PlanarVelocity< NumericType > operator* (const Speed< NumericType > &speed) const
constexpr const PhQ::PlanarVector< double > & Value () const noexcept
Value of this physical quantity.
std::string Print () const
Prints this physical quantity as a string.
std::string JSON () const
Serializes this physical quantity as a JSON message.
std::string XML () const
Serializes this physical quantity as an XML message.
std::string YAML () const
Serializes this physical quantity as a YAML message.
Static Public Member Functions
static constexpr PlanarDirection< NumericType > Zero ()
Statically creates a planar direction whose value is the zero vector.
static constexpr PhQ::Dimensions Dimensions ()
Physical dimension set of this physical quantity. Since this physical quantity is dimensionless, its physical dimension set is simply the null set.
Protected Attributes
PhQ::PlanarVector< double > value
Value of this physical quantity.
Detailed Description
template<typename NumericType = double>
class PhQ::PlanarDirection< NumericType >
two-dimensional Euclidean direction vector in the XY plane. Contains two components in Cartesian coordinates: x and y. Guaranteed to be either a unit vector or the zero vector (0, 0). For a three-dimensional Euclidean direction vector, see PhQ::Direction.
Definition at line 115 of file PlanarDirection.hpp.
Constructor & Destructor Documentation
PlanarDirection() [1/17]
template<typename NumericType = double> constexpr PhQ::PlanarDirection< NumericType >::PlanarDirection () inline constexpr
Default constructor. Initializes a planar direction to the zero planar vector.
Definition at line 118 of file PlanarDirection.hpp.
PlanarDirection() [2/17]
template<typename NumericType = double> PhQ::PlanarDirection< NumericType >::PlanarDirection (const NumericType x, const NumericType y) inline
Constructor. Constructs a planar direction by normalizing the given x and y Cartesian components to a unit planar vector. If x = 0 and y = 0, initializes the planar direction to the zero planar vector.
Definition at line 124 of file PlanarDirection.hpp.
References PhQ::PlanarDirection< NumericType >::Set(), PhQ::PlanarDirection< NumericType >::x(), and PhQ::PlanarDirection< NumericType >::y().
PlanarDirection() [3/17]
template<typename NumericType = double> PhQ::PlanarDirection< NumericType >::PlanarDirection (const std::array< NumericType, 2 > & x_y) inline explicit
Constructor. Constructs a planar direction by normalizing a given array representing x and y Cartesian components to a unit planar vector. If x = 0 and y = 0, initializes the planar direction to the zero planar vector.
Definition at line 132 of file PlanarDirection.hpp.
References PhQ::PlanarDirection< NumericType >::Set().
PlanarDirection() [4/17]
template<typename NumericType = double> PhQ::PlanarDirection< NumericType >::PlanarDirection (const PlanarVector< NumericType > & value) inline explicit
Constructor. Constructs a planar direction by normalizing the given planar vector to a unit planar vector. If the given planar vector is the zero planar vector, initializes the planar direction to the zero planar vector.
Definition at line 140 of file PlanarDirection.hpp.
References PhQ::PlanarDirection< NumericType >::Set(), and PhQ::DimensionlessPlanarVector< double >::value.
PlanarDirection() [5/17]
template<typename NumericType > constexpr PhQ::PlanarDirection< NumericType >::PlanarDirection (const Direction< NumericType > & direction) inline explicit constexpr
Constructor. Constructs a planar direction from a given direction by projecting the direction onto the XY plane.
Definition at line 433 of file Direction.hpp.
References PhQ::DimensionlessVector< NumericType >::Value().
PlanarDirection() [6/17]
template<typename NumericType > PhQ::PlanarDirection< NumericType >::PlanarDirection (const PlanarAcceleration< NumericType > & planar_acceleration) inline explicit
Constructor. Constructs a planar direction from a planar acceleration.
Definition at line 277 of file PlanarAcceleration.hpp.
PlanarDirection() [7/17]
template<typename NumericType > PhQ::PlanarDirection< NumericType >::PlanarDirection (const PlanarDisplacement< NumericType > & planar_displacement) inline explicit
Constructor. Constructs a planar direction from a planar displacement.
Definition at line 306 of file PlanarDisplacement.hpp.
PlanarDirection() [8/17]
template<typename NumericType > PhQ::PlanarDirection< NumericType >::PlanarDirection (const PlanarForce< NumericType > & planar_force) inline explicit
Constructor. Constructs a planar direction from a planar force.
Definition at line 256 of file PlanarForce.hpp.
PlanarDirection() [9/17]
template<typename NumericType > PhQ::PlanarDirection< NumericType >::PlanarDirection (const PlanarHeatFlux< NumericType > & planar_heat_flux) inline explicit
Constructor. Constructs a planar direction from a planar heat flux.
Definition at line 274 of file PlanarHeatFlux.hpp.
PlanarDirection() [10/17]
template<typename NumericType > PhQ::PlanarDirection< NumericType >::PlanarDirection (const PlanarPosition< NumericType > & planar_position) inline explicit
Constructor. Constructs a planar direction from a planar position.
Definition at line 279 of file PlanarPosition.hpp.
PlanarDirection() [11/17]
template<typename NumericType > PhQ::PlanarDirection< NumericType >::PlanarDirection (const PlanarTemperatureGradient< NumericType > & planar_temperature_gradient) inline explicit
Constructor. Constructs a planar direction from a planar temperature gradient.
Definition at line 274 of file PlanarTemperatureGradient.hpp.
PlanarDirection() [12/17]
template<typename NumericType > PhQ::PlanarDirection< NumericType >::PlanarDirection (const PlanarTraction< NumericType > & planar_traction) inline explicit
Constructor. Constructs a planar direction from a planar traction.
Definition at line 273 of file PlanarTraction.hpp.
PlanarDirection() [13/17]
template<typename NumericType = double> PhQ::PlanarDirection< NumericType >::PlanarDirection (const PlanarVectorArea< NumericType > & planar_vector_area) explicit
Constructor. Constructs a planar direction from a planar vector area.
PlanarDirection() [14/17]
template<typename NumericType > PhQ::PlanarDirection< NumericType >::PlanarDirection (const PlanarVelocity< NumericType > & planar_velocity) inline explicit
Constructor. Constructs a planar direction from a planar velocity.
Definition at line 292 of file PlanarVelocity.hpp.
~PlanarDirection()
template<typename NumericType = double> PhQ::PlanarDirection< NumericType >::~PlanarDirection () default noexcept
Destructor. Destroys this planar direction.
PlanarDirection() [15/17]
template<typename NumericType = double> constexpr PhQ::PlanarDirection< NumericType >::PlanarDirection (const PlanarDirection< NumericType > & other) constexpr default
Copy constructor. Constructs a planar direction by copying another one.
PlanarDirection() [16/17]
template<typename NumericType = double> template<typename OtherNumericType > constexpr PhQ::PlanarDirection< NumericType >::PlanarDirection (const PlanarDirection< OtherNumericType > & other) inline explicit constexpr
Copy constructor. Constructs a planar direction by copying another one.
Definition at line 185 of file PlanarDirection.hpp.
PlanarDirection() [17/17]
template<typename NumericType = double> constexpr PhQ::PlanarDirection< NumericType >::PlanarDirection (PlanarDirection< NumericType > && other) constexpr default noexcept
Move constructor. Constructs a planar direction by moving another one.
Member Function Documentation
Angle() [1/2]
template<typename NumericType = double> PhQ::Angle<NumericType> PhQ::PlanarDirection< NumericType >::Angle (const PlanarDirection< NumericType > & planar_direction) const inline
Returns the angle between this planar direction and the given other planar direction.
Definition at line 315 of file PlanarDirection.hpp.
Angle() [2/2]
template<typename NumericType = double> PhQ::Angle<NumericType> PhQ::PlanarDirection< NumericType >::Angle (const PlanarVector< NumericType > & planar_vector) const inline
Returns the angle between this planar direction and the given planar vector.
Definition at line 309 of file PlanarDirection.hpp.
Cross() [1/2]
template<typename NumericType > Direction< NumericType > PhQ::PlanarDirection< NumericType >::Cross (const PlanarDirection< NumericType > & planar_direction) const
Returns the cross product of this planar direction with the given other planar direction.
Definition at line 438 of file Direction.hpp.
References PhQ::Direction< NumericType >::Cross(), and PhQ::DimensionlessPlanarVector< NumericType >::value.
Cross() [2/2]
template<typename NumericType = double> constexpr Vector<NumericType> PhQ::PlanarDirection< NumericType >::Cross (const PlanarVector< NumericType > & planar_vector) const inline constexpr
Returns the cross product of this planar direction with the given planar vector.
Definition at line 285 of file PlanarDirection.hpp.
References PhQ::PlanarVector< NumericType >::Cross(), and PhQ::DimensionlessPlanarVector< double >::value.
Dimensions()
static constexpr PhQ::Dimensions PhQ::DimensionlessPlanarVector< double >::Dimensions () inline static constexpr inherited
Physical dimension set of this physical quantity. Since this physical quantity is dimensionless, its physical dimension set is simply the null set.
Definition at line 53 of file DimensionlessPlanarVector.hpp.
Dot() [1/2]
template<typename NumericType = double> constexpr NumericType PhQ::PlanarDirection< NumericType >::Dot (const PlanarDirection< NumericType > & planar_direction) const inline constexpr noexcept
Returns the dot product (also known as the scalar product or the inner product) of this planar direction with the given other planar direction.
Definition at line 279 of file PlanarDirection.hpp.
References PhQ::PlanarVector< NumericType >::Dot(), and PhQ::DimensionlessPlanarVector< double >::value.
Dot() [2/2]
template<typename NumericType = double> constexpr NumericType PhQ::PlanarDirection< NumericType >::Dot (const PlanarVector< NumericType > & planar_vector) const inline constexpr noexcept
Returns the dot product (also known as the scalar product or the inner product) of this planar direction with the given planar vector.
Definition at line 272 of file PlanarDirection.hpp.
References PhQ::PlanarVector< NumericType >::Dot(), and PhQ::DimensionlessPlanarVector< double >::value.
Dyadic() [1/2]
template<typename NumericType = double> constexpr Dyad<NumericType> PhQ::PlanarDirection< NumericType >::Dyadic (const PlanarDirection< NumericType > & planar_direction) const inline constexpr
Returns the dyadic product of this planar direction with the given other planar direction.
Definition at line 303 of file PlanarDirection.hpp.
References PhQ::PlanarVector< NumericType >::Dyadic(), PhQ::DimensionlessPlanarVector< NumericType >::value, and PhQ::DimensionlessPlanarVector< double >::value.
Dyadic() [2/2]
template<typename NumericType = double> constexpr Dyad<NumericType> PhQ::PlanarDirection< NumericType >::Dyadic (const PlanarVector< NumericType > & planar_vector) const inline constexpr
Returns the dyadic product of this planar direction with the given planar vector.
Definition at line 296 of file PlanarDirection.hpp.
References PhQ::PlanarVector< NumericType >::Dyadic(), and PhQ::DimensionlessPlanarVector< double >::value.
JSON()
std::string PhQ::DimensionlessPlanarVector< double >::JSON () const inline inherited
Serializes this physical quantity as a JSON message.
Definition at line 68 of file DimensionlessPlanarVector.hpp.
Magnitude()
template<typename NumericType = double> NumericType PhQ::PlanarDirection< NumericType >::Magnitude () const inline noexcept
Returns the magnitude of this planar direction. This is guaranteed to be exactly 1 if the planar direction is not the zero planar vector, or 0 if the planar direction is the zero planar vector.
Definition at line 266 of file PlanarDirection.hpp.
References PhQ::PlanarVector< NumericType >::Magnitude(), and PhQ::DimensionlessPlanarVector< double >::value.
MagnitudeSquared()
template<typename NumericType = double> constexpr NumericType PhQ::PlanarDirection< NumericType >::MagnitudeSquared () const inline constexpr noexcept
Returns the square of the magnitude of this planar direction. This is guaranteed to be exactly 1 if the planar direction is not the zero planar vector, or 0 if the planar direction is the zero planar vector.
Definition at line 259 of file PlanarDirection.hpp.
References PhQ::PlanarVector< NumericType >::MagnitudeSquared(), and PhQ::DimensionlessPlanarVector< double >::value.
operator*() [1/8]
template<typename NumericType = double> constexpr PlanarVectorArea<NumericType> PhQ::PlanarDirection< NumericType >::operator* (const Area< NumericType > & area) const constexpr
operator*() [2/8]
template<typename NumericType > constexpr PlanarPosition< NumericType > PhQ::PlanarDirection< NumericType >::operator* (const Length< NumericType > & length) const inline constexpr
Definition at line 306 of file PlanarPosition.hpp.
operator*() [3/8]
template<typename NumericType > constexpr PlanarAcceleration< NumericType > PhQ::PlanarDirection< NumericType >::operator* (const ScalarAcceleration< NumericType > & scalar_acceleration) const inline constexpr
Definition at line 298 of file PlanarAcceleration.hpp.
operator*() [4/8]
template<typename NumericType > constexpr PlanarForce< NumericType > PhQ::PlanarDirection< NumericType >::operator* (const ScalarForce< NumericType > & scalar_force) const inline constexpr
Definition at line 265 of file PlanarForce.hpp.
operator*() [5/8]
template<typename NumericType > constexpr PlanarHeatFlux< NumericType > PhQ::PlanarDirection< NumericType >::operator* (const ScalarHeatFlux< NumericType > & scalar_heat_flux) const inline constexpr
Definition at line 284 of file PlanarHeatFlux.hpp.
operator*() [6/8]
template<typename NumericType > constexpr PlanarTemperatureGradient< NumericType > PhQ::PlanarDirection< NumericType >::operator* (const ScalarTemperatureGradient< NumericType > & scalar_temperature_gradient) const inline constexpr
Definition at line 286 of file PlanarTemperatureGradient.hpp.
operator*() [7/8]
template<typename NumericType > constexpr PlanarTraction< NumericType > PhQ::PlanarDirection< NumericType >::operator* (const ScalarTraction< NumericType > & scalar_traction) const inline constexpr
Definition at line 288 of file PlanarTraction.hpp.
operator*() [8/8]
template<typename NumericType > constexpr PlanarVelocity< NumericType > PhQ::PlanarDirection< NumericType >::operator* (const Speed< NumericType > & speed) const inline constexpr
Definition at line 312 of file PlanarVelocity.hpp.
operator=() [1/3]
template<typename NumericType = double> constexpr PlanarDirection<NumericType>& PhQ::PlanarDirection< NumericType >::operator= (const PlanarDirection< NumericType > & other) constexpr default
Copy assignment operator. Assigns this planar direction by copying another one.
operator=() [2/3]
template<typename NumericType = double> template<typename OtherNumericType > constexpr PlanarDirection<NumericType>& PhQ::PlanarDirection< NumericType >::operator= (const PlanarDirection< OtherNumericType > & other) inline constexpr
Copy assignment operator. Assigns this planar direction by copying another one.
Definition at line 197 of file PlanarDirection.hpp.
References PhQ::DimensionlessPlanarVector< NumericType >::Value(), and PhQ::DimensionlessPlanarVector< double >::value.
operator=() [3/3]
template<typename NumericType = double> constexpr PlanarDirection<NumericType>& PhQ::PlanarDirection< NumericType >::operator= (PlanarDirection< NumericType > && other) constexpr default noexcept
Move assignment operator. Assigns the value of this planar direction by moving another one.
Print()
std::string PhQ::DimensionlessPlanarVector< double >::Print () const inline inherited
Prints this physical quantity as a string.
Definition at line 63 of file DimensionlessPlanarVector.hpp.
Set() [1/3]
template<typename NumericType = double> constexpr void PhQ::PlanarDirection< NumericType >::Set (const NumericType x, const NumericType y) inline constexpr
Sets the value of this planar direction by normalizing the given x and y Cartesian components to a unit planar vector. If x = 0 and y = 0, sets the planar direction to the zero planar vector.
Definition at line 226 of file PlanarDirection.hpp.
References PhQ::PlanarDirection< NumericType >::x(), and PhQ::PlanarDirection< NumericType >::y().
Referenced by PhQ::PlanarDirection< NumericType >::PlanarDirection(), and PhQ::PlanarDirection< NumericType >::Set().
Set() [2/3]
template<typename NumericType = double> constexpr void PhQ::PlanarDirection< NumericType >::Set (const PlanarVector< NumericType > & value) inline constexpr
Sets the value of this planar direction by normalizing the given planar vector to a unit planar vector. If the given planar vector is the zero planar vector, sets the planar direction to the zero planar vector.
Definition at line 252 of file PlanarDirection.hpp.
References PhQ::PlanarDirection< NumericType >::Set(), PhQ::DimensionlessPlanarVector< double >::value, and PhQ::PlanarVector< NumericType >::x_y().
Set() [3/3]
template<typename NumericType = double> constexpr void PhQ::PlanarDirection< NumericType >::Set (const std::array< NumericType, 2 > & x_y) inline constexpr
Sets the value of this planar direction by normalizing the given x and y Cartesian components to a unit planar vector. If x = 0 and y = 0, sets the planar direction to the zero planar vector.
Definition at line 239 of file PlanarDirection.hpp.
Value()
constexpr const PhQ::PlanarVector<double >& PhQ::DimensionlessPlanarVector< double >::Value () const inline constexpr noexcept inherited
Value of this physical quantity.
Definition at line 58 of file DimensionlessPlanarVector.hpp.
x()
template<typename NumericType = double> constexpr NumericType PhQ::PlanarDirection< NumericType >::x () const inline constexpr noexcept
Returns the x Cartesian component of this planar direction.
Definition at line 214 of file PlanarDirection.hpp.
References PhQ::DimensionlessPlanarVector< double >::value, and PhQ::PlanarVector< NumericType >::x().
Referenced by PhQ::PlanarDirection< NumericType >::PlanarDirection(), and PhQ::PlanarDirection< NumericType >::Set().
XML()
std::string PhQ::DimensionlessPlanarVector< double >::XML () const inline inherited
Serializes this physical quantity as an XML message.
Definition at line 73 of file DimensionlessPlanarVector.hpp.
y()
template<typename NumericType = double> constexpr NumericType PhQ::PlanarDirection< NumericType >::y () const inline constexpr noexcept
Returns the y Cartesian component of this planar direction.
Definition at line 219 of file PlanarDirection.hpp.
References PhQ::DimensionlessPlanarVector< double >::value, and PhQ::PlanarVector< NumericType >::y().
Referenced by PhQ::PlanarDirection< NumericType >::PlanarDirection(), and PhQ::PlanarDirection< NumericType >::Set().
YAML()
std::string PhQ::DimensionlessPlanarVector< double >::YAML () const inline inherited
Serializes this physical quantity as a YAML message.
Definition at line 78 of file DimensionlessPlanarVector.hpp.
Zero()
template<typename NumericType = double> static constexpr PlanarDirection<NumericType> PhQ::PlanarDirection< NumericType >::Zero () inline static constexpr
Statically creates a planar direction whose value is the zero vector.
Definition at line 209 of file PlanarDirection.hpp.
Member Data Documentation
value
PhQ::PlanarVector<double > PhQ::DimensionlessPlanarVector< double >::value protected inherited
Value of this physical quantity.
Definition at line 141 of file DimensionlessPlanarVector.hpp.
The documentation for this class was generated from the following files:
PhQ/Angle.hpp
PhQ/PlanarDirection.hpp
PhQ/Direction.hpp
PhQ/PlanarAcceleration.hpp
PhQ/PlanarDisplacement.hpp
PhQ/PlanarForce.hpp
PhQ/PlanarHeatFlux.hpp
PhQ/PlanarPosition.hpp
PhQ/PlanarTemperatureGradient.hpp
PhQ/PlanarTraction.hpp
PhQ/PlanarVelocity.hpp