Physical Quantities: PhQ::TemperatureGradient< NumericType > Class Template Reference
PhQ::TemperatureGradient< NumericType > Class Template Reference
Three-dimensional Euclidean temperature gradient vector. Contains three components in Cartesian coordinates: x, y, and z. For a two-dimensional Euclidean temperature gradient vector in the XY plane, see PhQ::PlanarTemperatureGradient. For scalar temperature gradient components or for the magnitude of a temperature gradient vector, see PhQ::ScalarTemperatureGradient.
#include "TemperatureGradient.hpp"
Public Member Functions
TemperatureGradient ()=default
Default constructor. Constructs a temperature gradient vector with an uninitialized value.
TemperatureGradient (const Vector< NumericType > &value, const Unit::TemperatureGradient unit)
Constructor. Constructs a temperature gradient vector with a given value expressed in a given temperature gradient unit.
TemperatureGradient (const ScalarTemperatureGradient< NumericType > &x, const ScalarTemperatureGradient< NumericType > &y, const ScalarTemperatureGradient< NumericType > &z)
Constructor. Constructs a temperature gradient vector from a given set of scalar temperature gradient components.
constexpr TemperatureGradient (const ScalarTemperatureGradient< NumericType > &scalar_temperature_gradient, const Direction< NumericType > &direction)
Constructor. Constructs a temperature gradient vector from a given scalar temperature gradient magnitude and direction.
constexpr TemperatureGradient (const PlanarTemperatureGradient< NumericType > &planar_temperature_gradient)
Constructor. Constructs a temperature gradient vector from a given planar temperature gradient vector in the XY plane. This temperature gradient vector's z-component is initialized to zero.
~TemperatureGradient () noexcept=default
Destructor. Destroys this temperature gradient vector.
constexpr TemperatureGradient (const TemperatureGradient< NumericType > &other)=default
Copy constructor. Constructs a temperature gradient vector by copying another one.
template<typename OtherNumericType >
constexpr TemperatureGradient (const TemperatureGradient< OtherNumericType > &other)
Copy constructor. Constructs a temperature gradient vector by copying another one.
constexpr TemperatureGradient (TemperatureGradient< NumericType > &&other) noexcept=default
Move constructor. Constructs a temperature gradient vector by moving another one.
constexpr TemperatureGradient< NumericType > & operator= (const TemperatureGradient< NumericType > &other)=default
Copy assignment operator. Assigns this temperature gradient vector by copying another one.
template<typename OtherNumericType >
constexpr TemperatureGradient< NumericType > & operator= (const TemperatureGradient< OtherNumericType > &other)
Copy assignment operator. Assigns this temperature gradient vector by copying another one.
constexpr TemperatureGradient< NumericType > & operator= (TemperatureGradient< NumericType > &&other) noexcept=default
Move assignment operator. Assigns this temperature gradient vector by moving another one.
constexpr ScalarTemperatureGradient< NumericType > x () const noexcept
Returns the x Cartesian component of this temperature gradient vector.
constexpr ScalarTemperatureGradient< NumericType > y () const noexcept
Returns the y Cartesian component of this temperature gradient vector.
constexpr ScalarTemperatureGradient< NumericType > z () const noexcept
Returns the z Cartesian component of this temperature gradient vector.
ScalarTemperatureGradient< NumericType > Magnitude () const
Returns the magnitude of this temperature gradient vector.
PhQ::Direction< NumericType > Direction () const
Returns the direction of this temperature gradient vector.
PhQ::Angle< NumericType > Angle (const TemperatureGradient< NumericType > &temperature_gradient) const
Returns the angle between this temperature gradient vector and another one.
constexpr TemperatureGradient< NumericType > operator+ (const TemperatureGradient< NumericType > &temperature_gradient) const
constexpr TemperatureGradient< NumericType > operator- (const TemperatureGradient< NumericType > &temperature_gradient) const
constexpr TemperatureGradient< NumericType > operator* (const NumericType number) const
constexpr TemperatureGradient< NumericType > operator/ (const NumericType number) const
constexpr void operator+= (const TemperatureGradient< NumericType > &temperature_gradient) noexcept
constexpr void operator-= (const TemperatureGradient< NumericType > &temperature_gradient) noexcept
constexpr void operator*= (const NumericType number) noexcept
constexpr void operator/= (const NumericType number) noexcept
constexpr const PhQ::Vector< NumericType > & Value () const noexcept
Value of this physical quantity expressed in its standard unit of measure.
PhQ::Vector< NumericType > Value (const UnitType unit) const
Value of this physical quantity expressed in a given unit of measure.
template<UnitType NewUnit>
constexpr PhQ::Vector< NumericType > StaticValue () const
Value of this physical quantity expressed in a given unit of measure. This method can be evaluated statically at compile-time.
constexpr PhQ::Vector< NumericType > & MutableValue () noexcept
Returns the value of this physical quantity expressed in its standard unit of measure as a mutable value.
constexpr void SetValue (const PhQ::Vector< NumericType > &value) noexcept
Sets the value of this physical quantity expressed in its standard unit of measure to the given value.
std::string Print () const
Prints this physical quantity as a string. This physical quantity's value is expressed in its standard unit of measure.
std::string Print (const UnitType unit) const
Prints this physical quantity as a string. This physical quantity's value is expressed in the given unit of measure.
std::string JSON () const
Serializes this physical quantity as a JSON message. This physical quantity's value is expressed in its standard unit of measure.
std::string JSON (const UnitType unit) const
Serializes this physical quantity as a JSON message. This physical quantity's value is expressed in the given unit of measure.
std::string XML () const
Serializes this physical quantity as an XML message. This physical quantity's value is expressed in its standard unit of measure.
std::string XML (const UnitType unit) const
Serializes this physical quantity as an XML message. This physical quantity's value is expressed in the given unit of measure.
std::string YAML () const
Serializes this physical quantity as a YAML message. This physical quantity's value is expressed in its standard unit of measure.
std::string YAML (const UnitType unit) const
Serializes this physical quantity as a YAML message. This physical quantity's value is expressed in the given unit of measure.
Static Public Member Functions
static constexpr TemperatureGradient< NumericType > Zero ()
Statically creates a temperature gradient vector of zero.
template<Unit::TemperatureGradient Unit>
static constexpr TemperatureGradient< NumericType > Create (const NumericType x, const NumericType y, const NumericType z)
Statically creates a temperature gradient vector from the given x, y, and z Cartesian components expressed in a given temperature gradient unit.
template<Unit::TemperatureGradient Unit>
static constexpr TemperatureGradient< NumericType > Create (const std::array< NumericType, 3 > &x_y_z)
Statically creates a temperature gradient vector from the given x, y, and z Cartesian components expressed in a given temperature gradient unit.
template<Unit::TemperatureGradient Unit>
static constexpr TemperatureGradient< NumericType > Create (const Vector< NumericType > &value)
Statically creates a temperature gradient vector with a given value expressed in a given temperature gradient unit.
static constexpr const PhQ::Dimensions & Dimensions ()
Physical dimension set of this physical quantity.
static constexpr UnitType Unit ()
Standard unit of measure for this physical quantity. This physical quantity's value is stored internally in this unit of measure.
Protected Attributes
PhQ::Vector< NumericType > value
Value of this physical quantity expressed in its standard unit of measure.
Private Member Functions
constexpr TemperatureGradient (const Vector< NumericType > &value)
Constructor. Constructs a temperature gradient vector with a given value expressed in the standard temperature gradient unit.
Detailed Description
template<typename NumericType = double>
class PhQ::TemperatureGradient< NumericType >
Three-dimensional Euclidean temperature gradient vector. Contains three components in Cartesian coordinates: x, y, and z. For a two-dimensional Euclidean temperature gradient vector in the XY plane, see PhQ::PlanarTemperatureGradient. For scalar temperature gradient components or for the magnitude of a temperature gradient vector, see PhQ::ScalarTemperatureGradient.
Definition at line 48 of file TemperatureGradient.hpp.
Constructor & Destructor Documentation
TemperatureGradient() [1/9]
template<typename NumericType = double> PhQ::TemperatureGradient< NumericType >::TemperatureGradient () default
Default constructor. Constructs a temperature gradient vector with an uninitialized value.
TemperatureGradient() [2/9]
template<typename NumericType = double> PhQ::TemperatureGradient< NumericType >::TemperatureGradient (const Vector< NumericType > & value, const Unit::TemperatureGradient< NumericType > unit) inline
Constructor. Constructs a temperature gradient vector with a given value expressed in a given temperature gradient unit.
Definition at line 56 of file TemperatureGradient.hpp.
TemperatureGradient() [3/9]
template<typename NumericType = double> PhQ::TemperatureGradient< NumericType >::TemperatureGradient (const ScalarTemperatureGradient< NumericType > & x, const ScalarTemperatureGradient< NumericType > & y, const ScalarTemperatureGradient< NumericType > & z) inline
Constructor. Constructs a temperature gradient vector from a given set of scalar temperature gradient components.
Definition at line 61 of file TemperatureGradient.hpp.
References PhQ::TemperatureGradient< NumericType >::x(), PhQ::TemperatureGradient< NumericType >::y(), and PhQ::TemperatureGradient< NumericType >::z().
TemperatureGradient() [4/9]
template<typename NumericType = double> constexpr PhQ::TemperatureGradient< NumericType >::TemperatureGradient (const ScalarTemperatureGradient< NumericType > & scalar_temperature_gradient, const Direction< NumericType > & direction) inline constexpr
Constructor. Constructs a temperature gradient vector from a given scalar temperature gradient magnitude and direction.
Definition at line 68 of file TemperatureGradient.hpp.
TemperatureGradient() [5/9]
template<typename NumericType = double> constexpr PhQ::TemperatureGradient< NumericType >::TemperatureGradient (const PlanarTemperatureGradient< NumericType > & planar_temperature_gradient) inline explicit constexpr
Constructor. Constructs a temperature gradient vector from a given planar temperature gradient vector in the XY plane. This temperature gradient vector's z-component is initialized to zero.
Definition at line 76 of file TemperatureGradient.hpp.
References PhQ::DimensionalPlanarVector< UnitType, NumericType >::Value().
~TemperatureGradient()
template<typename NumericType = double> PhQ::TemperatureGradient< NumericType >::~TemperatureGradient () default noexcept
Destructor. Destroys this temperature gradient vector.
TemperatureGradient() [6/9]
template<typename NumericType = double> constexpr PhQ::TemperatureGradient< NumericType >::TemperatureGradient (const TemperatureGradient< NumericType > & other) constexpr default
Copy constructor. Constructs a temperature gradient vector by copying another one.
TemperatureGradient() [7/9]
template<typename NumericType = double> template<typename OtherNumericType > constexpr PhQ::TemperatureGradient< NumericType >::TemperatureGradient (const TemperatureGradient< OtherNumericType > & other) inline explicit constexpr
Copy constructor. Constructs a temperature gradient vector by copying another one.
Definition at line 88 of file TemperatureGradient.hpp.
TemperatureGradient() [8/9]
template<typename NumericType = double> constexpr PhQ::TemperatureGradient< NumericType >::TemperatureGradient (TemperatureGradient< NumericType > && other) constexpr default noexcept
Move constructor. Constructs a temperature gradient vector by moving another one.
TemperatureGradient() [9/9]
template<typename NumericType = double> constexpr PhQ::TemperatureGradient< NumericType >::TemperatureGradient (const Vector< NumericType > & value) inline explicit constexpr private
Constructor. Constructs a temperature gradient vector with a given value expressed in the standard temperature gradient unit.
Definition at line 216 of file TemperatureGradient.hpp.
Member Function Documentation
Angle()
template<typename NumericType = double> PhQ::Angle< NumericType > PhQ::TemperatureGradient< NumericType >::Angle (const TemperatureGradient< NumericType > & temperature_gradient) const inline
Returns the angle between this temperature gradient vector and another one.
Definition at line 174 of file TemperatureGradient.hpp.
Create() [1/3]
template<typename NumericType = double> template<Unit::TemperatureGradient Unit> static constexpr TemperatureGradient< NumericType > PhQ::TemperatureGradient< NumericType >::Create (const NumericType x, const NumericType y, const NumericType z) inline static constexpr
Statically creates a temperature gradient vector from the given x, y, and z Cartesian components expressed in a given temperature gradient unit.
Definition at line 121 of file TemperatureGradient.hpp.
References PhQ::TemperatureGradient< NumericType >::x(), PhQ::TemperatureGradient< NumericType >::y(), and PhQ::TemperatureGradient< NumericType >::z().
Create() [2/3]
template<typename NumericType = double> template<Unit::TemperatureGradient Unit> static constexpr TemperatureGradient< NumericType > PhQ::TemperatureGradient< NumericType >::Create (const std::array< NumericType, 3 > & x_y_z) inline static constexpr
Statically creates a temperature gradient vector from the given x, y, and z Cartesian components expressed in a given temperature gradient unit.
Definition at line 131 of file TemperatureGradient.hpp.
Create() [3/3]
template<typename NumericType = double> template<Unit::TemperatureGradient Unit> static constexpr TemperatureGradient< NumericType > PhQ::TemperatureGradient< NumericType >::Create (const Vector< NumericType > & value) inline static constexpr
Statically creates a temperature gradient vector with a given value expressed in a given temperature gradient unit.
Definition at line 141 of file TemperatureGradient.hpp.
References PhQ::DimensionalVector< UnitType, NumericType >::value.
Dimensions()
template<typename UnitType , typename NumericType = double> static constexpr const PhQ::Dimensions & PhQ::DimensionalVector< UnitType, NumericType >::Dimensions () inline static constexpr inherited
Physical dimension set of this physical quantity.
Definition at line 50 of file DimensionalVector.hpp.
Direction()
template<typename NumericType = double> PhQ::Direction< NumericType > PhQ::TemperatureGradient< NumericType >::Direction () const inline
Returns the direction of this temperature gradient vector.
Definition at line 169 of file TemperatureGradient.hpp.
References PhQ::DimensionalVector< UnitType, NumericType >::value.
JSON() [1/2]
template<typename UnitType , typename NumericType = double> std::string PhQ::DimensionalVector< UnitType, NumericType >::JSON () const inline inherited
Serializes this physical quantity as a JSON message. This physical quantity's value is expressed in its standard unit of measure.
Definition at line 103 of file DimensionalVector.hpp.
References PhQ::Abbreviation(), and PhQ::DimensionalVector< UnitType, NumericType >::value.
Referenced by PhQ::DimensionalVector< UnitType, NumericType >::JSON().
JSON() [2/2]
template<typename UnitType , typename NumericType = double> std::string PhQ::DimensionalVector< UnitType, NumericType >::JSON (const UnitType unit) const inline inherited
Serializes this physical quantity as a JSON message. This physical quantity's value is expressed in the given unit of measure.
Definition at line 113 of file DimensionalVector.hpp.
References PhQ::Abbreviation(), PhQ::DimensionalVector< UnitType, NumericType >::JSON(), and PhQ::DimensionalVector< UnitType, NumericType >::Value().
Magnitude()
template<typename NumericType = double> ScalarTemperatureGradient< NumericType > PhQ::TemperatureGradient< NumericType >::Magnitude () const inline
Returns the magnitude of this temperature gradient vector.
Definition at line 164 of file TemperatureGradient.hpp.
References PhQ::DimensionalVector< UnitType, NumericType >::value.
MutableValue()
template<typename UnitType , typename NumericType = double> constexpr PhQ::Vector< NumericType > & PhQ::DimensionalVector< UnitType, NumericType >::MutableValue () inline constexpr noexcept inherited
Returns the value of this physical quantity expressed in its standard unit of measure as a mutable value.
Definition at line 79 of file DimensionalVector.hpp.
References PhQ::DimensionalVector< UnitType, NumericType >::value.
operator*()
template<typename NumericType = double> constexpr TemperatureGradient< NumericType > PhQ::TemperatureGradient< NumericType >::operator* (const NumericType number) const inline constexpr
Definition at line 189 of file TemperatureGradient.hpp.
References PhQ::DimensionalVector< UnitType, NumericType >::value.
operator*=()
template<typename NumericType = double> constexpr void PhQ::TemperatureGradient< NumericType >::operator*= (const NumericType number) inline constexpr noexcept
Definition at line 205 of file TemperatureGradient.hpp.
References PhQ::DimensionalVector< UnitType, NumericType >::value.
operator+()
template<typename NumericType = double> constexpr TemperatureGradient< NumericType > PhQ::TemperatureGradient< NumericType >::operator+ (const TemperatureGradient< NumericType > & temperature_gradient) const inline constexpr
Definition at line 179 of file TemperatureGradient.hpp.
References PhQ::DimensionalVector< UnitType, NumericType >::value.
operator+=()
template<typename NumericType = double> constexpr void PhQ::TemperatureGradient< NumericType >::operator+= (const TemperatureGradient< NumericType > & temperature_gradient) inline constexpr noexcept
Definition at line 197 of file TemperatureGradient.hpp.
References PhQ::DimensionalVector< UnitType, NumericType >::value.
operator-()
template<typename NumericType = double> constexpr TemperatureGradient< NumericType > PhQ::TemperatureGradient< NumericType >::operator- (const TemperatureGradient< NumericType > & temperature_gradient) const inline constexpr
Definition at line 184 of file TemperatureGradient.hpp.
References PhQ::DimensionalVector< UnitType, NumericType >::value.
operator-=()
template<typename NumericType = double> constexpr void PhQ::TemperatureGradient< NumericType >::operator-= (const TemperatureGradient< NumericType > & temperature_gradient) inline constexpr noexcept
Definition at line 201 of file TemperatureGradient.hpp.
References PhQ::DimensionalVector< UnitType, NumericType >::value.
operator/()
template<typename NumericType = double> constexpr TemperatureGradient< NumericType > PhQ::TemperatureGradient< NumericType >::operator/ (const NumericType number) const inline constexpr
Definition at line 193 of file TemperatureGradient.hpp.
References PhQ::DimensionalVector< UnitType, NumericType >::value.
operator/=()
template<typename NumericType = double> constexpr void PhQ::TemperatureGradient< NumericType >::operator/= (const NumericType number) inline constexpr noexcept
Definition at line 209 of file TemperatureGradient.hpp.
References PhQ::DimensionalVector< UnitType, NumericType >::value.
operator=() [1/3]
template<typename NumericType = double> constexpr TemperatureGradient< NumericType > & PhQ::TemperatureGradient< NumericType >::operator= (const TemperatureGradient< NumericType > & other) constexpr default
Copy assignment operator. Assigns this temperature gradient vector by copying another one.
operator=() [2/3]
template<typename NumericType = double> template<typename OtherNumericType > constexpr TemperatureGradient< NumericType > & PhQ::TemperatureGradient< NumericType >::operator= (const TemperatureGradient< OtherNumericType > & other) inline constexpr
Copy assignment operator. Assigns this temperature gradient vector by copying another one.
Definition at line 102 of file TemperatureGradient.hpp.
References PhQ::DimensionalVector< UnitType, NumericType >::Value(), and PhQ::DimensionalVector< UnitType, NumericType >::value.
operator=() [3/3]
template<typename NumericType = double> constexpr TemperatureGradient< NumericType > & PhQ::TemperatureGradient< NumericType >::operator= (TemperatureGradient< NumericType > && other) constexpr default noexcept
Move assignment operator. Assigns this temperature gradient vector by moving another one.
Print() [1/2]
template<typename UnitType , typename NumericType = double> std::string PhQ::DimensionalVector< UnitType, NumericType >::Print () const inline inherited
Prints this physical quantity as a string. This physical quantity's value is expressed in its standard unit of measure.
Definition at line 91 of file DimensionalVector.hpp.
References PhQ::Abbreviation(), and PhQ::DimensionalVector< UnitType, NumericType >::value.
Referenced by PhQ::operator<<(), PhQ::operator<<(), PhQ::operator<<(), PhQ::operator<<(), PhQ::operator<<(), PhQ::operator<<(), PhQ::operator<<(), PhQ::operator<<(), and PhQ::operator<<().
Print() [2/2]
template<typename UnitType , typename NumericType = double> std::string PhQ::DimensionalVector< UnitType, NumericType >::Print (const UnitType unit) const inline inherited
Prints this physical quantity as a string. This physical quantity's value is expressed in the given unit of measure.
Definition at line 97 of file DimensionalVector.hpp.
References PhQ::Abbreviation(), and PhQ::DimensionalVector< UnitType, NumericType >::Value().
SetValue()
template<typename UnitType , typename NumericType = double> constexpr void PhQ::DimensionalVector< UnitType, NumericType >::SetValue (const PhQ::Vector< NumericType > & value) inline constexpr noexcept inherited
Sets the value of this physical quantity expressed in its standard unit of measure to the given value.
Definition at line 85 of file DimensionalVector.hpp.
References PhQ::DimensionalVector< UnitType, NumericType >::value.
StaticValue()
template<typename UnitType , typename NumericType = double> template<UnitType NewUnit> constexpr PhQ::Vector< NumericType > PhQ::DimensionalVector< UnitType, NumericType >::StaticValue () const inline constexpr inherited
Value of this physical quantity expressed in a given unit of measure. This method can be evaluated statically at compile-time.
Definition at line 73 of file DimensionalVector.hpp.
References PhQ::DimensionalVector< UnitType, NumericType >::value.
Unit()
template<typename UnitType , typename NumericType = double> static constexpr UnitType PhQ::DimensionalVector< UnitType, NumericType >::Unit () inline static constexpr inherited
Standard unit of measure for this physical quantity. This physical quantity's value is stored internally in this unit of measure.
Definition at line 56 of file DimensionalVector.hpp.
Value() [1/2]
template<typename UnitType , typename NumericType = double> constexpr const PhQ::Vector< NumericType > & PhQ::DimensionalVector< UnitType, NumericType >::Value () const inline constexpr noexcept inherited
Value of this physical quantity expressed in its standard unit of measure.
Definition at line 61 of file DimensionalVector.hpp.
References PhQ::DimensionalVector< UnitType, NumericType >::value.
Referenced by PhQ::DimensionalVector< UnitType, NumericType >::JSON(), PhQ::Position< NumericType >::operator+(), PhQ::Displacement< NumericType >::operator+(), PhQ::Position< NumericType >::operator-(), PhQ::Displacement< NumericType >::operator-(), PhQ::Acceleration< NumericType >::operator=(), PhQ::DimensionalVector< UnitType, NumericType >::operator=(), PhQ::Displacement< NumericType >::operator=(), PhQ::Force< NumericType >::operator=(), PhQ::HeatFlux< NumericType >::operator=(), PhQ::Position< NumericType >::operator=(), PhQ::TemperatureGradient< NumericType >::operator=(), PhQ::Traction< NumericType >::operator=(), PhQ::VectorArea< NumericType >::operator=(), PhQ::Velocity< NumericType >::operator=(), PhQ::operator==(), PhQ::operator==(), PhQ::operator==(), PhQ::operator==(), PhQ::operator==(), PhQ::operator==(), PhQ::operator==(), PhQ::operator==(), PhQ::operator==(), PhQ::operator==(), PhQ::operator==(), PhQ::operator==(), PhQ::operator==(), PhQ::operator==(), PhQ::operator==(), PhQ::operator==(), PhQ::PlanarAcceleration< NumericType >::PlanarAcceleration(), PhQ::PlanarDisplacement< NumericType >::PlanarDisplacement(), PhQ::PlanarForce< NumericType >::PlanarForce(), PhQ::PlanarHeatFlux< NumericType >::PlanarHeatFlux(), PhQ::PlanarPosition< NumericType >::PlanarPosition(), PhQ::PlanarTemperatureGradient< NumericType >::PlanarTemperatureGradient(), PhQ::PlanarTraction< NumericType >::PlanarTraction(), PhQ::PlanarVelocity< NumericType >::PlanarVelocity(), PhQ::DimensionalVector< UnitType, NumericType >::Print(), PhQ::DimensionalVector< UnitType, NumericType >::XML(), and PhQ::DimensionalVector< UnitType, NumericType >::YAML().
Value() [2/2]
template<typename UnitType , typename NumericType = double> PhQ::Vector< NumericType > PhQ::DimensionalVector< UnitType, NumericType >::Value (const UnitType unit) const inline inherited
Value of this physical quantity expressed in a given unit of measure.
Definition at line 66 of file DimensionalVector.hpp.
References PhQ::Convert(), and PhQ::DimensionalVector< UnitType, NumericType >::value.
x()
template<typename NumericType = double> constexpr ScalarTemperatureGradient< NumericType > PhQ::TemperatureGradient< NumericType >::x () const inline constexpr noexcept
Returns the x Cartesian component of this temperature gradient vector.
Definition at line 149 of file TemperatureGradient.hpp.
References PhQ::DimensionalVector< UnitType, NumericType >::value.
Referenced by PhQ::TemperatureGradient< NumericType >::Create(), and PhQ::TemperatureGradient< NumericType >::TemperatureGradient().
XML() [1/2]
template<typename UnitType , typename NumericType = double> std::string PhQ::DimensionalVector< UnitType, NumericType >::XML () const inline inherited
Serializes this physical quantity as an XML message. This physical quantity's value is expressed in its standard unit of measure.
Definition at line 123 of file DimensionalVector.hpp.
References PhQ::Abbreviation(), and PhQ::DimensionalVector< UnitType, NumericType >::value.
Referenced by PhQ::DimensionalVector< UnitType, NumericType >::XML().
XML() [2/2]
template<typename UnitType , typename NumericType = double> std::string PhQ::DimensionalVector< UnitType, NumericType >::XML (const UnitType unit) const inline inherited
Serializes this physical quantity as an XML message. This physical quantity's value is expressed in the given unit of measure.
Definition at line 133 of file DimensionalVector.hpp.
References PhQ::Abbreviation(), PhQ::DimensionalVector< UnitType, NumericType >::Value(), and PhQ::DimensionalVector< UnitType, NumericType >::XML().
y()
template<typename NumericType = double> constexpr ScalarTemperatureGradient< NumericType > PhQ::TemperatureGradient< NumericType >::y () const inline constexpr noexcept
Returns the y Cartesian component of this temperature gradient vector.
Definition at line 154 of file TemperatureGradient.hpp.
References PhQ::DimensionalVector< UnitType, NumericType >::value.
Referenced by PhQ::TemperatureGradient< NumericType >::Create(), and PhQ::TemperatureGradient< NumericType >::TemperatureGradient().
YAML() [1/2]
template<typename UnitType , typename NumericType = double> std::string PhQ::DimensionalVector< UnitType, NumericType >::YAML () const inline inherited
Serializes this physical quantity as a YAML message. This physical quantity's value is expressed in its standard unit of measure.
Definition at line 143 of file DimensionalVector.hpp.
References PhQ::Abbreviation(), and PhQ::DimensionalVector< UnitType, NumericType >::value.
Referenced by PhQ::DimensionalVector< UnitType, NumericType >::YAML().
YAML() [2/2]
template<typename UnitType , typename NumericType = double> std::string PhQ::DimensionalVector< UnitType, NumericType >::YAML (const UnitType unit) const inline inherited
Serializes this physical quantity as a YAML message. This physical quantity's value is expressed in the given unit of measure.
Definition at line 153 of file DimensionalVector.hpp.
References PhQ::Abbreviation(), PhQ::DimensionalVector< UnitType, NumericType >::Value(), and PhQ::DimensionalVector< UnitType, NumericType >::YAML().
z()
template<typename NumericType = double> constexpr ScalarTemperatureGradient< NumericType > PhQ::TemperatureGradient< NumericType >::z () const inline constexpr noexcept
Returns the z Cartesian component of this temperature gradient vector.
Definition at line 159 of file TemperatureGradient.hpp.
References PhQ::DimensionalVector< UnitType, NumericType >::value.
Referenced by PhQ::TemperatureGradient< NumericType >::Create(), and PhQ::TemperatureGradient< NumericType >::TemperatureGradient().
Zero()
template<typename NumericType = double> static constexpr TemperatureGradient< NumericType > PhQ::TemperatureGradient< NumericType >::Zero () inline static constexpr
Statically creates a temperature gradient vector of zero.
Definition at line 114 of file TemperatureGradient.hpp.
References PhQ::Vector< NumericType >::Zero().
Member Data Documentation
value
template<typename UnitType , typename NumericType = double> PhQ::Vector<NumericType> PhQ::DimensionalVector< UnitType, NumericType >::value protected inherited
Value of this physical quantity expressed in its standard unit of measure.
Definition at line 217 of file DimensionalVector.hpp.
Referenced by PhQ::Acceleration< NumericType >::Create(), PhQ::Displacement< NumericType >::Create(), PhQ::Force< NumericType >::Create(), PhQ::HeatFlux< NumericType >::Create(), PhQ::Position< NumericType >::Create(), PhQ::TemperatureGradient< NumericType >::Create(), PhQ::Traction< NumericType >::Create(), PhQ::VectorArea< NumericType >::Create(), PhQ::Velocity< NumericType >::Create(), PhQ::Acceleration< NumericType >::Direction(), PhQ::Displacement< NumericType >::Direction(), PhQ::Force< NumericType >::Direction(), PhQ::HeatFlux< NumericType >::Direction(), PhQ::Position< NumericType >::Direction(), PhQ::TemperatureGradient< NumericType >::Direction(), PhQ::Traction< NumericType >::Direction(), PhQ::VectorArea< NumericType >::Direction(), PhQ::Velocity< NumericType >::Direction(), PhQ::DimensionalVector< UnitType, NumericType >::JSON(), PhQ::Acceleration< NumericType >::Magnitude(), PhQ::Displacement< NumericType >::Magnitude(), PhQ::Force< NumericType >::Magnitude(), PhQ::HeatFlux< NumericType >::Magnitude(), PhQ::Position< NumericType >::Magnitude(), PhQ::TemperatureGradient< NumericType >::Magnitude(), PhQ::Traction< NumericType >::Magnitude(), PhQ::VectorArea< NumericType >::Magnitude(), PhQ::Velocity< NumericType >::Magnitude(), PhQ::DimensionalVector< UnitType, NumericType >::MutableValue(), PhQ::Acceleration< NumericType >::operator*(), PhQ::Displacement< NumericType >::operator*(), PhQ::Force< NumericType >::operator*(), PhQ::HeatFlux< NumericType >::operator*(), PhQ::Position< NumericType >::operator*(), PhQ::TemperatureGradient< NumericType >::operator*(), PhQ::Traction< NumericType >::operator*(), PhQ::VectorArea< NumericType >::operator*(), PhQ::Velocity< NumericType >::operator*(), PhQ::Acceleration< NumericType >::operator*=(), PhQ::Displacement< NumericType >::operator*=(), PhQ::Force< NumericType >::operator*=(), PhQ::HeatFlux< NumericType >::operator*=(), PhQ::Position< NumericType >::operator*=(), PhQ::TemperatureGradient< NumericType >::operator*=(), PhQ::Traction< NumericType >::operator*=(), PhQ::VectorArea< NumericType >::operator*=(), PhQ::Velocity< NumericType >::operator*=(), PhQ::Acceleration< NumericType >::operator+(), PhQ::Displacement< NumericType >::operator+(), PhQ::Position< NumericType >::operator+(), PhQ::Force< NumericType >::operator+(), PhQ::HeatFlux< NumericType >::operator+(), PhQ::Position< NumericType >::operator+(), PhQ::TemperatureGradient< NumericType >::operator+(), PhQ::Traction< NumericType >::operator+(), PhQ::VectorArea< NumericType >::operator+(), PhQ::Velocity< NumericType >::operator+(), PhQ::Acceleration< NumericType >::operator+=(), PhQ::Displacement< NumericType >::operator+=(), PhQ::Position< NumericType >::operator+=(), PhQ::Force< NumericType >::operator+=(), PhQ::HeatFlux< NumericType >::operator+=(), PhQ::Position< NumericType >::operator+=(), PhQ::TemperatureGradient< NumericType >::operator+=(), PhQ::Traction< NumericType >::operator+=(), PhQ::VectorArea< NumericType >::operator+=(), PhQ::Velocity< NumericType >::operator+=(), PhQ::Acceleration< NumericType >::operator-(), PhQ::Displacement< NumericType >::operator-(), PhQ::Position< NumericType >::operator-(), PhQ::Force< NumericType >::operator-(), PhQ::HeatFlux< NumericType >::operator-(), PhQ::Position< NumericType >::operator-(), PhQ::TemperatureGradient< NumericType >::operator-(), PhQ::Traction< NumericType >::operator-(), PhQ::VectorArea< NumericType >::operator-(), PhQ::Velocity< NumericType >::operator-(), PhQ::Acceleration< NumericType >::operator-=(), PhQ::Displacement< NumericType >::operator-=(), PhQ::Position< NumericType >::operator-=(), PhQ::Force< NumericType >::operator-=(), PhQ::HeatFlux< NumericType >::operator-=(), PhQ::Position< NumericType >::operator-=(), PhQ::TemperatureGradient< NumericType >::operator-=(), PhQ::Traction< NumericType >::operator-=(), PhQ::VectorArea< NumericType >::operator-=(), PhQ::Velocity< NumericType >::operator-=(), PhQ::Acceleration< NumericType >::operator/(), PhQ::Displacement< NumericType >::operator/(), PhQ::Force< NumericType >::operator/(), PhQ::HeatFlux< NumericType >::operator/(), PhQ::Position< NumericType >::operator/(), PhQ::TemperatureGradient< NumericType >::operator/(), PhQ::Traction< NumericType >::operator/(), PhQ::VectorArea< NumericType >::operator/(), PhQ::Velocity< NumericType >::operator/(), PhQ::Acceleration< NumericType >::operator/=(), PhQ::Displacement< NumericType >::operator/=(), PhQ::Force< NumericType >::operator/=(), PhQ::HeatFlux< NumericType >::operator/=(), PhQ::Position< NumericType >::operator/=(), PhQ::TemperatureGradient< NumericType >::operator/=(), PhQ::Traction< NumericType >::operator/=(), PhQ::VectorArea< NumericType >::operator/=(), PhQ::Velocity< NumericType >::operator/=(), PhQ::Acceleration< NumericType >::operator=(), PhQ::DimensionalVector< UnitType, NumericType >::operator=(), PhQ::Displacement< NumericType >::operator=(), PhQ::Force< NumericType >::operator=(), PhQ::HeatFlux< NumericType >::operator=(), PhQ::Position< NumericType >::operator=(), PhQ::TemperatureGradient< NumericType >::operator=(), PhQ::Traction< NumericType >::operator=(), PhQ::VectorArea< NumericType >::operator=(), PhQ::Velocity< NumericType >::operator=(), PhQ::DimensionalVector< UnitType, NumericType >::Print(), PhQ::DimensionalVector< UnitType, NumericType >::SetValue(), PhQ::DimensionalVector< UnitType, NumericType >::StaticValue(), PhQ::DimensionalVector< UnitType, NumericType >::Value(), PhQ::DimensionalVector< UnitType, NumericType >::Value(), PhQ::Acceleration< NumericType >::x(), PhQ::Displacement< NumericType >::x(), PhQ::Force< NumericType >::x(), PhQ::HeatFlux< NumericType >::x(), PhQ::Position< NumericType >::x(), PhQ::TemperatureGradient< NumericType >::x(), PhQ::Traction< NumericType >::x(), PhQ::VectorArea< NumericType >::x(), PhQ::Velocity< NumericType >::x(), PhQ::DimensionalVector< UnitType, NumericType >::XML(), PhQ::Acceleration< NumericType >::y(), PhQ::Displacement< NumericType >::y(), PhQ::Force< NumericType >::y(), PhQ::HeatFlux< NumericType >::y(), PhQ::Position< NumericType >::y(), PhQ::TemperatureGradient< NumericType >::y(), PhQ::Traction< NumericType >::y(), PhQ::VectorArea< NumericType >::y(), PhQ::Velocity< NumericType >::y(), PhQ::DimensionalVector< UnitType, NumericType >::YAML(), PhQ::Acceleration< NumericType >::z(), PhQ::Displacement< NumericType >::z(), PhQ::Force< NumericType >::z(), PhQ::HeatFlux< NumericType >::z(), PhQ::Position< NumericType >::z(), PhQ::TemperatureGradient< NumericType >::z(), PhQ::Traction< NumericType >::z(), PhQ::VectorArea< NumericType >::z(), and PhQ::Velocity< NumericType >::z().
The documentation for this class was generated from the following files:
PhQ/Angle.hpp
PhQ/TemperatureGradient.hpp