Physical Quantities: PhQ::ConstitutiveModel::CompressibleNewtonianFluid< NumericType > Class Template Reference
PhQ::ConstitutiveModel::CompressibleNewtonianFluid< NumericType > Class Template Reference
Constitutive model for a compressible Newtonian fluid. This is the simplest constitutive model for a compressible fluid. It is similar to the model for an incompressible Newtonian fluid, but also includes the effect of the volumetric component of the strain rate tensor in addition to its deviatoric component.
#include "CompressibleNewtonianFluid.hpp"
Public Types
enum class Type : int8_t { CompressibleNewtonianFluid , ElasticIsotropicSolid , IncompressibleNewtonianFluid }
Type of a material's constitutive model.
Public Member Functions
CompressibleNewtonianFluid ()
Default constructor. Constructs a compressible Newtonian fluid constitutive model with an uninitialized dynamic viscosity and bulk dynamic viscosity.
constexpr CompressibleNewtonianFluid (const DynamicViscosity< NumericType > &dynamic_viscosity)
Constructor. Constructs a compressible Newtonian fluid constitutive model from a given dynamic viscosity. Initializes the bulk dynamic viscosity to zero.
constexpr CompressibleNewtonianFluid (const DynamicViscosity< NumericType > &dynamic_viscosity, const BulkDynamicViscosity< NumericType > &bulk_dynamic_viscosity)
Constructor. Constructs a compressible Newtonian fluid constitutive model from a given dynamic viscosity and bulk dynamic viscosity.
~CompressibleNewtonianFluid () noexcept override=default
Destructor. Destroys this compressible Newtonian fluid constitutive model.
constexpr CompressibleNewtonianFluid (const CompressibleNewtonianFluid &other)=default
Copy constructor. Constructs a compressible Newtonian fluid constitutive model by copying another one.
constexpr CompressibleNewtonianFluid (CompressibleNewtonianFluid &&other) noexcept=default
Move constructor. Constructs a compressible Newtonian fluid constitutive model by moving another one.
CompressibleNewtonianFluid & operator= (const CompressibleNewtonianFluid &other)=default
Copy assignment operator. Assigns this compressible Newtonian fluid constitutive model by copying another one.
CompressibleNewtonianFluid & operator= (CompressibleNewtonianFluid &&other) noexcept=default
Move assignment operator. Assigns this compressible Newtonian fluid constitutive model by moving another one.
constexpr const PhQ::DynamicViscosity< NumericType > & DynamicViscosity () const noexcept
Dynamic viscosity of this compressible Newtonian fluid constitutive model.
constexpr const PhQ::BulkDynamicViscosity< NumericType > & BulkDynamicViscosity () const noexcept
Bulk dynamic viscosity of this compressible Newtonian fluid constitutive model.
ConstitutiveModel::Type GetType () const noexcept override
Returns this constitutive model's type.
PhQ::Stress< float > Stress (const PhQ::Strain< float > &, const PhQ::StrainRate< float > &strain_rate) const override
Returns the stress resulting from a given strain and strain rate. Since this is a compressible Newtonian fluid constitutive model, the strain does not contribute to the stress and is ignored.
PhQ::Stress< double > Stress (const PhQ::Strain< double > &, const PhQ::StrainRate< double > &strain_rate) const override
Returns the stress resulting from a given strain and strain rate. Since this is a compressible Newtonian fluid constitutive model, the strain does not contribute to the stress and is ignored.
PhQ::Stress< long double > Stress (const PhQ::Strain< long double > &, const PhQ::StrainRate< long double > &strain_rate) const override
Returns the stress resulting from a given strain and strain rate. Since this is a compressible Newtonian fluid constitutive model, the strain does not contribute to the stress and is ignored.
PhQ::Stress< float > Stress (const PhQ::Strain< float > &) const override
Returns the stress resulting from a given strain. Since this is a compressible Newtonian fluid constitutive model, the strain does not contribute to the stress, so this always returns a stress of zero.
PhQ::Stress< double > Stress (const PhQ::Strain< double > &) const override
Returns the stress resulting from a given strain. Since this is a compressible Newtonian fluid constitutive model, the strain does not contribute to the stress, so this always returns a stress of zero.
PhQ::Stress< long double > Stress (const PhQ::Strain< long double > &) const override
Returns the stress resulting from a given strain. Since this is a compressible Newtonian fluid constitutive model, the strain does not contribute to the stress, so this always returns a stress of zero.
PhQ::Stress< float > Stress (const PhQ::StrainRate< float > &strain_rate) const override
Returns the stress resulting from a given strain rate.
PhQ::Stress< double > Stress (const PhQ::StrainRate< double > &strain_rate) const override
Returns the stress resulting from a given strain rate.
PhQ::Stress< long double > Stress (const PhQ::StrainRate< long double > &strain_rate) const override
Returns the stress resulting from a given strain rate.
PhQ::Strain< float > Strain (const PhQ::Stress< float > &) const override
Returns the strain resulting from a given stress. Since this is a compressible Newtonian fluid constitutive model, stress does not depend on strain, so this always returns a strain of zero.
PhQ::Strain< double > Strain (const PhQ::Stress< double > &) const override
Returns the strain resulting from a given stress. Since this is a compressible Newtonian fluid constitutive model, stress does not depend on strain, so this always returns a strain of zero.
PhQ::Strain< long double > Strain (const PhQ::Stress< long double > &) const override
Returns the strain resulting from a given stress. Since this is a compressible Newtonian fluid constitutive model, stress does not depend on strain, so this always returns a strain of zero.
PhQ::StrainRate< float > StrainRate (const PhQ::Stress< float > &stress) const override
Returns the strain rate resulting from a given stress.
PhQ::StrainRate< double > StrainRate (const PhQ::Stress< double > &stress) const override
Returns the strain rate resulting from a given stress.
PhQ::StrainRate< long double > StrainRate (const PhQ::Stress< long double > &stress) const override
Returns the strain rate resulting from a given stress.
std::string Print () const override
Prints this compressible Newtonian fluid constitutive model as a string.
std::string JSON () const override
Serializes this compressible Newtonian fluid constitutive model as a JSON message.
std::string XML () const override
Serializes this compressible Newtonian fluid constitutive model as an XML message.
std::string YAML () const override
Serializes this compressible Newtonian fluid constitutive model as a YAML message.
Private Attributes
PhQ::DynamicViscosity< NumericType > dynamic_viscosity
Dynamic viscosity of this compressible Newtonian fluid constitutive model.
PhQ::BulkDynamicViscosity< NumericType > bulk_dynamic_viscosity
Bulk dynamic viscosity of this compressible Newtonian fluid constitutive model.
Detailed Description
template<typename NumericType = double>
class PhQ::ConstitutiveModel::CompressibleNewtonianFluid< NumericType >
Constitutive model for a compressible Newtonian fluid. This is the simplest constitutive model for a compressible fluid. It is similar to the model for an incompressible Newtonian fluid, but also includes the effect of the volumetric component of the strain rate tensor in addition to its deviatoric component.
Definition at line 51 of file CompressibleNewtonianFluid.hpp.
Member Enumeration Documentation
Type
enum class PhQ::ConstitutiveModel::Type : int8_t strong inherited
Type of a material's constitutive model.
Enumerator
CompressibleNewtonianFluid
Compressible Newtonian fluid constitutive model.
ElasticIsotropicSolid
Elastic isotropic solid constitutive model.
IncompressibleNewtonianFluid
Incompressible Newtonian fluid constitutive model.
Definition at line 57 of file ConstitutiveModel.hpp.
Constructor & Destructor Documentation
CompressibleNewtonianFluid() [1/5]
template<typename NumericType = double> PhQ::ConstitutiveModel::CompressibleNewtonianFluid< NumericType >::CompressibleNewtonianFluid () inline
Default constructor. Constructs a compressible Newtonian fluid constitutive model with an uninitialized dynamic viscosity and bulk dynamic viscosity.
Definition at line 55 of file CompressibleNewtonianFluid.hpp.
CompressibleNewtonianFluid() [2/5]
template<typename NumericType = double> constexpr PhQ::ConstitutiveModel::CompressibleNewtonianFluid< NumericType >::CompressibleNewtonianFluid (const DynamicViscosity< NumericType > & dynamic_viscosity) inline explicit constexpr
Constructor. Constructs a compressible Newtonian fluid constitutive model from a given dynamic viscosity. Initializes the bulk dynamic viscosity to zero.
Definition at line 59 of file CompressibleNewtonianFluid.hpp.
CompressibleNewtonianFluid() [3/5]
template<typename NumericType = double> constexpr PhQ::ConstitutiveModel::CompressibleNewtonianFluid< NumericType >::CompressibleNewtonianFluid (const DynamicViscosity< NumericType > & dynamic_viscosity, const BulkDynamicViscosity< NumericType > & bulk_dynamic_viscosity) inline constexpr
Constructor. Constructs a compressible Newtonian fluid constitutive model from a given dynamic viscosity and bulk dynamic viscosity.
Definition at line 66 of file CompressibleNewtonianFluid.hpp.
~CompressibleNewtonianFluid()
template<typename NumericType = double> PhQ::ConstitutiveModel::CompressibleNewtonianFluid< NumericType >::~CompressibleNewtonianFluid () override default noexcept
Destructor. Destroys this compressible Newtonian fluid constitutive model.
CompressibleNewtonianFluid() [4/5]
template<typename NumericType = double> constexpr PhQ::ConstitutiveModel::CompressibleNewtonianFluid< NumericType >::CompressibleNewtonianFluid (const CompressibleNewtonianFluid< NumericType > & other) constexpr default
Copy constructor. Constructs a compressible Newtonian fluid constitutive model by copying another one.
CompressibleNewtonianFluid() [5/5]
template<typename NumericType = double> constexpr PhQ::ConstitutiveModel::CompressibleNewtonianFluid< NumericType >::CompressibleNewtonianFluid (CompressibleNewtonianFluid< NumericType > && other) constexpr default noexcept
Move constructor. Constructs a compressible Newtonian fluid constitutive model by moving another one.
Member Function Documentation
BulkDynamicViscosity()
template<typename NumericType = double> constexpr const PhQ::BulkDynamicViscosity< NumericType > & PhQ::ConstitutiveModel::CompressibleNewtonianFluid< NumericType >::BulkDynamicViscosity () const inline constexpr noexcept
Bulk dynamic viscosity of this compressible Newtonian fluid constitutive model.
Definition at line 99 of file CompressibleNewtonianFluid.hpp.
References PhQ::ConstitutiveModel::CompressibleNewtonianFluid< NumericType >::bulk_dynamic_viscosity.
DynamicViscosity()
template<typename NumericType = double> constexpr const PhQ::DynamicViscosity< NumericType > & PhQ::ConstitutiveModel::CompressibleNewtonianFluid< NumericType >::DynamicViscosity () const inline constexpr noexcept
Dynamic viscosity of this compressible Newtonian fluid constitutive model.
Definition at line 93 of file CompressibleNewtonianFluid.hpp.
References PhQ::ConstitutiveModel::CompressibleNewtonianFluid< NumericType >::dynamic_viscosity.
GetType()
template<typename NumericType = double> ConstitutiveModel::Type PhQ::ConstitutiveModel::CompressibleNewtonianFluid< NumericType >::GetType () const inline override virtual noexcept
Returns this constitutive model's type.
Implements PhQ::ConstitutiveModel.
Definition at line 104 of file CompressibleNewtonianFluid.hpp.
References PhQ::ConstitutiveModel::CompressibleNewtonianFluid.
Referenced by PhQ::ConstitutiveModel::CompressibleNewtonianFluid< NumericType >::JSON(), PhQ::ConstitutiveModel::CompressibleNewtonianFluid< NumericType >::Print(), PhQ::ConstitutiveModel::CompressibleNewtonianFluid< NumericType >::XML(), and PhQ::ConstitutiveModel::CompressibleNewtonianFluid< NumericType >::YAML().
JSON()
template<typename NumericType = double> std::string PhQ::ConstitutiveModel::CompressibleNewtonianFluid< NumericType >::JSON () const inline override virtual
Serializes this compressible Newtonian fluid constitutive model as a JSON message.
Implements PhQ::ConstitutiveModel.
Definition at line 314 of file CompressibleNewtonianFluid.hpp.
References PhQ::Abbreviation(), PhQ::ConstitutiveModel::CompressibleNewtonianFluid< NumericType >::bulk_dynamic_viscosity, PhQ::ConstitutiveModel::CompressibleNewtonianFluid< NumericType >::dynamic_viscosity, PhQ::ConstitutiveModel::CompressibleNewtonianFluid< NumericType >::GetType(), and PhQ::SnakeCase().
operator=() [1/2]
template<typename NumericType = double> CompressibleNewtonianFluid & PhQ::ConstitutiveModel::CompressibleNewtonianFluid< NumericType >::operator= (CompressibleNewtonianFluid< NumericType > && other) default noexcept
Move assignment operator. Assigns this compressible Newtonian fluid constitutive model by moving another one.
operator=() [2/2]
template<typename NumericType = double> CompressibleNewtonianFluid & PhQ::ConstitutiveModel::CompressibleNewtonianFluid< NumericType >::operator= (const CompressibleNewtonianFluid< NumericType > & other) default
Copy assignment operator. Assigns this compressible Newtonian fluid constitutive model by copying another one.
Print()
template<typename NumericType = double> std::string PhQ::ConstitutiveModel::CompressibleNewtonianFluid< NumericType >::Print () const inline override virtual
Prints this compressible Newtonian fluid constitutive model as a string.
Implements PhQ::ConstitutiveModel.
Definition at line 307 of file CompressibleNewtonianFluid.hpp.
References PhQ::Abbreviation(), PhQ::ConstitutiveModel::CompressibleNewtonianFluid< NumericType >::bulk_dynamic_viscosity, PhQ::ConstitutiveModel::CompressibleNewtonianFluid< NumericType >::dynamic_viscosity, and PhQ::ConstitutiveModel::CompressibleNewtonianFluid< NumericType >::GetType().
Referenced by PhQ::operator<<().
Strain() [1/3]
template<typename NumericType = double> PhQ::Strain< double > PhQ::ConstitutiveModel::CompressibleNewtonianFluid< NumericType >::Strain (const PhQ::Stress< double > &) const inline override virtual
Returns the strain resulting from a given stress. Since this is a compressible Newtonian fluid constitutive model, stress does not depend on strain, so this always returns a strain of zero.
Implements PhQ::ConstitutiveModel.
Definition at line 222 of file CompressibleNewtonianFluid.hpp.
References PhQ::Strain< NumericType >::Zero().
Strain() [2/3]
template<typename NumericType = double> PhQ::Strain< float > PhQ::ConstitutiveModel::CompressibleNewtonianFluid< NumericType >::Strain (const PhQ::Stress< float > &) const inline override virtual
Returns the strain resulting from a given stress. Since this is a compressible Newtonian fluid constitutive model, stress does not depend on strain, so this always returns a strain of zero.
Implements PhQ::ConstitutiveModel.
Definition at line 214 of file CompressibleNewtonianFluid.hpp.
References PhQ::Strain< NumericType >::Zero().
Strain() [3/3]
template<typename NumericType = double> PhQ::Strain< long double > PhQ::ConstitutiveModel::CompressibleNewtonianFluid< NumericType >::Strain (const PhQ::Stress< long double > &) const inline override virtual
Returns the strain resulting from a given stress. Since this is a compressible Newtonian fluid constitutive model, stress does not depend on strain, so this always returns a strain of zero.
Implements PhQ::ConstitutiveModel.
Definition at line 230 of file CompressibleNewtonianFluid.hpp.
References PhQ::Strain< NumericType >::Zero().
StrainRate() [1/3]
template<typename NumericType = double> PhQ::StrainRate< double > PhQ::ConstitutiveModel::CompressibleNewtonianFluid< NumericType >::StrainRate (const PhQ::Stress< double > & stress) const inline override virtual
Returns the strain rate resulting from a given stress.
Implements PhQ::ConstitutiveModel.
Definition at line 259 of file CompressibleNewtonianFluid.hpp.
References PhQ::ConstitutiveModel::CompressibleNewtonianFluid< NumericType >::bulk_dynamic_viscosity, PhQ::ConstitutiveModel::CompressibleNewtonianFluid< NumericType >::dynamic_viscosity, and PhQ::DimensionalSymmetricDyad< UnitType, NumericType >::Value().
StrainRate() [2/3]
template<typename NumericType = double> PhQ::StrainRate< float > PhQ::ConstitutiveModel::CompressibleNewtonianFluid< NumericType >::StrainRate (const PhQ::Stress< float > & stress) const inline override virtual
Returns the strain rate resulting from a given stress.
Implements PhQ::ConstitutiveModel.
Definition at line 236 of file CompressibleNewtonianFluid.hpp.
References PhQ::ConstitutiveModel::CompressibleNewtonianFluid< NumericType >::bulk_dynamic_viscosity, PhQ::ConstitutiveModel::CompressibleNewtonianFluid< NumericType >::dynamic_viscosity, and PhQ::DimensionalSymmetricDyad< UnitType, NumericType >::Value().
StrainRate() [3/3]
template<typename NumericType = double> PhQ::StrainRate< long double > PhQ::ConstitutiveModel::CompressibleNewtonianFluid< NumericType >::StrainRate (const PhQ::Stress< long double > & stress) const inline override virtual
Returns the strain rate resulting from a given stress.
Implements PhQ::ConstitutiveModel.
Definition at line 282 of file CompressibleNewtonianFluid.hpp.
References PhQ::ConstitutiveModel::CompressibleNewtonianFluid< NumericType >::bulk_dynamic_viscosity, PhQ::ConstitutiveModel::CompressibleNewtonianFluid< NumericType >::dynamic_viscosity, and PhQ::DimensionalSymmetricDyad< UnitType, NumericType >::Value().
Stress() [1/9]
template<typename NumericType = double> PhQ::Stress< double > PhQ::ConstitutiveModel::CompressibleNewtonianFluid< NumericType >::Stress (const PhQ::Strain< double > &) const inline override virtual
Returns the stress resulting from a given strain. Since this is a compressible Newtonian fluid constitutive model, the strain does not contribute to the stress, so this always returns a stress of zero.
Implements PhQ::ConstitutiveModel.
Definition at line 146 of file CompressibleNewtonianFluid.hpp.
References PhQ::Stress< NumericType >::Zero().
Stress() [2/9]
template<typename NumericType = double> PhQ::Stress< double > PhQ::ConstitutiveModel::CompressibleNewtonianFluid< NumericType >::Stress (const PhQ::Strain< double > & , const PhQ::StrainRate< double > & strain_rate) const inline override virtual
Returns the stress resulting from a given strain and strain rate. Since this is a compressible Newtonian fluid constitutive model, the strain does not contribute to the stress and is ignored.
Implements PhQ::ConstitutiveModel.
Definition at line 120 of file CompressibleNewtonianFluid.hpp.
Stress() [3/9]
template<typename NumericType = double> PhQ::Stress< float > PhQ::ConstitutiveModel::CompressibleNewtonianFluid< NumericType >::Stress (const PhQ::Strain< float > &) const inline override virtual
Returns the stress resulting from a given strain. Since this is a compressible Newtonian fluid constitutive model, the strain does not contribute to the stress, so this always returns a stress of zero.
Implements PhQ::ConstitutiveModel.
Definition at line 138 of file CompressibleNewtonianFluid.hpp.
References PhQ::Stress< NumericType >::Zero().
Stress() [4/9]
template<typename NumericType = double> PhQ::Stress< float > PhQ::ConstitutiveModel::CompressibleNewtonianFluid< NumericType >::Stress (const PhQ::Strain< float > & , const PhQ::StrainRate< float > & strain_rate) const inline override virtual
Returns the stress resulting from a given strain and strain rate. Since this is a compressible Newtonian fluid constitutive model, the strain does not contribute to the stress and is ignored.
Implements PhQ::ConstitutiveModel.
Definition at line 111 of file CompressibleNewtonianFluid.hpp.
Stress() [5/9]
template<typename NumericType = double> PhQ::Stress< long double > PhQ::ConstitutiveModel::CompressibleNewtonianFluid< NumericType >::Stress (const PhQ::Strain< long double > &) const inline override virtual
Returns the stress resulting from a given strain. Since this is a compressible Newtonian fluid constitutive model, the strain does not contribute to the stress, so this always returns a stress of zero.
Implements PhQ::ConstitutiveModel.
Definition at line 154 of file CompressibleNewtonianFluid.hpp.
References PhQ::Stress< NumericType >::Zero().
Stress() [6/9]
template<typename NumericType = double> PhQ::Stress< long double > PhQ::ConstitutiveModel::CompressibleNewtonianFluid< NumericType >::Stress (const PhQ::Strain< long double > & , const PhQ::StrainRate< long double > & strain_rate) const inline override virtual
Returns the stress resulting from a given strain and strain rate. Since this is a compressible Newtonian fluid constitutive model, the strain does not contribute to the stress and is ignored.
Implements PhQ::ConstitutiveModel.
Definition at line 129 of file CompressibleNewtonianFluid.hpp.
Stress() [7/9]
template<typename NumericType = double> PhQ::Stress< double > PhQ::ConstitutiveModel::CompressibleNewtonianFluid< NumericType >::Stress (const PhQ::StrainRate< double > & strain_rate) const inline override virtual
Returns the stress resulting from a given strain rate.
Implements PhQ::ConstitutiveModel.
Definition at line 177 of file CompressibleNewtonianFluid.hpp.
References PhQ::ConstitutiveModel::CompressibleNewtonianFluid< NumericType >::bulk_dynamic_viscosity, PhQ::ConstitutiveModel::CompressibleNewtonianFluid< NumericType >::dynamic_viscosity, and PhQ::DimensionalSymmetricDyad< UnitType, NumericType >::Value().
Stress() [8/9]
template<typename NumericType = double> PhQ::Stress< float > PhQ::ConstitutiveModel::CompressibleNewtonianFluid< NumericType >::Stress (const PhQ::StrainRate< float > & strain_rate) const inline override virtual
Returns the stress resulting from a given strain rate.
Implements PhQ::ConstitutiveModel.
Definition at line 160 of file CompressibleNewtonianFluid.hpp.
References PhQ::ConstitutiveModel::CompressibleNewtonianFluid< NumericType >::bulk_dynamic_viscosity, PhQ::ConstitutiveModel::CompressibleNewtonianFluid< NumericType >::dynamic_viscosity, and PhQ::DimensionalSymmetricDyad< UnitType, NumericType >::Value().
Stress() [9/9]
template<typename NumericType = double> PhQ::Stress< long double > PhQ::ConstitutiveModel::CompressibleNewtonianFluid< NumericType >::Stress (const PhQ::StrainRate< long double > & strain_rate) const inline override virtual
Returns the stress resulting from a given strain rate.
Implements PhQ::ConstitutiveModel.
Definition at line 194 of file CompressibleNewtonianFluid.hpp.
References PhQ::ConstitutiveModel::CompressibleNewtonianFluid< NumericType >::bulk_dynamic_viscosity, PhQ::ConstitutiveModel::CompressibleNewtonianFluid< NumericType >::dynamic_viscosity, and PhQ::DimensionalSymmetricDyad< UnitType, NumericType >::Value().
XML()
template<typename NumericType = double> std::string PhQ::ConstitutiveModel::CompressibleNewtonianFluid< NumericType >::XML () const inline override virtual
Serializes this compressible Newtonian fluid constitutive model as an XML message.
Implements PhQ::ConstitutiveModel.
Definition at line 321 of file CompressibleNewtonianFluid.hpp.
References PhQ::Abbreviation(), PhQ::ConstitutiveModel::CompressibleNewtonianFluid< NumericType >::bulk_dynamic_viscosity, PhQ::ConstitutiveModel::CompressibleNewtonianFluid< NumericType >::dynamic_viscosity, PhQ::ConstitutiveModel::CompressibleNewtonianFluid< NumericType >::GetType(), and PhQ::SnakeCase().
YAML()
template<typename NumericType = double> std::string PhQ::ConstitutiveModel::CompressibleNewtonianFluid< NumericType >::YAML () const inline override virtual
Serializes this compressible Newtonian fluid constitutive model as a YAML message.
Implements PhQ::ConstitutiveModel.
Definition at line 328 of file CompressibleNewtonianFluid.hpp.
References PhQ::Abbreviation(), PhQ::ConstitutiveModel::CompressibleNewtonianFluid< NumericType >::bulk_dynamic_viscosity, PhQ::ConstitutiveModel::CompressibleNewtonianFluid< NumericType >::dynamic_viscosity, PhQ::ConstitutiveModel::CompressibleNewtonianFluid< NumericType >::GetType(), and PhQ::SnakeCase().
Member Data Documentation
bulk_dynamic_viscosity
template<typename NumericType = double> PhQ::BulkDynamicViscosity<NumericType> PhQ::ConstitutiveModel::CompressibleNewtonianFluid< NumericType >::bulk_dynamic_viscosity private
Bulk dynamic viscosity of this compressible Newtonian fluid constitutive model.
Definition at line 339 of file CompressibleNewtonianFluid.hpp.
Referenced by PhQ::ConstitutiveModel::CompressibleNewtonianFluid< NumericType >::BulkDynamicViscosity(), PhQ::ConstitutiveModel::CompressibleNewtonianFluid< NumericType >::JSON(), PhQ::ConstitutiveModel::CompressibleNewtonianFluid< NumericType >::Print(), PhQ::ConstitutiveModel::CompressibleNewtonianFluid< NumericType >::StrainRate(), PhQ::ConstitutiveModel::CompressibleNewtonianFluid< NumericType >::StrainRate(), PhQ::ConstitutiveModel::CompressibleNewtonianFluid< NumericType >::StrainRate(), PhQ::ConstitutiveModel::CompressibleNewtonianFluid< NumericType >::Stress(), PhQ::ConstitutiveModel::CompressibleNewtonianFluid< NumericType >::Stress(), PhQ::ConstitutiveModel::CompressibleNewtonianFluid< NumericType >::Stress(), PhQ::ConstitutiveModel::CompressibleNewtonianFluid< NumericType >::XML(), and PhQ::ConstitutiveModel::CompressibleNewtonianFluid< NumericType >::YAML().
dynamic_viscosity
template<typename NumericType = double> PhQ::DynamicViscosity<NumericType> PhQ::ConstitutiveModel::CompressibleNewtonianFluid< NumericType >::dynamic_viscosity private
Dynamic viscosity of this compressible Newtonian fluid constitutive model.
Definition at line 336 of file CompressibleNewtonianFluid.hpp.
Referenced by PhQ::ConstitutiveModel::CompressibleNewtonianFluid< NumericType >::DynamicViscosity(), PhQ::ConstitutiveModel::CompressibleNewtonianFluid< NumericType >::JSON(), PhQ::ConstitutiveModel::CompressibleNewtonianFluid< NumericType >::Print(), PhQ::ConstitutiveModel::CompressibleNewtonianFluid< NumericType >::StrainRate(), PhQ::ConstitutiveModel::CompressibleNewtonianFluid< NumericType >::StrainRate(), PhQ::ConstitutiveModel::CompressibleNewtonianFluid< NumericType >::StrainRate(), PhQ::ConstitutiveModel::CompressibleNewtonianFluid< NumericType >::Stress(), PhQ::ConstitutiveModel::CompressibleNewtonianFluid< NumericType >::Stress(), PhQ::ConstitutiveModel::CompressibleNewtonianFluid< NumericType >::Stress(), PhQ::ConstitutiveModel::CompressibleNewtonianFluid< NumericType >::XML(), and PhQ::ConstitutiveModel::CompressibleNewtonianFluid< NumericType >::YAML().
The documentation for this class was generated from the following files:
PhQ/ConstitutiveModel.hpp
PhQ/ConstitutiveModel/CompressibleNewtonianFluid.hpp