Physical Quantities (PhQ): PhQ::TransportEnergyConsumption< NumericType > Class Template Reference
PhQ::TransportEnergyConsumption< NumericType > Class Template Reference
Transport energy consumption, also known as energy consumption in transport. A measure of energy use per distance traveled. Energy consumption in transport is often measured in joules per metre (J/m), kilowatt-hours per kilometre (kW路hr/km), or kilowatt-hours per mile (kW路hr/mi).
#include "TransportEnergyConsumption.hpp"
Public Member Functions
TransportEnergyConsumption ()=default
Default constructor. Constructs a transport energy consumption with an uninitialized value.
TransportEnergyConsumption (const NumericType value, const Unit::TransportEnergyConsumption unit)
Constructor. Constructs a transport energy consumption with a given value expressed in a given transport energy consumption unit.
constexpr TransportEnergyConsumption (const Energy< NumericType > &energy, const Length< NumericType > &length)
Constructor. Constructs a transport energy consumption from a given energy and length using the definition of transport energy consumption.
~TransportEnergyConsumption () noexcept=default
Destructor. Destroys this transport energy consumption.
constexpr TransportEnergyConsumption (const TransportEnergyConsumption< NumericType > &other)=default
Copy constructor. Constructs a transport energy consumption by copying another one.
template<typename OtherNumericType >
constexpr TransportEnergyConsumption (const TransportEnergyConsumption< OtherNumericType > &other)
Copy constructor. Constructs a transport energy consumption by copying another one.
constexpr TransportEnergyConsumption (TransportEnergyConsumption< NumericType > &&other) noexcept=default
Move constructor. Constructs a transport energy consumption by moving another one.
constexpr TransportEnergyConsumption< NumericType > & operator= (const TransportEnergyConsumption< NumericType > &other)=default
Copy assignment operator. Assigns this transport energy consumption by copying another one.
template<typename OtherNumericType >
constexpr TransportEnergyConsumption< NumericType > & operator= (const TransportEnergyConsumption< OtherNumericType > &other)
Copy assignment operator. Assigns this transport energy consumption by copying another one.
constexpr TransportEnergyConsumption< NumericType > & operator= (TransportEnergyConsumption< NumericType > &&other) noexcept=default
Move assignment operator. Assigns this transport energy consumption by moving another one.
constexpr TransportEnergyConsumption< NumericType > operator+ (const TransportEnergyConsumption< NumericType > &transport_energy_consumption) const
constexpr TransportEnergyConsumption< NumericType > operator- (const TransportEnergyConsumption< NumericType > &transport_energy_consumption) const
constexpr TransportEnergyConsumption< NumericType > operator* (const NumericType number) const
constexpr Energy< NumericType > operator* (const Length< NumericType > length) const
constexpr Power< NumericType > operator* (const Speed< NumericType > speed) const
constexpr TransportEnergyConsumption< NumericType > operator/ (const NumericType number) const
constexpr NumericType operator/ (const TransportEnergyConsumption< NumericType > &transport_energy_consumption) const noexcept
constexpr void operator+= (const TransportEnergyConsumption< NumericType > &transport_energy_consumption) noexcept
constexpr void operator-= (const TransportEnergyConsumption< NumericType > &transport_energy_consumption) noexcept
constexpr void operator*= (const NumericType number) noexcept
constexpr void operator/= (const NumericType number) noexcept
constexpr double Value () const noexcept
Value of this physical quantity expressed in its standard unit of measure.
double Value (const Unit::TransportEnergyConsumption unit) const
Value of this physical quantity expressed in a given unit of measure.
constexpr double StaticValue () const
Value of this physical quantity expressed in a given unit of measure. This method can be evaluated statically at compile-time.
constexpr double & MutableValue () noexcept
Returns the value of this physical quantity expressed in its standard unit of measure as a mutable value.
constexpr void SetValue (const double value) noexcept
Sets the value of this physical quantity expressed in its standard unit of measure to the given value.
std::string Print () const
Prints this physical quantity as a string. This physical quantity's value is expressed in its standard unit of measure.
std::string Print (const Unit::TransportEnergyConsumption unit) const
Prints this physical quantity as a string. This physical quantity's value is expressed in the given unit of measure.
std::string JSON () const
Serializes this physical quantity as a JSON message. This physical quantity's value is expressed in its standard unit of measure.
std::string JSON (const Unit::TransportEnergyConsumption unit) const
Serializes this physical quantity as a JSON message. This physical quantity's value is expressed in the given unit of measure.
std::string XML () const
Serializes this physical quantity as an XML message. This physical quantity's value is expressed in its standard unit of measure.
std::string XML (const Unit::TransportEnergyConsumption unit) const
Serializes this physical quantity as an XML message. This physical quantity's value is expressed in the given unit of measure.
std::string YAML () const
Serializes this physical quantity as a YAML message. This physical quantity's value is expressed in its standard unit of measure.
std::string YAML (const Unit::TransportEnergyConsumption unit) const
Serializes this physical quantity as a YAML message. This physical quantity's value is expressed in the given unit of measure.
Static Public Member Functions
static constexpr TransportEnergyConsumption< NumericType > Zero ()
Statically creates a transport energy consumption of zero.
template<Unit::TransportEnergyConsumption Unit>
static constexpr TransportEnergyConsumption< NumericType > Create (const NumericType value)
Statically creates a transport energy consumption with a given value expressed in a given transport energy consumption unit.
static constexpr const PhQ::Dimensions & Dimensions ()
Physical dimension set of this physical quantity.
static constexpr Unit::TransportEnergyConsumption Unit ()
Standard unit of measure for this physical quantity. This physical quantity's value is stored internally in this unit of measure.
Protected Attributes
double value
Value of this physical quantity expressed in its standard unit of measure.
Private Member Functions
constexpr TransportEnergyConsumption (const NumericType value)
Constructor. Constructs a transport energy consumption with a given value expressed in the standard transport energy consumption unit.
Detailed Description
template<typename NumericType = double>
class PhQ::TransportEnergyConsumption< NumericType >
Transport energy consumption, also known as energy consumption in transport. A measure of energy use per distance traveled. Energy consumption in transport is often measured in joules per metre (J/m), kilowatt-hours per kilometre (kW路hr/km), or kilowatt-hours per mile (kW路hr/mi).
Definition at line 46 of file TransportEnergyConsumption.hpp.
Constructor & Destructor Documentation
TransportEnergyConsumption() [1/7]
template<typename NumericType = double> PhQ::TransportEnergyConsumption< NumericType >::TransportEnergyConsumption () default
Default constructor. Constructs a transport energy consumption with an uninitialized value.
TransportEnergyConsumption() [2/7]
template<typename NumericType = double> PhQ::TransportEnergyConsumption< NumericType >::TransportEnergyConsumption (const NumericType value, const Unit::TransportEnergyConsumption< NumericType > unit) inline
Constructor. Constructs a transport energy consumption with a given value expressed in a given transport energy consumption unit.
Definition at line 55 of file TransportEnergyConsumption.hpp.
TransportEnergyConsumption() [3/7]
template<typename NumericType = double> constexpr PhQ::TransportEnergyConsumption< NumericType >::TransportEnergyConsumption (const Energy< NumericType > & energy, const Length< NumericType > & length) inline constexpr
Constructor. Constructs a transport energy consumption from a given energy and length using the definition of transport energy consumption.
Definition at line 60 of file TransportEnergyConsumption.hpp.
~TransportEnergyConsumption()
template<typename NumericType = double> PhQ::TransportEnergyConsumption< NumericType >::~TransportEnergyConsumption () default noexcept
Destructor. Destroys this transport energy consumption.
TransportEnergyConsumption() [4/7]
template<typename NumericType = double> constexpr PhQ::TransportEnergyConsumption< NumericType >::TransportEnergyConsumption (const TransportEnergyConsumption< NumericType > & other) constexpr default
Copy constructor. Constructs a transport energy consumption by copying another one.
TransportEnergyConsumption() [5/7]
template<typename NumericType = double> template<typename OtherNumericType > constexpr PhQ::TransportEnergyConsumption< NumericType >::TransportEnergyConsumption (const TransportEnergyConsumption< OtherNumericType > & other) inline explicit constexpr
Copy constructor. Constructs a transport energy consumption by copying another one.
Definition at line 73 of file TransportEnergyConsumption.hpp.
TransportEnergyConsumption() [6/7]
template<typename NumericType = double> constexpr PhQ::TransportEnergyConsumption< NumericType >::TransportEnergyConsumption (TransportEnergyConsumption< NumericType > && other) constexpr default noexcept
Move constructor. Constructs a transport energy consumption by moving another one.
TransportEnergyConsumption() [7/7]
template<typename NumericType = double> constexpr PhQ::TransportEnergyConsumption< NumericType >::TransportEnergyConsumption (const NumericType value) inline explicit constexpr private
Constructor. Constructs a transport energy consumption with a given value expressed in the standard transport energy consumption unit.
Definition at line 168 of file TransportEnergyConsumption.hpp.
Member Function Documentation
Create()
template<typename NumericType = double> template<Unit::TransportEnergyConsumption Unit> static constexpr TransportEnergyConsumption<NumericType> PhQ::TransportEnergyConsumption< NumericType >::Create (const NumericType value) inline static constexpr
Statically creates a transport energy consumption with a given value expressed in a given transport energy consumption unit.
Definition at line 108 of file TransportEnergyConsumption.hpp.
References PhQ::ConvertStatically(), PhQ::DimensionalScalar< Unit::TransportEnergyConsumption, double >::Unit(), and PhQ::DimensionalScalar< Unit::TransportEnergyConsumption, double >::value.
Dimensions()
static constexpr const PhQ::Dimensions& PhQ::DimensionalScalar< Unit::TransportEnergyConsumption , double >::Dimensions () inline static constexpr inherited
Physical dimension set of this physical quantity.
Definition at line 53 of file DimensionalScalar.hpp.
JSON() [1/2]
std::string PhQ::DimensionalScalar< Unit::TransportEnergyConsumption , double >::JSON () const inline inherited
Serializes this physical quantity as a JSON message. This physical quantity's value is expressed in its standard unit of measure.
Definition at line 106 of file DimensionalScalar.hpp.
JSON() [2/2]
std::string PhQ::DimensionalScalar< Unit::TransportEnergyConsumption , double >::JSON (const Unit::TransportEnergyConsumption unit) const inline inherited
Serializes this physical quantity as a JSON message. This physical quantity's value is expressed in the given unit of measure.
Definition at line 116 of file DimensionalScalar.hpp.
MutableValue()
constexpr double & PhQ::DimensionalScalar< Unit::TransportEnergyConsumption , double >::MutableValue () inline constexpr noexcept inherited
Returns the value of this physical quantity expressed in its standard unit of measure as a mutable value.
Definition at line 82 of file DimensionalScalar.hpp.
operator*() [1/3]
template<typename NumericType = double> constexpr Energy<NumericType> PhQ::TransportEnergyConsumption< NumericType >::operator* (const Length< NumericType > length) const inline constexpr
Definition at line 130 of file TransportEnergyConsumption.hpp.
operator*() [2/3]
template<typename NumericType = double> constexpr TransportEnergyConsumption<NumericType> PhQ::TransportEnergyConsumption< NumericType >::operator* (const NumericType number) const inline constexpr
Definition at line 126 of file TransportEnergyConsumption.hpp.
References PhQ::DimensionalScalar< Unit::TransportEnergyConsumption, double >::value.
operator*() [3/3]
template<typename NumericType = double> constexpr Power<NumericType> PhQ::TransportEnergyConsumption< NumericType >::operator* (const Speed< NumericType > speed) const inline constexpr
Definition at line 134 of file TransportEnergyConsumption.hpp.
operator*=()
template<typename NumericType = double> constexpr void PhQ::TransportEnergyConsumption< NumericType >::operator*= (const NumericType number) inline constexpr noexcept
Definition at line 157 of file TransportEnergyConsumption.hpp.
References PhQ::DimensionalScalar< Unit::TransportEnergyConsumption, double >::value.
operator+()
template<typename NumericType = double> constexpr TransportEnergyConsumption<NumericType> PhQ::TransportEnergyConsumption< NumericType >::operator+ (const TransportEnergyConsumption< NumericType > & transport_energy_consumption) const inline constexpr
Definition at line 114 of file TransportEnergyConsumption.hpp.
References PhQ::DimensionalScalar< UnitType, NumericType >::value, and PhQ::DimensionalScalar< Unit::TransportEnergyConsumption, double >::value.
operator+=()
template<typename NumericType = double> constexpr void PhQ::TransportEnergyConsumption< NumericType >::operator+= (const TransportEnergyConsumption< NumericType > & transport_energy_consumption) inline constexpr noexcept
Definition at line 147 of file TransportEnergyConsumption.hpp.
References PhQ::DimensionalScalar< Unit::TransportEnergyConsumption, double >::value.
operator-()
template<typename NumericType = double> constexpr TransportEnergyConsumption<NumericType> PhQ::TransportEnergyConsumption< NumericType >::operator- (const TransportEnergyConsumption< NumericType > & transport_energy_consumption) const inline constexpr
Definition at line 120 of file TransportEnergyConsumption.hpp.
References PhQ::DimensionalScalar< UnitType, NumericType >::value, and PhQ::DimensionalScalar< Unit::TransportEnergyConsumption, double >::value.
operator-=()
template<typename NumericType = double> constexpr void PhQ::TransportEnergyConsumption< NumericType >::operator-= (const TransportEnergyConsumption< NumericType > & transport_energy_consumption) inline constexpr noexcept
Definition at line 152 of file TransportEnergyConsumption.hpp.
References PhQ::DimensionalScalar< Unit::TransportEnergyConsumption, double >::value.
operator/() [1/2]
template<typename NumericType = double> constexpr TransportEnergyConsumption<NumericType> PhQ::TransportEnergyConsumption< NumericType >::operator/ (const NumericType number) const inline constexpr
Definition at line 138 of file TransportEnergyConsumption.hpp.
References PhQ::DimensionalScalar< Unit::TransportEnergyConsumption, double >::value.
operator/() [2/2]
template<typename NumericType = double> constexpr NumericType PhQ::TransportEnergyConsumption< NumericType >::operator/ (const TransportEnergyConsumption< NumericType > & transport_energy_consumption) const inline constexpr noexcept
Definition at line 142 of file TransportEnergyConsumption.hpp.
References PhQ::DimensionalScalar< Unit::TransportEnergyConsumption, double >::value.
operator/=()
template<typename NumericType = double> constexpr void PhQ::TransportEnergyConsumption< NumericType >::operator/= (const NumericType number) inline constexpr noexcept
Definition at line 161 of file TransportEnergyConsumption.hpp.
References PhQ::DimensionalScalar< Unit::TransportEnergyConsumption, double >::value.
operator=() [1/3]
template<typename NumericType = double> constexpr TransportEnergyConsumption<NumericType>& PhQ::TransportEnergyConsumption< NumericType >::operator= (const TransportEnergyConsumption< NumericType > & other) constexpr default
Copy assignment operator. Assigns this transport energy consumption by copying another one.
operator=() [2/3]
template<typename NumericType = double> template<typename OtherNumericType > constexpr TransportEnergyConsumption<NumericType>& PhQ::TransportEnergyConsumption< NumericType >::operator= (const TransportEnergyConsumption< OtherNumericType > & other) inline constexpr
Copy assignment operator. Assigns this transport energy consumption by copying another one.
Definition at line 89 of file TransportEnergyConsumption.hpp.
References PhQ::DimensionalScalar< UnitType, NumericType >::Value(), and PhQ::DimensionalScalar< Unit::TransportEnergyConsumption, double >::value.
operator=() [3/3]
template<typename NumericType = double> constexpr TransportEnergyConsumption<NumericType>& PhQ::TransportEnergyConsumption< NumericType >::operator= (TransportEnergyConsumption< NumericType > && other) constexpr default noexcept
Move assignment operator. Assigns this transport energy consumption by moving another one.
Print() [1/2]
std::string PhQ::DimensionalScalar< Unit::TransportEnergyConsumption , double >::Print () const inline inherited
Prints this physical quantity as a string. This physical quantity's value is expressed in its standard unit of measure.
Definition at line 94 of file DimensionalScalar.hpp.
Print() [2/2]
std::string PhQ::DimensionalScalar< Unit::TransportEnergyConsumption , double >::Print (const Unit::TransportEnergyConsumption unit) const inline inherited
Prints this physical quantity as a string. This physical quantity's value is expressed in the given unit of measure.
Definition at line 100 of file DimensionalScalar.hpp.
SetValue()
constexpr void PhQ::DimensionalScalar< Unit::TransportEnergyConsumption , double >::SetValue (const double value) inline constexpr noexcept inherited
Sets the value of this physical quantity expressed in its standard unit of measure to the given value.
Definition at line 88 of file DimensionalScalar.hpp.
StaticValue()
constexpr double PhQ::DimensionalScalar< Unit::TransportEnergyConsumption , double >::StaticValue () const inline constexpr inherited
Value of this physical quantity expressed in a given unit of measure. This method can be evaluated statically at compile-time.
Definition at line 76 of file DimensionalScalar.hpp.
Unit()
static constexpr Unit::TransportEnergyConsumption PhQ::DimensionalScalar< Unit::TransportEnergyConsumption , double >::Unit () inline static constexpr inherited
Standard unit of measure for this physical quantity. This physical quantity's value is stored internally in this unit of measure.
Definition at line 59 of file DimensionalScalar.hpp.
Value() [1/2]
constexpr double PhQ::DimensionalScalar< Unit::TransportEnergyConsumption , double >::Value () const inline constexpr noexcept inherited
Value of this physical quantity expressed in its standard unit of measure.
Definition at line 64 of file DimensionalScalar.hpp.
Value() [2/2]
double PhQ::DimensionalScalar< Unit::TransportEnergyConsumption , double >::Value (const Unit::TransportEnergyConsumption unit) const inline inherited
Value of this physical quantity expressed in a given unit of measure.
Definition at line 69 of file DimensionalScalar.hpp.
XML() [1/2]
std::string PhQ::DimensionalScalar< Unit::TransportEnergyConsumption , double >::XML () const inline inherited
Serializes this physical quantity as an XML message. This physical quantity's value is expressed in its standard unit of measure.
Definition at line 126 of file DimensionalScalar.hpp.
XML() [2/2]
std::string PhQ::DimensionalScalar< Unit::TransportEnergyConsumption , double >::XML (const Unit::TransportEnergyConsumption unit) const inline inherited
Serializes this physical quantity as an XML message. This physical quantity's value is expressed in the given unit of measure.
Definition at line 136 of file DimensionalScalar.hpp.
YAML() [1/2]
std::string PhQ::DimensionalScalar< Unit::TransportEnergyConsumption , double >::YAML () const inline inherited
Serializes this physical quantity as a YAML message. This physical quantity's value is expressed in its standard unit of measure.
Definition at line 146 of file DimensionalScalar.hpp.
YAML() [2/2]
std::string PhQ::DimensionalScalar< Unit::TransportEnergyConsumption , double >::YAML (const Unit::TransportEnergyConsumption unit) const inline inherited
Serializes this physical quantity as a YAML message. This physical quantity's value is expressed in the given unit of measure.
Definition at line 156 of file DimensionalScalar.hpp.
Zero()
template<typename NumericType = double> static constexpr TransportEnergyConsumption<NumericType> PhQ::TransportEnergyConsumption< NumericType >::Zero () inline static constexpr
Statically creates a transport energy consumption of zero.
Definition at line 101 of file TransportEnergyConsumption.hpp.
Member Data Documentation
value
double PhQ::DimensionalScalar< Unit::TransportEnergyConsumption , double >::value protected inherited
Value of this physical quantity expressed in its standard unit of measure.
Definition at line 216 of file DimensionalScalar.hpp.
The documentation for this class was generated from the following files:
PhQ/Energy.hpp
PhQ/TransportEnergyConsumption.hpp