Physical Quantities: PhQ::ThermalConductivity< NumericType > Class Template Reference
PhQ::ThermalConductivity< NumericType > Class Template Reference
Three-dimensional Euclidean Cauchy thermal conductivity symmetric dyadic tensor. Contains six components in Cartesian coordinates: xx, xy = yx, xz = zx, yy, yz = zy, and zz. In general, thermal conductivity is a tensor; however, in isotropic materials, thermal conductivity simplifies to a scalar. For the scalar components or resultants of a thermal conductivity tensor, see PhQ::ScalarThermalConductivity.
#include "ThermalConductivity.hpp"
Public Member Functions
ThermalConductivity ()=default
Default constructor. Constructs a thermal conductivity tensor with an uninitialized value.
ThermalConductivity (const SymmetricDyad< NumericType > &value, const Unit::ThermalConductivity unit)
Constructor. Constructs a thermal conductivity tensor with a given value expressed in a given thermal conductivity unit.
constexpr ThermalConductivity (const ScalarThermalConductivity< NumericType > &scalar_thermal_conductivity)
Constructor. Constructs a thermal conductivity tensor from a given scalar thermal conductivity.
~ThermalConductivity () noexcept=default
Destructor. Destroys this thermal conductivity tensor.
constexpr ThermalConductivity (const ThermalConductivity< NumericType > &other)=default
Copy constructor. Constructs a thermal conductivity tensor by copying another one.
template<typename OtherNumericType >
constexpr ThermalConductivity (const ThermalConductivity< OtherNumericType > &other)
Copy constructor. Constructs a thermal conductivity tensor by copying another one.
constexpr ThermalConductivity (ThermalConductivity< NumericType > &&other) noexcept=default
Move constructor. Constructs a thermal conductivity tensor by moving another one.
constexpr ThermalConductivity< NumericType > & operator= (const ThermalConductivity< NumericType > &other)=default
Copy assignment operator. Assigns this thermal conductivity tensor by copying another one.
template<typename OtherNumericType >
constexpr ThermalConductivity< NumericType > & operator= (const ThermalConductivity< OtherNumericType > &other)
Copy assignment operator. Assigns this thermal conductivity tensor by copying another one.
constexpr ThermalConductivity< NumericType > & operator= (ThermalConductivity< NumericType > &&other) noexcept=default
Move assignment operator. Assigns this thermal conductivity tensor by moving another one.
constexpr ScalarThermalConductivity< NumericType > xx () const noexcept
Returns the xx Cartesian component of this thermal conductivity tensor.
constexpr ScalarThermalConductivity< NumericType > xy () const noexcept
Returns the xy = yx Cartesian component of this thermal conductivity tensor.
constexpr ScalarThermalConductivity< NumericType > xz () const noexcept
Returns the xz = zx Cartesian component of this thermal conductivity tensor.
constexpr ScalarThermalConductivity< NumericType > yx () const noexcept
Returns the yx = xy Cartesian component of this thermal conductivity tensor.
constexpr ScalarThermalConductivity< NumericType > yy () const noexcept
Returns the yy Cartesian component of this thermal conductivity tensor.
constexpr ScalarThermalConductivity< NumericType > yz () const noexcept
Returns the yz = zy Cartesian component of this thermal conductivity tensor.
constexpr ScalarThermalConductivity< NumericType > zx () const noexcept
Returns the zx = xz Cartesian component of this thermal conductivity tensor.
constexpr ScalarThermalConductivity< NumericType > zy () const noexcept
Returns the zy = yz Cartesian component of this thermal conductivity tensor.
constexpr ScalarThermalConductivity< NumericType > zz () const noexcept
Returns the zz Cartesian component of this thermal conductivity tensor.
constexpr ThermalConductivity< NumericType > operator+ (const ThermalConductivity< NumericType > &thermal_conductivity) const
constexpr ThermalConductivity< NumericType > operator- (const ThermalConductivity< NumericType > &thermal_conductivity) const
constexpr ThermalConductivity< NumericType > operator* (const NumericType number) const
constexpr ThermalConductivity< NumericType > operator/ (const NumericType number) const
constexpr void operator+= (const ThermalConductivity< NumericType > &thermal_conductivity) noexcept
constexpr void operator-= (const ThermalConductivity< NumericType > &thermal_conductivity) noexcept
constexpr void operator*= (const NumericType number) noexcept
constexpr void operator/= (const NumericType number) noexcept
constexpr const PhQ::SymmetricDyad< NumericType > & Value () const noexcept
Value of this physical quantity expressed in its standard unit of measure.
PhQ::SymmetricDyad< NumericType > Value (const UnitType unit) const
Value of this physical quantity expressed in a given unit of measure.
template<UnitType NewUnit>
constexpr PhQ::SymmetricDyad< NumericType > StaticValue () const
Value of this physical quantity expressed in a given unit of measure. This method can be evaluated statically at compile-time.
constexpr PhQ::SymmetricDyad< NumericType > & MutableValue () noexcept
Returns the value of this physical quantity expressed in its standard unit of measure as a mutable value.
constexpr void SetValue (const PhQ::SymmetricDyad< NumericType > &value) noexcept
Sets the value of this physical quantity expressed in its standard unit of measure to the given value.
std::string Print () const
Prints this physical quantity as a string. This physical quantity's value is expressed in its standard unit of measure.
std::string Print (const UnitType unit) const
Prints this physical quantity as a string. This physical quantity's value is expressed in the given unit of measure.
std::string JSON () const
Serializes this physical quantity as a JSON message. This physical quantity's value is expressed in its standard unit of measure.
std::string JSON (const UnitType unit) const
Serializes this physical quantity as a JSON message. This physical quantity's value is expressed in the given unit of measure.
std::string XML () const
Serializes this physical quantity as an XML message. This physical quantity's value is expressed in its standard unit of measure.
std::string XML (const UnitType unit) const
Serializes this physical quantity as an XML message. This physical quantity's value is expressed in the given unit of measure.
std::string YAML () const
Serializes this physical quantity as a YAML message. This physical quantity's value is expressed in its standard unit of measure.
std::string YAML (const UnitType unit) const
Serializes this physical quantity as a YAML message. This physical quantity's value is expressed in the given unit of measure.
Static Public Member Functions
static constexpr ThermalConductivity< NumericType > Zero ()
Statically creates a thermal conductivity tensor of zero.
template<Unit::ThermalConductivity Unit>
static constexpr ThermalConductivity< NumericType > Create (const NumericType xx, const NumericType xy, const NumericType xz, const NumericType yy, const NumericType yz, const NumericType zz)
Statically creates a thermal conductivity tensor from the given xx, xy, xz, yy, yz, and zz Cartesian components expressed in a given pressure unit.
template<Unit::ThermalConductivity Unit>
static constexpr ThermalConductivity< NumericType > Create (const std::array< NumericType, 6 > &xx_xy_xz_yy_yz_zz)
Statically creates a thermal conductivity tensor from the given xx, xy, xz, yy, yz, and zz Cartesian components expressed in a given pressure unit.
template<Unit::ThermalConductivity Unit>
static constexpr ThermalConductivity< NumericType > Create (const SymmetricDyad< NumericType > &value)
Statically creates a thermal conductivity tensor with a given value expressed in a given thermal conductivity unit.
static constexpr const PhQ::Dimensions & Dimensions ()
Physical dimension set of this physical quantity.
static constexpr UnitType Unit ()
Standard unit of measure for this physical quantity. This physical quantity's value is stored internally in this unit of measure.
Protected Attributes
PhQ::SymmetricDyad< NumericType > value
Value of this physical quantity expressed in its standard unit of measure.
Private Member Functions
constexpr ThermalConductivity (const SymmetricDyad< NumericType > &value)
Constructor. Constructs a thermal conductivity tensor with a given value expressed in the standard thermal conductivity unit.
Detailed Description
template<typename NumericType = double>
class PhQ::ThermalConductivity< NumericType >
Three-dimensional Euclidean Cauchy thermal conductivity symmetric dyadic tensor. Contains six components in Cartesian coordinates: xx, xy = yx, xz = zx, yy, yz = zy, and zz. In general, thermal conductivity is a tensor; however, in isotropic materials, thermal conductivity simplifies to a scalar. For the scalar components or resultants of a thermal conductivity tensor, see PhQ::ScalarThermalConductivity.
Definition at line 46 of file ThermalConductivity.hpp.
Constructor & Destructor Documentation
ThermalConductivity() [1/7]
template<typename NumericType = double> PhQ::ThermalConductivity< NumericType >::ThermalConductivity () default
Default constructor. Constructs a thermal conductivity tensor with an uninitialized value.
ThermalConductivity() [2/7]
template<typename NumericType = double> PhQ::ThermalConductivity< NumericType >::ThermalConductivity (const SymmetricDyad< NumericType > & value, const Unit::ThermalConductivity< NumericType > unit) inline
Constructor. Constructs a thermal conductivity tensor with a given value expressed in a given thermal conductivity unit.
Definition at line 55 of file ThermalConductivity.hpp.
ThermalConductivity() [3/7]
template<typename NumericType = double> constexpr PhQ::ThermalConductivity< NumericType >::ThermalConductivity (const ScalarThermalConductivity< NumericType > & scalar_thermal_conductivity) inline explicit constexpr
Constructor. Constructs a thermal conductivity tensor from a given scalar thermal conductivity.
Definition at line 60 of file ThermalConductivity.hpp.
References PhQ::DimensionalScalar< UnitType, NumericType >::Value().
~ThermalConductivity()
template<typename NumericType = double> PhQ::ThermalConductivity< NumericType >::~ThermalConductivity () default noexcept
Destructor. Destroys this thermal conductivity tensor.
ThermalConductivity() [4/7]
template<typename NumericType = double> constexpr PhQ::ThermalConductivity< NumericType >::ThermalConductivity (const ThermalConductivity< NumericType > & other) constexpr default
Copy constructor. Constructs a thermal conductivity tensor by copying another one.
ThermalConductivity() [5/7]
template<typename NumericType = double> template<typename OtherNumericType > constexpr PhQ::ThermalConductivity< NumericType >::ThermalConductivity (const ThermalConductivity< OtherNumericType > & other) inline explicit constexpr
Copy constructor. Constructs a thermal conductivity tensor by copying another one.
Definition at line 74 of file ThermalConductivity.hpp.
ThermalConductivity() [6/7]
template<typename NumericType = double> constexpr PhQ::ThermalConductivity< NumericType >::ThermalConductivity (ThermalConductivity< NumericType > && other) constexpr default noexcept
Move constructor. Constructs a thermal conductivity tensor by moving another one.
ThermalConductivity() [7/7]
template<typename NumericType = double> constexpr PhQ::ThermalConductivity< NumericType >::ThermalConductivity (const SymmetricDyad< NumericType > & value) inline explicit constexpr private
Constructor. Constructs a thermal conductivity tensor with a given value expressed in the standard thermal conductivity unit.
Definition at line 217 of file ThermalConductivity.hpp.
Member Function Documentation
Create() [1/3]
template<typename NumericType = double> template<Unit::ThermalConductivity Unit> static constexpr ThermalConductivity< NumericType > PhQ::ThermalConductivity< NumericType >::Create (const NumericType xx, const NumericType xy, const NumericType xz, const NumericType yy, const NumericType yz, const NumericType zz) inline static constexpr
Statically creates a thermal conductivity tensor from the given xx, xy, xz, yy, yz, and zz Cartesian components expressed in a given pressure unit.
Definition at line 107 of file ThermalConductivity.hpp.
References PhQ::ThermalConductivity< NumericType >::xx(), PhQ::ThermalConductivity< NumericType >::xy(), PhQ::ThermalConductivity< NumericType >::xz(), PhQ::ThermalConductivity< NumericType >::yy(), PhQ::ThermalConductivity< NumericType >::yz(), and PhQ::ThermalConductivity< NumericType >::zz().
Create() [2/3]
template<typename NumericType = double> template<Unit::ThermalConductivity Unit> static constexpr ThermalConductivity< NumericType > PhQ::ThermalConductivity< NumericType >::Create (const std::array< NumericType, 6 > & xx_xy_xz_yy_yz_zz) inline static constexpr
Statically creates a thermal conductivity tensor from the given xx, xy, xz, yy, yz, and zz Cartesian components expressed in a given pressure unit.
Definition at line 118 of file ThermalConductivity.hpp.
Create() [3/3]
template<typename NumericType = double> template<Unit::ThermalConductivity Unit> static constexpr ThermalConductivity< NumericType > PhQ::ThermalConductivity< NumericType >::Create (const SymmetricDyad< NumericType > & value) inline static constexpr
Statically creates a thermal conductivity tensor with a given value expressed in a given thermal conductivity unit.
Definition at line 128 of file ThermalConductivity.hpp.
References PhQ::DimensionalSymmetricDyad< UnitType, NumericType >::value.
Dimensions()
template<typename UnitType , typename NumericType = double> static constexpr const PhQ::Dimensions & PhQ::DimensionalSymmetricDyad< UnitType, NumericType >::Dimensions () inline static constexpr inherited
Physical dimension set of this physical quantity.
Definition at line 50 of file DimensionalSymmetricDyad.hpp.
JSON() [1/2]
template<typename UnitType , typename NumericType = double> std::string PhQ::DimensionalSymmetricDyad< UnitType, NumericType >::JSON () const inline inherited
Serializes this physical quantity as a JSON message. This physical quantity's value is expressed in its standard unit of measure.
Definition at line 103 of file DimensionalSymmetricDyad.hpp.
References PhQ::Abbreviation(), and PhQ::DimensionalSymmetricDyad< UnitType, NumericType >::value.
Referenced by PhQ::DimensionalSymmetricDyad< UnitType, NumericType >::JSON().
JSON() [2/2]
template<typename UnitType , typename NumericType = double> std::string PhQ::DimensionalSymmetricDyad< UnitType, NumericType >::JSON (const UnitType unit) const inline inherited
Serializes this physical quantity as a JSON message. This physical quantity's value is expressed in the given unit of measure.
Definition at line 113 of file DimensionalSymmetricDyad.hpp.
References PhQ::Abbreviation(), PhQ::DimensionalSymmetricDyad< UnitType, NumericType >::JSON(), and PhQ::DimensionalSymmetricDyad< UnitType, NumericType >::Value().
MutableValue()
template<typename UnitType , typename NumericType = double> constexpr PhQ::SymmetricDyad< NumericType > & PhQ::DimensionalSymmetricDyad< UnitType, NumericType >::MutableValue () inline constexpr noexcept inherited
Returns the value of this physical quantity expressed in its standard unit of measure as a mutable value.
Definition at line 79 of file DimensionalSymmetricDyad.hpp.
References PhQ::DimensionalSymmetricDyad< UnitType, NumericType >::value.
operator*()
template<typename NumericType = double> constexpr ThermalConductivity< NumericType > PhQ::ThermalConductivity< NumericType >::operator* (const NumericType number) const inline constexpr
Definition at line 190 of file ThermalConductivity.hpp.
References PhQ::DimensionalSymmetricDyad< UnitType, NumericType >::value.
operator*=()
template<typename NumericType = double> constexpr void PhQ::ThermalConductivity< NumericType >::operator*= (const NumericType number) inline constexpr noexcept
Definition at line 206 of file ThermalConductivity.hpp.
References PhQ::DimensionalSymmetricDyad< UnitType, NumericType >::value.
operator+()
template<typename NumericType = double> constexpr ThermalConductivity< NumericType > PhQ::ThermalConductivity< NumericType >::operator+ (const ThermalConductivity< NumericType > & thermal_conductivity) const inline constexpr
Definition at line 180 of file ThermalConductivity.hpp.
References PhQ::DimensionalSymmetricDyad< UnitType, NumericType >::value.
operator+=()
template<typename NumericType = double> constexpr void PhQ::ThermalConductivity< NumericType >::operator+= (const ThermalConductivity< NumericType > & thermal_conductivity) inline constexpr noexcept
Definition at line 198 of file ThermalConductivity.hpp.
References PhQ::DimensionalSymmetricDyad< UnitType, NumericType >::value.
operator-()
template<typename NumericType = double> constexpr ThermalConductivity< NumericType > PhQ::ThermalConductivity< NumericType >::operator- (const ThermalConductivity< NumericType > & thermal_conductivity) const inline constexpr
Definition at line 185 of file ThermalConductivity.hpp.
References PhQ::DimensionalSymmetricDyad< UnitType, NumericType >::value.
operator-=()
template<typename NumericType = double> constexpr void PhQ::ThermalConductivity< NumericType >::operator-= (const ThermalConductivity< NumericType > & thermal_conductivity) inline constexpr noexcept
Definition at line 202 of file ThermalConductivity.hpp.
References PhQ::DimensionalSymmetricDyad< UnitType, NumericType >::value.
operator/()
template<typename NumericType = double> constexpr ThermalConductivity< NumericType > PhQ::ThermalConductivity< NumericType >::operator/ (const NumericType number) const inline constexpr
Definition at line 194 of file ThermalConductivity.hpp.
References PhQ::DimensionalSymmetricDyad< UnitType, NumericType >::value.
operator/=()
template<typename NumericType = double> constexpr void PhQ::ThermalConductivity< NumericType >::operator/= (const NumericType number) inline constexpr noexcept
Definition at line 210 of file ThermalConductivity.hpp.
References PhQ::DimensionalSymmetricDyad< UnitType, NumericType >::value.
operator=() [1/3]
template<typename NumericType = double> constexpr ThermalConductivity< NumericType > & PhQ::ThermalConductivity< NumericType >::operator= (const ThermalConductivity< NumericType > & other) constexpr default
Copy assignment operator. Assigns this thermal conductivity tensor by copying another one.
operator=() [2/3]
template<typename NumericType = double> template<typename OtherNumericType > constexpr ThermalConductivity< NumericType > & PhQ::ThermalConductivity< NumericType >::operator= (const ThermalConductivity< OtherNumericType > & other) inline constexpr
Copy assignment operator. Assigns this thermal conductivity tensor by copying another one.
Definition at line 88 of file ThermalConductivity.hpp.
References PhQ::DimensionalSymmetricDyad< UnitType, NumericType >::Value(), and PhQ::DimensionalSymmetricDyad< UnitType, NumericType >::value.
operator=() [3/3]
template<typename NumericType = double> constexpr ThermalConductivity< NumericType > & PhQ::ThermalConductivity< NumericType >::operator= (ThermalConductivity< NumericType > && other) constexpr default noexcept
Move assignment operator. Assigns this thermal conductivity tensor by moving another one.
Print() [1/2]
template<typename UnitType , typename NumericType = double> std::string PhQ::DimensionalSymmetricDyad< UnitType, NumericType >::Print () const inline inherited
Prints this physical quantity as a string. This physical quantity's value is expressed in its standard unit of measure.
Definition at line 91 of file DimensionalSymmetricDyad.hpp.
References PhQ::Abbreviation(), and PhQ::DimensionalSymmetricDyad< UnitType, NumericType >::value.
Referenced by PhQ::operator<<(), PhQ::operator<<(), and PhQ::operator<<().
Print() [2/2]
template<typename UnitType , typename NumericType = double> std::string PhQ::DimensionalSymmetricDyad< UnitType, NumericType >::Print (const UnitType unit) const inline inherited
Prints this physical quantity as a string. This physical quantity's value is expressed in the given unit of measure.
Definition at line 97 of file DimensionalSymmetricDyad.hpp.
References PhQ::Abbreviation(), and PhQ::DimensionalSymmetricDyad< UnitType, NumericType >::Value().
SetValue()
template<typename UnitType , typename NumericType = double> constexpr void PhQ::DimensionalSymmetricDyad< UnitType, NumericType >::SetValue (const PhQ::SymmetricDyad< NumericType > & value) inline constexpr noexcept inherited
Sets the value of this physical quantity expressed in its standard unit of measure to the given value.
Definition at line 85 of file DimensionalSymmetricDyad.hpp.
References PhQ::DimensionalSymmetricDyad< UnitType, NumericType >::value.
StaticValue()
template<typename UnitType , typename NumericType = double> template<UnitType NewUnit> constexpr PhQ::SymmetricDyad< NumericType > PhQ::DimensionalSymmetricDyad< UnitType, NumericType >::StaticValue () const inline constexpr inherited
Value of this physical quantity expressed in a given unit of measure. This method can be evaluated statically at compile-time.
Definition at line 73 of file DimensionalSymmetricDyad.hpp.
References PhQ::DimensionalSymmetricDyad< UnitType, NumericType >::value.
Unit()
template<typename UnitType , typename NumericType = double> static constexpr UnitType PhQ::DimensionalSymmetricDyad< UnitType, NumericType >::Unit () inline static constexpr inherited
Standard unit of measure for this physical quantity. This physical quantity's value is stored internally in this unit of measure.
Definition at line 56 of file DimensionalSymmetricDyad.hpp.
Value() [1/2]
template<typename UnitType , typename NumericType = double> constexpr const PhQ::SymmetricDyad< NumericType > & PhQ::DimensionalSymmetricDyad< UnitType, NumericType >::Value () const inline constexpr noexcept inherited
Value of this physical quantity expressed in its standard unit of measure.
Definition at line 61 of file DimensionalSymmetricDyad.hpp.
References PhQ::DimensionalSymmetricDyad< UnitType, NumericType >::value.
Referenced by PhQ::DimensionalSymmetricDyad< UnitType, NumericType >::JSON(), PhQ::DimensionalSymmetricDyad< UnitType, NumericType >::operator=(), PhQ::StrainRate< NumericType >::operator=(), PhQ::Stress< NumericType >::operator=(), PhQ::ThermalConductivity< NumericType >::operator=(), PhQ::operator==(), PhQ::operator==(), PhQ::operator==(), PhQ::operator==(), PhQ::PlanarHeatFlux< NumericType >::PlanarHeatFlux(), PhQ::PlanarTraction< NumericType >::PlanarTraction(), PhQ::DimensionalSymmetricDyad< UnitType, NumericType >::Print(), PhQ::ConstitutiveModel::ElasticIsotropicSolid< NumericType >::Strain(), PhQ::ConstitutiveModel::ElasticIsotropicSolid< NumericType >::Strain(), PhQ::ConstitutiveModel::ElasticIsotropicSolid< NumericType >::Strain(), PhQ::ConstitutiveModel::CompressibleNewtonianFluid< NumericType >::StrainRate(), PhQ::ConstitutiveModel::IncompressibleNewtonianFluid< NumericType >::StrainRate(), PhQ::ConstitutiveModel::CompressibleNewtonianFluid< NumericType >::StrainRate(), PhQ::ConstitutiveModel::IncompressibleNewtonianFluid< NumericType >::StrainRate(), PhQ::ConstitutiveModel::CompressibleNewtonianFluid< NumericType >::StrainRate(), PhQ::ConstitutiveModel::IncompressibleNewtonianFluid< NumericType >::StrainRate(), PhQ::ConstitutiveModel::CompressibleNewtonianFluid< NumericType >::Stress(), PhQ::ConstitutiveModel::IncompressibleNewtonianFluid< NumericType >::Stress(), PhQ::ConstitutiveModel::CompressibleNewtonianFluid< NumericType >::Stress(), PhQ::ConstitutiveModel::IncompressibleNewtonianFluid< NumericType >::Stress(), PhQ::ConstitutiveModel::CompressibleNewtonianFluid< NumericType >::Stress(), PhQ::ConstitutiveModel::IncompressibleNewtonianFluid< NumericType >::Stress(), PhQ::Traction< NumericType >::Traction(), PhQ::DimensionalSymmetricDyad< UnitType, NumericType >::XML(), and PhQ::DimensionalSymmetricDyad< UnitType, NumericType >::YAML().
Value() [2/2]
template<typename UnitType , typename NumericType = double> PhQ::SymmetricDyad< NumericType > PhQ::DimensionalSymmetricDyad< UnitType, NumericType >::Value (const UnitType unit) const inline inherited
Value of this physical quantity expressed in a given unit of measure.
Definition at line 66 of file DimensionalSymmetricDyad.hpp.
References PhQ::Convert(), and PhQ::DimensionalSymmetricDyad< UnitType, NumericType >::value.
XML() [1/2]
template<typename UnitType , typename NumericType = double> std::string PhQ::DimensionalSymmetricDyad< UnitType, NumericType >::XML () const inline inherited
Serializes this physical quantity as an XML message. This physical quantity's value is expressed in its standard unit of measure.
Definition at line 123 of file DimensionalSymmetricDyad.hpp.
References PhQ::Abbreviation(), and PhQ::DimensionalSymmetricDyad< UnitType, NumericType >::value.
Referenced by PhQ::DimensionalSymmetricDyad< UnitType, NumericType >::XML().
XML() [2/2]
template<typename UnitType , typename NumericType = double> std::string PhQ::DimensionalSymmetricDyad< UnitType, NumericType >::XML (const UnitType unit) const inline inherited
Serializes this physical quantity as an XML message. This physical quantity's value is expressed in the given unit of measure.
Definition at line 133 of file DimensionalSymmetricDyad.hpp.
References PhQ::Abbreviation(), PhQ::DimensionalSymmetricDyad< UnitType, NumericType >::Value(), and PhQ::DimensionalSymmetricDyad< UnitType, NumericType >::XML().
xx()
template<typename NumericType = double> constexpr ScalarThermalConductivity< NumericType > PhQ::ThermalConductivity< NumericType >::xx () const inline constexpr noexcept
Returns the xx Cartesian component of this thermal conductivity tensor.
Definition at line 136 of file ThermalConductivity.hpp.
References PhQ::DimensionalSymmetricDyad< UnitType, NumericType >::value.
Referenced by PhQ::ThermalConductivity< NumericType >::Create().
xy()
template<typename NumericType = double> constexpr ScalarThermalConductivity< NumericType > PhQ::ThermalConductivity< NumericType >::xy () const inline constexpr noexcept
Returns the xy = yx Cartesian component of this thermal conductivity tensor.
Definition at line 141 of file ThermalConductivity.hpp.
References PhQ::DimensionalSymmetricDyad< UnitType, NumericType >::value.
Referenced by PhQ::ThermalConductivity< NumericType >::Create().
xz()
template<typename NumericType = double> constexpr ScalarThermalConductivity< NumericType > PhQ::ThermalConductivity< NumericType >::xz () const inline constexpr noexcept
Returns the xz = zx Cartesian component of this thermal conductivity tensor.
Definition at line 146 of file ThermalConductivity.hpp.
References PhQ::DimensionalSymmetricDyad< UnitType, NumericType >::value.
Referenced by PhQ::ThermalConductivity< NumericType >::Create().
YAML() [1/2]
template<typename UnitType , typename NumericType = double> std::string PhQ::DimensionalSymmetricDyad< UnitType, NumericType >::YAML () const inline inherited
Serializes this physical quantity as a YAML message. This physical quantity's value is expressed in its standard unit of measure.
Definition at line 143 of file DimensionalSymmetricDyad.hpp.
References PhQ::Abbreviation(), and PhQ::DimensionalSymmetricDyad< UnitType, NumericType >::value.
Referenced by PhQ::DimensionalSymmetricDyad< UnitType, NumericType >::YAML().
YAML() [2/2]
template<typename UnitType , typename NumericType = double> std::string PhQ::DimensionalSymmetricDyad< UnitType, NumericType >::YAML (const UnitType unit) const inline inherited
Serializes this physical quantity as a YAML message. This physical quantity's value is expressed in the given unit of measure.
Definition at line 153 of file DimensionalSymmetricDyad.hpp.
References PhQ::Abbreviation(), PhQ::DimensionalSymmetricDyad< UnitType, NumericType >::Value(), and PhQ::DimensionalSymmetricDyad< UnitType, NumericType >::YAML().
yx()
template<typename NumericType = double> constexpr ScalarThermalConductivity< NumericType > PhQ::ThermalConductivity< NumericType >::yx () const inline constexpr noexcept
Returns the yx = xy Cartesian component of this thermal conductivity tensor.
Definition at line 151 of file ThermalConductivity.hpp.
References PhQ::DimensionalSymmetricDyad< UnitType, NumericType >::value.
yy()
template<typename NumericType = double> constexpr ScalarThermalConductivity< NumericType > PhQ::ThermalConductivity< NumericType >::yy () const inline constexpr noexcept
Returns the yy Cartesian component of this thermal conductivity tensor.
Definition at line 156 of file ThermalConductivity.hpp.
References PhQ::DimensionalSymmetricDyad< UnitType, NumericType >::value.
Referenced by PhQ::ThermalConductivity< NumericType >::Create().
yz()
template<typename NumericType = double> constexpr ScalarThermalConductivity< NumericType > PhQ::ThermalConductivity< NumericType >::yz () const inline constexpr noexcept
Returns the yz = zy Cartesian component of this thermal conductivity tensor.
Definition at line 161 of file ThermalConductivity.hpp.
References PhQ::DimensionalSymmetricDyad< UnitType, NumericType >::value.
Referenced by PhQ::ThermalConductivity< NumericType >::Create().
Zero()
template<typename NumericType = double> static constexpr ThermalConductivity< NumericType > PhQ::ThermalConductivity< NumericType >::Zero () inline static constexpr
Statically creates a thermal conductivity tensor of zero.
Definition at line 100 of file ThermalConductivity.hpp.
References PhQ::SymmetricDyad< NumericType >::Zero().
zx()
template<typename NumericType = double> constexpr ScalarThermalConductivity< NumericType > PhQ::ThermalConductivity< NumericType >::zx () const inline constexpr noexcept
Returns the zx = xz Cartesian component of this thermal conductivity tensor.
Definition at line 166 of file ThermalConductivity.hpp.
References PhQ::DimensionalSymmetricDyad< UnitType, NumericType >::value.
zy()
template<typename NumericType = double> constexpr ScalarThermalConductivity< NumericType > PhQ::ThermalConductivity< NumericType >::zy () const inline constexpr noexcept
Returns the zy = yz Cartesian component of this thermal conductivity tensor.
Definition at line 171 of file ThermalConductivity.hpp.
References PhQ::DimensionalSymmetricDyad< UnitType, NumericType >::value.
zz()
template<typename NumericType = double> constexpr ScalarThermalConductivity< NumericType > PhQ::ThermalConductivity< NumericType >::zz () const inline constexpr noexcept
Returns the zz Cartesian component of this thermal conductivity tensor.
Definition at line 176 of file ThermalConductivity.hpp.
References PhQ::DimensionalSymmetricDyad< UnitType, NumericType >::value.
Referenced by PhQ::ThermalConductivity< NumericType >::Create().
Member Data Documentation
value
template<typename UnitType , typename NumericType = double> PhQ::SymmetricDyad<NumericType> PhQ::DimensionalSymmetricDyad< UnitType, NumericType >::value protected inherited
Value of this physical quantity expressed in its standard unit of measure.
Definition at line 222 of file DimensionalSymmetricDyad.hpp.
Referenced by PhQ::StrainRate< NumericType >::Create(), PhQ::Stress< NumericType >::Create(), PhQ::ThermalConductivity< NumericType >::Create(), PhQ::DimensionalSymmetricDyad< UnitType, NumericType >::JSON(), PhQ::DimensionalSymmetricDyad< UnitType, NumericType >::MutableValue(), PhQ::StrainRate< NumericType >::operator*(), PhQ::Stress< NumericType >::operator*(), PhQ::ThermalConductivity< NumericType >::operator*(), PhQ::StrainRate< NumericType >::operator*=(), PhQ::Stress< NumericType >::operator*=(), PhQ::ThermalConductivity< NumericType >::operator*=(), PhQ::StrainRate< NumericType >::operator+(), PhQ::Stress< NumericType >::operator+(), PhQ::ThermalConductivity< NumericType >::operator+(), PhQ::StrainRate< NumericType >::operator+=(), PhQ::Stress< NumericType >::operator+=(), PhQ::ThermalConductivity< NumericType >::operator+=(), PhQ::StrainRate< NumericType >::operator-(), PhQ::Stress< NumericType >::operator-(), PhQ::ThermalConductivity< NumericType >::operator-(), PhQ::StrainRate< NumericType >::operator-=(), PhQ::Stress< NumericType >::operator-=(), PhQ::ThermalConductivity< NumericType >::operator-=(), PhQ::StrainRate< NumericType >::operator/(), PhQ::Stress< NumericType >::operator/(), PhQ::ThermalConductivity< NumericType >::operator/(), PhQ::StrainRate< NumericType >::operator/=(), PhQ::Stress< NumericType >::operator/=(), PhQ::ThermalConductivity< NumericType >::operator/=(), PhQ::DimensionalSymmetricDyad< UnitType, NumericType >::operator=(), PhQ::StrainRate< NumericType >::operator=(), PhQ::Stress< NumericType >::operator=(), PhQ::ThermalConductivity< NumericType >::operator=(), PhQ::DimensionalSymmetricDyad< UnitType, NumericType >::Print(), PhQ::DimensionalSymmetricDyad< UnitType, NumericType >::SetValue(), PhQ::DimensionalSymmetricDyad< UnitType, NumericType >::StaticValue(), PhQ::DimensionalSymmetricDyad< UnitType, NumericType >::Value(), PhQ::DimensionalSymmetricDyad< UnitType, NumericType >::Value(), PhQ::Stress< NumericType >::VonMises(), PhQ::DimensionalSymmetricDyad< UnitType, NumericType >::XML(), PhQ::StrainRate< NumericType >::xx(), PhQ::Stress< NumericType >::xx(), PhQ::ThermalConductivity< NumericType >::xx(), PhQ::StrainRate< NumericType >::xy(), PhQ::Stress< NumericType >::xy(), PhQ::ThermalConductivity< NumericType >::xy(), PhQ::StrainRate< NumericType >::xz(), PhQ::Stress< NumericType >::xz(), PhQ::ThermalConductivity< NumericType >::xz(), PhQ::DimensionalSymmetricDyad< UnitType, NumericType >::YAML(), PhQ::StrainRate< NumericType >::yx(), PhQ::Stress< NumericType >::yx(), PhQ::ThermalConductivity< NumericType >::yx(), PhQ::StrainRate< NumericType >::yy(), PhQ::Stress< NumericType >::yy(), PhQ::ThermalConductivity< NumericType >::yy(), PhQ::StrainRate< NumericType >::yz(), PhQ::Stress< NumericType >::yz(), PhQ::ThermalConductivity< NumericType >::yz(), PhQ::StrainRate< NumericType >::zx(), PhQ::Stress< NumericType >::zx(), PhQ::ThermalConductivity< NumericType >::zx(), PhQ::StrainRate< NumericType >::zy(), PhQ::Stress< NumericType >::zy(), PhQ::ThermalConductivity< NumericType >::zy(), PhQ::StrainRate< NumericType >::zz(), PhQ::Stress< NumericType >::zz(), and PhQ::ThermalConductivity< NumericType >::zz().
The documentation for this class was generated from the following file:
PhQ/ThermalConductivity.hpp