Physical Quantities: PhQ::Direction< NumericType > Class Template Reference
PhQ::Direction< NumericType > Class Template Reference
Three-dimensional Euclidean direction vector. Contains three components in Cartesian coordinates: x, y, and z. Guaranteed to be either a unit vector or the zero vector (0, 0, 0). For a two-dimensional Euclidean direction vector in the XY plane, see PhQ::PlanarDirection.
#include "Direction.hpp"
Public Member Functions
constexpr Direction ()
Default constructor. Initializes a direction to the zero vector.
Direction (const NumericType x, const NumericType y, const NumericType z)
Constructor. Constructs a direction by normalizing the given x, y, and z Cartesian components to a unit vector. If x = 0, y = 0, and z = 0, initializes the direction to the zero vector.
Direction (const std::array< NumericType, 3 > &x_y_z)
Constructor. Constructs a direction by normalizing a given array representing x, y, and z Cartesian components to a unit vector. If x = 0, y = 0, and z = 0, initializes the direction to the zero vector.
Direction (const Vector< NumericType > &value)
Constructor. Constructs a direction by normalizing the given vector to a unit vector. If the given vector is the zero vector, initializes the direction to the zero vector.
constexpr Direction (const PlanarDirection< NumericType > &planar_direction)
Constructor. Constructs a direction from a given planar direction in the XY plane. This direction's z-component is initialized to zero.
Direction (const Acceleration< NumericType > &acceleration)
Constructor. Constructs a direction from an acceleration.
Direction (const Displacement< NumericType > &displacement)
Constructor. Constructs a direction from a displacement.
Direction (const Force< NumericType > &force)
Constructor. Constructs a direction from a force.
Direction (const HeatFlux< NumericType > &heat_flux)
Constructor. Constructs a direction from a heat flux.
Direction (const Position< NumericType > &position)
Constructor. Constructs a direction from a position.
Direction (const TemperatureGradient< NumericType > &temperature_gradient)
Constructor. Constructs a direction from a temperature gradient.
Direction (const Traction< NumericType > &traction)
Constructor. Constructs a direction from a traction.
Direction (const VectorArea< NumericType > &vector_area)
Constructor. Constructs a direction from a vector area.
Direction (const Velocity< NumericType > &velocity)
Constructor. Constructs a direction from a velocity.
~Direction () noexcept=default
Destructor. Destroys this direction.
constexpr Direction (const Direction< NumericType > &other)=default
Copy constructor. Constructs a direction by copying another one.
template<typename OtherNumericType >
constexpr Direction (const Direction< OtherNumericType > &other)
Copy constructor. Constructs a direction by copying another one.
constexpr Direction (Direction< NumericType > &&other) noexcept=default
Move constructor. Constructs a direction by moving another one.
constexpr Direction< NumericType > & operator= (const Direction< NumericType > &other)=default
Copy assignment operator. Assigns this direction by copying another one.
template<typename OtherNumericType >
constexpr Direction< NumericType > & operator= (const Direction< OtherNumericType > &other)
Copy assignment operator. Assigns this direction by copying another one.
constexpr Direction< NumericType > & operator= (Direction< NumericType > &&other) noexcept=default
Move assignment operator. Assigns the value of this direction by moving another one.
constexpr NumericType x () const noexcept
Returns the x Cartesian component of this direction.
constexpr NumericType y () const noexcept
Returns the y Cartesian component of this direction.
constexpr NumericType z () const noexcept
Returns the z Cartesian component of this direction.
constexpr void Set (const NumericType x, const NumericType y, const NumericType z)
Sets the value of this direction by normalizing the given x, y, and z Cartesian components to a unit vector. If x = 0, y = 0, and z = 0, sets the direction to the zero vector.
constexpr void Set (const std::array< NumericType, 3 > &x_y_z)
Sets the value of this direction by normalizing the given x, y, and z Cartesian components to a unit vector. If x = 0, y = 0, and z = 0, sets the direction to the zero vector.
constexpr void Set (const Vector< NumericType > &value)
Sets the value of this direction by normalizing the given vector to a unit vector. If the given vector is a zero vector, sets the direction to the zero vector.
constexpr NumericType MagnitudeSquared () const noexcept
Returns the square of the magnitude of this direction. This is guaranteed to be exactly 1 if the direction is not the zero vector, or 0 if the direction is the zero vector.
NumericType Magnitude () const noexcept
Returns the magnitude of this direction. This is guaranteed to be exactly 1 if the direction is not the zero vector, or 0 if the direction is the zero vector.
constexpr NumericType Dot (const Vector< NumericType > &vector) const noexcept
Returns the dot product (also known as the scalar product or the inner product) of this direction with the given vector.
constexpr NumericType Dot (const Direction< NumericType > &direction) const noexcept
Returns the dot product (also known as the scalar product or the inner product) of this direction with the given other direction.
constexpr Vector< NumericType > Cross (const Vector< NumericType > &vector) const
Returns the cross product of this direction with the given vector.
Direction< NumericType > Cross (const Direction< NumericType > &direction) const
Returns the cross product of this direction with the given other direction.
constexpr Dyad< NumericType > Dyadic (const Vector< NumericType > &vector) const
Returns the dyadic product of this direction with the given vector.
constexpr Dyad< NumericType > Dyadic (const Direction< NumericType > &direction) const
Returns the dyadic product of this direction with the given other direction.
PhQ::Angle< NumericType > Angle (const Vector< NumericType > &vector) const
Returns the angle between this direction and the given vector.
PhQ::Angle< NumericType > Angle (const Direction< NumericType > &direction) const
Returns the angle between this direction and the given other direction.
constexpr Acceleration< NumericType > operator* (const ScalarAcceleration< NumericType > &scalar_acceleration) const
constexpr VectorArea< NumericType > operator* (const Area< NumericType > &area) const
constexpr Position< NumericType > operator* (const Length< NumericType > &length) const
constexpr Force< NumericType > operator* (const ScalarForce< NumericType > &scalar_force) const
constexpr HeatFlux< NumericType > operator* (const ScalarHeatFlux< NumericType > &scalar_heat_flux) const
constexpr TemperatureGradient< NumericType > operator* (const ScalarTemperatureGradient< NumericType > &scalar_temperature_gradient) const
constexpr Traction< NumericType > operator* (const ScalarTraction< NumericType > &scalar_traction) const
constexpr Velocity< NumericType > operator* (const Speed< NumericType > &speed) const
constexpr const PhQ::Vector< NumericType > & Value () const noexcept
Value of this physical quantity.
std::string Print () const
Prints this physical quantity as a string.
std::string JSON () const
Serializes this physical quantity as a JSON message.
std::string XML () const
Serializes this physical quantity as an XML message.
std::string YAML () const
Serializes this physical quantity as a YAML message.
Static Public Member Functions
static constexpr Direction< NumericType > Zero ()
Statically creates a direction whose value is the zero vector.
static constexpr PhQ::Dimensions Dimensions ()
Physical dimension set of this physical quantity. Since this physical quantity is dimensionless, its physical dimension set is simply the null set.
Protected Attributes
PhQ::Vector< NumericType > value
Value of this physical quantity.
Detailed Description
template<typename NumericType = double>
class PhQ::Direction< NumericType >
Three-dimensional Euclidean direction vector. Contains three components in Cartesian coordinates: x, y, and z. Guaranteed to be either a unit vector or the zero vector (0, 0, 0). For a two-dimensional Euclidean direction vector in the XY plane, see PhQ::PlanarDirection.
Definition at line 115 of file Direction.hpp.
Constructor & Destructor Documentation
Direction() [1/17]
template<typename NumericType = double> constexpr PhQ::Direction< NumericType >::Direction () inline constexpr
Default constructor. Initializes a direction to the zero vector.
Definition at line 118 of file Direction.hpp.
Direction() [2/17]
template<typename NumericType = double> PhQ::Direction< NumericType >::Direction (const NumericType x, const NumericType y, const NumericType z) inline
Constructor. Constructs a direction by normalizing the given x, y, and z Cartesian components to a unit vector. If x = 0, y = 0, and z = 0, initializes the direction to the zero vector.
Definition at line 123 of file Direction.hpp.
References PhQ::Direction< NumericType >::Set(), PhQ::Direction< NumericType >::x(), PhQ::Direction< NumericType >::y(), and PhQ::Direction< NumericType >::z().
Direction() [3/17]
template<typename NumericType = double> PhQ::Direction< NumericType >::Direction (const std::array< NumericType, 3 > & x_y_z) inline explicit
Constructor. Constructs a direction by normalizing a given array representing x, y, and z Cartesian components to a unit vector. If x = 0, y = 0, and z = 0, initializes the direction to the zero vector.
Definition at line 131 of file Direction.hpp.
References PhQ::Direction< NumericType >::Set().
Direction() [4/17]
template<typename NumericType = double> PhQ::Direction< NumericType >::Direction (const Vector< NumericType > & value) inline explicit
Constructor. Constructs a direction by normalizing the given vector to a unit vector. If the given vector is the zero vector, initializes the direction to the zero vector.
Definition at line 137 of file Direction.hpp.
References PhQ::Direction< NumericType >::Set(), and PhQ::DimensionlessVector< NumericType >::value.
Direction() [5/17]
template<typename NumericType = double> constexpr PhQ::Direction< NumericType >::Direction (const PlanarDirection< NumericType > & planar_direction) inline explicit constexpr
Constructor. Constructs a direction from a given planar direction in the XY plane. This direction's z-component is initialized to zero.
Definition at line 143 of file Direction.hpp.
References PhQ::DimensionlessPlanarVector< NumericType >::Value().
Direction() [6/17]
template<typename NumericType > PhQ::Direction< NumericType >::Direction (const Acceleration< NumericType > & acceleration) inline explicit
Constructor. Constructs a direction from an acceleration.
Definition at line 278 of file Acceleration.hpp.
Direction() [7/17]
template<typename NumericType > PhQ::Direction< NumericType >::Direction (const Displacement< NumericType > & displacement) inline explicit
Constructor. Constructs a direction from a displacement.
Definition at line 294 of file Displacement.hpp.
Direction() [8/17]
template<typename NumericType > PhQ::Direction< NumericType >::Direction (const Force< NumericType > & force) inline explicit
Constructor. Constructs a direction from a force.
Definition at line 258 of file Force.hpp.
Direction() [9/17]
template<typename NumericType > PhQ::Direction< NumericType >::Direction (const HeatFlux< NumericType > & heat_flux) inline explicit
Constructor. Constructs a direction from a heat flux.
Definition at line 271 of file HeatFlux.hpp.
Direction() [10/17]
template<typename NumericType > PhQ::Direction< NumericType >::Direction (const Position< NumericType > & position) inline explicit
Constructor. Constructs a direction from a position.
Definition at line 273 of file Position.hpp.
Direction() [11/17]
template<typename NumericType > PhQ::Direction< NumericType >::Direction (const TemperatureGradient< NumericType > & temperature_gradient) inline explicit
Constructor. Constructs a direction from a temperature gradient.
Definition at line 270 of file TemperatureGradient.hpp.
Direction() [12/17]
template<typename NumericType > PhQ::Direction< NumericType >::Direction (const Traction< NumericType > & traction) inline explicit
Constructor. Constructs a direction from a traction.
Definition at line 269 of file Traction.hpp.
Direction() [13/17]
template<typename NumericType > PhQ::Direction< NumericType >::Direction (const VectorArea< NumericType > & vector_area) inline explicit
Constructor. Constructs a direction from a vector area.
Definition at line 241 of file VectorArea.hpp.
Direction() [14/17]
template<typename NumericType > PhQ::Direction< NumericType >::Direction (const Velocity< NumericType > & velocity) inline explicit
Constructor. Constructs a direction from a velocity.
Definition at line 286 of file Velocity.hpp.
~Direction()
template<typename NumericType = double> PhQ::Direction< NumericType >::~Direction () default noexcept
Destructor. Destroys this direction.
Direction() [15/17]
template<typename NumericType = double> constexpr PhQ::Direction< NumericType >::Direction (const Direction< NumericType > & other) constexpr default
Copy constructor. Constructs a direction by copying another one.
Direction() [16/17]
template<typename NumericType = double> template<typename OtherNumericType > constexpr PhQ::Direction< NumericType >::Direction (const Direction< OtherNumericType > & other) inline explicit constexpr
Copy constructor. Constructs a direction by copying another one.
Definition at line 181 of file Direction.hpp.
Direction() [17/17]
template<typename NumericType = double> constexpr PhQ::Direction< NumericType >::Direction (Direction< NumericType > && other) constexpr default noexcept
Move constructor. Constructs a direction by moving another one.
Member Function Documentation
Angle() [1/2]
template<typename NumericType = double> PhQ::Angle< NumericType > PhQ::Direction< NumericType >::Angle (const Direction< NumericType > & direction) const inline
Returns the angle between this direction and the given other direction.
Definition at line 303 of file Direction.hpp.
Angle() [2/2]
template<typename NumericType = double> PhQ::Angle< NumericType > PhQ::Direction< NumericType >::Angle (const Vector< NumericType > & vector) const inline
Returns the angle between this direction and the given vector.
Definition at line 298 of file Direction.hpp.
Cross() [1/2]
template<typename NumericType = double> Direction< NumericType > PhQ::Direction< NumericType >::Cross (const Direction< NumericType > & direction) const inline
Returns the cross product of this direction with the given other direction.
Definition at line 283 of file Direction.hpp.
References PhQ::Direction< NumericType >::Cross(), and PhQ::DimensionlessVector< NumericType >::value.
Cross() [2/2]
template<typename NumericType = double> constexpr Vector< NumericType > PhQ::Direction< NumericType >::Cross (const Vector< NumericType > & vector) const inline constexpr
Returns the cross product of this direction with the given vector.
Definition at line 278 of file Direction.hpp.
References PhQ::DimensionlessVector< NumericType >::value.
Referenced by PhQ::Direction< NumericType >::Cross(), and PhQ::PlanarDirection< NumericType >::Cross().
Dimensions()
template<typename NumericType = double> static constexpr PhQ::Dimensions PhQ::DimensionlessVector< NumericType >::Dimensions () inline static constexpr inherited
Physical dimension set of this physical quantity. Since this physical quantity is dimensionless, its physical dimension set is simply the null set.
Definition at line 55 of file DimensionlessVector.hpp.
References PhQ::Dimensionless.
Dot() [1/2]
template<typename NumericType = double> constexpr NumericType PhQ::Direction< NumericType >::Dot (const Direction< NumericType > & direction) const inline constexpr noexcept
Returns the dot product (also known as the scalar product or the inner product) of this direction with the given other direction.
Definition at line 273 of file Direction.hpp.
References PhQ::DimensionlessVector< NumericType >::value.
Dot() [2/2]
template<typename NumericType = double> constexpr NumericType PhQ::Direction< NumericType >::Dot (const Vector< NumericType > & vector) const inline constexpr noexcept
Returns the dot product (also known as the scalar product or the inner product) of this direction with the given vector.
Definition at line 267 of file Direction.hpp.
References PhQ::DimensionlessVector< NumericType >::value.
Dyadic() [1/2]
template<typename NumericType = double> constexpr Dyad< NumericType > PhQ::Direction< NumericType >::Dyadic (const Direction< NumericType > & direction) const inline constexpr
Returns the dyadic product of this direction with the given other direction.
Definition at line 293 of file Direction.hpp.
References PhQ::DimensionlessVector< NumericType >::value.
Dyadic() [2/2]
template<typename NumericType = double> constexpr Dyad< NumericType > PhQ::Direction< NumericType >::Dyadic (const Vector< NumericType > & vector) const inline constexpr
Returns the dyadic product of this direction with the given vector.
Definition at line 288 of file Direction.hpp.
References PhQ::DimensionlessVector< NumericType >::value.
JSON()
template<typename NumericType = double> std::string PhQ::DimensionlessVector< NumericType >::JSON () const inline inherited
Serializes this physical quantity as a JSON message.
Definition at line 70 of file DimensionlessVector.hpp.
References PhQ::DimensionlessVector< NumericType >::value.
Magnitude()
template<typename NumericType = double> NumericType PhQ::Direction< NumericType >::Magnitude () const inline noexcept
Returns the magnitude of this direction. This is guaranteed to be exactly 1 if the direction is not the zero vector, or 0 if the direction is the zero vector.
Definition at line 261 of file Direction.hpp.
References PhQ::DimensionlessVector< NumericType >::value.
MagnitudeSquared()
template<typename NumericType = double> constexpr NumericType PhQ::Direction< NumericType >::MagnitudeSquared () const inline constexpr noexcept
Returns the square of the magnitude of this direction. This is guaranteed to be exactly 1 if the direction is not the zero vector, or 0 if the direction is the zero vector.
Definition at line 255 of file Direction.hpp.
References PhQ::DimensionlessVector< NumericType >::value.
operator*() [1/8]
template<typename NumericType > constexpr VectorArea< NumericType > PhQ::Direction< NumericType >::operator* (const Area< NumericType > & area) const inline constexpr
Definition at line 250 of file VectorArea.hpp.
operator*() [2/8]
template<typename NumericType > constexpr Position< NumericType > PhQ::Direction< NumericType >::operator* (const Length< NumericType > & length) const inline constexpr
Definition at line 298 of file Position.hpp.
operator*() [3/8]
template<typename NumericType > constexpr Acceleration< NumericType > PhQ::Direction< NumericType >::operator* (const ScalarAcceleration< NumericType > & scalar_acceleration) const inline constexpr
Definition at line 302 of file Acceleration.hpp.
operator*() [4/8]
template<typename NumericType > constexpr Force< NumericType > PhQ::Direction< NumericType >::operator* (const ScalarForce< NumericType > & scalar_force) const inline constexpr
Definition at line 266 of file Force.hpp.
operator*() [5/8]
template<typename NumericType > constexpr HeatFlux< NumericType > PhQ::Direction< NumericType >::operator* (const ScalarHeatFlux< NumericType > & scalar_heat_flux) const inline constexpr
Definition at line 280 of file HeatFlux.hpp.
operator*() [6/8]
template<typename NumericType > constexpr TemperatureGradient< NumericType > PhQ::Direction< NumericType >::operator* (const ScalarTemperatureGradient< NumericType > & scalar_temperature_gradient) const inline constexpr
Definition at line 280 of file TemperatureGradient.hpp.
operator*() [7/8]
template<typename NumericType > constexpr Traction< NumericType > PhQ::Direction< NumericType >::operator* (const ScalarTraction< NumericType > & scalar_traction) const inline constexpr
Definition at line 283 of file Traction.hpp.
operator*() [8/8]
template<typename NumericType > constexpr Velocity< NumericType > PhQ::Direction< NumericType >::operator* (const Speed< NumericType > & speed) const inline constexpr
Definition at line 309 of file Velocity.hpp.
operator=() [1/3]
template<typename NumericType = double> constexpr Direction< NumericType > & PhQ::Direction< NumericType >::operator= (const Direction< NumericType > & other) constexpr default
Copy assignment operator. Assigns this direction by copying another one.
operator=() [2/3]
template<typename NumericType = double> template<typename OtherNumericType > constexpr Direction< NumericType > & PhQ::Direction< NumericType >::operator= (const Direction< OtherNumericType > & other) inline constexpr
Copy assignment operator. Assigns this direction by copying another one.
Definition at line 192 of file Direction.hpp.
References PhQ::DimensionlessVector< NumericType >::Value(), and PhQ::DimensionlessVector< NumericType >::value.
operator=() [3/3]
template<typename NumericType = double> constexpr Direction< NumericType > & PhQ::Direction< NumericType >::operator= (Direction< NumericType > && other) constexpr default noexcept
Move assignment operator. Assigns the value of this direction by moving another one.
Print()
template<typename NumericType = double> std::string PhQ::DimensionlessVector< NumericType >::Print () const inline inherited
Prints this physical quantity as a string.
Definition at line 65 of file DimensionlessVector.hpp.
References PhQ::DimensionlessVector< NumericType >::value.
Referenced by PhQ::operator<<().
Set() [1/3]
template<typename NumericType = double> constexpr void PhQ::Direction< NumericType >::Set (const NumericType x, const NumericType y, const NumericType z) inline constexpr
Sets the value of this direction by normalizing the given x, y, and z Cartesian components to a unit vector. If x = 0, y = 0, and z = 0, sets the direction to the zero vector.
Definition at line 223 of file Direction.hpp.
Referenced by PhQ::Direction< NumericType >::Direction(), PhQ::Direction< NumericType >::Direction(), PhQ::Direction< NumericType >::Direction(), and PhQ::Direction< NumericType >::Set().
Set() [2/3]
template<typename NumericType = double> constexpr void PhQ::Direction< NumericType >::Set (const std::array< NumericType, 3 > & x_y_z) inline constexpr
Sets the value of this direction by normalizing the given x, y, and z Cartesian components to a unit vector. If x = 0, y = 0, and z = 0, sets the direction to the zero vector.
Definition at line 236 of file Direction.hpp.
Set() [3/3]
template<typename NumericType = double> constexpr void PhQ::Direction< NumericType >::Set (const Vector< NumericType > & value) inline constexpr
Sets the value of this direction by normalizing the given vector to a unit vector. If the given vector is a zero vector, sets the direction to the zero vector.
Definition at line 249 of file Direction.hpp.
References PhQ::Direction< NumericType >::Set(), and PhQ::DimensionlessVector< NumericType >::value.
Value()
template<typename NumericType = double> constexpr const PhQ::Vector< NumericType > & PhQ::DimensionlessVector< NumericType >::Value () const inline constexpr noexcept inherited
Value of this physical quantity.
Definition at line 60 of file DimensionlessVector.hpp.
References PhQ::DimensionlessVector< NumericType >::value.
Referenced by PhQ::Vector< NumericType >::Cross(), PhQ::Vector< NumericType >::Dyadic(), PhQ::operator*(), PhQ::operator*(), PhQ::DimensionlessVector< NumericType >::operator=(), PhQ::Direction< NumericType >::operator=(), PhQ::PlanarDirection< NumericType >::PlanarDirection(), and PhQ::Vector< NumericType >::Vector().
x()
template<typename NumericType = double> constexpr NumericType PhQ::Direction< NumericType >::x () const inline constexpr noexcept
Returns the x Cartesian component of this direction.
Definition at line 206 of file Direction.hpp.
References PhQ::DimensionlessVector< NumericType >::value.
Referenced by PhQ::Direction< NumericType >::Direction(), and PhQ::Vector< double >::Dot().
XML()
template<typename NumericType = double> std::string PhQ::DimensionlessVector< NumericType >::XML () const inline inherited
Serializes this physical quantity as an XML message.
Definition at line 75 of file DimensionlessVector.hpp.
References PhQ::DimensionlessVector< NumericType >::value.
y()
template<typename NumericType = double> constexpr NumericType PhQ::Direction< NumericType >::y () const inline constexpr noexcept
Returns the y Cartesian component of this direction.
Definition at line 211 of file Direction.hpp.
References PhQ::DimensionlessVector< NumericType >::value.
Referenced by PhQ::Direction< NumericType >::Direction(), and PhQ::Vector< double >::Dot().
YAML()
template<typename NumericType = double> std::string PhQ::DimensionlessVector< NumericType >::YAML () const inline inherited
Serializes this physical quantity as a YAML message.
Definition at line 80 of file DimensionlessVector.hpp.
References PhQ::DimensionlessVector< NumericType >::value.
z()
template<typename NumericType = double> constexpr NumericType PhQ::Direction< NumericType >::z () const inline constexpr noexcept
Returns the z Cartesian component of this direction.
Definition at line 216 of file Direction.hpp.
References PhQ::DimensionlessVector< NumericType >::value.
Referenced by PhQ::Direction< NumericType >::Direction(), and PhQ::Vector< double >::Dot().
Zero()
template<typename NumericType = double> static constexpr Direction< NumericType > PhQ::Direction< NumericType >::Zero () inline static constexpr
Statically creates a direction whose value is the zero vector.
Definition at line 201 of file Direction.hpp.
Member Data Documentation
value
template<typename NumericType = double> PhQ::Vector<NumericType> PhQ::DimensionlessVector< NumericType >::value protected inherited
Value of this physical quantity.
Definition at line 142 of file DimensionlessVector.hpp.
Referenced by PhQ::Direction< NumericType >::Cross(), PhQ::Direction< NumericType >::Cross(), PhQ::Direction< NumericType >::Direction(), PhQ::Direction< NumericType >::Dot(), PhQ::Direction< NumericType >::Dot(), PhQ::Direction< NumericType >::Dyadic(), PhQ::Direction< NumericType >::Dyadic(), PhQ::DimensionlessVector< NumericType >::JSON(), PhQ::Direction< NumericType >::Magnitude(), PhQ::Direction< NumericType >::MagnitudeSquared(), PhQ::DimensionlessVector< NumericType >::operator=(), PhQ::Direction< NumericType >::operator=(), PhQ::DimensionlessVector< NumericType >::Print(), PhQ::Direction< NumericType >::Set(), PhQ::DimensionlessVector< NumericType >::Value(), PhQ::Direction< NumericType >::x(), PhQ::DimensionlessVector< NumericType >::XML(), PhQ::Direction< NumericType >::y(), PhQ::DimensionlessVector< NumericType >::YAML(), and PhQ::Direction< NumericType >::z().
The documentation for this class was generated from the following files:
PhQ/Angle.hpp
PhQ/Direction.hpp
PhQ/Acceleration.hpp
PhQ/Displacement.hpp
PhQ/Force.hpp
PhQ/HeatFlux.hpp
PhQ/Position.hpp
PhQ/TemperatureGradient.hpp
PhQ/Traction.hpp
PhQ/VectorArea.hpp
PhQ/Velocity.hpp