Physical Quantities: PhQ::HeatFlux< NumericType > Class Template Reference
PhQ::HeatFlux< NumericType > Class Template Reference
Three-dimensional Euclidean heat flux vector. Contains three components in Cartesian coordinates: x, y, and z. For a two-dimensional Euclidean heat flux vector in the XY plane, see PhQ::PlanarHeatFlux. For scalar heat flux components or for the magnitude of a heat flux vector, see PhQ::ScalarHeatFlux.
#include "HeatFlux.hpp"
Public Member Functions
HeatFlux ()=default
Default constructor. Constructs a heat flux vector with an uninitialized value.
HeatFlux (const Vector< NumericType > &value, const Unit::EnergyFlux unit)
Constructor. Constructs a heat flux vector with a given value expressed in a given energy flux unit.
HeatFlux (const ScalarHeatFlux< NumericType > &x, const ScalarHeatFlux< NumericType > &y, const ScalarHeatFlux< NumericType > &z)
Constructor. Constructs a heat flux vector from a given set of scalar heat flux components.
constexpr HeatFlux (const ScalarHeatFlux< NumericType > &scalar_heat_flux, const Direction< NumericType > &direction)
Constructor. Constructs a heat flux vector from a given scalar heat flux magnitude and direction.
constexpr HeatFlux (const PlanarHeatFlux< NumericType > &planar_heat_flux)
Constructor. Constructs a heat flux vector from a given planar heat flux vector in the XY plane. This heat flux vector's z-component is initialized to zero.
constexpr HeatFlux (const ScalarThermalConductivity< NumericType > &scalar_thermal_conductivity, const TemperatureGradient< NumericType > &temperature_gradient)
Constructor. Constructs a heat flux vector from a given scalar thermal conductivity and temperature gradient vector using Fourier's law of heat conduction. Since heat flows opposite the temperature gradient, the resulting heat flux direction is opposite the temperature gradient direction.
constexpr HeatFlux (const ThermalConductivity< NumericType > &thermal_conductivity, const TemperatureGradient< NumericType > &temperature_gradient)
Constructor. Constructs a heat flux vector from a given thermal conductivity tensor and temperature gradient vector using Fourier's law of heat conduction. Since heat flows opposite the temperature gradient, the resulting heat flux direction is opposite the temperature gradient direction.
~HeatFlux () noexcept=default
Destructor. Destroys this heat flux vector.
constexpr HeatFlux (const HeatFlux< NumericType > &other)=default
Copy constructor. Constructs a heat flux vector by copying another one.
template<typename OtherNumericType >
constexpr HeatFlux (const HeatFlux< OtherNumericType > &other)
Copy constructor. Constructs a heat flux vector by copying another one.
constexpr HeatFlux (HeatFlux< NumericType > &&other) noexcept=default
Move constructor. Constructs a heat flux vector by moving another one.
constexpr HeatFlux< NumericType > & operator= (const HeatFlux< NumericType > &other)=default
Copy assignment operator. Assigns this heat flux vector by copying another one.
template<typename OtherNumericType >
constexpr HeatFlux< NumericType > & operator= (const HeatFlux< OtherNumericType > &other)
Copy assignment operator. Assigns this heat flux vector by copying another one.
constexpr HeatFlux< NumericType > & operator= (HeatFlux< NumericType > &&other) noexcept=default
Move assignment operator. Assigns this heat flux vector by moving another one.
constexpr ScalarHeatFlux< NumericType > x () const noexcept
Returns the x Cartesian component of this heat flux vector.
constexpr ScalarHeatFlux< NumericType > y () const noexcept
Returns the y Cartesian component of this heat flux vector.
constexpr ScalarHeatFlux< NumericType > z () const noexcept
Returns the z Cartesian component of this heat flux vector.
ScalarHeatFlux< NumericType > Magnitude () const
Returns the magnitude of this heat flux vector.
PhQ::Direction< NumericType > Direction () const
Returns the direction of this heat flux vector.
PhQ::Angle< NumericType > Angle (const HeatFlux< NumericType > &heat_flux) const
Returns the angle between this heat flux vector and another one.
constexpr HeatFlux< NumericType > operator+ (const HeatFlux< NumericType > &heat_flux) const
constexpr HeatFlux< NumericType > operator- (const HeatFlux< NumericType > &heat_flux) const
constexpr HeatFlux< NumericType > operator* (const NumericType number) const
constexpr HeatFlux< NumericType > operator/ (const NumericType number) const
constexpr void operator+= (const HeatFlux< NumericType > &heat_flux) noexcept
constexpr void operator-= (const HeatFlux< NumericType > &heat_flux) noexcept
constexpr void operator*= (const NumericType number) noexcept
constexpr void operator/= (const NumericType number) noexcept
constexpr const PhQ::Vector< NumericType > & Value () const noexcept
Value of this physical quantity expressed in its standard unit of measure.
PhQ::Vector< NumericType > Value (const UnitType unit) const
Value of this physical quantity expressed in a given unit of measure.
template<UnitType NewUnit>
constexpr PhQ::Vector< NumericType > StaticValue () const
Value of this physical quantity expressed in a given unit of measure. This method can be evaluated statically at compile-time.
constexpr PhQ::Vector< NumericType > & MutableValue () noexcept
Returns the value of this physical quantity expressed in its standard unit of measure as a mutable value.
constexpr void SetValue (const PhQ::Vector< NumericType > &value) noexcept
Sets the value of this physical quantity expressed in its standard unit of measure to the given value.
std::string Print () const
Prints this physical quantity as a string. This physical quantity's value is expressed in its standard unit of measure.
std::string Print (const UnitType unit) const
Prints this physical quantity as a string. This physical quantity's value is expressed in the given unit of measure.
std::string JSON () const
Serializes this physical quantity as a JSON message. This physical quantity's value is expressed in its standard unit of measure.
std::string JSON (const UnitType unit) const
Serializes this physical quantity as a JSON message. This physical quantity's value is expressed in the given unit of measure.
std::string XML () const
Serializes this physical quantity as an XML message. This physical quantity's value is expressed in its standard unit of measure.
std::string XML (const UnitType unit) const
Serializes this physical quantity as an XML message. This physical quantity's value is expressed in the given unit of measure.
std::string YAML () const
Serializes this physical quantity as a YAML message. This physical quantity's value is expressed in its standard unit of measure.
std::string YAML (const UnitType unit) const
Serializes this physical quantity as a YAML message. This physical quantity's value is expressed in the given unit of measure.
Static Public Member Functions
static constexpr HeatFlux< NumericType > Zero ()
Statically creates a heat flux vector of zero.
template<Unit::EnergyFlux Unit>
static constexpr HeatFlux< NumericType > Create (const NumericType x, const NumericType y, const NumericType z)
Statically creates a heat flux vector from the given x, y, and z Cartesian components expressed in a given energy flux unit.
template<Unit::EnergyFlux Unit>
static constexpr HeatFlux< NumericType > Create (const std::array< NumericType, 3 > &x_y_z)
Statically creates a heat flux vector from the given x, y, and z Cartesian components expressed in a given energy flux unit.
template<Unit::EnergyFlux Unit>
static constexpr HeatFlux< NumericType > Create (const Vector< NumericType > &value)
Statically creates a heat flux vector with a given value expressed in a given energy flux unit.
static constexpr const PhQ::Dimensions & Dimensions ()
Physical dimension set of this physical quantity.
static constexpr UnitType Unit ()
Standard unit of measure for this physical quantity. This physical quantity's value is stored internally in this unit of measure.
Protected Attributes
PhQ::Vector< NumericType > value
Value of this physical quantity expressed in its standard unit of measure.
Private Member Functions
constexpr HeatFlux (const Vector< NumericType > &value)
Constructor. Constructs a heat flux vector with a given value expressed in the standard energy flux unit.
Detailed Description
template<typename NumericType = double>
class PhQ::HeatFlux< NumericType >
Three-dimensional Euclidean heat flux vector. Contains three components in Cartesian coordinates: x, y, and z. For a two-dimensional Euclidean heat flux vector in the XY plane, see PhQ::PlanarHeatFlux. For scalar heat flux components or for the magnitude of a heat flux vector, see PhQ::ScalarHeatFlux.
Definition at line 50 of file HeatFlux.hpp.
Constructor & Destructor Documentation
HeatFlux() [1/11]
template<typename NumericType = double> PhQ::HeatFlux< NumericType >::HeatFlux () default
Default constructor. Constructs a heat flux vector with an uninitialized value.
HeatFlux() [2/11]
template<typename NumericType = double> PhQ::HeatFlux< NumericType >::HeatFlux (const Vector< NumericType > & value, const Unit::EnergyFlux unit) inline
Constructor. Constructs a heat flux vector with a given value expressed in a given energy flux unit.
Definition at line 57 of file HeatFlux.hpp.
HeatFlux() [3/11]
template<typename NumericType = double> PhQ::HeatFlux< NumericType >::HeatFlux (const ScalarHeatFlux< NumericType > & x, const ScalarHeatFlux< NumericType > & y, const ScalarHeatFlux< NumericType > & z) inline
Constructor. Constructs a heat flux vector from a given set of scalar heat flux components.
Definition at line 62 of file HeatFlux.hpp.
References PhQ::HeatFlux< NumericType >::x(), PhQ::HeatFlux< NumericType >::y(), and PhQ::HeatFlux< NumericType >::z().
HeatFlux() [4/11]
template<typename NumericType = double> constexpr PhQ::HeatFlux< NumericType >::HeatFlux (const ScalarHeatFlux< NumericType > & scalar_heat_flux, const Direction< NumericType > & direction) inline constexpr
Constructor. Constructs a heat flux vector from a given scalar heat flux magnitude and direction.
Definition at line 68 of file HeatFlux.hpp.
HeatFlux() [5/11]
template<typename NumericType = double> constexpr PhQ::HeatFlux< NumericType >::HeatFlux (const PlanarHeatFlux< NumericType > & planar_heat_flux) inline explicit constexpr
Constructor. Constructs a heat flux vector from a given planar heat flux vector in the XY plane. This heat flux vector's z-component is initialized to zero.
Definition at line 74 of file HeatFlux.hpp.
References PhQ::DimensionalPlanarVector< UnitType, NumericType >::Value().
HeatFlux() [6/11]
template<typename NumericType = double> constexpr PhQ::HeatFlux< NumericType >::HeatFlux (const ScalarThermalConductivity< NumericType > & scalar_thermal_conductivity, const TemperatureGradient< NumericType > & temperature_gradient) inline constexpr
Constructor. Constructs a heat flux vector from a given scalar thermal conductivity and temperature gradient vector using Fourier's law of heat conduction. Since heat flows opposite the temperature gradient, the resulting heat flux direction is opposite the temperature gradient direction.
Definition at line 81 of file HeatFlux.hpp.
HeatFlux() [7/11]
template<typename NumericType = double> constexpr PhQ::HeatFlux< NumericType >::HeatFlux (const ThermalConductivity< NumericType > & thermal_conductivity, const TemperatureGradient< NumericType > & temperature_gradient) inline constexpr
Constructor. Constructs a heat flux vector from a given thermal conductivity tensor and temperature gradient vector using Fourier's law of heat conduction. Since heat flows opposite the temperature gradient, the resulting heat flux direction is opposite the temperature gradient direction.
Definition at line 89 of file HeatFlux.hpp.
~HeatFlux()
template<typename NumericType = double> PhQ::HeatFlux< NumericType >::~HeatFlux () default noexcept
Destructor. Destroys this heat flux vector.
HeatFlux() [8/11]
template<typename NumericType = double> constexpr PhQ::HeatFlux< NumericType >::HeatFlux (const HeatFlux< NumericType > & other) constexpr default
Copy constructor. Constructs a heat flux vector by copying another one.
HeatFlux() [9/11]
template<typename NumericType = double> template<typename OtherNumericType > constexpr PhQ::HeatFlux< NumericType >::HeatFlux (const HeatFlux< OtherNumericType > & other) inline explicit constexpr
Copy constructor. Constructs a heat flux vector by copying another one.
Definition at line 101 of file HeatFlux.hpp.
HeatFlux() [10/11]
template<typename NumericType = double> constexpr PhQ::HeatFlux< NumericType >::HeatFlux (HeatFlux< NumericType > && other) constexpr default noexcept
Move constructor. Constructs a heat flux vector by moving another one.
HeatFlux() [11/11]
template<typename NumericType = double> constexpr PhQ::HeatFlux< NumericType >::HeatFlux (const Vector< NumericType > & value) inline explicit constexpr private
Constructor. Constructs a heat flux vector with a given value expressed in the standard energy flux unit.
Definition at line 218 of file HeatFlux.hpp.
Member Function Documentation
Angle()
template<typename NumericType = double> PhQ::Angle< NumericType > PhQ::HeatFlux< NumericType >::Angle (const HeatFlux< NumericType > & heat_flux) const inline
Returns the angle between this heat flux vector and another one.
Definition at line 179 of file HeatFlux.hpp.
Create() [1/3]
template<typename NumericType = double> template<Unit::EnergyFlux Unit> static constexpr HeatFlux< NumericType > PhQ::HeatFlux< NumericType >::Create (const NumericType x, const NumericType y, const NumericType z) inline static constexpr
Statically creates a heat flux vector from the given x, y, and z Cartesian components expressed in a given energy flux unit.
Definition at line 128 of file HeatFlux.hpp.
References PhQ::HeatFlux< NumericType >::x(), PhQ::HeatFlux< NumericType >::y(), and PhQ::HeatFlux< NumericType >::z().
Create() [2/3]
template<typename NumericType = double> template<Unit::EnergyFlux Unit> static constexpr HeatFlux< NumericType > PhQ::HeatFlux< NumericType >::Create (const std::array< NumericType, 3 > & x_y_z) inline static constexpr
Statically creates a heat flux vector from the given x, y, and z Cartesian components expressed in a given energy flux unit.
Definition at line 138 of file HeatFlux.hpp.
Create() [3/3]
template<typename NumericType = double> template<Unit::EnergyFlux Unit> static constexpr HeatFlux< NumericType > PhQ::HeatFlux< NumericType >::Create (const Vector< NumericType > & value) inline static constexpr
Statically creates a heat flux vector with a given value expressed in a given energy flux unit.
Definition at line 148 of file HeatFlux.hpp.
References PhQ::DimensionalVector< UnitType, NumericType >::value.
Dimensions()
template<typename UnitType , typename NumericType = double> static constexpr const PhQ::Dimensions & PhQ::DimensionalVector< UnitType, NumericType >::Dimensions () inline static constexpr inherited
Physical dimension set of this physical quantity.
Definition at line 50 of file DimensionalVector.hpp.
Direction()
template<typename NumericType = double> PhQ::Direction< NumericType > PhQ::HeatFlux< NumericType >::Direction () const inline
Returns the direction of this heat flux vector.
Definition at line 174 of file HeatFlux.hpp.
References PhQ::DimensionalVector< UnitType, NumericType >::value.
JSON() [1/2]
template<typename UnitType , typename NumericType = double> std::string PhQ::DimensionalVector< UnitType, NumericType >::JSON () const inline inherited
Serializes this physical quantity as a JSON message. This physical quantity's value is expressed in its standard unit of measure.
Definition at line 103 of file DimensionalVector.hpp.
References PhQ::Abbreviation(), and PhQ::DimensionalVector< UnitType, NumericType >::value.
Referenced by PhQ::DimensionalVector< UnitType, NumericType >::JSON().
JSON() [2/2]
template<typename UnitType , typename NumericType = double> std::string PhQ::DimensionalVector< UnitType, NumericType >::JSON (const UnitType unit) const inline inherited
Serializes this physical quantity as a JSON message. This physical quantity's value is expressed in the given unit of measure.
Definition at line 113 of file DimensionalVector.hpp.
References PhQ::Abbreviation(), PhQ::DimensionalVector< UnitType, NumericType >::JSON(), and PhQ::DimensionalVector< UnitType, NumericType >::Value().
Magnitude()
template<typename NumericType = double> ScalarHeatFlux< NumericType > PhQ::HeatFlux< NumericType >::Magnitude () const inline
Returns the magnitude of this heat flux vector.
Definition at line 169 of file HeatFlux.hpp.
References PhQ::DimensionalVector< UnitType, NumericType >::value.
MutableValue()
template<typename UnitType , typename NumericType = double> constexpr PhQ::Vector< NumericType > & PhQ::DimensionalVector< UnitType, NumericType >::MutableValue () inline constexpr noexcept inherited
Returns the value of this physical quantity expressed in its standard unit of measure as a mutable value.
Definition at line 79 of file DimensionalVector.hpp.
References PhQ::DimensionalVector< UnitType, NumericType >::value.
operator*()
template<typename NumericType = double> constexpr HeatFlux< NumericType > PhQ::HeatFlux< NumericType >::operator* (const NumericType number) const inline constexpr
Definition at line 191 of file HeatFlux.hpp.
References PhQ::DimensionalVector< UnitType, NumericType >::value.
operator*=()
template<typename NumericType = double> constexpr void PhQ::HeatFlux< NumericType >::operator*= (const NumericType number) inline constexpr noexcept
Definition at line 207 of file HeatFlux.hpp.
References PhQ::DimensionalVector< UnitType, NumericType >::value.
operator+()
template<typename NumericType = double> constexpr HeatFlux< NumericType > PhQ::HeatFlux< NumericType >::operator+ (const HeatFlux< NumericType > & heat_flux) const inline constexpr
Definition at line 183 of file HeatFlux.hpp.
References PhQ::DimensionalVector< UnitType, NumericType >::value.
operator+=()
template<typename NumericType = double> constexpr void PhQ::HeatFlux< NumericType >::operator+= (const HeatFlux< NumericType > & heat_flux) inline constexpr noexcept
Definition at line 199 of file HeatFlux.hpp.
References PhQ::DimensionalVector< UnitType, NumericType >::value.
operator-()
template<typename NumericType = double> constexpr HeatFlux< NumericType > PhQ::HeatFlux< NumericType >::operator- (const HeatFlux< NumericType > & heat_flux) const inline constexpr
Definition at line 187 of file HeatFlux.hpp.
References PhQ::DimensionalVector< UnitType, NumericType >::value.
operator-=()
template<typename NumericType = double> constexpr void PhQ::HeatFlux< NumericType >::operator-= (const HeatFlux< NumericType > & heat_flux) inline constexpr noexcept
Definition at line 203 of file HeatFlux.hpp.
References PhQ::DimensionalVector< UnitType, NumericType >::value.
operator/()
template<typename NumericType = double> constexpr HeatFlux< NumericType > PhQ::HeatFlux< NumericType >::operator/ (const NumericType number) const inline constexpr
Definition at line 195 of file HeatFlux.hpp.
References PhQ::DimensionalVector< UnitType, NumericType >::value.
operator/=()
template<typename NumericType = double> constexpr void PhQ::HeatFlux< NumericType >::operator/= (const NumericType number) inline constexpr noexcept
Definition at line 211 of file HeatFlux.hpp.
References PhQ::DimensionalVector< UnitType, NumericType >::value.
operator=() [1/3]
template<typename NumericType = double> constexpr HeatFlux< NumericType > & PhQ::HeatFlux< NumericType >::operator= (const HeatFlux< NumericType > & other) constexpr default
Copy assignment operator. Assigns this heat flux vector by copying another one.
operator=() [2/3]
template<typename NumericType = double> template<typename OtherNumericType > constexpr HeatFlux< NumericType > & PhQ::HeatFlux< NumericType >::operator= (const HeatFlux< OtherNumericType > & other) inline constexpr
Copy assignment operator. Assigns this heat flux vector by copying another one.
Definition at line 112 of file HeatFlux.hpp.
References PhQ::DimensionalVector< UnitType, NumericType >::Value(), and PhQ::DimensionalVector< UnitType, NumericType >::value.
operator=() [3/3]
template<typename NumericType = double> constexpr HeatFlux< NumericType > & PhQ::HeatFlux< NumericType >::operator= (HeatFlux< NumericType > && other) constexpr default noexcept
Move assignment operator. Assigns this heat flux vector by moving another one.
Print() [1/2]
template<typename UnitType , typename NumericType = double> std::string PhQ::DimensionalVector< UnitType, NumericType >::Print () const inline inherited
Prints this physical quantity as a string. This physical quantity's value is expressed in its standard unit of measure.
Definition at line 91 of file DimensionalVector.hpp.
References PhQ::Abbreviation(), and PhQ::DimensionalVector< UnitType, NumericType >::value.
Referenced by PhQ::operator<<(), PhQ::operator<<(), PhQ::operator<<(), PhQ::operator<<(), PhQ::operator<<(), PhQ::operator<<(), PhQ::operator<<(), PhQ::operator<<(), and PhQ::operator<<().
Print() [2/2]
template<typename UnitType , typename NumericType = double> std::string PhQ::DimensionalVector< UnitType, NumericType >::Print (const UnitType unit) const inline inherited
Prints this physical quantity as a string. This physical quantity's value is expressed in the given unit of measure.
Definition at line 97 of file DimensionalVector.hpp.
References PhQ::Abbreviation(), and PhQ::DimensionalVector< UnitType, NumericType >::Value().
SetValue()
template<typename UnitType , typename NumericType = double> constexpr void PhQ::DimensionalVector< UnitType, NumericType >::SetValue (const PhQ::Vector< NumericType > & value) inline constexpr noexcept inherited
Sets the value of this physical quantity expressed in its standard unit of measure to the given value.
Definition at line 85 of file DimensionalVector.hpp.
References PhQ::DimensionalVector< UnitType, NumericType >::value.
StaticValue()
template<typename UnitType , typename NumericType = double> template<UnitType NewUnit> constexpr PhQ::Vector< NumericType > PhQ::DimensionalVector< UnitType, NumericType >::StaticValue () const inline constexpr inherited
Value of this physical quantity expressed in a given unit of measure. This method can be evaluated statically at compile-time.
Definition at line 73 of file DimensionalVector.hpp.
References PhQ::DimensionalVector< UnitType, NumericType >::value.
Unit()
template<typename UnitType , typename NumericType = double> static constexpr UnitType PhQ::DimensionalVector< UnitType, NumericType >::Unit () inline static constexpr inherited
Standard unit of measure for this physical quantity. This physical quantity's value is stored internally in this unit of measure.
Definition at line 56 of file DimensionalVector.hpp.
Value() [1/2]
template<typename UnitType , typename NumericType = double> constexpr const PhQ::Vector< NumericType > & PhQ::DimensionalVector< UnitType, NumericType >::Value () const inline constexpr noexcept inherited
Value of this physical quantity expressed in its standard unit of measure.
Definition at line 61 of file DimensionalVector.hpp.
References PhQ::DimensionalVector< UnitType, NumericType >::value.
Referenced by PhQ::DimensionalVector< UnitType, NumericType >::JSON(), PhQ::Position< NumericType >::operator+(), PhQ::Displacement< NumericType >::operator+(), PhQ::Position< NumericType >::operator-(), PhQ::Displacement< NumericType >::operator-(), PhQ::Acceleration< NumericType >::operator=(), PhQ::DimensionalVector< UnitType, NumericType >::operator=(), PhQ::Displacement< NumericType >::operator=(), PhQ::Force< NumericType >::operator=(), PhQ::HeatFlux< NumericType >::operator=(), PhQ::Position< NumericType >::operator=(), PhQ::TemperatureGradient< NumericType >::operator=(), PhQ::Traction< NumericType >::operator=(), PhQ::VectorArea< NumericType >::operator=(), PhQ::Velocity< NumericType >::operator=(), PhQ::operator==(), PhQ::operator==(), PhQ::operator==(), PhQ::operator==(), PhQ::operator==(), PhQ::operator==(), PhQ::operator==(), PhQ::operator==(), PhQ::operator==(), PhQ::operator==(), PhQ::operator==(), PhQ::operator==(), PhQ::operator==(), PhQ::operator==(), PhQ::operator==(), PhQ::operator==(), PhQ::PlanarAcceleration< NumericType >::PlanarAcceleration(), PhQ::PlanarDisplacement< NumericType >::PlanarDisplacement(), PhQ::PlanarForce< NumericType >::PlanarForce(), PhQ::PlanarHeatFlux< NumericType >::PlanarHeatFlux(), PhQ::PlanarPosition< NumericType >::PlanarPosition(), PhQ::PlanarTemperatureGradient< NumericType >::PlanarTemperatureGradient(), PhQ::PlanarTraction< NumericType >::PlanarTraction(), PhQ::PlanarVelocity< NumericType >::PlanarVelocity(), PhQ::DimensionalVector< UnitType, NumericType >::Print(), PhQ::DimensionalVector< UnitType, NumericType >::XML(), and PhQ::DimensionalVector< UnitType, NumericType >::YAML().
Value() [2/2]
template<typename UnitType , typename NumericType = double> PhQ::Vector< NumericType > PhQ::DimensionalVector< UnitType, NumericType >::Value (const UnitType unit) const inline inherited
Value of this physical quantity expressed in a given unit of measure.
Definition at line 66 of file DimensionalVector.hpp.
References PhQ::Convert(), and PhQ::DimensionalVector< UnitType, NumericType >::value.
x()
template<typename NumericType = double> constexpr ScalarHeatFlux< NumericType > PhQ::HeatFlux< NumericType >::x () const inline constexpr noexcept
Returns the x Cartesian component of this heat flux vector.
Definition at line 154 of file HeatFlux.hpp.
References PhQ::DimensionalVector< UnitType, NumericType >::value.
Referenced by PhQ::HeatFlux< NumericType >::Create(), and PhQ::HeatFlux< NumericType >::HeatFlux().
XML() [1/2]
template<typename UnitType , typename NumericType = double> std::string PhQ::DimensionalVector< UnitType, NumericType >::XML () const inline inherited
Serializes this physical quantity as an XML message. This physical quantity's value is expressed in its standard unit of measure.
Definition at line 123 of file DimensionalVector.hpp.
References PhQ::Abbreviation(), and PhQ::DimensionalVector< UnitType, NumericType >::value.
Referenced by PhQ::DimensionalVector< UnitType, NumericType >::XML().
XML() [2/2]
template<typename UnitType , typename NumericType = double> std::string PhQ::DimensionalVector< UnitType, NumericType >::XML (const UnitType unit) const inline inherited
Serializes this physical quantity as an XML message. This physical quantity's value is expressed in the given unit of measure.
Definition at line 133 of file DimensionalVector.hpp.
References PhQ::Abbreviation(), PhQ::DimensionalVector< UnitType, NumericType >::Value(), and PhQ::DimensionalVector< UnitType, NumericType >::XML().
y()
template<typename NumericType = double> constexpr ScalarHeatFlux< NumericType > PhQ::HeatFlux< NumericType >::y () const inline constexpr noexcept
Returns the y Cartesian component of this heat flux vector.
Definition at line 159 of file HeatFlux.hpp.
References PhQ::DimensionalVector< UnitType, NumericType >::value.
Referenced by PhQ::HeatFlux< NumericType >::Create(), and PhQ::HeatFlux< NumericType >::HeatFlux().
YAML() [1/2]
template<typename UnitType , typename NumericType = double> std::string PhQ::DimensionalVector< UnitType, NumericType >::YAML () const inline inherited
Serializes this physical quantity as a YAML message. This physical quantity's value is expressed in its standard unit of measure.
Definition at line 143 of file DimensionalVector.hpp.
References PhQ::Abbreviation(), and PhQ::DimensionalVector< UnitType, NumericType >::value.
Referenced by PhQ::DimensionalVector< UnitType, NumericType >::YAML().
YAML() [2/2]
template<typename UnitType , typename NumericType = double> std::string PhQ::DimensionalVector< UnitType, NumericType >::YAML (const UnitType unit) const inline inherited
Serializes this physical quantity as a YAML message. This physical quantity's value is expressed in the given unit of measure.
Definition at line 153 of file DimensionalVector.hpp.
References PhQ::Abbreviation(), PhQ::DimensionalVector< UnitType, NumericType >::Value(), and PhQ::DimensionalVector< UnitType, NumericType >::YAML().
z()
template<typename NumericType = double> constexpr ScalarHeatFlux< NumericType > PhQ::HeatFlux< NumericType >::z () const inline constexpr noexcept
Returns the z Cartesian component of this heat flux vector.
Definition at line 164 of file HeatFlux.hpp.
References PhQ::DimensionalVector< UnitType, NumericType >::value.
Referenced by PhQ::HeatFlux< NumericType >::Create(), and PhQ::HeatFlux< NumericType >::HeatFlux().
Zero()
template<typename NumericType = double> static constexpr HeatFlux< NumericType > PhQ::HeatFlux< NumericType >::Zero () inline static constexpr
Statically creates a heat flux vector of zero.
Definition at line 121 of file HeatFlux.hpp.
References PhQ::Vector< NumericType >::Zero().
Member Data Documentation
value
template<typename UnitType , typename NumericType = double> PhQ::Vector<NumericType> PhQ::DimensionalVector< UnitType, NumericType >::value protected inherited
Value of this physical quantity expressed in its standard unit of measure.
Definition at line 217 of file DimensionalVector.hpp.
Referenced by PhQ::Acceleration< NumericType >::Create(), PhQ::Displacement< NumericType >::Create(), PhQ::Force< NumericType >::Create(), PhQ::HeatFlux< NumericType >::Create(), PhQ::Position< NumericType >::Create(), PhQ::TemperatureGradient< NumericType >::Create(), PhQ::Traction< NumericType >::Create(), PhQ::VectorArea< NumericType >::Create(), PhQ::Velocity< NumericType >::Create(), PhQ::Acceleration< NumericType >::Direction(), PhQ::Displacement< NumericType >::Direction(), PhQ::Force< NumericType >::Direction(), PhQ::HeatFlux< NumericType >::Direction(), PhQ::Position< NumericType >::Direction(), PhQ::TemperatureGradient< NumericType >::Direction(), PhQ::Traction< NumericType >::Direction(), PhQ::VectorArea< NumericType >::Direction(), PhQ::Velocity< NumericType >::Direction(), PhQ::DimensionalVector< UnitType, NumericType >::JSON(), PhQ::Acceleration< NumericType >::Magnitude(), PhQ::Displacement< NumericType >::Magnitude(), PhQ::Force< NumericType >::Magnitude(), PhQ::HeatFlux< NumericType >::Magnitude(), PhQ::Position< NumericType >::Magnitude(), PhQ::TemperatureGradient< NumericType >::Magnitude(), PhQ::Traction< NumericType >::Magnitude(), PhQ::VectorArea< NumericType >::Magnitude(), PhQ::Velocity< NumericType >::Magnitude(), PhQ::DimensionalVector< UnitType, NumericType >::MutableValue(), PhQ::Acceleration< NumericType >::operator*(), PhQ::Displacement< NumericType >::operator*(), PhQ::Force< NumericType >::operator*(), PhQ::HeatFlux< NumericType >::operator*(), PhQ::Position< NumericType >::operator*(), PhQ::TemperatureGradient< NumericType >::operator*(), PhQ::Traction< NumericType >::operator*(), PhQ::VectorArea< NumericType >::operator*(), PhQ::Velocity< NumericType >::operator*(), PhQ::Acceleration< NumericType >::operator*=(), PhQ::Displacement< NumericType >::operator*=(), PhQ::Force< NumericType >::operator*=(), PhQ::HeatFlux< NumericType >::operator*=(), PhQ::Position< NumericType >::operator*=(), PhQ::TemperatureGradient< NumericType >::operator*=(), PhQ::Traction< NumericType >::operator*=(), PhQ::VectorArea< NumericType >::operator*=(), PhQ::Velocity< NumericType >::operator*=(), PhQ::Acceleration< NumericType >::operator+(), PhQ::Displacement< NumericType >::operator+(), PhQ::Position< NumericType >::operator+(), PhQ::Force< NumericType >::operator+(), PhQ::HeatFlux< NumericType >::operator+(), PhQ::Position< NumericType >::operator+(), PhQ::TemperatureGradient< NumericType >::operator+(), PhQ::Traction< NumericType >::operator+(), PhQ::VectorArea< NumericType >::operator+(), PhQ::Velocity< NumericType >::operator+(), PhQ::Acceleration< NumericType >::operator+=(), PhQ::Displacement< NumericType >::operator+=(), PhQ::Position< NumericType >::operator+=(), PhQ::Force< NumericType >::operator+=(), PhQ::HeatFlux< NumericType >::operator+=(), PhQ::Position< NumericType >::operator+=(), PhQ::TemperatureGradient< NumericType >::operator+=(), PhQ::Traction< NumericType >::operator+=(), PhQ::VectorArea< NumericType >::operator+=(), PhQ::Velocity< NumericType >::operator+=(), PhQ::Acceleration< NumericType >::operator-(), PhQ::Displacement< NumericType >::operator-(), PhQ::Position< NumericType >::operator-(), PhQ::Force< NumericType >::operator-(), PhQ::HeatFlux< NumericType >::operator-(), PhQ::Position< NumericType >::operator-(), PhQ::TemperatureGradient< NumericType >::operator-(), PhQ::Traction< NumericType >::operator-(), PhQ::VectorArea< NumericType >::operator-(), PhQ::Velocity< NumericType >::operator-(), PhQ::Acceleration< NumericType >::operator-=(), PhQ::Displacement< NumericType >::operator-=(), PhQ::Position< NumericType >::operator-=(), PhQ::Force< NumericType >::operator-=(), PhQ::HeatFlux< NumericType >::operator-=(), PhQ::Position< NumericType >::operator-=(), PhQ::TemperatureGradient< NumericType >::operator-=(), PhQ::Traction< NumericType >::operator-=(), PhQ::VectorArea< NumericType >::operator-=(), PhQ::Velocity< NumericType >::operator-=(), PhQ::Acceleration< NumericType >::operator/(), PhQ::Displacement< NumericType >::operator/(), PhQ::Force< NumericType >::operator/(), PhQ::HeatFlux< NumericType >::operator/(), PhQ::Position< NumericType >::operator/(), PhQ::TemperatureGradient< NumericType >::operator/(), PhQ::Traction< NumericType >::operator/(), PhQ::VectorArea< NumericType >::operator/(), PhQ::Velocity< NumericType >::operator/(), PhQ::Acceleration< NumericType >::operator/=(), PhQ::Displacement< NumericType >::operator/=(), PhQ::Force< NumericType >::operator/=(), PhQ::HeatFlux< NumericType >::operator/=(), PhQ::Position< NumericType >::operator/=(), PhQ::TemperatureGradient< NumericType >::operator/=(), PhQ::Traction< NumericType >::operator/=(), PhQ::VectorArea< NumericType >::operator/=(), PhQ::Velocity< NumericType >::operator/=(), PhQ::Acceleration< NumericType >::operator=(), PhQ::DimensionalVector< UnitType, NumericType >::operator=(), PhQ::Displacement< NumericType >::operator=(), PhQ::Force< NumericType >::operator=(), PhQ::HeatFlux< NumericType >::operator=(), PhQ::Position< NumericType >::operator=(), PhQ::TemperatureGradient< NumericType >::operator=(), PhQ::Traction< NumericType >::operator=(), PhQ::VectorArea< NumericType >::operator=(), PhQ::Velocity< NumericType >::operator=(), PhQ::DimensionalVector< UnitType, NumericType >::Print(), PhQ::DimensionalVector< UnitType, NumericType >::SetValue(), PhQ::DimensionalVector< UnitType, NumericType >::StaticValue(), PhQ::DimensionalVector< UnitType, NumericType >::Value(), PhQ::DimensionalVector< UnitType, NumericType >::Value(), PhQ::Acceleration< NumericType >::x(), PhQ::Displacement< NumericType >::x(), PhQ::Force< NumericType >::x(), PhQ::HeatFlux< NumericType >::x(), PhQ::Position< NumericType >::x(), PhQ::TemperatureGradient< NumericType >::x(), PhQ::Traction< NumericType >::x(), PhQ::VectorArea< NumericType >::x(), PhQ::Velocity< NumericType >::x(), PhQ::DimensionalVector< UnitType, NumericType >::XML(), PhQ::Acceleration< NumericType >::y(), PhQ::Displacement< NumericType >::y(), PhQ::Force< NumericType >::y(), PhQ::HeatFlux< NumericType >::y(), PhQ::Position< NumericType >::y(), PhQ::TemperatureGradient< NumericType >::y(), PhQ::Traction< NumericType >::y(), PhQ::VectorArea< NumericType >::y(), PhQ::Velocity< NumericType >::y(), PhQ::DimensionalVector< UnitType, NumericType >::YAML(), PhQ::Acceleration< NumericType >::z(), PhQ::Displacement< NumericType >::z(), PhQ::Force< NumericType >::z(), PhQ::HeatFlux< NumericType >::z(), PhQ::Position< NumericType >::z(), PhQ::TemperatureGradient< NumericType >::z(), PhQ::Traction< NumericType >::z(), PhQ::VectorArea< NumericType >::z(), and PhQ::Velocity< NumericType >::z().
The documentation for this class was generated from the following files:
PhQ/Angle.hpp
PhQ/HeatFlux.hpp