Physical Quantities: PhQ::PlanarTemperatureGradient< NumericType > Class Template Reference
PhQ::PlanarTemperatureGradient< NumericType > Class Template Reference
Two-dimensional Euclidean temperature gradient vector in the XY plane. Contains two components in Cartesian coordinates: x and y. For a three-dimensional Euclidean temperature gradient vector, see PhQ::TemperatureGradient. For scalar temperature gradient components or for the magnitude of a temperature gradient vector, see PhQ::ScalarTemperatureGradient.
#include "PlanarTemperatureGradient.hpp"
Public Member Functions
PlanarTemperatureGradient ()=default
Default constructor. Constructs a planar temperature gradient vector with an uninitialized value.
PlanarTemperatureGradient (const PlanarVector< NumericType > &value, const Unit::TemperatureGradient unit)
Constructor. Constructs a planar temperature gradient vector with a given value expressed in a given temperature gradient unit.
PlanarTemperatureGradient (const ScalarTemperatureGradient< NumericType > &x, const ScalarTemperatureGradient< NumericType > &y)
Constructor. Constructs a planar temperature gradient vector from a given set of scalar temperature gradient components.
constexpr PlanarTemperatureGradient (const ScalarTemperatureGradient< NumericType > &scalar_temperature_gradient, const PlanarDirection< NumericType > &planar_direction)
Constructor. Constructs a planar temperature gradient vector from a given scalar temperature gradient magnitude and planar direction.
constexpr PlanarTemperatureGradient (const TemperatureGradient< NumericType > &temperature_gradient)
Constructor. Constructs a planar temperature gradient vector from a given temperature gradient vector by projecting the temperature gradient vector onto the XY plane.
~PlanarTemperatureGradient () noexcept=default
Destructor. Destroys this planar temperature gradient vector.
constexpr PlanarTemperatureGradient (const PlanarTemperatureGradient< NumericType > &other)=default
Copy constructor. Constructs a planar temperature gradient vector by copying another one.
template<typename OtherNumericType >
constexpr PlanarTemperatureGradient (const PlanarTemperatureGradient< OtherNumericType > &other)
Copy constructor. Constructs a planar temperature gradient vector by copying another one.
constexpr PlanarTemperatureGradient (PlanarTemperatureGradient< NumericType > &&other) noexcept=default
Move constructor. Constructs a planar temperature gradient vector by moving another one.
constexpr PlanarTemperatureGradient< NumericType > & operator= (const PlanarTemperatureGradient< NumericType > &other)=default
Copy assignment operator. Assigns this planar temperature gradient vector by copying another one.
template<typename OtherNumericType >
constexpr PlanarTemperatureGradient< NumericType > & operator= (const PlanarTemperatureGradient< OtherNumericType > &other)
Copy assignment operator. Assigns this planar temperature gradient vector by copying another one.
constexpr PlanarTemperatureGradient< NumericType > & operator= (PlanarTemperatureGradient< NumericType > &&other) noexcept=default
Move assignment operator. Assigns this planar temperature gradient vector by moving another one.
constexpr ScalarTemperatureGradient< NumericType > x () const noexcept
Returns the x Cartesian component of this planar temperature gradient vector.
constexpr ScalarTemperatureGradient< NumericType > y () const noexcept
Returns the y Cartesian component of this planar temperature gradient vector.
ScalarTemperatureGradient< NumericType > Magnitude () const
Returns the magnitude of this planar temperature gradient vector.
PhQ::PlanarDirection< NumericType > PlanarDirection () const
Returns the direction of this planar temperature gradient vector.
PhQ::Angle< NumericType > Angle (const PlanarTemperatureGradient< NumericType > &planar_temperature_gradient) const
Returns the angle between this planar temperature gradient vector and another one.
constexpr PlanarTemperatureGradient< NumericType > operator+ (const PlanarTemperatureGradient< NumericType > &planar_temperature_gradient) const
constexpr PlanarTemperatureGradient< NumericType > operator- (const PlanarTemperatureGradient< NumericType > &planar_temperature_gradient) const
constexpr PlanarTemperatureGradient< NumericType > operator* (const NumericType number) const
constexpr PlanarTemperatureGradient< NumericType > operator/ (const NumericType number) const
constexpr void operator+= (const PlanarTemperatureGradient< NumericType > &planar_temperature_gradient) noexcept
constexpr void operator-= (const PlanarTemperatureGradient< NumericType > &planar_temperature_gradient) noexcept
constexpr void operator*= (const NumericType number) noexcept
constexpr void operator/= (const NumericType number) noexcept
constexpr const PhQ::PlanarVector< NumericType > & Value () const noexcept
Value of this physical quantity expressed in its standard unit of measure.
PhQ::PlanarVector< NumericType > Value (const UnitType unit) const
Value of this physical quantity expressed in a given unit of measure.
template<UnitType NewUnit>
constexpr PhQ::PlanarVector< NumericType > StaticValue () const
Value of this physical quantity expressed in a given unit of measure. This method can be evaluated statically at compile-time.
constexpr PhQ::PlanarVector< NumericType > & MutableValue () noexcept
Returns the value of this physical quantity expressed in its standard unit of measure as a mutable value.
constexpr void SetValue (const PhQ::PlanarVector< NumericType > &value) noexcept
Sets the value of this physical quantity expressed in its standard unit of measure to the given value.
std::string Print () const
Prints this physical quantity as a string. This physical quantity's value is expressed in its standard unit of measure.
std::string Print (const UnitType unit) const
Prints this physical quantity as a string. This physical quantity's value is expressed in the given unit of measure.
std::string JSON () const
Serializes this physical quantity as a JSON message. This physical quantity's value is expressed in its standard unit of measure.
std::string JSON (const UnitType unit) const
Serializes this physical quantity as a JSON message. This physical quantity's value is expressed in the given unit of measure.
std::string XML () const
Serializes this physical quantity as an XML message. This physical quantity's value is expressed in its standard unit of measure.
std::string XML (const UnitType unit) const
Serializes this physical quantity as an XML message. This physical quantity's value is expressed in the given unit of measure.
std::string YAML () const
Serializes this physical quantity as a YAML message. This physical quantity's value is expressed in its standard unit of measure.
std::string YAML (const UnitType unit) const
Serializes this physical quantity as a YAML message. This physical quantity's value is expressed in the given unit of measure.
Static Public Member Functions
static constexpr PlanarTemperatureGradient< NumericType > Zero ()
Statically creates a planar temperature gradient vector of zero.
template<Unit::TemperatureGradient Unit>
static constexpr PlanarTemperatureGradient< NumericType > Create (const NumericType x, const NumericType y)
Statically creates a planar temperature gradient vector from the given x and y Cartesian components expressed in a given temperature gradient unit.
template<Unit::TemperatureGradient Unit>
static constexpr PlanarTemperatureGradient< NumericType > Create (const std::array< NumericType, 2 > &x_y)
Statically creates a planar temperature gradient vector from the given x and y Cartesian components expressed in a given temperature gradient unit.
template<Unit::TemperatureGradient Unit>
static constexpr PlanarTemperatureGradient< NumericType > Create (const PlanarVector< NumericType > &value)
Statically creates a planar temperature gradient vector with a given value expressed in a given temperature gradient unit.
static constexpr const PhQ::Dimensions & Dimensions ()
Physical dimension set of this physical quantity.
static constexpr UnitType Unit ()
Standard unit of measure for this physical quantity. This physical quantity's value is stored internally in this unit of measure.
Protected Attributes
PhQ::PlanarVector< NumericType > value
Value of this physical quantity expressed in its standard unit of measure.
Private Member Functions
constexpr PlanarTemperatureGradient (const PlanarVector< NumericType > &value)
Constructor. Constructs a planar temperature gradient vector with a given value expressed in the standard temperature gradient unit.
Detailed Description
template<typename NumericType = double>
class PhQ::PlanarTemperatureGradient< NumericType >
Two-dimensional Euclidean temperature gradient vector in the XY plane. Contains two components in Cartesian coordinates: x and y. For a three-dimensional Euclidean temperature gradient vector, see PhQ::TemperatureGradient. For scalar temperature gradient components or for the magnitude of a temperature gradient vector, see PhQ::ScalarTemperatureGradient.
Definition at line 47 of file PlanarTemperatureGradient.hpp.
Constructor & Destructor Documentation
PlanarTemperatureGradient() [1/9]
template<typename NumericType = double> PhQ::PlanarTemperatureGradient< NumericType >::PlanarTemperatureGradient () default
Default constructor. Constructs a planar temperature gradient vector with an uninitialized value.
PlanarTemperatureGradient() [2/9]
template<typename NumericType = double> PhQ::PlanarTemperatureGradient< NumericType >::PlanarTemperatureGradient (const PlanarVector< NumericType > & value, const Unit::TemperatureGradient unit) inline
Constructor. Constructs a planar temperature gradient vector with a given value expressed in a given temperature gradient unit.
Definition at line 56 of file PlanarTemperatureGradient.hpp.
PlanarTemperatureGradient() [3/9]
template<typename NumericType = double> PhQ::PlanarTemperatureGradient< NumericType >::PlanarTemperatureGradient (const ScalarTemperatureGradient< NumericType > & x, const ScalarTemperatureGradient< NumericType > & y) inline
Constructor. Constructs a planar temperature gradient vector from a given set of scalar temperature gradient components.
Definition at line 62 of file PlanarTemperatureGradient.hpp.
References PhQ::PlanarTemperatureGradient< NumericType >::x(), and PhQ::PlanarTemperatureGradient< NumericType >::y().
PlanarTemperatureGradient() [4/9]
template<typename NumericType = double> constexpr PhQ::PlanarTemperatureGradient< NumericType >::PlanarTemperatureGradient (const ScalarTemperatureGradient< NumericType > & scalar_temperature_gradient, const PlanarDirection< NumericType > & planar_direction) inline constexpr
Constructor. Constructs a planar temperature gradient vector from a given scalar temperature gradient magnitude and planar direction.
Definition at line 68 of file PlanarTemperatureGradient.hpp.
PlanarTemperatureGradient() [5/9]
template<typename NumericType > constexpr PhQ::PlanarTemperatureGradient< NumericType >::PlanarTemperatureGradient (const TemperatureGradient< NumericType > & temperature_gradient) inline explicit constexpr
Constructor. Constructs a planar temperature gradient vector from a given temperature gradient vector by projecting the temperature gradient vector onto the XY plane.
Definition at line 292 of file TemperatureGradient.hpp.
References PhQ::DimensionalVector< UnitType, NumericType >::Value().
~PlanarTemperatureGradient()
template<typename NumericType = double> PhQ::PlanarTemperatureGradient< NumericType >::~PlanarTemperatureGradient () default noexcept
Destructor. Destroys this planar temperature gradient vector.
PlanarTemperatureGradient() [6/9]
template<typename NumericType = double> constexpr PhQ::PlanarTemperatureGradient< NumericType >::PlanarTemperatureGradient (const PlanarTemperatureGradient< NumericType > & other) constexpr default
Copy constructor. Constructs a planar temperature gradient vector by copying another one.
PlanarTemperatureGradient() [7/9]
template<typename NumericType = double> template<typename OtherNumericType > constexpr PhQ::PlanarTemperatureGradient< NumericType >::PlanarTemperatureGradient (const PlanarTemperatureGradient< OtherNumericType > & other) inline explicit constexpr
Copy constructor. Constructs a planar temperature gradient vector by copying another one.
Definition at line 90 of file PlanarTemperatureGradient.hpp.
PlanarTemperatureGradient() [8/9]
template<typename NumericType = double> constexpr PhQ::PlanarTemperatureGradient< NumericType >::PlanarTemperatureGradient (PlanarTemperatureGradient< NumericType > && other) constexpr default noexcept
Move constructor. Constructs a planar temperature gradient vector by moving another one.
PlanarTemperatureGradient() [9/9]
template<typename NumericType = double> constexpr PhQ::PlanarTemperatureGradient< NumericType >::PlanarTemperatureGradient (const PlanarVector< NumericType > & value) inline explicit constexpr private
Constructor. Constructs a planar temperature gradient vector with a given value expressed in the standard temperature gradient unit.
Definition at line 218 of file PlanarTemperatureGradient.hpp.
Member Function Documentation
Angle()
template<typename NumericType = double> PhQ::Angle< NumericType > PhQ::PlanarTemperatureGradient< NumericType >::Angle (const PlanarTemperatureGradient< NumericType > & planar_temperature_gradient) const inline
Returns the angle between this planar temperature gradient vector and another one.
Definition at line 174 of file PlanarTemperatureGradient.hpp.
Create() [1/3]
template<typename NumericType = double> template<Unit::TemperatureGradient Unit> static constexpr PlanarTemperatureGradient< NumericType > PhQ::PlanarTemperatureGradient< NumericType >::Create (const NumericType x, const NumericType y) inline static constexpr
Statically creates a planar temperature gradient vector from the given x and y Cartesian components expressed in a given temperature gradient unit.
Definition at line 126 of file PlanarTemperatureGradient.hpp.
References PhQ::PlanarTemperatureGradient< NumericType >::x(), and PhQ::PlanarTemperatureGradient< NumericType >::y().
Create() [2/3]
template<typename NumericType = double> template<Unit::TemperatureGradient Unit> static constexpr PlanarTemperatureGradient< NumericType > PhQ::PlanarTemperatureGradient< NumericType >::Create (const PlanarVector< NumericType > & value) inline static constexpr
Statically creates a planar temperature gradient vector with a given value expressed in a given temperature gradient unit.
Definition at line 146 of file PlanarTemperatureGradient.hpp.
References PhQ::DimensionalPlanarVector< UnitType, NumericType >::value.
Create() [3/3]
template<typename NumericType = double> template<Unit::TemperatureGradient Unit> static constexpr PlanarTemperatureGradient< NumericType > PhQ::PlanarTemperatureGradient< NumericType >::Create (const std::array< NumericType, 2 > & x_y) inline static constexpr
Statically creates a planar temperature gradient vector from the given x and y Cartesian components expressed in a given temperature gradient unit.
Definition at line 136 of file PlanarTemperatureGradient.hpp.
Dimensions()
template<typename UnitType , typename NumericType = double> static constexpr const PhQ::Dimensions & PhQ::DimensionalPlanarVector< UnitType, NumericType >::Dimensions () inline static constexpr inherited
Physical dimension set of this physical quantity.
Definition at line 50 of file DimensionalPlanarVector.hpp.
JSON() [1/2]
template<typename UnitType , typename NumericType = double> std::string PhQ::DimensionalPlanarVector< UnitType, NumericType >::JSON () const inline inherited
Serializes this physical quantity as a JSON message. This physical quantity's value is expressed in its standard unit of measure.
Definition at line 103 of file DimensionalPlanarVector.hpp.
References PhQ::Abbreviation(), and PhQ::DimensionalPlanarVector< UnitType, NumericType >::value.
Referenced by PhQ::DimensionalPlanarVector< UnitType, NumericType >::JSON().
JSON() [2/2]
template<typename UnitType , typename NumericType = double> std::string PhQ::DimensionalPlanarVector< UnitType, NumericType >::JSON (const UnitType unit) const inline inherited
Serializes this physical quantity as a JSON message. This physical quantity's value is expressed in the given unit of measure.
Definition at line 113 of file DimensionalPlanarVector.hpp.
References PhQ::Abbreviation(), PhQ::DimensionalPlanarVector< UnitType, NumericType >::JSON(), and PhQ::DimensionalPlanarVector< UnitType, NumericType >::Value().
Magnitude()
template<typename NumericType = double> ScalarTemperatureGradient< NumericType > PhQ::PlanarTemperatureGradient< NumericType >::Magnitude () const inline
Returns the magnitude of this planar temperature gradient vector.
Definition at line 164 of file PlanarTemperatureGradient.hpp.
References PhQ::DimensionalPlanarVector< UnitType, NumericType >::value.
MutableValue()
template<typename UnitType , typename NumericType = double> constexpr PhQ::PlanarVector< NumericType > & PhQ::DimensionalPlanarVector< UnitType, NumericType >::MutableValue () inline constexpr noexcept inherited
Returns the value of this physical quantity expressed in its standard unit of measure as a mutable value.
Definition at line 79 of file DimensionalPlanarVector.hpp.
References PhQ::DimensionalPlanarVector< UnitType, NumericType >::value.
operator*()
template<typename NumericType = double> constexpr PlanarTemperatureGradient< NumericType > PhQ::PlanarTemperatureGradient< NumericType >::operator* (const NumericType number) const inline constexpr
Definition at line 189 of file PlanarTemperatureGradient.hpp.
References PhQ::DimensionalPlanarVector< UnitType, NumericType >::value.
operator*=()
template<typename NumericType = double> constexpr void PhQ::PlanarTemperatureGradient< NumericType >::operator*= (const NumericType number) inline constexpr noexcept
Definition at line 207 of file PlanarTemperatureGradient.hpp.
References PhQ::DimensionalPlanarVector< UnitType, NumericType >::value.
operator+()
template<typename NumericType = double> constexpr PlanarTemperatureGradient< NumericType > PhQ::PlanarTemperatureGradient< NumericType >::operator+ (const PlanarTemperatureGradient< NumericType > & planar_temperature_gradient) const inline constexpr
Definition at line 179 of file PlanarTemperatureGradient.hpp.
References PhQ::DimensionalPlanarVector< UnitType, NumericType >::value.
operator+=()
template<typename NumericType = double> constexpr void PhQ::PlanarTemperatureGradient< NumericType >::operator+= (const PlanarTemperatureGradient< NumericType > & planar_temperature_gradient) inline constexpr noexcept
Definition at line 197 of file PlanarTemperatureGradient.hpp.
References PhQ::DimensionalPlanarVector< UnitType, NumericType >::value.
operator-()
template<typename NumericType = double> constexpr PlanarTemperatureGradient< NumericType > PhQ::PlanarTemperatureGradient< NumericType >::operator- (const PlanarTemperatureGradient< NumericType > & planar_temperature_gradient) const inline constexpr
Definition at line 184 of file PlanarTemperatureGradient.hpp.
References PhQ::DimensionalPlanarVector< UnitType, NumericType >::value.
operator-=()
template<typename NumericType = double> constexpr void PhQ::PlanarTemperatureGradient< NumericType >::operator-= (const PlanarTemperatureGradient< NumericType > & planar_temperature_gradient) inline constexpr noexcept
Definition at line 202 of file PlanarTemperatureGradient.hpp.
References PhQ::DimensionalPlanarVector< UnitType, NumericType >::value.
operator/()
template<typename NumericType = double> constexpr PlanarTemperatureGradient< NumericType > PhQ::PlanarTemperatureGradient< NumericType >::operator/ (const NumericType number) const inline constexpr
Definition at line 193 of file PlanarTemperatureGradient.hpp.
References PhQ::DimensionalPlanarVector< UnitType, NumericType >::value.
operator/=()
template<typename NumericType = double> constexpr void PhQ::PlanarTemperatureGradient< NumericType >::operator/= (const NumericType number) inline constexpr noexcept
Definition at line 211 of file PlanarTemperatureGradient.hpp.
References PhQ::DimensionalPlanarVector< UnitType, NumericType >::value.
operator=() [1/3]
template<typename NumericType = double> constexpr PlanarTemperatureGradient< NumericType > & PhQ::PlanarTemperatureGradient< NumericType >::operator= (const PlanarTemperatureGradient< NumericType > & other) constexpr default
Copy assignment operator. Assigns this planar temperature gradient vector by copying another one.
operator=() [2/3]
template<typename NumericType = double> template<typename OtherNumericType > constexpr PlanarTemperatureGradient< NumericType > & PhQ::PlanarTemperatureGradient< NumericType >::operator= (const PlanarTemperatureGradient< OtherNumericType > & other) inline constexpr
Copy assignment operator. Assigns this planar temperature gradient vector by copying another one.
Definition at line 107 of file PlanarTemperatureGradient.hpp.
References PhQ::DimensionalPlanarVector< UnitType, NumericType >::Value(), and PhQ::DimensionalPlanarVector< UnitType, NumericType >::value.
operator=() [3/3]
template<typename NumericType = double> constexpr PlanarTemperatureGradient< NumericType > & PhQ::PlanarTemperatureGradient< NumericType >::operator= (PlanarTemperatureGradient< NumericType > && other) constexpr default noexcept
Move assignment operator. Assigns this planar temperature gradient vector by moving another one.
PlanarDirection()
template<typename NumericType = double> PhQ::PlanarDirection< NumericType > PhQ::PlanarTemperatureGradient< NumericType >::PlanarDirection () const inline
Returns the direction of this planar temperature gradient vector.
Definition at line 169 of file PlanarTemperatureGradient.hpp.
References PhQ::DimensionalPlanarVector< UnitType, NumericType >::value.
Print() [1/2]
template<typename UnitType , typename NumericType = double> std::string PhQ::DimensionalPlanarVector< UnitType, NumericType >::Print () const inline inherited
Prints this physical quantity as a string. This physical quantity's value is expressed in its standard unit of measure.
Definition at line 91 of file DimensionalPlanarVector.hpp.
References PhQ::Abbreviation(), and PhQ::DimensionalPlanarVector< UnitType, NumericType >::value.
Referenced by PhQ::operator<<(), PhQ::operator<<(), PhQ::operator<<(), PhQ::operator<<(), PhQ::operator<<(), PhQ::operator<<(), PhQ::operator<<(), and PhQ::operator<<().
Print() [2/2]
template<typename UnitType , typename NumericType = double> std::string PhQ::DimensionalPlanarVector< UnitType, NumericType >::Print (const UnitType unit) const inline inherited
Prints this physical quantity as a string. This physical quantity's value is expressed in the given unit of measure.
Definition at line 97 of file DimensionalPlanarVector.hpp.
References PhQ::Abbreviation(), and PhQ::DimensionalPlanarVector< UnitType, NumericType >::Value().
SetValue()
template<typename UnitType , typename NumericType = double> constexpr void PhQ::DimensionalPlanarVector< UnitType, NumericType >::SetValue (const PhQ::PlanarVector< NumericType > & value) inline constexpr noexcept inherited
Sets the value of this physical quantity expressed in its standard unit of measure to the given value.
Definition at line 85 of file DimensionalPlanarVector.hpp.
References PhQ::DimensionalPlanarVector< UnitType, NumericType >::value.
StaticValue()
template<typename UnitType , typename NumericType = double> template<UnitType NewUnit> constexpr PhQ::PlanarVector< NumericType > PhQ::DimensionalPlanarVector< UnitType, NumericType >::StaticValue () const inline constexpr inherited
Value of this physical quantity expressed in a given unit of measure. This method can be evaluated statically at compile-time.
Definition at line 73 of file DimensionalPlanarVector.hpp.
References PhQ::DimensionalPlanarVector< UnitType, NumericType >::value.
Unit()
template<typename UnitType , typename NumericType = double> static constexpr UnitType PhQ::DimensionalPlanarVector< UnitType, NumericType >::Unit () inline static constexpr inherited
Standard unit of measure for this physical quantity. This physical quantity's value is stored internally in this unit of measure.
Definition at line 56 of file DimensionalPlanarVector.hpp.
Value() [1/2]
template<typename UnitType , typename NumericType = double> constexpr const PhQ::PlanarVector< NumericType > & PhQ::DimensionalPlanarVector< UnitType, NumericType >::Value () const inline constexpr noexcept inherited
Value of this physical quantity expressed in its standard unit of measure.
Definition at line 61 of file DimensionalPlanarVector.hpp.
References PhQ::DimensionalPlanarVector< UnitType, NumericType >::value.
Referenced by PhQ::Acceleration< NumericType >::Acceleration(), PhQ::Displacement< NumericType >::Displacement(), PhQ::Force< NumericType >::Force(), PhQ::HeatFlux< NumericType >::HeatFlux(), PhQ::DimensionalPlanarVector< UnitType, NumericType >::JSON(), PhQ::PlanarPosition< NumericType >::operator+(), PhQ::PlanarDisplacement< NumericType >::operator+(), PhQ::PlanarPosition< NumericType >::operator-(), PhQ::PlanarDisplacement< NumericType >::operator-(), PhQ::DimensionalPlanarVector< UnitType, NumericType >::operator=(), PhQ::PlanarAcceleration< NumericType >::operator=(), PhQ::PlanarDisplacement< NumericType >::operator=(), PhQ::PlanarForce< NumericType >::operator=(), PhQ::PlanarHeatFlux< NumericType >::operator=(), PhQ::PlanarPosition< NumericType >::operator=(), PhQ::PlanarTemperatureGradient< NumericType >::operator=(), PhQ::PlanarTraction< NumericType >::operator=(), PhQ::PlanarVelocity< NumericType >::operator=(), PhQ::operator==(), PhQ::operator==(), PhQ::PlanarHeatFlux< NumericType >::PlanarHeatFlux(), PhQ::Position< NumericType >::Position(), PhQ::DimensionalPlanarVector< UnitType, NumericType >::Print(), PhQ::TemperatureGradient< NumericType >::TemperatureGradient(), PhQ::Traction< NumericType >::Traction(), PhQ::Velocity< NumericType >::Velocity(), PhQ::DimensionalPlanarVector< UnitType, NumericType >::XML(), and PhQ::DimensionalPlanarVector< UnitType, NumericType >::YAML().
Value() [2/2]
template<typename UnitType , typename NumericType = double> PhQ::PlanarVector< NumericType > PhQ::DimensionalPlanarVector< UnitType, NumericType >::Value (const UnitType unit) const inline inherited
Value of this physical quantity expressed in a given unit of measure.
Definition at line 66 of file DimensionalPlanarVector.hpp.
References PhQ::Convert(), and PhQ::DimensionalPlanarVector< UnitType, NumericType >::value.
x()
template<typename NumericType = double> constexpr ScalarTemperatureGradient< NumericType > PhQ::PlanarTemperatureGradient< NumericType >::x () const inline constexpr noexcept
Returns the x Cartesian component of this planar temperature gradient vector.
Definition at line 154 of file PlanarTemperatureGradient.hpp.
References PhQ::DimensionalPlanarVector< UnitType, NumericType >::value.
Referenced by PhQ::PlanarTemperatureGradient< NumericType >::Create(), and PhQ::PlanarTemperatureGradient< NumericType >::PlanarTemperatureGradient().
XML() [1/2]
template<typename UnitType , typename NumericType = double> std::string PhQ::DimensionalPlanarVector< UnitType, NumericType >::XML () const inline inherited
Serializes this physical quantity as an XML message. This physical quantity's value is expressed in its standard unit of measure.
Definition at line 123 of file DimensionalPlanarVector.hpp.
References PhQ::Abbreviation(), and PhQ::DimensionalPlanarVector< UnitType, NumericType >::value.
Referenced by PhQ::DimensionalPlanarVector< UnitType, NumericType >::XML().
XML() [2/2]
template<typename UnitType , typename NumericType = double> std::string PhQ::DimensionalPlanarVector< UnitType, NumericType >::XML (const UnitType unit) const inline inherited
Serializes this physical quantity as an XML message. This physical quantity's value is expressed in the given unit of measure.
Definition at line 133 of file DimensionalPlanarVector.hpp.
References PhQ::Abbreviation(), PhQ::DimensionalPlanarVector< UnitType, NumericType >::Value(), and PhQ::DimensionalPlanarVector< UnitType, NumericType >::XML().
y()
template<typename NumericType = double> constexpr ScalarTemperatureGradient< NumericType > PhQ::PlanarTemperatureGradient< NumericType >::y () const inline constexpr noexcept
Returns the y Cartesian component of this planar temperature gradient vector.
Definition at line 159 of file PlanarTemperatureGradient.hpp.
References PhQ::DimensionalPlanarVector< UnitType, NumericType >::value.
Referenced by PhQ::PlanarTemperatureGradient< NumericType >::Create(), and PhQ::PlanarTemperatureGradient< NumericType >::PlanarTemperatureGradient().
YAML() [1/2]
template<typename UnitType , typename NumericType = double> std::string PhQ::DimensionalPlanarVector< UnitType, NumericType >::YAML () const inline inherited
Serializes this physical quantity as a YAML message. This physical quantity's value is expressed in its standard unit of measure.
Definition at line 143 of file DimensionalPlanarVector.hpp.
References PhQ::Abbreviation(), and PhQ::DimensionalPlanarVector< UnitType, NumericType >::value.
Referenced by PhQ::DimensionalPlanarVector< UnitType, NumericType >::YAML().
YAML() [2/2]
template<typename UnitType , typename NumericType = double> std::string PhQ::DimensionalPlanarVector< UnitType, NumericType >::YAML (const UnitType unit) const inline inherited
Serializes this physical quantity as a YAML message. This physical quantity's value is expressed in the given unit of measure.
Definition at line 153 of file DimensionalPlanarVector.hpp.
References PhQ::Abbreviation(), PhQ::DimensionalPlanarVector< UnitType, NumericType >::Value(), and PhQ::DimensionalPlanarVector< UnitType, NumericType >::YAML().
Zero()
template<typename NumericType = double> static constexpr PlanarTemperatureGradient< NumericType > PhQ::PlanarTemperatureGradient< NumericType >::Zero () inline static constexpr
Statically creates a planar temperature gradient vector of zero.
Definition at line 119 of file PlanarTemperatureGradient.hpp.
References PhQ::PlanarVector< NumericType >::Zero().
Member Data Documentation
value
template<typename UnitType , typename NumericType = double> PhQ::PlanarVector<NumericType> PhQ::DimensionalPlanarVector< UnitType, NumericType >::value protected inherited
Value of this physical quantity expressed in its standard unit of measure.
Definition at line 222 of file DimensionalPlanarVector.hpp.
Referenced by PhQ::PlanarAcceleration< NumericType >::Create(), PhQ::PlanarDisplacement< NumericType >::Create(), PhQ::PlanarForce< NumericType >::Create(), PhQ::PlanarHeatFlux< NumericType >::Create(), PhQ::PlanarPosition< NumericType >::Create(), PhQ::PlanarTemperatureGradient< NumericType >::Create(), PhQ::PlanarTraction< NumericType >::Create(), PhQ::PlanarVelocity< NumericType >::Create(), PhQ::DimensionalPlanarVector< UnitType, NumericType >::JSON(), PhQ::PlanarAcceleration< NumericType >::Magnitude(), PhQ::PlanarDisplacement< NumericType >::Magnitude(), PhQ::PlanarForce< NumericType >::Magnitude(), PhQ::PlanarHeatFlux< NumericType >::Magnitude(), PhQ::PlanarPosition< NumericType >::Magnitude(), PhQ::PlanarTemperatureGradient< NumericType >::Magnitude(), PhQ::PlanarTraction< NumericType >::Magnitude(), PhQ::PlanarVelocity< NumericType >::Magnitude(), PhQ::DimensionalPlanarVector< UnitType, NumericType >::MutableValue(), PhQ::PlanarAcceleration< NumericType >::operator*(), PhQ::PlanarDisplacement< NumericType >::operator*(), PhQ::PlanarForce< NumericType >::operator*(), PhQ::PlanarHeatFlux< NumericType >::operator*(), PhQ::PlanarPosition< NumericType >::operator*(), PhQ::PlanarTemperatureGradient< NumericType >::operator*(), PhQ::PlanarTraction< NumericType >::operator*(), PhQ::PlanarVelocity< NumericType >::operator*(), PhQ::PlanarAcceleration< NumericType >::operator*=(), PhQ::PlanarDisplacement< NumericType >::operator*=(), PhQ::PlanarForce< NumericType >::operator*=(), PhQ::PlanarHeatFlux< NumericType >::operator*=(), PhQ::PlanarPosition< NumericType >::operator*=(), PhQ::PlanarTemperatureGradient< NumericType >::operator*=(), PhQ::PlanarTraction< NumericType >::operator*=(), PhQ::PlanarVelocity< NumericType >::operator*=(), PhQ::PlanarAcceleration< NumericType >::operator+(), PhQ::PlanarDisplacement< NumericType >::operator+(), PhQ::PlanarPosition< NumericType >::operator+(), PhQ::PlanarForce< NumericType >::operator+(), PhQ::PlanarHeatFlux< NumericType >::operator+(), PhQ::PlanarPosition< NumericType >::operator+(), PhQ::PlanarTemperatureGradient< NumericType >::operator+(), PhQ::PlanarTraction< NumericType >::operator+(), PhQ::PlanarVelocity< NumericType >::operator+(), PhQ::PlanarAcceleration< NumericType >::operator+=(), PhQ::PlanarDisplacement< NumericType >::operator+=(), PhQ::PlanarPosition< NumericType >::operator+=(), PhQ::PlanarForce< NumericType >::operator+=(), PhQ::PlanarHeatFlux< NumericType >::operator+=(), PhQ::PlanarPosition< NumericType >::operator+=(), PhQ::PlanarTemperatureGradient< NumericType >::operator+=(), PhQ::PlanarTraction< NumericType >::operator+=(), PhQ::PlanarVelocity< NumericType >::operator+=(), PhQ::PlanarAcceleration< NumericType >::operator-(), PhQ::PlanarDisplacement< NumericType >::operator-(), PhQ::PlanarPosition< NumericType >::operator-(), PhQ::PlanarForce< NumericType >::operator-(), PhQ::PlanarHeatFlux< NumericType >::operator-(), PhQ::PlanarPosition< NumericType >::operator-(), PhQ::PlanarTemperatureGradient< NumericType >::operator-(), PhQ::PlanarTraction< NumericType >::operator-(), PhQ::PlanarVelocity< NumericType >::operator-(), PhQ::PlanarAcceleration< NumericType >::operator-=(), PhQ::PlanarDisplacement< NumericType >::operator-=(), PhQ::PlanarPosition< NumericType >::operator-=(), PhQ::PlanarForce< NumericType >::operator-=(), PhQ::PlanarHeatFlux< NumericType >::operator-=(), PhQ::PlanarPosition< NumericType >::operator-=(), PhQ::PlanarTemperatureGradient< NumericType >::operator-=(), PhQ::PlanarTraction< NumericType >::operator-=(), PhQ::PlanarVelocity< NumericType >::operator-=(), PhQ::PlanarAcceleration< NumericType >::operator/(), PhQ::PlanarDisplacement< NumericType >::operator/(), PhQ::PlanarForce< NumericType >::operator/(), PhQ::PlanarHeatFlux< NumericType >::operator/(), PhQ::PlanarPosition< NumericType >::operator/(), PhQ::PlanarTemperatureGradient< NumericType >::operator/(), PhQ::PlanarTraction< NumericType >::operator/(), PhQ::PlanarVelocity< NumericType >::operator/(), PhQ::PlanarAcceleration< NumericType >::operator/=(), PhQ::PlanarDisplacement< NumericType >::operator/=(), PhQ::PlanarForce< NumericType >::operator/=(), PhQ::PlanarHeatFlux< NumericType >::operator/=(), PhQ::PlanarPosition< NumericType >::operator/=(), PhQ::PlanarTemperatureGradient< NumericType >::operator/=(), PhQ::PlanarTraction< NumericType >::operator/=(), PhQ::PlanarVelocity< NumericType >::operator/=(), PhQ::DimensionalPlanarVector< UnitType, NumericType >::operator=(), PhQ::PlanarAcceleration< NumericType >::operator=(), PhQ::PlanarDisplacement< NumericType >::operator=(), PhQ::PlanarForce< NumericType >::operator=(), PhQ::PlanarHeatFlux< NumericType >::operator=(), PhQ::PlanarPosition< NumericType >::operator=(), PhQ::PlanarTemperatureGradient< NumericType >::operator=(), PhQ::PlanarTraction< NumericType >::operator=(), PhQ::PlanarVelocity< NumericType >::operator=(), PhQ::PlanarAcceleration< NumericType >::PlanarDirection(), PhQ::PlanarDisplacement< NumericType >::PlanarDirection(), PhQ::PlanarForce< NumericType >::PlanarDirection(), PhQ::PlanarHeatFlux< NumericType >::PlanarDirection(), PhQ::PlanarPosition< NumericType >::PlanarDirection(), PhQ::PlanarTemperatureGradient< NumericType >::PlanarDirection(), PhQ::PlanarTraction< NumericType >::PlanarDirection(), PhQ::PlanarVelocity< NumericType >::PlanarDirection(), PhQ::DimensionalPlanarVector< UnitType, NumericType >::Print(), PhQ::DimensionalPlanarVector< UnitType, NumericType >::SetValue(), PhQ::DimensionalPlanarVector< UnitType, NumericType >::StaticValue(), PhQ::DimensionalPlanarVector< UnitType, NumericType >::Value(), PhQ::DimensionalPlanarVector< UnitType, NumericType >::Value(), PhQ::PlanarAcceleration< NumericType >::x(), PhQ::PlanarDisplacement< NumericType >::x(), PhQ::PlanarForce< NumericType >::x(), PhQ::PlanarHeatFlux< NumericType >::x(), PhQ::PlanarPosition< NumericType >::x(), PhQ::PlanarTemperatureGradient< NumericType >::x(), PhQ::PlanarTraction< NumericType >::x(), PhQ::PlanarVelocity< NumericType >::x(), PhQ::DimensionalPlanarVector< UnitType, NumericType >::XML(), PhQ::PlanarAcceleration< NumericType >::y(), PhQ::PlanarDisplacement< NumericType >::y(), PhQ::PlanarForce< NumericType >::y(), PhQ::PlanarHeatFlux< NumericType >::y(), PhQ::PlanarPosition< NumericType >::y(), PhQ::PlanarTemperatureGradient< NumericType >::y(), PhQ::PlanarTraction< NumericType >::y(), PhQ::PlanarVelocity< NumericType >::y(), PhQ::DimensionalPlanarVector< UnitType, NumericType >::YAML(), and PhQ::PlanarDisplacement< NumericType >::z().
The documentation for this class was generated from the following files:
PhQ/Angle.hpp
PhQ/PlanarTemperatureGradient.hpp
PhQ/TemperatureGradient.hpp