Physical Quantities (PhQ): PhQ::Vector< NumericType > Class Template Reference
PhQ::Vector< NumericType > Class Template Reference
Three-dimensional Euclidean vector. Contains three components in Cartesian coordinates: x, y, and z. For a two-dimensional Euclidean vector in the XY plane, see PhQ::PlanarVector. For a three-dimensional Euclidean dyadic tensor, see PhQ::Dyad. For a three-dimensional symmetric Euclidean dyadic tensor, see PhQ::SymmetricDyad.
#include "Vector.hpp"
Public Member Functions
Vector ()=default
Default constructor. Constructs a three-dimensional vector with uninitialized x, y, and z Cartesian components.
constexpr Vector (const NumericType x, const NumericType y, const NumericType z)
Constructor. Constructs a three-dimensional vector from the given x, y, and z Cartesian components.
constexpr Vector (const std::array< NumericType, 3 > &x_y_z)
Constructor. Constructs a three-dimensional vector from a given array representing its x, y, and z Cartesian components.
constexpr Vector (const PlanarVector< NumericType > &planar_vector)
Constructor. Constructs a three-dimensional vector from a given two-dimensional planar vector in the XY plane. This vector's z-component is initialized to zero.
constexpr Vector (NumericType magnitude, const Direction< NumericType > &direction)
Constructor. Constructs a three-dimensional vector given a magnitude and a direction.
~Vector () noexcept=default
Destructor. Destroys this three-dimensional vector.
constexpr Vector (const Vector< NumericType > &other)=default
Copy constructor. Constructs a three-dimensional vector by copying another one.
template<typename OtherNumericType >
constexpr Vector (const Vector< OtherNumericType > &other)
Copy constructor. Constructs a three-dimensional vector by copying another one.
constexpr Vector (Vector< NumericType > &&other) noexcept=default
Move constructor. Constructs a three-dimensional vector by moving another one.
constexpr Vector< NumericType > & operator= (const Vector< NumericType > &other)=default
Copy assignment operator. Assigns this three-dimensional vector by copying another one.
template<typename OtherNumericType >
constexpr Vector< NumericType > & operator= (const Vector< OtherNumericType > &other)
Copy assignment operator. Assigns this three-dimensional vector by copying another one.
constexpr Vector< NumericType > & operator= (Vector< NumericType > &&other) noexcept=default
Move assignment operator. Assigns this three-dimensional vector by moving another one.
constexpr Vector< NumericType > & operator= (const std::array< NumericType, 3 > &x_y_z)
Assignment operator. Assigns this three-dimensional vector by copying a given array representing its x, y, and z Cartesian components.
constexpr const std::array< NumericType, 3 > & x_y_z () const noexcept
Returns this three-dimensional vector's x, y, and z Cartesian components as an array.
constexpr NumericType x () const noexcept
Returns this three-dimensional vector's x Cartesian component.
constexpr NumericType y () const noexcept
Returns this three-dimensional vector's y Cartesian component.
constexpr NumericType z () const noexcept
Returns this three-dimensional vector's z Cartesian component.
constexpr std::array< NumericType, 3 > & Mutable_x_y_z () noexcept
Returns this three-dimensional vector's x, y, and z Cartesian components as a mutable array.
constexpr NumericType & Mutable_x () noexcept
Returns this three-dimensional vector's x Cartesian component as a mutable value.
constexpr NumericType & Mutable_y () noexcept
Returns this three-dimensional vector's y Cartesian component as a mutable value.
constexpr NumericType & Mutable_z () noexcept
Returns this three-dimensional vector's z Cartesian component as a mutable value.
constexpr void Set_x_y_z (const std::array< NumericType, 3 > &x_y_z) noexcept
Sets this three-dimensional vector's x, y, and z Cartesian components to the given values.
constexpr void Set_x_y_z (const NumericType x, const NumericType y, const NumericType z) noexcept
Sets this three-dimensional vector's x, y, and z Cartesian components to the given values.
constexpr void Set_x (const NumericType x) noexcept
Sets this three-dimensional vector's x Cartesian component to a given value.
constexpr void Set_y (const NumericType y) noexcept
Sets this three-dimensional vector's y Cartesian component to a given value.
constexpr void Set_z (const NumericType z) noexcept
Sets this three-dimensional vector's z Cartesian component to a given value.
constexpr NumericType MagnitudeSquared () const noexcept
Returns the square of the magnitude of this three-dimensional vector.
NumericType Magnitude () const noexcept
Returns the magnitude (also known as the L2 norm) of this three-dimensional vector.
PhQ::Direction< NumericType > Direction () const
Returns the direction of this three-dimensional vector.
constexpr NumericType Dot (const Vector< NumericType > &vector) const noexcept
Returns the dot product (also known as the inner product or scalar product) of this three-dimensional vector and another one.
constexpr NumericType Dot (const PhQ::Direction< NumericType > &direction) const noexcept
Returns the dot product (also known as the inner product or scalar product) of this three-dimensional vector and a given direction.
constexpr Vector< NumericType > Cross (const Vector< NumericType > &vector) const
Returns the cross product (also known as the vector product) of this three-dimensional vector and another one.
constexpr Vector< NumericType > Cross (const PhQ::Direction< NumericType > &direction) const
Returns the cross product (also known as the vector product) of this three-dimensional vector and a given direction.
constexpr Dyad< NumericType > Dyadic (const Vector< NumericType > &vector) const
Returns the dyadic tensor product (also known as the outer product) of this three-dimensional vector and another one.
constexpr Dyad< NumericType > Dyadic (const PhQ::Direction< NumericType > &direction) const
Returns the dyadic tensor product (also known as the outer product) of this three-dimensional vector and a given direction.
PhQ::Angle< NumericType > Angle (const Vector< NumericType > &vector) const
Returns the angle between this three-dimensional vector and another one.
PhQ::Angle< NumericType > Angle (const PhQ::Direction< NumericType > &direction) const
Returns the angle between this three-dimensional vector and a given direction.
std::string Print () const
Prints this three-dimensional vector as a string.
std::string JSON () const
Serializes this three-dimensional vector as a JSON message.
std::string XML () const
Serializes this three-dimensional vector as an XML message.
std::string YAML () const
Serializes this three-dimensional vector as a YAML message.
constexpr void operator+= (const Vector< NumericType > &vector) noexcept
constexpr void operator-= (const Vector< NumericType > &vector) noexcept
template<typename OtherNumericType >
constexpr void operator*= (const OtherNumericType number) noexcept
template<typename OtherNumericType >
constexpr void operator/= (const OtherNumericType number) noexcept
Static Public Member Functions
static constexpr Vector< NumericType > Zero ()
Statically creates a three-dimensional vector with its x, y, and z Cartesian components initialized to zero.
Private Attributes
std::array< NumericType, 3 > x_y_z_
Cartesian components of this three-dimensional vector.
Detailed Description
template<typename NumericType = double>
class PhQ::Vector< NumericType >
Three-dimensional Euclidean vector. Contains three components in Cartesian coordinates: x, y, and z. For a two-dimensional Euclidean vector in the XY plane, see PhQ::PlanarVector. For a three-dimensional Euclidean dyadic tensor, see PhQ::Dyad. For a three-dimensional symmetric Euclidean dyadic tensor, see PhQ::SymmetricDyad.
Definition at line 58 of file Vector.hpp.
Constructor & Destructor Documentation
Vector() [1/8]
template<typename NumericType = double> PhQ::Vector< NumericType >::Vector () default
Default constructor. Constructs a three-dimensional vector with uninitialized x, y, and z Cartesian components.
Vector() [2/8]
template<typename NumericType = double> constexpr PhQ::Vector< NumericType >::Vector (const NumericType x, const NumericType y, const NumericType z) inline constexpr
Constructor. Constructs a three-dimensional vector from the given x, y, and z Cartesian components.
Definition at line 70 of file Vector.hpp.
References PhQ::Vector< NumericType >::x(), PhQ::Vector< NumericType >::y(), and PhQ::Vector< NumericType >::z().
Vector() [3/8]
template<typename NumericType = double> constexpr PhQ::Vector< NumericType >::Vector (const std::array< NumericType, 3 > & x_y_z) inline explicit constexpr
Constructor. Constructs a three-dimensional vector from a given array representing its x, y, and z Cartesian components.
Definition at line 75 of file Vector.hpp.
Vector() [4/8]
template<typename NumericType = double> constexpr PhQ::Vector< NumericType >::Vector (const PlanarVector< NumericType > & planar_vector) inline explicit constexpr
Constructor. Constructs a three-dimensional vector from a given two-dimensional planar vector in the XY plane. This vector's z-component is initialized to zero.
Definition at line 79 of file Vector.hpp.
References PhQ::PlanarVector< NumericType >::x(), and PhQ::PlanarVector< NumericType >::y().
Vector() [5/8]
template<typename NumericType > constexpr PhQ::Vector< NumericType >::Vector (NumericType magnitude, const Direction< NumericType > & direction) inline constexpr
Constructor. Constructs a three-dimensional vector given a magnitude and a direction.
Definition at line 372 of file Direction.hpp.
References PhQ::DimensionlessVector< NumericType >::Value(), and PhQ::Vector< NumericType >::x_y_z_.
~Vector()
template<typename NumericType = double> PhQ::Vector< NumericType >::~Vector () default noexcept
Destructor. Destroys this three-dimensional vector.
Vector() [6/8]
template<typename NumericType = double> constexpr PhQ::Vector< NumericType >::Vector (const Vector< NumericType > & other) constexpr default
Copy constructor. Constructs a three-dimensional vector by copying another one.
Vector() [7/8]
template<typename NumericType = double> template<typename OtherNumericType > constexpr PhQ::Vector< NumericType >::Vector (const Vector< OtherNumericType > & other) inline explicit constexpr
Copy constructor. Constructs a three-dimensional vector by copying another one.
Definition at line 93 of file Vector.hpp.
Vector() [8/8]
template<typename NumericType = double> constexpr PhQ::Vector< NumericType >::Vector (Vector< NumericType > && other) constexpr default noexcept
Move constructor. Constructs a three-dimensional vector by moving another one.
Member Function Documentation
Angle() [1/2]
template<typename NumericType > Angle< NumericType > PhQ::Vector< NumericType >::Angle (const PhQ::Direction< NumericType > & direction) const inline
Returns the angle between this three-dimensional vector and a given direction.
Definition at line 412 of file Direction.hpp.
Angle() [2/2]
template<typename NumericType > PhQ::Angle< NumericType > PhQ::Vector< NumericType >::Angle (const Vector< NumericType > & vector) const inline
Returns the angle between this three-dimensional vector and another one.
Definition at line 409 of file Angle.hpp.
Cross() [1/2]
template<typename NumericType > constexpr Vector< NumericType > PhQ::Vector< NumericType >::Cross (const PhQ::Direction< NumericType > & direction) const inline constexpr
Returns the cross product (also known as the vector product) of this three-dimensional vector and a given direction.
Definition at line 388 of file Direction.hpp.
References PhQ::DimensionlessVector< NumericType >::Value().
Cross() [2/2]
template<typename NumericType = double> constexpr Vector<NumericType> PhQ::Vector< NumericType >::Cross (const Vector< NumericType > & vector) const inline constexpr
Returns the cross product (also known as the vector product) of this three-dimensional vector and another one.
Definition at line 228 of file Vector.hpp.
References PhQ::Vector< NumericType >::x_y_z_.
Referenced by PhQ::Direction< NumericType >::Cross().
Direction()
template<typename NumericType > PhQ::Direction< NumericType > PhQ::Vector< NumericType >::Direction inline
Returns the direction of this three-dimensional vector.
Definition at line 377 of file Direction.hpp.
Referenced by PhQ::Acceleration< NumericType >::Direction(), PhQ::Displacement< NumericType >::Direction(), PhQ::Force< NumericType >::Direction(), PhQ::HeatFlux< NumericType >::Direction(), PhQ::Position< NumericType >::Direction(), PhQ::TemperatureGradient< NumericType >::Direction(), PhQ::Traction< NumericType >::Direction(), PhQ::VectorArea< NumericType >::Direction(), and PhQ::Velocity< NumericType >::Direction().
Dot() [1/2]
template<typename NumericType > constexpr NumericType PhQ::Vector< NumericType >::Dot (const PhQ::Direction< NumericType > & direction) const inline constexpr noexcept
Returns the dot product (also known as the inner product or scalar product) of this three-dimensional vector and a given direction.
Definition at line 382 of file Direction.hpp.
Dot() [2/2]
template<typename NumericType = double> constexpr NumericType PhQ::Vector< NumericType >::Dot (const Vector< NumericType > & vector) const inline constexpr noexcept
Returns the dot product (also known as the inner product or scalar product) of this three-dimensional vector and another one.
Definition at line 216 of file Vector.hpp.
Referenced by PhQ::Direction< NumericType >::Dot().
Dyadic() [1/2]
template<typename NumericType > constexpr Dyad< NumericType > PhQ::Vector< NumericType >::Dyadic (const PhQ::Direction< NumericType > & direction) const inline constexpr
Returns the dyadic tensor product (also known as the outer product) of this three-dimensional vector and a given direction.
Definition at line 394 of file Direction.hpp.
References PhQ::DimensionlessVector< NumericType >::Value().
Dyadic() [2/2]
template<typename NumericType > constexpr Dyad< NumericType > PhQ::Vector< NumericType >::Dyadic (const Vector< NumericType > & vector) const inline constexpr
Returns the dyadic tensor product (also known as the outer product) of this three-dimensional vector and another one.
Definition at line 723 of file Dyad.hpp.
References PhQ::Vector< NumericType >::x_y_z_.
Referenced by PhQ::Direction< NumericType >::Dyadic().
JSON()
template<typename NumericType = double> std::string PhQ::Vector< NumericType >::JSON () const inline
Serializes this three-dimensional vector as a JSON message.
Definition at line 261 of file Vector.hpp.
References PhQ::Print(), and PhQ::Vector< NumericType >::x_y_z_.
Magnitude()
template<typename NumericType = double> NumericType PhQ::Vector< NumericType >::Magnitude () const inline noexcept
Returns the magnitude (also known as the L2 norm) of this three-dimensional vector.
Definition at line 207 of file Vector.hpp.
Referenced by PhQ::Acceleration< NumericType >::Magnitude(), PhQ::Displacement< NumericType >::Magnitude(), PhQ::Force< NumericType >::Magnitude(), PhQ::HeatFlux< NumericType >::Magnitude(), PhQ::Position< NumericType >::Magnitude(), PhQ::TemperatureGradient< NumericType >::Magnitude(), PhQ::Traction< NumericType >::Magnitude(), PhQ::VectorArea< NumericType >::Magnitude(), PhQ::Velocity< NumericType >::Magnitude(), and PhQ::Direction< NumericType >::Magnitude().
MagnitudeSquared()
template<typename NumericType = double> constexpr NumericType PhQ::Vector< NumericType >::MagnitudeSquared () const inline constexpr noexcept
Returns the square of the magnitude of this three-dimensional vector.
Definition at line 202 of file Vector.hpp.
References PhQ::Vector< NumericType >::x_y_z_.
Referenced by PhQ::Direction< NumericType >::MagnitudeSquared().
Mutable_x()
template<typename NumericType = double> constexpr NumericType& PhQ::Vector< NumericType >::Mutable_x () inline constexpr noexcept
Returns this three-dimensional vector's x Cartesian component as a mutable value.
Definition at line 158 of file Vector.hpp.
References PhQ::Vector< NumericType >::x_y_z_.
Mutable_x_y_z()
template<typename NumericType = double> constexpr std::array<NumericType, 3>& PhQ::Vector< NumericType >::Mutable_x_y_z () inline constexpr noexcept
Returns this three-dimensional vector's x, y, and z Cartesian components as a mutable array.
Definition at line 153 of file Vector.hpp.
References PhQ::Vector< NumericType >::x_y_z_.
Referenced by PhQ::ConvertInPlace().
Mutable_y()
template<typename NumericType = double> constexpr NumericType& PhQ::Vector< NumericType >::Mutable_y () inline constexpr noexcept
Returns this three-dimensional vector's y Cartesian component as a mutable value.
Definition at line 163 of file Vector.hpp.
References PhQ::Vector< NumericType >::x_y_z_.
Mutable_z()
template<typename NumericType = double> constexpr NumericType& PhQ::Vector< NumericType >::Mutable_z () inline constexpr noexcept
Returns this three-dimensional vector's z Cartesian component as a mutable value.
Definition at line 168 of file Vector.hpp.
References PhQ::Vector< NumericType >::x_y_z_.
operator*=()
template<typename NumericType = double> template<typename OtherNumericType > constexpr void PhQ::Vector< NumericType >::operator*= (const OtherNumericType number) inline constexpr noexcept
Definition at line 291 of file Vector.hpp.
References PhQ::Vector< NumericType >::x_y_z_.
operator+=()
template<typename NumericType = double> constexpr void PhQ::Vector< NumericType >::operator+= (const Vector< NumericType > & vector) inline constexpr noexcept
Definition at line 278 of file Vector.hpp.
References PhQ::Vector< NumericType >::x_y_z_.
operator-=()
template<typename NumericType = double> constexpr void PhQ::Vector< NumericType >::operator-= (const Vector< NumericType > & vector) inline constexpr noexcept
Definition at line 284 of file Vector.hpp.
References PhQ::Vector< NumericType >::x_y_z_.
operator/=()
template<typename NumericType = double> template<typename OtherNumericType > constexpr void PhQ::Vector< NumericType >::operator/= (const OtherNumericType number) inline constexpr noexcept
Definition at line 298 of file Vector.hpp.
References PhQ::Vector< NumericType >::x_y_z_.
operator=() [1/4]
template<typename NumericType = double> constexpr Vector<NumericType>& PhQ::Vector< NumericType >::operator= (const std::array< NumericType, 3 > & x_y_z) inline constexpr
Assignment operator. Assigns this three-dimensional vector by copying a given array representing its x, y, and z Cartesian components.
Definition at line 117 of file Vector.hpp.
References PhQ::Vector< NumericType >::x_y_z(), and PhQ::Vector< NumericType >::x_y_z_.
operator=() [2/4]
template<typename NumericType = double> constexpr Vector<NumericType>& PhQ::Vector< NumericType >::operator= (const Vector< NumericType > & other) constexpr default
Copy assignment operator. Assigns this three-dimensional vector by copying another one.
operator=() [3/4]
template<typename NumericType = double> template<typename OtherNumericType > constexpr Vector<NumericType>& PhQ::Vector< NumericType >::operator= (const Vector< OtherNumericType > & other) inline constexpr
Copy assignment operator. Assigns this three-dimensional vector by copying another one.
Definition at line 105 of file Vector.hpp.
References PhQ::Vector< NumericType >::x(), PhQ::Vector< NumericType >::x_y_z_, PhQ::Vector< NumericType >::y(), and PhQ::Vector< NumericType >::z().
operator=() [4/4]
template<typename NumericType = double> constexpr Vector<NumericType>& PhQ::Vector< NumericType >::operator= (Vector< NumericType > && other) constexpr default noexcept
Move assignment operator. Assigns this three-dimensional vector by moving another one.
Print()
template<typename NumericType = double> std::string PhQ::Vector< NumericType >::Print () const inline
Prints this three-dimensional vector as a string.
Definition at line 255 of file Vector.hpp.
References PhQ::Print(), and PhQ::Vector< NumericType >::x_y_z_.
Referenced by PhQ::operator<<().
Set_x()
template<typename NumericType = double> constexpr void PhQ::Vector< NumericType >::Set_x (const NumericType x) inline constexpr noexcept
Sets this three-dimensional vector's x Cartesian component to a given value.
Definition at line 187 of file Vector.hpp.
References PhQ::Vector< NumericType >::x(), and PhQ::Vector< NumericType >::x_y_z_.
Set_x_y_z() [1/2]
template<typename NumericType = double> constexpr void PhQ::Vector< NumericType >::Set_x_y_z (const NumericType x, const NumericType y, const NumericType z) inline constexpr noexcept
Sets this three-dimensional vector's x, y, and z Cartesian components to the given values.
Definition at line 180 of file Vector.hpp.
References PhQ::Vector< NumericType >::x(), PhQ::Vector< NumericType >::x_y_z_, PhQ::Vector< NumericType >::y(), and PhQ::Vector< NumericType >::z().
Set_x_y_z() [2/2]
template<typename NumericType = double> constexpr void PhQ::Vector< NumericType >::Set_x_y_z (const std::array< NumericType, 3 > & x_y_z) inline constexpr noexcept
Sets this three-dimensional vector's x, y, and z Cartesian components to the given values.
Definition at line 174 of file Vector.hpp.
References PhQ::Vector< NumericType >::x_y_z(), and PhQ::Vector< NumericType >::x_y_z_.
Set_y()
template<typename NumericType = double> constexpr void PhQ::Vector< NumericType >::Set_y (const NumericType y) inline constexpr noexcept
Sets this three-dimensional vector's y Cartesian component to a given value.
Definition at line 192 of file Vector.hpp.
References PhQ::Vector< NumericType >::x_y_z_, and PhQ::Vector< NumericType >::y().
Set_z()
template<typename NumericType = double> constexpr void PhQ::Vector< NumericType >::Set_z (const NumericType z) inline constexpr noexcept
Sets this three-dimensional vector's z Cartesian component to a given value.
Definition at line 197 of file Vector.hpp.
References PhQ::Vector< NumericType >::x_y_z_, and PhQ::Vector< NumericType >::z().
x()
template<typename NumericType = double> constexpr NumericType PhQ::Vector< NumericType >::x () const inline constexpr noexcept
Returns this three-dimensional vector's x Cartesian component.
Definition at line 137 of file Vector.hpp.
References PhQ::Vector< NumericType >::x_y_z_.
Referenced by PhQ::operator*(), PhQ::operator+(), PhQ::operator-(), PhQ::operator/(), PhQ::Vector< NumericType >::operator=(), PhQ::PlanarVector< NumericType >::PlanarVector(), PhQ::Vector< NumericType >::Set_x(), PhQ::Vector< NumericType >::Set_x_y_z(), PhQ::Vector< NumericType >::Vector(), PhQ::Acceleration< NumericType >::x(), PhQ::Direction< NumericType >::x(), PhQ::Displacement< NumericType >::x(), PhQ::Force< NumericType >::x(), PhQ::HeatFlux< NumericType >::x(), PhQ::Position< NumericType >::x(), PhQ::TemperatureGradient< NumericType >::x(), PhQ::Traction< NumericType >::x(), PhQ::VectorArea< NumericType >::x(), and PhQ::Velocity< NumericType >::x().
x_y_z()
template<typename NumericType = double> constexpr const std::array<NumericType, 3>& PhQ::Vector< NumericType >::x_y_z () const inline constexpr noexcept
Returns this three-dimensional vector's x, y, and z Cartesian components as an array.
Definition at line 132 of file Vector.hpp.
References PhQ::Vector< NumericType >::x_y_z_.
Referenced by PhQ::Convert(), PhQ::ConvertStatically(), PhQ::Vector< NumericType >::operator=(), PhQ::Direction< NumericType >::Set(), and PhQ::Vector< NumericType >::Set_x_y_z().
XML()
template<typename NumericType = double> std::string PhQ::Vector< NumericType >::XML () const inline
Serializes this three-dimensional vector as an XML message.
Definition at line 267 of file Vector.hpp.
References PhQ::Print(), and PhQ::Vector< NumericType >::x_y_z_.
y()
template<typename NumericType = double> constexpr NumericType PhQ::Vector< NumericType >::y () const inline constexpr noexcept
Returns this three-dimensional vector's y Cartesian component.
Definition at line 142 of file Vector.hpp.
References PhQ::Vector< NumericType >::x_y_z_.
Referenced by PhQ::operator*(), PhQ::operator+(), PhQ::operator-(), PhQ::operator/(), PhQ::Vector< NumericType >::operator=(), PhQ::PlanarVector< NumericType >::PlanarVector(), PhQ::Vector< NumericType >::Set_x_y_z(), PhQ::Vector< NumericType >::Set_y(), PhQ::Vector< NumericType >::Vector(), PhQ::Acceleration< NumericType >::y(), PhQ::Displacement< NumericType >::y(), PhQ::Force< NumericType >::y(), PhQ::HeatFlux< NumericType >::y(), PhQ::Position< NumericType >::y(), PhQ::TemperatureGradient< NumericType >::y(), PhQ::Traction< NumericType >::y(), PhQ::VectorArea< NumericType >::y(), and PhQ::Velocity< NumericType >::y().
YAML()
template<typename NumericType = double> std::string PhQ::Vector< NumericType >::YAML () const inline
Serializes this three-dimensional vector as a YAML message.
Definition at line 273 of file Vector.hpp.
References PhQ::Print(), and PhQ::Vector< NumericType >::x_y_z_.
z()
template<typename NumericType = double> constexpr NumericType PhQ::Vector< NumericType >::z () const inline constexpr noexcept
Returns this three-dimensional vector's z Cartesian component.
Definition at line 147 of file Vector.hpp.
References PhQ::Vector< NumericType >::x_y_z_.
Referenced by PhQ::operator*(), PhQ::operator+(), PhQ::operator-(), PhQ::operator/(), PhQ::Vector< NumericType >::operator=(), PhQ::Vector< NumericType >::Set_x_y_z(), PhQ::Vector< NumericType >::Set_z(), PhQ::Vector< NumericType >::Vector(), PhQ::Acceleration< NumericType >::z(), PhQ::Direction< NumericType >::z(), PhQ::Displacement< NumericType >::z(), PhQ::Force< NumericType >::z(), PhQ::HeatFlux< NumericType >::z(), PhQ::Position< NumericType >::z(), PhQ::TemperatureGradient< NumericType >::z(), PhQ::Traction< NumericType >::z(), PhQ::VectorArea< NumericType >::z(), and PhQ::Velocity< NumericType >::z().
Zero()
template<typename NumericType = double> static constexpr Vector<NumericType> PhQ::Vector< NumericType >::Zero () inline static constexpr
Statically creates a three-dimensional vector with its x, y, and z Cartesian components initialized to zero.
Definition at line 124 of file Vector.hpp.
Referenced by PhQ::Acceleration< NumericType >::Zero(), PhQ::Displacement< NumericType >::Zero(), PhQ::Force< NumericType >::Zero(), PhQ::HeatFlux< NumericType >::Zero(), PhQ::Position< NumericType >::Zero(), PhQ::TemperatureGradient< NumericType >::Zero(), PhQ::Traction< NumericType >::Zero(), PhQ::VectorArea< NumericType >::Zero(), and PhQ::Velocity< NumericType >::Zero().
Member Data Documentation
x_y_z_
template<typename NumericType = double> std::array<NumericType, 3> PhQ::Vector< NumericType >::x_y_z_ private
Cartesian components of this three-dimensional vector.
Definition at line 306 of file Vector.hpp.
Referenced by PhQ::PlanarVector< double >::Cross(), PhQ::Vector< NumericType >::Cross(), PhQ::Vector< NumericType >::Dyadic(), PhQ::Vector< NumericType >::JSON(), PhQ::Vector< NumericType >::MagnitudeSquared(), PhQ::Vector< NumericType >::Mutable_x(), PhQ::Vector< NumericType >::Mutable_x_y_z(), PhQ::Vector< NumericType >::Mutable_y(), PhQ::Vector< NumericType >::Mutable_z(), PhQ::Vector< NumericType >::operator*=(), PhQ::Vector< NumericType >::operator+=(), PhQ::Vector< NumericType >::operator-=(), PhQ::Vector< NumericType >::operator/=(), PhQ::Vector< NumericType >::operator=(), PhQ::Vector< NumericType >::Print(), PhQ::Vector< NumericType >::Set_x(), PhQ::Vector< NumericType >::Set_x_y_z(), PhQ::Vector< NumericType >::Set_y(), PhQ::Vector< NumericType >::Set_z(), PhQ::Vector< NumericType >::Vector(), PhQ::Vector< NumericType >::x(), PhQ::Vector< NumericType >::x_y_z(), PhQ::Vector< NumericType >::XML(), PhQ::Vector< NumericType >::y(), PhQ::Vector< NumericType >::YAML(), and PhQ::Vector< NumericType >::z().
The documentation for this class was generated from the following files:
PhQ/PlanarVector.hpp
PhQ/Vector.hpp
PhQ/Angle.hpp
PhQ/Direction.hpp
PhQ/Dyad.hpp