Physical Quantities: PhQ::VelocityGradient< NumericType > Class Template Reference
PhQ::VelocityGradient< NumericType > Class Template Reference
Three-dimensional Euclidean velocity gradient dyadic tensor. Gradient of the velocity vector. May be symmetric or asymmetric. Contains nine components in Cartesian coordinates: xx, xy, xz, yx, yy, yz, zx, zy, and zz. For the scalar components or resultants of a velocity gradient tensor, see PhQ::ScalarVelocityGradient. Can also represent the time rate of change of a displacement gradient; see PhQ::DisplacementGradient, PhQ::Time, and PhQ::Frequency.
#include "VelocityGradient.hpp"
Public Member Functions
VelocityGradient ()=default
Default constructor. Constructs a velocity gradient tensor with an uninitialized value.
VelocityGradient (const Dyad< NumericType > &value, const Unit::Frequency &unit)
Constructor. Constructs a velocity gradient tensor with a given value expressed in a given frequency unit.
VelocityGradient (const ScalarVelocityGradient< NumericType > &xx, const ScalarVelocityGradient< NumericType > &xy, const ScalarVelocityGradient< NumericType > &xz, const ScalarVelocityGradient< NumericType > &yx, const ScalarVelocityGradient< NumericType > &yy, const ScalarVelocityGradient< NumericType > &yz, const ScalarVelocityGradient< NumericType > &zx, const ScalarVelocityGradient< NumericType > &zy, const ScalarVelocityGradient< NumericType > &zz)
Constructor. Constructs a velocity gradient tensor from a given set of scalar velocity gradient components.
constexpr VelocityGradient (const DisplacementGradient< NumericType > &displacement_gradient, const Time< NumericType > &time)
Constructor. Constructs a velocity gradient tensor from a given displacement gradient tensor and time using the definition of speed.
constexpr VelocityGradient (const DisplacementGradient< NumericType > &displacement_gradient, const Frequency< NumericType > &frequency)
Constructor. Constructs a velocity gradient tensor from a given displacement gradient tensor and frequency using the definition of speed.
~VelocityGradient () noexcept=default
Destructor. Destroys this velocity gradient tensor.
constexpr VelocityGradient (const VelocityGradient< NumericType > &other)=default
Copy constructor. Constructs a velocity gradient tensor by copying another one.
template<typename OtherNumericType >
constexpr VelocityGradient (const VelocityGradient< OtherNumericType > &other)
Copy constructor. Constructs a velocity gradient tensor by copying another one.
constexpr VelocityGradient (VelocityGradient< NumericType > &&other) noexcept=default
Move constructor. Constructs a velocity gradient tensor by moving another one.
constexpr VelocityGradient< NumericType > & operator= (const VelocityGradient< NumericType > &other)=default
Copy assignment operator. Assigns this velocity gradient tensor by copying another one.
template<typename OtherNumericType >
constexpr VelocityGradient< NumericType > & operator= (const VelocityGradient< OtherNumericType > &other)
Copy assignment operator. Assigns this velocity gradient tensor by copying another one.
constexpr VelocityGradient< NumericType > & operator= (VelocityGradient< NumericType > &&other) noexcept=default
Move assignment operator. Assigns this velocity gradient tensor by moving another one.
constexpr ScalarVelocityGradient< NumericType > xx () const noexcept
Returns the xx Cartesian component of this velocity gradient tensor.
constexpr ScalarVelocityGradient< NumericType > xy () const noexcept
Returns the xy Cartesian component of this velocity gradient tensor.
constexpr ScalarVelocityGradient< NumericType > xz () const noexcept
Returns the xz Cartesian component of this velocity gradient tensor.
constexpr ScalarVelocityGradient< NumericType > yx () const noexcept
Returns the yx Cartesian component of this velocity gradient tensor.
constexpr ScalarVelocityGradient< NumericType > yy () const noexcept
Returns the yy Cartesian component of this velocity gradient tensor.
constexpr ScalarVelocityGradient< NumericType > yz () const noexcept
Returns the yz Cartesian component of this velocity gradient tensor.
constexpr ScalarVelocityGradient< NumericType > zx () const noexcept
Returns the zx Cartesian component of this velocity gradient tensor.
constexpr ScalarVelocityGradient< NumericType > zy () const noexcept
Returns the zy Cartesian component of this velocity gradient tensor.
constexpr ScalarVelocityGradient< NumericType > zz () const noexcept
Returns the zz Cartesian component of this velocity gradient tensor.
constexpr PhQ::StrainRate< NumericType > StrainRate () const
Creates a strain rate tensor from this velocity gradient tensor using the definition of the strain rate tensor.
constexpr VelocityGradient< NumericType > operator+ (const VelocityGradient< NumericType > &velocity_gradient) const
constexpr VelocityGradient< NumericType > operator- (const VelocityGradient< NumericType > &velocity_gradient) const
constexpr VelocityGradient< NumericType > operator* (const NumericType number) const
constexpr DisplacementGradient< NumericType > operator* (const Time< NumericType > &time) const
constexpr VelocityGradient< NumericType > operator/ (const NumericType number) const
constexpr DisplacementGradient< NumericType > operator/ (const Frequency< NumericType > &frequency) const
constexpr void operator+= (const VelocityGradient< NumericType > &velocity_gradient) noexcept
constexpr void operator-= (const VelocityGradient< NumericType > &velocity_gradient) noexcept
constexpr void operator*= (const NumericType number) noexcept
constexpr void operator/= (const NumericType number) noexcept
constexpr const PhQ::Dyad< NumericType > & Value () const noexcept
Value of this physical quantity expressed in its standard unit of measure.
PhQ::Dyad< NumericType > Value (const UnitType unit) const
Value of this physical quantity expressed in a given unit of measure.
template<UnitType NewUnit>
constexpr PhQ::Dyad< NumericType > StaticValue () const
Value of this physical quantity expressed in a given unit of measure. This method can be evaluated statically at compile-time.
constexpr PhQ::Dyad< NumericType > & MutableValue () noexcept
Returns the value of this physical quantity expressed in its standard unit of measure as a mutable value.
constexpr void SetValue (const PhQ::Dyad< NumericType > &value) noexcept
Sets the value of this physical quantity expressed in its standard unit of measure to the given value.
std::string Print () const
Prints this physical quantity as a string. This physical quantity's value is expressed in its standard unit of measure.
std::string Print (const UnitType unit) const
Prints this physical quantity as a string. This physical quantity's value is expressed in the given unit of measure.
std::string JSON () const
Serializes this physical quantity as a JSON message. This physical quantity's value is expressed in its standard unit of measure.
std::string JSON (const UnitType unit) const
Serializes this physical quantity as a JSON message. This physical quantity's value is expressed in the given unit of measure.
std::string XML () const
Serializes this physical quantity as an XML message. This physical quantity's value is expressed in its standard unit of measure.
std::string XML (const UnitType unit) const
Serializes this physical quantity as an XML message. This physical quantity's value is expressed in the given unit of measure.
std::string YAML () const
Serializes this physical quantity as a YAML message. This physical quantity's value is expressed in its standard unit of measure.
std::string YAML (const UnitType unit) const
Serializes this physical quantity as a YAML message. This physical quantity's value is expressed in the given unit of measure.
Static Public Member Functions
static constexpr VelocityGradient< NumericType > Zero ()
Statically creates a velocity gradient tensor of zero.
template<Unit::Frequency Unit>
static constexpr VelocityGradient< NumericType > Create (const NumericType xx, const NumericType xy, const NumericType xz, const NumericType yx, const NumericType yy, const NumericType yz, const NumericType zx, const NumericType zy, const NumericType zz)
Statically creates a velocity gradient tensor from the given xx, xy, xz, yx, yy, yz, zx,zy, and zz Cartesian components expressed in a given frequency unit.
template<Unit::Frequency Unit>
static constexpr VelocityGradient< NumericType > Create (const std::array< NumericType, 9 > &xx_xy_xz_yx_yy_yz_zx_zy_zz)
Statically creates a velocity gradient tensor from the given xx, xy, xz, yx, yy, yz, zx,zy, and zz Cartesian components expressed in a given frequency unit.
template<Unit::Frequency Unit>
static constexpr VelocityGradient< NumericType > Create (const Dyad< NumericType > &value)
Statically creates a velocity gradient tensor with a given value expressed in a given frequency unit.
static constexpr const PhQ::Dimensions & Dimensions ()
Physical dimension set of this physical quantity.
static constexpr UnitType Unit ()
Standard unit of measure for this physical quantity. This physical quantity's value is stored internally in this unit of measure.
Protected Attributes
PhQ::Dyad< NumericType > value
Value of this physical quantity expressed in its standard unit of measure.
Private Member Functions
constexpr VelocityGradient (const Dyad< NumericType > &value)
Constructor. Constructs a velocity gradient tensor with a given value expressed in the standard frequency unit.
Detailed Description
template<typename NumericType = double>
class PhQ::VelocityGradient< NumericType >
Three-dimensional Euclidean velocity gradient dyadic tensor. Gradient of the velocity vector. May be symmetric or asymmetric. Contains nine components in Cartesian coordinates: xx, xy, xz, yx, yy, yz, zx, zy, and zz. For the scalar components or resultants of a velocity gradient tensor, see PhQ::ScalarVelocityGradient. Can also represent the time rate of change of a displacement gradient; see PhQ::DisplacementGradient, PhQ::Time, and PhQ::Frequency.
Definition at line 50 of file VelocityGradient.hpp.
Constructor & Destructor Documentation
VelocityGradient() [1/9]
template<typename NumericType = double> PhQ::VelocityGradient< NumericType >::VelocityGradient () default
Default constructor. Constructs a velocity gradient tensor with an uninitialized value.
VelocityGradient() [2/9]
template<typename NumericType = double> PhQ::VelocityGradient< NumericType >::VelocityGradient (const Dyad< NumericType > & value, const Unit::Frequency & unit) inline
Constructor. Constructs a velocity gradient tensor with a given value expressed in a given frequency unit.
Definition at line 57 of file VelocityGradient.hpp.
VelocityGradient() [3/9]
template<typename NumericType = double> PhQ::VelocityGradient< NumericType >::VelocityGradient (const ScalarVelocityGradient< NumericType > & xx, const ScalarVelocityGradient< NumericType > & xy, const ScalarVelocityGradient< NumericType > & xz, const ScalarVelocityGradient< NumericType > & yx, const ScalarVelocityGradient< NumericType > & yy, const ScalarVelocityGradient< NumericType > & yz, const ScalarVelocityGradient< NumericType > & zx, const ScalarVelocityGradient< NumericType > & zy, const ScalarVelocityGradient< NumericType > & zz) inline
Constructor. Constructs a velocity gradient tensor from a given set of scalar velocity gradient components.
Definition at line 62 of file VelocityGradient.hpp.
References PhQ::VelocityGradient< NumericType >::xx(), PhQ::VelocityGradient< NumericType >::xy(), PhQ::VelocityGradient< NumericType >::xz(), PhQ::VelocityGradient< NumericType >::yx(), PhQ::VelocityGradient< NumericType >::yy(), PhQ::VelocityGradient< NumericType >::yz(), PhQ::VelocityGradient< NumericType >::zx(), PhQ::VelocityGradient< NumericType >::zy(), and PhQ::VelocityGradient< NumericType >::zz().
VelocityGradient() [4/9]
template<typename NumericType = double> constexpr PhQ::VelocityGradient< NumericType >::VelocityGradient (const DisplacementGradient< NumericType > & displacement_gradient, const Time< NumericType > & time) inline constexpr
Constructor. Constructs a velocity gradient tensor from a given displacement gradient tensor and time using the definition of speed.
Definition at line 73 of file VelocityGradient.hpp.
VelocityGradient() [5/9]
template<typename NumericType = double> constexpr PhQ::VelocityGradient< NumericType >::VelocityGradient (const DisplacementGradient< NumericType > & displacement_gradient, const Frequency< NumericType > & frequency) inline constexpr
Constructor. Constructs a velocity gradient tensor from a given displacement gradient tensor and frequency using the definition of speed.
Definition at line 79 of file VelocityGradient.hpp.
~VelocityGradient()
template<typename NumericType = double> PhQ::VelocityGradient< NumericType >::~VelocityGradient () default noexcept
Destructor. Destroys this velocity gradient tensor.
VelocityGradient() [6/9]
template<typename NumericType = double> constexpr PhQ::VelocityGradient< NumericType >::VelocityGradient (const VelocityGradient< NumericType > & other) constexpr default
Copy constructor. Constructs a velocity gradient tensor by copying another one.
VelocityGradient() [7/9]
template<typename NumericType = double> template<typename OtherNumericType > constexpr PhQ::VelocityGradient< NumericType >::VelocityGradient (const VelocityGradient< OtherNumericType > & other) inline explicit constexpr
Copy constructor. Constructs a velocity gradient tensor by copying another one.
Definition at line 91 of file VelocityGradient.hpp.
VelocityGradient() [8/9]
template<typename NumericType = double> constexpr PhQ::VelocityGradient< NumericType >::VelocityGradient (VelocityGradient< NumericType > && other) constexpr default noexcept
Move constructor. Constructs a velocity gradient tensor by moving another one.
VelocityGradient() [9/9]
template<typename NumericType = double> constexpr PhQ::VelocityGradient< NumericType >::VelocityGradient (const Dyad< NumericType > & value) inline explicit constexpr private
Constructor. Constructs a velocity gradient tensor with a given value expressed in the standard frequency unit.
Definition at line 246 of file VelocityGradient.hpp.
Member Function Documentation
Create() [1/3]
template<typename NumericType = double> template<Unit::Frequency Unit> static constexpr VelocityGradient< NumericType > PhQ::VelocityGradient< NumericType >::Create (const Dyad< NumericType > & value) inline static constexpr
Statically creates a velocity gradient tensor with a given value expressed in a given frequency unit.
Definition at line 143 of file VelocityGradient.hpp.
References PhQ::DimensionalDyad< UnitType, NumericType >::value.
Create() [2/3]
template<typename NumericType = double> template<Unit::Frequency Unit> static constexpr VelocityGradient< NumericType > PhQ::VelocityGradient< NumericType >::Create (const NumericType xx, const NumericType xy, const NumericType xz, const NumericType yx, const NumericType yy, const NumericType yz, const NumericType zx, const NumericType zy, const NumericType zz) inline static constexpr
Statically creates a velocity gradient tensor from the given xx, xy, xz, yx, yy, yz, zx,zy, and zz Cartesian components expressed in a given frequency unit.
Definition at line 121 of file VelocityGradient.hpp.
References PhQ::VelocityGradient< NumericType >::xx(), PhQ::VelocityGradient< NumericType >::xy(), PhQ::VelocityGradient< NumericType >::xz(), PhQ::VelocityGradient< NumericType >::yx(), PhQ::VelocityGradient< NumericType >::yy(), PhQ::VelocityGradient< NumericType >::yz(), PhQ::VelocityGradient< NumericType >::zx(), PhQ::VelocityGradient< NumericType >::zy(), and PhQ::VelocityGradient< NumericType >::zz().
Create() [3/3]
template<typename NumericType = double> template<Unit::Frequency Unit> static constexpr VelocityGradient< NumericType > PhQ::VelocityGradient< NumericType >::Create (const std::array< NumericType, 9 > & xx_xy_xz_yx_yy_yz_zx_zy_zz) inline static constexpr
Statically creates a velocity gradient tensor from the given xx, xy, xz, yx, yy, yz, zx,zy, and zz Cartesian components expressed in a given frequency unit.
Definition at line 133 of file VelocityGradient.hpp.
Dimensions()
template<typename UnitType , typename NumericType = double> static constexpr const PhQ::Dimensions & PhQ::DimensionalDyad< UnitType, NumericType >::Dimensions () inline static constexpr inherited
Physical dimension set of this physical quantity.
Definition at line 50 of file DimensionalDyad.hpp.
JSON() [1/2]
template<typename UnitType , typename NumericType = double> std::string PhQ::DimensionalDyad< UnitType, NumericType >::JSON () const inline inherited
Serializes this physical quantity as a JSON message. This physical quantity's value is expressed in its standard unit of measure.
Definition at line 103 of file DimensionalDyad.hpp.
References PhQ::Abbreviation(), and PhQ::DimensionalDyad< UnitType, NumericType >::value.
Referenced by PhQ::DimensionalDyad< UnitType, NumericType >::JSON().
JSON() [2/2]
template<typename UnitType , typename NumericType = double> std::string PhQ::DimensionalDyad< UnitType, NumericType >::JSON (const UnitType unit) const inline inherited
Serializes this physical quantity as a JSON message. This physical quantity's value is expressed in the given unit of measure.
Definition at line 113 of file DimensionalDyad.hpp.
References PhQ::Abbreviation(), PhQ::DimensionalDyad< UnitType, NumericType >::JSON(), and PhQ::DimensionalDyad< UnitType, NumericType >::Value().
MutableValue()
template<typename UnitType , typename NumericType = double> constexpr PhQ::Dyad< NumericType > & PhQ::DimensionalDyad< UnitType, NumericType >::MutableValue () inline constexpr noexcept inherited
Returns the value of this physical quantity expressed in its standard unit of measure as a mutable value.
Definition at line 79 of file DimensionalDyad.hpp.
References PhQ::DimensionalDyad< UnitType, NumericType >::value.
operator*() [1/2]
template<typename NumericType = double> constexpr VelocityGradient< NumericType > PhQ::VelocityGradient< NumericType >::operator* (const NumericType number) const inline constexpr
Definition at line 210 of file VelocityGradient.hpp.
References PhQ::DimensionalDyad< UnitType, NumericType >::value.
operator*() [2/2]
template<typename NumericType = double> constexpr DisplacementGradient< NumericType > PhQ::VelocityGradient< NumericType >::operator* (const Time< NumericType > & time) const inline constexpr
Definition at line 214 of file VelocityGradient.hpp.
operator*=()
template<typename NumericType = double> constexpr void PhQ::VelocityGradient< NumericType >::operator*= (const NumericType number) inline constexpr noexcept
Definition at line 235 of file VelocityGradient.hpp.
References PhQ::DimensionalDyad< UnitType, NumericType >::value.
operator+()
template<typename NumericType = double> constexpr VelocityGradient< NumericType > PhQ::VelocityGradient< NumericType >::operator+ (const VelocityGradient< NumericType > & velocity_gradient) const inline constexpr
Definition at line 200 of file VelocityGradient.hpp.
References PhQ::DimensionalDyad< UnitType, NumericType >::value.
operator+=()
template<typename NumericType = double> constexpr void PhQ::VelocityGradient< NumericType >::operator+= (const VelocityGradient< NumericType > & velocity_gradient) inline constexpr noexcept
Definition at line 227 of file VelocityGradient.hpp.
References PhQ::DimensionalDyad< UnitType, NumericType >::value.
operator-()
template<typename NumericType = double> constexpr VelocityGradient< NumericType > PhQ::VelocityGradient< NumericType >::operator- (const VelocityGradient< NumericType > & velocity_gradient) const inline constexpr
Definition at line 205 of file VelocityGradient.hpp.
References PhQ::DimensionalDyad< UnitType, NumericType >::value.
operator-=()
template<typename NumericType = double> constexpr void PhQ::VelocityGradient< NumericType >::operator-= (const VelocityGradient< NumericType > & velocity_gradient) inline constexpr noexcept
Definition at line 231 of file VelocityGradient.hpp.
References PhQ::DimensionalDyad< UnitType, NumericType >::value.
operator/() [1/2]
template<typename NumericType = double> constexpr DisplacementGradient< NumericType > PhQ::VelocityGradient< NumericType >::operator/ (const Frequency< NumericType > & frequency) const inline constexpr
Definition at line 222 of file VelocityGradient.hpp.
operator/() [2/2]
template<typename NumericType = double> constexpr VelocityGradient< NumericType > PhQ::VelocityGradient< NumericType >::operator/ (const NumericType number) const inline constexpr
Definition at line 218 of file VelocityGradient.hpp.
References PhQ::DimensionalDyad< UnitType, NumericType >::value.
operator/=()
template<typename NumericType = double> constexpr void PhQ::VelocityGradient< NumericType >::operator/= (const NumericType number) inline constexpr noexcept
Definition at line 239 of file VelocityGradient.hpp.
References PhQ::DimensionalDyad< UnitType, NumericType >::value.
operator=() [1/3]
template<typename NumericType = double> constexpr VelocityGradient< NumericType > & PhQ::VelocityGradient< NumericType >::operator= (const VelocityGradient< NumericType > & other) constexpr default
Copy assignment operator. Assigns this velocity gradient tensor by copying another one.
operator=() [2/3]
template<typename NumericType = double> template<typename OtherNumericType > constexpr VelocityGradient< NumericType > & PhQ::VelocityGradient< NumericType >::operator= (const VelocityGradient< OtherNumericType > & other) inline constexpr
Copy assignment operator. Assigns this velocity gradient tensor by copying another one.
Definition at line 103 of file VelocityGradient.hpp.
References PhQ::DimensionalDyad< UnitType, NumericType >::Value(), and PhQ::DimensionalDyad< UnitType, NumericType >::value.
operator=() [3/3]
template<typename NumericType = double> constexpr VelocityGradient< NumericType > & PhQ::VelocityGradient< NumericType >::operator= (VelocityGradient< NumericType > && other) constexpr default noexcept
Move assignment operator. Assigns this velocity gradient tensor by moving another one.
Print() [1/2]
template<typename UnitType , typename NumericType = double> std::string PhQ::DimensionalDyad< UnitType, NumericType >::Print () const inline inherited
Prints this physical quantity as a string. This physical quantity's value is expressed in its standard unit of measure.
Definition at line 91 of file DimensionalDyad.hpp.
References PhQ::Abbreviation(), and PhQ::DimensionalDyad< UnitType, NumericType >::value.
Referenced by PhQ::operator<<().
Print() [2/2]
template<typename UnitType , typename NumericType = double> std::string PhQ::DimensionalDyad< UnitType, NumericType >::Print (const UnitType unit) const inline inherited
Prints this physical quantity as a string. This physical quantity's value is expressed in the given unit of measure.
Definition at line 97 of file DimensionalDyad.hpp.
References PhQ::Abbreviation(), and PhQ::DimensionalDyad< UnitType, NumericType >::Value().
SetValue()
template<typename UnitType , typename NumericType = double> constexpr void PhQ::DimensionalDyad< UnitType, NumericType >::SetValue (const PhQ::Dyad< NumericType > & value) inline constexpr noexcept inherited
Sets the value of this physical quantity expressed in its standard unit of measure to the given value.
Definition at line 85 of file DimensionalDyad.hpp.
References PhQ::DimensionalDyad< UnitType, NumericType >::value.
StaticValue()
template<typename UnitType , typename NumericType = double> template<UnitType NewUnit> constexpr PhQ::Dyad< NumericType > PhQ::DimensionalDyad< UnitType, NumericType >::StaticValue () const inline constexpr inherited
Value of this physical quantity expressed in a given unit of measure. This method can be evaluated statically at compile-time.
Definition at line 73 of file DimensionalDyad.hpp.
References PhQ::DimensionalDyad< UnitType, NumericType >::value.
StrainRate()
template<typename NumericType = double> constexpr PhQ::StrainRate< NumericType > PhQ::VelocityGradient< NumericType >::StrainRate () const inline constexpr
Creates a strain rate tensor from this velocity gradient tensor using the definition of the strain rate tensor.
Definition at line 196 of file VelocityGradient.hpp.
Unit()
template<typename UnitType , typename NumericType = double> static constexpr UnitType PhQ::DimensionalDyad< UnitType, NumericType >::Unit () inline static constexpr inherited
Standard unit of measure for this physical quantity. This physical quantity's value is stored internally in this unit of measure.
Definition at line 56 of file DimensionalDyad.hpp.
Value() [1/2]
template<typename UnitType , typename NumericType = double> constexpr const PhQ::Dyad< NumericType > & PhQ::DimensionalDyad< UnitType, NumericType >::Value () const inline constexpr noexcept inherited
Value of this physical quantity expressed in its standard unit of measure.
Definition at line 61 of file DimensionalDyad.hpp.
References PhQ::DimensionalDyad< UnitType, NumericType >::value.
Referenced by PhQ::DimensionalDyad< UnitType, NumericType >::JSON(), PhQ::DimensionalDyad< UnitType, NumericType >::operator=(), PhQ::VelocityGradient< NumericType >::operator=(), PhQ::operator==(), PhQ::DimensionalDyad< UnitType, NumericType >::Print(), PhQ::StrainRate< NumericType >::StrainRate(), PhQ::DimensionalDyad< UnitType, NumericType >::XML(), and PhQ::DimensionalDyad< UnitType, NumericType >::YAML().
Value() [2/2]
template<typename UnitType , typename NumericType = double> PhQ::Dyad< NumericType > PhQ::DimensionalDyad< UnitType, NumericType >::Value (const UnitType unit) const inline inherited
Value of this physical quantity expressed in a given unit of measure.
Definition at line 66 of file DimensionalDyad.hpp.
References PhQ::Convert(), and PhQ::DimensionalDyad< UnitType, NumericType >::value.
XML() [1/2]
template<typename UnitType , typename NumericType = double> std::string PhQ::DimensionalDyad< UnitType, NumericType >::XML () const inline inherited
Serializes this physical quantity as an XML message. This physical quantity's value is expressed in its standard unit of measure.
Definition at line 123 of file DimensionalDyad.hpp.
References PhQ::Abbreviation(), and PhQ::DimensionalDyad< UnitType, NumericType >::value.
Referenced by PhQ::DimensionalDyad< UnitType, NumericType >::XML().
XML() [2/2]
template<typename UnitType , typename NumericType = double> std::string PhQ::DimensionalDyad< UnitType, NumericType >::XML (const UnitType unit) const inline inherited
Serializes this physical quantity as an XML message. This physical quantity's value is expressed in the given unit of measure.
Definition at line 133 of file DimensionalDyad.hpp.
References PhQ::Abbreviation(), PhQ::DimensionalDyad< UnitType, NumericType >::Value(), and PhQ::DimensionalDyad< UnitType, NumericType >::XML().
xx()
template<typename NumericType = double> constexpr ScalarVelocityGradient< NumericType > PhQ::VelocityGradient< NumericType >::xx () const inline constexpr noexcept
Returns the xx Cartesian component of this velocity gradient tensor.
Definition at line 150 of file VelocityGradient.hpp.
References PhQ::DimensionalDyad< UnitType, NumericType >::value.
Referenced by PhQ::VelocityGradient< NumericType >::Create(), and PhQ::VelocityGradient< NumericType >::VelocityGradient().
xy()
template<typename NumericType = double> constexpr ScalarVelocityGradient< NumericType > PhQ::VelocityGradient< NumericType >::xy () const inline constexpr noexcept
Returns the xy Cartesian component of this velocity gradient tensor.
Definition at line 155 of file VelocityGradient.hpp.
References PhQ::DimensionalDyad< UnitType, NumericType >::value.
Referenced by PhQ::VelocityGradient< NumericType >::Create(), and PhQ::VelocityGradient< NumericType >::VelocityGradient().
xz()
template<typename NumericType = double> constexpr ScalarVelocityGradient< NumericType > PhQ::VelocityGradient< NumericType >::xz () const inline constexpr noexcept
Returns the xz Cartesian component of this velocity gradient tensor.
Definition at line 160 of file VelocityGradient.hpp.
References PhQ::DimensionalDyad< UnitType, NumericType >::value.
Referenced by PhQ::VelocityGradient< NumericType >::Create(), and PhQ::VelocityGradient< NumericType >::VelocityGradient().
YAML() [1/2]
template<typename UnitType , typename NumericType = double> std::string PhQ::DimensionalDyad< UnitType, NumericType >::YAML () const inline inherited
Serializes this physical quantity as a YAML message. This physical quantity's value is expressed in its standard unit of measure.
Definition at line 143 of file DimensionalDyad.hpp.
References PhQ::Abbreviation(), and PhQ::DimensionalDyad< UnitType, NumericType >::value.
Referenced by PhQ::DimensionalDyad< UnitType, NumericType >::YAML().
YAML() [2/2]
template<typename UnitType , typename NumericType = double> std::string PhQ::DimensionalDyad< UnitType, NumericType >::YAML (const UnitType unit) const inline inherited
Serializes this physical quantity as a YAML message. This physical quantity's value is expressed in the given unit of measure.
Definition at line 153 of file DimensionalDyad.hpp.
References PhQ::Abbreviation(), PhQ::DimensionalDyad< UnitType, NumericType >::Value(), and PhQ::DimensionalDyad< UnitType, NumericType >::YAML().
yx()
template<typename NumericType = double> constexpr ScalarVelocityGradient< NumericType > PhQ::VelocityGradient< NumericType >::yx () const inline constexpr noexcept
Returns the yx Cartesian component of this velocity gradient tensor.
Definition at line 165 of file VelocityGradient.hpp.
References PhQ::DimensionalDyad< UnitType, NumericType >::value.
Referenced by PhQ::VelocityGradient< NumericType >::Create(), and PhQ::VelocityGradient< NumericType >::VelocityGradient().
yy()
template<typename NumericType = double> constexpr ScalarVelocityGradient< NumericType > PhQ::VelocityGradient< NumericType >::yy () const inline constexpr noexcept
Returns the yy Cartesian component of this velocity gradient tensor.
Definition at line 170 of file VelocityGradient.hpp.
References PhQ::DimensionalDyad< UnitType, NumericType >::value.
Referenced by PhQ::VelocityGradient< NumericType >::Create(), and PhQ::VelocityGradient< NumericType >::VelocityGradient().
yz()
template<typename NumericType = double> constexpr ScalarVelocityGradient< NumericType > PhQ::VelocityGradient< NumericType >::yz () const inline constexpr noexcept
Returns the yz Cartesian component of this velocity gradient tensor.
Definition at line 175 of file VelocityGradient.hpp.
References PhQ::DimensionalDyad< UnitType, NumericType >::value.
Referenced by PhQ::VelocityGradient< NumericType >::Create(), and PhQ::VelocityGradient< NumericType >::VelocityGradient().
Zero()
template<typename NumericType = double> static constexpr VelocityGradient< NumericType > PhQ::VelocityGradient< NumericType >::Zero () inline static constexpr
Statically creates a velocity gradient tensor of zero.
Definition at line 114 of file VelocityGradient.hpp.
References PhQ::Dyad< NumericType >::Zero().
zx()
template<typename NumericType = double> constexpr ScalarVelocityGradient< NumericType > PhQ::VelocityGradient< NumericType >::zx () const inline constexpr noexcept
Returns the zx Cartesian component of this velocity gradient tensor.
Definition at line 180 of file VelocityGradient.hpp.
References PhQ::DimensionalDyad< UnitType, NumericType >::value.
Referenced by PhQ::VelocityGradient< NumericType >::Create(), and PhQ::VelocityGradient< NumericType >::VelocityGradient().
zy()
template<typename NumericType = double> constexpr ScalarVelocityGradient< NumericType > PhQ::VelocityGradient< NumericType >::zy () const inline constexpr noexcept
Returns the zy Cartesian component of this velocity gradient tensor.
Definition at line 185 of file VelocityGradient.hpp.
References PhQ::DimensionalDyad< UnitType, NumericType >::value.
Referenced by PhQ::VelocityGradient< NumericType >::Create(), and PhQ::VelocityGradient< NumericType >::VelocityGradient().
zz()
template<typename NumericType = double> constexpr ScalarVelocityGradient< NumericType > PhQ::VelocityGradient< NumericType >::zz () const inline constexpr noexcept
Returns the zz Cartesian component of this velocity gradient tensor.
Definition at line 190 of file VelocityGradient.hpp.
References PhQ::DimensionalDyad< UnitType, NumericType >::value.
Referenced by PhQ::VelocityGradient< NumericType >::Create(), and PhQ::VelocityGradient< NumericType >::VelocityGradient().
Member Data Documentation
value
template<typename UnitType , typename NumericType = double> PhQ::Dyad<NumericType> PhQ::DimensionalDyad< UnitType, NumericType >::value protected inherited
Value of this physical quantity expressed in its standard unit of measure.
Definition at line 217 of file DimensionalDyad.hpp.
Referenced by PhQ::VelocityGradient< NumericType >::Create(), PhQ::DimensionalDyad< UnitType, NumericType >::JSON(), PhQ::DimensionalDyad< UnitType, NumericType >::MutableValue(), PhQ::VelocityGradient< NumericType >::operator*(), PhQ::VelocityGradient< NumericType >::operator*=(), PhQ::VelocityGradient< NumericType >::operator+(), PhQ::VelocityGradient< NumericType >::operator+=(), PhQ::VelocityGradient< NumericType >::operator-(), PhQ::VelocityGradient< NumericType >::operator-=(), PhQ::VelocityGradient< NumericType >::operator/(), PhQ::VelocityGradient< NumericType >::operator/=(), PhQ::DimensionalDyad< UnitType, NumericType >::operator=(), PhQ::VelocityGradient< NumericType >::operator=(), PhQ::DimensionalDyad< UnitType, NumericType >::Print(), PhQ::DimensionalDyad< UnitType, NumericType >::SetValue(), PhQ::DimensionalDyad< UnitType, NumericType >::StaticValue(), PhQ::DimensionalDyad< UnitType, NumericType >::Value(), PhQ::DimensionalDyad< UnitType, NumericType >::Value(), PhQ::DimensionalDyad< UnitType, NumericType >::XML(), PhQ::VelocityGradient< NumericType >::xx(), PhQ::VelocityGradient< NumericType >::xy(), PhQ::VelocityGradient< NumericType >::xz(), PhQ::DimensionalDyad< UnitType, NumericType >::YAML(), PhQ::VelocityGradient< NumericType >::yx(), PhQ::VelocityGradient< NumericType >::yy(), PhQ::VelocityGradient< NumericType >::yz(), PhQ::VelocityGradient< NumericType >::zx(), PhQ::VelocityGradient< NumericType >::zy(), and PhQ::VelocityGradient< NumericType >::zz().
The documentation for this class was generated from the following files:
PhQ/DisplacementGradient.hpp
PhQ/VelocityGradient.hpp