Physical Quantities: PhQ::Dimension::LuminousIntensity Class Reference
PhQ::Dimension::LuminousIntensity Class Reference
Base physical dimension of luminous intensity. Typically denoted "J". One of seven independent base physical dimensions that form the physical dimension set of any unit of measure or physical quantity. Part of PhQ::Dimensions.
#include "LuminousIntensity.hpp"
Public Member Functions
constexpr LuminousIntensity ()=default
Default constructor. Constructs a base physical dimension of luminous intensity with a value of zero.
constexpr LuminousIntensity (const int8_t value)
Constructor. Constructs a base physical dimension of luminous intensity with a given value.
~LuminousIntensity () noexcept=default
Destructor. Destroys this base physical dimension of luminous intensity.
constexpr LuminousIntensity (const LuminousIntensity &other)=default
Copy constructor. Constructs a base physical dimension of luminous intensity by copying another one.
constexpr LuminousIntensity & operator= (const LuminousIntensity &other)=default
Copy assignment operator. Assigns the value of this base physical dimension of luminous intensity by copying from another one.
constexpr LuminousIntensity (LuminousIntensity &&other) noexcept=default
Move constructor. Constructs a base physical dimension of luminous intensity by moving another one.
constexpr LuminousIntensity & operator= (LuminousIntensity &&other) noexcept=default
Move assignment operator. Assigns the value of this base physical dimension of luminous intensity by moving another one.
constexpr int8_t Value () const noexcept
Value of this base physical dimension.
std::string Print () const noexcept
Prints this base physical dimension as a string.
Static Public Member Functions
static std::string_view Abbreviation () noexcept
Abbreviation of this base physical dimension.
static std::string_view Label () noexcept
Label of this base physical dimension.
Private Attributes
int8_t value {0}
Value of this base physical dimension.
Detailed Description
Base physical dimension of luminous intensity. Typically denoted "J". One of seven independent base physical dimensions that form the physical dimension set of any unit of measure or physical quantity. Part of PhQ::Dimensions.
Definition at line 40 of file LuminousIntensity.hpp.
Constructor & Destructor Documentation
LuminousIntensity() [1/4]
constexpr PhQ::Dimension::LuminousIntensity::LuminousIntensity () constexpr default
Default constructor. Constructs a base physical dimension of luminous intensity with a value of zero.
Referenced by PhQ::operator==().
LuminousIntensity() [2/4]
constexpr PhQ::Dimension::LuminousIntensity::LuminousIntensity (const int8_t value) inline explicit constexpr
Constructor. Constructs a base physical dimension of luminous intensity with a given value.
Definition at line 48 of file LuminousIntensity.hpp.
~LuminousIntensity()
PhQ::Dimension::LuminousIntensity::~LuminousIntensity () default noexcept
Destructor. Destroys this base physical dimension of luminous intensity.
LuminousIntensity() [3/4]
constexpr PhQ::Dimension::LuminousIntensity::LuminousIntensity (const LuminousIntensity & other) constexpr default
Copy constructor. Constructs a base physical dimension of luminous intensity by copying another one.
LuminousIntensity() [4/4]
constexpr PhQ::Dimension::LuminousIntensity::LuminousIntensity (LuminousIntensity && other) constexpr default noexcept
Move constructor. Constructs a base physical dimension of luminous intensity by moving another one.
Member Function Documentation
Abbreviation()
static std::string_view PhQ::Dimension::LuminousIntensity::Abbreviation () inline static noexcept
Abbreviation of this base physical dimension.
Definition at line 75 of file LuminousIntensity.hpp.
Referenced by Print().
Label()
static std::string_view PhQ::Dimension::LuminousIntensity::Label () inline static noexcept
Label of this base physical dimension.
Definition at line 80 of file LuminousIntensity.hpp.
Referenced by PhQ::Dimensions::JSON(), PhQ::Dimensions::XML(), and PhQ::Dimensions::YAML().
operator=() [1/2]
constexpr LuminousIntensity & PhQ::Dimension::LuminousIntensity::operator= (const LuminousIntensity & other) constexpr default
Copy assignment operator. Assigns the value of this base physical dimension of luminous intensity by copying from another one.
operator=() [2/2]
constexpr LuminousIntensity & PhQ::Dimension::LuminousIntensity::operator= (LuminousIntensity && other) constexpr default noexcept
Move assignment operator. Assigns the value of this base physical dimension of luminous intensity by moving another one.
Print()
std::string PhQ::Dimension::LuminousIntensity::Print () const inline noexcept
Prints this base physical dimension as a string.
Definition at line 85 of file LuminousIntensity.hpp.
References Abbreviation(), and value.
Referenced by PhQ::Dimension::operator<<(), and PhQ::Dimensions::Print().
Value()
constexpr int8_t PhQ::Dimension::LuminousIntensity::Value () const inline constexpr noexcept
Value of this base physical dimension.
Definition at line 70 of file LuminousIntensity.hpp.
References value.
Referenced by PhQ::Dimensions::JSON(), PhQ::Dimensions::XML(), and PhQ::Dimensions::YAML().
Member Data Documentation
value
int8_t PhQ::Dimension::LuminousIntensity::value {0} private
Value of this base physical dimension.
Definition at line 100 of file LuminousIntensity.hpp.
Referenced by Print(), and Value().
The documentation for this class was generated from the following file:
PhQ/Dimension/LuminousIntensity.hpp