Physical Quantities: PhQ::Velocity< NumericType > Class Template Reference
PhQ::Velocity< NumericType > Class Template Reference
Three-dimensional Euclidean velocity vector. Contains three components in Cartesian coordinates: x, y, and z. For a two-dimensional Euclidean velocity vector in the XY plane, see PhQ::PlanarVelocity. For scalar velocity components or for the magnitude of a velocity vector, see PhQ::Speed.
#include "Velocity.hpp"
Public Member Functions
Velocity ()=default
Default constructor. Constructs a velocity vector with an uninitialized value.
Velocity (const Vector< NumericType > &value, const Unit::Speed unit)
Constructor. Constructs a velocity vector with a given value expressed in a given speed unit.
Velocity (const Speed< NumericType > &x, const Speed< NumericType > &y, const Speed< NumericType > &z)
Constructor. Constructs a velocity vector from a given set of speed components.
constexpr Velocity (const Speed< NumericType > &speed, const Direction< NumericType > &direction)
Constructor. Constructs a velocity vector from a given speed and direction.
constexpr Velocity (const PlanarVelocity< NumericType > &planar_velocity)
Constructor. Constructs a velocity vector from a given planar velocity vector in the XY plane. This velocity vector's z-component is initialized to zero.
constexpr Velocity (const Displacement< NumericType > &displacement, const Time< NumericType > &time)
Constructor. Constructs a velocity vector from a given displacement vector and time using the definition of velocity.
constexpr Velocity (const Displacement< NumericType > &displacement, const Frequency< NumericType > &frequency)
Constructor. Constructs a velocity vector from a given displacement vector and frequency using the definition of velocity.
constexpr Velocity (const Acceleration< NumericType > &acceleration, const Time< NumericType > &time)
Constructor. Constructs a velocity vector from a given acceleration vector and time using the definition of acceleration.
constexpr Velocity (const Acceleration< NumericType > &acceleration, const Frequency< NumericType > &frequency)
Constructor. Constructs a velocity vector from a given acceleration vector and frequency using the definition of acceleration.
~Velocity () noexcept=default
Destructor. Destroys this velocity vector.
constexpr Velocity (const Velocity< NumericType > &other)=default
Copy constructor. Constructs a velocity vector by copying another one.
template<typename OtherNumericType >
constexpr Velocity (const Velocity< OtherNumericType > &other)
Copy constructor. Constructs a velocity by copying another one.
constexpr Velocity (Velocity< NumericType > &&other) noexcept=default
Move constructor. Constructs a velocity vector by moving another one.
constexpr Velocity< NumericType > & operator= (const Velocity< NumericType > &other)=default
Copy assignment operator. Assigns this velocity vector by copying another one.
template<typename OtherNumericType >
constexpr Velocity< NumericType > & operator= (const Velocity< OtherNumericType > &other)
Copy assignment operator. Assigns this velocity by copying another one.
constexpr Velocity< NumericType > & operator= (Velocity< NumericType > &&other) noexcept=default
Move assignment operator. Assigns this velocity vector by moving another one.
constexpr Speed< NumericType > x () const noexcept
Returns the x Cartesian component of this velocity vector.
constexpr Speed< NumericType > y () const noexcept
Returns the y Cartesian component of this velocity vector.
constexpr Speed< NumericType > z () const noexcept
Returns the z Cartesian component of this velocity vector.
Speed< NumericType > Magnitude () const
Returns the magnitude of this velocity vector.
PhQ::Direction< NumericType > Direction () const
Returns the direction of this velocity vector.
PhQ::Angle< NumericType > Angle (const Velocity< NumericType > &velocity) const
Returns the angle between this velocity vector and another one.
constexpr Velocity< NumericType > operator+ (const Velocity< NumericType > &velocity) const
constexpr Velocity< NumericType > operator- (const Velocity< NumericType > &velocity) const
constexpr Velocity< NumericType > operator* (const NumericType number) const
constexpr Displacement< NumericType > operator* (const Time< NumericType > &time) const
constexpr Acceleration< NumericType > operator* (const Frequency< NumericType > &frequency) const
constexpr Velocity< NumericType > operator/ (const NumericType number) const
constexpr Acceleration< NumericType > operator/ (const Time< NumericType > &time) const
constexpr Displacement< NumericType > operator/ (const Frequency< NumericType > &frequency) const
constexpr void operator+= (const Velocity< NumericType > &velocity) noexcept
constexpr void operator-= (const Velocity< NumericType > &velocity) noexcept
constexpr void operator*= (const NumericType number) noexcept
constexpr void operator/= (const NumericType number) noexcept
constexpr const PhQ::Vector< NumericType > & Value () const noexcept
Value of this physical quantity expressed in its standard unit of measure.
PhQ::Vector< NumericType > Value (const UnitType unit) const
Value of this physical quantity expressed in a given unit of measure.
template<UnitType NewUnit>
constexpr PhQ::Vector< NumericType > StaticValue () const
Value of this physical quantity expressed in a given unit of measure. This method can be evaluated statically at compile-time.
constexpr PhQ::Vector< NumericType > & MutableValue () noexcept
Returns the value of this physical quantity expressed in its standard unit of measure as a mutable value.
constexpr void SetValue (const PhQ::Vector< NumericType > &value) noexcept
Sets the value of this physical quantity expressed in its standard unit of measure to the given value.
std::string Print () const
Prints this physical quantity as a string. This physical quantity's value is expressed in its standard unit of measure.
std::string Print (const UnitType unit) const
Prints this physical quantity as a string. This physical quantity's value is expressed in the given unit of measure.
std::string JSON () const
Serializes this physical quantity as a JSON message. This physical quantity's value is expressed in its standard unit of measure.
std::string JSON (const UnitType unit) const
Serializes this physical quantity as a JSON message. This physical quantity's value is expressed in the given unit of measure.
std::string XML () const
Serializes this physical quantity as an XML message. This physical quantity's value is expressed in its standard unit of measure.
std::string XML (const UnitType unit) const
Serializes this physical quantity as an XML message. This physical quantity's value is expressed in the given unit of measure.
std::string YAML () const
Serializes this physical quantity as a YAML message. This physical quantity's value is expressed in its standard unit of measure.
std::string YAML (const UnitType unit) const
Serializes this physical quantity as a YAML message. This physical quantity's value is expressed in the given unit of measure.
Static Public Member Functions
static constexpr Velocity< NumericType > Zero ()
Statically creates a velocity vector of zero.
template<Unit::Speed Unit>
static constexpr Velocity< NumericType > Create (const NumericType x, const NumericType y, const NumericType z)
Statically creates a velocity vector from the given x, y, and z Cartesian components expressed in a given speed unit.
template<Unit::Speed Unit>
static constexpr Velocity< NumericType > Create (const std::array< NumericType, 3 > &x_y_z)
Statically creates a velocity vector from the given x, y, and z Cartesian components expressed in a given speed unit.
template<Unit::Speed Unit>
static constexpr Velocity< NumericType > Create (const Vector< NumericType > &value)
Statically creates a velocity vector with a given value expressed in a given speed unit.
static constexpr const PhQ::Dimensions & Dimensions ()
Physical dimension set of this physical quantity.
static constexpr UnitType Unit ()
Standard unit of measure for this physical quantity. This physical quantity's value is stored internally in this unit of measure.
Protected Attributes
PhQ::Vector< NumericType > value
Value of this physical quantity expressed in its standard unit of measure.
Private Member Functions
constexpr Velocity (const Vector< NumericType > &value)
Constructor. Constructs a velocity vector with a given value expressed in the standard speed unit.
Detailed Description
template<typename NumericType = double>
class PhQ::Velocity< NumericType >
Three-dimensional Euclidean velocity vector. Contains three components in Cartesian coordinates: x, y, and z. For a two-dimensional Euclidean velocity vector in the XY plane, see PhQ::PlanarVelocity. For scalar velocity components or for the magnitude of a velocity vector, see PhQ::Speed.
Definition at line 55 of file Velocity.hpp.
Constructor & Destructor Documentation
Velocity() [1/13]
template<typename NumericType = double> PhQ::Velocity< NumericType >::Velocity () default
Default constructor. Constructs a velocity vector with an uninitialized value.
Velocity() [2/13]
template<typename NumericType = double> PhQ::Velocity< NumericType >::Velocity (const Vector< NumericType > & value, const Unit::Speed unit) inline
Constructor. Constructs a velocity vector with a given value expressed in a given speed unit.
Definition at line 62 of file Velocity.hpp.
Velocity() [3/13]
template<typename NumericType = double> PhQ::Velocity< NumericType >::Velocity (const Speed< NumericType > & x, const Speed< NumericType > & y, const Speed< NumericType > & z) inline
Constructor. Constructs a velocity vector from a given set of speed components.
Definition at line 66 of file Velocity.hpp.
References PhQ::Velocity< NumericType >::x(), PhQ::Velocity< NumericType >::y(), and PhQ::Velocity< NumericType >::z().
Velocity() [4/13]
template<typename NumericType = double> constexpr PhQ::Velocity< NumericType >::Velocity (const Speed< NumericType > & speed, const Direction< NumericType > & direction) inline constexpr
Constructor. Constructs a velocity vector from a given speed and direction.
Definition at line 70 of file Velocity.hpp.
Velocity() [5/13]
template<typename NumericType = double> constexpr PhQ::Velocity< NumericType >::Velocity (const PlanarVelocity< NumericType > & planar_velocity) inline explicit constexpr
Constructor. Constructs a velocity vector from a given planar velocity vector in the XY plane. This velocity vector's z-component is initialized to zero.
Definition at line 75 of file Velocity.hpp.
References PhQ::DimensionalPlanarVector< UnitType, NumericType >::Value().
Velocity() [6/13]
template<typename NumericType = double> constexpr PhQ::Velocity< NumericType >::Velocity (const Displacement< NumericType > & displacement, const Time< NumericType > & time) inline constexpr
Constructor. Constructs a velocity vector from a given displacement vector and time using the definition of velocity.
Definition at line 80 of file Velocity.hpp.
Velocity() [7/13]
template<typename NumericType = double> constexpr PhQ::Velocity< NumericType >::Velocity (const Displacement< NumericType > & displacement, const Frequency< NumericType > & frequency) inline constexpr
Constructor. Constructs a velocity vector from a given displacement vector and frequency using the definition of velocity.
Definition at line 85 of file Velocity.hpp.
Velocity() [8/13]
template<typename NumericType > constexpr PhQ::Velocity< NumericType >::Velocity (const Acceleration< NumericType > & acceleration, const Time< NumericType > & time) inline constexpr
Constructor. Constructs a velocity vector from a given acceleration vector and time using the definition of acceleration.
Definition at line 292 of file Acceleration.hpp.
Velocity() [9/13]
template<typename NumericType > constexpr PhQ::Velocity< NumericType >::Velocity (const Acceleration< NumericType > & acceleration, const Frequency< NumericType > & frequency) inline constexpr
Constructor. Constructs a velocity vector from a given acceleration vector and frequency using the definition of acceleration.
Definition at line 297 of file Acceleration.hpp.
~Velocity()
template<typename NumericType = double> PhQ::Velocity< NumericType >::~Velocity () default noexcept
Destructor. Destroys this velocity vector.
Velocity() [10/13]
template<typename NumericType = double> constexpr PhQ::Velocity< NumericType >::Velocity (const Velocity< NumericType > & other) constexpr default
Copy constructor. Constructs a velocity vector by copying another one.
Velocity() [11/13]
template<typename NumericType = double> template<typename OtherNumericType > constexpr PhQ::Velocity< NumericType >::Velocity (const Velocity< OtherNumericType > & other) inline explicit constexpr
Copy constructor. Constructs a velocity by copying another one.
Definition at line 106 of file Velocity.hpp.
Velocity() [12/13]
template<typename NumericType = double> constexpr PhQ::Velocity< NumericType >::Velocity (Velocity< NumericType > && other) constexpr default noexcept
Move constructor. Constructs a velocity vector by moving another one.
Velocity() [13/13]
template<typename NumericType = double> constexpr PhQ::Velocity< NumericType >::Velocity (const Vector< NumericType > & value) inline explicit constexpr private
Constructor. Constructs a velocity vector with a given value expressed in the standard speed unit.
Definition at line 233 of file Velocity.hpp.
Member Function Documentation
Angle()
template<typename NumericType = double> PhQ::Angle< NumericType > PhQ::Velocity< NumericType >::Angle (const Velocity< NumericType > & velocity) const inline
Returns the angle between this velocity vector and another one.
Definition at line 182 of file Velocity.hpp.
Create() [1/3]
template<typename NumericType = double> template<Unit::Speed Unit> static constexpr Velocity< NumericType > PhQ::Velocity< NumericType >::Create (const NumericType x, const NumericType y, const NumericType z) inline static constexpr
Statically creates a velocity vector from the given x, y, and z Cartesian components expressed in a given speed unit.
Definition at line 133 of file Velocity.hpp.
References PhQ::Velocity< NumericType >::x(), PhQ::Velocity< NumericType >::y(), and PhQ::Velocity< NumericType >::z().
Create() [2/3]
template<typename NumericType = double> template<Unit::Speed Unit> static constexpr Velocity< NumericType > PhQ::Velocity< NumericType >::Create (const std::array< NumericType, 3 > & x_y_z) inline static constexpr
Statically creates a velocity vector from the given x, y, and z Cartesian components expressed in a given speed unit.
Definition at line 142 of file Velocity.hpp.
Create() [3/3]
template<typename NumericType = double> template<Unit::Speed Unit> static constexpr Velocity< NumericType > PhQ::Velocity< NumericType >::Create (const Vector< NumericType > & value) inline static constexpr
Statically creates a velocity vector with a given value expressed in a given speed unit.
Definition at line 151 of file Velocity.hpp.
References PhQ::DimensionalVector< UnitType, NumericType >::value.
Dimensions()
template<typename UnitType , typename NumericType = double> static constexpr const PhQ::Dimensions & PhQ::DimensionalVector< UnitType, NumericType >::Dimensions () inline static constexpr inherited
Physical dimension set of this physical quantity.
Definition at line 50 of file DimensionalVector.hpp.
Direction()
template<typename NumericType = double> PhQ::Direction< NumericType > PhQ::Velocity< NumericType >::Direction () const inline
Returns the direction of this velocity vector.
Definition at line 177 of file Velocity.hpp.
References PhQ::DimensionalVector< UnitType, NumericType >::value.
JSON() [1/2]
template<typename UnitType , typename NumericType = double> std::string PhQ::DimensionalVector< UnitType, NumericType >::JSON () const inline inherited
Serializes this physical quantity as a JSON message. This physical quantity's value is expressed in its standard unit of measure.
Definition at line 103 of file DimensionalVector.hpp.
References PhQ::Abbreviation(), and PhQ::DimensionalVector< UnitType, NumericType >::value.
Referenced by PhQ::DimensionalVector< UnitType, NumericType >::JSON().
JSON() [2/2]
template<typename UnitType , typename NumericType = double> std::string PhQ::DimensionalVector< UnitType, NumericType >::JSON (const UnitType unit) const inline inherited
Serializes this physical quantity as a JSON message. This physical quantity's value is expressed in the given unit of measure.
Definition at line 113 of file DimensionalVector.hpp.
References PhQ::Abbreviation(), PhQ::DimensionalVector< UnitType, NumericType >::JSON(), and PhQ::DimensionalVector< UnitType, NumericType >::Value().
Magnitude()
template<typename NumericType = double> Speed< NumericType > PhQ::Velocity< NumericType >::Magnitude () const inline
Returns the magnitude of this velocity vector.
Definition at line 172 of file Velocity.hpp.
References PhQ::DimensionalVector< UnitType, NumericType >::value.
MutableValue()
template<typename UnitType , typename NumericType = double> constexpr PhQ::Vector< NumericType > & PhQ::DimensionalVector< UnitType, NumericType >::MutableValue () inline constexpr noexcept inherited
Returns the value of this physical quantity expressed in its standard unit of measure as a mutable value.
Definition at line 79 of file DimensionalVector.hpp.
References PhQ::DimensionalVector< UnitType, NumericType >::value.
operator*() [1/3]
template<typename NumericType > constexpr Acceleration< NumericType > PhQ::Velocity< NumericType >::operator* (const Frequency< NumericType > & frequency) const inline constexpr
Definition at line 320 of file Acceleration.hpp.
operator*() [2/3]
template<typename NumericType = double> constexpr Velocity< NumericType > PhQ::Velocity< NumericType >::operator* (const NumericType number) const inline constexpr
Definition at line 194 of file Velocity.hpp.
References PhQ::DimensionalVector< UnitType, NumericType >::value.
operator*() [3/3]
template<typename NumericType = double> constexpr Displacement< NumericType > PhQ::Velocity< NumericType >::operator* (const Time< NumericType > & time) const inline constexpr
Definition at line 198 of file Velocity.hpp.
operator*=()
template<typename NumericType = double> constexpr void PhQ::Velocity< NumericType >::operator*= (const NumericType number) inline constexpr noexcept
Definition at line 222 of file Velocity.hpp.
References PhQ::DimensionalVector< UnitType, NumericType >::value.
operator+()
template<typename NumericType = double> constexpr Velocity< NumericType > PhQ::Velocity< NumericType >::operator+ (const Velocity< NumericType > & velocity) const inline constexpr
Definition at line 186 of file Velocity.hpp.
References PhQ::DimensionalVector< UnitType, NumericType >::value.
operator+=()
template<typename NumericType = double> constexpr void PhQ::Velocity< NumericType >::operator+= (const Velocity< NumericType > & velocity) inline constexpr noexcept
Definition at line 214 of file Velocity.hpp.
References PhQ::DimensionalVector< UnitType, NumericType >::value.
operator-()
template<typename NumericType = double> constexpr Velocity< NumericType > PhQ::Velocity< NumericType >::operator- (const Velocity< NumericType > & velocity) const inline constexpr
Definition at line 190 of file Velocity.hpp.
References PhQ::DimensionalVector< UnitType, NumericType >::value.
operator-=()
template<typename NumericType = double> constexpr void PhQ::Velocity< NumericType >::operator-= (const Velocity< NumericType > & velocity) inline constexpr noexcept
Definition at line 218 of file Velocity.hpp.
References PhQ::DimensionalVector< UnitType, NumericType >::value.
operator/() [1/3]
template<typename NumericType = double> constexpr Displacement< NumericType > PhQ::Velocity< NumericType >::operator/ (const Frequency< NumericType > & frequency) const inline constexpr
Definition at line 210 of file Velocity.hpp.
operator/() [2/3]
template<typename NumericType = double> constexpr Velocity< NumericType > PhQ::Velocity< NumericType >::operator/ (const NumericType number) const inline constexpr
Definition at line 204 of file Velocity.hpp.
References PhQ::DimensionalVector< UnitType, NumericType >::value.
operator/() [3/3]
template<typename NumericType > constexpr Acceleration< NumericType > PhQ::Velocity< NumericType >::operator/ (const Time< NumericType > & time) const inline constexpr
Definition at line 332 of file Acceleration.hpp.
operator/=()
template<typename NumericType = double> constexpr void PhQ::Velocity< NumericType >::operator/= (const NumericType number) inline constexpr noexcept
Definition at line 226 of file Velocity.hpp.
References PhQ::DimensionalVector< UnitType, NumericType >::value.
operator=() [1/3]
template<typename NumericType = double> constexpr Velocity< NumericType > & PhQ::Velocity< NumericType >::operator= (const Velocity< NumericType > & other) constexpr default
Copy assignment operator. Assigns this velocity vector by copying another one.
operator=() [2/3]
template<typename NumericType = double> template<typename OtherNumericType > constexpr Velocity< NumericType > & PhQ::Velocity< NumericType >::operator= (const Velocity< OtherNumericType > & other) inline constexpr
Copy assignment operator. Assigns this velocity by copying another one.
Definition at line 117 of file Velocity.hpp.
References PhQ::DimensionalVector< UnitType, NumericType >::Value(), and PhQ::DimensionalVector< UnitType, NumericType >::value.
operator=() [3/3]
template<typename NumericType = double> constexpr Velocity< NumericType > & PhQ::Velocity< NumericType >::operator= (Velocity< NumericType > && other) constexpr default noexcept
Move assignment operator. Assigns this velocity vector by moving another one.
Print() [1/2]
template<typename UnitType , typename NumericType = double> std::string PhQ::DimensionalVector< UnitType, NumericType >::Print () const inline inherited
Prints this physical quantity as a string. This physical quantity's value is expressed in its standard unit of measure.
Definition at line 91 of file DimensionalVector.hpp.
References PhQ::Abbreviation(), and PhQ::DimensionalVector< UnitType, NumericType >::value.
Referenced by PhQ::operator<<(), PhQ::operator<<(), PhQ::operator<<(), PhQ::operator<<(), PhQ::operator<<(), PhQ::operator<<(), PhQ::operator<<(), PhQ::operator<<(), and PhQ::operator<<().
Print() [2/2]
template<typename UnitType , typename NumericType = double> std::string PhQ::DimensionalVector< UnitType, NumericType >::Print (const UnitType unit) const inline inherited
Prints this physical quantity as a string. This physical quantity's value is expressed in the given unit of measure.
Definition at line 97 of file DimensionalVector.hpp.
References PhQ::Abbreviation(), and PhQ::DimensionalVector< UnitType, NumericType >::Value().
SetValue()
template<typename UnitType , typename NumericType = double> constexpr void PhQ::DimensionalVector< UnitType, NumericType >::SetValue (const PhQ::Vector< NumericType > & value) inline constexpr noexcept inherited
Sets the value of this physical quantity expressed in its standard unit of measure to the given value.
Definition at line 85 of file DimensionalVector.hpp.
References PhQ::DimensionalVector< UnitType, NumericType >::value.
StaticValue()
template<typename UnitType , typename NumericType = double> template<UnitType NewUnit> constexpr PhQ::Vector< NumericType > PhQ::DimensionalVector< UnitType, NumericType >::StaticValue () const inline constexpr inherited
Value of this physical quantity expressed in a given unit of measure. This method can be evaluated statically at compile-time.
Definition at line 73 of file DimensionalVector.hpp.
References PhQ::DimensionalVector< UnitType, NumericType >::value.
Unit()
template<typename UnitType , typename NumericType = double> static constexpr UnitType PhQ::DimensionalVector< UnitType, NumericType >::Unit () inline static constexpr inherited
Standard unit of measure for this physical quantity. This physical quantity's value is stored internally in this unit of measure.
Definition at line 56 of file DimensionalVector.hpp.
Value() [1/2]
template<typename UnitType , typename NumericType = double> constexpr const PhQ::Vector< NumericType > & PhQ::DimensionalVector< UnitType, NumericType >::Value () const inline constexpr noexcept inherited
Value of this physical quantity expressed in its standard unit of measure.
Definition at line 61 of file DimensionalVector.hpp.
References PhQ::DimensionalVector< UnitType, NumericType >::value.
Referenced by PhQ::DimensionalVector< UnitType, NumericType >::JSON(), PhQ::Position< NumericType >::operator+(), PhQ::Displacement< NumericType >::operator+(), PhQ::Position< NumericType >::operator-(), PhQ::Displacement< NumericType >::operator-(), PhQ::Acceleration< NumericType >::operator=(), PhQ::DimensionalVector< UnitType, NumericType >::operator=(), PhQ::Displacement< NumericType >::operator=(), PhQ::Force< NumericType >::operator=(), PhQ::HeatFlux< NumericType >::operator=(), PhQ::Position< NumericType >::operator=(), PhQ::TemperatureGradient< NumericType >::operator=(), PhQ::Traction< NumericType >::operator=(), PhQ::VectorArea< NumericType >::operator=(), PhQ::Velocity< NumericType >::operator=(), PhQ::operator==(), PhQ::operator==(), PhQ::operator==(), PhQ::operator==(), PhQ::operator==(), PhQ::operator==(), PhQ::operator==(), PhQ::operator==(), PhQ::operator==(), PhQ::operator==(), PhQ::operator==(), PhQ::operator==(), PhQ::operator==(), PhQ::operator==(), PhQ::operator==(), PhQ::operator==(), PhQ::PlanarAcceleration< NumericType >::PlanarAcceleration(), PhQ::PlanarDisplacement< NumericType >::PlanarDisplacement(), PhQ::PlanarForce< NumericType >::PlanarForce(), PhQ::PlanarHeatFlux< NumericType >::PlanarHeatFlux(), PhQ::PlanarPosition< NumericType >::PlanarPosition(), PhQ::PlanarTemperatureGradient< NumericType >::PlanarTemperatureGradient(), PhQ::PlanarTraction< NumericType >::PlanarTraction(), PhQ::PlanarVelocity< NumericType >::PlanarVelocity(), PhQ::DimensionalVector< UnitType, NumericType >::Print(), PhQ::DimensionalVector< UnitType, NumericType >::XML(), and PhQ::DimensionalVector< UnitType, NumericType >::YAML().
Value() [2/2]
template<typename UnitType , typename NumericType = double> PhQ::Vector< NumericType > PhQ::DimensionalVector< UnitType, NumericType >::Value (const UnitType unit) const inline inherited
Value of this physical quantity expressed in a given unit of measure.
Definition at line 66 of file DimensionalVector.hpp.
References PhQ::Convert(), and PhQ::DimensionalVector< UnitType, NumericType >::value.
x()
template<typename NumericType = double> constexpr Speed< NumericType > PhQ::Velocity< NumericType >::x () const inline constexpr noexcept
Returns the x Cartesian component of this velocity vector.
Definition at line 157 of file Velocity.hpp.
References PhQ::DimensionalVector< UnitType, NumericType >::value.
Referenced by PhQ::Velocity< NumericType >::Create(), and PhQ::Velocity< NumericType >::Velocity().
XML() [1/2]
template<typename UnitType , typename NumericType = double> std::string PhQ::DimensionalVector< UnitType, NumericType >::XML () const inline inherited
Serializes this physical quantity as an XML message. This physical quantity's value is expressed in its standard unit of measure.
Definition at line 123 of file DimensionalVector.hpp.
References PhQ::Abbreviation(), and PhQ::DimensionalVector< UnitType, NumericType >::value.
Referenced by PhQ::DimensionalVector< UnitType, NumericType >::XML().
XML() [2/2]
template<typename UnitType , typename NumericType = double> std::string PhQ::DimensionalVector< UnitType, NumericType >::XML (const UnitType unit) const inline inherited
Serializes this physical quantity as an XML message. This physical quantity's value is expressed in the given unit of measure.
Definition at line 133 of file DimensionalVector.hpp.
References PhQ::Abbreviation(), PhQ::DimensionalVector< UnitType, NumericType >::Value(), and PhQ::DimensionalVector< UnitType, NumericType >::XML().
y()
template<typename NumericType = double> constexpr Speed< NumericType > PhQ::Velocity< NumericType >::y () const inline constexpr noexcept
Returns the y Cartesian component of this velocity vector.
Definition at line 162 of file Velocity.hpp.
References PhQ::DimensionalVector< UnitType, NumericType >::value.
Referenced by PhQ::Velocity< NumericType >::Create(), and PhQ::Velocity< NumericType >::Velocity().
YAML() [1/2]
template<typename UnitType , typename NumericType = double> std::string PhQ::DimensionalVector< UnitType, NumericType >::YAML () const inline inherited
Serializes this physical quantity as a YAML message. This physical quantity's value is expressed in its standard unit of measure.
Definition at line 143 of file DimensionalVector.hpp.
References PhQ::Abbreviation(), and PhQ::DimensionalVector< UnitType, NumericType >::value.
Referenced by PhQ::DimensionalVector< UnitType, NumericType >::YAML().
YAML() [2/2]
template<typename UnitType , typename NumericType = double> std::string PhQ::DimensionalVector< UnitType, NumericType >::YAML (const UnitType unit) const inline inherited
Serializes this physical quantity as a YAML message. This physical quantity's value is expressed in the given unit of measure.
Definition at line 153 of file DimensionalVector.hpp.
References PhQ::Abbreviation(), PhQ::DimensionalVector< UnitType, NumericType >::Value(), and PhQ::DimensionalVector< UnitType, NumericType >::YAML().
z()
template<typename NumericType = double> constexpr Speed< NumericType > PhQ::Velocity< NumericType >::z () const inline constexpr noexcept
Returns the z Cartesian component of this velocity vector.
Definition at line 167 of file Velocity.hpp.
References PhQ::DimensionalVector< UnitType, NumericType >::value.
Referenced by PhQ::Velocity< NumericType >::Create(), and PhQ::Velocity< NumericType >::Velocity().
Zero()
template<typename NumericType = double> static constexpr Velocity< NumericType > PhQ::Velocity< NumericType >::Zero () inline static constexpr
Statically creates a velocity vector of zero.
Definition at line 126 of file Velocity.hpp.
References PhQ::Vector< NumericType >::Zero().
Member Data Documentation
value
template<typename UnitType , typename NumericType = double> PhQ::Vector<NumericType> PhQ::DimensionalVector< UnitType, NumericType >::value protected inherited
Value of this physical quantity expressed in its standard unit of measure.
Definition at line 217 of file DimensionalVector.hpp.
Referenced by PhQ::Acceleration< NumericType >::Create(), PhQ::Displacement< NumericType >::Create(), PhQ::Force< NumericType >::Create(), PhQ::HeatFlux< NumericType >::Create(), PhQ::Position< NumericType >::Create(), PhQ::TemperatureGradient< NumericType >::Create(), PhQ::Traction< NumericType >::Create(), PhQ::VectorArea< NumericType >::Create(), PhQ::Velocity< NumericType >::Create(), PhQ::Acceleration< NumericType >::Direction(), PhQ::Displacement< NumericType >::Direction(), PhQ::Force< NumericType >::Direction(), PhQ::HeatFlux< NumericType >::Direction(), PhQ::Position< NumericType >::Direction(), PhQ::TemperatureGradient< NumericType >::Direction(), PhQ::Traction< NumericType >::Direction(), PhQ::VectorArea< NumericType >::Direction(), PhQ::Velocity< NumericType >::Direction(), PhQ::DimensionalVector< UnitType, NumericType >::JSON(), PhQ::Acceleration< NumericType >::Magnitude(), PhQ::Displacement< NumericType >::Magnitude(), PhQ::Force< NumericType >::Magnitude(), PhQ::HeatFlux< NumericType >::Magnitude(), PhQ::Position< NumericType >::Magnitude(), PhQ::TemperatureGradient< NumericType >::Magnitude(), PhQ::Traction< NumericType >::Magnitude(), PhQ::VectorArea< NumericType >::Magnitude(), PhQ::Velocity< NumericType >::Magnitude(), PhQ::DimensionalVector< UnitType, NumericType >::MutableValue(), PhQ::Acceleration< NumericType >::operator*(), PhQ::Displacement< NumericType >::operator*(), PhQ::Force< NumericType >::operator*(), PhQ::HeatFlux< NumericType >::operator*(), PhQ::Position< NumericType >::operator*(), PhQ::TemperatureGradient< NumericType >::operator*(), PhQ::Traction< NumericType >::operator*(), PhQ::VectorArea< NumericType >::operator*(), PhQ::Velocity< NumericType >::operator*(), PhQ::Acceleration< NumericType >::operator*=(), PhQ::Displacement< NumericType >::operator*=(), PhQ::Force< NumericType >::operator*=(), PhQ::HeatFlux< NumericType >::operator*=(), PhQ::Position< NumericType >::operator*=(), PhQ::TemperatureGradient< NumericType >::operator*=(), PhQ::Traction< NumericType >::operator*=(), PhQ::VectorArea< NumericType >::operator*=(), PhQ::Velocity< NumericType >::operator*=(), PhQ::Acceleration< NumericType >::operator+(), PhQ::Displacement< NumericType >::operator+(), PhQ::Position< NumericType >::operator+(), PhQ::Force< NumericType >::operator+(), PhQ::HeatFlux< NumericType >::operator+(), PhQ::Position< NumericType >::operator+(), PhQ::TemperatureGradient< NumericType >::operator+(), PhQ::Traction< NumericType >::operator+(), PhQ::VectorArea< NumericType >::operator+(), PhQ::Velocity< NumericType >::operator+(), PhQ::Acceleration< NumericType >::operator+=(), PhQ::Displacement< NumericType >::operator+=(), PhQ::Position< NumericType >::operator+=(), PhQ::Force< NumericType >::operator+=(), PhQ::HeatFlux< NumericType >::operator+=(), PhQ::Position< NumericType >::operator+=(), PhQ::TemperatureGradient< NumericType >::operator+=(), PhQ::Traction< NumericType >::operator+=(), PhQ::VectorArea< NumericType >::operator+=(), PhQ::Velocity< NumericType >::operator+=(), PhQ::Acceleration< NumericType >::operator-(), PhQ::Displacement< NumericType >::operator-(), PhQ::Position< NumericType >::operator-(), PhQ::Force< NumericType >::operator-(), PhQ::HeatFlux< NumericType >::operator-(), PhQ::Position< NumericType >::operator-(), PhQ::TemperatureGradient< NumericType >::operator-(), PhQ::Traction< NumericType >::operator-(), PhQ::VectorArea< NumericType >::operator-(), PhQ::Velocity< NumericType >::operator-(), PhQ::Acceleration< NumericType >::operator-=(), PhQ::Displacement< NumericType >::operator-=(), PhQ::Position< NumericType >::operator-=(), PhQ::Force< NumericType >::operator-=(), PhQ::HeatFlux< NumericType >::operator-=(), PhQ::Position< NumericType >::operator-=(), PhQ::TemperatureGradient< NumericType >::operator-=(), PhQ::Traction< NumericType >::operator-=(), PhQ::VectorArea< NumericType >::operator-=(), PhQ::Velocity< NumericType >::operator-=(), PhQ::Acceleration< NumericType >::operator/(), PhQ::Displacement< NumericType >::operator/(), PhQ::Force< NumericType >::operator/(), PhQ::HeatFlux< NumericType >::operator/(), PhQ::Position< NumericType >::operator/(), PhQ::TemperatureGradient< NumericType >::operator/(), PhQ::Traction< NumericType >::operator/(), PhQ::VectorArea< NumericType >::operator/(), PhQ::Velocity< NumericType >::operator/(), PhQ::Acceleration< NumericType >::operator/=(), PhQ::Displacement< NumericType >::operator/=(), PhQ::Force< NumericType >::operator/=(), PhQ::HeatFlux< NumericType >::operator/=(), PhQ::Position< NumericType >::operator/=(), PhQ::TemperatureGradient< NumericType >::operator/=(), PhQ::Traction< NumericType >::operator/=(), PhQ::VectorArea< NumericType >::operator/=(), PhQ::Velocity< NumericType >::operator/=(), PhQ::Acceleration< NumericType >::operator=(), PhQ::DimensionalVector< UnitType, NumericType >::operator=(), PhQ::Displacement< NumericType >::operator=(), PhQ::Force< NumericType >::operator=(), PhQ::HeatFlux< NumericType >::operator=(), PhQ::Position< NumericType >::operator=(), PhQ::TemperatureGradient< NumericType >::operator=(), PhQ::Traction< NumericType >::operator=(), PhQ::VectorArea< NumericType >::operator=(), PhQ::Velocity< NumericType >::operator=(), PhQ::DimensionalVector< UnitType, NumericType >::Print(), PhQ::DimensionalVector< UnitType, NumericType >::SetValue(), PhQ::DimensionalVector< UnitType, NumericType >::StaticValue(), PhQ::DimensionalVector< UnitType, NumericType >::Value(), PhQ::DimensionalVector< UnitType, NumericType >::Value(), PhQ::Acceleration< NumericType >::x(), PhQ::Displacement< NumericType >::x(), PhQ::Force< NumericType >::x(), PhQ::HeatFlux< NumericType >::x(), PhQ::Position< NumericType >::x(), PhQ::TemperatureGradient< NumericType >::x(), PhQ::Traction< NumericType >::x(), PhQ::VectorArea< NumericType >::x(), PhQ::Velocity< NumericType >::x(), PhQ::DimensionalVector< UnitType, NumericType >::XML(), PhQ::Acceleration< NumericType >::y(), PhQ::Displacement< NumericType >::y(), PhQ::Force< NumericType >::y(), PhQ::HeatFlux< NumericType >::y(), PhQ::Position< NumericType >::y(), PhQ::TemperatureGradient< NumericType >::y(), PhQ::Traction< NumericType >::y(), PhQ::VectorArea< NumericType >::y(), PhQ::Velocity< NumericType >::y(), PhQ::DimensionalVector< UnitType, NumericType >::YAML(), PhQ::Acceleration< NumericType >::z(), PhQ::Displacement< NumericType >::z(), PhQ::Force< NumericType >::z(), PhQ::HeatFlux< NumericType >::z(), PhQ::Position< NumericType >::z(), PhQ::TemperatureGradient< NumericType >::z(), PhQ::Traction< NumericType >::z(), PhQ::VectorArea< NumericType >::z(), and PhQ::Velocity< NumericType >::z().
The documentation for this class was generated from the following files:
PhQ/Angle.hpp
PhQ/Velocity.hpp
PhQ/Acceleration.hpp