Physical Quantities (PhQ): PhQ::Dimension::SubstanceAmount Class Reference
PhQ::Dimension::SubstanceAmount Class Reference
Base physical dimension of amount of substance. Typically denoted "N". One of seven independent base physical dimensions that form the physical dimension set of any unit of measure or physical quantity.
#include "SubstanceAmount.hpp"
Public Member Functions
constexpr SubstanceAmount ()=default
Default constructor. Constructs a base physical dimension of amount of substance with a value of zero.
constexpr SubstanceAmount (const int8_t value)
Constructor. Constructs a base physical dimension of amount of substance with a given value.
~SubstanceAmount () noexcept=default
Destructor. Destroys this base physical dimension of amount of substance.
constexpr SubstanceAmount (const SubstanceAmount &other)=default
Copy constructor. Constructs a base physical dimension of amount of substance by copying another one.
constexpr SubstanceAmount & operator= (const SubstanceAmount &other)=default
Copy assignment operator. Assigns the value of this base physical dimension of amount of substance by copying from another one.
constexpr SubstanceAmount (SubstanceAmount &&other) noexcept=default
Move constructor. Constructs a base physical dimension of amount of substance by moving another one.
constexpr SubstanceAmount & operator= (SubstanceAmount &&other) noexcept=default
Move assignment operator. Assigns the value of this base physical dimension of amount of substance by moving another one.
constexpr int8_t Value () const noexcept
Value of this base physical dimension.
std::string Print () const noexcept
Prints this base physical dimension as a string.
Static Public Member Functions
static std::string_view Abbreviation () noexcept
Abbreviation of this base physical dimension.
static std::string_view Label () noexcept
Label of this base physical dimension.
Private Attributes
int8_t value {0}
Value of this base physical dimension.
Detailed Description
Base physical dimension of amount of substance. Typically denoted "N". One of seven independent base physical dimensions that form the physical dimension set of any unit of measure or physical quantity.
Definition at line 42 of file SubstanceAmount.hpp.
Constructor & Destructor Documentation
SubstanceAmount() [1/4]
constexpr PhQ::Dimension::SubstanceAmount::SubstanceAmount () constexpr default
Default constructor. Constructs a base physical dimension of amount of substance with a value of zero.
SubstanceAmount() [2/4]
constexpr PhQ::Dimension::SubstanceAmount::SubstanceAmount (const int8_t value) inline explicit constexpr
Constructor. Constructs a base physical dimension of amount of substance with a given value.
Definition at line 50 of file SubstanceAmount.hpp.
~SubstanceAmount()
PhQ::Dimension::SubstanceAmount::~SubstanceAmount () default noexcept
Destructor. Destroys this base physical dimension of amount of substance.
SubstanceAmount() [3/4]
constexpr PhQ::Dimension::SubstanceAmount::SubstanceAmount (const SubstanceAmount & other) constexpr default
Copy constructor. Constructs a base physical dimension of amount of substance by copying another one.
SubstanceAmount() [4/4]
constexpr PhQ::Dimension::SubstanceAmount::SubstanceAmount (SubstanceAmount && other) constexpr default noexcept
Move constructor. Constructs a base physical dimension of amount of substance by moving another one.
Member Function Documentation
Abbreviation()
static std::string_view PhQ::Dimension::SubstanceAmount::Abbreviation () inline static noexcept
Abbreviation of this base physical dimension.
Definition at line 77 of file SubstanceAmount.hpp.
Referenced by Print().
Label()
static std::string_view PhQ::Dimension::SubstanceAmount::Label () inline static noexcept
Label of this base physical dimension.
Definition at line 82 of file SubstanceAmount.hpp.
Referenced by PhQ::Dimensions::JSON(), PhQ::Dimensions::XML(), and PhQ::Dimensions::YAML().
operator=() [1/2]
constexpr SubstanceAmount& PhQ::Dimension::SubstanceAmount::operator= (const SubstanceAmount & other) constexpr default
Copy assignment operator. Assigns the value of this base physical dimension of amount of substance by copying from another one.
operator=() [2/2]
constexpr SubstanceAmount& PhQ::Dimension::SubstanceAmount::operator= (SubstanceAmount && other) constexpr default noexcept
Move assignment operator. Assigns the value of this base physical dimension of amount of substance by moving another one.
Print()
std::string PhQ::Dimension::SubstanceAmount::Print () const inline noexcept
Prints this base physical dimension as a string.
Definition at line 87 of file SubstanceAmount.hpp.
References Abbreviation(), and value.
Referenced by PhQ::Dimension::operator<<(), and PhQ::Dimensions::Print().
Value()
constexpr int8_t PhQ::Dimension::SubstanceAmount::Value () const inline constexpr noexcept
Value of this base physical dimension.
Definition at line 72 of file SubstanceAmount.hpp.
References value.
Referenced by PhQ::Dimensions::JSON(), PhQ::Dimensions::XML(), and PhQ::Dimensions::YAML().
Member Data Documentation
value
int8_t PhQ::Dimension::SubstanceAmount::value {0} private
Value of this base physical dimension.
Definition at line 102 of file SubstanceAmount.hpp.
Referenced by Print(), and Value().
The documentation for this class was generated from the following file:
PhQ/Dimension/SubstanceAmount.hpp