Physical Quantities: PhQ::PlanarAcceleration< NumericType > Class Template Reference
PhQ::PlanarAcceleration< NumericType > Class Template Reference
Two-dimensional Euclidean acceleration vector in the XY plane. Contains two components in Cartesian coordinates: x and y. For a three-dimensional Euclidean acceleration vector, see PhQ::Acceleration. For scalar acceleration components or for the magnitude of an acceleration vector, see PhQ::ScalarAcceleration.
#include "PlanarAcceleration.hpp"
Public Member Functions
PlanarAcceleration ()=default
Default constructor. Constructs a planar acceleration vector with an uninitialized value.
PlanarAcceleration (const PlanarVector< NumericType > &value, const Unit::Acceleration unit)
Constructor. Constructs a planar acceleration vector with a given value expressed in a given acceleration unit.
PlanarAcceleration (const ScalarAcceleration< NumericType > &x, const ScalarAcceleration< NumericType > &y)
Constructor. Constructs a planar acceleration vector from a given set of scalar acceleration components.
constexpr PlanarAcceleration (const ScalarAcceleration< NumericType > &scalar_acceleration, const PlanarDirection< NumericType > &planar_direction)
Constructor. Constructs a planar acceleration vector from a given scalar acceleration magnitude and planar direction.
constexpr PlanarAcceleration (const Acceleration< NumericType > &acceleration)
Constructor. Constructs a planar acceleration vector from a given acceleration vector by projecting the acceleration vector onto the XY plane.
constexpr PlanarAcceleration (const PlanarVelocity< NumericType > &planar_velocity, const Time< NumericType > &time)
Constructor. Constructs a planar acceleration vector from a given planar velocity and time using the definition of acceleration.
constexpr PlanarAcceleration (const PlanarVelocity< NumericType > &planar_velocity, const Frequency< NumericType > &frequency)
Constructor. Constructs a planar acceleration vector from a given planar velocity and frequency using the definition of acceleration.
~PlanarAcceleration () noexcept=default
Destructor. Destroys this acceleration vector.
constexpr PlanarAcceleration (const PlanarAcceleration< NumericType > &other)=default
Copy constructor. Constructs a planar acceleration vector by copying another one.
template<typename OtherNumericType >
constexpr PlanarAcceleration (const PlanarAcceleration< OtherNumericType > &other)
Copy constructor. Constructs a planar acceleration vector by copying another one.
constexpr PlanarAcceleration (PlanarAcceleration< NumericType > &&other) noexcept=default
Move constructor. Constructs a planar acceleration vector by moving another one.
constexpr PlanarAcceleration< NumericType > & operator= (const PlanarAcceleration< NumericType > &other)=default
Copy assignment operator. Assigns this acceleration vector by copying another one.
template<typename OtherNumericType >
constexpr PlanarAcceleration< NumericType > & operator= (const PlanarAcceleration< OtherNumericType > &other)
Copy assignment operator. Assigns this acceleration vector by copying another one.
constexpr PlanarAcceleration< NumericType > & operator= (PlanarAcceleration< NumericType > &&other) noexcept=default
Move assignment operator. Assigns this acceleration vector by moving another one.
constexpr ScalarAcceleration< NumericType > x () const noexcept
Returns the x Cartesian component of this acceleration vector.
constexpr ScalarAcceleration< NumericType > y () const noexcept
Returns the y Cartesian component of this acceleration vector.
ScalarAcceleration< NumericType > Magnitude () const
Returns the magnitude of this acceleration vector.
PhQ::PlanarDirection< NumericType > PlanarDirection () const
Returns the planar direction of this acceleration vector.
PhQ::Angle< NumericType > Angle (const PlanarAcceleration< NumericType > &other) const
Returns the angle between this acceleration vector and another one.
constexpr PlanarAcceleration< NumericType > operator+ (const PlanarAcceleration< NumericType > &other) const
constexpr PlanarAcceleration< NumericType > operator- (const PlanarAcceleration< NumericType > &other) const
constexpr PlanarAcceleration< NumericType > operator* (const NumericType number) const
constexpr PlanarVelocity< NumericType > operator* (const Time< NumericType > &time) const
constexpr PlanarAcceleration< NumericType > operator/ (const NumericType number) const
constexpr PlanarVelocity< NumericType > operator/ (const Frequency< NumericType > &frequency) const
constexpr void operator+= (const PlanarAcceleration< NumericType > &other) noexcept
constexpr void operator-= (const PlanarAcceleration< NumericType > &other) noexcept
constexpr void operator*= (const NumericType number) noexcept
constexpr void operator/= (const NumericType number) noexcept
constexpr const PhQ::PlanarVector< NumericType > & Value () const noexcept
Value of this physical quantity expressed in its standard unit of measure.
PhQ::PlanarVector< NumericType > Value (const UnitType unit) const
Value of this physical quantity expressed in a given unit of measure.
template<UnitType NewUnit>
constexpr PhQ::PlanarVector< NumericType > StaticValue () const
Value of this physical quantity expressed in a given unit of measure. This method can be evaluated statically at compile-time.
constexpr PhQ::PlanarVector< NumericType > & MutableValue () noexcept
Returns the value of this physical quantity expressed in its standard unit of measure as a mutable value.
constexpr void SetValue (const PhQ::PlanarVector< NumericType > &value) noexcept
Sets the value of this physical quantity expressed in its standard unit of measure to the given value.
std::string Print () const
Prints this physical quantity as a string. This physical quantity's value is expressed in its standard unit of measure.
std::string Print (const UnitType unit) const
Prints this physical quantity as a string. This physical quantity's value is expressed in the given unit of measure.
std::string JSON () const
Serializes this physical quantity as a JSON message. This physical quantity's value is expressed in its standard unit of measure.
std::string JSON (const UnitType unit) const
Serializes this physical quantity as a JSON message. This physical quantity's value is expressed in the given unit of measure.
std::string XML () const
Serializes this physical quantity as an XML message. This physical quantity's value is expressed in its standard unit of measure.
std::string XML (const UnitType unit) const
Serializes this physical quantity as an XML message. This physical quantity's value is expressed in the given unit of measure.
std::string YAML () const
Serializes this physical quantity as a YAML message. This physical quantity's value is expressed in its standard unit of measure.
std::string YAML (const UnitType unit) const
Serializes this physical quantity as a YAML message. This physical quantity's value is expressed in the given unit of measure.
Static Public Member Functions
static constexpr PlanarAcceleration< NumericType > Zero ()
Statically creates a planar acceleration vector of zero.
template<Unit::Acceleration Unit>
static constexpr PlanarAcceleration< NumericType > Create (const NumericType x, const NumericType y)
Statically creates a planar acceleration vector from the given x and y Cartesian components expressed in a given acceleration unit.
template<Unit::Acceleration Unit>
static constexpr PlanarAcceleration< NumericType > Create (const std::array< NumericType, 2 > &x_y)
Statically creates a planar acceleration vector from the given x and y Cartesian components expressed in a given acceleration unit.
template<Unit::Acceleration Unit>
static constexpr PlanarAcceleration< NumericType > Create (const PlanarVector< NumericType > &value)
Statically creates a planar acceleration vector with a given value expressed in a given acceleration unit.
static constexpr const PhQ::Dimensions & Dimensions ()
Physical dimension set of this physical quantity.
static constexpr UnitType Unit ()
Standard unit of measure for this physical quantity. This physical quantity's value is stored internally in this unit of measure.
Protected Attributes
PhQ::PlanarVector< NumericType > value
Value of this physical quantity expressed in its standard unit of measure.
Private Member Functions
constexpr PlanarAcceleration (const PlanarVector< NumericType > &value)
Constructor. Constructs a planar acceleration vector with a given value expressed in the standard acceleration unit.
Detailed Description
template<typename NumericType = double>
class PhQ::PlanarAcceleration< NumericType >
Two-dimensional Euclidean acceleration vector in the XY plane. Contains two components in Cartesian coordinates: x and y. For a three-dimensional Euclidean acceleration vector, see PhQ::Acceleration. For scalar acceleration components or for the magnitude of an acceleration vector, see PhQ::ScalarAcceleration.
Definition at line 50 of file PlanarAcceleration.hpp.
Constructor & Destructor Documentation
PlanarAcceleration() [1/11]
template<typename NumericType = double> PhQ::PlanarAcceleration< NumericType >::PlanarAcceleration () default
Default constructor. Constructs a planar acceleration vector with an uninitialized value.
PlanarAcceleration() [2/11]
template<typename NumericType = double> PhQ::PlanarAcceleration< NumericType >::PlanarAcceleration (const PlanarVector< NumericType > & value, const Unit::Acceleration unit) inline
Constructor. Constructs a planar acceleration vector with a given value expressed in a given acceleration unit.
Definition at line 58 of file PlanarAcceleration.hpp.
PlanarAcceleration() [3/11]
template<typename NumericType = double> PhQ::PlanarAcceleration< NumericType >::PlanarAcceleration (const ScalarAcceleration< NumericType > & x, const ScalarAcceleration< NumericType > & y) inline
Constructor. Constructs a planar acceleration vector from a given set of scalar acceleration components.
Definition at line 63 of file PlanarAcceleration.hpp.
References PhQ::PlanarAcceleration< NumericType >::x(), and PhQ::PlanarAcceleration< NumericType >::y().
PlanarAcceleration() [4/11]
template<typename NumericType = double> constexpr PhQ::PlanarAcceleration< NumericType >::PlanarAcceleration (const ScalarAcceleration< NumericType > & scalar_acceleration, const PlanarDirection< NumericType > & planar_direction) inline constexpr
Constructor. Constructs a planar acceleration vector from a given scalar acceleration magnitude and planar direction.
Definition at line 69 of file PlanarAcceleration.hpp.
PlanarAcceleration() [5/11]
template<typename NumericType > constexpr PhQ::PlanarAcceleration< NumericType >::PlanarAcceleration (const Acceleration< NumericType > & acceleration) inline explicit constexpr
Constructor. Constructs a planar acceleration vector from a given acceleration vector by projecting the acceleration vector onto the XY plane.
Definition at line 287 of file Acceleration.hpp.
References PhQ::DimensionalVector< UnitType, NumericType >::Value().
PlanarAcceleration() [6/11]
template<typename NumericType = double> constexpr PhQ::PlanarAcceleration< NumericType >::PlanarAcceleration (const PlanarVelocity< NumericType > & planar_velocity, const Time< NumericType > & time) inline constexpr
Constructor. Constructs a planar acceleration vector from a given planar velocity and time using the definition of acceleration.
Definition at line 79 of file PlanarAcceleration.hpp.
PlanarAcceleration() [7/11]
template<typename NumericType = double> constexpr PhQ::PlanarAcceleration< NumericType >::PlanarAcceleration (const PlanarVelocity< NumericType > & planar_velocity, const Frequency< NumericType > & frequency) inline constexpr
Constructor. Constructs a planar acceleration vector from a given planar velocity and frequency using the definition of acceleration.
Definition at line 85 of file PlanarAcceleration.hpp.
~PlanarAcceleration()
template<typename NumericType = double> PhQ::PlanarAcceleration< NumericType >::~PlanarAcceleration () default noexcept
Destructor. Destroys this acceleration vector.
PlanarAcceleration() [8/11]
template<typename NumericType = double> constexpr PhQ::PlanarAcceleration< NumericType >::PlanarAcceleration (const PlanarAcceleration< NumericType > & other) constexpr default
Copy constructor. Constructs a planar acceleration vector by copying another one.
PlanarAcceleration() [9/11]
template<typename NumericType = double> template<typename OtherNumericType > constexpr PhQ::PlanarAcceleration< NumericType >::PlanarAcceleration (const PlanarAcceleration< OtherNumericType > & other) inline explicit constexpr
Copy constructor. Constructs a planar acceleration vector by copying another one.
Definition at line 97 of file PlanarAcceleration.hpp.
PlanarAcceleration() [10/11]
template<typename NumericType = double> constexpr PhQ::PlanarAcceleration< NumericType >::PlanarAcceleration (PlanarAcceleration< NumericType > && other) constexpr default noexcept
Move constructor. Constructs a planar acceleration vector by moving another one.
PlanarAcceleration() [11/11]
template<typename NumericType = double> constexpr PhQ::PlanarAcceleration< NumericType >::PlanarAcceleration (const PlanarVector< NumericType > & value) inline explicit constexpr private
Constructor. Constructs a planar acceleration vector with a given value expressed in the standard acceleration unit.
Definition at line 223 of file PlanarAcceleration.hpp.
Member Function Documentation
Angle()
template<typename NumericType = double> PhQ::Angle< NumericType > PhQ::PlanarAcceleration< NumericType >::Angle (const PlanarAcceleration< NumericType > & other) const inline
Returns the angle between this acceleration vector and another one.
Definition at line 174 of file PlanarAcceleration.hpp.
Create() [1/3]
template<typename NumericType = double> template<Unit::Acceleration Unit> static constexpr PlanarAcceleration< NumericType > PhQ::PlanarAcceleration< NumericType >::Create (const NumericType x, const NumericType y) inline static constexpr
Statically creates a planar acceleration vector from the given x and y Cartesian components expressed in a given acceleration unit.
Definition at line 127 of file PlanarAcceleration.hpp.
References PhQ::PlanarAcceleration< NumericType >::x(), and PhQ::PlanarAcceleration< NumericType >::y().
Create() [2/3]
template<typename NumericType = double> template<Unit::Acceleration Unit> static constexpr PlanarAcceleration< NumericType > PhQ::PlanarAcceleration< NumericType >::Create (const PlanarVector< NumericType > & value) inline static constexpr
Statically creates a planar acceleration vector with a given value expressed in a given acceleration unit.
Definition at line 147 of file PlanarAcceleration.hpp.
References PhQ::DimensionalPlanarVector< UnitType, NumericType >::value.
Create() [3/3]
template<typename NumericType = double> template<Unit::Acceleration Unit> static constexpr PlanarAcceleration< NumericType > PhQ::PlanarAcceleration< NumericType >::Create (const std::array< NumericType, 2 > & x_y) inline static constexpr
Statically creates a planar acceleration vector from the given x and y Cartesian components expressed in a given acceleration unit.
Definition at line 137 of file PlanarAcceleration.hpp.
Dimensions()
template<typename UnitType , typename NumericType = double> static constexpr const PhQ::Dimensions & PhQ::DimensionalPlanarVector< UnitType, NumericType >::Dimensions () inline static constexpr inherited
Physical dimension set of this physical quantity.
Definition at line 50 of file DimensionalPlanarVector.hpp.
JSON() [1/2]
template<typename UnitType , typename NumericType = double> std::string PhQ::DimensionalPlanarVector< UnitType, NumericType >::JSON () const inline inherited
Serializes this physical quantity as a JSON message. This physical quantity's value is expressed in its standard unit of measure.
Definition at line 103 of file DimensionalPlanarVector.hpp.
References PhQ::Abbreviation(), and PhQ::DimensionalPlanarVector< UnitType, NumericType >::value.
Referenced by PhQ::DimensionalPlanarVector< UnitType, NumericType >::JSON().
JSON() [2/2]
template<typename UnitType , typename NumericType = double> std::string PhQ::DimensionalPlanarVector< UnitType, NumericType >::JSON (const UnitType unit) const inline inherited
Serializes this physical quantity as a JSON message. This physical quantity's value is expressed in the given unit of measure.
Definition at line 113 of file DimensionalPlanarVector.hpp.
References PhQ::Abbreviation(), PhQ::DimensionalPlanarVector< UnitType, NumericType >::JSON(), and PhQ::DimensionalPlanarVector< UnitType, NumericType >::Value().
Magnitude()
template<typename NumericType = double> ScalarAcceleration< NumericType > PhQ::PlanarAcceleration< NumericType >::Magnitude () const inline
Returns the magnitude of this acceleration vector.
Definition at line 164 of file PlanarAcceleration.hpp.
References PhQ::DimensionalPlanarVector< UnitType, NumericType >::value.
MutableValue()
template<typename UnitType , typename NumericType = double> constexpr PhQ::PlanarVector< NumericType > & PhQ::DimensionalPlanarVector< UnitType, NumericType >::MutableValue () inline constexpr noexcept inherited
Returns the value of this physical quantity expressed in its standard unit of measure as a mutable value.
Definition at line 79 of file DimensionalPlanarVector.hpp.
References PhQ::DimensionalPlanarVector< UnitType, NumericType >::value.
operator*() [1/2]
template<typename NumericType = double> constexpr PlanarAcceleration< NumericType > PhQ::PlanarAcceleration< NumericType >::operator* (const NumericType number) const inline constexpr
Definition at line 188 of file PlanarAcceleration.hpp.
References PhQ::DimensionalPlanarVector< UnitType, NumericType >::value.
operator*() [2/2]
template<typename NumericType = double> constexpr PlanarVelocity< NumericType > PhQ::PlanarAcceleration< NumericType >::operator* (const Time< NumericType > & time) const inline constexpr
Definition at line 192 of file PlanarAcceleration.hpp.
operator*=()
template<typename NumericType = double> constexpr void PhQ::PlanarAcceleration< NumericType >::operator*= (const NumericType number) inline constexpr noexcept
Definition at line 212 of file PlanarAcceleration.hpp.
References PhQ::DimensionalPlanarVector< UnitType, NumericType >::value.
operator+()
template<typename NumericType = double> constexpr PlanarAcceleration< NumericType > PhQ::PlanarAcceleration< NumericType >::operator+ (const PlanarAcceleration< NumericType > & other) const inline constexpr
Definition at line 178 of file PlanarAcceleration.hpp.
References PhQ::DimensionalPlanarVector< UnitType, NumericType >::value.
operator+=()
template<typename NumericType = double> constexpr void PhQ::PlanarAcceleration< NumericType >::operator+= (const PlanarAcceleration< NumericType > & other) inline constexpr noexcept
Definition at line 204 of file PlanarAcceleration.hpp.
References PhQ::DimensionalPlanarVector< UnitType, NumericType >::value.
operator-()
template<typename NumericType = double> constexpr PlanarAcceleration< NumericType > PhQ::PlanarAcceleration< NumericType >::operator- (const PlanarAcceleration< NumericType > & other) const inline constexpr
Definition at line 183 of file PlanarAcceleration.hpp.
References PhQ::DimensionalPlanarVector< UnitType, NumericType >::value.
operator-=()
template<typename NumericType = double> constexpr void PhQ::PlanarAcceleration< NumericType >::operator-= (const PlanarAcceleration< NumericType > & other) inline constexpr noexcept
Definition at line 208 of file PlanarAcceleration.hpp.
References PhQ::DimensionalPlanarVector< UnitType, NumericType >::value.
operator/() [1/2]
template<typename NumericType = double> constexpr PlanarVelocity< NumericType > PhQ::PlanarAcceleration< NumericType >::operator/ (const Frequency< NumericType > & frequency) const inline constexpr
Definition at line 200 of file PlanarAcceleration.hpp.
operator/() [2/2]
template<typename NumericType = double> constexpr PlanarAcceleration< NumericType > PhQ::PlanarAcceleration< NumericType >::operator/ (const NumericType number) const inline constexpr
Definition at line 196 of file PlanarAcceleration.hpp.
References PhQ::DimensionalPlanarVector< UnitType, NumericType >::value.
operator/=()
template<typename NumericType = double> constexpr void PhQ::PlanarAcceleration< NumericType >::operator/= (const NumericType number) inline constexpr noexcept
Definition at line 216 of file PlanarAcceleration.hpp.
References PhQ::DimensionalPlanarVector< UnitType, NumericType >::value.
operator=() [1/3]
template<typename NumericType = double> constexpr PlanarAcceleration< NumericType > & PhQ::PlanarAcceleration< NumericType >::operator= (const PlanarAcceleration< NumericType > & other) constexpr default
Copy assignment operator. Assigns this acceleration vector by copying another one.
operator=() [2/3]
template<typename NumericType = double> template<typename OtherNumericType > constexpr PlanarAcceleration< NumericType > & PhQ::PlanarAcceleration< NumericType >::operator= (const PlanarAcceleration< OtherNumericType > & other) inline constexpr
Copy assignment operator. Assigns this acceleration vector by copying another one.
Definition at line 109 of file PlanarAcceleration.hpp.
References PhQ::DimensionalPlanarVector< UnitType, NumericType >::Value(), and PhQ::DimensionalPlanarVector< UnitType, NumericType >::value.
operator=() [3/3]
template<typename NumericType = double> constexpr PlanarAcceleration< NumericType > & PhQ::PlanarAcceleration< NumericType >::operator= (PlanarAcceleration< NumericType > && other) constexpr default noexcept
Move assignment operator. Assigns this acceleration vector by moving another one.
PlanarDirection()
template<typename NumericType = double> PhQ::PlanarDirection< NumericType > PhQ::PlanarAcceleration< NumericType >::PlanarDirection () const inline
Returns the planar direction of this acceleration vector.
Definition at line 169 of file PlanarAcceleration.hpp.
References PhQ::DimensionalPlanarVector< UnitType, NumericType >::value.
Print() [1/2]
template<typename UnitType , typename NumericType = double> std::string PhQ::DimensionalPlanarVector< UnitType, NumericType >::Print () const inline inherited
Prints this physical quantity as a string. This physical quantity's value is expressed in its standard unit of measure.
Definition at line 91 of file DimensionalPlanarVector.hpp.
References PhQ::Abbreviation(), and PhQ::DimensionalPlanarVector< UnitType, NumericType >::value.
Referenced by PhQ::operator<<(), PhQ::operator<<(), PhQ::operator<<(), PhQ::operator<<(), PhQ::operator<<(), PhQ::operator<<(), PhQ::operator<<(), and PhQ::operator<<().
Print() [2/2]
template<typename UnitType , typename NumericType = double> std::string PhQ::DimensionalPlanarVector< UnitType, NumericType >::Print (const UnitType unit) const inline inherited
Prints this physical quantity as a string. This physical quantity's value is expressed in the given unit of measure.
Definition at line 97 of file DimensionalPlanarVector.hpp.
References PhQ::Abbreviation(), and PhQ::DimensionalPlanarVector< UnitType, NumericType >::Value().
SetValue()
template<typename UnitType , typename NumericType = double> constexpr void PhQ::DimensionalPlanarVector< UnitType, NumericType >::SetValue (const PhQ::PlanarVector< NumericType > & value) inline constexpr noexcept inherited
Sets the value of this physical quantity expressed in its standard unit of measure to the given value.
Definition at line 85 of file DimensionalPlanarVector.hpp.
References PhQ::DimensionalPlanarVector< UnitType, NumericType >::value.
StaticValue()
template<typename UnitType , typename NumericType = double> template<UnitType NewUnit> constexpr PhQ::PlanarVector< NumericType > PhQ::DimensionalPlanarVector< UnitType, NumericType >::StaticValue () const inline constexpr inherited
Value of this physical quantity expressed in a given unit of measure. This method can be evaluated statically at compile-time.
Definition at line 73 of file DimensionalPlanarVector.hpp.
References PhQ::DimensionalPlanarVector< UnitType, NumericType >::value.
Unit()
template<typename UnitType , typename NumericType = double> static constexpr UnitType PhQ::DimensionalPlanarVector< UnitType, NumericType >::Unit () inline static constexpr inherited
Standard unit of measure for this physical quantity. This physical quantity's value is stored internally in this unit of measure.
Definition at line 56 of file DimensionalPlanarVector.hpp.
Value() [1/2]
template<typename UnitType , typename NumericType = double> constexpr const PhQ::PlanarVector< NumericType > & PhQ::DimensionalPlanarVector< UnitType, NumericType >::Value () const inline constexpr noexcept inherited
Value of this physical quantity expressed in its standard unit of measure.
Definition at line 61 of file DimensionalPlanarVector.hpp.
References PhQ::DimensionalPlanarVector< UnitType, NumericType >::value.
Referenced by PhQ::Acceleration< NumericType >::Acceleration(), PhQ::Displacement< NumericType >::Displacement(), PhQ::Force< NumericType >::Force(), PhQ::HeatFlux< NumericType >::HeatFlux(), PhQ::DimensionalPlanarVector< UnitType, NumericType >::JSON(), PhQ::PlanarPosition< NumericType >::operator+(), PhQ::PlanarDisplacement< NumericType >::operator+(), PhQ::PlanarPosition< NumericType >::operator-(), PhQ::PlanarDisplacement< NumericType >::operator-(), PhQ::DimensionalPlanarVector< UnitType, NumericType >::operator=(), PhQ::PlanarAcceleration< NumericType >::operator=(), PhQ::PlanarDisplacement< NumericType >::operator=(), PhQ::PlanarForce< NumericType >::operator=(), PhQ::PlanarHeatFlux< NumericType >::operator=(), PhQ::PlanarPosition< NumericType >::operator=(), PhQ::PlanarTemperatureGradient< NumericType >::operator=(), PhQ::PlanarTraction< NumericType >::operator=(), PhQ::PlanarVelocity< NumericType >::operator=(), PhQ::operator==(), PhQ::operator==(), PhQ::PlanarHeatFlux< NumericType >::PlanarHeatFlux(), PhQ::Position< NumericType >::Position(), PhQ::DimensionalPlanarVector< UnitType, NumericType >::Print(), PhQ::TemperatureGradient< NumericType >::TemperatureGradient(), PhQ::Traction< NumericType >::Traction(), PhQ::Velocity< NumericType >::Velocity(), PhQ::DimensionalPlanarVector< UnitType, NumericType >::XML(), and PhQ::DimensionalPlanarVector< UnitType, NumericType >::YAML().
Value() [2/2]
template<typename UnitType , typename NumericType = double> PhQ::PlanarVector< NumericType > PhQ::DimensionalPlanarVector< UnitType, NumericType >::Value (const UnitType unit) const inline inherited
Value of this physical quantity expressed in a given unit of measure.
Definition at line 66 of file DimensionalPlanarVector.hpp.
References PhQ::Convert(), and PhQ::DimensionalPlanarVector< UnitType, NumericType >::value.
x()
template<typename NumericType = double> constexpr ScalarAcceleration< NumericType > PhQ::PlanarAcceleration< NumericType >::x () const inline constexpr noexcept
Returns the x Cartesian component of this acceleration vector.
Definition at line 154 of file PlanarAcceleration.hpp.
References PhQ::DimensionalPlanarVector< UnitType, NumericType >::value.
Referenced by PhQ::PlanarAcceleration< NumericType >::Create(), and PhQ::PlanarAcceleration< NumericType >::PlanarAcceleration().
XML() [1/2]
template<typename UnitType , typename NumericType = double> std::string PhQ::DimensionalPlanarVector< UnitType, NumericType >::XML () const inline inherited
Serializes this physical quantity as an XML message. This physical quantity's value is expressed in its standard unit of measure.
Definition at line 123 of file DimensionalPlanarVector.hpp.
References PhQ::Abbreviation(), and PhQ::DimensionalPlanarVector< UnitType, NumericType >::value.
Referenced by PhQ::DimensionalPlanarVector< UnitType, NumericType >::XML().
XML() [2/2]
template<typename UnitType , typename NumericType = double> std::string PhQ::DimensionalPlanarVector< UnitType, NumericType >::XML (const UnitType unit) const inline inherited
Serializes this physical quantity as an XML message. This physical quantity's value is expressed in the given unit of measure.
Definition at line 133 of file DimensionalPlanarVector.hpp.
References PhQ::Abbreviation(), PhQ::DimensionalPlanarVector< UnitType, NumericType >::Value(), and PhQ::DimensionalPlanarVector< UnitType, NumericType >::XML().
y()
template<typename NumericType = double> constexpr ScalarAcceleration< NumericType > PhQ::PlanarAcceleration< NumericType >::y () const inline constexpr noexcept
Returns the y Cartesian component of this acceleration vector.
Definition at line 159 of file PlanarAcceleration.hpp.
References PhQ::DimensionalPlanarVector< UnitType, NumericType >::value.
Referenced by PhQ::PlanarAcceleration< NumericType >::Create(), and PhQ::PlanarAcceleration< NumericType >::PlanarAcceleration().
YAML() [1/2]
template<typename UnitType , typename NumericType = double> std::string PhQ::DimensionalPlanarVector< UnitType, NumericType >::YAML () const inline inherited
Serializes this physical quantity as a YAML message. This physical quantity's value is expressed in its standard unit of measure.
Definition at line 143 of file DimensionalPlanarVector.hpp.
References PhQ::Abbreviation(), and PhQ::DimensionalPlanarVector< UnitType, NumericType >::value.
Referenced by PhQ::DimensionalPlanarVector< UnitType, NumericType >::YAML().
YAML() [2/2]
template<typename UnitType , typename NumericType = double> std::string PhQ::DimensionalPlanarVector< UnitType, NumericType >::YAML (const UnitType unit) const inline inherited
Serializes this physical quantity as a YAML message. This physical quantity's value is expressed in the given unit of measure.
Definition at line 153 of file DimensionalPlanarVector.hpp.
References PhQ::Abbreviation(), PhQ::DimensionalPlanarVector< UnitType, NumericType >::Value(), and PhQ::DimensionalPlanarVector< UnitType, NumericType >::YAML().
Zero()
template<typename NumericType = double> static constexpr PlanarAcceleration< NumericType > PhQ::PlanarAcceleration< NumericType >::Zero () inline static constexpr
Statically creates a planar acceleration vector of zero.
Definition at line 120 of file PlanarAcceleration.hpp.
References PhQ::PlanarVector< NumericType >::Zero().
Member Data Documentation
value
template<typename UnitType , typename NumericType = double> PhQ::PlanarVector<NumericType> PhQ::DimensionalPlanarVector< UnitType, NumericType >::value protected inherited
Value of this physical quantity expressed in its standard unit of measure.
Definition at line 222 of file DimensionalPlanarVector.hpp.
Referenced by PhQ::PlanarAcceleration< NumericType >::Create(), PhQ::PlanarDisplacement< NumericType >::Create(), PhQ::PlanarForce< NumericType >::Create(), PhQ::PlanarHeatFlux< NumericType >::Create(), PhQ::PlanarPosition< NumericType >::Create(), PhQ::PlanarTemperatureGradient< NumericType >::Create(), PhQ::PlanarTraction< NumericType >::Create(), PhQ::PlanarVelocity< NumericType >::Create(), PhQ::DimensionalPlanarVector< UnitType, NumericType >::JSON(), PhQ::PlanarAcceleration< NumericType >::Magnitude(), PhQ::PlanarDisplacement< NumericType >::Magnitude(), PhQ::PlanarForce< NumericType >::Magnitude(), PhQ::PlanarHeatFlux< NumericType >::Magnitude(), PhQ::PlanarPosition< NumericType >::Magnitude(), PhQ::PlanarTemperatureGradient< NumericType >::Magnitude(), PhQ::PlanarTraction< NumericType >::Magnitude(), PhQ::PlanarVelocity< NumericType >::Magnitude(), PhQ::DimensionalPlanarVector< UnitType, NumericType >::MutableValue(), PhQ::PlanarAcceleration< NumericType >::operator*(), PhQ::PlanarDisplacement< NumericType >::operator*(), PhQ::PlanarForce< NumericType >::operator*(), PhQ::PlanarHeatFlux< NumericType >::operator*(), PhQ::PlanarPosition< NumericType >::operator*(), PhQ::PlanarTemperatureGradient< NumericType >::operator*(), PhQ::PlanarTraction< NumericType >::operator*(), PhQ::PlanarVelocity< NumericType >::operator*(), PhQ::PlanarAcceleration< NumericType >::operator*=(), PhQ::PlanarDisplacement< NumericType >::operator*=(), PhQ::PlanarForce< NumericType >::operator*=(), PhQ::PlanarHeatFlux< NumericType >::operator*=(), PhQ::PlanarPosition< NumericType >::operator*=(), PhQ::PlanarTemperatureGradient< NumericType >::operator*=(), PhQ::PlanarTraction< NumericType >::operator*=(), PhQ::PlanarVelocity< NumericType >::operator*=(), PhQ::PlanarAcceleration< NumericType >::operator+(), PhQ::PlanarDisplacement< NumericType >::operator+(), PhQ::PlanarPosition< NumericType >::operator+(), PhQ::PlanarForce< NumericType >::operator+(), PhQ::PlanarHeatFlux< NumericType >::operator+(), PhQ::PlanarPosition< NumericType >::operator+(), PhQ::PlanarTemperatureGradient< NumericType >::operator+(), PhQ::PlanarTraction< NumericType >::operator+(), PhQ::PlanarVelocity< NumericType >::operator+(), PhQ::PlanarAcceleration< NumericType >::operator+=(), PhQ::PlanarDisplacement< NumericType >::operator+=(), PhQ::PlanarPosition< NumericType >::operator+=(), PhQ::PlanarForce< NumericType >::operator+=(), PhQ::PlanarHeatFlux< NumericType >::operator+=(), PhQ::PlanarPosition< NumericType >::operator+=(), PhQ::PlanarTemperatureGradient< NumericType >::operator+=(), PhQ::PlanarTraction< NumericType >::operator+=(), PhQ::PlanarVelocity< NumericType >::operator+=(), PhQ::PlanarAcceleration< NumericType >::operator-(), PhQ::PlanarDisplacement< NumericType >::operator-(), PhQ::PlanarPosition< NumericType >::operator-(), PhQ::PlanarForce< NumericType >::operator-(), PhQ::PlanarHeatFlux< NumericType >::operator-(), PhQ::PlanarPosition< NumericType >::operator-(), PhQ::PlanarTemperatureGradient< NumericType >::operator-(), PhQ::PlanarTraction< NumericType >::operator-(), PhQ::PlanarVelocity< NumericType >::operator-(), PhQ::PlanarAcceleration< NumericType >::operator-=(), PhQ::PlanarDisplacement< NumericType >::operator-=(), PhQ::PlanarPosition< NumericType >::operator-=(), PhQ::PlanarForce< NumericType >::operator-=(), PhQ::PlanarHeatFlux< NumericType >::operator-=(), PhQ::PlanarPosition< NumericType >::operator-=(), PhQ::PlanarTemperatureGradient< NumericType >::operator-=(), PhQ::PlanarTraction< NumericType >::operator-=(), PhQ::PlanarVelocity< NumericType >::operator-=(), PhQ::PlanarAcceleration< NumericType >::operator/(), PhQ::PlanarDisplacement< NumericType >::operator/(), PhQ::PlanarForce< NumericType >::operator/(), PhQ::PlanarHeatFlux< NumericType >::operator/(), PhQ::PlanarPosition< NumericType >::operator/(), PhQ::PlanarTemperatureGradient< NumericType >::operator/(), PhQ::PlanarTraction< NumericType >::operator/(), PhQ::PlanarVelocity< NumericType >::operator/(), PhQ::PlanarAcceleration< NumericType >::operator/=(), PhQ::PlanarDisplacement< NumericType >::operator/=(), PhQ::PlanarForce< NumericType >::operator/=(), PhQ::PlanarHeatFlux< NumericType >::operator/=(), PhQ::PlanarPosition< NumericType >::operator/=(), PhQ::PlanarTemperatureGradient< NumericType >::operator/=(), PhQ::PlanarTraction< NumericType >::operator/=(), PhQ::PlanarVelocity< NumericType >::operator/=(), PhQ::DimensionalPlanarVector< UnitType, NumericType >::operator=(), PhQ::PlanarAcceleration< NumericType >::operator=(), PhQ::PlanarDisplacement< NumericType >::operator=(), PhQ::PlanarForce< NumericType >::operator=(), PhQ::PlanarHeatFlux< NumericType >::operator=(), PhQ::PlanarPosition< NumericType >::operator=(), PhQ::PlanarTemperatureGradient< NumericType >::operator=(), PhQ::PlanarTraction< NumericType >::operator=(), PhQ::PlanarVelocity< NumericType >::operator=(), PhQ::PlanarAcceleration< NumericType >::PlanarDirection(), PhQ::PlanarDisplacement< NumericType >::PlanarDirection(), PhQ::PlanarForce< NumericType >::PlanarDirection(), PhQ::PlanarHeatFlux< NumericType >::PlanarDirection(), PhQ::PlanarPosition< NumericType >::PlanarDirection(), PhQ::PlanarTemperatureGradient< NumericType >::PlanarDirection(), PhQ::PlanarTraction< NumericType >::PlanarDirection(), PhQ::PlanarVelocity< NumericType >::PlanarDirection(), PhQ::DimensionalPlanarVector< UnitType, NumericType >::Print(), PhQ::DimensionalPlanarVector< UnitType, NumericType >::SetValue(), PhQ::DimensionalPlanarVector< UnitType, NumericType >::StaticValue(), PhQ::DimensionalPlanarVector< UnitType, NumericType >::Value(), PhQ::DimensionalPlanarVector< UnitType, NumericType >::Value(), PhQ::PlanarAcceleration< NumericType >::x(), PhQ::PlanarDisplacement< NumericType >::x(), PhQ::PlanarForce< NumericType >::x(), PhQ::PlanarHeatFlux< NumericType >::x(), PhQ::PlanarPosition< NumericType >::x(), PhQ::PlanarTemperatureGradient< NumericType >::x(), PhQ::PlanarTraction< NumericType >::x(), PhQ::PlanarVelocity< NumericType >::x(), PhQ::DimensionalPlanarVector< UnitType, NumericType >::XML(), PhQ::PlanarAcceleration< NumericType >::y(), PhQ::PlanarDisplacement< NumericType >::y(), PhQ::PlanarForce< NumericType >::y(), PhQ::PlanarHeatFlux< NumericType >::y(), PhQ::PlanarPosition< NumericType >::y(), PhQ::PlanarTemperatureGradient< NumericType >::y(), PhQ::PlanarTraction< NumericType >::y(), PhQ::PlanarVelocity< NumericType >::y(), PhQ::DimensionalPlanarVector< UnitType, NumericType >::YAML(), and PhQ::PlanarDisplacement< NumericType >::z().
The documentation for this class was generated from the following files:
PhQ/Angle.hpp
PhQ/PlanarAcceleration.hpp
PhQ/Acceleration.hpp