Physical Quantities (PhQ): PhQ::Dimension::ElectricCurrent Class Reference
PhQ::Dimension::ElectricCurrent Class Reference
Base physical dimension of electric current. Typically denoted "I". One of seven independent base physical dimensions that form the physical dimension set of any unit of measure or physical quantity.
#include "ElectricCurrent.hpp"
Public Member Functions
constexpr ElectricCurrent ()=default
Default constructor. Constructs a base physical dimension of electric current with a value of zero.
constexpr ElectricCurrent (const int8_t value)
Constructor. Constructs a base physical dimension of electric current with a given value.
~ElectricCurrent () noexcept=default
Destructor. Destroys this base physical dimension of electric current.
constexpr ElectricCurrent (const ElectricCurrent &other)=default
Copy constructor. Constructs a base physical dimension of electric current by copying another one.
constexpr ElectricCurrent & operator= (const ElectricCurrent &other)=default
Copy assignment operator. Assigns the value of this base physical dimension of electric current by copying from another one.
constexpr ElectricCurrent (ElectricCurrent &&other) noexcept=default
Move constructor. Constructs a base physical dimension of electric current by moving another one.
constexpr ElectricCurrent & operator= (ElectricCurrent &&other) noexcept=default
Move assignment operator. Assigns the value of this base physical dimension of electric current by moving another one.
constexpr int8_t Value () const noexcept
Value of this base physical dimension.
std::string Print () const noexcept
Prints this base physical dimension as a string.
Static Public Member Functions
static std::string_view Abbreviation () noexcept
Abbreviation of this base physical dimension.
static std::string_view Label () noexcept
Label of this base physical dimension.
Private Attributes
int8_t value {0}
Value of this base physical dimension.
Detailed Description
Base physical dimension of electric current. Typically denoted "I". One of seven independent base physical dimensions that form the physical dimension set of any unit of measure or physical quantity.
Definition at line 42 of file ElectricCurrent.hpp.
Constructor & Destructor Documentation
ElectricCurrent() [1/4]
constexpr PhQ::Dimension::ElectricCurrent::ElectricCurrent () constexpr default
Default constructor. Constructs a base physical dimension of electric current with a value of zero.
ElectricCurrent() [2/4]
constexpr PhQ::Dimension::ElectricCurrent::ElectricCurrent (const int8_t value) inline explicit constexpr
Constructor. Constructs a base physical dimension of electric current with a given value.
Definition at line 50 of file ElectricCurrent.hpp.
~ElectricCurrent()
PhQ::Dimension::ElectricCurrent::~ElectricCurrent () default noexcept
Destructor. Destroys this base physical dimension of electric current.
ElectricCurrent() [3/4]
constexpr PhQ::Dimension::ElectricCurrent::ElectricCurrent (const ElectricCurrent & other) constexpr default
Copy constructor. Constructs a base physical dimension of electric current by copying another one.
ElectricCurrent() [4/4]
constexpr PhQ::Dimension::ElectricCurrent::ElectricCurrent (ElectricCurrent && other) constexpr default noexcept
Move constructor. Constructs a base physical dimension of electric current by moving another one.
Member Function Documentation
Abbreviation()
static std::string_view PhQ::Dimension::ElectricCurrent::Abbreviation () inline static noexcept
Abbreviation of this base physical dimension.
Definition at line 77 of file ElectricCurrent.hpp.
Referenced by Print().
Label()
static std::string_view PhQ::Dimension::ElectricCurrent::Label () inline static noexcept
Label of this base physical dimension.
Definition at line 82 of file ElectricCurrent.hpp.
Referenced by PhQ::Dimensions::JSON(), PhQ::Dimensions::XML(), and PhQ::Dimensions::YAML().
operator=() [1/2]
constexpr ElectricCurrent& PhQ::Dimension::ElectricCurrent::operator= (const ElectricCurrent & other) constexpr default
Copy assignment operator. Assigns the value of this base physical dimension of electric current by copying from another one.
operator=() [2/2]
constexpr ElectricCurrent& PhQ::Dimension::ElectricCurrent::operator= (ElectricCurrent && other) constexpr default noexcept
Move assignment operator. Assigns the value of this base physical dimension of electric current by moving another one.
Print()
std::string PhQ::Dimension::ElectricCurrent::Print () const inline noexcept
Prints this base physical dimension as a string.
Definition at line 87 of file ElectricCurrent.hpp.
References Abbreviation(), and value.
Referenced by PhQ::Dimension::operator<<(), and PhQ::Dimensions::Print().
Value()
constexpr int8_t PhQ::Dimension::ElectricCurrent::Value () const inline constexpr noexcept
Value of this base physical dimension.
Definition at line 72 of file ElectricCurrent.hpp.
References value.
Referenced by PhQ::Dimensions::JSON(), PhQ::Dimensions::XML(), and PhQ::Dimensions::YAML().
Member Data Documentation
value
int8_t PhQ::Dimension::ElectricCurrent::value {0} private
Value of this base physical dimension.
Definition at line 102 of file ElectricCurrent.hpp.
Referenced by Print(), and Value().
The documentation for this class was generated from the following file:
PhQ/Dimension/ElectricCurrent.hpp