Physical Quantities (PhQ): PhQ::DimensionlessScalar< NumericType > Class Template Reference
PhQ::DimensionlessScalar< NumericType > Class Template Reference
Abstract base class that represents any dimensionless scalar physical quantity. Such a physical quantity is composed only of a value where the value is a scalar number. Such a physical quantity has no unit of measure and no dimension set.
#include "DimensionlessScalar.hpp"
Public Member Functions
constexpr NumericType Value () const noexcept
Value of this physical quantity.
constexpr NumericType & MutableValue () noexcept
Returns the value of this physical quantity as a mutable value.
constexpr void SetValue (const NumericType value) noexcept
Sets the value of this physical quantity to the given value.
std::string Print () const
Prints this physical quantity as a string.
std::string JSON () const
Serializes this physical quantity as a JSON message.
std::string XML () const
Serializes this physical quantity as an XML message.
std::string YAML () const
Serializes this physical quantity as a YAML message.
Static Public Member Functions
static constexpr PhQ::Dimensions Dimensions ()
Physical dimension set of this physical quantity. Since this physical quantity is dimensionless, its physical dimension set is simply the null set.
Protected Member Functions
DimensionlessScalar ()=default
Default constructor. Constructs a dimensionless scalar physical quantity with an uninitialized value.
constexpr DimensionlessScalar (const NumericType value)
Constructor. Constructs a dimensionless scalar physical quantity with a given value.
~DimensionlessScalar () noexcept=default
Destructor. Destroys this dimensionless scalar physical quantity.
constexpr DimensionlessScalar (const DimensionlessScalar< NumericType > &other)=default
Copy constructor. Constructs a dimensionless scalar physical quantity by copying another one.
template<typename OtherNumericType >
constexpr DimensionlessScalar (const DimensionlessScalar< OtherNumericType > &other)
Copy constructor. Constructs a dimensionless scalar physical quantity by copying another one.
constexpr DimensionlessScalar (DimensionlessScalar< NumericType > &&other) noexcept=default
Move constructor. Constructs a dimensionless scalar physical quantity by moving another one.
constexpr DimensionlessScalar< NumericType > & operator= (const DimensionlessScalar< NumericType > &other)=default
Copy assignment operator. Assigns this dimensionless scalar physical quantity by copying another one.
template<typename OtherNumericType >
constexpr DimensionlessScalar< NumericType > & operator= (const DimensionlessScalar< OtherNumericType > &other)
Copy assignment operator. Assigns this dimensionless scalar physical quantity by copying another one.
constexpr DimensionlessScalar< NumericType > & operator= (DimensionlessScalar< NumericType > &&other) noexcept=default
Move assignment operator. Assigns this dimensionless scalar physical quantity by moving another one.
Protected Attributes
NumericType value
Value of this physical quantity.
Detailed Description
template<typename NumericType = double>
class PhQ::DimensionlessScalar< NumericType >
Abstract base class that represents any dimensionless scalar physical quantity. Such a physical quantity is composed only of a value where the value is a scalar number. Such a physical quantity has no unit of measure and no dimension set.
Definition at line 45 of file DimensionlessScalar.hpp.
Constructor & Destructor Documentation
DimensionlessScalar() [1/5]
template<typename NumericType = double> PhQ::DimensionlessScalar< NumericType >::DimensionlessScalar () protected default
Default constructor. Constructs a dimensionless scalar physical quantity with an uninitialized value.
DimensionlessScalar() [2/5]
template<typename NumericType = double> constexpr PhQ::DimensionlessScalar< NumericType >::DimensionlessScalar (const NumericType value) inline explicit constexpr protected
Constructor. Constructs a dimensionless scalar physical quantity with a given value.
Definition at line 98 of file DimensionlessScalar.hpp.
~DimensionlessScalar()
template<typename NumericType = double> PhQ::DimensionlessScalar< NumericType >::~DimensionlessScalar () protected default noexcept
Destructor. Destroys this dimensionless scalar physical quantity.
DimensionlessScalar() [3/5]
template<typename NumericType = double> constexpr PhQ::DimensionlessScalar< NumericType >::DimensionlessScalar (const DimensionlessScalar< NumericType > & other) constexpr protected default
Copy constructor. Constructs a dimensionless scalar physical quantity by copying another one.
DimensionlessScalar() [4/5]
template<typename NumericType = double> template<typename OtherNumericType > constexpr PhQ::DimensionlessScalar< NumericType >::DimensionlessScalar (const DimensionlessScalar< OtherNumericType > & other) inline explicit constexpr protected
Copy constructor. Constructs a dimensionless scalar physical quantity by copying another one.
Definition at line 110 of file DimensionlessScalar.hpp.
DimensionlessScalar() [5/5]
template<typename NumericType = double> constexpr PhQ::DimensionlessScalar< NumericType >::DimensionlessScalar (DimensionlessScalar< NumericType > && other) constexpr protected default noexcept
Move constructor. Constructs a dimensionless scalar physical quantity by moving another one.
Member Function Documentation
Dimensions()
template<typename NumericType = double> static constexpr PhQ::Dimensions PhQ::DimensionlessScalar< NumericType >::Dimensions () inline static constexpr
Physical dimension set of this physical quantity. Since this physical quantity is dimensionless, its physical dimension set is simply the null set.
Definition at line 53 of file DimensionlessScalar.hpp.
References PhQ::Dimensionless.
JSON()
template<typename NumericType = double> std::string PhQ::DimensionlessScalar< NumericType >::JSON () const inline
Serializes this physical quantity as a JSON message.
Definition at line 78 of file DimensionlessScalar.hpp.
References PhQ::Print(), and PhQ::DimensionlessScalar< NumericType >::value.
MutableValue()
template<typename NumericType = double> constexpr NumericType& PhQ::DimensionlessScalar< NumericType >::MutableValue () inline constexpr noexcept
Returns the value of this physical quantity as a mutable value.
Definition at line 63 of file DimensionlessScalar.hpp.
References PhQ::DimensionlessScalar< NumericType >::value.
operator=() [1/3]
template<typename NumericType = double> constexpr DimensionlessScalar<NumericType>& PhQ::DimensionlessScalar< NumericType >::operator= (const DimensionlessScalar< NumericType > & other) constexpr protected default
Copy assignment operator. Assigns this dimensionless scalar physical quantity by copying another one.
operator=() [2/3]
template<typename NumericType = double> template<typename OtherNumericType > constexpr DimensionlessScalar<NumericType>& PhQ::DimensionlessScalar< NumericType >::operator= (const DimensionlessScalar< OtherNumericType > & other) inline constexpr protected
Copy assignment operator. Assigns this dimensionless scalar physical quantity by copying another one.
Definition at line 125 of file DimensionlessScalar.hpp.
References PhQ::DimensionlessScalar< NumericType >::Value(), and PhQ::DimensionlessScalar< NumericType >::value.
operator=() [3/3]
template<typename NumericType = double> constexpr DimensionlessScalar<NumericType>& PhQ::DimensionlessScalar< NumericType >::operator= (DimensionlessScalar< NumericType > && other) constexpr protected default noexcept
Move assignment operator. Assigns this dimensionless scalar physical quantity by moving another one.
Print()
template<typename NumericType = double> std::string PhQ::DimensionlessScalar< NumericType >::Print () const inline
Prints this physical quantity as a string.
Definition at line 73 of file DimensionlessScalar.hpp.
References PhQ::Print(), and PhQ::DimensionlessScalar< NumericType >::value.
Referenced by PhQ::operator<<().
SetValue()
template<typename NumericType = double> constexpr void PhQ::DimensionlessScalar< NumericType >::SetValue (const NumericType value) inline constexpr noexcept
Sets the value of this physical quantity to the given value.
Definition at line 68 of file DimensionlessScalar.hpp.
References PhQ::DimensionlessScalar< NumericType >::value.
Value()
template<typename NumericType = double> constexpr NumericType PhQ::DimensionlessScalar< NumericType >::Value () const inline constexpr noexcept
Value of this physical quantity.
Definition at line 58 of file DimensionlessScalar.hpp.
References PhQ::DimensionlessScalar< NumericType >::value.
Referenced by PhQ::operator*(), PhQ::DimensionlessScalar< NumericType >::operator=(), PhQ::HeatCapacityRatio< NumericType >::operator=(), PhQ::MachNumber< NumericType >::operator=(), PhQ::PoissonRatio< NumericType >::operator=(), PhQ::PrandtlNumber< NumericType >::operator=(), PhQ::ReynoldsNumber< NumericType >::operator=(), PhQ::ScalarDisplacementGradient< NumericType >::operator=(), and PhQ::ScalarStrain< NumericType >::operator=().
XML()
template<typename NumericType = double> std::string PhQ::DimensionlessScalar< NumericType >::XML () const inline
Serializes this physical quantity as an XML message.
Definition at line 83 of file DimensionlessScalar.hpp.
References PhQ::Print(), and PhQ::DimensionlessScalar< NumericType >::value.
YAML()
template<typename NumericType = double> std::string PhQ::DimensionlessScalar< NumericType >::YAML () const inline
Serializes this physical quantity as a YAML message.
Definition at line 88 of file DimensionlessScalar.hpp.
References PhQ::Print(), and PhQ::DimensionlessScalar< NumericType >::value.
Member Data Documentation
value
template<typename NumericType = double> NumericType PhQ::DimensionlessScalar< NumericType >::value protected
Value of this physical quantity.
Definition at line 137 of file DimensionlessScalar.hpp.
Referenced by PhQ::DimensionlessScalar< NumericType >::JSON(), PhQ::DimensionlessScalar< NumericType >::MutableValue(), PhQ::HeatCapacityRatio< NumericType >::operator+(), PhQ::MachNumber< NumericType >::operator+(), PhQ::PoissonRatio< NumericType >::operator+(), PhQ::PrandtlNumber< NumericType >::operator+(), PhQ::ReynoldsNumber< NumericType >::operator+(), PhQ::ScalarDisplacementGradient< NumericType >::operator+(), PhQ::ScalarStrain< NumericType >::operator+(), PhQ::HeatCapacityRatio< NumericType >::operator-(), PhQ::MachNumber< NumericType >::operator-(), PhQ::PoissonRatio< NumericType >::operator-(), PhQ::PrandtlNumber< NumericType >::operator-(), PhQ::ReynoldsNumber< NumericType >::operator-(), PhQ::ScalarDisplacementGradient< NumericType >::operator-(), PhQ::ScalarStrain< NumericType >::operator-(), PhQ::DimensionlessScalar< NumericType >::operator=(), PhQ::DimensionlessScalar< NumericType >::Print(), PhQ::DimensionlessScalar< NumericType >::SetValue(), PhQ::DimensionlessScalar< NumericType >::Value(), PhQ::DimensionlessScalar< NumericType >::XML(), and PhQ::DimensionlessScalar< NumericType >::YAML().
The documentation for this class was generated from the following file:
PhQ/DimensionlessScalar.hpp