Physical Quantities (PhQ): PhQ::PlanarVectorArea< Number > Class Template Reference
PhQ::PlanarVectorArea< Number > Class Template Reference
Planar vector-area in the XY plane. The planar vector analog to a scalar area. See also PhQ::Area.
#include "PlanarVectorArea.hpp"
Public Member Functions
PlanarVectorArea ()=default
Default constructor. Constructs a planar vector area with an uninitialized value.
PlanarVectorArea (const PlanarVector< Number > &value, const Unit::Area unit)
Constructor. Constructs a planar vector area with a given value expressed in a given area unit.
constexpr PlanarVectorArea (const Area< Number > &area, const PlanarDirection< Number > &planar_direction)
Constructor. Constructs a planar vector area from a given area and planar direction.
constexpr PlanarVectorArea (const VectorArea< Number > &vector_area)
Constructor. Constructs a planar vector area from a given vector area by projecting the vector area onto the XY plane.
~PlanarVectorArea () noexcept=default
Destructor. Destroys this planar vector area.
constexpr PlanarVectorArea (const PlanarVectorArea< Number > &other)=default
Copy constructor. Constructs a planar vector area by copying another one.
template<typename OtherNumber >
constexpr PlanarVectorArea (const PlanarVectorArea< OtherNumber > &other)
Copy constructor. Constructs a planar vector area by copying another one.
constexpr PlanarVectorArea (PlanarVectorArea< Number > &&other) noexcept=default
Move constructor. Constructs a planar vector area by moving another one.
constexpr PlanarVectorArea< Number > & operator= (const PlanarVectorArea< Number > &other)=default
Copy assignment operator. Assigns this planar vector area by copying another one.
template<typename OtherNumber >
constexpr PlanarVectorArea< Number > & operator= (const PlanarVectorArea< OtherNumber > &other)
Copy assignment operator. Assigns this planar vector area by copying another one.
constexpr PlanarVectorArea< Number > & operator= (PlanarVectorArea< Number > &&other) noexcept=default
Move assignment operator. Assigns this planar vector area by moving another one.
constexpr Area< Number > x () const noexcept
Returns the x Cartesian component of this planar vector area.
constexpr Area< Number > y () const noexcept
Returns the y Cartesian component of this planar vector area.
Area< Number > Magnitude () const
Returns the magnitude of this planar vector area.
PhQ::PlanarDirection< Number > PlanarDirection () const
Returns the planar direction of this planar vector area.
PhQ::Angle< Number > Angle (const PlanarVectorArea< Number > &planar_vector_area) const
Returns the angle between this planar vector area and another one.
constexpr PlanarVectorArea< Number > operator+ (const PlanarVectorArea< Number > &planar_vector_area) const
constexpr PlanarVectorArea< Number > operator- (const PlanarVectorArea< Number > &planar_vector_area) const
constexpr PlanarVectorArea< Number > operator* (const Number number) const
constexpr PlanarVectorArea< Number > operator/ (const Number number) const
constexpr void operator+= (const PlanarVectorArea< Number > &planar_vector_area) noexcept
constexpr void operator-= (const PlanarVectorArea< Number > &planar_vector_area) noexcept
constexpr void operator*= (const Number number) noexcept
constexpr void operator/= (const Number number) noexcept
constexpr const PhQ::PlanarVector< double > & Value () const noexcept
Value of this physical quantity expressed in its standard unit of measure.
PhQ::PlanarVector< double > Value (const Unit::Area unit) const
Value of this physical quantity expressed in a given unit of measure.
constexpr PhQ::PlanarVector< double > StaticValue () const
Value of this physical quantity expressed in a given unit of measure. This method can be evaluated statically at compile-time.
constexpr PhQ::PlanarVector< double > & MutableValue () noexcept
Returns the value of this physical quantity expressed in its standard unit of measure as a mutable value.
constexpr void SetValue (const PhQ::PlanarVector< double > &value) noexcept
Sets the value of this physical quantity expressed in its standard unit of measure to the given value.
std::string Print () const
Prints this physical quantity as a string. This physical quantity's value is expressed in its standard unit of measure.
std::string Print (const Unit::Area unit) const
Prints this physical quantity as a string. This physical quantity's value is expressed in the given unit of measure.
std::string JSON () const
Serializes this physical quantity as a JSON message. This physical quantity's value is expressed in its standard unit of measure.
std::string JSON (const Unit::Area unit) const
Serializes this physical quantity as a JSON message. This physical quantity's value is expressed in the given unit of measure.
std::string XML () const
Serializes this physical quantity as an XML message. This physical quantity's value is expressed in its standard unit of measure.
std::string XML (const Unit::Area unit) const
Serializes this physical quantity as an XML message. This physical quantity's value is expressed in the given unit of measure.
std::string YAML () const
Serializes this physical quantity as a YAML message. This physical quantity's value is expressed in its standard unit of measure.
std::string YAML (const Unit::Area unit) const
Serializes this physical quantity as a YAML message. This physical quantity's value is expressed in the given unit of measure.
Static Public Member Functions
static constexpr PlanarVectorArea< Number > Zero ()
Statically creates a planar vector area of zero.
template<Unit::Area Unit>
static constexpr PlanarVectorArea< Number > Create (const Number x, const Number y)
Statically creates a planar vector area from the given x and y Cartesian components expressed in a given area unit.
template<Unit::Area Unit>
static constexpr PlanarVectorArea< Number > Create (const std::array< Number, 2 > &x_y)
Statically creates a planar vector area from the given x and y Cartesian components expressed in a given area unit.
template<Unit::Area Unit>
static constexpr PlanarVectorArea< Number > Create (const PlanarVector< Number > &value)
Statically creates a planar vector area with a given value expressed in a given area unit.
static constexpr const PhQ::Dimensions & Dimensions ()
Physical dimension set of this physical quantity.
static constexpr Unit::Area Unit ()
Standard unit of measure for this physical quantity. This physical quantity's value is stored internally in this unit of measure.
Protected Attributes
PhQ::PlanarVector< double > value
Value of this physical quantity expressed in its standard unit of measure.
Private Member Functions
constexpr PlanarVectorArea (const PlanarVector< Number > &value)
Constructor. Constructs a planar vector area with a given value expressed in the standard area unit.
Detailed Description
template<typename Number = double>
class PhQ::PlanarVectorArea< Number >
Planar vector-area in the XY plane. The planar vector analog to a scalar area. See also PhQ::Area.
Definition at line 47 of file PlanarVectorArea.hpp.
Constructor & Destructor Documentation
PlanarVectorArea() [1/8]
template<typename Number = double> PhQ::PlanarVectorArea< Number >::PlanarVectorArea () default
Default constructor. Constructs a planar vector area with an uninitialized value.
PlanarVectorArea() [2/8]
template<typename Number = double> PhQ::PlanarVectorArea< Number >::PlanarVectorArea (const PlanarVector< Number > & value, const Unit::Area unit) inline
Constructor. Constructs a planar vector area with a given value expressed in a given area unit.
Definition at line 54 of file PlanarVectorArea.hpp.
PlanarVectorArea() [3/8]
template<typename Number = double> constexpr PhQ::PlanarVectorArea< Number >::PlanarVectorArea (const Area< Number > & area, const PlanarDirection< Number > & planar_direction) inline constexpr
Constructor. Constructs a planar vector area from a given area and planar direction.
Definition at line 58 of file PlanarVectorArea.hpp.
PlanarVectorArea() [4/8]
template<typename Number > constexpr PhQ::PlanarVectorArea< Number >::PlanarVectorArea (const VectorArea< Number > & vector_area) inline explicit constexpr
Constructor. Constructs a planar vector area from a given vector area by projecting the vector area onto the XY plane.
Definition at line 257 of file VectorArea.hpp.
References PhQ::DimensionalVector< UnitType, Number >::Value().
~PlanarVectorArea()
template<typename Number = double> PhQ::PlanarVectorArea< Number >::~PlanarVectorArea () default noexcept
Destructor. Destroys this planar vector area.
PlanarVectorArea() [5/8]
template<typename Number = double> constexpr PhQ::PlanarVectorArea< Number >::PlanarVectorArea (const PlanarVectorArea< Number > & other) constexpr default
Copy constructor. Constructs a planar vector area by copying another one.
PlanarVectorArea() [6/8]
template<typename Number = double> template<typename OtherNumber > constexpr PhQ::PlanarVectorArea< Number >::PlanarVectorArea (const PlanarVectorArea< OtherNumber > & other) inline explicit constexpr
Copy constructor. Constructs a planar vector area by copying another one.
Definition at line 74 of file PlanarVectorArea.hpp.
PlanarVectorArea() [7/8]
template<typename Number = double> constexpr PhQ::PlanarVectorArea< Number >::PlanarVectorArea (PlanarVectorArea< Number > && other) constexpr default noexcept
Move constructor. Constructs a planar vector area by moving another one.
PlanarVectorArea() [8/8]
template<typename Number = double> constexpr PhQ::PlanarVectorArea< Number >::PlanarVectorArea (const PlanarVector< Number > & value) inline explicit constexpr private
Constructor. Constructs a planar vector area with a given value expressed in the standard area unit.
Definition at line 185 of file PlanarVectorArea.hpp.
Member Function Documentation
Angle()
template<typename Number = double> PhQ::Angle<Number> PhQ::PlanarVectorArea< Number >::Angle (const PlanarVectorArea< Number > & planar_vector_area) const inline
Returns the angle between this planar vector area and another one.
Definition at line 144 of file PlanarVectorArea.hpp.
Create() [1/3]
template<typename Number = double> template<Unit::Area Unit> static constexpr PlanarVectorArea<Number> PhQ::PlanarVectorArea< Number >::Create (const Number x, const Number y) inline static constexpr
Statically creates a planar vector area from the given x and y Cartesian components expressed in a given area unit.
Definition at line 102 of file PlanarVectorArea.hpp.
References PhQ::PlanarVectorArea< Number >::x(), and PhQ::PlanarVectorArea< Number >::y().
Create() [2/3]
template<typename Number = double> template<Unit::Area Unit> static constexpr PlanarVectorArea<Number> PhQ::PlanarVectorArea< Number >::Create (const PlanarVector< Number > & value) inline static constexpr
Statically creates a planar vector area with a given value expressed in a given area unit.
Definition at line 118 of file PlanarVectorArea.hpp.
References PhQ::DimensionalPlanarVector< Unit::Area, double >::value.
Create() [3/3]
template<typename Number = double> template<Unit::Area Unit> static constexpr PlanarVectorArea<Number> PhQ::PlanarVectorArea< Number >::Create (const std::array< Number, 2 > & x_y) inline static constexpr
Statically creates a planar vector area from the given x and y Cartesian components expressed in a given area unit.
Definition at line 110 of file PlanarVectorArea.hpp.
Dimensions()
static constexpr const PhQ::Dimensions& PhQ::DimensionalPlanarVector< Unit::Area , double >::Dimensions () inline static constexpr inherited
Physical dimension set of this physical quantity.
Definition at line 49 of file DimensionalPlanarVector.hpp.
JSON() [1/2]
std::string PhQ::DimensionalPlanarVector< Unit::Area , double >::JSON () const inline inherited
Serializes this physical quantity as a JSON message. This physical quantity's value is expressed in its standard unit of measure.
Definition at line 104 of file DimensionalPlanarVector.hpp.
JSON() [2/2]
std::string PhQ::DimensionalPlanarVector< Unit::Area , double >::JSON (const Unit::Area unit) const inline inherited
Serializes this physical quantity as a JSON message. This physical quantity's value is expressed in the given unit of measure.
Definition at line 114 of file DimensionalPlanarVector.hpp.
Magnitude()
template<typename Number = double> Area<Number> PhQ::PlanarVectorArea< Number >::Magnitude () const inline
Returns the magnitude of this planar vector area.
Definition at line 134 of file PlanarVectorArea.hpp.
References PhQ::PlanarVector< Number >::Magnitude(), and PhQ::DimensionalPlanarVector< Unit::Area, double >::value.
MutableValue()
constexpr PhQ::PlanarVector<double >& PhQ::DimensionalPlanarVector< Unit::Area , double >::MutableValue () inline constexpr noexcept inherited
Returns the value of this physical quantity expressed in its standard unit of measure as a mutable value.
Definition at line 80 of file DimensionalPlanarVector.hpp.
operator*()
template<typename Number = double> constexpr PlanarVectorArea<Number> PhQ::PlanarVectorArea< Number >::operator* (const Number number) const inline constexpr
Definition at line 158 of file PlanarVectorArea.hpp.
References PhQ::DimensionalPlanarVector< Unit::Area, double >::value.
operator*=()
template<typename Number = double> constexpr void PhQ::PlanarVectorArea< Number >::operator*= (const Number number) inline constexpr noexcept
Definition at line 174 of file PlanarVectorArea.hpp.
References PhQ::DimensionalPlanarVector< Unit::Area, double >::value.
operator+()
template<typename Number = double> constexpr PlanarVectorArea<Number> PhQ::PlanarVectorArea< Number >::operator+ (const PlanarVectorArea< Number > & planar_vector_area) const inline constexpr
Definition at line 148 of file PlanarVectorArea.hpp.
References PhQ::DimensionalPlanarVector< UnitType, Number >::value, and PhQ::DimensionalPlanarVector< Unit::Area, double >::value.
operator+=()
template<typename Number = double> constexpr void PhQ::PlanarVectorArea< Number >::operator+= (const PlanarVectorArea< Number > & planar_vector_area) inline constexpr noexcept
Definition at line 166 of file PlanarVectorArea.hpp.
References PhQ::DimensionalPlanarVector< Unit::Area, double >::value.
operator-()
template<typename Number = double> constexpr PlanarVectorArea<Number> PhQ::PlanarVectorArea< Number >::operator- (const PlanarVectorArea< Number > & planar_vector_area) const inline constexpr
Definition at line 153 of file PlanarVectorArea.hpp.
References PhQ::DimensionalPlanarVector< UnitType, Number >::value, and PhQ::DimensionalPlanarVector< Unit::Area, double >::value.
operator-=()
template<typename Number = double> constexpr void PhQ::PlanarVectorArea< Number >::operator-= (const PlanarVectorArea< Number > & planar_vector_area) inline constexpr noexcept
Definition at line 170 of file PlanarVectorArea.hpp.
References PhQ::DimensionalPlanarVector< Unit::Area, double >::value.
operator/()
template<typename Number = double> constexpr PlanarVectorArea<Number> PhQ::PlanarVectorArea< Number >::operator/ (const Number number) const inline constexpr
Definition at line 162 of file PlanarVectorArea.hpp.
References PhQ::DimensionalPlanarVector< Unit::Area, double >::value.
operator/=()
template<typename Number = double> constexpr void PhQ::PlanarVectorArea< Number >::operator/= (const Number number) inline constexpr noexcept
Definition at line 178 of file PlanarVectorArea.hpp.
References PhQ::DimensionalPlanarVector< Unit::Area, double >::value.
operator=() [1/3]
template<typename Number = double> constexpr PlanarVectorArea<Number>& PhQ::PlanarVectorArea< Number >::operator= (const PlanarVectorArea< Number > & other) constexpr default
Copy assignment operator. Assigns this planar vector area by copying another one.
operator=() [2/3]
template<typename Number = double> template<typename OtherNumber > constexpr PlanarVectorArea<Number>& PhQ::PlanarVectorArea< Number >::operator= (const PlanarVectorArea< OtherNumber > & other) inline constexpr
Copy assignment operator. Assigns this planar vector area by copying another one.
Definition at line 85 of file PlanarVectorArea.hpp.
References PhQ::DimensionalPlanarVector< UnitType, Number >::Value(), and PhQ::DimensionalPlanarVector< Unit::Area, double >::value.
operator=() [3/3]
template<typename Number = double> constexpr PlanarVectorArea<Number>& PhQ::PlanarVectorArea< Number >::operator= (PlanarVectorArea< Number > && other) constexpr default noexcept
Move assignment operator. Assigns this planar vector area by moving another one.
PlanarDirection()
template<typename Number = double> PhQ::PlanarDirection<Number> PhQ::PlanarVectorArea< Number >::PlanarDirection () const inline
Returns the planar direction of this planar vector area.
Definition at line 139 of file PlanarVectorArea.hpp.
References PhQ::PlanarVector< Number >::PlanarDirection(), and PhQ::DimensionalPlanarVector< Unit::Area, double >::value.
Print() [1/2]
std::string PhQ::DimensionalPlanarVector< Unit::Area , double >::Print () const inline inherited
Prints this physical quantity as a string. This physical quantity's value is expressed in its standard unit of measure.
Definition at line 92 of file DimensionalPlanarVector.hpp.
Print() [2/2]
std::string PhQ::DimensionalPlanarVector< Unit::Area , double >::Print (const Unit::Area unit) const inline inherited
Prints this physical quantity as a string. This physical quantity's value is expressed in the given unit of measure.
Definition at line 98 of file DimensionalPlanarVector.hpp.
SetValue()
constexpr void PhQ::DimensionalPlanarVector< Unit::Area , double >::SetValue (const PhQ::PlanarVector< double > & value) inline constexpr noexcept inherited
Sets the value of this physical quantity expressed in its standard unit of measure to the given value.
Definition at line 86 of file DimensionalPlanarVector.hpp.
StaticValue()
constexpr PhQ::PlanarVector<double > PhQ::DimensionalPlanarVector< Unit::Area , double >::StaticValue () const inline constexpr inherited
Value of this physical quantity expressed in a given unit of measure. This method can be evaluated statically at compile-time.
Definition at line 74 of file DimensionalPlanarVector.hpp.
Unit()
static constexpr Unit::Area PhQ::DimensionalPlanarVector< Unit::Area , double >::Unit () inline static constexpr inherited
Standard unit of measure for this physical quantity. This physical quantity's value is stored internally in this unit of measure.
Definition at line 55 of file DimensionalPlanarVector.hpp.
Value() [1/2]
constexpr const PhQ::PlanarVector<double >& PhQ::DimensionalPlanarVector< Unit::Area , double >::Value () const inline constexpr noexcept inherited
Value of this physical quantity expressed in its standard unit of measure.
Definition at line 60 of file DimensionalPlanarVector.hpp.
Value() [2/2]
PhQ::PlanarVector<double > PhQ::DimensionalPlanarVector< Unit::Area , double >::Value (const Unit::Area unit) const inline inherited
Value of this physical quantity expressed in a given unit of measure.
Definition at line 65 of file DimensionalPlanarVector.hpp.
x()
template<typename Number = double> constexpr Area<Number> PhQ::PlanarVectorArea< Number >::x () const inline constexpr noexcept
Returns the x Cartesian component of this planar vector area.
Definition at line 124 of file PlanarVectorArea.hpp.
References PhQ::DimensionalPlanarVector< Unit::Area, double >::value, and PhQ::PlanarVector< Number >::x().
Referenced by PhQ::PlanarVectorArea< Number >::Create().
XML() [1/2]
std::string PhQ::DimensionalPlanarVector< Unit::Area , double >::XML () const inline inherited
Serializes this physical quantity as an XML message. This physical quantity's value is expressed in its standard unit of measure.
Definition at line 124 of file DimensionalPlanarVector.hpp.
XML() [2/2]
std::string PhQ::DimensionalPlanarVector< Unit::Area , double >::XML (const Unit::Area unit) const inline inherited
Serializes this physical quantity as an XML message. This physical quantity's value is expressed in the given unit of measure.
Definition at line 134 of file DimensionalPlanarVector.hpp.
y()
template<typename Number = double> constexpr Area<Number> PhQ::PlanarVectorArea< Number >::y () const inline constexpr noexcept
Returns the y Cartesian component of this planar vector area.
Definition at line 129 of file PlanarVectorArea.hpp.
References PhQ::DimensionalPlanarVector< Unit::Area, double >::value, and PhQ::PlanarVector< Number >::y().
Referenced by PhQ::PlanarVectorArea< Number >::Create().
YAML() [1/2]
std::string PhQ::DimensionalPlanarVector< Unit::Area , double >::YAML () const inline inherited
Serializes this physical quantity as a YAML message. This physical quantity's value is expressed in its standard unit of measure.
Definition at line 144 of file DimensionalPlanarVector.hpp.
YAML() [2/2]
std::string PhQ::DimensionalPlanarVector< Unit::Area , double >::YAML (const Unit::Area unit) const inline inherited
Serializes this physical quantity as a YAML message. This physical quantity's value is expressed in the given unit of measure.
Definition at line 154 of file DimensionalPlanarVector.hpp.
Zero()
template<typename Number = double> static constexpr PlanarVectorArea<Number> PhQ::PlanarVectorArea< Number >::Zero () inline static constexpr
Statically creates a planar vector area of zero.
Definition at line 95 of file PlanarVectorArea.hpp.
References PhQ::PlanarVector< Number >::Zero().
Member Data Documentation
value
PhQ::PlanarVector<double > PhQ::DimensionalPlanarVector< Unit::Area , double >::value protected inherited
Value of this physical quantity expressed in its standard unit of measure.
Definition at line 219 of file DimensionalPlanarVector.hpp.
The documentation for this class was generated from the following files:
PhQ/Angle.hpp
PhQ/PlanarVectorArea.hpp
PhQ/VectorArea.hpp