Physical Quantities: PhQ::DimensionalScalar< UnitType, NumericType > Class Template Reference
PhQ::DimensionalScalar< UnitType, NumericType > Class Template Reference
Abstract base class that represents any dimensional scalar physical quantity. Such a physical quantity is composed of a value and a unit of measure where the value is a scalar number.
#include "DimensionalScalar.hpp"
Public Member Functions
constexpr NumericType Value () const noexcept
Value of this physical quantity expressed in its standard unit of measure.
NumericType Value (const UnitType unit) const
Value of this physical quantity expressed in a given unit of measure.
template<UnitType NewUnit>
constexpr NumericType StaticValue () const
Value of this physical quantity expressed in a given unit of measure. This method can be evaluated statically at compile-time.
constexpr NumericType & MutableValue () noexcept
Returns the value of this physical quantity expressed in its standard unit of measure as a mutable value.
constexpr void SetValue (const NumericType value) noexcept
Sets the value of this physical quantity expressed in its standard unit of measure to the given value.
std::string Print () const
Prints this physical quantity as a string. This physical quantity's value is expressed in its standard unit of measure.
std::string Print (const UnitType unit) const
Prints this physical quantity as a string. This physical quantity's value is expressed in the given unit of measure.
std::string JSON () const
Serializes this physical quantity as a JSON message. This physical quantity's value is expressed in its standard unit of measure.
std::string JSON (const UnitType unit) const
Serializes this physical quantity as a JSON message. This physical quantity's value is expressed in the given unit of measure.
std::string XML () const
Serializes this physical quantity as an XML message. This physical quantity's value is expressed in its standard unit of measure.
std::string XML (const UnitType unit) const
Serializes this physical quantity as an XML message. This physical quantity's value is expressed in the given unit of measure.
std::string YAML () const
Serializes this physical quantity as a YAML message. This physical quantity's value is expressed in its standard unit of measure.
std::string YAML (const UnitType unit) const
Serializes this physical quantity as a YAML message. This physical quantity's value is expressed in the given unit of measure.
Static Public Member Functions
static constexpr const PhQ::Dimensions & Dimensions ()
Physical dimension set of this physical quantity.
static constexpr UnitType Unit ()
Standard unit of measure for this physical quantity. This physical quantity's value is stored internally in this unit of measure.
Protected Member Functions
DimensionalScalar ()=default
Default constructor. Constructs a dimensional scalar physical quantity with an uninitialized value.
constexpr DimensionalScalar (const NumericType value)
Constructor. Constructs a dimensional scalar physical quantity with a given value expressed in its standard unit of measure.
DimensionalScalar (const NumericType value, const UnitType unit)
Constructor. Constructs a dimensional scalar physical quantity with a given value expressed in a given unit of measure.
~DimensionalScalar () noexcept=default
Destructor. Destroys this dimensional scalar physical quantity.
constexpr DimensionalScalar (const DimensionalScalar< UnitType, NumericType > &other)=default
Copy constructor. Constructs a dimensional scalar physical quantity by copying another one.
template<typename OtherNumericType >
constexpr DimensionalScalar (const DimensionalScalar< UnitType, OtherNumericType > &other)
Copy constructor. Constructs a dimensional scalar physical quantity by copying another one.
constexpr DimensionalScalar (DimensionalScalar< UnitType, NumericType > &&other) noexcept=default
Move constructor. Constructs a dimensional scalar physical quantity by moving another one.
constexpr DimensionalScalar< UnitType, NumericType > & operator= (const DimensionalScalar< UnitType, NumericType > &other)=default
Copy assignment operator. Assigns this dimensional scalar physical quantity by copying another one.
template<typename OtherNumericType >
constexpr DimensionalScalar< UnitType, NumericType > & operator= (const DimensionalScalar< UnitType, OtherNumericType > &other)
Copy assignment operator. Assigns this dimensional scalar physical quantity by copying another one.
constexpr DimensionalScalar< UnitType, NumericType > & operator= (DimensionalScalar< UnitType, NumericType > &&other) noexcept=default
Move assignment operator. Assigns this dimensional scalar physical quantity by moving another one.
Protected Attributes
NumericType value
Value of this physical quantity expressed in its standard unit of measure.
Detailed Description
template<typename UnitType, typename NumericType = double>
class PhQ::DimensionalScalar< UnitType, NumericType >
Abstract base class that represents any dimensional scalar physical quantity. Such a physical quantity is composed of a value and a unit of measure where the value is a scalar number.
Template Parameters
UnitType Unit of measure enumeration type.
NumericType Floating-point numeric type: float, double, or long double. Defaults to double if unspecified.
Definition at line 47 of file DimensionalScalar.hpp.
Constructor & Destructor Documentation
DimensionalScalar() [1/6]
template<typename UnitType , typename NumericType = double> PhQ::DimensionalScalar< UnitType, NumericType >::DimensionalScalar () protected default
Default constructor. Constructs a dimensional scalar physical quantity with an uninitialized value.
DimensionalScalar() [2/6]
template<typename UnitType , typename NumericType = double> constexpr PhQ::DimensionalScalar< UnitType, NumericType >::DimensionalScalar (const NumericType value) inline explicit constexpr protected
Constructor. Constructs a dimensional scalar physical quantity with a given value expressed in its standard unit of measure.
Definition at line 172 of file DimensionalScalar.hpp.
DimensionalScalar() [3/6]
template<typename UnitType , typename NumericType = double> PhQ::DimensionalScalar< UnitType, NumericType >::DimensionalScalar (const NumericType value, const UnitType unit) inline protected
Constructor. Constructs a dimensional scalar physical quantity with a given value expressed in a given unit of measure.
Definition at line 176 of file DimensionalScalar.hpp.
References PhQ::ConvertInPlace().
~DimensionalScalar()
template<typename UnitType , typename NumericType = double> PhQ::DimensionalScalar< UnitType, NumericType >::~DimensionalScalar () protected default noexcept
Destructor. Destroys this dimensional scalar physical quantity.
DimensionalScalar() [4/6]
template<typename UnitType , typename NumericType = double> constexpr PhQ::DimensionalScalar< UnitType, NumericType >::DimensionalScalar (const DimensionalScalar< UnitType, NumericType > & other) constexpr protected default
Copy constructor. Constructs a dimensional scalar physical quantity by copying another one.
DimensionalScalar() [5/6]
template<typename UnitType , typename NumericType = double> template<typename OtherNumericType > constexpr PhQ::DimensionalScalar< UnitType, NumericType >::DimensionalScalar (const DimensionalScalar< UnitType, OtherNumericType > & other) inline explicit constexpr protected
Copy constructor. Constructs a dimensional scalar physical quantity by copying another one.
Template Parameters
OtherNumericType Floating-point numeric type of the other physical quantity. Deduced automatically.
Definition at line 192 of file DimensionalScalar.hpp.
DimensionalScalar() [6/6]
template<typename UnitType , typename NumericType = double> constexpr PhQ::DimensionalScalar< UnitType, NumericType >::DimensionalScalar (DimensionalScalar< UnitType, NumericType > && other) constexpr protected default noexcept
Move constructor. Constructs a dimensional scalar physical quantity by moving another one.
Member Function Documentation
Dimensions()
template<typename UnitType , typename NumericType = double> static constexpr const PhQ::Dimensions& PhQ::DimensionalScalar< UnitType, NumericType >::Dimensions () inline static constexpr
Physical dimension set of this physical quantity.
Definition at line 54 of file DimensionalScalar.hpp.
JSON() [1/2]
template<typename UnitType , typename NumericType = double> std::string PhQ::DimensionalScalar< UnitType, NumericType >::JSON () const inline
Serializes this physical quantity as a JSON message. This physical quantity's value is expressed in its standard unit of measure.
Definition at line 107 of file DimensionalScalar.hpp.
References PhQ::Abbreviation(), PhQ::Print(), and PhQ::DimensionalScalar< UnitType, NumericType >::value.
JSON() [2/2]
template<typename UnitType , typename NumericType = double> std::string PhQ::DimensionalScalar< UnitType, NumericType >::JSON (const UnitType unit) const inline
Serializes this physical quantity as a JSON message. This physical quantity's value is expressed in the given unit of measure.
Definition at line 117 of file DimensionalScalar.hpp.
References PhQ::Abbreviation(), PhQ::Print(), and PhQ::DimensionalScalar< UnitType, NumericType >::Value().
MutableValue()
template<typename UnitType , typename NumericType = double> constexpr NumericType& PhQ::DimensionalScalar< UnitType, NumericType >::MutableValue () inline constexpr noexcept
Returns the value of this physical quantity expressed in its standard unit of measure as a mutable value.
Definition at line 83 of file DimensionalScalar.hpp.
References PhQ::DimensionalScalar< UnitType, NumericType >::value.
operator=() [1/3]
template<typename UnitType , typename NumericType = double> constexpr DimensionalScalar<UnitType, NumericType>& PhQ::DimensionalScalar< UnitType, NumericType >::operator= (const DimensionalScalar< UnitType, NumericType > & other) constexpr protected default
Copy assignment operator. Assigns this dimensional scalar physical quantity by copying another one.
operator=() [2/3]
template<typename UnitType , typename NumericType = double> template<typename OtherNumericType > constexpr DimensionalScalar<UnitType, NumericType>& PhQ::DimensionalScalar< UnitType, NumericType >::operator= (const DimensionalScalar< UnitType, OtherNumericType > & other) inline constexpr protected
Copy assignment operator. Assigns this dimensional scalar physical quantity by copying another one.
Template Parameters
OtherNumericType Floating-point numeric type of the other physical quantity. Deduced automatically.
Definition at line 209 of file DimensionalScalar.hpp.
References PhQ::DimensionalScalar< UnitType, NumericType >::Value(), and PhQ::DimensionalScalar< UnitType, NumericType >::value.
operator=() [3/3]
template<typename UnitType , typename NumericType = double> constexpr DimensionalScalar<UnitType, NumericType>& PhQ::DimensionalScalar< UnitType, NumericType >::operator= (DimensionalScalar< UnitType, NumericType > && other) constexpr protected default noexcept
Move assignment operator. Assigns this dimensional scalar physical quantity by moving another one.
Print() [1/2]
template<typename UnitType , typename NumericType = double> std::string PhQ::DimensionalScalar< UnitType, NumericType >::Print () const inline
Prints this physical quantity as a string. This physical quantity's value is expressed in its standard unit of measure.
Definition at line 95 of file DimensionalScalar.hpp.
References PhQ::Abbreviation(), PhQ::Print(), and PhQ::DimensionalScalar< UnitType, NumericType >::value.
Referenced by PhQ::operator<<().
Print() [2/2]
template<typename UnitType , typename NumericType = double> std::string PhQ::DimensionalScalar< UnitType, NumericType >::Print (const UnitType unit) const inline
Prints this physical quantity as a string. This physical quantity's value is expressed in the given unit of measure.
Definition at line 101 of file DimensionalScalar.hpp.
References PhQ::Abbreviation(), PhQ::Print(), and PhQ::DimensionalScalar< UnitType, NumericType >::Value().
SetValue()
template<typename UnitType , typename NumericType = double> constexpr void PhQ::DimensionalScalar< UnitType, NumericType >::SetValue (const NumericType value) inline constexpr noexcept
Sets the value of this physical quantity expressed in its standard unit of measure to the given value.
Definition at line 89 of file DimensionalScalar.hpp.
References PhQ::DimensionalScalar< UnitType, NumericType >::value.
StaticValue()
template<typename UnitType , typename NumericType = double> template<UnitType NewUnit> constexpr NumericType PhQ::DimensionalScalar< UnitType, NumericType >::StaticValue () const inline constexpr
Value of this physical quantity expressed in a given unit of measure. This method can be evaluated statically at compile-time.
Definition at line 77 of file DimensionalScalar.hpp.
References PhQ::DimensionalScalar< UnitType, NumericType >::value.
Unit()
template<typename UnitType , typename NumericType = double> static constexpr UnitType PhQ::DimensionalScalar< UnitType, NumericType >::Unit () inline static constexpr
Standard unit of measure for this physical quantity. This physical quantity's value is stored internally in this unit of measure.
Definition at line 60 of file DimensionalScalar.hpp.
Value() [1/2]
template<typename UnitType , typename NumericType = double> constexpr NumericType PhQ::DimensionalScalar< UnitType, NumericType >::Value () const inline constexpr noexcept
Value of this physical quantity expressed in its standard unit of measure.
Definition at line 65 of file DimensionalScalar.hpp.
References PhQ::DimensionalScalar< UnitType, NumericType >::value.
Referenced by PhQ::DimensionalScalar< UnitType, NumericType >::JSON(), PhQ::Temperature< NumericType >::operator+(), PhQ::Temperature< NumericType >::operator-(), PhQ::Angle< NumericType >::operator=(), PhQ::AngularSpeed< NumericType >::operator=(), PhQ::Area< NumericType >::operator=(), PhQ::BulkDynamicViscosity< NumericType >::operator=(), PhQ::DimensionalScalar< UnitType, NumericType >::operator=(), PhQ::DynamicKinematicPressure< NumericType >::operator=(), PhQ::DynamicPressure< NumericType >::operator=(), PhQ::DynamicViscosity< NumericType >::operator=(), PhQ::ElectricCharge< NumericType >::operator=(), PhQ::ElectricCurrent< NumericType >::operator=(), PhQ::Energy< NumericType >::operator=(), PhQ::Frequency< NumericType >::operator=(), PhQ::GasConstant< NumericType >::operator=(), PhQ::IsentropicBulkModulus< NumericType >::operator=(), PhQ::IsobaricHeatCapacity< NumericType >::operator=(), PhQ::IsochoricHeatCapacity< NumericType >::operator=(), PhQ::IsothermalBulkModulus< NumericType >::operator=(), PhQ::KinematicViscosity< NumericType >::operator=(), PhQ::LameFirstModulus< NumericType >::operator=(), PhQ::Length< NumericType >::operator=(), PhQ::LinearThermalExpansionCoefficient< NumericType >::operator=(), PhQ::Mass< NumericType >::operator=(), PhQ::MassDensity< NumericType >::operator=(), PhQ::MassRate< NumericType >::operator=(), PhQ::Memory< NumericType >::operator=(), PhQ::MemoryRate< NumericType >::operator=(), PhQ::Power< NumericType >::operator=(), PhQ::PWaveModulus< NumericType >::operator=(), PhQ::ScalarAcceleration< NumericType >::operator=(), PhQ::ScalarAngularAcceleration< NumericType >::operator=(), PhQ::ScalarForce< NumericType >::operator=(), PhQ::ScalarHeatFlux< NumericType >::operator=(), PhQ::ScalarStrainRate< NumericType >::operator=(), PhQ::ScalarStress< NumericType >::operator=(), PhQ::ScalarTemperatureGradient< NumericType >::operator=(), PhQ::ScalarThermalConductivity< NumericType >::operator=(), PhQ::ScalarTraction< NumericType >::operator=(), PhQ::ScalarVelocityGradient< NumericType >::operator=(), PhQ::ShearModulus< NumericType >::operator=(), PhQ::SolidAngle< NumericType >::operator=(), PhQ::SoundSpeed< NumericType >::operator=(), PhQ::SpecificEnergy< NumericType >::operator=(), PhQ::SpecificGasConstant< NumericType >::operator=(), PhQ::SpecificIsobaricHeatCapacity< NumericType >::operator=(), PhQ::SpecificIsochoricHeatCapacity< NumericType >::operator=(), PhQ::SpecificPower< NumericType >::operator=(), PhQ::Speed< NumericType >::operator=(), PhQ::StaticKinematicPressure< NumericType >::operator=(), PhQ::StaticPressure< NumericType >::operator=(), PhQ::SubstanceAmount< NumericType >::operator=(), PhQ::Temperature< NumericType >::operator=(), PhQ::TemperatureDifference< NumericType >::operator=(), PhQ::ThermalDiffusivity< NumericType >::operator=(), PhQ::Time< NumericType >::operator=(), PhQ::TotalKinematicPressure< NumericType >::operator=(), PhQ::TotalPressure< NumericType >::operator=(), PhQ::TransportEnergyConsumption< NumericType >::operator=(), PhQ::Volume< NumericType >::operator=(), PhQ::VolumeRate< NumericType >::operator=(), PhQ::VolumetricThermalExpansionCoefficient< NumericType >::operator=(), PhQ::YoungModulus< NumericType >::operator=(), PhQ::DimensionalScalar< UnitType, NumericType >::Print(), PhQ::Stress< NumericType >::Stress(), PhQ::ThermalConductivity< NumericType >::ThermalConductivity(), PhQ::DimensionalScalar< UnitType, NumericType >::XML(), and PhQ::DimensionalScalar< UnitType, NumericType >::YAML().
Value() [2/2]
template<typename UnitType , typename NumericType = double> NumericType PhQ::DimensionalScalar< UnitType, NumericType >::Value (const UnitType unit) const inline
Value of this physical quantity expressed in a given unit of measure.
Definition at line 70 of file DimensionalScalar.hpp.
References PhQ::Convert(), and PhQ::DimensionalScalar< UnitType, NumericType >::value.
XML() [1/2]
template<typename UnitType , typename NumericType = double> std::string PhQ::DimensionalScalar< UnitType, NumericType >::XML () const inline
Serializes this physical quantity as an XML message. This physical quantity's value is expressed in its standard unit of measure.
Definition at line 127 of file DimensionalScalar.hpp.
References PhQ::Abbreviation(), PhQ::Print(), and PhQ::DimensionalScalar< UnitType, NumericType >::value.
XML() [2/2]
template<typename UnitType , typename NumericType = double> std::string PhQ::DimensionalScalar< UnitType, NumericType >::XML (const UnitType unit) const inline
Serializes this physical quantity as an XML message. This physical quantity's value is expressed in the given unit of measure.
Definition at line 137 of file DimensionalScalar.hpp.
References PhQ::Abbreviation(), PhQ::Print(), and PhQ::DimensionalScalar< UnitType, NumericType >::Value().
YAML() [1/2]
template<typename UnitType , typename NumericType = double> std::string PhQ::DimensionalScalar< UnitType, NumericType >::YAML () const inline
Serializes this physical quantity as a YAML message. This physical quantity's value is expressed in its standard unit of measure.
Definition at line 147 of file DimensionalScalar.hpp.
References PhQ::Abbreviation(), PhQ::Print(), and PhQ::DimensionalScalar< UnitType, NumericType >::value.
YAML() [2/2]
template<typename UnitType , typename NumericType = double> std::string PhQ::DimensionalScalar< UnitType, NumericType >::YAML (const UnitType unit) const inline
Serializes this physical quantity as a YAML message. This physical quantity's value is expressed in the given unit of measure.
Definition at line 157 of file DimensionalScalar.hpp.
References PhQ::Abbreviation(), PhQ::Print(), and PhQ::DimensionalScalar< UnitType, NumericType >::Value().
Member Data Documentation
value
template<typename UnitType , typename NumericType = double> NumericType PhQ::DimensionalScalar< UnitType, NumericType >::value protected
Value of this physical quantity expressed in its standard unit of measure.
Definition at line 221 of file DimensionalScalar.hpp.
Referenced by PhQ::DimensionalScalar< UnitType, NumericType >::JSON(), PhQ::DimensionalScalar< UnitType, NumericType >::MutableValue(), PhQ::Angle< NumericType >::operator+(), PhQ::AngularSpeed< NumericType >::operator+(), PhQ::Area< NumericType >::operator+(), PhQ::BulkDynamicViscosity< NumericType >::operator+(), PhQ::DynamicKinematicPressure< NumericType >::operator+(), PhQ::DynamicPressure< NumericType >::operator+(), PhQ::DynamicViscosity< NumericType >::operator+(), PhQ::ElectricCharge< NumericType >::operator+(), PhQ::ElectricCurrent< NumericType >::operator+(), PhQ::Energy< NumericType >::operator+(), PhQ::Frequency< NumericType >::operator+(), PhQ::GasConstant< NumericType >::operator+(), PhQ::IsentropicBulkModulus< NumericType >::operator+(), PhQ::IsobaricHeatCapacity< NumericType >::operator+(), PhQ::IsochoricHeatCapacity< NumericType >::operator+(), PhQ::IsothermalBulkModulus< NumericType >::operator+(), PhQ::KinematicViscosity< NumericType >::operator+(), PhQ::LameFirstModulus< NumericType >::operator+(), PhQ::Length< NumericType >::operator+(), PhQ::LinearThermalExpansionCoefficient< NumericType >::operator+(), PhQ::Mass< NumericType >::operator+(), PhQ::MassDensity< NumericType >::operator+(), PhQ::MassRate< NumericType >::operator+(), PhQ::Memory< NumericType >::operator+(), PhQ::MemoryRate< NumericType >::operator+(), PhQ::Power< NumericType >::operator+(), PhQ::PWaveModulus< NumericType >::operator+(), PhQ::ScalarAcceleration< NumericType >::operator+(), PhQ::ScalarAngularAcceleration< NumericType >::operator+(), PhQ::ScalarForce< NumericType >::operator+(), PhQ::ScalarHeatFlux< NumericType >::operator+(), PhQ::ScalarStrainRate< NumericType >::operator+(), PhQ::ScalarStress< NumericType >::operator+(), PhQ::ScalarTemperatureGradient< NumericType >::operator+(), PhQ::ScalarThermalConductivity< NumericType >::operator+(), PhQ::ScalarTraction< NumericType >::operator+(), PhQ::ScalarVelocityGradient< NumericType >::operator+(), PhQ::ShearModulus< NumericType >::operator+(), PhQ::SolidAngle< NumericType >::operator+(), PhQ::SoundSpeed< NumericType >::operator+(), PhQ::SpecificEnergy< NumericType >::operator+(), PhQ::SpecificGasConstant< NumericType >::operator+(), PhQ::SpecificIsobaricHeatCapacity< NumericType >::operator+(), PhQ::SpecificIsochoricHeatCapacity< NumericType >::operator+(), PhQ::SpecificPower< NumericType >::operator+(), PhQ::Speed< NumericType >::operator+(), PhQ::StaticKinematicPressure< NumericType >::operator+(), PhQ::StaticPressure< NumericType >::operator+(), PhQ::SubstanceAmount< NumericType >::operator+(), PhQ::Temperature< NumericType >::operator+(), PhQ::TemperatureDifference< NumericType >::operator+(), PhQ::ThermalDiffusivity< NumericType >::operator+(), PhQ::Time< NumericType >::operator+(), PhQ::TotalKinematicPressure< NumericType >::operator+(), PhQ::TotalPressure< NumericType >::operator+(), PhQ::TransportEnergyConsumption< NumericType >::operator+(), PhQ::Volume< NumericType >::operator+(), PhQ::VolumeRate< NumericType >::operator+(), PhQ::VolumetricThermalExpansionCoefficient< NumericType >::operator+(), PhQ::YoungModulus< NumericType >::operator+(), PhQ::Angle< NumericType >::operator-(), PhQ::AngularSpeed< NumericType >::operator-(), PhQ::Area< NumericType >::operator-(), PhQ::BulkDynamicViscosity< NumericType >::operator-(), PhQ::DynamicKinematicPressure< NumericType >::operator-(), PhQ::DynamicPressure< NumericType >::operator-(), PhQ::DynamicViscosity< NumericType >::operator-(), PhQ::ElectricCharge< NumericType >::operator-(), PhQ::ElectricCurrent< NumericType >::operator-(), PhQ::Energy< NumericType >::operator-(), PhQ::Frequency< NumericType >::operator-(), PhQ::GasConstant< NumericType >::operator-(), PhQ::IsentropicBulkModulus< NumericType >::operator-(), PhQ::IsobaricHeatCapacity< NumericType >::operator-(), PhQ::IsochoricHeatCapacity< NumericType >::operator-(), PhQ::IsothermalBulkModulus< NumericType >::operator-(), PhQ::KinematicViscosity< NumericType >::operator-(), PhQ::LameFirstModulus< NumericType >::operator-(), PhQ::Length< NumericType >::operator-(), PhQ::LinearThermalExpansionCoefficient< NumericType >::operator-(), PhQ::Mass< NumericType >::operator-(), PhQ::MassDensity< NumericType >::operator-(), PhQ::MassRate< NumericType >::operator-(), PhQ::Memory< NumericType >::operator-(), PhQ::MemoryRate< NumericType >::operator-(), PhQ::Power< NumericType >::operator-(), PhQ::PWaveModulus< NumericType >::operator-(), PhQ::ScalarAcceleration< NumericType >::operator-(), PhQ::ScalarAngularAcceleration< NumericType >::operator-(), PhQ::ScalarForce< NumericType >::operator-(), PhQ::ScalarHeatFlux< NumericType >::operator-(), PhQ::ScalarStrainRate< NumericType >::operator-(), PhQ::ScalarStress< NumericType >::operator-(), PhQ::ScalarTemperatureGradient< NumericType >::operator-(), PhQ::ScalarThermalConductivity< NumericType >::operator-(), PhQ::ScalarTraction< NumericType >::operator-(), PhQ::ScalarVelocityGradient< NumericType >::operator-(), PhQ::ShearModulus< NumericType >::operator-(), PhQ::SolidAngle< NumericType >::operator-(), PhQ::SoundSpeed< NumericType >::operator-(), PhQ::SpecificEnergy< NumericType >::operator-(), PhQ::SpecificGasConstant< NumericType >::operator-(), PhQ::SpecificIsobaricHeatCapacity< NumericType >::operator-(), PhQ::SpecificIsochoricHeatCapacity< NumericType >::operator-(), PhQ::SpecificPower< NumericType >::operator-(), PhQ::Speed< NumericType >::operator-(), PhQ::StaticKinematicPressure< NumericType >::operator-(), PhQ::StaticPressure< NumericType >::operator-(), PhQ::SubstanceAmount< NumericType >::operator-(), PhQ::Temperature< NumericType >::operator-(), PhQ::TemperatureDifference< NumericType >::operator-(), PhQ::ThermalDiffusivity< NumericType >::operator-(), PhQ::Time< NumericType >::operator-(), PhQ::TotalKinematicPressure< NumericType >::operator-(), PhQ::TotalPressure< NumericType >::operator-(), PhQ::TransportEnergyConsumption< NumericType >::operator-(), PhQ::Volume< NumericType >::operator-(), PhQ::VolumeRate< NumericType >::operator-(), PhQ::VolumetricThermalExpansionCoefficient< NumericType >::operator-(), PhQ::YoungModulus< NumericType >::operator-(), PhQ::DimensionalScalar< UnitType, NumericType >::operator=(), PhQ::DimensionalScalar< UnitType, NumericType >::Print(), PhQ::DimensionalScalar< UnitType, NumericType >::SetValue(), PhQ::DimensionalScalar< UnitType, NumericType >::StaticValue(), PhQ::DimensionalScalar< UnitType, NumericType >::Value(), PhQ::DimensionalScalar< UnitType, NumericType >::XML(), and PhQ::DimensionalScalar< UnitType, NumericType >::YAML().
The documentation for this class was generated from the following file:
PhQ/DimensionalScalar.hpp