Physical Quantities: PhQ::Traction< NumericType > Class Template Reference
PhQ::Traction< NumericType > Class Template Reference
Three-dimensional Euclidean traction vector. Contains three components in Cartesian coordinates: x, y, and z. Traction is similar to pressure; however, traction can act in any direction, whereas pressure always acts compressively perpendicular to a surface. For a two-dimensional Euclidean traction vector in the XY plane, see PhQ::PlanarTraction. For scalar traction components or for the magnitude of a traction vector, see PhQ::ScalarTraction.
#include "Traction.hpp"
Public Member Functions
Traction ()=default
Default constructor. Constructs a traction vector with an uninitialized value.
Traction (const Vector< NumericType > &value, const Unit::Pressure unit)
Constructor. Constructs a traction vector with a given value expressed in a given pressure unit.
Traction (const ScalarTraction< NumericType > &x, const ScalarTraction< NumericType > &y, const ScalarTraction< NumericType > &z)
Constructor. Constructs a traction vector from a given set of scalar traction components.
constexpr Traction (const ScalarTraction< NumericType > &scalar_traction, const Direction< NumericType > &direction)
Constructor. Constructs a traction vector from a given scalar traction and direction.
constexpr Traction (const PlanarTraction< NumericType > &planar_traction)
Constructor. Constructs a traction vector from a given planar traction vector in the XY plane. This traction vector's z-component is initialized to zero.
constexpr Traction (const Force< NumericType > &force, const Area< NumericType > &area)
Constructor. Constructs a traction vector from a given force and area using the definition of traction.
constexpr Traction (const Stress< NumericType > &stress, const Direction< NumericType > &direction)
Constructor. Constructs a traction vector from a given stress and direction using the definition of traction.
~Traction () noexcept=default
Destructor. Destroys this traction vector.
constexpr Traction (const Traction< NumericType > &other)=default
Copy constructor. Constructs a traction vector by copying another one.
template<typename OtherNumericType >
constexpr Traction (const Traction< OtherNumericType > &other)
Copy constructor. Constructs a traction vector by copying another one.
constexpr Traction (Traction< NumericType > &&other) noexcept=default
Move constructor. Constructs a traction vector by moving another one.
constexpr Traction< NumericType > & operator= (const Traction< NumericType > &other)=default
Copy assignment operator. Assigns this traction vector by copying another one.
template<typename OtherNumericType >
constexpr Traction< NumericType > & operator= (const Traction< OtherNumericType > &other)
Copy assignment operator. Assigns this traction vector by copying another one.
constexpr Traction< NumericType > & operator= (Traction< NumericType > &&other) noexcept=default
Move assignment operator. Assigns this traction vector by moving another one.
constexpr ScalarTraction< NumericType > x () const noexcept
Returns the x Cartesian component of this traction vector.
constexpr ScalarTraction< NumericType > y () const noexcept
Returns the y Cartesian component of this traction vector.
constexpr ScalarTraction< NumericType > z () const noexcept
Returns the z Cartesian component of this traction vector.
ScalarTraction< NumericType > Magnitude () const
Returns the magnitude of this traction vector.
PhQ::Direction< NumericType > Direction () const
Returns the direction of this traction vector.
PhQ::Angle< NumericType > Angle (const Traction< NumericType > &traction) const
Returns the angle between this traction vector and another one.
constexpr Traction< NumericType > operator+ (const Traction< NumericType > &traction) const
constexpr Traction< NumericType > operator- (const Traction< NumericType > &traction) const
constexpr Traction< NumericType > operator* (const NumericType number) const
constexpr Force< NumericType > operator* (const Area< NumericType > &area) const
constexpr Traction< NumericType > operator/ (const NumericType number) const
constexpr void operator+= (const Traction< NumericType > &traction) noexcept
constexpr void operator-= (const Traction< NumericType > &traction) noexcept
constexpr void operator*= (const NumericType number) noexcept
constexpr void operator/= (const NumericType number) noexcept
constexpr const PhQ::Vector< NumericType > & Value () const noexcept
Value of this physical quantity expressed in its standard unit of measure.
PhQ::Vector< NumericType > Value (const UnitType unit) const
Value of this physical quantity expressed in a given unit of measure.
template<UnitType NewUnit>
constexpr PhQ::Vector< NumericType > StaticValue () const
Value of this physical quantity expressed in a given unit of measure. This method can be evaluated statically at compile-time.
constexpr PhQ::Vector< NumericType > & MutableValue () noexcept
Returns the value of this physical quantity expressed in its standard unit of measure as a mutable value.
constexpr void SetValue (const PhQ::Vector< NumericType > &value) noexcept
Sets the value of this physical quantity expressed in its standard unit of measure to the given value.
std::string Print () const
Prints this physical quantity as a string. This physical quantity's value is expressed in its standard unit of measure.
std::string Print (const UnitType unit) const
Prints this physical quantity as a string. This physical quantity's value is expressed in the given unit of measure.
std::string JSON () const
Serializes this physical quantity as a JSON message. This physical quantity's value is expressed in its standard unit of measure.
std::string JSON (const UnitType unit) const
Serializes this physical quantity as a JSON message. This physical quantity's value is expressed in the given unit of measure.
std::string XML () const
Serializes this physical quantity as an XML message. This physical quantity's value is expressed in its standard unit of measure.
std::string XML (const UnitType unit) const
Serializes this physical quantity as an XML message. This physical quantity's value is expressed in the given unit of measure.
std::string YAML () const
Serializes this physical quantity as a YAML message. This physical quantity's value is expressed in its standard unit of measure.
std::string YAML (const UnitType unit) const
Serializes this physical quantity as a YAML message. This physical quantity's value is expressed in the given unit of measure.
Static Public Member Functions
static constexpr Traction< NumericType > Zero ()
Statically creates a traction vector of zero.
template<Unit::Pressure Unit>
static constexpr Traction< NumericType > Create (const NumericType x, const NumericType y, const NumericType z)
Statically creates a traction vector from the given x, y, and z Cartesian components expressed in a given pressure unit.
template<Unit::Pressure Unit>
static constexpr Traction< NumericType > Create (const std::array< NumericType, 3 > &x_y_z)
Statically creates a traction vector from the given x, y, and z Cartesian components expressed in a given pressure unit.
template<Unit::Pressure Unit>
static constexpr Traction< NumericType > Create (const Vector< NumericType > &value)
Statically creates a traction vector with a given value expressed in a given pressure unit.
static constexpr const PhQ::Dimensions & Dimensions ()
Physical dimension set of this physical quantity.
static constexpr UnitType Unit ()
Standard unit of measure for this physical quantity. This physical quantity's value is stored internally in this unit of measure.
Protected Attributes
PhQ::Vector< NumericType > value
Value of this physical quantity expressed in its standard unit of measure.
Private Member Functions
constexpr Traction (const Vector< NumericType > &value)
Constructor. Constructs a traction vector with a given value expressed in the standard pressure unit.
Detailed Description
template<typename NumericType = double>
class PhQ::Traction< NumericType >
Three-dimensional Euclidean traction vector. Contains three components in Cartesian coordinates: x, y, and z. Traction is similar to pressure; however, traction can act in any direction, whereas pressure always acts compressively perpendicular to a surface. For a two-dimensional Euclidean traction vector in the XY plane, see PhQ::PlanarTraction. For scalar traction components or for the magnitude of a traction vector, see PhQ::ScalarTraction.
Definition at line 54 of file Traction.hpp.
Constructor & Destructor Documentation
Traction() [1/11]
template<typename NumericType = double> PhQ::Traction< NumericType >::Traction () default
Default constructor. Constructs a traction vector with an uninitialized value.
Traction() [2/11]
template<typename NumericType = double> PhQ::Traction< NumericType >::Traction (const Vector< NumericType > & value, const Unit::Pressure unit) inline
Constructor. Constructs a traction vector with a given value expressed in a given pressure unit.
Definition at line 61 of file Traction.hpp.
Traction() [3/11]
template<typename NumericType = double> PhQ::Traction< NumericType >::Traction (const ScalarTraction< NumericType > & x, const ScalarTraction< NumericType > & y, const ScalarTraction< NumericType > & z) inline
Constructor. Constructs a traction vector from a given set of scalar traction components.
Definition at line 66 of file Traction.hpp.
References PhQ::Traction< NumericType >::x(), PhQ::Traction< NumericType >::y(), and PhQ::Traction< NumericType >::z().
Traction() [4/11]
template<typename NumericType = double> constexpr PhQ::Traction< NumericType >::Traction (const ScalarTraction< NumericType > & scalar_traction, const Direction< NumericType > & direction) inline constexpr
Constructor. Constructs a traction vector from a given scalar traction and direction.
Definition at line 71 of file Traction.hpp.
Traction() [5/11]
template<typename NumericType = double> constexpr PhQ::Traction< NumericType >::Traction (const PlanarTraction< NumericType > & planar_traction) inline explicit constexpr
Constructor. Constructs a traction vector from a given planar traction vector in the XY plane. This traction vector's z-component is initialized to zero.
Definition at line 77 of file Traction.hpp.
References PhQ::DimensionalPlanarVector< UnitType, NumericType >::Value().
Traction() [6/11]
template<typename NumericType = double> constexpr PhQ::Traction< NumericType >::Traction (const Force< NumericType > & force, const Area< NumericType > & area) inline constexpr
Constructor. Constructs a traction vector from a given force and area using the definition of traction.
Definition at line 82 of file Traction.hpp.
Traction() [7/11]
template<typename NumericType > constexpr PhQ::Traction< NumericType >::Traction (const Stress< NumericType > & stress, const Direction< NumericType > & direction) inline constexpr
Constructor. Constructs a traction vector from a given stress and direction using the definition of traction.
Definition at line 302 of file Stress.hpp.
References PhQ::DimensionalSymmetricDyad< UnitType, NumericType >::Value().
~Traction()
template<typename NumericType = double> PhQ::Traction< NumericType >::~Traction () default noexcept
Destructor. Destroys this traction vector.
Traction() [8/11]
template<typename NumericType = double> constexpr PhQ::Traction< NumericType >::Traction (const Traction< NumericType > & other) constexpr default
Copy constructor. Constructs a traction vector by copying another one.
Traction() [9/11]
template<typename NumericType = double> template<typename OtherNumericType > constexpr PhQ::Traction< NumericType >::Traction (const Traction< OtherNumericType > & other) inline explicit constexpr
Copy constructor. Constructs a traction vector by copying another one.
Definition at line 97 of file Traction.hpp.
Traction() [10/11]
template<typename NumericType = double> constexpr PhQ::Traction< NumericType >::Traction (Traction< NumericType > && other) constexpr default noexcept
Move constructor. Constructs a traction vector by moving another one.
Traction() [11/11]
template<typename NumericType = double> constexpr PhQ::Traction< NumericType >::Traction (const Vector< NumericType > & value) inline explicit constexpr private
Constructor. Constructs a traction vector with a given value expressed in the standard pressure unit.
Definition at line 216 of file Traction.hpp.
Member Function Documentation
Angle()
template<typename NumericType = double> PhQ::Angle< NumericType > PhQ::Traction< NumericType >::Angle (const Traction< NumericType > & traction) const inline
Returns the angle between this traction vector and another one.
Definition at line 173 of file Traction.hpp.
Create() [1/3]
template<typename NumericType = double> template<Unit::Pressure Unit> static constexpr Traction< NumericType > PhQ::Traction< NumericType >::Create (const NumericType x, const NumericType y, const NumericType z) inline static constexpr
Statically creates a traction vector from the given x, y, and z Cartesian components expressed in a given pressure unit.
Definition at line 124 of file Traction.hpp.
References PhQ::Traction< NumericType >::x(), PhQ::Traction< NumericType >::y(), and PhQ::Traction< NumericType >::z().
Create() [2/3]
template<typename NumericType = double> template<Unit::Pressure Unit> static constexpr Traction< NumericType > PhQ::Traction< NumericType >::Create (const std::array< NumericType, 3 > & x_y_z) inline static constexpr
Statically creates a traction vector from the given x, y, and z Cartesian components expressed in a given pressure unit.
Definition at line 133 of file Traction.hpp.
Create() [3/3]
template<typename NumericType = double> template<Unit::Pressure Unit> static constexpr Traction< NumericType > PhQ::Traction< NumericType >::Create (const Vector< NumericType > & value) inline static constexpr
Statically creates a traction vector with a given value expressed in a given pressure unit.
Definition at line 142 of file Traction.hpp.
References PhQ::DimensionalVector< UnitType, NumericType >::value.
Dimensions()
template<typename UnitType , typename NumericType = double> static constexpr const PhQ::Dimensions & PhQ::DimensionalVector< UnitType, NumericType >::Dimensions () inline static constexpr inherited
Physical dimension set of this physical quantity.
Definition at line 50 of file DimensionalVector.hpp.
Direction()
template<typename NumericType = double> PhQ::Direction< NumericType > PhQ::Traction< NumericType >::Direction () const inline
Returns the direction of this traction vector.
Definition at line 168 of file Traction.hpp.
References PhQ::DimensionalVector< UnitType, NumericType >::value.
JSON() [1/2]
template<typename UnitType , typename NumericType = double> std::string PhQ::DimensionalVector< UnitType, NumericType >::JSON () const inline inherited
Serializes this physical quantity as a JSON message. This physical quantity's value is expressed in its standard unit of measure.
Definition at line 103 of file DimensionalVector.hpp.
References PhQ::Abbreviation(), and PhQ::DimensionalVector< UnitType, NumericType >::value.
Referenced by PhQ::DimensionalVector< UnitType, NumericType >::JSON().
JSON() [2/2]
template<typename UnitType , typename NumericType = double> std::string PhQ::DimensionalVector< UnitType, NumericType >::JSON (const UnitType unit) const inline inherited
Serializes this physical quantity as a JSON message. This physical quantity's value is expressed in the given unit of measure.
Definition at line 113 of file DimensionalVector.hpp.
References PhQ::Abbreviation(), PhQ::DimensionalVector< UnitType, NumericType >::JSON(), and PhQ::DimensionalVector< UnitType, NumericType >::Value().
Magnitude()
template<typename NumericType = double> ScalarTraction< NumericType > PhQ::Traction< NumericType >::Magnitude () const inline
Returns the magnitude of this traction vector.
Definition at line 163 of file Traction.hpp.
References PhQ::DimensionalVector< UnitType, NumericType >::value.
MutableValue()
template<typename UnitType , typename NumericType = double> constexpr PhQ::Vector< NumericType > & PhQ::DimensionalVector< UnitType, NumericType >::MutableValue () inline constexpr noexcept inherited
Returns the value of this physical quantity expressed in its standard unit of measure as a mutable value.
Definition at line 79 of file DimensionalVector.hpp.
References PhQ::DimensionalVector< UnitType, NumericType >::value.
operator*() [1/2]
template<typename NumericType = double> constexpr Force< NumericType > PhQ::Traction< NumericType >::operator* (const Area< NumericType > & area) const inline constexpr
Definition at line 189 of file Traction.hpp.
operator*() [2/2]
template<typename NumericType = double> constexpr Traction< NumericType > PhQ::Traction< NumericType >::operator* (const NumericType number) const inline constexpr
Definition at line 185 of file Traction.hpp.
References PhQ::DimensionalVector< UnitType, NumericType >::value.
operator*=()
template<typename NumericType = double> constexpr void PhQ::Traction< NumericType >::operator*= (const NumericType number) inline constexpr noexcept
Definition at line 205 of file Traction.hpp.
References PhQ::DimensionalVector< UnitType, NumericType >::value.
operator+()
template<typename NumericType = double> constexpr Traction< NumericType > PhQ::Traction< NumericType >::operator+ (const Traction< NumericType > & traction) const inline constexpr
Definition at line 177 of file Traction.hpp.
References PhQ::DimensionalVector< UnitType, NumericType >::value.
operator+=()
template<typename NumericType = double> constexpr void PhQ::Traction< NumericType >::operator+= (const Traction< NumericType > & traction) inline constexpr noexcept
Definition at line 197 of file Traction.hpp.
References PhQ::DimensionalVector< UnitType, NumericType >::value.
operator-()
template<typename NumericType = double> constexpr Traction< NumericType > PhQ::Traction< NumericType >::operator- (const Traction< NumericType > & traction) const inline constexpr
Definition at line 181 of file Traction.hpp.
References PhQ::DimensionalVector< UnitType, NumericType >::value.
operator-=()
template<typename NumericType = double> constexpr void PhQ::Traction< NumericType >::operator-= (const Traction< NumericType > & traction) inline constexpr noexcept
Definition at line 201 of file Traction.hpp.
References PhQ::DimensionalVector< UnitType, NumericType >::value.
operator/()
template<typename NumericType = double> constexpr Traction< NumericType > PhQ::Traction< NumericType >::operator/ (const NumericType number) const inline constexpr
Definition at line 193 of file Traction.hpp.
References PhQ::DimensionalVector< UnitType, NumericType >::value.
operator/=()
template<typename NumericType = double> constexpr void PhQ::Traction< NumericType >::operator/= (const NumericType number) inline constexpr noexcept
Definition at line 209 of file Traction.hpp.
References PhQ::DimensionalVector< UnitType, NumericType >::value.
operator=() [1/3]
template<typename NumericType = double> constexpr Traction< NumericType > & PhQ::Traction< NumericType >::operator= (const Traction< NumericType > & other) constexpr default
Copy assignment operator. Assigns this traction vector by copying another one.
operator=() [2/3]
template<typename NumericType = double> template<typename OtherNumericType > constexpr Traction< NumericType > & PhQ::Traction< NumericType >::operator= (const Traction< OtherNumericType > & other) inline constexpr
Copy assignment operator. Assigns this traction vector by copying another one.
Definition at line 108 of file Traction.hpp.
References PhQ::DimensionalVector< UnitType, NumericType >::Value(), and PhQ::DimensionalVector< UnitType, NumericType >::value.
operator=() [3/3]
template<typename NumericType = double> constexpr Traction< NumericType > & PhQ::Traction< NumericType >::operator= (Traction< NumericType > && other) constexpr default noexcept
Move assignment operator. Assigns this traction vector by moving another one.
Print() [1/2]
template<typename UnitType , typename NumericType = double> std::string PhQ::DimensionalVector< UnitType, NumericType >::Print () const inline inherited
Prints this physical quantity as a string. This physical quantity's value is expressed in its standard unit of measure.
Definition at line 91 of file DimensionalVector.hpp.
References PhQ::Abbreviation(), and PhQ::DimensionalVector< UnitType, NumericType >::value.
Referenced by PhQ::operator<<(), PhQ::operator<<(), PhQ::operator<<(), PhQ::operator<<(), PhQ::operator<<(), PhQ::operator<<(), PhQ::operator<<(), PhQ::operator<<(), and PhQ::operator<<().
Print() [2/2]
template<typename UnitType , typename NumericType = double> std::string PhQ::DimensionalVector< UnitType, NumericType >::Print (const UnitType unit) const inline inherited
Prints this physical quantity as a string. This physical quantity's value is expressed in the given unit of measure.
Definition at line 97 of file DimensionalVector.hpp.
References PhQ::Abbreviation(), and PhQ::DimensionalVector< UnitType, NumericType >::Value().
SetValue()
template<typename UnitType , typename NumericType = double> constexpr void PhQ::DimensionalVector< UnitType, NumericType >::SetValue (const PhQ::Vector< NumericType > & value) inline constexpr noexcept inherited
Sets the value of this physical quantity expressed in its standard unit of measure to the given value.
Definition at line 85 of file DimensionalVector.hpp.
References PhQ::DimensionalVector< UnitType, NumericType >::value.
StaticValue()
template<typename UnitType , typename NumericType = double> template<UnitType NewUnit> constexpr PhQ::Vector< NumericType > PhQ::DimensionalVector< UnitType, NumericType >::StaticValue () const inline constexpr inherited
Value of this physical quantity expressed in a given unit of measure. This method can be evaluated statically at compile-time.
Definition at line 73 of file DimensionalVector.hpp.
References PhQ::DimensionalVector< UnitType, NumericType >::value.
Unit()
template<typename UnitType , typename NumericType = double> static constexpr UnitType PhQ::DimensionalVector< UnitType, NumericType >::Unit () inline static constexpr inherited
Standard unit of measure for this physical quantity. This physical quantity's value is stored internally in this unit of measure.
Definition at line 56 of file DimensionalVector.hpp.
Value() [1/2]
template<typename UnitType , typename NumericType = double> constexpr const PhQ::Vector< NumericType > & PhQ::DimensionalVector< UnitType, NumericType >::Value () const inline constexpr noexcept inherited
Value of this physical quantity expressed in its standard unit of measure.
Definition at line 61 of file DimensionalVector.hpp.
References PhQ::DimensionalVector< UnitType, NumericType >::value.
Referenced by PhQ::DimensionalVector< UnitType, NumericType >::JSON(), PhQ::Position< NumericType >::operator+(), PhQ::Displacement< NumericType >::operator+(), PhQ::Position< NumericType >::operator-(), PhQ::Displacement< NumericType >::operator-(), PhQ::Acceleration< NumericType >::operator=(), PhQ::DimensionalVector< UnitType, NumericType >::operator=(), PhQ::Displacement< NumericType >::operator=(), PhQ::Force< NumericType >::operator=(), PhQ::HeatFlux< NumericType >::operator=(), PhQ::Position< NumericType >::operator=(), PhQ::TemperatureGradient< NumericType >::operator=(), PhQ::Traction< NumericType >::operator=(), PhQ::VectorArea< NumericType >::operator=(), PhQ::Velocity< NumericType >::operator=(), PhQ::operator==(), PhQ::operator==(), PhQ::operator==(), PhQ::operator==(), PhQ::operator==(), PhQ::operator==(), PhQ::operator==(), PhQ::operator==(), PhQ::operator==(), PhQ::operator==(), PhQ::operator==(), PhQ::operator==(), PhQ::operator==(), PhQ::operator==(), PhQ::operator==(), PhQ::operator==(), PhQ::PlanarAcceleration< NumericType >::PlanarAcceleration(), PhQ::PlanarDisplacement< NumericType >::PlanarDisplacement(), PhQ::PlanarForce< NumericType >::PlanarForce(), PhQ::PlanarHeatFlux< NumericType >::PlanarHeatFlux(), PhQ::PlanarPosition< NumericType >::PlanarPosition(), PhQ::PlanarTemperatureGradient< NumericType >::PlanarTemperatureGradient(), PhQ::PlanarTraction< NumericType >::PlanarTraction(), PhQ::PlanarVelocity< NumericType >::PlanarVelocity(), PhQ::DimensionalVector< UnitType, NumericType >::Print(), PhQ::DimensionalVector< UnitType, NumericType >::XML(), and PhQ::DimensionalVector< UnitType, NumericType >::YAML().
Value() [2/2]
template<typename UnitType , typename NumericType = double> PhQ::Vector< NumericType > PhQ::DimensionalVector< UnitType, NumericType >::Value (const UnitType unit) const inline inherited
Value of this physical quantity expressed in a given unit of measure.
Definition at line 66 of file DimensionalVector.hpp.
References PhQ::Convert(), and PhQ::DimensionalVector< UnitType, NumericType >::value.
x()
template<typename NumericType = double> constexpr ScalarTraction< NumericType > PhQ::Traction< NumericType >::x () const inline constexpr noexcept
Returns the x Cartesian component of this traction vector.
Definition at line 148 of file Traction.hpp.
References PhQ::DimensionalVector< UnitType, NumericType >::value.
Referenced by PhQ::Traction< NumericType >::Create(), and PhQ::Traction< NumericType >::Traction().
XML() [1/2]
template<typename UnitType , typename NumericType = double> std::string PhQ::DimensionalVector< UnitType, NumericType >::XML () const inline inherited
Serializes this physical quantity as an XML message. This physical quantity's value is expressed in its standard unit of measure.
Definition at line 123 of file DimensionalVector.hpp.
References PhQ::Abbreviation(), and PhQ::DimensionalVector< UnitType, NumericType >::value.
Referenced by PhQ::DimensionalVector< UnitType, NumericType >::XML().
XML() [2/2]
template<typename UnitType , typename NumericType = double> std::string PhQ::DimensionalVector< UnitType, NumericType >::XML (const UnitType unit) const inline inherited
Serializes this physical quantity as an XML message. This physical quantity's value is expressed in the given unit of measure.
Definition at line 133 of file DimensionalVector.hpp.
References PhQ::Abbreviation(), PhQ::DimensionalVector< UnitType, NumericType >::Value(), and PhQ::DimensionalVector< UnitType, NumericType >::XML().
y()
template<typename NumericType = double> constexpr ScalarTraction< NumericType > PhQ::Traction< NumericType >::y () const inline constexpr noexcept
Returns the y Cartesian component of this traction vector.
Definition at line 153 of file Traction.hpp.
References PhQ::DimensionalVector< UnitType, NumericType >::value.
Referenced by PhQ::Traction< NumericType >::Create(), and PhQ::Traction< NumericType >::Traction().
YAML() [1/2]
template<typename UnitType , typename NumericType = double> std::string PhQ::DimensionalVector< UnitType, NumericType >::YAML () const inline inherited
Serializes this physical quantity as a YAML message. This physical quantity's value is expressed in its standard unit of measure.
Definition at line 143 of file DimensionalVector.hpp.
References PhQ::Abbreviation(), and PhQ::DimensionalVector< UnitType, NumericType >::value.
Referenced by PhQ::DimensionalVector< UnitType, NumericType >::YAML().
YAML() [2/2]
template<typename UnitType , typename NumericType = double> std::string PhQ::DimensionalVector< UnitType, NumericType >::YAML (const UnitType unit) const inline inherited
Serializes this physical quantity as a YAML message. This physical quantity's value is expressed in the given unit of measure.
Definition at line 153 of file DimensionalVector.hpp.
References PhQ::Abbreviation(), PhQ::DimensionalVector< UnitType, NumericType >::Value(), and PhQ::DimensionalVector< UnitType, NumericType >::YAML().
z()
template<typename NumericType = double> constexpr ScalarTraction< NumericType > PhQ::Traction< NumericType >::z () const inline constexpr noexcept
Returns the z Cartesian component of this traction vector.
Definition at line 158 of file Traction.hpp.
References PhQ::DimensionalVector< UnitType, NumericType >::value.
Referenced by PhQ::Traction< NumericType >::Create(), and PhQ::Traction< NumericType >::Traction().
Zero()
template<typename NumericType = double> static constexpr Traction< NumericType > PhQ::Traction< NumericType >::Zero () inline static constexpr
Statically creates a traction vector of zero.
Definition at line 117 of file Traction.hpp.
References PhQ::Vector< NumericType >::Zero().
Member Data Documentation
value
template<typename UnitType , typename NumericType = double> PhQ::Vector<NumericType> PhQ::DimensionalVector< UnitType, NumericType >::value protected inherited
Value of this physical quantity expressed in its standard unit of measure.
Definition at line 217 of file DimensionalVector.hpp.
Referenced by PhQ::Acceleration< NumericType >::Create(), PhQ::Displacement< NumericType >::Create(), PhQ::Force< NumericType >::Create(), PhQ::HeatFlux< NumericType >::Create(), PhQ::Position< NumericType >::Create(), PhQ::TemperatureGradient< NumericType >::Create(), PhQ::Traction< NumericType >::Create(), PhQ::VectorArea< NumericType >::Create(), PhQ::Velocity< NumericType >::Create(), PhQ::Acceleration< NumericType >::Direction(), PhQ::Displacement< NumericType >::Direction(), PhQ::Force< NumericType >::Direction(), PhQ::HeatFlux< NumericType >::Direction(), PhQ::Position< NumericType >::Direction(), PhQ::TemperatureGradient< NumericType >::Direction(), PhQ::Traction< NumericType >::Direction(), PhQ::VectorArea< NumericType >::Direction(), PhQ::Velocity< NumericType >::Direction(), PhQ::DimensionalVector< UnitType, NumericType >::JSON(), PhQ::Acceleration< NumericType >::Magnitude(), PhQ::Displacement< NumericType >::Magnitude(), PhQ::Force< NumericType >::Magnitude(), PhQ::HeatFlux< NumericType >::Magnitude(), PhQ::Position< NumericType >::Magnitude(), PhQ::TemperatureGradient< NumericType >::Magnitude(), PhQ::Traction< NumericType >::Magnitude(), PhQ::VectorArea< NumericType >::Magnitude(), PhQ::Velocity< NumericType >::Magnitude(), PhQ::DimensionalVector< UnitType, NumericType >::MutableValue(), PhQ::Acceleration< NumericType >::operator*(), PhQ::Displacement< NumericType >::operator*(), PhQ::Force< NumericType >::operator*(), PhQ::HeatFlux< NumericType >::operator*(), PhQ::Position< NumericType >::operator*(), PhQ::TemperatureGradient< NumericType >::operator*(), PhQ::Traction< NumericType >::operator*(), PhQ::VectorArea< NumericType >::operator*(), PhQ::Velocity< NumericType >::operator*(), PhQ::Acceleration< NumericType >::operator*=(), PhQ::Displacement< NumericType >::operator*=(), PhQ::Force< NumericType >::operator*=(), PhQ::HeatFlux< NumericType >::operator*=(), PhQ::Position< NumericType >::operator*=(), PhQ::TemperatureGradient< NumericType >::operator*=(), PhQ::Traction< NumericType >::operator*=(), PhQ::VectorArea< NumericType >::operator*=(), PhQ::Velocity< NumericType >::operator*=(), PhQ::Acceleration< NumericType >::operator+(), PhQ::Displacement< NumericType >::operator+(), PhQ::Position< NumericType >::operator+(), PhQ::Force< NumericType >::operator+(), PhQ::HeatFlux< NumericType >::operator+(), PhQ::Position< NumericType >::operator+(), PhQ::TemperatureGradient< NumericType >::operator+(), PhQ::Traction< NumericType >::operator+(), PhQ::VectorArea< NumericType >::operator+(), PhQ::Velocity< NumericType >::operator+(), PhQ::Acceleration< NumericType >::operator+=(), PhQ::Displacement< NumericType >::operator+=(), PhQ::Position< NumericType >::operator+=(), PhQ::Force< NumericType >::operator+=(), PhQ::HeatFlux< NumericType >::operator+=(), PhQ::Position< NumericType >::operator+=(), PhQ::TemperatureGradient< NumericType >::operator+=(), PhQ::Traction< NumericType >::operator+=(), PhQ::VectorArea< NumericType >::operator+=(), PhQ::Velocity< NumericType >::operator+=(), PhQ::Acceleration< NumericType >::operator-(), PhQ::Displacement< NumericType >::operator-(), PhQ::Position< NumericType >::operator-(), PhQ::Force< NumericType >::operator-(), PhQ::HeatFlux< NumericType >::operator-(), PhQ::Position< NumericType >::operator-(), PhQ::TemperatureGradient< NumericType >::operator-(), PhQ::Traction< NumericType >::operator-(), PhQ::VectorArea< NumericType >::operator-(), PhQ::Velocity< NumericType >::operator-(), PhQ::Acceleration< NumericType >::operator-=(), PhQ::Displacement< NumericType >::operator-=(), PhQ::Position< NumericType >::operator-=(), PhQ::Force< NumericType >::operator-=(), PhQ::HeatFlux< NumericType >::operator-=(), PhQ::Position< NumericType >::operator-=(), PhQ::TemperatureGradient< NumericType >::operator-=(), PhQ::Traction< NumericType >::operator-=(), PhQ::VectorArea< NumericType >::operator-=(), PhQ::Velocity< NumericType >::operator-=(), PhQ::Acceleration< NumericType >::operator/(), PhQ::Displacement< NumericType >::operator/(), PhQ::Force< NumericType >::operator/(), PhQ::HeatFlux< NumericType >::operator/(), PhQ::Position< NumericType >::operator/(), PhQ::TemperatureGradient< NumericType >::operator/(), PhQ::Traction< NumericType >::operator/(), PhQ::VectorArea< NumericType >::operator/(), PhQ::Velocity< NumericType >::operator/(), PhQ::Acceleration< NumericType >::operator/=(), PhQ::Displacement< NumericType >::operator/=(), PhQ::Force< NumericType >::operator/=(), PhQ::HeatFlux< NumericType >::operator/=(), PhQ::Position< NumericType >::operator/=(), PhQ::TemperatureGradient< NumericType >::operator/=(), PhQ::Traction< NumericType >::operator/=(), PhQ::VectorArea< NumericType >::operator/=(), PhQ::Velocity< NumericType >::operator/=(), PhQ::Acceleration< NumericType >::operator=(), PhQ::DimensionalVector< UnitType, NumericType >::operator=(), PhQ::Displacement< NumericType >::operator=(), PhQ::Force< NumericType >::operator=(), PhQ::HeatFlux< NumericType >::operator=(), PhQ::Position< NumericType >::operator=(), PhQ::TemperatureGradient< NumericType >::operator=(), PhQ::Traction< NumericType >::operator=(), PhQ::VectorArea< NumericType >::operator=(), PhQ::Velocity< NumericType >::operator=(), PhQ::DimensionalVector< UnitType, NumericType >::Print(), PhQ::DimensionalVector< UnitType, NumericType >::SetValue(), PhQ::DimensionalVector< UnitType, NumericType >::StaticValue(), PhQ::DimensionalVector< UnitType, NumericType >::Value(), PhQ::DimensionalVector< UnitType, NumericType >::Value(), PhQ::Acceleration< NumericType >::x(), PhQ::Displacement< NumericType >::x(), PhQ::Force< NumericType >::x(), PhQ::HeatFlux< NumericType >::x(), PhQ::Position< NumericType >::x(), PhQ::TemperatureGradient< NumericType >::x(), PhQ::Traction< NumericType >::x(), PhQ::VectorArea< NumericType >::x(), PhQ::Velocity< NumericType >::x(), PhQ::DimensionalVector< UnitType, NumericType >::XML(), PhQ::Acceleration< NumericType >::y(), PhQ::Displacement< NumericType >::y(), PhQ::Force< NumericType >::y(), PhQ::HeatFlux< NumericType >::y(), PhQ::Position< NumericType >::y(), PhQ::TemperatureGradient< NumericType >::y(), PhQ::Traction< NumericType >::y(), PhQ::VectorArea< NumericType >::y(), PhQ::Velocity< NumericType >::y(), PhQ::DimensionalVector< UnitType, NumericType >::YAML(), PhQ::Acceleration< NumericType >::z(), PhQ::Displacement< NumericType >::z(), PhQ::Force< NumericType >::z(), PhQ::HeatFlux< NumericType >::z(), PhQ::Position< NumericType >::z(), PhQ::TemperatureGradient< NumericType >::z(), PhQ::Traction< NumericType >::z(), PhQ::VectorArea< NumericType >::z(), and PhQ::Velocity< NumericType >::z().
The documentation for this class was generated from the following files:
PhQ/Angle.hpp
PhQ/Traction.hpp
PhQ/Stress.hpp