Physical Quantities: PhQ::ConstitutiveModel::IncompressibleNewtonianFluid< NumericType > Class Template Reference
PhQ::ConstitutiveModel::IncompressibleNewtonianFluid< NumericType > Class Template Reference abstract
Constitutive model for an incompressible Newtonian fluid. This is the simplest constitutive model for a fluid. The viscous stress tensor at a point is a linear function of only the local strain rate tensor at that point.
#include "IncompressibleNewtonianFluid.hpp"
Public Types
enum class Type : int8_t { CompressibleNewtonianFluid , ElasticIsotropicSolid , IncompressibleNewtonianFluid }
Type of a material's constitutive model.
Public Member Functions
IncompressibleNewtonianFluid ()
Default constructor. Constructs an incompressible Newtonian fluid constitutive model with an uninitialized dynamic viscosity.
constexpr IncompressibleNewtonianFluid (const DynamicViscosity< NumericType > &dynamic_viscosity)
Constructor. Constructs an incompressible Newtonian fluid constitutive model from a given dynamic viscosity.
~IncompressibleNewtonianFluid () noexcept override=default
Destructor. Destroys this incompressible Newtonian fluid constitutive model.
constexpr IncompressibleNewtonianFluid (const IncompressibleNewtonianFluid &other)=default
Copy constructor. Constructs an incompressible Newtonian fluid constitutive model by copying another one.
constexpr IncompressibleNewtonianFluid (IncompressibleNewtonianFluid &&other) noexcept=default
Move constructor. Constructs an incompressible Newtonian fluid constitutive model by moving another one.
IncompressibleNewtonianFluid & operator= (const IncompressibleNewtonianFluid &other)=default
Copy assignment operator. Assigns this incompressible Newtonian fluid constitutive model by copying another one.
IncompressibleNewtonianFluid & operator= (IncompressibleNewtonianFluid &&other) noexcept=default
Move assignment operator. Assigns this incompressible Newtonian fluid constitutive model by moving another one.
constexpr const PhQ::DynamicViscosity< NumericType > & DynamicViscosity () const noexcept
Dynamic viscosity of this incompressible Newtonian fluid constitutive model.
ConstitutiveModel::Type GetType () const noexcept override
Returns this constitutive model's type.
PhQ::Stress< float > Stress (const PhQ::Strain< float > &, const PhQ::StrainRate< float > &strain_rate) const override
Returns the stress resulting from a given strain and strain rate. Since this is an incompressible Newtonian fluid constitutive model, the strain does not contribute to the stress and is ignored.
PhQ::Stress< double > Stress (const PhQ::Strain< double > &, const PhQ::StrainRate< double > &strain_rate) const override
Returns the stress resulting from a given strain and strain rate. Since this is an incompressible Newtonian fluid constitutive model, the strain does not contribute to the stress and is ignored.
PhQ::Stress< long double > Stress (const PhQ::Strain< long double > &, const PhQ::StrainRate< long double > &strain_rate) const override
Returns the stress resulting from a given strain and strain rate. Since this is an incompressible Newtonian fluid constitutive model, the strain does not contribute to the stress and is ignored.
PhQ::Stress< float > Stress (const PhQ::Strain< float > &) const override
Returns the stress resulting from a given strain. Since this is an incompressible Newtonian fluid constitutive model, the strain does not contribute to the stress, so this always returns a stress of zero.
PhQ::Stress< double > Stress (const PhQ::Strain< double > &) const override
Returns the stress resulting from a given strain. Since this is an incompressible Newtonian fluid constitutive model, the strain does not contribute to the stress, so this always returns a stress of zero.
PhQ::Stress< long double > Stress (const PhQ::Strain< long double > &) const override
Returns the stress resulting from a given strain. Since this is an incompressible Newtonian fluid constitutive model, the strain does not contribute to the stress, so this always returns a stress of zero.
PhQ::Stress< float > Stress (const PhQ::StrainRate< float > &strain_rate) const override
Returns the stress resulting from a given strain rate.
PhQ::Stress< double > Stress (const PhQ::StrainRate< double > &strain_rate) const override
Returns the stress resulting from a given strain rate.
PhQ::Stress< long double > Stress (const PhQ::StrainRate< long double > &strain_rate) const override
Returns the stress resulting from a given strain rate.
PhQ::Strain< float > Strain (const PhQ::Stress< float > &) const override
Returns the strain resulting from a given stress. Since this is an incompressible Newtonian fluid constitutive model, stress does not depend on strain, so this always returns a strain of zero.
PhQ::Strain< double > Strain (const PhQ::Stress< double > &) const override
Returns the strain resulting from a given stress. Since this is an incompressible Newtonian fluid constitutive model, stress does not depend on strain, so this always returns a strain of zero.
PhQ::Strain< long double > Strain (const PhQ::Stress< long double > &) const override
Returns the strain resulting from a given stress. Since this is an incompressible Newtonian fluid constitutive model, stress does not depend on strain, so this always returns a strain of zero.
PhQ::StrainRate< float > StrainRate (const PhQ::Stress< float > &stress) const override
Returns the strain rate resulting from a given stress.
PhQ::StrainRate< double > StrainRate (const PhQ::Stress< double > &stress) const override
Returns the strain rate resulting from a given stress.
PhQ::StrainRate< long double > StrainRate (const PhQ::Stress< long double > &stress) const override
Returns the strain rate resulting from a given stress.
std::string Print () const override
Prints this incompressible Newtonian fluid constitutive model as a string.
std::string JSON () const override
Serializes this incompressible Newtonian fluid constitutive model as a JSON message.
virtual std::string XML () const =0
Serializes this constitutive model as an XML message.
virtual std::string YAML () const =0
Serializes this constitutive model as a YAML message.
Private Attributes
PhQ::DynamicViscosity< NumericType > dynamic_viscosity
Dynamic viscosity of this incompressible Newtonian fluid constitutive model.
Detailed Description
template<typename NumericType = double>
class PhQ::ConstitutiveModel::IncompressibleNewtonianFluid< NumericType >
Constitutive model for an incompressible Newtonian fluid. This is the simplest constitutive model for a fluid. The viscous stress tensor at a point is a linear function of only the local strain rate tensor at that point.
Definition at line 49 of file IncompressibleNewtonianFluid.hpp.
Member Enumeration Documentation
Type
enum class PhQ::ConstitutiveModel::Type : int8_t strong inherited
Type of a material's constitutive model.
Enumerator
CompressibleNewtonianFluid
Compressible Newtonian fluid constitutive model.
ElasticIsotropicSolid
Elastic isotropic solid constitutive model.
IncompressibleNewtonianFluid
Incompressible Newtonian fluid constitutive model.
Definition at line 57 of file ConstitutiveModel.hpp.
Constructor & Destructor Documentation
IncompressibleNewtonianFluid() [1/4]
template<typename NumericType = double> PhQ::ConstitutiveModel::IncompressibleNewtonianFluid< NumericType >::IncompressibleNewtonianFluid () inline
Default constructor. Constructs an incompressible Newtonian fluid constitutive model with an uninitialized dynamic viscosity.
Definition at line 53 of file IncompressibleNewtonianFluid.hpp.
IncompressibleNewtonianFluid() [2/4]
template<typename NumericType = double> constexpr PhQ::ConstitutiveModel::IncompressibleNewtonianFluid< NumericType >::IncompressibleNewtonianFluid (const DynamicViscosity< NumericType > & dynamic_viscosity) inline explicit constexpr
Constructor. Constructs an incompressible Newtonian fluid constitutive model from a given dynamic viscosity.
Definition at line 57 of file IncompressibleNewtonianFluid.hpp.
~IncompressibleNewtonianFluid()
template<typename NumericType = double> PhQ::ConstitutiveModel::IncompressibleNewtonianFluid< NumericType >::~IncompressibleNewtonianFluid () override default noexcept
Destructor. Destroys this incompressible Newtonian fluid constitutive model.
IncompressibleNewtonianFluid() [3/4]
template<typename NumericType = double> constexpr PhQ::ConstitutiveModel::IncompressibleNewtonianFluid< NumericType >::IncompressibleNewtonianFluid (const IncompressibleNewtonianFluid< NumericType > & other) constexpr default
Copy constructor. Constructs an incompressible Newtonian fluid constitutive model by copying another one.
IncompressibleNewtonianFluid() [4/4]
template<typename NumericType = double> constexpr PhQ::ConstitutiveModel::IncompressibleNewtonianFluid< NumericType >::IncompressibleNewtonianFluid (IncompressibleNewtonianFluid< NumericType > && other) constexpr default noexcept
Move constructor. Constructs an incompressible Newtonian fluid constitutive model by moving another one.
Member Function Documentation
DynamicViscosity()
template<typename NumericType = double> constexpr const PhQ::DynamicViscosity< NumericType > & PhQ::ConstitutiveModel::IncompressibleNewtonianFluid< NumericType >::DynamicViscosity () const inline constexpr noexcept
Dynamic viscosity of this incompressible Newtonian fluid constitutive model.
Definition at line 82 of file IncompressibleNewtonianFluid.hpp.
References PhQ::ConstitutiveModel::IncompressibleNewtonianFluid< NumericType >::dynamic_viscosity.
GetType()
template<typename NumericType = double> ConstitutiveModel::Type PhQ::ConstitutiveModel::IncompressibleNewtonianFluid< NumericType >::GetType () const inline override virtual noexcept
Returns this constitutive model's type.
Implements PhQ::ConstitutiveModel.
Definition at line 87 of file IncompressibleNewtonianFluid.hpp.
References PhQ::ConstitutiveModel::IncompressibleNewtonianFluid.
Referenced by PhQ::ConstitutiveModel::IncompressibleNewtonianFluid< NumericType >::JSON(), and PhQ::ConstitutiveModel::IncompressibleNewtonianFluid< NumericType >::Print().
JSON()
template<typename NumericType = double> std::string PhQ::ConstitutiveModel::IncompressibleNewtonianFluid< NumericType >::JSON () const inline override virtual
Serializes this incompressible Newtonian fluid constitutive model as a JSON message.
Implements PhQ::ConstitutiveModel.
Definition at line 232 of file IncompressibleNewtonianFluid.hpp.
References PhQ::Abbreviation(), PhQ::ConstitutiveModel::IncompressibleNewtonianFluid< NumericType >::dynamic_viscosity, PhQ::ConstitutiveModel::IncompressibleNewtonianFluid< NumericType >::GetType(), and PhQ::SnakeCase().
operator=() [1/2]
template<typename NumericType = double> IncompressibleNewtonianFluid & PhQ::ConstitutiveModel::IncompressibleNewtonianFluid< NumericType >::operator= (const IncompressibleNewtonianFluid< NumericType > & other) default
Copy assignment operator. Assigns this incompressible Newtonian fluid constitutive model by copying another one.
operator=() [2/2]
template<typename NumericType = double> IncompressibleNewtonianFluid & PhQ::ConstitutiveModel::IncompressibleNewtonianFluid< NumericType >::operator= (IncompressibleNewtonianFluid< NumericType > && other) default noexcept
Move assignment operator. Assigns this incompressible Newtonian fluid constitutive model by moving another one.
Print()
template<typename NumericType = double> std::string PhQ::ConstitutiveModel::IncompressibleNewtonianFluid< NumericType >::Print () const inline override virtual
Prints this incompressible Newtonian fluid constitutive model as a string.
Implements PhQ::ConstitutiveModel.
Definition at line 226 of file IncompressibleNewtonianFluid.hpp.
References PhQ::Abbreviation(), PhQ::ConstitutiveModel::IncompressibleNewtonianFluid< NumericType >::dynamic_viscosity, and PhQ::ConstitutiveModel::IncompressibleNewtonianFluid< NumericType >::GetType().
Referenced by PhQ::operator<<().
Strain() [1/3]
template<typename NumericType = double> PhQ::Strain< double > PhQ::ConstitutiveModel::IncompressibleNewtonianFluid< NumericType >::Strain (const PhQ::Stress< double > &) const inline override virtual
Returns the strain resulting from a given stress. Since this is an incompressible Newtonian fluid constitutive model, stress does not depend on strain, so this always returns a strain of zero.
Implements PhQ::ConstitutiveModel.
Definition at line 182 of file IncompressibleNewtonianFluid.hpp.
References PhQ::Strain< NumericType >::Zero().
Strain() [2/3]
template<typename NumericType = double> PhQ::Strain< float > PhQ::ConstitutiveModel::IncompressibleNewtonianFluid< NumericType >::Strain (const PhQ::Stress< float > &) const inline override virtual
Returns the strain resulting from a given stress. Since this is an incompressible Newtonian fluid constitutive model, stress does not depend on strain, so this always returns a strain of zero.
Implements PhQ::ConstitutiveModel.
Definition at line 174 of file IncompressibleNewtonianFluid.hpp.
References PhQ::Strain< NumericType >::Zero().
Strain() [3/3]
template<typename NumericType = double> PhQ::Strain< long double > PhQ::ConstitutiveModel::IncompressibleNewtonianFluid< NumericType >::Strain (const PhQ::Stress< long double > &) const inline override virtual
Returns the strain resulting from a given stress. Since this is an incompressible Newtonian fluid constitutive model, stress does not depend on strain, so this always returns a strain of zero.
Implements PhQ::ConstitutiveModel.
Definition at line 190 of file IncompressibleNewtonianFluid.hpp.
References PhQ::Strain< NumericType >::Zero().
StrainRate() [1/3]
template<typename NumericType = double> PhQ::StrainRate< double > PhQ::ConstitutiveModel::IncompressibleNewtonianFluid< NumericType >::StrainRate (const PhQ::Stress< double > & stress) const inline override virtual
Returns the strain rate resulting from a given stress.
Implements PhQ::ConstitutiveModel.
Definition at line 206 of file IncompressibleNewtonianFluid.hpp.
References PhQ::ConstitutiveModel::IncompressibleNewtonianFluid< NumericType >::dynamic_viscosity, and PhQ::DimensionalSymmetricDyad< UnitType, NumericType >::Value().
StrainRate() [2/3]
template<typename NumericType = double> PhQ::StrainRate< float > PhQ::ConstitutiveModel::IncompressibleNewtonianFluid< NumericType >::StrainRate (const PhQ::Stress< float > & stress) const inline override virtual
Returns the strain rate resulting from a given stress.
Implements PhQ::ConstitutiveModel.
Definition at line 196 of file IncompressibleNewtonianFluid.hpp.
References PhQ::ConstitutiveModel::IncompressibleNewtonianFluid< NumericType >::dynamic_viscosity, and PhQ::DimensionalSymmetricDyad< UnitType, NumericType >::Value().
StrainRate() [3/3]
template<typename NumericType = double> PhQ::StrainRate< long double > PhQ::ConstitutiveModel::IncompressibleNewtonianFluid< NumericType >::StrainRate (const PhQ::Stress< long double > & stress) const inline override virtual
Returns the strain rate resulting from a given stress.
Implements PhQ::ConstitutiveModel.
Definition at line 216 of file IncompressibleNewtonianFluid.hpp.
References PhQ::ConstitutiveModel::IncompressibleNewtonianFluid< NumericType >::dynamic_viscosity, and PhQ::DimensionalSymmetricDyad< UnitType, NumericType >::Value().
Stress() [1/9]
template<typename NumericType = double> PhQ::Stress< double > PhQ::ConstitutiveModel::IncompressibleNewtonianFluid< NumericType >::Stress (const PhQ::Strain< double > &) const inline override virtual
Returns the stress resulting from a given strain. Since this is an incompressible Newtonian fluid constitutive model, the strain does not contribute to the stress, so this always returns a stress of zero.
Implements PhQ::ConstitutiveModel.
Definition at line 129 of file IncompressibleNewtonianFluid.hpp.
References PhQ::Stress< NumericType >::Zero().
Stress() [2/9]
template<typename NumericType = double> PhQ::Stress< double > PhQ::ConstitutiveModel::IncompressibleNewtonianFluid< NumericType >::Stress (const PhQ::Strain< double > & , const PhQ::StrainRate< double > & strain_rate) const inline override virtual
Returns the stress resulting from a given strain and strain rate. Since this is an incompressible Newtonian fluid constitutive model, the strain does not contribute to the stress and is ignored.
Implements PhQ::ConstitutiveModel.
Definition at line 103 of file IncompressibleNewtonianFluid.hpp.
Stress() [3/9]
template<typename NumericType = double> PhQ::Stress< float > PhQ::ConstitutiveModel::IncompressibleNewtonianFluid< NumericType >::Stress (const PhQ::Strain< float > &) const inline override virtual
Returns the stress resulting from a given strain. Since this is an incompressible Newtonian fluid constitutive model, the strain does not contribute to the stress, so this always returns a stress of zero.
Implements PhQ::ConstitutiveModel.
Definition at line 121 of file IncompressibleNewtonianFluid.hpp.
References PhQ::Stress< NumericType >::Zero().
Stress() [4/9]
template<typename NumericType = double> PhQ::Stress< float > PhQ::ConstitutiveModel::IncompressibleNewtonianFluid< NumericType >::Stress (const PhQ::Strain< float > & , const PhQ::StrainRate< float > & strain_rate) const inline override virtual
Returns the stress resulting from a given strain and strain rate. Since this is an incompressible Newtonian fluid constitutive model, the strain does not contribute to the stress and is ignored.
Implements PhQ::ConstitutiveModel.
Definition at line 94 of file IncompressibleNewtonianFluid.hpp.
Stress() [5/9]
template<typename NumericType = double> PhQ::Stress< long double > PhQ::ConstitutiveModel::IncompressibleNewtonianFluid< NumericType >::Stress (const PhQ::Strain< long double > &) const inline override virtual
Returns the stress resulting from a given strain. Since this is an incompressible Newtonian fluid constitutive model, the strain does not contribute to the stress, so this always returns a stress of zero.
Implements PhQ::ConstitutiveModel.
Definition at line 137 of file IncompressibleNewtonianFluid.hpp.
References PhQ::Stress< NumericType >::Zero().
Stress() [6/9]
template<typename NumericType = double> PhQ::Stress< long double > PhQ::ConstitutiveModel::IncompressibleNewtonianFluid< NumericType >::Stress (const PhQ::Strain< long double > & , const PhQ::StrainRate< long double > & strain_rate) const inline override virtual
Returns the stress resulting from a given strain and strain rate. Since this is an incompressible Newtonian fluid constitutive model, the strain does not contribute to the stress and is ignored.
Implements PhQ::ConstitutiveModel.
Definition at line 112 of file IncompressibleNewtonianFluid.hpp.
Stress() [7/9]
template<typename NumericType = double> PhQ::Stress< double > PhQ::ConstitutiveModel::IncompressibleNewtonianFluid< NumericType >::Stress (const PhQ::StrainRate< double > & strain_rate) const inline override virtual
Returns the stress resulting from a given strain rate.
Implements PhQ::ConstitutiveModel.
Definition at line 152 of file IncompressibleNewtonianFluid.hpp.
References PhQ::ConstitutiveModel::IncompressibleNewtonianFluid< NumericType >::dynamic_viscosity, and PhQ::DimensionalSymmetricDyad< UnitType, NumericType >::Value().
Stress() [8/9]
template<typename NumericType = double> PhQ::Stress< float > PhQ::ConstitutiveModel::IncompressibleNewtonianFluid< NumericType >::Stress (const PhQ::StrainRate< float > & strain_rate) const inline override virtual
Returns the stress resulting from a given strain rate.
Implements PhQ::ConstitutiveModel.
Definition at line 143 of file IncompressibleNewtonianFluid.hpp.
References PhQ::ConstitutiveModel::IncompressibleNewtonianFluid< NumericType >::dynamic_viscosity, and PhQ::DimensionalSymmetricDyad< UnitType, NumericType >::Value().
Stress() [9/9]
template<typename NumericType = double> PhQ::Stress< long double > PhQ::ConstitutiveModel::IncompressibleNewtonianFluid< NumericType >::Stress (const PhQ::StrainRate< long double > & strain_rate) const inline override virtual
Returns the stress resulting from a given strain rate.
Implements PhQ::ConstitutiveModel.
Definition at line 162 of file IncompressibleNewtonianFluid.hpp.
References PhQ::ConstitutiveModel::IncompressibleNewtonianFluid< NumericType >::dynamic_viscosity, and PhQ::DimensionalSymmetricDyad< UnitType, NumericType >::Value().
XML()
virtual std::string PhQ::ConstitutiveModel::XML () const inline pure virtual inherited
Serializes this constitutive model as an XML message.
Implemented in PhQ::ConstitutiveModel::CompressibleNewtonianFluid< NumericType >, and PhQ::ConstitutiveModel::ElasticIsotropicSolid< NumericType >.
YAML()
virtual std::string PhQ::ConstitutiveModel::YAML () const inline pure virtual inherited
Serializes this constitutive model as a YAML message.
Implemented in PhQ::ConstitutiveModel::CompressibleNewtonianFluid< NumericType >, and PhQ::ConstitutiveModel::ElasticIsotropicSolid< NumericType >.
References PhQ::ConstitutiveModel::CompressibleNewtonianFluid, PhQ::ConstitutiveModel::ElasticIsotropicSolid, and PhQ::ConstitutiveModel::IncompressibleNewtonianFluid.
Member Data Documentation
dynamic_viscosity
template<typename NumericType = double> PhQ::DynamicViscosity<NumericType> PhQ::ConstitutiveModel::IncompressibleNewtonianFluid< NumericType >::dynamic_viscosity private
Dynamic viscosity of this incompressible Newtonian fluid constitutive model.
Definition at line 251 of file IncompressibleNewtonianFluid.hpp.
Referenced by PhQ::ConstitutiveModel::IncompressibleNewtonianFluid< NumericType >::DynamicViscosity(), PhQ::ConstitutiveModel::IncompressibleNewtonianFluid< NumericType >::JSON(), PhQ::ConstitutiveModel::IncompressibleNewtonianFluid< NumericType >::Print(), PhQ::ConstitutiveModel::IncompressibleNewtonianFluid< NumericType >::StrainRate(), PhQ::ConstitutiveModel::IncompressibleNewtonianFluid< NumericType >::StrainRate(), PhQ::ConstitutiveModel::IncompressibleNewtonianFluid< NumericType >::StrainRate(), PhQ::ConstitutiveModel::IncompressibleNewtonianFluid< NumericType >::Stress(), PhQ::ConstitutiveModel::IncompressibleNewtonianFluid< NumericType >::Stress(), and PhQ::ConstitutiveModel::IncompressibleNewtonianFluid< NumericType >::Stress().
The documentation for this class was generated from the following files:
PhQ/ConstitutiveModel.hpp
PhQ/ConstitutiveModel/IncompressibleNewtonianFluid.hpp