Physical Quantities: PhQ::Dimension::Length Class Reference
PhQ::Dimension::Length Class Reference
Base physical dimension of length. Typically denoted "L". One of seven independent base physical dimensions that form the physical dimension set of any unit of measure or physical quantity. Part of PhQ::Dimensions.
#include "Length.hpp"
Public Member Functions
constexpr Length ()=default
Default constructor. Constructs a base physical dimension of length with a value of zero.
constexpr Length (const int8_t value)
Constructor. Constructs a base physical dimension of length with a given value.
~Length () noexcept=default
Destructor. Destroys this base physical dimension of length.
constexpr Length (const Length &other)=default
Copy constructor. Constructs a base physical dimension of length by copying another one.
constexpr Length & operator= (const Length &other)=default
Copy assignment operator. Assigns the value of this base physical dimension of length by copying from another one.
constexpr Length (Length &&other) noexcept=default
Move constructor. Constructs a base physical dimension of length by moving another one.
constexpr Length & operator= (Length &&other) noexcept=default
Move assignment operator. Assigns the value of this base physical dimension of length by moving another one.
constexpr int8_t Value () const noexcept
Value of this base physical dimension.
std::string Print () const noexcept
Prints this base physical dimension as a string.
Static Public Member Functions
static std::string_view Abbreviation () noexcept
Abbreviation of this base physical dimension.
static std::string_view Label () noexcept
Label of this base physical dimension.
Private Attributes
int8_t value {0}
Value of this base physical dimension.
Detailed Description
Base physical dimension of length. Typically denoted "L". One of seven independent base physical dimensions that form the physical dimension set of any unit of measure or physical quantity. Part of PhQ::Dimensions.
Definition at line 40 of file Length.hpp.
Constructor & Destructor Documentation
Length() [1/4]
constexpr PhQ::Dimension::Length::Length () constexpr default
Default constructor. Constructs a base physical dimension of length with a value of zero.
Length() [2/4]
constexpr PhQ::Dimension::Length::Length (const int8_t value) inline explicit constexpr
Constructor. Constructs a base physical dimension of length with a given value.
Definition at line 47 of file Length.hpp.
~Length()
PhQ::Dimension::Length::~Length () default noexcept
Destructor. Destroys this base physical dimension of length.
Length() [3/4]
constexpr PhQ::Dimension::Length::Length (const Length & other) constexpr default
Copy constructor. Constructs a base physical dimension of length by copying another one.
Length() [4/4]
constexpr PhQ::Dimension::Length::Length (Length && other) constexpr default noexcept
Move constructor. Constructs a base physical dimension of length by moving another one.
Member Function Documentation
Abbreviation()
static std::string_view PhQ::Dimension::Length::Abbreviation () inline static noexcept
Abbreviation of this base physical dimension.
Definition at line 73 of file Length.hpp.
Referenced by Print().
Label()
static std::string_view PhQ::Dimension::Length::Label () inline static noexcept
Label of this base physical dimension.
Definition at line 78 of file Length.hpp.
Referenced by PhQ::Dimensions::JSON(), PhQ::Dimensions::XML(), and PhQ::Dimensions::YAML().
operator=() [1/2]
constexpr Length & PhQ::Dimension::Length::operator= (const Length & other) constexpr default
Copy assignment operator. Assigns the value of this base physical dimension of length by copying from another one.
operator=() [2/2]
constexpr Length & PhQ::Dimension::Length::operator= (Length && other) constexpr default noexcept
Move assignment operator. Assigns the value of this base physical dimension of length by moving another one.
Print()
std::string PhQ::Dimension::Length::Print () const inline noexcept
Prints this base physical dimension as a string.
Definition at line 83 of file Length.hpp.
References Abbreviation(), and value.
Referenced by PhQ::Dimension::operator<<(), and PhQ::Dimensions::Print().
Value()
constexpr int8_t PhQ::Dimension::Length::Value () const inline constexpr noexcept
Value of this base physical dimension.
Definition at line 68 of file Length.hpp.
References value.
Referenced by PhQ::Dimensions::JSON(), PhQ::Dimensions::XML(), and PhQ::Dimensions::YAML().
Member Data Documentation
value
int8_t PhQ::Dimension::Length::value {0} private
Value of this base physical dimension.
Definition at line 98 of file Length.hpp.
Referenced by Print(), and Value().
The documentation for this class was generated from the following file:
PhQ/Dimension/Length.hpp