Physical Quantities: PhQ::Dyad< NumericType > Class Template Reference
PhQ::Dyad< NumericType > Class Template Reference
Three-dimensional Euclidean dyadic tensor. Contains nine components in Cartesian coordinates: xx, xy, xz, yx, yy, yz, zx, zy, and zz. May be symmetric or asymmetric. For a symmetric three-dimensional Euclidean dyadic tensor, see PhQ::SymmetricDyad. For a three-dimensional Euclidean vector, see PhQ::Vector. For a two-dimensional Euclidean vector in the XY plane, see PhQ::PlanarVector.
#include "Dyad.hpp"
Public Member Functions
Dyad ()=default
Default constructor. Constructs a three-dimensional dyadic tensor with uninitialized xx, xy, xz, yx, yy, yz, zx, zy, and zz Cartesian components.
constexpr Dyad (const NumericType xx, const NumericType xy, const NumericType xz, const NumericType yx, const NumericType yy, const NumericType yz, const NumericType zx, const NumericType zy, const NumericType zz)
Constructor. Constructs a three-dimensional dyadic tensor from the given xx, xy, xz, yx, yy, yz, zx, zy, and zz Cartesian components.
constexpr Dyad (const std::array< NumericType, 9 > &xx_xy_xz_yx_yy_yz_zx_zy_zz)
Constructor. Constructs a three-dimensional dyadic tensor from a given array representing its xx, xy, xz, yx, yy, yz, zx, zy, and zz Cartesian components.
constexpr Dyad (const SymmetricDyad< NumericType > &symmetric_dyad)
Constructor. Constructs a three-dimensional dyadic tensor from a given three-dimensional symmetric dyadic tensor.
~Dyad () noexcept=default
Destructor. Destroys this three-dimensional dyadic tensor.
constexpr Dyad (const Dyad< NumericType > &other)=default
Copy constructor. Constructs a three-dimensional dyadic tensor by copying another one.
template<typename OtherNumericType >
constexpr Dyad (const Dyad< OtherNumericType > &other)
Copy constructor. Constructs a three-dimensional dyadic tensor by copying another one.
constexpr Dyad (Dyad< NumericType > &&other) noexcept=default
Move constructor. Constructs a three-dimensional dyadic tensor by moving another one.
constexpr Dyad< NumericType > & operator= (const Dyad< NumericType > &other)=default
Copy assignment operator. Assigns this three-dimensional dyadic tensor by copying another one.
template<typename OtherNumericType >
constexpr Dyad< NumericType > & operator= (const Dyad< OtherNumericType > &other)
Copy assignment operator. Assigns this three-dimensional dyadic tensor by copying another one.
constexpr Dyad< NumericType > & operator= (Dyad< NumericType > &&other) noexcept=default
Move assignment operator. Assigns this three-dimensional dyadic tensor by moving another one.
constexpr Dyad< NumericType > & operator= (const SymmetricDyad< NumericType > &other)
Assignment operator. Assigns this three-dimensional dyadic tensor by copying a three-dimensional symmetric dyadic tensor.
constexpr Dyad< NumericType > & operator= (const std::array< NumericType, 9 > &xx_xy_xz_yx_yy_yz_zx_zy_zz)
Assignment operator. Assigns this three-dimensional dyadic tensor by copying a given array representing its xx, xy, xz, yx, yy, yz, zx, zy, and zz Cartesian components.
constexpr const std::array< NumericType, 9 > & xx_xy_xz_yx_yy_yz_zx_zy_zz () const noexcept
Returns this three-dimensional symmetric dyadic tensor's xx, xy, xz, yx, yy, yz, zx, zy, and zz Cartesian components as an array.
constexpr NumericType xx () const noexcept
Returns this three-dimensional dyadic tensor's xx Cartesian component.
constexpr NumericType xy () const noexcept
Returns this three-dimensional dyadic tensor's xy Cartesian component.
constexpr NumericType xz () const noexcept
Returns this three-dimensional dyadic tensor's xz Cartesian component.
constexpr NumericType yx () const noexcept
Returns this three-dimensional dyadic tensor's yx Cartesian component.
constexpr NumericType yy () const noexcept
Returns this three-dimensional dyadic tensor's yy Cartesian component.
constexpr NumericType yz () const noexcept
Returns this three-dimensional dyadic tensor's yz Cartesian component.
constexpr NumericType zx () const noexcept
Returns this three-dimensional dyadic tensor's zx Cartesian component.
constexpr NumericType zy () const noexcept
Returns this three-dimensional dyadic tensor's zy Cartesian component.
constexpr NumericType zz () const noexcept
Returns this three-dimensional dyadic tensor's zz Cartesian component.
constexpr std::array< NumericType, 9 > & Mutable_xx_xy_xz_yx_yy_yz_zx_zy_zz () noexcept
Returns this three-dimensional symmetric dyadic tensor's xx, xy, xz, yx, yy, yz, zx, zy, and zz Cartesian components as a mutable array.
constexpr NumericType & Mutable_xx () noexcept
Returns this three-dimensional dyadic tensor's xx Cartesian component as a mutable value.
constexpr NumericType & Mutable_xy () noexcept
Returns this three-dimensional dyadic tensor's xy Cartesian component as a mutable value.
constexpr NumericType & Mutable_xz () noexcept
Returns this three-dimensional dyadic tensor's xz Cartesian component as a mutable value.
constexpr NumericType & Mutable_yx () noexcept
Returns this three-dimensional dyadic tensor's yx Cartesian component as a mutable value.
constexpr NumericType & Mutable_yy () noexcept
Returns this three-dimensional dyadic tensor's yy Cartesian component as a mutable value.
constexpr NumericType & Mutable_yz () noexcept
Returns this three-dimensional dyadic tensor's yz Cartesian component as a mutable value.
constexpr NumericType & Mutable_zx () noexcept
Returns this three-dimensional dyadic tensor's zx Cartesian component as a mutable value.
constexpr NumericType & Mutable_zy () noexcept
Returns this three-dimensional dyadic tensor's zy Cartesian component as a mutable value.
constexpr NumericType & Mutable_zz () noexcept
Returns this three-dimensional dyadic tensor's zz Cartesian component as a mutable value.
constexpr void Set_xx_xy_xz_yx_yy_yz_zx_zy_zz (const std::array< NumericType, 9 > &xx_xy_xz_yx_yy_yz_zx_zy_zz) noexcept
Sets this three-dimensional dyadic tensor's xx, xy, xz, yx, yy, yz, zx, zy, and zz Cartesian components to the given values.
constexpr void Set_xx_xy_xz_yx_yy_yz_zx_zy_zz (const NumericType xx, const NumericType xy, const NumericType xz, const NumericType yx, const NumericType yy, const NumericType yz, const NumericType zx, const NumericType zy, const NumericType zz) noexcept
Sets this three-dimensional dyadic tensor's xx, xy, xz, yx, yy, yz, zx, zy, and zz Cartesian components to the given values.
constexpr void Set_xx (const NumericType xx) noexcept
Sets this three-dimensional dyadic tensor's xx Cartesian component to a given value.
constexpr void Set_xy (const NumericType xy) noexcept
Sets this three-dimensional dyadic tensor's xy Cartesian component to a given value.
constexpr void Set_xz (const NumericType xz) noexcept
Sets this three-dimensional dyadic tensor's xz Cartesian component to a given value.
constexpr void Set_yx (const NumericType yx) noexcept
Sets this three-dimensional dyadic tensor's yx Cartesian component to a given value.
constexpr void Set_yy (const NumericType yy) noexcept
Sets this three-dimensional dyadic tensor's yy Cartesian component to a given value.
constexpr void Set_yz (const NumericType yz) noexcept
Sets this three-dimensional dyadic tensor's yz Cartesian component to a given value.
constexpr void Set_zx (const NumericType zx) noexcept
Sets this three-dimensional dyadic tensor's zx Cartesian component to a given value.
constexpr void Set_zy (const NumericType zy) noexcept
Sets this three-dimensional dyadic tensor's zy Cartesian component to a given value.
constexpr void Set_zz (const NumericType zz) noexcept
Sets this three-dimensional dyadic tensor's zz Cartesian component to a given value.
constexpr bool IsSymmetric () const noexcept
Returns whether this three-dimensional dyadic tensor is symmetric.
constexpr NumericType Trace () const noexcept
Returns the trace of this three-dimensional dyadic tensor.
constexpr NumericType Determinant () const noexcept
Returns the determinant of this three-dimensional dyadic tensor.
constexpr Dyad< NumericType > Transpose () const
Returns the transpose of this three-dimensional dyadic tensor.
constexpr Dyad< NumericType > Cofactors () const
Returns the cofactors of this three-dimensional dyadic tensor.
constexpr Dyad< NumericType > Adjugate () const
Returns the adjugate of this three-dimensional dyadic tensor.
constexpr std::optional< Dyad< NumericType > > Inverse () const
Returns the inverse of this three-dimensional dyadic tensor if it exists, or std::nullopt otherwise.
std::string Print () const
Prints this three-dimensional dyadic tensor as a string.
std::string JSON () const
Serializes this three-dimensional dyadic tensor as a JSON message.
std::string XML () const
Serializes this three-dimensional dyadic tensor as an XML message.
std::string YAML () const
Serializes this three-dimensional dyadic tensor as a YAML message.
constexpr void operator+= (const Dyad< NumericType > &other) noexcept
Adds another three-dimensional dyadic tensor to this one.
constexpr void operator-= (const Dyad< NumericType > &other) noexcept
Subtracts another three-dimensional dyadic tensor from this one.
template<typename OtherNumericType >
constexpr void operator*= (const OtherNumericType number) noexcept
Multiplies this three-dimensional dyadic tensor by the given number.
template<typename OtherNumericType >
constexpr void operator/= (const OtherNumericType number) noexcept
Divides this three-dimensional dyadic tensor by the given number.
Static Public Member Functions
static constexpr Dyad< NumericType > Zero ()
Statically creates a three-dimensional dyadic tensor with its xx, xy, xz, yx, yy, yz, zx, zy, and zz Cartesian components initialized to zero.
Private Attributes
std::array< NumericType, 9 > xx_xy_xz_yx_yy_yz_zx_zy_zz_
Cartesian components of this three-dimensional dyadic tensor.
Detailed Description
template<typename NumericType = double>
class PhQ::Dyad< NumericType >
Three-dimensional Euclidean dyadic tensor. Contains nine components in Cartesian coordinates: xx, xy, xz, yx, yy, yz, zx, zy, and zz. May be symmetric or asymmetric. For a symmetric three-dimensional Euclidean dyadic tensor, see PhQ::SymmetricDyad. For a three-dimensional Euclidean vector, see PhQ::Vector. For a two-dimensional Euclidean vector in the XY plane, see PhQ::PlanarVector.
Template Parameters
NumericType Floating-point numeric type: float, double, or long double. Defaults to double if unspecified.
Definition at line 51 of file Dyad.hpp.
Constructor & Destructor Documentation
Dyad() [1/7]
template<typename NumericType = double> PhQ::Dyad< NumericType >::Dyad () default
Default constructor. Constructs a three-dimensional dyadic tensor with uninitialized xx, xy, xz, yx, yy, yz, zx, zy, and zz Cartesian components.
Dyad() [2/7]
template<typename NumericType = double> constexpr PhQ::Dyad< NumericType >::Dyad (const NumericType xx, const NumericType xy, const NumericType xz, const NumericType yx, const NumericType yy, const NumericType yz, const NumericType zx, const NumericType zy, const NumericType zz) inline constexpr
Constructor. Constructs a three-dimensional dyadic tensor from the given xx, xy, xz, yx, yy, yz, zx, zy, and zz Cartesian components.
Definition at line 63 of file Dyad.hpp.
References PhQ::Dyad< NumericType >::xx(), PhQ::Dyad< NumericType >::xy(), PhQ::Dyad< NumericType >::xz(), PhQ::Dyad< NumericType >::yx(), PhQ::Dyad< NumericType >::yy(), PhQ::Dyad< NumericType >::yz(), PhQ::Dyad< NumericType >::zx(), PhQ::Dyad< NumericType >::zy(), and PhQ::Dyad< NumericType >::zz().
Dyad() [3/7]
template<typename NumericType = double> constexpr PhQ::Dyad< NumericType >::Dyad (const std::array< NumericType, 9 > & xx_xy_xz_yx_yy_yz_zx_zy_zz) inline explicit constexpr
Constructor. Constructs a three-dimensional dyadic tensor from a given array representing its xx, xy, xz, yx, yy, yz, zx, zy, and zz Cartesian components.
Definition at line 70 of file Dyad.hpp.
Dyad() [4/7]
template<typename NumericType = double> constexpr PhQ::Dyad< NumericType >::Dyad (const SymmetricDyad< NumericType > & symmetric_dyad) inline explicit constexpr
Constructor. Constructs a three-dimensional dyadic tensor from a given three-dimensional symmetric dyadic tensor.
Definition at line 75 of file Dyad.hpp.
References PhQ::SymmetricDyad< NumericType >::xx(), PhQ::SymmetricDyad< NumericType >::xy(), PhQ::SymmetricDyad< NumericType >::xz(), PhQ::SymmetricDyad< NumericType >::yx(), PhQ::SymmetricDyad< NumericType >::yy(), PhQ::SymmetricDyad< NumericType >::yz(), PhQ::SymmetricDyad< NumericType >::zx(), PhQ::SymmetricDyad< NumericType >::zy(), and PhQ::SymmetricDyad< NumericType >::zz().
~Dyad()
template<typename NumericType = double> PhQ::Dyad< NumericType >::~Dyad () default noexcept
Destructor. Destroys this three-dimensional dyadic tensor.
Dyad() [5/7]
template<typename NumericType = double> constexpr PhQ::Dyad< NumericType >::Dyad (const Dyad< NumericType > & other) constexpr default
Copy constructor. Constructs a three-dimensional dyadic tensor by copying another one.
Dyad() [6/7]
template<typename NumericType = double> template<typename OtherNumericType > constexpr PhQ::Dyad< NumericType >::Dyad (const Dyad< OtherNumericType > & other) inline explicit constexpr
Copy constructor. Constructs a three-dimensional dyadic tensor by copying another one.
Definition at line 89 of file Dyad.hpp.
Dyad() [7/7]
template<typename NumericType = double> constexpr PhQ::Dyad< NumericType >::Dyad (Dyad< NumericType > && other) constexpr default noexcept
Move constructor. Constructs a three-dimensional dyadic tensor by moving another one.
Member Function Documentation
Adjugate()
template<typename NumericType = double> constexpr Dyad< NumericType > PhQ::Dyad< NumericType >::Adjugate () const inline constexpr
Returns the adjugate of this three-dimensional dyadic tensor.
Definition at line 377 of file Dyad.hpp.
References PhQ::Dyad< NumericType >::Cofactors().
Cofactors()
template<typename NumericType = double> constexpr Dyad< NumericType > PhQ::Dyad< NumericType >::Cofactors () const inline constexpr
Returns the cofactors of this three-dimensional dyadic tensor.
Definition at line 362 of file Dyad.hpp.
References PhQ::Dyad< NumericType >::xx(), PhQ::Dyad< NumericType >::xy(), PhQ::Dyad< NumericType >::xz(), PhQ::Dyad< NumericType >::yx(), PhQ::Dyad< NumericType >::yy(), PhQ::Dyad< NumericType >::yz(), PhQ::Dyad< NumericType >::zx(), PhQ::Dyad< NumericType >::zy(), and PhQ::Dyad< NumericType >::zz().
Referenced by PhQ::Dyad< NumericType >::Adjugate().
Determinant()
template<typename NumericType = double> constexpr NumericType PhQ::Dyad< NumericType >::Determinant () const inline constexpr noexcept
Returns the determinant of this three-dimensional dyadic tensor.
Definition at line 351 of file Dyad.hpp.
References PhQ::Dyad< NumericType >::xx(), PhQ::Dyad< NumericType >::xy(), PhQ::Dyad< NumericType >::xz(), PhQ::Dyad< NumericType >::yx(), PhQ::Dyad< NumericType >::yy(), PhQ::Dyad< NumericType >::yz(), PhQ::Dyad< NumericType >::zx(), PhQ::Dyad< NumericType >::zy(), and PhQ::Dyad< NumericType >::zz().
Inverse()
template<typename NumericType > constexpr std::optional< Dyad< NumericType > > PhQ::Dyad< NumericType >::Inverse () const inline constexpr
Returns the inverse of this three-dimensional dyadic tensor if it exists, or std::nullopt otherwise.
Definition at line 713 of file Dyad.hpp.
IsSymmetric()
template<typename NumericType = double> constexpr bool PhQ::Dyad< NumericType >::IsSymmetric () const inline constexpr noexcept
Returns whether this three-dimensional dyadic tensor is symmetric.
Definition at line 341 of file Dyad.hpp.
References PhQ::Dyad< NumericType >::xy(), PhQ::Dyad< NumericType >::xz(), PhQ::Dyad< NumericType >::yx(), PhQ::Dyad< NumericType >::yz(), PhQ::Dyad< NumericType >::zx(), and PhQ::Dyad< NumericType >::zy().
JSON()
template<typename NumericType = double> std::string PhQ::Dyad< NumericType >::JSON () const inline
Serializes this three-dimensional dyadic tensor as a JSON message.
Definition at line 393 of file Dyad.hpp.
References PhQ::Print(), PhQ::Dyad< NumericType >::xx(), PhQ::Dyad< NumericType >::xy(), PhQ::Dyad< NumericType >::xz(), PhQ::Dyad< NumericType >::yx(), PhQ::Dyad< NumericType >::yy(), PhQ::Dyad< NumericType >::yz(), PhQ::Dyad< NumericType >::zx(), PhQ::Dyad< NumericType >::zy(), and PhQ::Dyad< NumericType >::zz().
Mutable_xx()
template<typename NumericType = double> constexpr NumericType & PhQ::Dyad< NumericType >::Mutable_xx () inline constexpr noexcept
Returns this three-dimensional dyadic tensor's xx Cartesian component as a mutable value.
Definition at line 219 of file Dyad.hpp.
References PhQ::Dyad< NumericType >::xx_xy_xz_yx_yy_yz_zx_zy_zz_.
Mutable_xx_xy_xz_yx_yy_yz_zx_zy_zz()
template<typename NumericType = double> constexpr std::array< NumericType, 9 > & PhQ::Dyad< NumericType >::Mutable_xx_xy_xz_yx_yy_yz_zx_zy_zz () inline constexpr noexcept
Returns this three-dimensional symmetric dyadic tensor's xx, xy, xz, yx, yy, yz, zx, zy, and zz Cartesian components as a mutable array.
Definition at line 213 of file Dyad.hpp.
References PhQ::Dyad< NumericType >::xx_xy_xz_yx_yy_yz_zx_zy_zz_.
Referenced by PhQ::ConvertInPlace().
Mutable_xy()
template<typename NumericType = double> constexpr NumericType & PhQ::Dyad< NumericType >::Mutable_xy () inline constexpr noexcept
Returns this three-dimensional dyadic tensor's xy Cartesian component as a mutable value.
Definition at line 225 of file Dyad.hpp.
Mutable_xz()
template<typename NumericType = double> constexpr NumericType & PhQ::Dyad< NumericType >::Mutable_xz () inline constexpr noexcept
Returns this three-dimensional dyadic tensor's xz Cartesian component as a mutable value.
Definition at line 231 of file Dyad.hpp.
References PhQ::Dyad< NumericType >::xx_xy_xz_yx_yy_yz_zx_zy_zz_.
Mutable_yx()
template<typename NumericType = double> constexpr NumericType & PhQ::Dyad< NumericType >::Mutable_yx () inline constexpr noexcept
Returns this three-dimensional dyadic tensor's yx Cartesian component as a mutable value.
Definition at line 237 of file Dyad.hpp.
References PhQ::Dyad< NumericType >::xx_xy_xz_yx_yy_yz_zx_zy_zz_.
Mutable_yy()
template<typename NumericType = double> constexpr NumericType & PhQ::Dyad< NumericType >::Mutable_yy () inline constexpr noexcept
Returns this three-dimensional dyadic tensor's yy Cartesian component as a mutable value.
Definition at line 243 of file Dyad.hpp.
References PhQ::Dyad< NumericType >::xx_xy_xz_yx_yy_yz_zx_zy_zz_.
Mutable_yz()
template<typename NumericType = double> constexpr NumericType & PhQ::Dyad< NumericType >::Mutable_yz () inline constexpr noexcept
Returns this three-dimensional dyadic tensor's yz Cartesian component as a mutable value.
Definition at line 249 of file Dyad.hpp.
References PhQ::Dyad< NumericType >::xx_xy_xz_yx_yy_yz_zx_zy_zz_.
Mutable_zx()
template<typename NumericType = double> constexpr NumericType & PhQ::Dyad< NumericType >::Mutable_zx () inline constexpr noexcept
Returns this three-dimensional dyadic tensor's zx Cartesian component as a mutable value.
Definition at line 255 of file Dyad.hpp.
References PhQ::Dyad< NumericType >::xx_xy_xz_yx_yy_yz_zx_zy_zz_.
Mutable_zy()
template<typename NumericType = double> constexpr NumericType & PhQ::Dyad< NumericType >::Mutable_zy () inline constexpr noexcept
Returns this three-dimensional dyadic tensor's zy Cartesian component as a mutable value.
Definition at line 261 of file Dyad.hpp.
References PhQ::Dyad< NumericType >::xx_xy_xz_yx_yy_yz_zx_zy_zz_.
Mutable_zz()
template<typename NumericType = double> constexpr NumericType & PhQ::Dyad< NumericType >::Mutable_zz () inline constexpr noexcept
Returns this three-dimensional dyadic tensor's zz Cartesian component as a mutable value.
Definition at line 267 of file Dyad.hpp.
References PhQ::Dyad< NumericType >::xx_xy_xz_yx_yy_yz_zx_zy_zz_.
operator*=()
template<typename NumericType = double> template<typename OtherNumericType > constexpr void PhQ::Dyad< NumericType >::operator*= (const OtherNumericType number) inline constexpr noexcept
Multiplies this three-dimensional dyadic tensor by the given number.
Template Parameters
OtherNumericType Floating-point numeric type of the given number. Deduced automatically.
Definition at line 446 of file Dyad.hpp.
References PhQ::Dyad< NumericType >::xx_xy_xz_yx_yy_yz_zx_zy_zz_.
operator+=()
template<typename NumericType = double> constexpr void PhQ::Dyad< NumericType >::operator+= (const Dyad< NumericType > & other) inline constexpr noexcept
Adds another three-dimensional dyadic tensor to this one.
Definition at line 417 of file Dyad.hpp.
References PhQ::Dyad< NumericType >::xx_xy_xz_yx_yy_yz_zx_zy_zz_.
operator-=()
template<typename NumericType = double> constexpr void PhQ::Dyad< NumericType >::operator-= (const Dyad< NumericType > & other) inline constexpr noexcept
Subtracts another three-dimensional dyadic tensor from this one.
Definition at line 430 of file Dyad.hpp.
References PhQ::Dyad< NumericType >::xx_xy_xz_yx_yy_yz_zx_zy_zz_.
operator/=()
template<typename NumericType = double> template<typename OtherNumericType > constexpr void PhQ::Dyad< NumericType >::operator/= (const OtherNumericType number) inline constexpr noexcept
Divides this three-dimensional dyadic tensor by the given number.
Template Parameters
OtherNumericType Floating-point numeric type of the given number. Deduced automatically.
Definition at line 462 of file Dyad.hpp.
References PhQ::Dyad< NumericType >::xx_xy_xz_yx_yy_yz_zx_zy_zz_.
operator=() [1/5]
template<typename NumericType = double> constexpr Dyad< NumericType > & PhQ::Dyad< NumericType >::operator= (const Dyad< NumericType > & other) constexpr default
Copy assignment operator. Assigns this three-dimensional dyadic tensor by copying another one.
operator=() [2/5]
template<typename NumericType = double> template<typename OtherNumericType > constexpr Dyad< NumericType > & PhQ::Dyad< NumericType >::operator= (const Dyad< OtherNumericType > & other) inline constexpr
Copy assignment operator. Assigns this three-dimensional dyadic tensor by copying another one.
Definition at line 107 of file Dyad.hpp.
References PhQ::Dyad< NumericType >::xx(), PhQ::Dyad< NumericType >::xx_xy_xz_yx_yy_yz_zx_zy_zz_, PhQ::Dyad< NumericType >::xy(), PhQ::Dyad< NumericType >::xz(), PhQ::Dyad< NumericType >::yx(), PhQ::Dyad< NumericType >::yy(), PhQ::Dyad< NumericType >::yz(), PhQ::Dyad< NumericType >::zx(), PhQ::Dyad< NumericType >::zy(), and PhQ::Dyad< NumericType >::zz().
operator=() [3/5]
template<typename NumericType = double> constexpr Dyad< NumericType > & PhQ::Dyad< NumericType >::operator= (const std::array< NumericType, 9 > & xx_xy_xz_yx_yy_yz_zx_zy_zz) inline constexpr
Assignment operator. Assigns this three-dimensional dyadic tensor by copying a given array representing its xx, xy, xz, yx, yy, yz, zx, zy, and zz Cartesian components.
Definition at line 141 of file Dyad.hpp.
References PhQ::Dyad< NumericType >::xx_xy_xz_yx_yy_yz_zx_zy_zz(), and PhQ::Dyad< NumericType >::xx_xy_xz_yx_yy_yz_zx_zy_zz_.
operator=() [4/5]
template<typename NumericType = double> constexpr Dyad< NumericType > & PhQ::Dyad< NumericType >::operator= (const SymmetricDyad< NumericType > & other) inline constexpr
Assignment operator. Assigns this three-dimensional dyadic tensor by copying a three-dimensional symmetric dyadic tensor.
Definition at line 126 of file Dyad.hpp.
References PhQ::SymmetricDyad< NumericType >::xx(), PhQ::Dyad< NumericType >::xx_xy_xz_yx_yy_yz_zx_zy_zz_, PhQ::SymmetricDyad< NumericType >::xy(), PhQ::SymmetricDyad< NumericType >::xz(), PhQ::SymmetricDyad< NumericType >::yx(), PhQ::SymmetricDyad< NumericType >::yy(), PhQ::SymmetricDyad< NumericType >::yz(), PhQ::SymmetricDyad< NumericType >::zx(), PhQ::SymmetricDyad< NumericType >::zy(), and PhQ::SymmetricDyad< NumericType >::zz().
operator=() [5/5]
template<typename NumericType = double> constexpr Dyad< NumericType > & PhQ::Dyad< NumericType >::operator= (Dyad< NumericType > && other) constexpr default noexcept
Move assignment operator. Assigns this three-dimensional dyadic tensor by moving another one.
Print()
template<typename NumericType = double> std::string PhQ::Dyad< NumericType >::Print () const inline
Prints this three-dimensional dyadic tensor as a string.
Definition at line 386 of file Dyad.hpp.
References PhQ::Print(), PhQ::Dyad< NumericType >::xx(), PhQ::Dyad< NumericType >::xy(), PhQ::Dyad< NumericType >::xz(), PhQ::Dyad< NumericType >::yx(), PhQ::Dyad< NumericType >::yy(), PhQ::Dyad< NumericType >::yz(), PhQ::Dyad< NumericType >::zx(), PhQ::Dyad< NumericType >::zy(), and PhQ::Dyad< NumericType >::zz().
Referenced by PhQ::operator<<().
Set_xx()
template<typename NumericType = double> constexpr void PhQ::Dyad< NumericType >::Set_xx (const NumericType xx) inline constexpr noexcept
Sets this three-dimensional dyadic tensor's xx Cartesian component to a given value.
Definition at line 296 of file Dyad.hpp.
References PhQ::Dyad< NumericType >::xx(), and PhQ::Dyad< NumericType >::xx_xy_xz_yx_yy_yz_zx_zy_zz_.
Set_xx_xy_xz_yx_yy_yz_zx_zy_zz() [1/2]
template<typename NumericType = double> constexpr void PhQ::Dyad< NumericType >::Set_xx_xy_xz_yx_yy_yz_zx_zy_zz (const NumericType xx, const NumericType xy, const NumericType xz, const NumericType yx, const NumericType yy, const NumericType yz, const NumericType zx, const NumericType zy, const NumericType zz) inline constexpr noexcept
Sets this three-dimensional dyadic tensor's xx, xy, xz, yx, yy, yz, zx, zy, and zz Cartesian components to the given values.
Definition at line 280 of file Dyad.hpp.
References PhQ::Dyad< NumericType >::xx(), PhQ::Dyad< NumericType >::xx_xy_xz_yx_yy_yz_zx_zy_zz_, PhQ::Dyad< NumericType >::xy(), PhQ::Dyad< NumericType >::xz(), PhQ::Dyad< NumericType >::yx(), PhQ::Dyad< NumericType >::yy(), PhQ::Dyad< NumericType >::yz(), PhQ::Dyad< NumericType >::zx(), PhQ::Dyad< NumericType >::zy(), and PhQ::Dyad< NumericType >::zz().
Set_xx_xy_xz_yx_yy_yz_zx_zy_zz() [2/2]
template<typename NumericType = double> constexpr void PhQ::Dyad< NumericType >::Set_xx_xy_xz_yx_yy_yz_zx_zy_zz (const std::array< NumericType, 9 > & xx_xy_xz_yx_yy_yz_zx_zy_zz) inline constexpr noexcept
Sets this three-dimensional dyadic tensor's xx, xy, xz, yx, yy, yz, zx, zy, and zz Cartesian components to the given values.
Definition at line 273 of file Dyad.hpp.
References PhQ::Dyad< NumericType >::xx_xy_xz_yx_yy_yz_zx_zy_zz(), and PhQ::Dyad< NumericType >::xx_xy_xz_yx_yy_yz_zx_zy_zz_.
Set_xy()
template<typename NumericType = double> constexpr void PhQ::Dyad< NumericType >::Set_xy (const NumericType xy) inline constexpr noexcept
Sets this three-dimensional dyadic tensor's xy Cartesian component to a given value.
Definition at line 301 of file Dyad.hpp.
References PhQ::Dyad< NumericType >::xx_xy_xz_yx_yy_yz_zx_zy_zz_, and PhQ::Dyad< NumericType >::xy().
Set_xz()
template<typename NumericType = double> constexpr void PhQ::Dyad< NumericType >::Set_xz (const NumericType xz) inline constexpr noexcept
Sets this three-dimensional dyadic tensor's xz Cartesian component to a given value.
Definition at line 306 of file Dyad.hpp.
References PhQ::Dyad< NumericType >::xx_xy_xz_yx_yy_yz_zx_zy_zz_, and PhQ::Dyad< NumericType >::xz().
Set_yx()
template<typename NumericType = double> constexpr void PhQ::Dyad< NumericType >::Set_yx (const NumericType yx) inline constexpr noexcept
Sets this three-dimensional dyadic tensor's yx Cartesian component to a given value.
Definition at line 311 of file Dyad.hpp.
References PhQ::Dyad< NumericType >::xx_xy_xz_yx_yy_yz_zx_zy_zz_, and PhQ::Dyad< NumericType >::yx().
Set_yy()
template<typename NumericType = double> constexpr void PhQ::Dyad< NumericType >::Set_yy (const NumericType yy) inline constexpr noexcept
Sets this three-dimensional dyadic tensor's yy Cartesian component to a given value.
Definition at line 316 of file Dyad.hpp.
References PhQ::Dyad< NumericType >::xx_xy_xz_yx_yy_yz_zx_zy_zz_, and PhQ::Dyad< NumericType >::yy().
Set_yz()
template<typename NumericType = double> constexpr void PhQ::Dyad< NumericType >::Set_yz (const NumericType yz) inline constexpr noexcept
Sets this three-dimensional dyadic tensor's yz Cartesian component to a given value.
Definition at line 321 of file Dyad.hpp.
References PhQ::Dyad< NumericType >::xx_xy_xz_yx_yy_yz_zx_zy_zz_, and PhQ::Dyad< NumericType >::yz().
Set_zx()
template<typename NumericType = double> constexpr void PhQ::Dyad< NumericType >::Set_zx (const NumericType zx) inline constexpr noexcept
Sets this three-dimensional dyadic tensor's zx Cartesian component to a given value.
Definition at line 326 of file Dyad.hpp.
References PhQ::Dyad< NumericType >::xx_xy_xz_yx_yy_yz_zx_zy_zz_, and PhQ::Dyad< NumericType >::zx().
Set_zy()
template<typename NumericType = double> constexpr void PhQ::Dyad< NumericType >::Set_zy (const NumericType zy) inline constexpr noexcept
Sets this three-dimensional dyadic tensor's zy Cartesian component to a given value.
Definition at line 331 of file Dyad.hpp.
References PhQ::Dyad< NumericType >::xx_xy_xz_yx_yy_yz_zx_zy_zz_, and PhQ::Dyad< NumericType >::zy().
Set_zz()
template<typename NumericType = double> constexpr void PhQ::Dyad< NumericType >::Set_zz (const NumericType zz) inline constexpr noexcept
Sets this three-dimensional dyadic tensor's zz Cartesian component to a given value.
Definition at line 336 of file Dyad.hpp.
References PhQ::Dyad< NumericType >::xx_xy_xz_yx_yy_yz_zx_zy_zz_, and PhQ::Dyad< NumericType >::zz().
Trace()
template<typename NumericType = double> constexpr NumericType PhQ::Dyad< NumericType >::Trace () const inline constexpr noexcept
Returns the trace of this three-dimensional dyadic tensor.
Definition at line 346 of file Dyad.hpp.
References PhQ::Dyad< NumericType >::xx(), PhQ::Dyad< NumericType >::yy(), and PhQ::Dyad< NumericType >::zz().
Transpose()
template<typename NumericType = double> constexpr Dyad< NumericType > PhQ::Dyad< NumericType >::Transpose () const inline constexpr
Returns the transpose of this three-dimensional dyadic tensor.
Definition at line 357 of file Dyad.hpp.
References PhQ::Dyad< NumericType >::xx(), PhQ::Dyad< NumericType >::xy(), PhQ::Dyad< NumericType >::xz(), PhQ::Dyad< NumericType >::yx(), PhQ::Dyad< NumericType >::yy(), PhQ::Dyad< NumericType >::yz(), PhQ::Dyad< NumericType >::zx(), PhQ::Dyad< NumericType >::zy(), and PhQ::Dyad< NumericType >::zz().
XML()
template<typename NumericType = double> std::string PhQ::Dyad< NumericType >::XML () const inline
Serializes this three-dimensional dyadic tensor as an XML message.
Definition at line 401 of file Dyad.hpp.
References PhQ::Print(), PhQ::Dyad< NumericType >::xx(), PhQ::Dyad< NumericType >::xy(), PhQ::Dyad< NumericType >::xz(), PhQ::Dyad< NumericType >::yx(), PhQ::Dyad< NumericType >::yy(), PhQ::Dyad< NumericType >::yz(), PhQ::Dyad< NumericType >::zx(), PhQ::Dyad< NumericType >::zy(), and PhQ::Dyad< NumericType >::zz().
xx()
template<typename NumericType = double> constexpr NumericType PhQ::Dyad< NumericType >::xx () const inline constexpr noexcept
Returns this three-dimensional dyadic tensor's xx Cartesian component.
Definition at line 166 of file Dyad.hpp.
References PhQ::Dyad< NumericType >::xx_xy_xz_yx_yy_yz_zx_zy_zz_.
Referenced by PhQ::Dyad< NumericType >::Cofactors(), PhQ::Dyad< NumericType >::Determinant(), PhQ::Dyad< NumericType >::Dyad(), PhQ::Dyad< NumericType >::JSON(), PhQ::operator*(), PhQ::operator*(), PhQ::operator*(), PhQ::operator*(), PhQ::operator*(), PhQ::operator*(), PhQ::operator+(), PhQ::operator-(), PhQ::operator/(), PhQ::Dyad< NumericType >::operator=(), PhQ::Dyad< NumericType >::Print(), PhQ::Dyad< NumericType >::Set_xx(), PhQ::Dyad< NumericType >::Set_xx_xy_xz_yx_yy_yz_zx_zy_zz(), PhQ::Dyad< NumericType >::Trace(), PhQ::Dyad< NumericType >::Transpose(), PhQ::Dyad< NumericType >::XML(), and PhQ::Dyad< NumericType >::YAML().
xx_xy_xz_yx_yy_yz_zx_zy_zz()
template<typename NumericType = double> constexpr const std::array< NumericType, 9 > & PhQ::Dyad< NumericType >::xx_xy_xz_yx_yy_yz_zx_zy_zz () const inline constexpr noexcept
Returns this three-dimensional symmetric dyadic tensor's xx, xy, xz, yx, yy, yz, zx, zy, and zz Cartesian components as an array.
Definition at line 161 of file Dyad.hpp.
References PhQ::Dyad< NumericType >::xx_xy_xz_yx_yy_yz_zx_zy_zz_.
Referenced by PhQ::Convert(), PhQ::ConvertStatically(), PhQ::Dyad< NumericType >::operator=(), and PhQ::Dyad< NumericType >::Set_xx_xy_xz_yx_yy_yz_zx_zy_zz().
xy()
template<typename NumericType = double> constexpr NumericType PhQ::Dyad< NumericType >::xy () const inline constexpr noexcept
Returns this three-dimensional dyadic tensor's xy Cartesian component.
Definition at line 171 of file Dyad.hpp.
References PhQ::Dyad< NumericType >::xx_xy_xz_yx_yy_yz_zx_zy_zz_.
Referenced by PhQ::Dyad< NumericType >::Cofactors(), PhQ::Dyad< NumericType >::Determinant(), PhQ::Dyad< NumericType >::Dyad(), PhQ::Dyad< NumericType >::IsSymmetric(), PhQ::Dyad< NumericType >::JSON(), PhQ::operator*(), PhQ::operator*(), PhQ::operator*(), PhQ::operator*(), PhQ::operator*(), PhQ::operator*(), PhQ::operator+(), PhQ::operator-(), PhQ::operator/(), PhQ::Dyad< NumericType >::operator=(), PhQ::Dyad< NumericType >::Print(), PhQ::Dyad< NumericType >::Set_xx_xy_xz_yx_yy_yz_zx_zy_zz(), PhQ::Dyad< NumericType >::Set_xy(), PhQ::Dyad< NumericType >::Transpose(), PhQ::Dyad< NumericType >::XML(), and PhQ::Dyad< NumericType >::YAML().
xz()
template<typename NumericType = double> constexpr NumericType PhQ::Dyad< NumericType >::xz () const inline constexpr noexcept
Returns this three-dimensional dyadic tensor's xz Cartesian component.
Definition at line 176 of file Dyad.hpp.
References PhQ::Dyad< NumericType >::xx_xy_xz_yx_yy_yz_zx_zy_zz_.
Referenced by PhQ::Dyad< NumericType >::Cofactors(), PhQ::Dyad< NumericType >::Determinant(), PhQ::Dyad< NumericType >::Dyad(), PhQ::Dyad< NumericType >::IsSymmetric(), PhQ::Dyad< NumericType >::JSON(), PhQ::operator*(), PhQ::operator*(), PhQ::operator*(), PhQ::operator*(), PhQ::operator*(), PhQ::operator+(), PhQ::operator-(), PhQ::operator/(), PhQ::Dyad< NumericType >::operator=(), PhQ::Dyad< NumericType >::Print(), PhQ::Dyad< NumericType >::Set_xx_xy_xz_yx_yy_yz_zx_zy_zz(), PhQ::Dyad< NumericType >::Set_xz(), PhQ::Dyad< NumericType >::Transpose(), PhQ::Dyad< NumericType >::XML(), and PhQ::Dyad< NumericType >::YAML().
YAML()
template<typename NumericType = double> std::string PhQ::Dyad< NumericType >::YAML () const inline
Serializes this three-dimensional dyadic tensor as a YAML message.
Definition at line 409 of file Dyad.hpp.
References PhQ::Print(), PhQ::Dyad< NumericType >::xx(), PhQ::Dyad< NumericType >::xy(), PhQ::Dyad< NumericType >::xz(), PhQ::Dyad< NumericType >::yx(), PhQ::Dyad< NumericType >::yy(), PhQ::Dyad< NumericType >::yz(), PhQ::Dyad< NumericType >::zx(), PhQ::Dyad< NumericType >::zy(), and PhQ::Dyad< NumericType >::zz().
yx()
template<typename NumericType = double> constexpr NumericType PhQ::Dyad< NumericType >::yx () const inline constexpr noexcept
Returns this three-dimensional dyadic tensor's yx Cartesian component.
Definition at line 181 of file Dyad.hpp.
References PhQ::Dyad< NumericType >::xx_xy_xz_yx_yy_yz_zx_zy_zz_.
Referenced by PhQ::Dyad< NumericType >::Cofactors(), PhQ::Dyad< NumericType >::Determinant(), PhQ::Dyad< NumericType >::Dyad(), PhQ::Dyad< NumericType >::IsSymmetric(), PhQ::Dyad< NumericType >::JSON(), PhQ::operator*(), PhQ::operator*(), PhQ::operator*(), PhQ::operator*(), PhQ::operator*(), PhQ::operator*(), PhQ::operator+(), PhQ::operator-(), PhQ::operator/(), PhQ::Dyad< NumericType >::operator=(), PhQ::Dyad< NumericType >::Print(), PhQ::Dyad< NumericType >::Set_xx_xy_xz_yx_yy_yz_zx_zy_zz(), PhQ::Dyad< NumericType >::Set_yx(), PhQ::Dyad< NumericType >::Transpose(), PhQ::Dyad< NumericType >::XML(), and PhQ::Dyad< NumericType >::YAML().
yy()
template<typename NumericType = double> constexpr NumericType PhQ::Dyad< NumericType >::yy () const inline constexpr noexcept
Returns this three-dimensional dyadic tensor's yy Cartesian component.
Definition at line 186 of file Dyad.hpp.
References PhQ::Dyad< NumericType >::xx_xy_xz_yx_yy_yz_zx_zy_zz_.
Referenced by PhQ::Dyad< NumericType >::Cofactors(), PhQ::Dyad< NumericType >::Determinant(), PhQ::Dyad< NumericType >::Dyad(), PhQ::Dyad< NumericType >::JSON(), PhQ::operator*(), PhQ::operator*(), PhQ::operator*(), PhQ::operator*(), PhQ::operator*(), PhQ::operator*(), PhQ::operator+(), PhQ::operator-(), PhQ::operator/(), PhQ::Dyad< NumericType >::operator=(), PhQ::Dyad< NumericType >::Print(), PhQ::Dyad< NumericType >::Set_xx_xy_xz_yx_yy_yz_zx_zy_zz(), PhQ::Dyad< NumericType >::Set_yy(), PhQ::Dyad< NumericType >::Trace(), PhQ::Dyad< NumericType >::Transpose(), PhQ::Dyad< NumericType >::XML(), and PhQ::Dyad< NumericType >::YAML().
yz()
template<typename NumericType = double> constexpr NumericType PhQ::Dyad< NumericType >::yz () const inline constexpr noexcept
Returns this three-dimensional dyadic tensor's yz Cartesian component.
Definition at line 191 of file Dyad.hpp.
References PhQ::Dyad< NumericType >::xx_xy_xz_yx_yy_yz_zx_zy_zz_.
Referenced by PhQ::Dyad< NumericType >::Cofactors(), PhQ::Dyad< NumericType >::Determinant(), PhQ::Dyad< NumericType >::Dyad(), PhQ::Dyad< NumericType >::IsSymmetric(), PhQ::Dyad< NumericType >::JSON(), PhQ::operator*(), PhQ::operator*(), PhQ::operator*(), PhQ::operator*(), PhQ::operator*(), PhQ::operator+(), PhQ::operator-(), PhQ::operator/(), PhQ::Dyad< NumericType >::operator=(), PhQ::Dyad< NumericType >::Print(), PhQ::Dyad< NumericType >::Set_xx_xy_xz_yx_yy_yz_zx_zy_zz(), PhQ::Dyad< NumericType >::Set_yz(), PhQ::Dyad< NumericType >::Transpose(), PhQ::Dyad< NumericType >::XML(), and PhQ::Dyad< NumericType >::YAML().
Zero()
template<typename NumericType = double> static constexpr Dyad< NumericType > PhQ::Dyad< NumericType >::Zero () inline static constexpr
Statically creates a three-dimensional dyadic tensor with its xx, xy, xz, yx, yy, yz, zx, zy, and zz Cartesian components initialized to zero.
Definition at line 149 of file Dyad.hpp.
Referenced by PhQ::DisplacementGradient< NumericType >::Zero(), and PhQ::VelocityGradient< NumericType >::Zero().
zx()
template<typename NumericType = double> constexpr NumericType PhQ::Dyad< NumericType >::zx () const inline constexpr noexcept
Returns this three-dimensional dyadic tensor's zx Cartesian component.
Definition at line 196 of file Dyad.hpp.
References PhQ::Dyad< NumericType >::xx_xy_xz_yx_yy_yz_zx_zy_zz_.
Referenced by PhQ::Dyad< NumericType >::Cofactors(), PhQ::Dyad< NumericType >::Determinant(), PhQ::Dyad< NumericType >::Dyad(), PhQ::Dyad< NumericType >::IsSymmetric(), PhQ::Dyad< NumericType >::JSON(), PhQ::operator*(), PhQ::operator*(), PhQ::operator*(), PhQ::operator*(), PhQ::operator*(), PhQ::operator*(), PhQ::operator+(), PhQ::operator-(), PhQ::operator/(), PhQ::Dyad< NumericType >::operator=(), PhQ::Dyad< NumericType >::Print(), PhQ::Dyad< NumericType >::Set_xx_xy_xz_yx_yy_yz_zx_zy_zz(), PhQ::Dyad< NumericType >::Set_zx(), PhQ::Dyad< NumericType >::Transpose(), PhQ::Dyad< NumericType >::XML(), and PhQ::Dyad< NumericType >::YAML().
zy()
template<typename NumericType = double> constexpr NumericType PhQ::Dyad< NumericType >::zy () const inline constexpr noexcept
Returns this three-dimensional dyadic tensor's zy Cartesian component.
Definition at line 201 of file Dyad.hpp.
References PhQ::Dyad< NumericType >::xx_xy_xz_yx_yy_yz_zx_zy_zz_.
Referenced by PhQ::Dyad< NumericType >::Cofactors(), PhQ::Dyad< NumericType >::Determinant(), PhQ::Dyad< NumericType >::Dyad(), PhQ::Dyad< NumericType >::IsSymmetric(), PhQ::Dyad< NumericType >::JSON(), PhQ::operator*(), PhQ::operator*(), PhQ::operator*(), PhQ::operator*(), PhQ::operator*(), PhQ::operator*(), PhQ::operator+(), PhQ::operator-(), PhQ::operator/(), PhQ::Dyad< NumericType >::operator=(), PhQ::Dyad< NumericType >::Print(), PhQ::Dyad< NumericType >::Set_xx_xy_xz_yx_yy_yz_zx_zy_zz(), PhQ::Dyad< NumericType >::Set_zy(), PhQ::Dyad< NumericType >::Transpose(), PhQ::Dyad< NumericType >::XML(), and PhQ::Dyad< NumericType >::YAML().
zz()
template<typename NumericType = double> constexpr NumericType PhQ::Dyad< NumericType >::zz () const inline constexpr noexcept
Returns this three-dimensional dyadic tensor's zz Cartesian component.
Definition at line 206 of file Dyad.hpp.
References PhQ::Dyad< NumericType >::xx_xy_xz_yx_yy_yz_zx_zy_zz_.
Referenced by PhQ::Dyad< NumericType >::Cofactors(), PhQ::Dyad< NumericType >::Determinant(), PhQ::Dyad< NumericType >::Dyad(), PhQ::Dyad< NumericType >::JSON(), PhQ::operator*(), PhQ::operator*(), PhQ::operator*(), PhQ::operator*(), PhQ::operator*(), PhQ::operator+(), PhQ::operator-(), PhQ::operator/(), PhQ::Dyad< NumericType >::operator=(), PhQ::Dyad< NumericType >::Print(), PhQ::Dyad< NumericType >::Set_xx_xy_xz_yx_yy_yz_zx_zy_zz(), PhQ::Dyad< NumericType >::Set_zz(), PhQ::Dyad< NumericType >::Trace(), PhQ::Dyad< NumericType >::Transpose(), PhQ::Dyad< NumericType >::XML(), and PhQ::Dyad< NumericType >::YAML().
Member Data Documentation
xx_xy_xz_yx_yy_yz_zx_zy_zz_
template<typename NumericType = double> std::array<NumericType, 9> PhQ::Dyad< NumericType >::xx_xy_xz_yx_yy_yz_zx_zy_zz_ private
Cartesian components of this three-dimensional dyadic tensor.
Definition at line 476 of file Dyad.hpp.
Referenced by PhQ::Dyad< NumericType >::Mutable_xx(), PhQ::Dyad< NumericType >::Mutable_xx_xy_xz_yx_yy_yz_zx_zy_zz(), PhQ::Dyad< NumericType >::Mutable_xz(), PhQ::Dyad< NumericType >::Mutable_yx(), PhQ::Dyad< NumericType >::Mutable_yy(), PhQ::Dyad< NumericType >::Mutable_yz(), PhQ::Dyad< NumericType >::Mutable_zx(), PhQ::Dyad< NumericType >::Mutable_zy(), PhQ::Dyad< NumericType >::Mutable_zz(), PhQ::Dyad< NumericType >::operator*=(), PhQ::Dyad< NumericType >::operator+=(), PhQ::Dyad< NumericType >::operator-=(), PhQ::Dyad< NumericType >::operator/=(), PhQ::Dyad< NumericType >::operator=(), PhQ::Dyad< NumericType >::operator=(), PhQ::Dyad< NumericType >::operator=(), PhQ::Dyad< NumericType >::Set_xx(), PhQ::Dyad< NumericType >::Set_xx_xy_xz_yx_yy_yz_zx_zy_zz(), PhQ::Dyad< NumericType >::Set_xx_xy_xz_yx_yy_yz_zx_zy_zz(), PhQ::Dyad< NumericType >::Set_xy(), PhQ::Dyad< NumericType >::Set_xz(), PhQ::Dyad< NumericType >::Set_yx(), PhQ::Dyad< NumericType >::Set_yy(), PhQ::Dyad< NumericType >::Set_yz(), PhQ::Dyad< NumericType >::Set_zx(), PhQ::Dyad< NumericType >::Set_zy(), PhQ::Dyad< NumericType >::Set_zz(), PhQ::Dyad< NumericType >::xx(), PhQ::Dyad< NumericType >::xx_xy_xz_yx_yy_yz_zx_zy_zz(), PhQ::Dyad< NumericType >::xy(), PhQ::Dyad< NumericType >::xz(), PhQ::Dyad< NumericType >::yx(), PhQ::Dyad< NumericType >::yy(), PhQ::Dyad< NumericType >::yz(), PhQ::Dyad< NumericType >::zx(), PhQ::Dyad< NumericType >::zy(), and PhQ::Dyad< NumericType >::zz().
The documentation for this class was generated from the following file:
PhQ/Dyad.hpp