Physical Quantities: PhQ::Stress< NumericType > Class Template Reference
PhQ::Stress< NumericType > Class Template Reference
Three-dimensional Euclidean Cauchy stress symmetric dyadic tensor. Contains six components in Cartesian coordinates: xx, xy = yx, xz = zx, yy, yz = zy, and zz. For the scalar components or resultants of a Cauchy stress tensor, see PhQ::ScalarStress.
#include "Stress.hpp"
Public Member Functions
Stress ()=default
Default constructor. Constructs a stress tensor with an uninitialized value.
Stress (const SymmetricDyad< NumericType > &value, const Unit::Pressure unit)
Constructor. Constructs a stress tensor with a given value expressed in a given pressure unit.
Stress (const ScalarStress< NumericType > &xx, const ScalarStress< NumericType > &xy, const ScalarStress< NumericType > &xz, const ScalarStress< NumericType > &yy, const ScalarStress< NumericType > &yz, const ScalarStress< NumericType > &zz)
Constructor. Constructs a stress tensor from a given set of scalar stress components.
constexpr Stress (const StaticPressure< NumericType > &static_pressure)
Constructor. Constructs a stress tensor from a given static pressure using the definition of stress due to pressure. Since pressure is compressive, the negative of the static pressure contributes to the stress.
~Stress () noexcept=default
Destructor. Destroys this stress tensor.
constexpr Stress (const Stress< NumericType > &other)=default
Copy constructor. Constructs a stress tensor by copying another one.
template<typename OtherNumericType >
constexpr Stress (const Stress< OtherNumericType > &other)
Copy constructor. Constructs a stress tensor by copying another one.
constexpr Stress (Stress< NumericType > &&other) noexcept=default
Move constructor. Constructs a stress tensor by moving another one.
constexpr Stress< NumericType > & operator= (const Stress< NumericType > &other)=default
Copy assignment operator. Assigns this stress tensor by copying another one.
template<typename OtherNumericType >
constexpr Stress< NumericType > & operator= (const Stress< OtherNumericType > &other)
Copy assignment operator. Assigns this stress tensor by copying another one.
constexpr Stress< NumericType > & operator= (Stress< NumericType > &&other) noexcept=default
Move assignment operator. Assigns this stress tensor by moving another one.
constexpr ScalarStress< NumericType > xx () const noexcept
Returns the xx Cartesian component of this stress tensor.
constexpr ScalarStress< NumericType > xy () const noexcept
Returns the xy = yx Cartesian component of this stress tensor.
constexpr ScalarStress< NumericType > xz () const noexcept
Returns the xz = zx Cartesian component of this stress tensor.
constexpr ScalarStress< NumericType > yx () const noexcept
Returns the yx = xy Cartesian component of this stress tensor.
constexpr ScalarStress< NumericType > yy () const noexcept
Returns the yy Cartesian component of this stress tensor.
constexpr ScalarStress< NumericType > yz () const noexcept
Returns the yz = zy Cartesian component of this stress tensor.
constexpr ScalarStress< NumericType > zx () const noexcept
Returns the zx = xz Cartesian component of this stress tensor.
constexpr ScalarStress< NumericType > zy () const noexcept
Returns the zy = yz Cartesian component of this stress tensor.
constexpr ScalarStress< NumericType > zz () const noexcept
Returns the zz Cartesian component of this stress tensor.
constexpr PhQ::PlanarTraction< NumericType > PlanarTraction (const PlanarDirection< NumericType > &direction) const
Creates a planar traction vector from this stress tensor and a given planar direction using the definition of traction.
constexpr PhQ::Traction< NumericType > Traction (const Direction< NumericType > &direction) const
Creates a traction vector from this stress tensor and a given direction using the definition of traction.
constexpr ScalarStress< NumericType > VonMises () const
Computes the von Mises stress of this stress tensor using the von Mises yield criterion.
constexpr Stress< NumericType > operator+ (const Stress< NumericType > &stress) const
constexpr Stress< NumericType > operator- (const Stress< NumericType > &stress) const
constexpr Stress< NumericType > operator* (const NumericType number) const
constexpr Stress< NumericType > operator/ (const NumericType number) const
constexpr void operator+= (const Stress< NumericType > &stress) noexcept
constexpr void operator-= (const Stress< NumericType > &stress) noexcept
constexpr void operator*= (const NumericType number) noexcept
constexpr void operator/= (const NumericType number) noexcept
constexpr const PhQ::SymmetricDyad< NumericType > & Value () const noexcept
Value of this physical quantity expressed in its standard unit of measure.
PhQ::SymmetricDyad< NumericType > Value (const UnitType unit) const
Value of this physical quantity expressed in a given unit of measure.
template<UnitType NewUnit>
constexpr PhQ::SymmetricDyad< NumericType > StaticValue () const
Value of this physical quantity expressed in a given unit of measure. This method can be evaluated statically at compile-time.
constexpr PhQ::SymmetricDyad< NumericType > & MutableValue () noexcept
Returns the value of this physical quantity expressed in its standard unit of measure as a mutable value.
constexpr void SetValue (const PhQ::SymmetricDyad< NumericType > &value) noexcept
Sets the value of this physical quantity expressed in its standard unit of measure to the given value.
std::string Print () const
Prints this physical quantity as a string. This physical quantity's value is expressed in its standard unit of measure.
std::string Print (const UnitType unit) const
Prints this physical quantity as a string. This physical quantity's value is expressed in the given unit of measure.
std::string JSON () const
Serializes this physical quantity as a JSON message. This physical quantity's value is expressed in its standard unit of measure.
std::string JSON (const UnitType unit) const
Serializes this physical quantity as a JSON message. This physical quantity's value is expressed in the given unit of measure.
std::string XML () const
Serializes this physical quantity as an XML message. This physical quantity's value is expressed in its standard unit of measure.
std::string XML (const UnitType unit) const
Serializes this physical quantity as an XML message. This physical quantity's value is expressed in the given unit of measure.
std::string YAML () const
Serializes this physical quantity as a YAML message. This physical quantity's value is expressed in its standard unit of measure.
std::string YAML (const UnitType unit) const
Serializes this physical quantity as a YAML message. This physical quantity's value is expressed in the given unit of measure.
Static Public Member Functions
static constexpr Stress< NumericType > Zero ()
Statically creates a stress tensor of zero.
template<Unit::Pressure Unit>
static constexpr Stress< NumericType > Create (const NumericType xx, const NumericType xy, const NumericType xz, const NumericType yy, const NumericType yz, const NumericType zz)
Statically creates a stress tensor from the given xx, xy, xz, yy, yz, and zz Cartesian components expressed in a given pressure unit.
template<Unit::Pressure Unit>
static constexpr Stress< NumericType > Create (const std::array< NumericType, 6 > &xx_xy_xz_yy_yz_zz)
Statically creates a stress tensor from the given xx, xy, xz, yy, yz, and zz Cartesian components expressed in a given pressure unit.
template<Unit::Pressure Unit>
static constexpr Stress< NumericType > Create (const SymmetricDyad< NumericType > &value)
Statically creates a stress tensor with a given value expressed in a given pressure unit.
static constexpr const PhQ::Dimensions & Dimensions ()
Physical dimension set of this physical quantity.
static constexpr UnitType Unit ()
Standard unit of measure for this physical quantity. This physical quantity's value is stored internally in this unit of measure.
Protected Attributes
PhQ::SymmetricDyad< NumericType > value
Value of this physical quantity expressed in its standard unit of measure.
Private Member Functions
constexpr Stress (const SymmetricDyad< NumericType > &value)
Constructor. Constructs a stress tensor with a given value expressed in the standard pressure unit.
Detailed Description
template<typename NumericType = double>
class PhQ::Stress< NumericType >
Three-dimensional Euclidean Cauchy stress symmetric dyadic tensor. Contains six components in Cartesian coordinates: xx, xy = yx, xz = zx, yy, yz = zy, and zz. For the scalar components or resultants of a Cauchy stress tensor, see PhQ::ScalarStress.
Definition at line 50 of file Stress.hpp.
Constructor & Destructor Documentation
Stress() [1/8]
template<typename NumericType = double> PhQ::Stress< NumericType >::Stress () default
Default constructor. Constructs a stress tensor with an uninitialized value.
Stress() [2/8]
template<typename NumericType = double> PhQ::Stress< NumericType >::Stress (const SymmetricDyad< NumericType > & value, const Unit::Pressure unit) inline
Constructor. Constructs a stress tensor with a given value expressed in a given pressure unit.
Definition at line 57 of file Stress.hpp.
Stress() [3/8]
template<typename NumericType = double> PhQ::Stress< NumericType >::Stress (const ScalarStress< NumericType > & xx, const ScalarStress< NumericType > & xy, const ScalarStress< NumericType > & xz, const ScalarStress< NumericType > & yy, const ScalarStress< NumericType > & yz, const ScalarStress< NumericType > & zz) inline
Constructor. Constructs a stress tensor from a given set of scalar stress components.
Definition at line 61 of file Stress.hpp.
References PhQ::Stress< NumericType >::xx(), PhQ::Stress< NumericType >::xy(), PhQ::Stress< NumericType >::xz(), PhQ::Stress< NumericType >::yy(), PhQ::Stress< NumericType >::yz(), and PhQ::Stress< NumericType >::zz().
Stress() [4/8]
template<typename NumericType = double> constexpr PhQ::Stress< NumericType >::Stress (const StaticPressure< NumericType > & static_pressure) inline explicit constexpr
Constructor. Constructs a stress tensor from a given static pressure using the definition of stress due to pressure. Since pressure is compressive, the negative of the static pressure contributes to the stress.
Definition at line 70 of file Stress.hpp.
References PhQ::DimensionalScalar< UnitType, NumericType >::Value().
~Stress()
template<typename NumericType = double> PhQ::Stress< NumericType >::~Stress () default noexcept
Destructor. Destroys this stress tensor.
Stress() [5/8]
template<typename NumericType = double> constexpr PhQ::Stress< NumericType >::Stress (const Stress< NumericType > & other) constexpr default
Copy constructor. Constructs a stress tensor by copying another one.
Stress() [6/8]
template<typename NumericType = double> template<typename OtherNumericType > constexpr PhQ::Stress< NumericType >::Stress (const Stress< OtherNumericType > & other) inline explicit constexpr
Copy constructor. Constructs a stress tensor by copying another one.
Definition at line 85 of file Stress.hpp.
Stress() [7/8]
template<typename NumericType = double> constexpr PhQ::Stress< NumericType >::Stress (Stress< NumericType > && other) constexpr default noexcept
Move constructor. Constructs a stress tensor by moving another one.
Stress() [8/8]
template<typename NumericType = double> constexpr PhQ::Stress< NumericType >::Stress (const SymmetricDyad< NumericType > & value) inline explicit constexpr private
Constructor. Constructs a stress tensor with a given value expressed in the standard pressure unit.
Definition at line 244 of file Stress.hpp.
Member Function Documentation
Create() [1/3]
template<typename NumericType = double> template<Unit::Pressure Unit> static constexpr Stress< NumericType > PhQ::Stress< NumericType >::Create (const NumericType xx, const NumericType xy, const NumericType xz, const NumericType yy, const NumericType yz, const NumericType zz) inline static constexpr
Statically creates a stress tensor from the given xx, xy, xz, yy, yz, and zz Cartesian components expressed in a given pressure unit.
Definition at line 112 of file Stress.hpp.
References PhQ::Stress< NumericType >::xx(), PhQ::Stress< NumericType >::xy(), PhQ::Stress< NumericType >::xz(), PhQ::Stress< NumericType >::yy(), PhQ::Stress< NumericType >::yz(), and PhQ::Stress< NumericType >::zz().
Create() [2/3]
template<typename NumericType = double> template<Unit::Pressure Unit> static constexpr Stress< NumericType > PhQ::Stress< NumericType >::Create (const std::array< NumericType, 6 > & xx_xy_xz_yy_yz_zz) inline static constexpr
Statically creates a stress tensor from the given xx, xy, xz, yy, yz, and zz Cartesian components expressed in a given pressure unit.
Definition at line 122 of file Stress.hpp.
Create() [3/3]
template<typename NumericType = double> template<Unit::Pressure Unit> static constexpr Stress< NumericType > PhQ::Stress< NumericType >::Create (const SymmetricDyad< NumericType > & value) inline static constexpr
Statically creates a stress tensor with a given value expressed in a given pressure unit.
Definition at line 131 of file Stress.hpp.
References PhQ::DimensionalSymmetricDyad< UnitType, NumericType >::value.
Dimensions()
template<typename UnitType , typename NumericType = double> static constexpr const PhQ::Dimensions & PhQ::DimensionalSymmetricDyad< UnitType, NumericType >::Dimensions () inline static constexpr inherited
Physical dimension set of this physical quantity.
Definition at line 50 of file DimensionalSymmetricDyad.hpp.
JSON() [1/2]
template<typename UnitType , typename NumericType = double> std::string PhQ::DimensionalSymmetricDyad< UnitType, NumericType >::JSON () const inline inherited
Serializes this physical quantity as a JSON message. This physical quantity's value is expressed in its standard unit of measure.
Definition at line 103 of file DimensionalSymmetricDyad.hpp.
References PhQ::Abbreviation(), and PhQ::DimensionalSymmetricDyad< UnitType, NumericType >::value.
Referenced by PhQ::DimensionalSymmetricDyad< UnitType, NumericType >::JSON().
JSON() [2/2]
template<typename UnitType , typename NumericType = double> std::string PhQ::DimensionalSymmetricDyad< UnitType, NumericType >::JSON (const UnitType unit) const inline inherited
Serializes this physical quantity as a JSON message. This physical quantity's value is expressed in the given unit of measure.
Definition at line 113 of file DimensionalSymmetricDyad.hpp.
References PhQ::Abbreviation(), PhQ::DimensionalSymmetricDyad< UnitType, NumericType >::JSON(), and PhQ::DimensionalSymmetricDyad< UnitType, NumericType >::Value().
MutableValue()
template<typename UnitType , typename NumericType = double> constexpr PhQ::SymmetricDyad< NumericType > & PhQ::DimensionalSymmetricDyad< UnitType, NumericType >::MutableValue () inline constexpr noexcept inherited
Returns the value of this physical quantity expressed in its standard unit of measure as a mutable value.
Definition at line 79 of file DimensionalSymmetricDyad.hpp.
References PhQ::DimensionalSymmetricDyad< UnitType, NumericType >::value.
operator*()
template<typename NumericType = double> constexpr Stress< NumericType > PhQ::Stress< NumericType >::operator* (const NumericType number) const inline constexpr
Definition at line 217 of file Stress.hpp.
References PhQ::DimensionalSymmetricDyad< UnitType, NumericType >::value.
operator*=()
template<typename NumericType = double> constexpr void PhQ::Stress< NumericType >::operator*= (const NumericType number) inline constexpr noexcept
Definition at line 233 of file Stress.hpp.
References PhQ::DimensionalSymmetricDyad< UnitType, NumericType >::value.
operator+()
template<typename NumericType = double> constexpr Stress< NumericType > PhQ::Stress< NumericType >::operator+ (const Stress< NumericType > & stress) const inline constexpr
Definition at line 209 of file Stress.hpp.
References PhQ::DimensionalSymmetricDyad< UnitType, NumericType >::value.
operator+=()
template<typename NumericType = double> constexpr void PhQ::Stress< NumericType >::operator+= (const Stress< NumericType > & stress) inline constexpr noexcept
Definition at line 225 of file Stress.hpp.
References PhQ::DimensionalSymmetricDyad< UnitType, NumericType >::value.
operator-()
template<typename NumericType = double> constexpr Stress< NumericType > PhQ::Stress< NumericType >::operator- (const Stress< NumericType > & stress) const inline constexpr
Definition at line 213 of file Stress.hpp.
References PhQ::DimensionalSymmetricDyad< UnitType, NumericType >::value.
operator-=()
template<typename NumericType = double> constexpr void PhQ::Stress< NumericType >::operator-= (const Stress< NumericType > & stress) inline constexpr noexcept
Definition at line 229 of file Stress.hpp.
References PhQ::DimensionalSymmetricDyad< UnitType, NumericType >::value.
operator/()
template<typename NumericType = double> constexpr Stress< NumericType > PhQ::Stress< NumericType >::operator/ (const NumericType number) const inline constexpr
Definition at line 221 of file Stress.hpp.
References PhQ::DimensionalSymmetricDyad< UnitType, NumericType >::value.
operator/=()
template<typename NumericType = double> constexpr void PhQ::Stress< NumericType >::operator/= (const NumericType number) inline constexpr noexcept
Definition at line 237 of file Stress.hpp.
References PhQ::DimensionalSymmetricDyad< UnitType, NumericType >::value.
operator=() [1/3]
template<typename NumericType = double> constexpr Stress< NumericType > & PhQ::Stress< NumericType >::operator= (const Stress< NumericType > & other) constexpr default
Copy assignment operator. Assigns this stress tensor by copying another one.
operator=() [2/3]
template<typename NumericType = double> template<typename OtherNumericType > constexpr Stress< NumericType > & PhQ::Stress< NumericType >::operator= (const Stress< OtherNumericType > & other) inline constexpr
Copy assignment operator. Assigns this stress tensor by copying another one.
Definition at line 96 of file Stress.hpp.
References PhQ::DimensionalSymmetricDyad< UnitType, NumericType >::Value(), and PhQ::DimensionalSymmetricDyad< UnitType, NumericType >::value.
operator=() [3/3]
template<typename NumericType = double> constexpr Stress< NumericType > & PhQ::Stress< NumericType >::operator= (Stress< NumericType > && other) constexpr default noexcept
Move assignment operator. Assigns this stress tensor by moving another one.
PlanarTraction()
template<typename NumericType = double> constexpr PhQ::PlanarTraction< NumericType > PhQ::Stress< NumericType >::PlanarTraction (const PlanarDirection< NumericType > & direction) const inline constexpr
Creates a planar traction vector from this stress tensor and a given planar direction using the definition of traction.
Definition at line 184 of file Stress.hpp.
Print() [1/2]
template<typename UnitType , typename NumericType = double> std::string PhQ::DimensionalSymmetricDyad< UnitType, NumericType >::Print () const inline inherited
Prints this physical quantity as a string. This physical quantity's value is expressed in its standard unit of measure.
Definition at line 91 of file DimensionalSymmetricDyad.hpp.
References PhQ::Abbreviation(), and PhQ::DimensionalSymmetricDyad< UnitType, NumericType >::value.
Referenced by PhQ::operator<<(), PhQ::operator<<(), and PhQ::operator<<().
Print() [2/2]
template<typename UnitType , typename NumericType = double> std::string PhQ::DimensionalSymmetricDyad< UnitType, NumericType >::Print (const UnitType unit) const inline inherited
Prints this physical quantity as a string. This physical quantity's value is expressed in the given unit of measure.
Definition at line 97 of file DimensionalSymmetricDyad.hpp.
References PhQ::Abbreviation(), and PhQ::DimensionalSymmetricDyad< UnitType, NumericType >::Value().
SetValue()
template<typename UnitType , typename NumericType = double> constexpr void PhQ::DimensionalSymmetricDyad< UnitType, NumericType >::SetValue (const PhQ::SymmetricDyad< NumericType > & value) inline constexpr noexcept inherited
Sets the value of this physical quantity expressed in its standard unit of measure to the given value.
Definition at line 85 of file DimensionalSymmetricDyad.hpp.
References PhQ::DimensionalSymmetricDyad< UnitType, NumericType >::value.
StaticValue()
template<typename UnitType , typename NumericType = double> template<UnitType NewUnit> constexpr PhQ::SymmetricDyad< NumericType > PhQ::DimensionalSymmetricDyad< UnitType, NumericType >::StaticValue () const inline constexpr inherited
Value of this physical quantity expressed in a given unit of measure. This method can be evaluated statically at compile-time.
Definition at line 73 of file DimensionalSymmetricDyad.hpp.
References PhQ::DimensionalSymmetricDyad< UnitType, NumericType >::value.
Traction()
template<typename NumericType = double> constexpr PhQ::Traction< NumericType > PhQ::Stress< NumericType >::Traction (const Direction< NumericType > & direction) const inline constexpr
Creates a traction vector from this stress tensor and a given direction using the definition of traction.
Definition at line 191 of file Stress.hpp.
Unit()
template<typename UnitType , typename NumericType = double> static constexpr UnitType PhQ::DimensionalSymmetricDyad< UnitType, NumericType >::Unit () inline static constexpr inherited
Standard unit of measure for this physical quantity. This physical quantity's value is stored internally in this unit of measure.
Definition at line 56 of file DimensionalSymmetricDyad.hpp.
Value() [1/2]
template<typename UnitType , typename NumericType = double> constexpr const PhQ::SymmetricDyad< NumericType > & PhQ::DimensionalSymmetricDyad< UnitType, NumericType >::Value () const inline constexpr noexcept inherited
Value of this physical quantity expressed in its standard unit of measure.
Definition at line 61 of file DimensionalSymmetricDyad.hpp.
References PhQ::DimensionalSymmetricDyad< UnitType, NumericType >::value.
Referenced by PhQ::DimensionalSymmetricDyad< UnitType, NumericType >::JSON(), PhQ::DimensionalSymmetricDyad< UnitType, NumericType >::operator=(), PhQ::StrainRate< NumericType >::operator=(), PhQ::Stress< NumericType >::operator=(), PhQ::ThermalConductivity< NumericType >::operator=(), PhQ::operator==(), PhQ::operator==(), PhQ::operator==(), PhQ::operator==(), PhQ::PlanarHeatFlux< NumericType >::PlanarHeatFlux(), PhQ::PlanarTraction< NumericType >::PlanarTraction(), PhQ::DimensionalSymmetricDyad< UnitType, NumericType >::Print(), PhQ::ConstitutiveModel::ElasticIsotropicSolid< NumericType >::Strain(), PhQ::ConstitutiveModel::ElasticIsotropicSolid< NumericType >::Strain(), PhQ::ConstitutiveModel::ElasticIsotropicSolid< NumericType >::Strain(), PhQ::ConstitutiveModel::CompressibleNewtonianFluid< NumericType >::StrainRate(), PhQ::ConstitutiveModel::IncompressibleNewtonianFluid< NumericType >::StrainRate(), PhQ::ConstitutiveModel::CompressibleNewtonianFluid< NumericType >::StrainRate(), PhQ::ConstitutiveModel::IncompressibleNewtonianFluid< NumericType >::StrainRate(), PhQ::ConstitutiveModel::CompressibleNewtonianFluid< NumericType >::StrainRate(), PhQ::ConstitutiveModel::IncompressibleNewtonianFluid< NumericType >::StrainRate(), PhQ::ConstitutiveModel::CompressibleNewtonianFluid< NumericType >::Stress(), PhQ::ConstitutiveModel::IncompressibleNewtonianFluid< NumericType >::Stress(), PhQ::ConstitutiveModel::CompressibleNewtonianFluid< NumericType >::Stress(), PhQ::ConstitutiveModel::IncompressibleNewtonianFluid< NumericType >::Stress(), PhQ::ConstitutiveModel::CompressibleNewtonianFluid< NumericType >::Stress(), PhQ::ConstitutiveModel::IncompressibleNewtonianFluid< NumericType >::Stress(), PhQ::Traction< NumericType >::Traction(), PhQ::DimensionalSymmetricDyad< UnitType, NumericType >::XML(), and PhQ::DimensionalSymmetricDyad< UnitType, NumericType >::YAML().
Value() [2/2]
template<typename UnitType , typename NumericType = double> PhQ::SymmetricDyad< NumericType > PhQ::DimensionalSymmetricDyad< UnitType, NumericType >::Value (const UnitType unit) const inline inherited
Value of this physical quantity expressed in a given unit of measure.
Definition at line 66 of file DimensionalSymmetricDyad.hpp.
References PhQ::Convert(), and PhQ::DimensionalSymmetricDyad< UnitType, NumericType >::value.
VonMises()
template<typename NumericType = double> constexpr ScalarStress< NumericType > PhQ::Stress< NumericType >::VonMises () const inline constexpr
Computes the von Mises stress of this stress tensor using the von Mises yield criterion.
Definition at line 198 of file Stress.hpp.
References PhQ::DimensionalSymmetricDyad< UnitType, NumericType >::value.
XML() [1/2]
template<typename UnitType , typename NumericType = double> std::string PhQ::DimensionalSymmetricDyad< UnitType, NumericType >::XML () const inline inherited
Serializes this physical quantity as an XML message. This physical quantity's value is expressed in its standard unit of measure.
Definition at line 123 of file DimensionalSymmetricDyad.hpp.
References PhQ::Abbreviation(), and PhQ::DimensionalSymmetricDyad< UnitType, NumericType >::value.
Referenced by PhQ::DimensionalSymmetricDyad< UnitType, NumericType >::XML().
XML() [2/2]
template<typename UnitType , typename NumericType = double> std::string PhQ::DimensionalSymmetricDyad< UnitType, NumericType >::XML (const UnitType unit) const inline inherited
Serializes this physical quantity as an XML message. This physical quantity's value is expressed in the given unit of measure.
Definition at line 133 of file DimensionalSymmetricDyad.hpp.
References PhQ::Abbreviation(), PhQ::DimensionalSymmetricDyad< UnitType, NumericType >::Value(), and PhQ::DimensionalSymmetricDyad< UnitType, NumericType >::XML().
xx()
template<typename NumericType = double> constexpr ScalarStress< NumericType > PhQ::Stress< NumericType >::xx () const inline constexpr noexcept
Returns the xx Cartesian component of this stress tensor.
Definition at line 138 of file Stress.hpp.
References PhQ::DimensionalSymmetricDyad< UnitType, NumericType >::value.
Referenced by PhQ::Stress< NumericType >::Create(), and PhQ::Stress< NumericType >::Stress().
xy()
template<typename NumericType = double> constexpr ScalarStress< NumericType > PhQ::Stress< NumericType >::xy () const inline constexpr noexcept
Returns the xy = yx Cartesian component of this stress tensor.
Definition at line 143 of file Stress.hpp.
References PhQ::DimensionalSymmetricDyad< UnitType, NumericType >::value.
Referenced by PhQ::Stress< NumericType >::Create(), and PhQ::Stress< NumericType >::Stress().
xz()
template<typename NumericType = double> constexpr ScalarStress< NumericType > PhQ::Stress< NumericType >::xz () const inline constexpr noexcept
Returns the xz = zx Cartesian component of this stress tensor.
Definition at line 148 of file Stress.hpp.
References PhQ::DimensionalSymmetricDyad< UnitType, NumericType >::value.
Referenced by PhQ::Stress< NumericType >::Create(), and PhQ::Stress< NumericType >::Stress().
YAML() [1/2]
template<typename UnitType , typename NumericType = double> std::string PhQ::DimensionalSymmetricDyad< UnitType, NumericType >::YAML () const inline inherited
Serializes this physical quantity as a YAML message. This physical quantity's value is expressed in its standard unit of measure.
Definition at line 143 of file DimensionalSymmetricDyad.hpp.
References PhQ::Abbreviation(), and PhQ::DimensionalSymmetricDyad< UnitType, NumericType >::value.
Referenced by PhQ::DimensionalSymmetricDyad< UnitType, NumericType >::YAML().
YAML() [2/2]
template<typename UnitType , typename NumericType = double> std::string PhQ::DimensionalSymmetricDyad< UnitType, NumericType >::YAML (const UnitType unit) const inline inherited
Serializes this physical quantity as a YAML message. This physical quantity's value is expressed in the given unit of measure.
Definition at line 153 of file DimensionalSymmetricDyad.hpp.
References PhQ::Abbreviation(), PhQ::DimensionalSymmetricDyad< UnitType, NumericType >::Value(), and PhQ::DimensionalSymmetricDyad< UnitType, NumericType >::YAML().
yx()
template<typename NumericType = double> constexpr ScalarStress< NumericType > PhQ::Stress< NumericType >::yx () const inline constexpr noexcept
Returns the yx = xy Cartesian component of this stress tensor.
Definition at line 153 of file Stress.hpp.
References PhQ::DimensionalSymmetricDyad< UnitType, NumericType >::value.
yy()
template<typename NumericType = double> constexpr ScalarStress< NumericType > PhQ::Stress< NumericType >::yy () const inline constexpr noexcept
Returns the yy Cartesian component of this stress tensor.
Definition at line 158 of file Stress.hpp.
References PhQ::DimensionalSymmetricDyad< UnitType, NumericType >::value.
Referenced by PhQ::Stress< NumericType >::Create(), and PhQ::Stress< NumericType >::Stress().
yz()
template<typename NumericType = double> constexpr ScalarStress< NumericType > PhQ::Stress< NumericType >::yz () const inline constexpr noexcept
Returns the yz = zy Cartesian component of this stress tensor.
Definition at line 163 of file Stress.hpp.
References PhQ::DimensionalSymmetricDyad< UnitType, NumericType >::value.
Referenced by PhQ::Stress< NumericType >::Create(), and PhQ::Stress< NumericType >::Stress().
Zero()
template<typename NumericType = double> static constexpr Stress< NumericType > PhQ::Stress< NumericType >::Zero () inline static constexpr
Statically creates a stress tensor of zero.
Definition at line 105 of file Stress.hpp.
References PhQ::SymmetricDyad< NumericType >::Zero().
Referenced by PhQ::ConstitutiveModel::CompressibleNewtonianFluid< NumericType >::Stress(), PhQ::ConstitutiveModel::IncompressibleNewtonianFluid< NumericType >::Stress(), PhQ::ConstitutiveModel::CompressibleNewtonianFluid< NumericType >::Stress(), PhQ::ConstitutiveModel::IncompressibleNewtonianFluid< NumericType >::Stress(), PhQ::ConstitutiveModel::CompressibleNewtonianFluid< NumericType >::Stress(), PhQ::ConstitutiveModel::IncompressibleNewtonianFluid< NumericType >::Stress(), PhQ::ConstitutiveModel::ElasticIsotropicSolid< NumericType >::Stress(), PhQ::ConstitutiveModel::ElasticIsotropicSolid< NumericType >::Stress(), and PhQ::ConstitutiveModel::ElasticIsotropicSolid< NumericType >::Stress().
zx()
template<typename NumericType = double> constexpr ScalarStress< NumericType > PhQ::Stress< NumericType >::zx () const inline constexpr noexcept
Returns the zx = xz Cartesian component of this stress tensor.
Definition at line 168 of file Stress.hpp.
References PhQ::DimensionalSymmetricDyad< UnitType, NumericType >::value.
zy()
template<typename NumericType = double> constexpr ScalarStress< NumericType > PhQ::Stress< NumericType >::zy () const inline constexpr noexcept
Returns the zy = yz Cartesian component of this stress tensor.
Definition at line 173 of file Stress.hpp.
References PhQ::DimensionalSymmetricDyad< UnitType, NumericType >::value.
zz()
template<typename NumericType = double> constexpr ScalarStress< NumericType > PhQ::Stress< NumericType >::zz () const inline constexpr noexcept
Returns the zz Cartesian component of this stress tensor.
Definition at line 178 of file Stress.hpp.
References PhQ::DimensionalSymmetricDyad< UnitType, NumericType >::value.
Referenced by PhQ::Stress< NumericType >::Create(), and PhQ::Stress< NumericType >::Stress().
Member Data Documentation
value
template<typename UnitType , typename NumericType = double> PhQ::SymmetricDyad<NumericType> PhQ::DimensionalSymmetricDyad< UnitType, NumericType >::value protected inherited
Value of this physical quantity expressed in its standard unit of measure.
Definition at line 222 of file DimensionalSymmetricDyad.hpp.
Referenced by PhQ::StrainRate< NumericType >::Create(), PhQ::Stress< NumericType >::Create(), PhQ::ThermalConductivity< NumericType >::Create(), PhQ::DimensionalSymmetricDyad< UnitType, NumericType >::JSON(), PhQ::DimensionalSymmetricDyad< UnitType, NumericType >::MutableValue(), PhQ::StrainRate< NumericType >::operator*(), PhQ::Stress< NumericType >::operator*(), PhQ::ThermalConductivity< NumericType >::operator*(), PhQ::StrainRate< NumericType >::operator*=(), PhQ::Stress< NumericType >::operator*=(), PhQ::ThermalConductivity< NumericType >::operator*=(), PhQ::StrainRate< NumericType >::operator+(), PhQ::Stress< NumericType >::operator+(), PhQ::ThermalConductivity< NumericType >::operator+(), PhQ::StrainRate< NumericType >::operator+=(), PhQ::Stress< NumericType >::operator+=(), PhQ::ThermalConductivity< NumericType >::operator+=(), PhQ::StrainRate< NumericType >::operator-(), PhQ::Stress< NumericType >::operator-(), PhQ::ThermalConductivity< NumericType >::operator-(), PhQ::StrainRate< NumericType >::operator-=(), PhQ::Stress< NumericType >::operator-=(), PhQ::ThermalConductivity< NumericType >::operator-=(), PhQ::StrainRate< NumericType >::operator/(), PhQ::Stress< NumericType >::operator/(), PhQ::ThermalConductivity< NumericType >::operator/(), PhQ::StrainRate< NumericType >::operator/=(), PhQ::Stress< NumericType >::operator/=(), PhQ::ThermalConductivity< NumericType >::operator/=(), PhQ::DimensionalSymmetricDyad< UnitType, NumericType >::operator=(), PhQ::StrainRate< NumericType >::operator=(), PhQ::Stress< NumericType >::operator=(), PhQ::ThermalConductivity< NumericType >::operator=(), PhQ::DimensionalSymmetricDyad< UnitType, NumericType >::Print(), PhQ::DimensionalSymmetricDyad< UnitType, NumericType >::SetValue(), PhQ::DimensionalSymmetricDyad< UnitType, NumericType >::StaticValue(), PhQ::DimensionalSymmetricDyad< UnitType, NumericType >::Value(), PhQ::DimensionalSymmetricDyad< UnitType, NumericType >::Value(), PhQ::Stress< NumericType >::VonMises(), PhQ::DimensionalSymmetricDyad< UnitType, NumericType >::XML(), PhQ::StrainRate< NumericType >::xx(), PhQ::Stress< NumericType >::xx(), PhQ::ThermalConductivity< NumericType >::xx(), PhQ::StrainRate< NumericType >::xy(), PhQ::Stress< NumericType >::xy(), PhQ::ThermalConductivity< NumericType >::xy(), PhQ::StrainRate< NumericType >::xz(), PhQ::Stress< NumericType >::xz(), PhQ::ThermalConductivity< NumericType >::xz(), PhQ::DimensionalSymmetricDyad< UnitType, NumericType >::YAML(), PhQ::StrainRate< NumericType >::yx(), PhQ::Stress< NumericType >::yx(), PhQ::ThermalConductivity< NumericType >::yx(), PhQ::StrainRate< NumericType >::yy(), PhQ::Stress< NumericType >::yy(), PhQ::ThermalConductivity< NumericType >::yy(), PhQ::StrainRate< NumericType >::yz(), PhQ::Stress< NumericType >::yz(), PhQ::ThermalConductivity< NumericType >::yz(), PhQ::StrainRate< NumericType >::zx(), PhQ::Stress< NumericType >::zx(), PhQ::ThermalConductivity< NumericType >::zx(), PhQ::StrainRate< NumericType >::zy(), PhQ::Stress< NumericType >::zy(), PhQ::ThermalConductivity< NumericType >::zy(), PhQ::StrainRate< NumericType >::zz(), PhQ::Stress< NumericType >::zz(), and PhQ::ThermalConductivity< NumericType >::zz().
The documentation for this class was generated from the following files:
PhQ/PlanarTraction.hpp
PhQ/Stress.hpp