Physical Quantities: PhQ::DimensionlessPlanarVector< NumericType > Class Template Reference
PhQ::DimensionlessPlanarVector< NumericType > Class Template Reference
Abstract base class that represents any dimensionless planar vector physical quantity. Such a physical quantity is composed only of a value where the value is a two-dimensional planar vector in the XY plane. Such a physical quantity has no unit of measure and no dimension set.
#include "DimensionlessPlanarVector.hpp"
Public Member Functions
constexpr const PhQ::PlanarVector< NumericType > & Value () const noexcept
Value of this physical quantity.
std::string Print () const
Prints this physical quantity as a string.
std::string JSON () const
Serializes this physical quantity as a JSON message.
std::string XML () const
Serializes this physical quantity as an XML message.
std::string YAML () const
Serializes this physical quantity as a YAML message.
Static Public Member Functions
static constexpr PhQ::Dimensions Dimensions ()
Physical dimension set of this physical quantity. Since this physical quantity is dimensionless, its physical dimension set is simply the null set.
Protected Member Functions
DimensionlessPlanarVector ()=default
Default constructor. Constructs a dimensionless planar vector physical quantity with an uninitialized value.
constexpr DimensionlessPlanarVector (const NumericType x, const NumericType y)
Constructor. Constructs a dimensionless planar vector physical quantity whose value has the given x, y, and z Cartesian components.
constexpr DimensionlessPlanarVector (const std::array< NumericType, 2 > &x_y)
Constructor. Constructs a dimensionless planar vector physical quantity from a given array representing its value's x and y Cartesian components.
constexpr DimensionlessPlanarVector (const PhQ::PlanarVector< NumericType > &value)
Constructor. Constructs a dimensionless planar vector physical quantity with a given value.
~DimensionlessPlanarVector () noexcept=default
Destructor. Destroys this dimensionless planar vector physical quantity.
constexpr DimensionlessPlanarVector (const DimensionlessPlanarVector< NumericType > &other)=default
Copy constructor. Constructs a dimensionless planar vector physical quantity by copying another one.
template<typename OtherNumericType >
constexpr DimensionlessPlanarVector (const DimensionlessPlanarVector< OtherNumericType > &other)
Copy constructor. Constructs a dimensionless planar vector physical quantity by copying another one.
constexpr DimensionlessPlanarVector (DimensionlessPlanarVector< NumericType > &&other) noexcept=default
Move constructor. Constructs a dimensionless planar vector physical quantity by moving another one.
constexpr DimensionlessPlanarVector< NumericType > & operator= (const DimensionlessPlanarVector< NumericType > &other)=default
Copy assignment operator. Assigns this dimensionless planar vector physical quantity by copying another one.
template<typename OtherNumericType >
constexpr DimensionlessPlanarVector< NumericType > & operator= (const DimensionlessPlanarVector< OtherNumericType > &other)
Copy assignment operator. Assigns this dimensionless planar vector physical quantity by copying another one.
constexpr DimensionlessPlanarVector< NumericType > & operator= (DimensionlessPlanarVector< NumericType > &&other) noexcept=default
Move assignment operator. Assigns this dimensionless planar vector physical quantity by moving another one.
Protected Attributes
PhQ::PlanarVector< NumericType > value
Value of this physical quantity.
Detailed Description
template<typename NumericType = double>
class PhQ::DimensionlessPlanarVector< NumericType >
Abstract base class that represents any dimensionless planar vector physical quantity. Such a physical quantity is composed only of a value where the value is a two-dimensional planar vector in the XY plane. Such a physical quantity has no unit of measure and no dimension set.
Template Parameters
NumericType Floating-point numeric type: float, double, or long double. Defaults to double if unspecified.
Definition at line 47 of file DimensionlessPlanarVector.hpp.
Constructor & Destructor Documentation
DimensionlessPlanarVector() [1/7]
template<typename NumericType = double> PhQ::DimensionlessPlanarVector< NumericType >::DimensionlessPlanarVector () protected default
Default constructor. Constructs a dimensionless planar vector physical quantity with an uninitialized value.
DimensionlessPlanarVector() [2/7]
template<typename NumericType = double> constexpr PhQ::DimensionlessPlanarVector< NumericType >::DimensionlessPlanarVector (const NumericType x, const NumericType y) inline constexpr protected
Constructor. Constructs a dimensionless planar vector physical quantity whose value has the given x, y, and z Cartesian components.
Definition at line 91 of file DimensionlessPlanarVector.hpp.
DimensionlessPlanarVector() [3/7]
template<typename NumericType = double> constexpr PhQ::DimensionlessPlanarVector< NumericType >::DimensionlessPlanarVector (const std::array< NumericType, 2 > & x_y) inline explicit constexpr protected
Constructor. Constructs a dimensionless planar vector physical quantity from a given array representing its value's x and y Cartesian components.
Definition at line 95 of file DimensionlessPlanarVector.hpp.
DimensionlessPlanarVector() [4/7]
template<typename NumericType = double> constexpr PhQ::DimensionlessPlanarVector< NumericType >::DimensionlessPlanarVector (const PhQ::PlanarVector< NumericType > & value) inline explicit constexpr protected
Constructor. Constructs a dimensionless planar vector physical quantity with a given value.
Definition at line 100 of file DimensionlessPlanarVector.hpp.
~DimensionlessPlanarVector()
template<typename NumericType = double> PhQ::DimensionlessPlanarVector< NumericType >::~DimensionlessPlanarVector () protected default noexcept
Destructor. Destroys this dimensionless planar vector physical quantity.
DimensionlessPlanarVector() [5/7]
template<typename NumericType = double> constexpr PhQ::DimensionlessPlanarVector< NumericType >::DimensionlessPlanarVector (const DimensionlessPlanarVector< NumericType > & other) constexpr protected default
Copy constructor. Constructs a dimensionless planar vector physical quantity by copying another one.
DimensionlessPlanarVector() [6/7]
template<typename NumericType = double> template<typename OtherNumericType > constexpr PhQ::DimensionlessPlanarVector< NumericType >::DimensionlessPlanarVector (const DimensionlessPlanarVector< OtherNumericType > & other) inline explicit constexpr protected
Copy constructor. Constructs a dimensionless planar vector physical quantity by copying another one.
Template Parameters
OtherNumericType Floating-point numeric type of the other physical quantity. Deduced automatically.
Definition at line 116 of file DimensionlessPlanarVector.hpp.
DimensionlessPlanarVector() [7/7]
template<typename NumericType = double> constexpr PhQ::DimensionlessPlanarVector< NumericType >::DimensionlessPlanarVector (DimensionlessPlanarVector< NumericType > && other) constexpr protected default noexcept
Move constructor. Constructs a dimensionless planar vector physical quantity by moving another one.
Member Function Documentation
Dimensions()
template<typename NumericType = double> static constexpr PhQ::Dimensions PhQ::DimensionlessPlanarVector< NumericType >::Dimensions () inline static constexpr
Physical dimension set of this physical quantity. Since this physical quantity is dimensionless, its physical dimension set is simply the null set.
Definition at line 55 of file DimensionlessPlanarVector.hpp.
References PhQ::Dimensionless.
JSON()
template<typename NumericType = double> std::string PhQ::DimensionlessPlanarVector< NumericType >::JSON () const inline
Serializes this physical quantity as a JSON message.
Definition at line 70 of file DimensionlessPlanarVector.hpp.
References PhQ::DimensionlessPlanarVector< NumericType >::value.
operator=() [1/3]
template<typename NumericType = double> constexpr DimensionlessPlanarVector<NumericType>& PhQ::DimensionlessPlanarVector< NumericType >::operator= (const DimensionlessPlanarVector< NumericType > & other) constexpr protected default
Copy assignment operator. Assigns this dimensionless planar vector physical quantity by copying another one.
operator=() [2/3]
template<typename NumericType = double> template<typename OtherNumericType > constexpr DimensionlessPlanarVector<NumericType>& PhQ::DimensionlessPlanarVector< NumericType >::operator= (const DimensionlessPlanarVector< OtherNumericType > & other) inline constexpr protected
Copy assignment operator. Assigns this dimensionless planar vector physical quantity by copying another one.
Template Parameters
OtherNumericType Floating-point numeric type of the other physical quantity. Deduced automatically.
Definition at line 135 of file DimensionlessPlanarVector.hpp.
References PhQ::DimensionlessPlanarVector< NumericType >::Value(), and PhQ::DimensionlessPlanarVector< NumericType >::value.
operator=() [3/3]
template<typename NumericType = double> constexpr DimensionlessPlanarVector<NumericType>& PhQ::DimensionlessPlanarVector< NumericType >::operator= (DimensionlessPlanarVector< NumericType > && other) constexpr protected default noexcept
Move assignment operator. Assigns this dimensionless planar vector physical quantity by moving another one.
Print()
template<typename NumericType = double> std::string PhQ::DimensionlessPlanarVector< NumericType >::Print () const inline
Prints this physical quantity as a string.
Definition at line 65 of file DimensionlessPlanarVector.hpp.
References PhQ::DimensionlessPlanarVector< NumericType >::value.
Referenced by PhQ::operator<<().
Value()
template<typename NumericType = double> constexpr const PhQ::PlanarVector<NumericType>& PhQ::DimensionlessPlanarVector< NumericType >::Value () const inline constexpr noexcept
Value of this physical quantity.
Definition at line 60 of file DimensionlessPlanarVector.hpp.
References PhQ::DimensionlessPlanarVector< NumericType >::value.
Referenced by PhQ::PlanarVector< NumericType >::Cross(), PhQ::Direction< NumericType >::Direction(), PhQ::PlanarVector< NumericType >::Dyadic(), PhQ::operator*(), PhQ::DimensionlessPlanarVector< NumericType >::operator=(), PhQ::PlanarDirection< NumericType >::operator=(), and PhQ::PlanarVector< NumericType >::PlanarVector().
XML()
template<typename NumericType = double> std::string PhQ::DimensionlessPlanarVector< NumericType >::XML () const inline
Serializes this physical quantity as an XML message.
Definition at line 75 of file DimensionlessPlanarVector.hpp.
References PhQ::DimensionlessPlanarVector< NumericType >::value.
YAML()
template<typename NumericType = double> std::string PhQ::DimensionlessPlanarVector< NumericType >::YAML () const inline
Serializes this physical quantity as a YAML message.
Definition at line 80 of file DimensionlessPlanarVector.hpp.
References PhQ::DimensionlessPlanarVector< NumericType >::value.
Member Data Documentation
value
template<typename NumericType = double> PhQ::PlanarVector<NumericType> PhQ::DimensionlessPlanarVector< NumericType >::value protected
Value of this physical quantity.
Definition at line 147 of file DimensionlessPlanarVector.hpp.
Referenced by PhQ::PlanarDirection< NumericType >::Cross(), PhQ::PlanarDirection< NumericType >::Dyadic(), PhQ::DimensionlessPlanarVector< NumericType >::JSON(), PhQ::DimensionlessPlanarVector< NumericType >::operator=(), PhQ::DimensionlessPlanarVector< NumericType >::Print(), PhQ::DimensionlessPlanarVector< NumericType >::Value(), PhQ::DimensionlessPlanarVector< NumericType >::XML(), and PhQ::DimensionlessPlanarVector< NumericType >::YAML().
The documentation for this class was generated from the following file:
PhQ/DimensionlessPlanarVector.hpp