Physical Quantities: PhQ::PlanarForce< NumericType > Class Template Reference
PhQ::PlanarForce< NumericType > Class Template Reference
Two-dimensional Euclidean force vector in the XY plane. Contains two components in Cartesian coordinates: x and y. For a three-dimensional Euclidean force vector, see PhQ::Force. For scalar force components or for the magnitude of a force vector, see PhQ::ScalarForce.
#include "PlanarForce.hpp"
Public Member Functions
PlanarForce ()=default
Default constructor. Constructs a planar force vector with an uninitialized value.
PlanarForce (const PlanarVector< NumericType > &value, const Unit::Force unit)
Constructor. Constructs a planar force vector with a given value expressed in a given force unit.
PlanarForce (const ScalarForce< NumericType > &x, const ScalarForce< NumericType > &y)
Constructor. Constructs a planar force vector from a given set of scalar force components.
constexpr PlanarForce (const ScalarForce< NumericType > &scalar_force, const PlanarDirection< NumericType > &planar_direction)
Constructor. Constructs a planar force vector from a given scalar force magnitude and planar direction.
constexpr PlanarForce (const Force< NumericType > &force)
Constructor. Constructs a planar force vector from a given force vector by projecting the force vector onto the XY plane.
constexpr PlanarForce (const PlanarTraction< NumericType > &planar_traction, const Area< NumericType > &area)
Constructor. Constructs a planar force vector from a given planar traction and area using the definition of traction.
~PlanarForce () noexcept=default
Destructor. Destroys this planar force vector.
constexpr PlanarForce (const PlanarForce< NumericType > &other)=default
Copy constructor. Constructs a planar force vector by copying another one.
template<typename OtherNumericType >
constexpr PlanarForce (const PlanarForce< OtherNumericType > &other)
Copy constructor. Constructs a planar force vector by copying another one.
constexpr PlanarForce (PlanarForce< NumericType > &&other) noexcept=default
Move constructor. Constructs a planar force vector by moving another one.
constexpr PlanarForce< NumericType > & operator= (const PlanarForce< NumericType > &other)=default
Copy assignment operator. Assigns this planar force vector by copying another one.
template<typename OtherNumericType >
constexpr PlanarForce< NumericType > & operator= (const PlanarForce< OtherNumericType > &other)
Copy assignment operator. Assigns this planar force vector by copying another one.
constexpr PlanarForce< NumericType > & operator= (PlanarForce< NumericType > &&other) noexcept=default
Move assignment operator. Assigns this planar force vector by moving another one.
constexpr ScalarForce< NumericType > x () const noexcept
Returns the x Cartesian component of this planar force vector.
constexpr ScalarForce< NumericType > y () const noexcept
Returns the y Cartesian component of this planar force vector.
ScalarForce< NumericType > Magnitude () const
Returns the magnitude of this planar force vector.
PhQ::PlanarDirection< NumericType > PlanarDirection () const
Returns the planar direction of this planar force vector.
PhQ::Angle< NumericType > Angle (const PlanarForce< NumericType > &planar_force) const
Returns the angle between this planar force vector and another one.
constexpr PlanarForce< NumericType > operator+ (const PlanarForce< NumericType > &planar_force) const
constexpr PlanarForce< NumericType > operator- (const PlanarForce< NumericType > &planar_force) const
constexpr PlanarForce< NumericType > operator* (const NumericType number) const
constexpr PlanarForce< NumericType > operator/ (const NumericType number) const
constexpr PlanarTraction< NumericType > operator/ (const Area< NumericType > &area) const
constexpr void operator+= (const PlanarForce< NumericType > &planar_force) noexcept
constexpr void operator-= (const PlanarForce< NumericType > &planar_force) noexcept
constexpr void operator*= (const NumericType number) noexcept
constexpr void operator/= (const NumericType number) noexcept
constexpr const PhQ::PlanarVector< NumericType > & Value () const noexcept
Value of this physical quantity expressed in its standard unit of measure.
PhQ::PlanarVector< NumericType > Value (const UnitType unit) const
Value of this physical quantity expressed in a given unit of measure.
template<UnitType NewUnit>
constexpr PhQ::PlanarVector< NumericType > StaticValue () const
Value of this physical quantity expressed in a given unit of measure. This method can be evaluated statically at compile-time.
constexpr PhQ::PlanarVector< NumericType > & MutableValue () noexcept
Returns the value of this physical quantity expressed in its standard unit of measure as a mutable value.
constexpr void SetValue (const PhQ::PlanarVector< NumericType > &value) noexcept
Sets the value of this physical quantity expressed in its standard unit of measure to the given value.
std::string Print () const
Prints this physical quantity as a string. This physical quantity's value is expressed in its standard unit of measure.
std::string Print (const UnitType unit) const
Prints this physical quantity as a string. This physical quantity's value is expressed in the given unit of measure.
std::string JSON () const
Serializes this physical quantity as a JSON message. This physical quantity's value is expressed in its standard unit of measure.
std::string JSON (const UnitType unit) const
Serializes this physical quantity as a JSON message. This physical quantity's value is expressed in the given unit of measure.
std::string XML () const
Serializes this physical quantity as an XML message. This physical quantity's value is expressed in its standard unit of measure.
std::string XML (const UnitType unit) const
Serializes this physical quantity as an XML message. This physical quantity's value is expressed in the given unit of measure.
std::string YAML () const
Serializes this physical quantity as a YAML message. This physical quantity's value is expressed in its standard unit of measure.
std::string YAML (const UnitType unit) const
Serializes this physical quantity as a YAML message. This physical quantity's value is expressed in the given unit of measure.
Static Public Member Functions
static constexpr PlanarForce< NumericType > Zero ()
Statically creates a planar force vector of zero.
template<Unit::Force Unit>
static constexpr PlanarForce< NumericType > Create (const NumericType x, const NumericType y)
Statically creates a planar force vector from the given x and y Cartesian components expressed in a given force unit.
template<Unit::Force Unit>
static constexpr PlanarForce< NumericType > Create (const std::array< NumericType, 2 > &x_y)
Statically creates a planar force vector from the given x and y Cartesian components expressed in a given force unit.
template<Unit::Force Unit>
static constexpr PlanarForce< NumericType > Create (const PlanarVector< NumericType > &value)
Statically creates a planar force vector with a given value expressed in a given force unit.
static constexpr const PhQ::Dimensions & Dimensions ()
Physical dimension set of this physical quantity.
static constexpr UnitType Unit ()
Standard unit of measure for this physical quantity. This physical quantity's value is stored internally in this unit of measure.
Protected Attributes
PhQ::PlanarVector< NumericType > value
Value of this physical quantity expressed in its standard unit of measure.
Private Member Functions
constexpr PlanarForce (const PlanarVector< NumericType > &value)
Constructor. Constructs a planar force vector with a given value expressed in the standard force unit.
Detailed Description
template<typename NumericType = double>
class PhQ::PlanarForce< NumericType >
Two-dimensional Euclidean force vector in the XY plane. Contains two components in Cartesian coordinates: x and y. For a three-dimensional Euclidean force vector, see PhQ::Force. For scalar force components or for the magnitude of a force vector, see PhQ::ScalarForce.
Definition at line 50 of file PlanarForce.hpp.
Constructor & Destructor Documentation
PlanarForce() [1/10]
template<typename NumericType = double> PhQ::PlanarForce< NumericType >::PlanarForce () default
Default constructor. Constructs a planar force vector with an uninitialized value.
PlanarForce() [2/10]
template<typename NumericType = double> PhQ::PlanarForce< NumericType >::PlanarForce (const PlanarVector< NumericType > & value, const Unit::Force unit) inline
Constructor. Constructs a planar force vector with a given value expressed in a given force unit.
Definition at line 57 of file PlanarForce.hpp.
PlanarForce() [3/10]
template<typename NumericType = double> PhQ::PlanarForce< NumericType >::PlanarForce (const ScalarForce< NumericType > & x, const ScalarForce< NumericType > & y) inline
Constructor. Constructs a planar force vector from a given set of scalar force components.
Definition at line 62 of file PlanarForce.hpp.
References PhQ::PlanarForce< NumericType >::x(), and PhQ::PlanarForce< NumericType >::y().
PlanarForce() [4/10]
template<typename NumericType = double> constexpr PhQ::PlanarForce< NumericType >::PlanarForce (const ScalarForce< NumericType > & scalar_force, const PlanarDirection< NumericType > & planar_direction) inline constexpr
Constructor. Constructs a planar force vector from a given scalar force magnitude and planar direction.
Definition at line 67 of file PlanarForce.hpp.
PlanarForce() [5/10]
template<typename NumericType > constexpr PhQ::PlanarForce< NumericType >::PlanarForce (const Force< NumericType > & force) inline explicit constexpr
Constructor. Constructs a planar force vector from a given force vector by projecting the force vector onto the XY plane.
Definition at line 278 of file Force.hpp.
References PhQ::DimensionalVector< UnitType, NumericType >::Value().
PlanarForce() [6/10]
template<typename NumericType > constexpr PhQ::PlanarForce< NumericType >::PlanarForce (const PlanarTraction< NumericType > & planar_traction, const Area< NumericType > & area) inline constexpr
Constructor. Constructs a planar force vector from a given planar traction and area using the definition of traction.
Definition at line 283 of file PlanarTraction.hpp.
~PlanarForce()
template<typename NumericType = double> PhQ::PlanarForce< NumericType >::~PlanarForce () default noexcept
Destructor. Destroys this planar force vector.
PlanarForce() [7/10]
template<typename NumericType = double> constexpr PhQ::PlanarForce< NumericType >::PlanarForce (const PlanarForce< NumericType > & other) constexpr default
Copy constructor. Constructs a planar force vector by copying another one.
PlanarForce() [8/10]
template<typename NumericType = double> template<typename OtherNumericType > constexpr PhQ::PlanarForce< NumericType >::PlanarForce (const PlanarForce< OtherNumericType > & other) inline explicit constexpr
Copy constructor. Constructs a planar force vector by copying another one.
Definition at line 88 of file PlanarForce.hpp.
PlanarForce() [9/10]
template<typename NumericType = double> constexpr PhQ::PlanarForce< NumericType >::PlanarForce (PlanarForce< NumericType > && other) constexpr default noexcept
Move constructor. Constructs a planar force vector by moving another one.
PlanarForce() [10/10]
template<typename NumericType = double> constexpr PhQ::PlanarForce< NumericType >::PlanarForce (const PlanarVector< NumericType > & value) inline explicit constexpr private
Constructor. Constructs a planar force vector with a given value expressed in the standard force unit.
Definition at line 202 of file PlanarForce.hpp.
Member Function Documentation
Angle()
template<typename NumericType = double> PhQ::Angle< NumericType > PhQ::PlanarForce< NumericType >::Angle (const PlanarForce< NumericType > & planar_force) const inline
Returns the angle between this planar force vector and another one.
Definition at line 161 of file PlanarForce.hpp.
Create() [1/3]
template<typename NumericType = double> template<Unit::Force Unit> static constexpr PlanarForce< NumericType > PhQ::PlanarForce< NumericType >::Create (const NumericType x, const NumericType y) inline static constexpr
Statically creates a planar force vector from the given x and y Cartesian components expressed in a given force unit.
Definition at line 116 of file PlanarForce.hpp.
References PhQ::PlanarForce< NumericType >::x(), and PhQ::PlanarForce< NumericType >::y().
Create() [2/3]
template<typename NumericType = double> template<Unit::Force Unit> static constexpr PlanarForce< NumericType > PhQ::PlanarForce< NumericType >::Create (const PlanarVector< NumericType > & value) inline static constexpr
Statically creates a planar force vector with a given value expressed in a given force unit.
Definition at line 134 of file PlanarForce.hpp.
References PhQ::DimensionalPlanarVector< UnitType, NumericType >::value.
Create() [3/3]
template<typename NumericType = double> template<Unit::Force Unit> static constexpr PlanarForce< NumericType > PhQ::PlanarForce< NumericType >::Create (const std::array< NumericType, 2 > & x_y) inline static constexpr
Statically creates a planar force vector from the given x and y Cartesian components expressed in a given force unit.
Definition at line 125 of file PlanarForce.hpp.
Dimensions()
template<typename UnitType , typename NumericType = double> static constexpr const PhQ::Dimensions & PhQ::DimensionalPlanarVector< UnitType, NumericType >::Dimensions () inline static constexpr inherited
Physical dimension set of this physical quantity.
Definition at line 50 of file DimensionalPlanarVector.hpp.
JSON() [1/2]
template<typename UnitType , typename NumericType = double> std::string PhQ::DimensionalPlanarVector< UnitType, NumericType >::JSON () const inline inherited
Serializes this physical quantity as a JSON message. This physical quantity's value is expressed in its standard unit of measure.
Definition at line 103 of file DimensionalPlanarVector.hpp.
References PhQ::Abbreviation(), and PhQ::DimensionalPlanarVector< UnitType, NumericType >::value.
Referenced by PhQ::DimensionalPlanarVector< UnitType, NumericType >::JSON().
JSON() [2/2]
template<typename UnitType , typename NumericType = double> std::string PhQ::DimensionalPlanarVector< UnitType, NumericType >::JSON (const UnitType unit) const inline inherited
Serializes this physical quantity as a JSON message. This physical quantity's value is expressed in the given unit of measure.
Definition at line 113 of file DimensionalPlanarVector.hpp.
References PhQ::Abbreviation(), PhQ::DimensionalPlanarVector< UnitType, NumericType >::JSON(), and PhQ::DimensionalPlanarVector< UnitType, NumericType >::Value().
Magnitude()
template<typename NumericType = double> ScalarForce< NumericType > PhQ::PlanarForce< NumericType >::Magnitude () const inline
Returns the magnitude of this planar force vector.
Definition at line 151 of file PlanarForce.hpp.
References PhQ::DimensionalPlanarVector< UnitType, NumericType >::value.
MutableValue()
template<typename UnitType , typename NumericType = double> constexpr PhQ::PlanarVector< NumericType > & PhQ::DimensionalPlanarVector< UnitType, NumericType >::MutableValue () inline constexpr noexcept inherited
Returns the value of this physical quantity expressed in its standard unit of measure as a mutable value.
Definition at line 79 of file DimensionalPlanarVector.hpp.
References PhQ::DimensionalPlanarVector< UnitType, NumericType >::value.
operator*()
template<typename NumericType = double> constexpr PlanarForce< NumericType > PhQ::PlanarForce< NumericType >::operator* (const NumericType number) const inline constexpr
Definition at line 173 of file PlanarForce.hpp.
References PhQ::DimensionalPlanarVector< UnitType, NumericType >::value.
operator*=()
template<typename NumericType = double> constexpr void PhQ::PlanarForce< NumericType >::operator*= (const NumericType number) inline constexpr noexcept
Definition at line 191 of file PlanarForce.hpp.
References PhQ::DimensionalPlanarVector< UnitType, NumericType >::value.
operator+()
template<typename NumericType = double> constexpr PlanarForce< NumericType > PhQ::PlanarForce< NumericType >::operator+ (const PlanarForce< NumericType > & planar_force) const inline constexpr
Definition at line 165 of file PlanarForce.hpp.
References PhQ::DimensionalPlanarVector< UnitType, NumericType >::value.
operator+=()
template<typename NumericType = double> constexpr void PhQ::PlanarForce< NumericType >::operator+= (const PlanarForce< NumericType > & planar_force) inline constexpr noexcept
Definition at line 183 of file PlanarForce.hpp.
References PhQ::DimensionalPlanarVector< UnitType, NumericType >::value.
operator-()
template<typename NumericType = double> constexpr PlanarForce< NumericType > PhQ::PlanarForce< NumericType >::operator- (const PlanarForce< NumericType > & planar_force) const inline constexpr
Definition at line 169 of file PlanarForce.hpp.
References PhQ::DimensionalPlanarVector< UnitType, NumericType >::value.
operator-=()
template<typename NumericType = double> constexpr void PhQ::PlanarForce< NumericType >::operator-= (const PlanarForce< NumericType > & planar_force) inline constexpr noexcept
Definition at line 187 of file PlanarForce.hpp.
References PhQ::DimensionalPlanarVector< UnitType, NumericType >::value.
operator/() [1/2]
template<typename NumericType > constexpr PlanarTraction< NumericType > PhQ::PlanarForce< NumericType >::operator/ (const Area< NumericType > & area) const inline constexpr
Definition at line 300 of file PlanarTraction.hpp.
operator/() [2/2]
template<typename NumericType = double> constexpr PlanarForce< NumericType > PhQ::PlanarForce< NumericType >::operator/ (const NumericType number) const inline constexpr
Definition at line 177 of file PlanarForce.hpp.
References PhQ::DimensionalPlanarVector< UnitType, NumericType >::value.
operator/=()
template<typename NumericType = double> constexpr void PhQ::PlanarForce< NumericType >::operator/= (const NumericType number) inline constexpr noexcept
Definition at line 195 of file PlanarForce.hpp.
References PhQ::DimensionalPlanarVector< UnitType, NumericType >::value.
operator=() [1/3]
template<typename NumericType = double> constexpr PlanarForce< NumericType > & PhQ::PlanarForce< NumericType >::operator= (const PlanarForce< NumericType > & other) constexpr default
Copy assignment operator. Assigns this planar force vector by copying another one.
operator=() [2/3]
template<typename NumericType = double> template<typename OtherNumericType > constexpr PlanarForce< NumericType > & PhQ::PlanarForce< NumericType >::operator= (const PlanarForce< OtherNumericType > & other) inline constexpr
Copy assignment operator. Assigns this planar force vector by copying another one.
Definition at line 99 of file PlanarForce.hpp.
References PhQ::DimensionalPlanarVector< UnitType, NumericType >::Value(), and PhQ::DimensionalPlanarVector< UnitType, NumericType >::value.
operator=() [3/3]
template<typename NumericType = double> constexpr PlanarForce< NumericType > & PhQ::PlanarForce< NumericType >::operator= (PlanarForce< NumericType > && other) constexpr default noexcept
Move assignment operator. Assigns this planar force vector by moving another one.
PlanarDirection()
template<typename NumericType = double> PhQ::PlanarDirection< NumericType > PhQ::PlanarForce< NumericType >::PlanarDirection () const inline
Returns the planar direction of this planar force vector.
Definition at line 156 of file PlanarForce.hpp.
References PhQ::DimensionalPlanarVector< UnitType, NumericType >::value.
Print() [1/2]
template<typename UnitType , typename NumericType = double> std::string PhQ::DimensionalPlanarVector< UnitType, NumericType >::Print () const inline inherited
Prints this physical quantity as a string. This physical quantity's value is expressed in its standard unit of measure.
Definition at line 91 of file DimensionalPlanarVector.hpp.
References PhQ::Abbreviation(), and PhQ::DimensionalPlanarVector< UnitType, NumericType >::value.
Referenced by PhQ::operator<<(), PhQ::operator<<(), PhQ::operator<<(), PhQ::operator<<(), PhQ::operator<<(), PhQ::operator<<(), PhQ::operator<<(), and PhQ::operator<<().
Print() [2/2]
template<typename UnitType , typename NumericType = double> std::string PhQ::DimensionalPlanarVector< UnitType, NumericType >::Print (const UnitType unit) const inline inherited
Prints this physical quantity as a string. This physical quantity's value is expressed in the given unit of measure.
Definition at line 97 of file DimensionalPlanarVector.hpp.
References PhQ::Abbreviation(), and PhQ::DimensionalPlanarVector< UnitType, NumericType >::Value().
SetValue()
template<typename UnitType , typename NumericType = double> constexpr void PhQ::DimensionalPlanarVector< UnitType, NumericType >::SetValue (const PhQ::PlanarVector< NumericType > & value) inline constexpr noexcept inherited
Sets the value of this physical quantity expressed in its standard unit of measure to the given value.
Definition at line 85 of file DimensionalPlanarVector.hpp.
References PhQ::DimensionalPlanarVector< UnitType, NumericType >::value.
StaticValue()
template<typename UnitType , typename NumericType = double> template<UnitType NewUnit> constexpr PhQ::PlanarVector< NumericType > PhQ::DimensionalPlanarVector< UnitType, NumericType >::StaticValue () const inline constexpr inherited
Value of this physical quantity expressed in a given unit of measure. This method can be evaluated statically at compile-time.
Definition at line 73 of file DimensionalPlanarVector.hpp.
References PhQ::DimensionalPlanarVector< UnitType, NumericType >::value.
Unit()
template<typename UnitType , typename NumericType = double> static constexpr UnitType PhQ::DimensionalPlanarVector< UnitType, NumericType >::Unit () inline static constexpr inherited
Standard unit of measure for this physical quantity. This physical quantity's value is stored internally in this unit of measure.
Definition at line 56 of file DimensionalPlanarVector.hpp.
Value() [1/2]
template<typename UnitType , typename NumericType = double> constexpr const PhQ::PlanarVector< NumericType > & PhQ::DimensionalPlanarVector< UnitType, NumericType >::Value () const inline constexpr noexcept inherited
Value of this physical quantity expressed in its standard unit of measure.
Definition at line 61 of file DimensionalPlanarVector.hpp.
References PhQ::DimensionalPlanarVector< UnitType, NumericType >::value.
Referenced by PhQ::Acceleration< NumericType >::Acceleration(), PhQ::Displacement< NumericType >::Displacement(), PhQ::Force< NumericType >::Force(), PhQ::HeatFlux< NumericType >::HeatFlux(), PhQ::DimensionalPlanarVector< UnitType, NumericType >::JSON(), PhQ::PlanarPosition< NumericType >::operator+(), PhQ::PlanarDisplacement< NumericType >::operator+(), PhQ::PlanarPosition< NumericType >::operator-(), PhQ::PlanarDisplacement< NumericType >::operator-(), PhQ::DimensionalPlanarVector< UnitType, NumericType >::operator=(), PhQ::PlanarAcceleration< NumericType >::operator=(), PhQ::PlanarDisplacement< NumericType >::operator=(), PhQ::PlanarForce< NumericType >::operator=(), PhQ::PlanarHeatFlux< NumericType >::operator=(), PhQ::PlanarPosition< NumericType >::operator=(), PhQ::PlanarTemperatureGradient< NumericType >::operator=(), PhQ::PlanarTraction< NumericType >::operator=(), PhQ::PlanarVelocity< NumericType >::operator=(), PhQ::operator==(), PhQ::operator==(), PhQ::PlanarHeatFlux< NumericType >::PlanarHeatFlux(), PhQ::Position< NumericType >::Position(), PhQ::DimensionalPlanarVector< UnitType, NumericType >::Print(), PhQ::TemperatureGradient< NumericType >::TemperatureGradient(), PhQ::Traction< NumericType >::Traction(), PhQ::Velocity< NumericType >::Velocity(), PhQ::DimensionalPlanarVector< UnitType, NumericType >::XML(), and PhQ::DimensionalPlanarVector< UnitType, NumericType >::YAML().
Value() [2/2]
template<typename UnitType , typename NumericType = double> PhQ::PlanarVector< NumericType > PhQ::DimensionalPlanarVector< UnitType, NumericType >::Value (const UnitType unit) const inline inherited
Value of this physical quantity expressed in a given unit of measure.
Definition at line 66 of file DimensionalPlanarVector.hpp.
References PhQ::Convert(), and PhQ::DimensionalPlanarVector< UnitType, NumericType >::value.
x()
template<typename NumericType = double> constexpr ScalarForce< NumericType > PhQ::PlanarForce< NumericType >::x () const inline constexpr noexcept
Returns the x Cartesian component of this planar force vector.
Definition at line 141 of file PlanarForce.hpp.
References PhQ::DimensionalPlanarVector< UnitType, NumericType >::value.
Referenced by PhQ::PlanarForce< NumericType >::Create(), and PhQ::PlanarForce< NumericType >::PlanarForce().
XML() [1/2]
template<typename UnitType , typename NumericType = double> std::string PhQ::DimensionalPlanarVector< UnitType, NumericType >::XML () const inline inherited
Serializes this physical quantity as an XML message. This physical quantity's value is expressed in its standard unit of measure.
Definition at line 123 of file DimensionalPlanarVector.hpp.
References PhQ::Abbreviation(), and PhQ::DimensionalPlanarVector< UnitType, NumericType >::value.
Referenced by PhQ::DimensionalPlanarVector< UnitType, NumericType >::XML().
XML() [2/2]
template<typename UnitType , typename NumericType = double> std::string PhQ::DimensionalPlanarVector< UnitType, NumericType >::XML (const UnitType unit) const inline inherited
Serializes this physical quantity as an XML message. This physical quantity's value is expressed in the given unit of measure.
Definition at line 133 of file DimensionalPlanarVector.hpp.
References PhQ::Abbreviation(), PhQ::DimensionalPlanarVector< UnitType, NumericType >::Value(), and PhQ::DimensionalPlanarVector< UnitType, NumericType >::XML().
y()
template<typename NumericType = double> constexpr ScalarForce< NumericType > PhQ::PlanarForce< NumericType >::y () const inline constexpr noexcept
Returns the y Cartesian component of this planar force vector.
Definition at line 146 of file PlanarForce.hpp.
References PhQ::DimensionalPlanarVector< UnitType, NumericType >::value.
Referenced by PhQ::PlanarForce< NumericType >::Create(), and PhQ::PlanarForce< NumericType >::PlanarForce().
YAML() [1/2]
template<typename UnitType , typename NumericType = double> std::string PhQ::DimensionalPlanarVector< UnitType, NumericType >::YAML () const inline inherited
Serializes this physical quantity as a YAML message. This physical quantity's value is expressed in its standard unit of measure.
Definition at line 143 of file DimensionalPlanarVector.hpp.
References PhQ::Abbreviation(), and PhQ::DimensionalPlanarVector< UnitType, NumericType >::value.
Referenced by PhQ::DimensionalPlanarVector< UnitType, NumericType >::YAML().
YAML() [2/2]
template<typename UnitType , typename NumericType = double> std::string PhQ::DimensionalPlanarVector< UnitType, NumericType >::YAML (const UnitType unit) const inline inherited
Serializes this physical quantity as a YAML message. This physical quantity's value is expressed in the given unit of measure.
Definition at line 153 of file DimensionalPlanarVector.hpp.
References PhQ::Abbreviation(), PhQ::DimensionalPlanarVector< UnitType, NumericType >::Value(), and PhQ::DimensionalPlanarVector< UnitType, NumericType >::YAML().
Zero()
template<typename NumericType = double> static constexpr PlanarForce< NumericType > PhQ::PlanarForce< NumericType >::Zero () inline static constexpr
Statically creates a planar force vector of zero.
Definition at line 109 of file PlanarForce.hpp.
References PhQ::PlanarVector< NumericType >::Zero().
Member Data Documentation
value
template<typename UnitType , typename NumericType = double> PhQ::PlanarVector<NumericType> PhQ::DimensionalPlanarVector< UnitType, NumericType >::value protected inherited
Value of this physical quantity expressed in its standard unit of measure.
Definition at line 222 of file DimensionalPlanarVector.hpp.
Referenced by PhQ::PlanarAcceleration< NumericType >::Create(), PhQ::PlanarDisplacement< NumericType >::Create(), PhQ::PlanarForce< NumericType >::Create(), PhQ::PlanarHeatFlux< NumericType >::Create(), PhQ::PlanarPosition< NumericType >::Create(), PhQ::PlanarTemperatureGradient< NumericType >::Create(), PhQ::PlanarTraction< NumericType >::Create(), PhQ::PlanarVelocity< NumericType >::Create(), PhQ::DimensionalPlanarVector< UnitType, NumericType >::JSON(), PhQ::PlanarAcceleration< NumericType >::Magnitude(), PhQ::PlanarDisplacement< NumericType >::Magnitude(), PhQ::PlanarForce< NumericType >::Magnitude(), PhQ::PlanarHeatFlux< NumericType >::Magnitude(), PhQ::PlanarPosition< NumericType >::Magnitude(), PhQ::PlanarTemperatureGradient< NumericType >::Magnitude(), PhQ::PlanarTraction< NumericType >::Magnitude(), PhQ::PlanarVelocity< NumericType >::Magnitude(), PhQ::DimensionalPlanarVector< UnitType, NumericType >::MutableValue(), PhQ::PlanarAcceleration< NumericType >::operator*(), PhQ::PlanarDisplacement< NumericType >::operator*(), PhQ::PlanarForce< NumericType >::operator*(), PhQ::PlanarHeatFlux< NumericType >::operator*(), PhQ::PlanarPosition< NumericType >::operator*(), PhQ::PlanarTemperatureGradient< NumericType >::operator*(), PhQ::PlanarTraction< NumericType >::operator*(), PhQ::PlanarVelocity< NumericType >::operator*(), PhQ::PlanarAcceleration< NumericType >::operator*=(), PhQ::PlanarDisplacement< NumericType >::operator*=(), PhQ::PlanarForce< NumericType >::operator*=(), PhQ::PlanarHeatFlux< NumericType >::operator*=(), PhQ::PlanarPosition< NumericType >::operator*=(), PhQ::PlanarTemperatureGradient< NumericType >::operator*=(), PhQ::PlanarTraction< NumericType >::operator*=(), PhQ::PlanarVelocity< NumericType >::operator*=(), PhQ::PlanarAcceleration< NumericType >::operator+(), PhQ::PlanarDisplacement< NumericType >::operator+(), PhQ::PlanarPosition< NumericType >::operator+(), PhQ::PlanarForce< NumericType >::operator+(), PhQ::PlanarHeatFlux< NumericType >::operator+(), PhQ::PlanarPosition< NumericType >::operator+(), PhQ::PlanarTemperatureGradient< NumericType >::operator+(), PhQ::PlanarTraction< NumericType >::operator+(), PhQ::PlanarVelocity< NumericType >::operator+(), PhQ::PlanarAcceleration< NumericType >::operator+=(), PhQ::PlanarDisplacement< NumericType >::operator+=(), PhQ::PlanarPosition< NumericType >::operator+=(), PhQ::PlanarForce< NumericType >::operator+=(), PhQ::PlanarHeatFlux< NumericType >::operator+=(), PhQ::PlanarPosition< NumericType >::operator+=(), PhQ::PlanarTemperatureGradient< NumericType >::operator+=(), PhQ::PlanarTraction< NumericType >::operator+=(), PhQ::PlanarVelocity< NumericType >::operator+=(), PhQ::PlanarAcceleration< NumericType >::operator-(), PhQ::PlanarDisplacement< NumericType >::operator-(), PhQ::PlanarPosition< NumericType >::operator-(), PhQ::PlanarForce< NumericType >::operator-(), PhQ::PlanarHeatFlux< NumericType >::operator-(), PhQ::PlanarPosition< NumericType >::operator-(), PhQ::PlanarTemperatureGradient< NumericType >::operator-(), PhQ::PlanarTraction< NumericType >::operator-(), PhQ::PlanarVelocity< NumericType >::operator-(), PhQ::PlanarAcceleration< NumericType >::operator-=(), PhQ::PlanarDisplacement< NumericType >::operator-=(), PhQ::PlanarPosition< NumericType >::operator-=(), PhQ::PlanarForce< NumericType >::operator-=(), PhQ::PlanarHeatFlux< NumericType >::operator-=(), PhQ::PlanarPosition< NumericType >::operator-=(), PhQ::PlanarTemperatureGradient< NumericType >::operator-=(), PhQ::PlanarTraction< NumericType >::operator-=(), PhQ::PlanarVelocity< NumericType >::operator-=(), PhQ::PlanarAcceleration< NumericType >::operator/(), PhQ::PlanarDisplacement< NumericType >::operator/(), PhQ::PlanarForce< NumericType >::operator/(), PhQ::PlanarHeatFlux< NumericType >::operator/(), PhQ::PlanarPosition< NumericType >::operator/(), PhQ::PlanarTemperatureGradient< NumericType >::operator/(), PhQ::PlanarTraction< NumericType >::operator/(), PhQ::PlanarVelocity< NumericType >::operator/(), PhQ::PlanarAcceleration< NumericType >::operator/=(), PhQ::PlanarDisplacement< NumericType >::operator/=(), PhQ::PlanarForce< NumericType >::operator/=(), PhQ::PlanarHeatFlux< NumericType >::operator/=(), PhQ::PlanarPosition< NumericType >::operator/=(), PhQ::PlanarTemperatureGradient< NumericType >::operator/=(), PhQ::PlanarTraction< NumericType >::operator/=(), PhQ::PlanarVelocity< NumericType >::operator/=(), PhQ::DimensionalPlanarVector< UnitType, NumericType >::operator=(), PhQ::PlanarAcceleration< NumericType >::operator=(), PhQ::PlanarDisplacement< NumericType >::operator=(), PhQ::PlanarForce< NumericType >::operator=(), PhQ::PlanarHeatFlux< NumericType >::operator=(), PhQ::PlanarPosition< NumericType >::operator=(), PhQ::PlanarTemperatureGradient< NumericType >::operator=(), PhQ::PlanarTraction< NumericType >::operator=(), PhQ::PlanarVelocity< NumericType >::operator=(), PhQ::PlanarAcceleration< NumericType >::PlanarDirection(), PhQ::PlanarDisplacement< NumericType >::PlanarDirection(), PhQ::PlanarForce< NumericType >::PlanarDirection(), PhQ::PlanarHeatFlux< NumericType >::PlanarDirection(), PhQ::PlanarPosition< NumericType >::PlanarDirection(), PhQ::PlanarTemperatureGradient< NumericType >::PlanarDirection(), PhQ::PlanarTraction< NumericType >::PlanarDirection(), PhQ::PlanarVelocity< NumericType >::PlanarDirection(), PhQ::DimensionalPlanarVector< UnitType, NumericType >::Print(), PhQ::DimensionalPlanarVector< UnitType, NumericType >::SetValue(), PhQ::DimensionalPlanarVector< UnitType, NumericType >::StaticValue(), PhQ::DimensionalPlanarVector< UnitType, NumericType >::Value(), PhQ::DimensionalPlanarVector< UnitType, NumericType >::Value(), PhQ::PlanarAcceleration< NumericType >::x(), PhQ::PlanarDisplacement< NumericType >::x(), PhQ::PlanarForce< NumericType >::x(), PhQ::PlanarHeatFlux< NumericType >::x(), PhQ::PlanarPosition< NumericType >::x(), PhQ::PlanarTemperatureGradient< NumericType >::x(), PhQ::PlanarTraction< NumericType >::x(), PhQ::PlanarVelocity< NumericType >::x(), PhQ::DimensionalPlanarVector< UnitType, NumericType >::XML(), PhQ::PlanarAcceleration< NumericType >::y(), PhQ::PlanarDisplacement< NumericType >::y(), PhQ::PlanarForce< NumericType >::y(), PhQ::PlanarHeatFlux< NumericType >::y(), PhQ::PlanarPosition< NumericType >::y(), PhQ::PlanarTemperatureGradient< NumericType >::y(), PhQ::PlanarTraction< NumericType >::y(), PhQ::PlanarVelocity< NumericType >::y(), PhQ::DimensionalPlanarVector< UnitType, NumericType >::YAML(), and PhQ::PlanarDisplacement< NumericType >::z().
The documentation for this class was generated from the following files:
PhQ/Angle.hpp
PhQ/PlanarForce.hpp
PhQ/Force.hpp
PhQ/PlanarTraction.hpp