Physical Quantities (PhQ): PhQ::Dimensions Class Reference
PhQ::Dimensions Class Reference
Physical dimension set of a unit of measure or physical quantity. Composed of the seven independent base physical dimensions: time (T), length (L), mass (M), electric current (I), temperature (Θ), amount of substance (N), and luminous intensity (J). Units of measure that share the same physical dimension set are of the same type and can be converted between one another. For example, the metre per second and the mile per hour are both units of measure that have the same physical dimension set of T^(-1)·L, which is the physical dimension set of speed, so these two units of measure can be converted between one another. On the other hand, the kilogram per cubic metre is a unit of measure with physical dimension set L^(-3)·M, which is the physical dimension set of mass density, so this unit of measure cannot be converted to either the metre per second or the mile per hour, which have a different physical dimension set.
#include "Dimensions.hpp"
Public Member Functions
constexpr Dimensions ()=default
Default constructor. Constructs a dimensionless physical dimension set where all base physical dimensions are zero.
constexpr Dimensions (const Dimension::Time &time, const Dimension::Length &length, const Dimension::Mass &mass, const Dimension::ElectricCurrent &electric_current, const Dimension::Temperature &temperature, const Dimension::SubstanceAmount &substance_amount, const Dimension::LuminousIntensity &luminous_intensity)
Constructor. Constructs a physical dimension set from the given base physical dimensions.
~Dimensions () noexcept=default
Destructor. Destroys this physical dimension set.
constexpr Dimensions (const Dimensions &other)=default
Copy constructor. Constructs a physical dimension set by copying another one.
constexpr Dimensions (Dimensions &&other) noexcept=default
Move constructor. Constructs a physical dimension set by moving another one.
constexpr Dimensions & operator= (const Dimensions &other)=default
Copy assignment operator. Assigns the base physical dimensions of this physical dimension set by copying from another one.
constexpr Dimensions & operator= (Dimensions &&other) noexcept=default
Move assignment operator. Assigns the base physical dimensions of this physical dimension set by moving another one.
constexpr const Dimension::Time & Time () const noexcept
Base physical dimension of time of this physical dimension set.
constexpr const Dimension::Length & Length () const noexcept
Base physical dimension of length of this physical dimension set.
constexpr const Dimension::Mass & Mass () const noexcept
Base physical dimension of mass of this physical dimension set.
constexpr const Dimension::ElectricCurrent & ElectricCurrent () const noexcept
Base physical dimension of electric current of this physical dimension set.
constexpr const Dimension::Temperature & Temperature () const noexcept
Base physical dimension of temperature of this physical dimension set.
constexpr const Dimension::SubstanceAmount & SubstanceAmount () const noexcept
Base physical dimension of amount of substance of this physical dimension set.
constexpr const Dimension::LuminousIntensity & LuminousIntensity () const noexcept
Base physical dimension of luminous intensity of this physical dimension set.
std::string Print () const
Prints this physical dimension set as a string.
std::string JSON () const
Serializes this physical dimension set as a JSON message.
std::string XML () const
Serializes this physical dimension set as an XML message.
std::string YAML () const
Serializes this physical dimension set as a YAML message.
Private Attributes
Dimension::Time time
Base physical dimension of time of this physical dimension set.
Dimension::Length length
Base physical dimension of length of this physical dimension set.
Dimension::Mass mass
Base physical dimension of mass of this physical dimension set.
Dimension::ElectricCurrent electric_current
Base physical dimension of electric current of this physical dimension set.
Dimension::Temperature temperature
Base physical dimension of temperature of this physical dimension set.
Dimension::SubstanceAmount substance_amount
Base physical dimension of amount of substance of this physical dimension set.
Dimension::LuminousIntensity luminous_intensity
Base physical dimension of luminous intensity of this physical dimension set.
Detailed Description
Physical dimension set of a unit of measure or physical quantity. Composed of the seven independent base physical dimensions: time (T), length (L), mass (M), electric current (I), temperature (Θ), amount of substance (N), and luminous intensity (J). Units of measure that share the same physical dimension set are of the same type and can be converted between one another. For example, the metre per second and the mile per hour are both units of measure that have the same physical dimension set of T^(-1)·L, which is the physical dimension set of speed, so these two units of measure can be converted between one another. On the other hand, the kilogram per cubic metre is a unit of measure with physical dimension set L^(-3)·M, which is the physical dimension set of mass density, so this unit of measure cannot be converted to either the metre per second or the mile per hour, which have a different physical dimension set.
Definition at line 51 of file Dimensions.hpp.
Constructor & Destructor Documentation
Dimensions() [1/4]
constexpr PhQ::Dimensions::Dimensions () constexpr default
Default constructor. Constructs a dimensionless physical dimension set where all base physical dimensions are zero.
Dimensions() [2/4]
constexpr PhQ::Dimensions::Dimensions (const Dimension::Time & time, const Dimension::Length & length, const Dimension::Mass & mass, const Dimension::ElectricCurrent & electric_current, const Dimension::Temperature & temperature, const Dimension::SubstanceAmount & substance_amount, const Dimension::LuminousIntensity & luminous_intensity) inline constexpr
Constructor. Constructs a physical dimension set from the given base physical dimensions.
Definition at line 59 of file Dimensions.hpp.
~Dimensions()
PhQ::Dimensions::~Dimensions () default noexcept
Destructor. Destroys this physical dimension set.
Dimensions() [3/4]
constexpr PhQ::Dimensions::Dimensions (const Dimensions & other) constexpr default
Copy constructor. Constructs a physical dimension set by copying another one.
Dimensions() [4/4]
constexpr PhQ::Dimensions::Dimensions (Dimensions && other) constexpr default noexcept
Move constructor. Constructs a physical dimension set by moving another one.
Member Function Documentation
ElectricCurrent()
constexpr const Dimension::ElectricCurrent& PhQ::Dimensions::ElectricCurrent () const inline constexpr noexcept
Base physical dimension of electric current of this physical dimension set.
Definition at line 101 of file Dimensions.hpp.
References electric_current.
JSON()
std::string PhQ::Dimensions::JSON () const inline
Serializes this physical dimension set as a JSON message.
Definition at line 185 of file Dimensions.hpp.
References electric_current, PhQ::Dimension::ElectricCurrent::Label(), PhQ::Dimension::Length::Label(), PhQ::Dimension::LuminousIntensity::Label(), PhQ::Dimension::Mass::Label(), PhQ::Dimension::SubstanceAmount::Label(), PhQ::Dimension::Temperature::Label(), PhQ::Dimension::Time::Label(), length, luminous_intensity, mass, PhQ::SnakeCaseCopy(), substance_amount, temperature, time, PhQ::Dimension::ElectricCurrent::Value(), PhQ::Dimension::Length::Value(), PhQ::Dimension::LuminousIntensity::Value(), PhQ::Dimension::Mass::Value(), PhQ::Dimension::SubstanceAmount::Value(), PhQ::Dimension::Temperature::Value(), and PhQ::Dimension::Time::Value().
Length()
constexpr const Dimension::Length& PhQ::Dimensions::Length () const inline constexpr noexcept
Base physical dimension of length of this physical dimension set.
Definition at line 91 of file Dimensions.hpp.
References length.
LuminousIntensity()
constexpr const Dimension::LuminousIntensity& PhQ::Dimensions::LuminousIntensity () const inline constexpr noexcept
Base physical dimension of luminous intensity of this physical dimension set.
Definition at line 116 of file Dimensions.hpp.
References luminous_intensity.
Mass()
constexpr const Dimension::Mass& PhQ::Dimensions::Mass () const inline constexpr noexcept
Base physical dimension of mass of this physical dimension set.
Definition at line 96 of file Dimensions.hpp.
References mass.
operator=() [1/2]
constexpr Dimensions& PhQ::Dimensions::operator= (const Dimensions & other) constexpr default
Copy assignment operator. Assigns the base physical dimensions of this physical dimension set by copying from another one.
operator=() [2/2]
constexpr Dimensions& PhQ::Dimensions::operator= (Dimensions && other) constexpr default noexcept
Move assignment operator. Assigns the base physical dimensions of this physical dimension set by moving another one.
Print()
std::string PhQ::Dimensions::Print () const inline
Prints this physical dimension set as a string.
Definition at line 121 of file Dimensions.hpp.
References electric_current, length, luminous_intensity, mass, PhQ::Dimension::ElectricCurrent::Print(), PhQ::Dimension::Length::Print(), PhQ::Dimension::LuminousIntensity::Print(), PhQ::Dimension::Mass::Print(), PhQ::Dimension::SubstanceAmount::Print(), PhQ::Dimension::Temperature::Print(), PhQ::Dimension::Time::Print(), substance_amount, temperature, and time.
Referenced by PhQ::operator<<().
SubstanceAmount()
constexpr const Dimension::SubstanceAmount& PhQ::Dimensions::SubstanceAmount () const inline constexpr noexcept
Base physical dimension of amount of substance of this physical dimension set.
Definition at line 111 of file Dimensions.hpp.
References substance_amount.
Temperature()
constexpr const Dimension::Temperature& PhQ::Dimensions::Temperature () const inline constexpr noexcept
Base physical dimension of temperature of this physical dimension set.
Definition at line 106 of file Dimensions.hpp.
References temperature.
Time()
constexpr const Dimension::Time& PhQ::Dimensions::Time () const inline constexpr noexcept
Base physical dimension of time of this physical dimension set.
Definition at line 86 of file Dimensions.hpp.
References time.
XML()
std::string PhQ::Dimensions::XML () const inline
Serializes this physical dimension set as an XML message.
Definition at line 237 of file Dimensions.hpp.
References electric_current, PhQ::Dimension::ElectricCurrent::Label(), PhQ::Dimension::Length::Label(), PhQ::Dimension::LuminousIntensity::Label(), PhQ::Dimension::Mass::Label(), PhQ::Dimension::SubstanceAmount::Label(), PhQ::Dimension::Temperature::Label(), PhQ::Dimension::Time::Label(), length, luminous_intensity, mass, PhQ::SnakeCaseCopy(), substance_amount, temperature, time, PhQ::Dimension::ElectricCurrent::Value(), PhQ::Dimension::Length::Value(), PhQ::Dimension::LuminousIntensity::Value(), PhQ::Dimension::Mass::Value(), PhQ::Dimension::SubstanceAmount::Value(), PhQ::Dimension::Temperature::Value(), and PhQ::Dimension::Time::Value().
YAML()
std::string PhQ::Dimensions::YAML () const inline
Serializes this physical dimension set as a YAML message.
Definition at line 274 of file Dimensions.hpp.
References electric_current, PhQ::Dimension::ElectricCurrent::Label(), PhQ::Dimension::Length::Label(), PhQ::Dimension::LuminousIntensity::Label(), PhQ::Dimension::Mass::Label(), PhQ::Dimension::SubstanceAmount::Label(), PhQ::Dimension::Temperature::Label(), PhQ::Dimension::Time::Label(), length, luminous_intensity, mass, PhQ::SnakeCaseCopy(), substance_amount, temperature, time, PhQ::Dimension::ElectricCurrent::Value(), PhQ::Dimension::Length::Value(), PhQ::Dimension::LuminousIntensity::Value(), PhQ::Dimension::Mass::Value(), PhQ::Dimension::SubstanceAmount::Value(), PhQ::Dimension::Temperature::Value(), and PhQ::Dimension::Time::Value().
Member Data Documentation
electric_current
Dimension::ElectricCurrent PhQ::Dimensions::electric_current private
Base physical dimension of electric current of this physical dimension set.
Definition at line 333 of file Dimensions.hpp.
Referenced by ElectricCurrent(), JSON(), Print(), XML(), and YAML().
length
Dimension::Length PhQ::Dimensions::length private
Base physical dimension of length of this physical dimension set.
Definition at line 327 of file Dimensions.hpp.
Referenced by JSON(), Length(), Print(), XML(), and YAML().
luminous_intensity
Dimension::LuminousIntensity PhQ::Dimensions::luminous_intensity private
Base physical dimension of luminous intensity of this physical dimension set.
Definition at line 342 of file Dimensions.hpp.
Referenced by JSON(), LuminousIntensity(), Print(), XML(), and YAML().
mass
Dimension::Mass PhQ::Dimensions::mass private
Base physical dimension of mass of this physical dimension set.
Definition at line 330 of file Dimensions.hpp.
Referenced by JSON(), Mass(), Print(), XML(), and YAML().
substance_amount
Dimension::SubstanceAmount PhQ::Dimensions::substance_amount private
Base physical dimension of amount of substance of this physical dimension set.
Definition at line 339 of file Dimensions.hpp.
Referenced by JSON(), Print(), SubstanceAmount(), XML(), and YAML().
temperature
Dimension::Temperature PhQ::Dimensions::temperature private
Base physical dimension of temperature of this physical dimension set.
Definition at line 336 of file Dimensions.hpp.
Referenced by JSON(), Print(), Temperature(), XML(), and YAML().
time
Dimension::Time PhQ::Dimensions::time private
Base physical dimension of time of this physical dimension set.
Definition at line 324 of file Dimensions.hpp.
Referenced by JSON(), Print(), Time(), XML(), and YAML().
The documentation for this class was generated from the following file:
PhQ/Dimensions.hpp