Physical Quantities (PhQ): PhQ::Dimension::Time Class Reference
PhQ::Dimension::Time Class Reference
Base physical dimension of time. Typically denoted "T". One of seven independent base physical dimensions that form the physical dimension set of any unit of measure or physical quantity.
#include "Time.hpp"
Public Member Functions
constexpr Time ()=default
Default constructor. Constructs a base physical dimension of time with a value of zero.
constexpr Time (const int8_t value)
Constructor. Constructs a base physical dimension of time with a given value.
~Time () noexcept=default
Destructor. Destroys this base physical dimension of time.
constexpr Time (const Time &other)=default
Copy constructor. Constructs a base physical dimension of time by copying another one.
constexpr Time & operator= (const Time &other)=default
Copy assignment operator. Assigns the value of this base physical dimension of time by copying from another one.
constexpr Time (Time &&other) noexcept=default
Move constructor. Constructs a base physical dimension of time by moving another one.
constexpr Time & operator= (Time &&other) noexcept=default
Move assignment operator. Assigns the value of this base physical dimension of time by moving another one.
constexpr int8_t Value () const noexcept
Value of this base physical dimension.
std::string Print () const noexcept
Prints this base physical dimension as a string.
Static Public Member Functions
static std::string_view Abbreviation () noexcept
Abbreviation of this base physical dimension.
static std::string_view Label () noexcept
Label of this base physical dimension.
Private Attributes
int8_t value {0}
Value of this base physical dimension.
Detailed Description
Base physical dimension of time. Typically denoted "T". One of seven independent base physical dimensions that form the physical dimension set of any unit of measure or physical quantity.
Definition at line 42 of file Time.hpp.
Constructor & Destructor Documentation
Time() [1/4]
constexpr PhQ::Dimension::Time::Time () constexpr default
Default constructor. Constructs a base physical dimension of time with a value of zero.
Time() [2/4]
constexpr PhQ::Dimension::Time::Time (const int8_t value) inline explicit constexpr
Constructor. Constructs a base physical dimension of time with a given value.
Definition at line 48 of file Time.hpp.
~Time()
PhQ::Dimension::Time::~Time () default noexcept
Destructor. Destroys this base physical dimension of time.
Time() [3/4]
constexpr PhQ::Dimension::Time::Time (const Time & other) constexpr default
Copy constructor. Constructs a base physical dimension of time by copying another one.
Time() [4/4]
constexpr PhQ::Dimension::Time::Time (Time && other) constexpr default noexcept
Move constructor. Constructs a base physical dimension of time by moving another one.
Member Function Documentation
Abbreviation()
static std::string_view PhQ::Dimension::Time::Abbreviation () inline static noexcept
Abbreviation of this base physical dimension.
Definition at line 73 of file Time.hpp.
Referenced by Print().
Label()
static std::string_view PhQ::Dimension::Time::Label () inline static noexcept
Label of this base physical dimension.
Definition at line 78 of file Time.hpp.
Referenced by PhQ::Dimensions::JSON(), PhQ::Dimensions::XML(), and PhQ::Dimensions::YAML().
operator=() [1/2]
constexpr Time& PhQ::Dimension::Time::operator= (const Time & other) constexpr default
Copy assignment operator. Assigns the value of this base physical dimension of time by copying from another one.
operator=() [2/2]
constexpr Time& PhQ::Dimension::Time::operator= (Time && other) constexpr default noexcept
Move assignment operator. Assigns the value of this base physical dimension of time by moving another one.
Print()
std::string PhQ::Dimension::Time::Print () const inline noexcept
Prints this base physical dimension as a string.
Definition at line 83 of file Time.hpp.
References Abbreviation(), and value.
Referenced by PhQ::Dimension::operator<<(), and PhQ::Dimensions::Print().
Value()
constexpr int8_t PhQ::Dimension::Time::Value () const inline constexpr noexcept
Value of this base physical dimension.
Definition at line 68 of file Time.hpp.
References value.
Referenced by PhQ::Dimensions::JSON(), PhQ::Dimensions::XML(), and PhQ::Dimensions::YAML().
Member Data Documentation
value
int8_t PhQ::Dimension::Time::value {0} private
Value of this base physical dimension.
Definition at line 98 of file Time.hpp.
Referenced by Print(), and Value().
The documentation for this class was generated from the following file:
PhQ/Dimension/Time.hpp