Physical Quantities: PhQ::PlanarDisplacement< NumericType > Class Template Reference
PhQ::PlanarDisplacement< NumericType > Class Template Reference
Two-dimensional Euclidean displacement vector in the XY plane. Contains two components in Cartesian coordinates: x and y. Displacement is not to be confused with position; for a two-dimensional Euclidean position vector in the XY plane, see PhQ::PlanarPosition. For a three-dimensional Euclidean displacement vector, see PhQ::Displacement. For scalar displacement components or for the magnitude of a displacement vector, see PhQ::Length.
#include "PlanarDisplacement.hpp"
Public Member Functions
PlanarDisplacement ()=default
Default constructor. Constructs a planar displacement vector with an uninitialized value.
PlanarDisplacement (const PlanarVector< NumericType > &value, const Unit::Length unit)
Constructor. Constructs a planar displacement vector with a given value expressed in a given length unit.
PlanarDisplacement (const Length< NumericType > &x, const Length< NumericType > &y)
Constructor. Constructs a planar displacement vector from a given set of length components.
constexpr PlanarDisplacement (const Length< NumericType > &length, const PlanarDirection< NumericType > &planar_direction)
Constructor. Constructs a planar displacement vector from a given length and planar direction.
constexpr PlanarDisplacement (const Displacement< NumericType > &displacement)
Constructor. Constructs a planar displacement vector from a given displacement vector by projecting the displacement vector onto the XY plane.
constexpr PlanarDisplacement (const PlanarVelocity< NumericType > &planar_velocity, const Time< NumericType > &time)
Constructor. Constructs a planar displacement vector from a given planar velocity vector and time using the definition of velocity.
constexpr PlanarDisplacement (const PlanarVelocity< NumericType > &planar_velocity, const Frequency< NumericType > &frequency)
Constructor. Constructs a planar displacement vector from a given planar velocity vector and frequency using the definition of velocity.
constexpr PlanarDisplacement (const PlanarPosition< NumericType > &planar_position)
Constructor. Constructs a planar displacement vector between a given planar position vector and the origin.
~PlanarDisplacement () noexcept=default
Destructor. Destroys this planar displacement vector.
constexpr PlanarDisplacement (const PlanarDisplacement< NumericType > &other)=default
Copy constructor. Constructs a planar displacement vector by copying another one.
template<typename OtherNumericType >
constexpr PlanarDisplacement (const PlanarDisplacement< OtherNumericType > &other)
Copy constructor. Constructs a planar displacement by copying another one.
constexpr PlanarDisplacement (PlanarDisplacement< NumericType > &&other) noexcept=default
Move constructor. Constructs a planar displacement vector by moving another one.
constexpr PlanarDisplacement< NumericType > & operator= (const PlanarDisplacement< NumericType > &other)=default
Copy assignment operator. Assigns this planar displacement vector by copying another one.
template<typename OtherNumericType >
constexpr PlanarDisplacement< NumericType > & operator= (const PlanarDisplacement< OtherNumericType > &other)
Copy assignment operator. Assigns this planar displacement vector by copying another one.
constexpr PlanarDisplacement< NumericType > & operator= (PlanarDisplacement< NumericType > &&other) noexcept=default
Move assignment operator. Assigns this planar displacement vector by moving another one.
constexpr Length< NumericType > x () const noexcept
Returns the x Cartesian component of this planar displacement vector.
constexpr Length< NumericType > y () const noexcept
Returns the y Cartesian component of this planar displacement vector.
constexpr Length< NumericType > z () const noexcept
Returns the z Cartesian component of this planar displacement vector.
Length< NumericType > Magnitude () const
Returns the magnitude of this planar displacement vector.
PhQ::PlanarDirection< NumericType > PlanarDirection () const
Returns the planar direction of this planar displacement vector.
PhQ::Angle< NumericType > Angle (const PlanarDisplacement< NumericType > &planar_displacement) const
Returns the angle between this planar displacement vector and another one.
constexpr PlanarPosition< NumericType > operator+ (const PlanarPosition< NumericType > &planar_position) const
constexpr PlanarDisplacement< NumericType > operator+ (const PlanarDisplacement< NumericType > &planar_displacement) const
constexpr PlanarPosition< NumericType > operator- (const PlanarPosition< NumericType > &planar_position) const
constexpr PlanarDisplacement< NumericType > operator- (const PlanarDisplacement< NumericType > &planar_displacement) const
constexpr PlanarDisplacement< NumericType > operator* (const NumericType number) const
constexpr PlanarVelocity< NumericType > operator* (const Frequency< NumericType > &frequency) const
constexpr PlanarDisplacement< NumericType > operator/ (const NumericType number) const
constexpr PlanarVelocity< NumericType > operator/ (const Time< NumericType > &time) const
constexpr void operator+= (const PlanarDisplacement< NumericType > &planar_displacement) noexcept
constexpr void operator-= (const PlanarDisplacement< NumericType > &planar_displacement) noexcept
constexpr void operator*= (const NumericType number) noexcept
constexpr void operator/= (const NumericType number) noexcept
constexpr const PhQ::PlanarVector< NumericType > & Value () const noexcept
Value of this physical quantity expressed in its standard unit of measure.
PhQ::PlanarVector< NumericType > Value (const UnitType unit) const
Value of this physical quantity expressed in a given unit of measure.
template<UnitType NewUnit>
constexpr PhQ::PlanarVector< NumericType > StaticValue () const
Value of this physical quantity expressed in a given unit of measure. This method can be evaluated statically at compile-time.
constexpr PhQ::PlanarVector< NumericType > & MutableValue () noexcept
Returns the value of this physical quantity expressed in its standard unit of measure as a mutable value.
constexpr void SetValue (const PhQ::PlanarVector< NumericType > &value) noexcept
Sets the value of this physical quantity expressed in its standard unit of measure to the given value.
std::string Print () const
Prints this physical quantity as a string. This physical quantity's value is expressed in its standard unit of measure.
std::string Print (const UnitType unit) const
Prints this physical quantity as a string. This physical quantity's value is expressed in the given unit of measure.
std::string JSON () const
Serializes this physical quantity as a JSON message. This physical quantity's value is expressed in its standard unit of measure.
std::string JSON (const UnitType unit) const
Serializes this physical quantity as a JSON message. This physical quantity's value is expressed in the given unit of measure.
std::string XML () const
Serializes this physical quantity as an XML message. This physical quantity's value is expressed in its standard unit of measure.
std::string XML (const UnitType unit) const
Serializes this physical quantity as an XML message. This physical quantity's value is expressed in the given unit of measure.
std::string YAML () const
Serializes this physical quantity as a YAML message. This physical quantity's value is expressed in its standard unit of measure.
std::string YAML (const UnitType unit) const
Serializes this physical quantity as a YAML message. This physical quantity's value is expressed in the given unit of measure.
Static Public Member Functions
static constexpr PlanarDisplacement< NumericType > Zero ()
Statically creates a planar displacement vector of zero.
template<Unit::Length Unit>
static constexpr PlanarDisplacement< NumericType > Create (const NumericType x, const NumericType y)
Statically creates a planar displacement vector from the given x and y Cartesian components expressed in a given length unit.
template<Unit::Length Unit>
static constexpr PlanarDisplacement< NumericType > Create (const std::array< NumericType, 2 > &x_y)
Statically creates a planar displacement vector from the given x and y Cartesian components expressed in a given length unit.
template<Unit::Length Unit>
static constexpr PlanarDisplacement< NumericType > Create (const PlanarVector< NumericType > &value)
Statically creates a planar displacement vector with a given value expressed in a given length unit.
static constexpr const PhQ::Dimensions & Dimensions ()
Physical dimension set of this physical quantity.
static constexpr UnitType Unit ()
Standard unit of measure for this physical quantity. This physical quantity's value is stored internally in this unit of measure.
Protected Attributes
PhQ::PlanarVector< NumericType > value
Value of this physical quantity expressed in its standard unit of measure.
Private Member Functions
constexpr PlanarDisplacement (const PlanarVector< NumericType > &value)
Constructor. Constructs a planar displacement vector with a given value expressed in the standard length unit.
Friends
template<typename OtherNumericType >
class PlanarPosition
Detailed Description
template<typename NumericType = double>
class PhQ::PlanarDisplacement< NumericType >
Two-dimensional Euclidean displacement vector in the XY plane. Contains two components in Cartesian coordinates: x and y. Displacement is not to be confused with position; for a two-dimensional Euclidean position vector in the XY plane, see PhQ::PlanarPosition. For a three-dimensional Euclidean displacement vector, see PhQ::Displacement. For scalar displacement components or for the magnitude of a displacement vector, see PhQ::Length.
Definition at line 64 of file PlanarDisplacement.hpp.
Constructor & Destructor Documentation
PlanarDisplacement() [1/12]
template<typename NumericType = double> PhQ::PlanarDisplacement< NumericType >::PlanarDisplacement () default
Default constructor. Constructs a planar displacement vector with an uninitialized value.
PlanarDisplacement() [2/12]
template<typename NumericType = double> PhQ::PlanarDisplacement< NumericType >::PlanarDisplacement (const PlanarVector< NumericType > & value, const Unit::Length unit) inline
Constructor. Constructs a planar displacement vector with a given value expressed in a given length unit.
Definition at line 72 of file PlanarDisplacement.hpp.
PlanarDisplacement() [3/12]
template<typename NumericType = double> PhQ::PlanarDisplacement< NumericType >::PlanarDisplacement (const Length< NumericType > & x, const Length< NumericType > & y) inline
Constructor. Constructs a planar displacement vector from a given set of length components.
Definition at line 77 of file PlanarDisplacement.hpp.
References PhQ::PlanarDisplacement< NumericType >::x(), and PhQ::PlanarDisplacement< NumericType >::y().
PlanarDisplacement() [4/12]
template<typename NumericType = double> constexpr PhQ::PlanarDisplacement< NumericType >::PlanarDisplacement (const Length< NumericType > & length, const PlanarDirection< NumericType > & planar_direction) inline constexpr
Constructor. Constructs a planar displacement vector from a given length and planar direction.
Definition at line 82 of file PlanarDisplacement.hpp.
PlanarDisplacement() [5/12]
template<typename NumericType > constexpr PhQ::PlanarDisplacement< NumericType >::PlanarDisplacement (const Displacement< NumericType > & displacement) inline explicit constexpr
Constructor. Constructs a planar displacement vector from a given displacement vector by projecting the displacement vector onto the XY plane.
Definition at line 303 of file Displacement.hpp.
References PhQ::DimensionalVector< UnitType, NumericType >::Value().
PlanarDisplacement() [6/12]
template<typename NumericType > constexpr PhQ::PlanarDisplacement< NumericType >::PlanarDisplacement (const PlanarVelocity< NumericType > & planar_velocity, const Time< NumericType > & time) inline constexpr
Constructor. Constructs a planar displacement vector from a given planar velocity vector and time using the definition of velocity.
Definition at line 302 of file PlanarVelocity.hpp.
PlanarDisplacement() [7/12]
template<typename NumericType > constexpr PhQ::PlanarDisplacement< NumericType >::PlanarDisplacement (const PlanarVelocity< NumericType > & planar_velocity, const Frequency< NumericType > & frequency) inline constexpr
Constructor. Constructs a planar displacement vector from a given planar velocity vector and frequency using the definition of velocity.
Definition at line 307 of file PlanarVelocity.hpp.
PlanarDisplacement() [8/12]
template<typename NumericType > constexpr PhQ::PlanarDisplacement< NumericType >::PlanarDisplacement (const PlanarPosition< NumericType > & planar_position) inline explicit constexpr
Constructor. Constructs a planar displacement vector between a given planar position vector and the origin.
Definition at line 289 of file PlanarPosition.hpp.
~PlanarDisplacement()
template<typename NumericType = double> PhQ::PlanarDisplacement< NumericType >::~PlanarDisplacement () default noexcept
Destructor. Destroys this planar displacement vector.
PlanarDisplacement() [9/12]
template<typename NumericType = double> constexpr PhQ::PlanarDisplacement< NumericType >::PlanarDisplacement (const PlanarDisplacement< NumericType > & other) constexpr default
Copy constructor. Constructs a planar displacement vector by copying another one.
PlanarDisplacement() [10/12]
template<typename NumericType = double> template<typename OtherNumericType > constexpr PhQ::PlanarDisplacement< NumericType >::PlanarDisplacement (const PlanarDisplacement< OtherNumericType > & other) inline explicit constexpr
Copy constructor. Constructs a planar displacement by copying another one.
Definition at line 112 of file PlanarDisplacement.hpp.
PlanarDisplacement() [11/12]
template<typename NumericType = double> constexpr PhQ::PlanarDisplacement< NumericType >::PlanarDisplacement (PlanarDisplacement< NumericType > && other) constexpr default noexcept
Move constructor. Constructs a planar displacement vector by moving another one.
PlanarDisplacement() [12/12]
template<typename NumericType = double> constexpr PhQ::PlanarDisplacement< NumericType >::PlanarDisplacement (const PlanarVector< NumericType > & value) inline explicit constexpr private
Constructor. Constructs a planar displacement vector with a given value expressed in the standard length unit.
Definition at line 249 of file PlanarDisplacement.hpp.
Member Function Documentation
Angle()
template<typename NumericType = double> PhQ::Angle< NumericType > PhQ::PlanarDisplacement< NumericType >::Angle (const PlanarDisplacement< NumericType > & planar_displacement) const inline
Returns the angle between this planar displacement vector and another one.
Definition at line 197 of file PlanarDisplacement.hpp.
Create() [1/3]
template<typename NumericType = double> template<Unit::Length Unit> static constexpr PlanarDisplacement< NumericType > PhQ::PlanarDisplacement< NumericType >::Create (const NumericType x, const NumericType y) inline static constexpr
Statically creates a planar displacement vector from the given x and y Cartesian components expressed in a given length unit.
Definition at line 145 of file PlanarDisplacement.hpp.
References PhQ::PlanarDisplacement< NumericType >::x(), and PhQ::PlanarDisplacement< NumericType >::y().
Create() [2/3]
template<typename NumericType = double> template<Unit::Length Unit> static constexpr PlanarDisplacement< NumericType > PhQ::PlanarDisplacement< NumericType >::Create (const PlanarVector< NumericType > & value) inline static constexpr
Statically creates a planar displacement vector with a given value expressed in a given length unit.
Definition at line 165 of file PlanarDisplacement.hpp.
References PhQ::DimensionalPlanarVector< UnitType, NumericType >::value.
Create() [3/3]
template<typename NumericType = double> template<Unit::Length Unit> static constexpr PlanarDisplacement< NumericType > PhQ::PlanarDisplacement< NumericType >::Create (const std::array< NumericType, 2 > & x_y) inline static constexpr
Statically creates a planar displacement vector from the given x and y Cartesian components expressed in a given length unit.
Definition at line 155 of file PlanarDisplacement.hpp.
Dimensions()
template<typename UnitType , typename NumericType = double> static constexpr const PhQ::Dimensions & PhQ::DimensionalPlanarVector< UnitType, NumericType >::Dimensions () inline static constexpr inherited
Physical dimension set of this physical quantity.
Definition at line 50 of file DimensionalPlanarVector.hpp.
JSON() [1/2]
template<typename UnitType , typename NumericType = double> std::string PhQ::DimensionalPlanarVector< UnitType, NumericType >::JSON () const inline inherited
Serializes this physical quantity as a JSON message. This physical quantity's value is expressed in its standard unit of measure.
Definition at line 103 of file DimensionalPlanarVector.hpp.
References PhQ::Abbreviation(), and PhQ::DimensionalPlanarVector< UnitType, NumericType >::value.
Referenced by PhQ::DimensionalPlanarVector< UnitType, NumericType >::JSON().
JSON() [2/2]
template<typename UnitType , typename NumericType = double> std::string PhQ::DimensionalPlanarVector< UnitType, NumericType >::JSON (const UnitType unit) const inline inherited
Serializes this physical quantity as a JSON message. This physical quantity's value is expressed in the given unit of measure.
Definition at line 113 of file DimensionalPlanarVector.hpp.
References PhQ::Abbreviation(), PhQ::DimensionalPlanarVector< UnitType, NumericType >::JSON(), and PhQ::DimensionalPlanarVector< UnitType, NumericType >::Value().
Magnitude()
template<typename NumericType = double> Length< NumericType > PhQ::PlanarDisplacement< NumericType >::Magnitude () const inline
Returns the magnitude of this planar displacement vector.
Definition at line 187 of file PlanarDisplacement.hpp.
References PhQ::DimensionalPlanarVector< UnitType, NumericType >::value.
MutableValue()
template<typename UnitType , typename NumericType = double> constexpr PhQ::PlanarVector< NumericType > & PhQ::DimensionalPlanarVector< UnitType, NumericType >::MutableValue () inline constexpr noexcept inherited
Returns the value of this physical quantity expressed in its standard unit of measure as a mutable value.
Definition at line 79 of file DimensionalPlanarVector.hpp.
References PhQ::DimensionalPlanarVector< UnitType, NumericType >::value.
operator*() [1/2]
template<typename NumericType > constexpr PlanarVelocity< NumericType > PhQ::PlanarDisplacement< NumericType >::operator* (const Frequency< NumericType > & frequency) const inline constexpr
Definition at line 336 of file PlanarVelocity.hpp.
operator*() [2/2]
template<typename NumericType = double> constexpr PlanarDisplacement< NumericType > PhQ::PlanarDisplacement< NumericType >::operator* (const NumericType number) const inline constexpr
Definition at line 218 of file PlanarDisplacement.hpp.
References PhQ::DimensionalPlanarVector< UnitType, NumericType >::value.
operator*=()
template<typename NumericType = double> constexpr void PhQ::PlanarDisplacement< NumericType >::operator*= (const NumericType number) inline constexpr noexcept
Definition at line 238 of file PlanarDisplacement.hpp.
References PhQ::DimensionalPlanarVector< UnitType, NumericType >::value.
operator+() [1/2]
template<typename NumericType = double> constexpr PlanarDisplacement< NumericType > PhQ::PlanarDisplacement< NumericType >::operator+ (const PlanarDisplacement< NumericType > & planar_displacement) const inline constexpr
Definition at line 205 of file PlanarDisplacement.hpp.
References PhQ::DimensionalPlanarVector< UnitType, NumericType >::value.
operator+() [2/2]
template<typename NumericType > constexpr PlanarPosition< NumericType > PhQ::PlanarDisplacement< NumericType >::operator+ (const PlanarPosition< NumericType > & planar_position) const inline constexpr
Definition at line 294 of file PlanarPosition.hpp.
References PhQ::DimensionalPlanarVector< UnitType, NumericType >::Value().
operator+=()
template<typename NumericType = double> constexpr void PhQ::PlanarDisplacement< NumericType >::operator+= (const PlanarDisplacement< NumericType > & planar_displacement) inline constexpr noexcept
Definition at line 230 of file PlanarDisplacement.hpp.
References PhQ::DimensionalPlanarVector< UnitType, NumericType >::value.
operator-() [1/2]
template<typename NumericType = double> constexpr PlanarDisplacement< NumericType > PhQ::PlanarDisplacement< NumericType >::operator- (const PlanarDisplacement< NumericType > & planar_displacement) const inline constexpr
Definition at line 213 of file PlanarDisplacement.hpp.
References PhQ::DimensionalPlanarVector< UnitType, NumericType >::value.
operator-() [2/2]
template<typename NumericType > constexpr PlanarPosition< NumericType > PhQ::PlanarDisplacement< NumericType >::operator- (const PlanarPosition< NumericType > & planar_position) const inline constexpr
Definition at line 300 of file PlanarPosition.hpp.
References PhQ::DimensionalPlanarVector< UnitType, NumericType >::Value().
operator-=()
template<typename NumericType = double> constexpr void PhQ::PlanarDisplacement< NumericType >::operator-= (const PlanarDisplacement< NumericType > & planar_displacement) inline constexpr noexcept
Definition at line 234 of file PlanarDisplacement.hpp.
References PhQ::DimensionalPlanarVector< UnitType, NumericType >::value.
operator/() [1/2]
template<typename NumericType = double> constexpr PlanarDisplacement< NumericType > PhQ::PlanarDisplacement< NumericType >::operator/ (const NumericType number) const inline constexpr
Definition at line 224 of file PlanarDisplacement.hpp.
References PhQ::DimensionalPlanarVector< UnitType, NumericType >::value.
operator/() [2/2]
template<typename NumericType > constexpr PlanarVelocity< NumericType > PhQ::PlanarDisplacement< NumericType >::operator/ (const Time< NumericType > & time) const inline constexpr
Definition at line 342 of file PlanarVelocity.hpp.
operator/=()
template<typename NumericType = double> constexpr void PhQ::PlanarDisplacement< NumericType >::operator/= (const NumericType number) inline constexpr noexcept
Definition at line 242 of file PlanarDisplacement.hpp.
References PhQ::DimensionalPlanarVector< UnitType, NumericType >::value.
operator=() [1/3]
template<typename NumericType = double> constexpr PlanarDisplacement< NumericType > & PhQ::PlanarDisplacement< NumericType >::operator= (const PlanarDisplacement< NumericType > & other) constexpr default
Copy assignment operator. Assigns this planar displacement vector by copying another one.
operator=() [2/3]
template<typename NumericType = double> template<typename OtherNumericType > constexpr PlanarDisplacement< NumericType > & PhQ::PlanarDisplacement< NumericType >::operator= (const PlanarDisplacement< OtherNumericType > & other) inline constexpr
Copy assignment operator. Assigns this planar displacement vector by copying another one.
Definition at line 126 of file PlanarDisplacement.hpp.
References PhQ::DimensionalPlanarVector< UnitType, NumericType >::Value(), and PhQ::DimensionalPlanarVector< UnitType, NumericType >::value.
operator=() [3/3]
template<typename NumericType = double> constexpr PlanarDisplacement< NumericType > & PhQ::PlanarDisplacement< NumericType >::operator= (PlanarDisplacement< NumericType > && other) constexpr default noexcept
Move assignment operator. Assigns this planar displacement vector by moving another one.
PlanarDirection()
template<typename NumericType = double> PhQ::PlanarDirection< NumericType > PhQ::PlanarDisplacement< NumericType >::PlanarDirection () const inline
Returns the planar direction of this planar displacement vector.
Definition at line 192 of file PlanarDisplacement.hpp.
References PhQ::DimensionalPlanarVector< UnitType, NumericType >::value.
Print() [1/2]
template<typename UnitType , typename NumericType = double> std::string PhQ::DimensionalPlanarVector< UnitType, NumericType >::Print () const inline inherited
Prints this physical quantity as a string. This physical quantity's value is expressed in its standard unit of measure.
Definition at line 91 of file DimensionalPlanarVector.hpp.
References PhQ::Abbreviation(), and PhQ::DimensionalPlanarVector< UnitType, NumericType >::value.
Referenced by PhQ::operator<<(), PhQ::operator<<(), PhQ::operator<<(), PhQ::operator<<(), PhQ::operator<<(), PhQ::operator<<(), PhQ::operator<<(), and PhQ::operator<<().
Print() [2/2]
template<typename UnitType , typename NumericType = double> std::string PhQ::DimensionalPlanarVector< UnitType, NumericType >::Print (const UnitType unit) const inline inherited
Prints this physical quantity as a string. This physical quantity's value is expressed in the given unit of measure.
Definition at line 97 of file DimensionalPlanarVector.hpp.
References PhQ::Abbreviation(), and PhQ::DimensionalPlanarVector< UnitType, NumericType >::Value().
SetValue()
template<typename UnitType , typename NumericType = double> constexpr void PhQ::DimensionalPlanarVector< UnitType, NumericType >::SetValue (const PhQ::PlanarVector< NumericType > & value) inline constexpr noexcept inherited
Sets the value of this physical quantity expressed in its standard unit of measure to the given value.
Definition at line 85 of file DimensionalPlanarVector.hpp.
References PhQ::DimensionalPlanarVector< UnitType, NumericType >::value.
StaticValue()
template<typename UnitType , typename NumericType = double> template<UnitType NewUnit> constexpr PhQ::PlanarVector< NumericType > PhQ::DimensionalPlanarVector< UnitType, NumericType >::StaticValue () const inline constexpr inherited
Value of this physical quantity expressed in a given unit of measure. This method can be evaluated statically at compile-time.
Definition at line 73 of file DimensionalPlanarVector.hpp.
References PhQ::DimensionalPlanarVector< UnitType, NumericType >::value.
Unit()
template<typename UnitType , typename NumericType = double> static constexpr UnitType PhQ::DimensionalPlanarVector< UnitType, NumericType >::Unit () inline static constexpr inherited
Standard unit of measure for this physical quantity. This physical quantity's value is stored internally in this unit of measure.
Definition at line 56 of file DimensionalPlanarVector.hpp.
Value() [1/2]
template<typename UnitType , typename NumericType = double> constexpr const PhQ::PlanarVector< NumericType > & PhQ::DimensionalPlanarVector< UnitType, NumericType >::Value () const inline constexpr noexcept inherited
Value of this physical quantity expressed in its standard unit of measure.
Definition at line 61 of file DimensionalPlanarVector.hpp.
References PhQ::DimensionalPlanarVector< UnitType, NumericType >::value.
Referenced by PhQ::Acceleration< NumericType >::Acceleration(), PhQ::Displacement< NumericType >::Displacement(), PhQ::Force< NumericType >::Force(), PhQ::HeatFlux< NumericType >::HeatFlux(), PhQ::DimensionalPlanarVector< UnitType, NumericType >::JSON(), PhQ::PlanarPosition< NumericType >::operator+(), PhQ::PlanarDisplacement< NumericType >::operator+(), PhQ::PlanarPosition< NumericType >::operator-(), PhQ::PlanarDisplacement< NumericType >::operator-(), PhQ::DimensionalPlanarVector< UnitType, NumericType >::operator=(), PhQ::PlanarAcceleration< NumericType >::operator=(), PhQ::PlanarDisplacement< NumericType >::operator=(), PhQ::PlanarForce< NumericType >::operator=(), PhQ::PlanarHeatFlux< NumericType >::operator=(), PhQ::PlanarPosition< NumericType >::operator=(), PhQ::PlanarTemperatureGradient< NumericType >::operator=(), PhQ::PlanarTraction< NumericType >::operator=(), PhQ::PlanarVelocity< NumericType >::operator=(), PhQ::operator==(), PhQ::operator==(), PhQ::PlanarHeatFlux< NumericType >::PlanarHeatFlux(), PhQ::Position< NumericType >::Position(), PhQ::DimensionalPlanarVector< UnitType, NumericType >::Print(), PhQ::TemperatureGradient< NumericType >::TemperatureGradient(), PhQ::Traction< NumericType >::Traction(), PhQ::Velocity< NumericType >::Velocity(), PhQ::DimensionalPlanarVector< UnitType, NumericType >::XML(), and PhQ::DimensionalPlanarVector< UnitType, NumericType >::YAML().
Value() [2/2]
template<typename UnitType , typename NumericType = double> PhQ::PlanarVector< NumericType > PhQ::DimensionalPlanarVector< UnitType, NumericType >::Value (const UnitType unit) const inline inherited
Value of this physical quantity expressed in a given unit of measure.
Definition at line 66 of file DimensionalPlanarVector.hpp.
References PhQ::Convert(), and PhQ::DimensionalPlanarVector< UnitType, NumericType >::value.
x()
template<typename NumericType = double> constexpr Length< NumericType > PhQ::PlanarDisplacement< NumericType >::x () const inline constexpr noexcept
Returns the x Cartesian component of this planar displacement vector.
Definition at line 172 of file PlanarDisplacement.hpp.
References PhQ::DimensionalPlanarVector< UnitType, NumericType >::value.
Referenced by PhQ::PlanarDisplacement< NumericType >::Create(), and PhQ::PlanarDisplacement< NumericType >::PlanarDisplacement().
XML() [1/2]
template<typename UnitType , typename NumericType = double> std::string PhQ::DimensionalPlanarVector< UnitType, NumericType >::XML () const inline inherited
Serializes this physical quantity as an XML message. This physical quantity's value is expressed in its standard unit of measure.
Definition at line 123 of file DimensionalPlanarVector.hpp.
References PhQ::Abbreviation(), and PhQ::DimensionalPlanarVector< UnitType, NumericType >::value.
Referenced by PhQ::DimensionalPlanarVector< UnitType, NumericType >::XML().
XML() [2/2]
template<typename UnitType , typename NumericType = double> std::string PhQ::DimensionalPlanarVector< UnitType, NumericType >::XML (const UnitType unit) const inline inherited
Serializes this physical quantity as an XML message. This physical quantity's value is expressed in the given unit of measure.
Definition at line 133 of file DimensionalPlanarVector.hpp.
References PhQ::Abbreviation(), PhQ::DimensionalPlanarVector< UnitType, NumericType >::Value(), and PhQ::DimensionalPlanarVector< UnitType, NumericType >::XML().
y()
template<typename NumericType = double> constexpr Length< NumericType > PhQ::PlanarDisplacement< NumericType >::y () const inline constexpr noexcept
Returns the y Cartesian component of this planar displacement vector.
Definition at line 177 of file PlanarDisplacement.hpp.
References PhQ::DimensionalPlanarVector< UnitType, NumericType >::value.
Referenced by PhQ::PlanarDisplacement< NumericType >::Create(), and PhQ::PlanarDisplacement< NumericType >::PlanarDisplacement().
YAML() [1/2]
template<typename UnitType , typename NumericType = double> std::string PhQ::DimensionalPlanarVector< UnitType, NumericType >::YAML () const inline inherited
Serializes this physical quantity as a YAML message. This physical quantity's value is expressed in its standard unit of measure.
Definition at line 143 of file DimensionalPlanarVector.hpp.
References PhQ::Abbreviation(), and PhQ::DimensionalPlanarVector< UnitType, NumericType >::value.
Referenced by PhQ::DimensionalPlanarVector< UnitType, NumericType >::YAML().
YAML() [2/2]
template<typename UnitType , typename NumericType = double> std::string PhQ::DimensionalPlanarVector< UnitType, NumericType >::YAML (const UnitType unit) const inline inherited
Serializes this physical quantity as a YAML message. This physical quantity's value is expressed in the given unit of measure.
Definition at line 153 of file DimensionalPlanarVector.hpp.
References PhQ::Abbreviation(), PhQ::DimensionalPlanarVector< UnitType, NumericType >::Value(), and PhQ::DimensionalPlanarVector< UnitType, NumericType >::YAML().
z()
template<typename NumericType = double> constexpr Length< NumericType > PhQ::PlanarDisplacement< NumericType >::z () const inline constexpr noexcept
Returns the z Cartesian component of this planar displacement vector.
Definition at line 182 of file PlanarDisplacement.hpp.
References PhQ::DimensionalPlanarVector< UnitType, NumericType >::value.
Zero()
template<typename NumericType = double> static constexpr PlanarDisplacement< NumericType > PhQ::PlanarDisplacement< NumericType >::Zero () inline static constexpr
Statically creates a planar displacement vector of zero.
Definition at line 138 of file PlanarDisplacement.hpp.
References PhQ::PlanarVector< NumericType >::Zero().
Friends And Related Symbol Documentation
PlanarPosition
template<typename NumericType = double> template<typename OtherNumericType > friend class PlanarPosition friend
Definition at line 253 of file PlanarDisplacement.hpp.
Member Data Documentation
value
template<typename UnitType , typename NumericType = double> PhQ::PlanarVector<NumericType> PhQ::DimensionalPlanarVector< UnitType, NumericType >::value protected inherited
Value of this physical quantity expressed in its standard unit of measure.
Definition at line 222 of file DimensionalPlanarVector.hpp.
Referenced by PhQ::PlanarAcceleration< NumericType >::Create(), PhQ::PlanarDisplacement< NumericType >::Create(), PhQ::PlanarForce< NumericType >::Create(), PhQ::PlanarHeatFlux< NumericType >::Create(), PhQ::PlanarPosition< NumericType >::Create(), PhQ::PlanarTemperatureGradient< NumericType >::Create(), PhQ::PlanarTraction< NumericType >::Create(), PhQ::PlanarVelocity< NumericType >::Create(), PhQ::DimensionalPlanarVector< UnitType, NumericType >::JSON(), PhQ::PlanarAcceleration< NumericType >::Magnitude(), PhQ::PlanarDisplacement< NumericType >::Magnitude(), PhQ::PlanarForce< NumericType >::Magnitude(), PhQ::PlanarHeatFlux< NumericType >::Magnitude(), PhQ::PlanarPosition< NumericType >::Magnitude(), PhQ::PlanarTemperatureGradient< NumericType >::Magnitude(), PhQ::PlanarTraction< NumericType >::Magnitude(), PhQ::PlanarVelocity< NumericType >::Magnitude(), PhQ::DimensionalPlanarVector< UnitType, NumericType >::MutableValue(), PhQ::PlanarAcceleration< NumericType >::operator*(), PhQ::PlanarDisplacement< NumericType >::operator*(), PhQ::PlanarForce< NumericType >::operator*(), PhQ::PlanarHeatFlux< NumericType >::operator*(), PhQ::PlanarPosition< NumericType >::operator*(), PhQ::PlanarTemperatureGradient< NumericType >::operator*(), PhQ::PlanarTraction< NumericType >::operator*(), PhQ::PlanarVelocity< NumericType >::operator*(), PhQ::PlanarAcceleration< NumericType >::operator*=(), PhQ::PlanarDisplacement< NumericType >::operator*=(), PhQ::PlanarForce< NumericType >::operator*=(), PhQ::PlanarHeatFlux< NumericType >::operator*=(), PhQ::PlanarPosition< NumericType >::operator*=(), PhQ::PlanarTemperatureGradient< NumericType >::operator*=(), PhQ::PlanarTraction< NumericType >::operator*=(), PhQ::PlanarVelocity< NumericType >::operator*=(), PhQ::PlanarAcceleration< NumericType >::operator+(), PhQ::PlanarDisplacement< NumericType >::operator+(), PhQ::PlanarPosition< NumericType >::operator+(), PhQ::PlanarForce< NumericType >::operator+(), PhQ::PlanarHeatFlux< NumericType >::operator+(), PhQ::PlanarPosition< NumericType >::operator+(), PhQ::PlanarTemperatureGradient< NumericType >::operator+(), PhQ::PlanarTraction< NumericType >::operator+(), PhQ::PlanarVelocity< NumericType >::operator+(), PhQ::PlanarAcceleration< NumericType >::operator+=(), PhQ::PlanarDisplacement< NumericType >::operator+=(), PhQ::PlanarPosition< NumericType >::operator+=(), PhQ::PlanarForce< NumericType >::operator+=(), PhQ::PlanarHeatFlux< NumericType >::operator+=(), PhQ::PlanarPosition< NumericType >::operator+=(), PhQ::PlanarTemperatureGradient< NumericType >::operator+=(), PhQ::PlanarTraction< NumericType >::operator+=(), PhQ::PlanarVelocity< NumericType >::operator+=(), PhQ::PlanarAcceleration< NumericType >::operator-(), PhQ::PlanarDisplacement< NumericType >::operator-(), PhQ::PlanarPosition< NumericType >::operator-(), PhQ::PlanarForce< NumericType >::operator-(), PhQ::PlanarHeatFlux< NumericType >::operator-(), PhQ::PlanarPosition< NumericType >::operator-(), PhQ::PlanarTemperatureGradient< NumericType >::operator-(), PhQ::PlanarTraction< NumericType >::operator-(), PhQ::PlanarVelocity< NumericType >::operator-(), PhQ::PlanarAcceleration< NumericType >::operator-=(), PhQ::PlanarDisplacement< NumericType >::operator-=(), PhQ::PlanarPosition< NumericType >::operator-=(), PhQ::PlanarForce< NumericType >::operator-=(), PhQ::PlanarHeatFlux< NumericType >::operator-=(), PhQ::PlanarPosition< NumericType >::operator-=(), PhQ::PlanarTemperatureGradient< NumericType >::operator-=(), PhQ::PlanarTraction< NumericType >::operator-=(), PhQ::PlanarVelocity< NumericType >::operator-=(), PhQ::PlanarAcceleration< NumericType >::operator/(), PhQ::PlanarDisplacement< NumericType >::operator/(), PhQ::PlanarForce< NumericType >::operator/(), PhQ::PlanarHeatFlux< NumericType >::operator/(), PhQ::PlanarPosition< NumericType >::operator/(), PhQ::PlanarTemperatureGradient< NumericType >::operator/(), PhQ::PlanarTraction< NumericType >::operator/(), PhQ::PlanarVelocity< NumericType >::operator/(), PhQ::PlanarAcceleration< NumericType >::operator/=(), PhQ::PlanarDisplacement< NumericType >::operator/=(), PhQ::PlanarForce< NumericType >::operator/=(), PhQ::PlanarHeatFlux< NumericType >::operator/=(), PhQ::PlanarPosition< NumericType >::operator/=(), PhQ::PlanarTemperatureGradient< NumericType >::operator/=(), PhQ::PlanarTraction< NumericType >::operator/=(), PhQ::PlanarVelocity< NumericType >::operator/=(), PhQ::DimensionalPlanarVector< UnitType, NumericType >::operator=(), PhQ::PlanarAcceleration< NumericType >::operator=(), PhQ::PlanarDisplacement< NumericType >::operator=(), PhQ::PlanarForce< NumericType >::operator=(), PhQ::PlanarHeatFlux< NumericType >::operator=(), PhQ::PlanarPosition< NumericType >::operator=(), PhQ::PlanarTemperatureGradient< NumericType >::operator=(), PhQ::PlanarTraction< NumericType >::operator=(), PhQ::PlanarVelocity< NumericType >::operator=(), PhQ::PlanarAcceleration< NumericType >::PlanarDirection(), PhQ::PlanarDisplacement< NumericType >::PlanarDirection(), PhQ::PlanarForce< NumericType >::PlanarDirection(), PhQ::PlanarHeatFlux< NumericType >::PlanarDirection(), PhQ::PlanarPosition< NumericType >::PlanarDirection(), PhQ::PlanarTemperatureGradient< NumericType >::PlanarDirection(), PhQ::PlanarTraction< NumericType >::PlanarDirection(), PhQ::PlanarVelocity< NumericType >::PlanarDirection(), PhQ::DimensionalPlanarVector< UnitType, NumericType >::Print(), PhQ::DimensionalPlanarVector< UnitType, NumericType >::SetValue(), PhQ::DimensionalPlanarVector< UnitType, NumericType >::StaticValue(), PhQ::DimensionalPlanarVector< UnitType, NumericType >::Value(), PhQ::DimensionalPlanarVector< UnitType, NumericType >::Value(), PhQ::PlanarAcceleration< NumericType >::x(), PhQ::PlanarDisplacement< NumericType >::x(), PhQ::PlanarForce< NumericType >::x(), PhQ::PlanarHeatFlux< NumericType >::x(), PhQ::PlanarPosition< NumericType >::x(), PhQ::PlanarTemperatureGradient< NumericType >::x(), PhQ::PlanarTraction< NumericType >::x(), PhQ::PlanarVelocity< NumericType >::x(), PhQ::DimensionalPlanarVector< UnitType, NumericType >::XML(), PhQ::PlanarAcceleration< NumericType >::y(), PhQ::PlanarDisplacement< NumericType >::y(), PhQ::PlanarForce< NumericType >::y(), PhQ::PlanarHeatFlux< NumericType >::y(), PhQ::PlanarPosition< NumericType >::y(), PhQ::PlanarTemperatureGradient< NumericType >::y(), PhQ::PlanarTraction< NumericType >::y(), PhQ::PlanarVelocity< NumericType >::y(), PhQ::DimensionalPlanarVector< UnitType, NumericType >::YAML(), and PhQ::PlanarDisplacement< NumericType >::z().
The documentation for this class was generated from the following files:
PhQ/Angle.hpp
PhQ/PlanarDisplacement.hpp
PhQ/Displacement.hpp
PhQ/PlanarPosition.hpp
PhQ/PlanarVelocity.hpp