Physical Quantities: PhQ::PlanarHeatFlux< NumericType > Class Template Reference
PhQ::PlanarHeatFlux< NumericType > Class Template Reference
Two-dimensional Euclidean heat flux vector in the XY plane. Contains two components in Cartesian coordinates: x and y. For a three-dimensional Euclidean heat flux vector, see PhQ::HeatFlux. For scalar heat flux components or for the magnitude of a heat flux vector, see PhQ::ScalarHeatFlux.
#include "PlanarHeatFlux.hpp"
Public Member Functions
PlanarHeatFlux ()=default
Default constructor. Constructs a planar heat flux vector with an uninitialized value.
PlanarHeatFlux (const PlanarVector< NumericType > &value, const Unit::EnergyFlux unit)
Constructor. Constructs a planar heat flux vector with a given value expressed in a given energy flux unit.
PlanarHeatFlux (const ScalarHeatFlux< NumericType > &x, const ScalarHeatFlux< NumericType > &y)
Constructor. Constructs a planar heat flux vector from a given set of scalar heat flux components.
constexpr PlanarHeatFlux (const ScalarHeatFlux< NumericType > &scalar_heat_flux, const PlanarDirection< NumericType > &planar_direction)
Constructor. Constructs a planar heat flux vector from a given scalar heat flux magnitude and planar direction.
constexpr PlanarHeatFlux (const HeatFlux< NumericType > &heat_flux)
Constructor. Constructs a planar heat flux vector from a given heat flux vector by projecting the heat flux vector onto the XY plane.
constexpr PlanarHeatFlux (const ScalarThermalConductivity< NumericType > &scalar_thermal_conductivity, const PlanarTemperatureGradient< NumericType > &planar_temperature_gradient)
Constructor. Constructs a planar heat flux vector from a given scalar thermal conductivity and planar temperature gradient vector using Fourier's law of heat conduction. Since heat flows opposite the temperature gradient, the resulting heat flux direction is opposite the temperature gradient direction.
constexpr PlanarHeatFlux (const ThermalConductivity< NumericType > &thermal_conductivity, const PlanarTemperatureGradient< NumericType > &planar_temperature_gradient)
Constructor. Constructs a planar heat flux vector from a given thermal conductivity tensor and planar temperature gradient vector using Fourier's law of heat conduction. Since heat flows opposite the temperature gradient, the resulting heat flux direction is opposite the temperature gradient direction.
~PlanarHeatFlux () noexcept=default
Destructor. Destroys this planar heat flux vector.
constexpr PlanarHeatFlux (const PlanarHeatFlux< NumericType > &other)=default
Copy constructor. Constructs a planar heat flux vector by copying another one.
template<typename OtherNumericType >
constexpr PlanarHeatFlux (const PlanarHeatFlux< OtherNumericType > &other)
Copy constructor. Constructs a planar heat flux vector by copying another one.
constexpr PlanarHeatFlux (PlanarHeatFlux< NumericType > &&other) noexcept=default
Move constructor. Constructs a planar heat flux vector by moving another one.
constexpr PlanarHeatFlux< NumericType > & operator= (const PlanarHeatFlux< NumericType > &other)=default
Copy assignment operator. Assigns this planar heat flux vector by copying another one.
template<typename OtherNumericType >
constexpr PlanarHeatFlux< NumericType > & operator= (const PlanarHeatFlux< OtherNumericType > &other)
Copy assignment operator. Assigns this planar heat flux vector by copying another one.
constexpr PlanarHeatFlux< NumericType > & operator= (PlanarHeatFlux< NumericType > &&other) noexcept=default
Move assignment operator. Assigns this planar heat flux vector by moving another one.
constexpr ScalarHeatFlux< NumericType > x () const noexcept
Returns the x Cartesian component of this planar heat flux vector.
constexpr ScalarHeatFlux< NumericType > y () const noexcept
Returns the y Cartesian component of this planar heat flux vector.
ScalarHeatFlux< NumericType > Magnitude () const
Returns the magnitude of this planar heat flux vector.
PhQ::PlanarDirection< NumericType > PlanarDirection () const
Returns the direction of this planar heat flux vector.
PhQ::Angle< NumericType > Angle (const PlanarHeatFlux< NumericType > &planar_heat_flux) const
Returns the angle between this planar heat flux vector and another one.
constexpr PlanarHeatFlux< NumericType > operator+ (const PlanarHeatFlux< NumericType > &planar_heat_flux) const
constexpr PlanarHeatFlux< NumericType > operator- (const PlanarHeatFlux< NumericType > &planar_heat_flux) const
constexpr PlanarHeatFlux< NumericType > operator* (const NumericType number) const
constexpr PlanarHeatFlux< NumericType > operator/ (const NumericType number) const
constexpr void operator+= (const PlanarHeatFlux< NumericType > &planar_heat_flux) noexcept
constexpr void operator-= (const PlanarHeatFlux< NumericType > &planar_heat_flux) noexcept
constexpr void operator*= (const NumericType number) noexcept
constexpr void operator/= (const NumericType number) noexcept
constexpr const PhQ::PlanarVector< NumericType > & Value () const noexcept
Value of this physical quantity expressed in its standard unit of measure.
PhQ::PlanarVector< NumericType > Value (const UnitType unit) const
Value of this physical quantity expressed in a given unit of measure.
template<UnitType NewUnit>
constexpr PhQ::PlanarVector< NumericType > StaticValue () const
Value of this physical quantity expressed in a given unit of measure. This method can be evaluated statically at compile-time.
constexpr PhQ::PlanarVector< NumericType > & MutableValue () noexcept
Returns the value of this physical quantity expressed in its standard unit of measure as a mutable value.
constexpr void SetValue (const PhQ::PlanarVector< NumericType > &value) noexcept
Sets the value of this physical quantity expressed in its standard unit of measure to the given value.
std::string Print () const
Prints this physical quantity as a string. This physical quantity's value is expressed in its standard unit of measure.
std::string Print (const UnitType unit) const
Prints this physical quantity as a string. This physical quantity's value is expressed in the given unit of measure.
std::string JSON () const
Serializes this physical quantity as a JSON message. This physical quantity's value is expressed in its standard unit of measure.
std::string JSON (const UnitType unit) const
Serializes this physical quantity as a JSON message. This physical quantity's value is expressed in the given unit of measure.
std::string XML () const
Serializes this physical quantity as an XML message. This physical quantity's value is expressed in its standard unit of measure.
std::string XML (const UnitType unit) const
Serializes this physical quantity as an XML message. This physical quantity's value is expressed in the given unit of measure.
std::string YAML () const
Serializes this physical quantity as a YAML message. This physical quantity's value is expressed in its standard unit of measure.
std::string YAML (const UnitType unit) const
Serializes this physical quantity as a YAML message. This physical quantity's value is expressed in the given unit of measure.
Static Public Member Functions
static constexpr PlanarHeatFlux< NumericType > Zero ()
Statically creates a planar heat flux vector of zero.
template<Unit::EnergyFlux Unit>
static constexpr PlanarHeatFlux< NumericType > Create (const NumericType x, const NumericType y)
Statically creates a planar heat flux vector from the given x and y Cartesian components expressed in a given energy flux unit.
template<Unit::EnergyFlux Unit>
static constexpr PlanarHeatFlux< NumericType > Create (const std::array< NumericType, 2 > &x_y)
Statically creates a planar heat flux vector from the given x and y Cartesian components expressed in a given energy flux unit.
template<Unit::EnergyFlux Unit>
static constexpr PlanarHeatFlux< NumericType > Create (const PlanarVector< NumericType > &value)
Statically creates a planar heat flux vector with a given value expressed in a given energy flux unit.
static constexpr const PhQ::Dimensions & Dimensions ()
Physical dimension set of this physical quantity.
static constexpr UnitType Unit ()
Standard unit of measure for this physical quantity. This physical quantity's value is stored internally in this unit of measure.
Protected Attributes
PhQ::PlanarVector< NumericType > value
Value of this physical quantity expressed in its standard unit of measure.
Private Member Functions
constexpr PlanarHeatFlux (const PlanarVector< NumericType > &value)
Constructor. Constructs a planar heat flux vector with a given value expressed in the standard energy flux unit.
Detailed Description
template<typename NumericType = double>
class PhQ::PlanarHeatFlux< NumericType >
Two-dimensional Euclidean heat flux vector in the XY plane. Contains two components in Cartesian coordinates: x and y. For a three-dimensional Euclidean heat flux vector, see PhQ::HeatFlux. For scalar heat flux components or for the magnitude of a heat flux vector, see PhQ::ScalarHeatFlux.
Definition at line 49 of file PlanarHeatFlux.hpp.
Constructor & Destructor Documentation
PlanarHeatFlux() [1/11]
template<typename NumericType = double> PhQ::PlanarHeatFlux< NumericType >::PlanarHeatFlux () default
Default constructor. Constructs a planar heat flux vector with an uninitialized value.
PlanarHeatFlux() [2/11]
template<typename NumericType = double> PhQ::PlanarHeatFlux< NumericType >::PlanarHeatFlux (const PlanarVector< NumericType > & value, const Unit::EnergyFlux unit) inline
Constructor. Constructs a planar heat flux vector with a given value expressed in a given energy flux unit.
Definition at line 56 of file PlanarHeatFlux.hpp.
PlanarHeatFlux() [3/11]
template<typename NumericType = double> PhQ::PlanarHeatFlux< NumericType >::PlanarHeatFlux (const ScalarHeatFlux< NumericType > & x, const ScalarHeatFlux< NumericType > & y) inline
Constructor. Constructs a planar heat flux vector from a given set of scalar heat flux components.
Definition at line 61 of file PlanarHeatFlux.hpp.
References PhQ::PlanarHeatFlux< NumericType >::x(), and PhQ::PlanarHeatFlux< NumericType >::y().
PlanarHeatFlux() [4/11]
template<typename NumericType = double> constexpr PhQ::PlanarHeatFlux< NumericType >::PlanarHeatFlux (const ScalarHeatFlux< NumericType > & scalar_heat_flux, const PlanarDirection< NumericType > & planar_direction) inline constexpr
Constructor. Constructs a planar heat flux vector from a given scalar heat flux magnitude and planar direction.
Definition at line 66 of file PlanarHeatFlux.hpp.
PlanarHeatFlux() [5/11]
template<typename NumericType > constexpr PhQ::PlanarHeatFlux< NumericType >::PlanarHeatFlux (const HeatFlux< NumericType > & heat_flux) inline explicit constexpr
Constructor. Constructs a planar heat flux vector from a given heat flux vector by projecting the heat flux vector onto the XY plane.
Definition at line 292 of file HeatFlux.hpp.
References PhQ::DimensionalVector< UnitType, NumericType >::Value().
PlanarHeatFlux() [6/11]
template<typename NumericType = double> constexpr PhQ::PlanarHeatFlux< NumericType >::PlanarHeatFlux (const ScalarThermalConductivity< NumericType > & scalar_thermal_conductivity, const PlanarTemperatureGradient< NumericType > & planar_temperature_gradient) inline constexpr
Constructor. Constructs a planar heat flux vector from a given scalar thermal conductivity and planar temperature gradient vector using Fourier's law of heat conduction. Since heat flows opposite the temperature gradient, the resulting heat flux direction is opposite the temperature gradient direction.
Definition at line 78 of file PlanarHeatFlux.hpp.
PlanarHeatFlux() [7/11]
template<typename NumericType = double> constexpr PhQ::PlanarHeatFlux< NumericType >::PlanarHeatFlux (const ThermalConductivity< NumericType > & thermal_conductivity, const PlanarTemperatureGradient< NumericType > & planar_temperature_gradient) inline constexpr
Constructor. Constructs a planar heat flux vector from a given thermal conductivity tensor and planar temperature gradient vector using Fourier's law of heat conduction. Since heat flows opposite the temperature gradient, the resulting heat flux direction is opposite the temperature gradient direction.
Definition at line 88 of file PlanarHeatFlux.hpp.
References PhQ::DimensionalPlanarVector< UnitType, NumericType >::Value(), and PhQ::DimensionalSymmetricDyad< UnitType, NumericType >::Value().
~PlanarHeatFlux()
template<typename NumericType = double> PhQ::PlanarHeatFlux< NumericType >::~PlanarHeatFlux () default noexcept
Destructor. Destroys this planar heat flux vector.
PlanarHeatFlux() [8/11]
template<typename NumericType = double> constexpr PhQ::PlanarHeatFlux< NumericType >::PlanarHeatFlux (const PlanarHeatFlux< NumericType > & other) constexpr default
Copy constructor. Constructs a planar heat flux vector by copying another one.
PlanarHeatFlux() [9/11]
template<typename NumericType = double> template<typename OtherNumericType > constexpr PhQ::PlanarHeatFlux< NumericType >::PlanarHeatFlux (const PlanarHeatFlux< OtherNumericType > & other) inline explicit constexpr
Copy constructor. Constructs a planar heat flux vector by copying another one.
Definition at line 102 of file PlanarHeatFlux.hpp.
PlanarHeatFlux() [10/11]
template<typename NumericType = double> constexpr PhQ::PlanarHeatFlux< NumericType >::PlanarHeatFlux (PlanarHeatFlux< NumericType > && other) constexpr default noexcept
Move constructor. Constructs a planar heat flux vector by moving another one.
PlanarHeatFlux() [11/11]
template<typename NumericType = double> constexpr PhQ::PlanarHeatFlux< NumericType >::PlanarHeatFlux (const PlanarVector< NumericType > & value) inline explicit constexpr private
Constructor. Constructs a planar heat flux vector with a given value expressed in the standard energy flux unit.
Definition at line 220 of file PlanarHeatFlux.hpp.
Member Function Documentation
Angle()
template<typename NumericType = double> PhQ::Angle< NumericType > PhQ::PlanarHeatFlux< NumericType >::Angle (const PlanarHeatFlux< NumericType > & planar_heat_flux) const inline
Returns the angle between this planar heat flux vector and another one.
Definition at line 178 of file PlanarHeatFlux.hpp.
Create() [1/3]
template<typename NumericType = double> template<Unit::EnergyFlux Unit> static constexpr PlanarHeatFlux< NumericType > PhQ::PlanarHeatFlux< NumericType >::Create (const NumericType x, const NumericType y) inline static constexpr
Statically creates a planar heat flux vector from the given x and y Cartesian components expressed in a given energy flux unit.
Definition at line 131 of file PlanarHeatFlux.hpp.
References PhQ::PlanarHeatFlux< NumericType >::x(), and PhQ::PlanarHeatFlux< NumericType >::y().
Create() [2/3]
template<typename NumericType = double> template<Unit::EnergyFlux Unit> static constexpr PlanarHeatFlux< NumericType > PhQ::PlanarHeatFlux< NumericType >::Create (const PlanarVector< NumericType > & value) inline static constexpr
Statically creates a planar heat flux vector with a given value expressed in a given energy flux unit.
Definition at line 151 of file PlanarHeatFlux.hpp.
References PhQ::DimensionalPlanarVector< UnitType, NumericType >::value.
Create() [3/3]
template<typename NumericType = double> template<Unit::EnergyFlux Unit> static constexpr PlanarHeatFlux< NumericType > PhQ::PlanarHeatFlux< NumericType >::Create (const std::array< NumericType, 2 > & x_y) inline static constexpr
Statically creates a planar heat flux vector from the given x and y Cartesian components expressed in a given energy flux unit.
Definition at line 141 of file PlanarHeatFlux.hpp.
Dimensions()
template<typename UnitType , typename NumericType = double> static constexpr const PhQ::Dimensions & PhQ::DimensionalPlanarVector< UnitType, NumericType >::Dimensions () inline static constexpr inherited
Physical dimension set of this physical quantity.
Definition at line 50 of file DimensionalPlanarVector.hpp.
JSON() [1/2]
template<typename UnitType , typename NumericType = double> std::string PhQ::DimensionalPlanarVector< UnitType, NumericType >::JSON () const inline inherited
Serializes this physical quantity as a JSON message. This physical quantity's value is expressed in its standard unit of measure.
Definition at line 103 of file DimensionalPlanarVector.hpp.
References PhQ::Abbreviation(), and PhQ::DimensionalPlanarVector< UnitType, NumericType >::value.
Referenced by PhQ::DimensionalPlanarVector< UnitType, NumericType >::JSON().
JSON() [2/2]
template<typename UnitType , typename NumericType = double> std::string PhQ::DimensionalPlanarVector< UnitType, NumericType >::JSON (const UnitType unit) const inline inherited
Serializes this physical quantity as a JSON message. This physical quantity's value is expressed in the given unit of measure.
Definition at line 113 of file DimensionalPlanarVector.hpp.
References PhQ::Abbreviation(), PhQ::DimensionalPlanarVector< UnitType, NumericType >::JSON(), and PhQ::DimensionalPlanarVector< UnitType, NumericType >::Value().
Magnitude()
template<typename NumericType = double> ScalarHeatFlux< NumericType > PhQ::PlanarHeatFlux< NumericType >::Magnitude () const inline
Returns the magnitude of this planar heat flux vector.
Definition at line 168 of file PlanarHeatFlux.hpp.
References PhQ::DimensionalPlanarVector< UnitType, NumericType >::value.
MutableValue()
template<typename UnitType , typename NumericType = double> constexpr PhQ::PlanarVector< NumericType > & PhQ::DimensionalPlanarVector< UnitType, NumericType >::MutableValue () inline constexpr noexcept inherited
Returns the value of this physical quantity expressed in its standard unit of measure as a mutable value.
Definition at line 79 of file DimensionalPlanarVector.hpp.
References PhQ::DimensionalPlanarVector< UnitType, NumericType >::value.
operator*()
template<typename NumericType = double> constexpr PlanarHeatFlux< NumericType > PhQ::PlanarHeatFlux< NumericType >::operator* (const NumericType number) const inline constexpr
Definition at line 193 of file PlanarHeatFlux.hpp.
References PhQ::DimensionalPlanarVector< UnitType, NumericType >::value.
operator*=()
template<typename NumericType = double> constexpr void PhQ::PlanarHeatFlux< NumericType >::operator*= (const NumericType number) inline constexpr noexcept
Definition at line 209 of file PlanarHeatFlux.hpp.
References PhQ::DimensionalPlanarVector< UnitType, NumericType >::value.
operator+()
template<typename NumericType = double> constexpr PlanarHeatFlux< NumericType > PhQ::PlanarHeatFlux< NumericType >::operator+ (const PlanarHeatFlux< NumericType > & planar_heat_flux) const inline constexpr
Definition at line 183 of file PlanarHeatFlux.hpp.
References PhQ::DimensionalPlanarVector< UnitType, NumericType >::value.
operator+=()
template<typename NumericType = double> constexpr void PhQ::PlanarHeatFlux< NumericType >::operator+= (const PlanarHeatFlux< NumericType > & planar_heat_flux) inline constexpr noexcept
Definition at line 201 of file PlanarHeatFlux.hpp.
References PhQ::DimensionalPlanarVector< UnitType, NumericType >::value.
operator-()
template<typename NumericType = double> constexpr PlanarHeatFlux< NumericType > PhQ::PlanarHeatFlux< NumericType >::operator- (const PlanarHeatFlux< NumericType > & planar_heat_flux) const inline constexpr
Definition at line 188 of file PlanarHeatFlux.hpp.
References PhQ::DimensionalPlanarVector< UnitType, NumericType >::value.
operator-=()
template<typename NumericType = double> constexpr void PhQ::PlanarHeatFlux< NumericType >::operator-= (const PlanarHeatFlux< NumericType > & planar_heat_flux) inline constexpr noexcept
Definition at line 205 of file PlanarHeatFlux.hpp.
References PhQ::DimensionalPlanarVector< UnitType, NumericType >::value.
operator/()
template<typename NumericType = double> constexpr PlanarHeatFlux< NumericType > PhQ::PlanarHeatFlux< NumericType >::operator/ (const NumericType number) const inline constexpr
Definition at line 197 of file PlanarHeatFlux.hpp.
References PhQ::DimensionalPlanarVector< UnitType, NumericType >::value.
operator/=()
template<typename NumericType = double> constexpr void PhQ::PlanarHeatFlux< NumericType >::operator/= (const NumericType number) inline constexpr noexcept
Definition at line 213 of file PlanarHeatFlux.hpp.
References PhQ::DimensionalPlanarVector< UnitType, NumericType >::value.
operator=() [1/3]
template<typename NumericType = double> constexpr PlanarHeatFlux< NumericType > & PhQ::PlanarHeatFlux< NumericType >::operator= (const PlanarHeatFlux< NumericType > & other) constexpr default
Copy assignment operator. Assigns this planar heat flux vector by copying another one.
operator=() [2/3]
template<typename NumericType = double> template<typename OtherNumericType > constexpr PlanarHeatFlux< NumericType > & PhQ::PlanarHeatFlux< NumericType >::operator= (const PlanarHeatFlux< OtherNumericType > & other) inline constexpr
Copy assignment operator. Assigns this planar heat flux vector by copying another one.
Definition at line 114 of file PlanarHeatFlux.hpp.
References PhQ::DimensionalPlanarVector< UnitType, NumericType >::Value(), and PhQ::DimensionalPlanarVector< UnitType, NumericType >::value.
operator=() [3/3]
template<typename NumericType = double> constexpr PlanarHeatFlux< NumericType > & PhQ::PlanarHeatFlux< NumericType >::operator= (PlanarHeatFlux< NumericType > && other) constexpr default noexcept
Move assignment operator. Assigns this planar heat flux vector by moving another one.
PlanarDirection()
template<typename NumericType = double> PhQ::PlanarDirection< NumericType > PhQ::PlanarHeatFlux< NumericType >::PlanarDirection () const inline
Returns the direction of this planar heat flux vector.
Definition at line 173 of file PlanarHeatFlux.hpp.
References PhQ::DimensionalPlanarVector< UnitType, NumericType >::value.
Print() [1/2]
template<typename UnitType , typename NumericType = double> std::string PhQ::DimensionalPlanarVector< UnitType, NumericType >::Print () const inline inherited
Prints this physical quantity as a string. This physical quantity's value is expressed in its standard unit of measure.
Definition at line 91 of file DimensionalPlanarVector.hpp.
References PhQ::Abbreviation(), and PhQ::DimensionalPlanarVector< UnitType, NumericType >::value.
Referenced by PhQ::operator<<(), PhQ::operator<<(), PhQ::operator<<(), PhQ::operator<<(), PhQ::operator<<(), PhQ::operator<<(), PhQ::operator<<(), and PhQ::operator<<().
Print() [2/2]
template<typename UnitType , typename NumericType = double> std::string PhQ::DimensionalPlanarVector< UnitType, NumericType >::Print (const UnitType unit) const inline inherited
Prints this physical quantity as a string. This physical quantity's value is expressed in the given unit of measure.
Definition at line 97 of file DimensionalPlanarVector.hpp.
References PhQ::Abbreviation(), and PhQ::DimensionalPlanarVector< UnitType, NumericType >::Value().
SetValue()
template<typename UnitType , typename NumericType = double> constexpr void PhQ::DimensionalPlanarVector< UnitType, NumericType >::SetValue (const PhQ::PlanarVector< NumericType > & value) inline constexpr noexcept inherited
Sets the value of this physical quantity expressed in its standard unit of measure to the given value.
Definition at line 85 of file DimensionalPlanarVector.hpp.
References PhQ::DimensionalPlanarVector< UnitType, NumericType >::value.
StaticValue()
template<typename UnitType , typename NumericType = double> template<UnitType NewUnit> constexpr PhQ::PlanarVector< NumericType > PhQ::DimensionalPlanarVector< UnitType, NumericType >::StaticValue () const inline constexpr inherited
Value of this physical quantity expressed in a given unit of measure. This method can be evaluated statically at compile-time.
Definition at line 73 of file DimensionalPlanarVector.hpp.
References PhQ::DimensionalPlanarVector< UnitType, NumericType >::value.
Unit()
template<typename UnitType , typename NumericType = double> static constexpr UnitType PhQ::DimensionalPlanarVector< UnitType, NumericType >::Unit () inline static constexpr inherited
Standard unit of measure for this physical quantity. This physical quantity's value is stored internally in this unit of measure.
Definition at line 56 of file DimensionalPlanarVector.hpp.
Value() [1/2]
template<typename UnitType , typename NumericType = double> constexpr const PhQ::PlanarVector< NumericType > & PhQ::DimensionalPlanarVector< UnitType, NumericType >::Value () const inline constexpr noexcept inherited
Value of this physical quantity expressed in its standard unit of measure.
Definition at line 61 of file DimensionalPlanarVector.hpp.
References PhQ::DimensionalPlanarVector< UnitType, NumericType >::value.
Referenced by PhQ::Acceleration< NumericType >::Acceleration(), PhQ::Displacement< NumericType >::Displacement(), PhQ::Force< NumericType >::Force(), PhQ::HeatFlux< NumericType >::HeatFlux(), PhQ::DimensionalPlanarVector< UnitType, NumericType >::JSON(), PhQ::PlanarPosition< NumericType >::operator+(), PhQ::PlanarDisplacement< NumericType >::operator+(), PhQ::PlanarPosition< NumericType >::operator-(), PhQ::PlanarDisplacement< NumericType >::operator-(), PhQ::DimensionalPlanarVector< UnitType, NumericType >::operator=(), PhQ::PlanarAcceleration< NumericType >::operator=(), PhQ::PlanarDisplacement< NumericType >::operator=(), PhQ::PlanarForce< NumericType >::operator=(), PhQ::PlanarHeatFlux< NumericType >::operator=(), PhQ::PlanarPosition< NumericType >::operator=(), PhQ::PlanarTemperatureGradient< NumericType >::operator=(), PhQ::PlanarTraction< NumericType >::operator=(), PhQ::PlanarVelocity< NumericType >::operator=(), PhQ::operator==(), PhQ::operator==(), PhQ::PlanarHeatFlux< NumericType >::PlanarHeatFlux(), PhQ::Position< NumericType >::Position(), PhQ::DimensionalPlanarVector< UnitType, NumericType >::Print(), PhQ::TemperatureGradient< NumericType >::TemperatureGradient(), PhQ::Traction< NumericType >::Traction(), PhQ::Velocity< NumericType >::Velocity(), PhQ::DimensionalPlanarVector< UnitType, NumericType >::XML(), and PhQ::DimensionalPlanarVector< UnitType, NumericType >::YAML().
Value() [2/2]
template<typename UnitType , typename NumericType = double> PhQ::PlanarVector< NumericType > PhQ::DimensionalPlanarVector< UnitType, NumericType >::Value (const UnitType unit) const inline inherited
Value of this physical quantity expressed in a given unit of measure.
Definition at line 66 of file DimensionalPlanarVector.hpp.
References PhQ::Convert(), and PhQ::DimensionalPlanarVector< UnitType, NumericType >::value.
x()
template<typename NumericType = double> constexpr ScalarHeatFlux< NumericType > PhQ::PlanarHeatFlux< NumericType >::x () const inline constexpr noexcept
Returns the x Cartesian component of this planar heat flux vector.
Definition at line 158 of file PlanarHeatFlux.hpp.
References PhQ::DimensionalPlanarVector< UnitType, NumericType >::value.
Referenced by PhQ::PlanarHeatFlux< NumericType >::Create(), and PhQ::PlanarHeatFlux< NumericType >::PlanarHeatFlux().
XML() [1/2]
template<typename UnitType , typename NumericType = double> std::string PhQ::DimensionalPlanarVector< UnitType, NumericType >::XML () const inline inherited
Serializes this physical quantity as an XML message. This physical quantity's value is expressed in its standard unit of measure.
Definition at line 123 of file DimensionalPlanarVector.hpp.
References PhQ::Abbreviation(), and PhQ::DimensionalPlanarVector< UnitType, NumericType >::value.
Referenced by PhQ::DimensionalPlanarVector< UnitType, NumericType >::XML().
XML() [2/2]
template<typename UnitType , typename NumericType = double> std::string PhQ::DimensionalPlanarVector< UnitType, NumericType >::XML (const UnitType unit) const inline inherited
Serializes this physical quantity as an XML message. This physical quantity's value is expressed in the given unit of measure.
Definition at line 133 of file DimensionalPlanarVector.hpp.
References PhQ::Abbreviation(), PhQ::DimensionalPlanarVector< UnitType, NumericType >::Value(), and PhQ::DimensionalPlanarVector< UnitType, NumericType >::XML().
y()
template<typename NumericType = double> constexpr ScalarHeatFlux< NumericType > PhQ::PlanarHeatFlux< NumericType >::y () const inline constexpr noexcept
Returns the y Cartesian component of this planar heat flux vector.
Definition at line 163 of file PlanarHeatFlux.hpp.
References PhQ::DimensionalPlanarVector< UnitType, NumericType >::value.
Referenced by PhQ::PlanarHeatFlux< NumericType >::Create(), and PhQ::PlanarHeatFlux< NumericType >::PlanarHeatFlux().
YAML() [1/2]
template<typename UnitType , typename NumericType = double> std::string PhQ::DimensionalPlanarVector< UnitType, NumericType >::YAML () const inline inherited
Serializes this physical quantity as a YAML message. This physical quantity's value is expressed in its standard unit of measure.
Definition at line 143 of file DimensionalPlanarVector.hpp.
References PhQ::Abbreviation(), and PhQ::DimensionalPlanarVector< UnitType, NumericType >::value.
Referenced by PhQ::DimensionalPlanarVector< UnitType, NumericType >::YAML().
YAML() [2/2]
template<typename UnitType , typename NumericType = double> std::string PhQ::DimensionalPlanarVector< UnitType, NumericType >::YAML (const UnitType unit) const inline inherited
Serializes this physical quantity as a YAML message. This physical quantity's value is expressed in the given unit of measure.
Definition at line 153 of file DimensionalPlanarVector.hpp.
References PhQ::Abbreviation(), PhQ::DimensionalPlanarVector< UnitType, NumericType >::Value(), and PhQ::DimensionalPlanarVector< UnitType, NumericType >::YAML().
Zero()
template<typename NumericType = double> static constexpr PlanarHeatFlux< NumericType > PhQ::PlanarHeatFlux< NumericType >::Zero () inline static constexpr
Statically creates a planar heat flux vector of zero.
Definition at line 124 of file PlanarHeatFlux.hpp.
References PhQ::PlanarVector< NumericType >::Zero().
Member Data Documentation
value
template<typename UnitType , typename NumericType = double> PhQ::PlanarVector<NumericType> PhQ::DimensionalPlanarVector< UnitType, NumericType >::value protected inherited
Value of this physical quantity expressed in its standard unit of measure.
Definition at line 222 of file DimensionalPlanarVector.hpp.
Referenced by PhQ::PlanarAcceleration< NumericType >::Create(), PhQ::PlanarDisplacement< NumericType >::Create(), PhQ::PlanarForce< NumericType >::Create(), PhQ::PlanarHeatFlux< NumericType >::Create(), PhQ::PlanarPosition< NumericType >::Create(), PhQ::PlanarTemperatureGradient< NumericType >::Create(), PhQ::PlanarTraction< NumericType >::Create(), PhQ::PlanarVelocity< NumericType >::Create(), PhQ::DimensionalPlanarVector< UnitType, NumericType >::JSON(), PhQ::PlanarAcceleration< NumericType >::Magnitude(), PhQ::PlanarDisplacement< NumericType >::Magnitude(), PhQ::PlanarForce< NumericType >::Magnitude(), PhQ::PlanarHeatFlux< NumericType >::Magnitude(), PhQ::PlanarPosition< NumericType >::Magnitude(), PhQ::PlanarTemperatureGradient< NumericType >::Magnitude(), PhQ::PlanarTraction< NumericType >::Magnitude(), PhQ::PlanarVelocity< NumericType >::Magnitude(), PhQ::DimensionalPlanarVector< UnitType, NumericType >::MutableValue(), PhQ::PlanarAcceleration< NumericType >::operator*(), PhQ::PlanarDisplacement< NumericType >::operator*(), PhQ::PlanarForce< NumericType >::operator*(), PhQ::PlanarHeatFlux< NumericType >::operator*(), PhQ::PlanarPosition< NumericType >::operator*(), PhQ::PlanarTemperatureGradient< NumericType >::operator*(), PhQ::PlanarTraction< NumericType >::operator*(), PhQ::PlanarVelocity< NumericType >::operator*(), PhQ::PlanarAcceleration< NumericType >::operator*=(), PhQ::PlanarDisplacement< NumericType >::operator*=(), PhQ::PlanarForce< NumericType >::operator*=(), PhQ::PlanarHeatFlux< NumericType >::operator*=(), PhQ::PlanarPosition< NumericType >::operator*=(), PhQ::PlanarTemperatureGradient< NumericType >::operator*=(), PhQ::PlanarTraction< NumericType >::operator*=(), PhQ::PlanarVelocity< NumericType >::operator*=(), PhQ::PlanarAcceleration< NumericType >::operator+(), PhQ::PlanarDisplacement< NumericType >::operator+(), PhQ::PlanarPosition< NumericType >::operator+(), PhQ::PlanarForce< NumericType >::operator+(), PhQ::PlanarHeatFlux< NumericType >::operator+(), PhQ::PlanarPosition< NumericType >::operator+(), PhQ::PlanarTemperatureGradient< NumericType >::operator+(), PhQ::PlanarTraction< NumericType >::operator+(), PhQ::PlanarVelocity< NumericType >::operator+(), PhQ::PlanarAcceleration< NumericType >::operator+=(), PhQ::PlanarDisplacement< NumericType >::operator+=(), PhQ::PlanarPosition< NumericType >::operator+=(), PhQ::PlanarForce< NumericType >::operator+=(), PhQ::PlanarHeatFlux< NumericType >::operator+=(), PhQ::PlanarPosition< NumericType >::operator+=(), PhQ::PlanarTemperatureGradient< NumericType >::operator+=(), PhQ::PlanarTraction< NumericType >::operator+=(), PhQ::PlanarVelocity< NumericType >::operator+=(), PhQ::PlanarAcceleration< NumericType >::operator-(), PhQ::PlanarDisplacement< NumericType >::operator-(), PhQ::PlanarPosition< NumericType >::operator-(), PhQ::PlanarForce< NumericType >::operator-(), PhQ::PlanarHeatFlux< NumericType >::operator-(), PhQ::PlanarPosition< NumericType >::operator-(), PhQ::PlanarTemperatureGradient< NumericType >::operator-(), PhQ::PlanarTraction< NumericType >::operator-(), PhQ::PlanarVelocity< NumericType >::operator-(), PhQ::PlanarAcceleration< NumericType >::operator-=(), PhQ::PlanarDisplacement< NumericType >::operator-=(), PhQ::PlanarPosition< NumericType >::operator-=(), PhQ::PlanarForce< NumericType >::operator-=(), PhQ::PlanarHeatFlux< NumericType >::operator-=(), PhQ::PlanarPosition< NumericType >::operator-=(), PhQ::PlanarTemperatureGradient< NumericType >::operator-=(), PhQ::PlanarTraction< NumericType >::operator-=(), PhQ::PlanarVelocity< NumericType >::operator-=(), PhQ::PlanarAcceleration< NumericType >::operator/(), PhQ::PlanarDisplacement< NumericType >::operator/(), PhQ::PlanarForce< NumericType >::operator/(), PhQ::PlanarHeatFlux< NumericType >::operator/(), PhQ::PlanarPosition< NumericType >::operator/(), PhQ::PlanarTemperatureGradient< NumericType >::operator/(), PhQ::PlanarTraction< NumericType >::operator/(), PhQ::PlanarVelocity< NumericType >::operator/(), PhQ::PlanarAcceleration< NumericType >::operator/=(), PhQ::PlanarDisplacement< NumericType >::operator/=(), PhQ::PlanarForce< NumericType >::operator/=(), PhQ::PlanarHeatFlux< NumericType >::operator/=(), PhQ::PlanarPosition< NumericType >::operator/=(), PhQ::PlanarTemperatureGradient< NumericType >::operator/=(), PhQ::PlanarTraction< NumericType >::operator/=(), PhQ::PlanarVelocity< NumericType >::operator/=(), PhQ::DimensionalPlanarVector< UnitType, NumericType >::operator=(), PhQ::PlanarAcceleration< NumericType >::operator=(), PhQ::PlanarDisplacement< NumericType >::operator=(), PhQ::PlanarForce< NumericType >::operator=(), PhQ::PlanarHeatFlux< NumericType >::operator=(), PhQ::PlanarPosition< NumericType >::operator=(), PhQ::PlanarTemperatureGradient< NumericType >::operator=(), PhQ::PlanarTraction< NumericType >::operator=(), PhQ::PlanarVelocity< NumericType >::operator=(), PhQ::PlanarAcceleration< NumericType >::PlanarDirection(), PhQ::PlanarDisplacement< NumericType >::PlanarDirection(), PhQ::PlanarForce< NumericType >::PlanarDirection(), PhQ::PlanarHeatFlux< NumericType >::PlanarDirection(), PhQ::PlanarPosition< NumericType >::PlanarDirection(), PhQ::PlanarTemperatureGradient< NumericType >::PlanarDirection(), PhQ::PlanarTraction< NumericType >::PlanarDirection(), PhQ::PlanarVelocity< NumericType >::PlanarDirection(), PhQ::DimensionalPlanarVector< UnitType, NumericType >::Print(), PhQ::DimensionalPlanarVector< UnitType, NumericType >::SetValue(), PhQ::DimensionalPlanarVector< UnitType, NumericType >::StaticValue(), PhQ::DimensionalPlanarVector< UnitType, NumericType >::Value(), PhQ::DimensionalPlanarVector< UnitType, NumericType >::Value(), PhQ::PlanarAcceleration< NumericType >::x(), PhQ::PlanarDisplacement< NumericType >::x(), PhQ::PlanarForce< NumericType >::x(), PhQ::PlanarHeatFlux< NumericType >::x(), PhQ::PlanarPosition< NumericType >::x(), PhQ::PlanarTemperatureGradient< NumericType >::x(), PhQ::PlanarTraction< NumericType >::x(), PhQ::PlanarVelocity< NumericType >::x(), PhQ::DimensionalPlanarVector< UnitType, NumericType >::XML(), PhQ::PlanarAcceleration< NumericType >::y(), PhQ::PlanarDisplacement< NumericType >::y(), PhQ::PlanarForce< NumericType >::y(), PhQ::PlanarHeatFlux< NumericType >::y(), PhQ::PlanarPosition< NumericType >::y(), PhQ::PlanarTemperatureGradient< NumericType >::y(), PhQ::PlanarTraction< NumericType >::y(), PhQ::PlanarVelocity< NumericType >::y(), PhQ::DimensionalPlanarVector< UnitType, NumericType >::YAML(), and PhQ::PlanarDisplacement< NumericType >::z().
The documentation for this class was generated from the following files:
PhQ/Angle.hpp
PhQ/PlanarHeatFlux.hpp
PhQ/HeatFlux.hpp