Physical Quantities: PhQ::Displacement< NumericType > Class Template Reference
PhQ::Displacement< NumericType > Class Template Reference
Three-dimensional Euclidean displacement vector. Contains three components in Cartesian coordinates: x, y, and z. Displacement is not to be confused with position; for a three-dimensional Euclidean position vector, see PhQ::Position. For a two-dimensional Euclidean displacement vector in the XY plane, see PhQ::PlanarDisplacement. For scalar displacement components or for the magnitude of a displacement vector, see PhQ::Length.
#include "Displacement.hpp"
Public Member Functions
Displacement ()=default
Default constructor. Constructs a displacement vector with an uninitialized value.
Displacement (const Vector< NumericType > &value, const Unit::Length unit)
Constructor. Constructs a displacement vector with a given value expressed in a given length unit.
Displacement (const Length< NumericType > &x, const Length< NumericType > &y, const Length< NumericType > &z)
Constructor. Constructs a displacement vector from a given set of length components.
constexpr Displacement (const Length< NumericType > &length, const Direction< NumericType > &direction)
Constructor. Constructs a displacement vector from a given length and direction.
constexpr Displacement (const PlanarDisplacement< NumericType > &planar_displacement)
Constructor. Constructs an displacement vector from a given planar displacement vector in the XY plane. This displacement vector's z-component is initialized to zero.
constexpr Displacement (const Velocity< NumericType > &velocity, const Time< NumericType > &time)
Constructor. Constructs a displacement vector from a given velocity vector and time using the definition of velocity.
constexpr Displacement (const Velocity< NumericType > &velocity, const Frequency< NumericType > &frequency)
Constructor. Constructs a displacement vector from a given velocity vector and frequency using the definition of velocity.
constexpr Displacement (const Position< NumericType > &position)
Constructor. Constructs a displacement vector between a given position vector and the origin.
~Displacement () noexcept=default
Destructor. Destroys this displacement vector.
constexpr Displacement (const Displacement< NumericType > &other)=default
Copy constructor. Constructs a displacement vector by copying another one.
template<typename OtherNumericType >
constexpr Displacement (const Displacement< OtherNumericType > &other)
Copy constructor. Constructs a displacement by copying another one.
constexpr Displacement (Displacement< NumericType > &&other) noexcept=default
Move constructor. Constructs a displacement vector by moving another one.
constexpr Displacement< NumericType > & operator= (const Displacement< NumericType > &other)=default
Copy assignment operator. Assigns this displacement vector by copying another one.
template<typename OtherNumericType >
constexpr Displacement< NumericType > & operator= (const Displacement< OtherNumericType > &other)
Copy assignment operator. Assigns this displacement by copying another one.
constexpr Displacement< NumericType > & operator= (Displacement< NumericType > &&other) noexcept=default
Move assignment operator. Assigns this displacement vector by moving another one.
constexpr Length< NumericType > x () const noexcept
Returns the x Cartesian component of this displacement vector.
constexpr Length< NumericType > y () const noexcept
Returns the y Cartesian component of this displacement vector.
constexpr Length< NumericType > z () const noexcept
Returns the z Cartesian component of this displacement vector.
Length< NumericType > Magnitude () const
Returns the magnitude of this displacement vector.
PhQ::Direction< NumericType > Direction () const
Returns the direction of this displacement vector.
PhQ::Angle< NumericType > Angle (const Displacement< NumericType > &displacement) const
Returns the angle between this displacement vector and another one.
constexpr Position< NumericType > operator+ (const Position< NumericType > &position) const
constexpr Displacement< NumericType > operator+ (const Displacement< NumericType > &displacement) const
constexpr Position< NumericType > operator- (const Position< NumericType > &position) const
constexpr Displacement< NumericType > operator- (const Displacement< NumericType > &displacement) const
constexpr Displacement< NumericType > operator* (const NumericType number) const
constexpr Velocity< NumericType > operator* (const Frequency< NumericType > &frequency) const
constexpr Displacement< NumericType > operator/ (const NumericType number) const
constexpr Velocity< NumericType > operator/ (const Time< NumericType > &time) const
constexpr void operator+= (const Displacement< NumericType > &displacement) noexcept
constexpr void operator-= (const Displacement< NumericType > &displacement) noexcept
constexpr void operator*= (const NumericType number) noexcept
constexpr void operator/= (const NumericType number) noexcept
constexpr const PhQ::Vector< NumericType > & Value () const noexcept
Value of this physical quantity expressed in its standard unit of measure.
PhQ::Vector< NumericType > Value (const UnitType unit) const
Value of this physical quantity expressed in a given unit of measure.
template<UnitType NewUnit>
constexpr PhQ::Vector< NumericType > StaticValue () const
Value of this physical quantity expressed in a given unit of measure. This method can be evaluated statically at compile-time.
constexpr PhQ::Vector< NumericType > & MutableValue () noexcept
Returns the value of this physical quantity expressed in its standard unit of measure as a mutable value.
constexpr void SetValue (const PhQ::Vector< NumericType > &value) noexcept
Sets the value of this physical quantity expressed in its standard unit of measure to the given value.
std::string Print () const
Prints this physical quantity as a string. This physical quantity's value is expressed in its standard unit of measure.
std::string Print (const UnitType unit) const
Prints this physical quantity as a string. This physical quantity's value is expressed in the given unit of measure.
std::string JSON () const
Serializes this physical quantity as a JSON message. This physical quantity's value is expressed in its standard unit of measure.
std::string JSON (const UnitType unit) const
Serializes this physical quantity as a JSON message. This physical quantity's value is expressed in the given unit of measure.
std::string XML () const
Serializes this physical quantity as an XML message. This physical quantity's value is expressed in its standard unit of measure.
std::string XML (const UnitType unit) const
Serializes this physical quantity as an XML message. This physical quantity's value is expressed in the given unit of measure.
std::string YAML () const
Serializes this physical quantity as a YAML message. This physical quantity's value is expressed in its standard unit of measure.
std::string YAML (const UnitType unit) const
Serializes this physical quantity as a YAML message. This physical quantity's value is expressed in the given unit of measure.
Static Public Member Functions
static constexpr Displacement< NumericType > Zero ()
Statically creates a displacement vector of zero.
template<Unit::Length Unit>
static constexpr Displacement< NumericType > Create (const NumericType x, const NumericType y, const NumericType z)
Statically creates a displacement vector from the given x, y, and z Cartesian components expressed in a given length unit.
template<Unit::Length Unit>
static constexpr Displacement< NumericType > Create (const std::array< NumericType, 3 > &x_y_z)
Statically creates a displacement vector from the given x, y, and z Cartesian components expressed in a given length unit.
template<Unit::Length Unit>
static constexpr Displacement< NumericType > Create (const Vector< NumericType > &value)
Statically creates a displacement vector with a given value expressed in a given length unit.
static constexpr const PhQ::Dimensions & Dimensions ()
Physical dimension set of this physical quantity.
static constexpr UnitType Unit ()
Standard unit of measure for this physical quantity. This physical quantity's value is stored internally in this unit of measure.
Protected Attributes
PhQ::Vector< NumericType > value
Value of this physical quantity expressed in its standard unit of measure.
Private Member Functions
constexpr Displacement (const Vector< NumericType > &value)
Constructor. Constructs a displacement vector with a given value expressed in the standard length unit.
Friends
template<typename OtherNumericType >
class Position
Detailed Description
template<typename NumericType = double>
class PhQ::Displacement< NumericType >
Three-dimensional Euclidean displacement vector. Contains three components in Cartesian coordinates: x, y, and z. Displacement is not to be confused with position; for a three-dimensional Euclidean position vector, see PhQ::Position. For a two-dimensional Euclidean displacement vector in the XY plane, see PhQ::PlanarDisplacement. For scalar displacement components or for the magnitude of a displacement vector, see PhQ::Length.
Definition at line 65 of file Displacement.hpp.
Constructor & Destructor Documentation
Displacement() [1/12]
template<typename NumericType = double> PhQ::Displacement< NumericType >::Displacement () default
Default constructor. Constructs a displacement vector with an uninitialized value.
Displacement() [2/12]
template<typename NumericType = double> PhQ::Displacement< NumericType >::Displacement (const Vector< NumericType > & value, const Unit::Length unit) inline
Constructor. Constructs a displacement vector with a given value expressed in a given length unit.
Definition at line 72 of file Displacement.hpp.
Displacement() [3/12]
template<typename NumericType = double> PhQ::Displacement< NumericType >::Displacement (const Length< NumericType > & x, const Length< NumericType > & y, const Length< NumericType > & z) inline
Constructor. Constructs a displacement vector from a given set of length components.
Definition at line 76 of file Displacement.hpp.
References PhQ::Displacement< NumericType >::x(), PhQ::Displacement< NumericType >::y(), and PhQ::Displacement< NumericType >::z().
Displacement() [4/12]
template<typename NumericType = double> constexpr PhQ::Displacement< NumericType >::Displacement (const Length< NumericType > & length, const Direction< NumericType > & direction) inline constexpr
Constructor. Constructs a displacement vector from a given length and direction.
Definition at line 81 of file Displacement.hpp.
Displacement() [5/12]
template<typename NumericType = double> constexpr PhQ::Displacement< NumericType >::Displacement (const PlanarDisplacement< NumericType > & planar_displacement) inline explicit constexpr
Constructor. Constructs an displacement vector from a given planar displacement vector in the XY plane. This displacement vector's z-component is initialized to zero.
Definition at line 86 of file Displacement.hpp.
References PhQ::DimensionalPlanarVector< UnitType, NumericType >::Value().
Displacement() [6/12]
template<typename NumericType > constexpr PhQ::Displacement< NumericType >::Displacement (const Velocity< NumericType > & velocity, const Time< NumericType > & time) inline constexpr
Constructor. Constructs a displacement vector from a given velocity vector and time using the definition of velocity.
Definition at line 295 of file Velocity.hpp.
Displacement() [7/12]
template<typename NumericType > constexpr PhQ::Displacement< NumericType >::Displacement (const Velocity< NumericType > & velocity, const Frequency< NumericType > & frequency) inline constexpr
Constructor. Constructs a displacement vector from a given velocity vector and frequency using the definition of velocity.
Definition at line 300 of file Velocity.hpp.
Displacement() [8/12]
template<typename NumericType > constexpr PhQ::Displacement< NumericType >::Displacement (const Position< NumericType > & position) inline explicit constexpr
Constructor. Constructs a displacement vector between a given position vector and the origin.
Definition at line 282 of file Position.hpp.
~Displacement()
template<typename NumericType = double> PhQ::Displacement< NumericType >::~Displacement () default noexcept
Destructor. Destroys this displacement vector.
Displacement() [9/12]
template<typename NumericType = double> constexpr PhQ::Displacement< NumericType >::Displacement (const Displacement< NumericType > & other) constexpr default
Copy constructor. Constructs a displacement vector by copying another one.
Displacement() [10/12]
template<typename NumericType = double> template<typename OtherNumericType > constexpr PhQ::Displacement< NumericType >::Displacement (const Displacement< OtherNumericType > & other) inline explicit constexpr
Copy constructor. Constructs a displacement by copying another one.
Definition at line 110 of file Displacement.hpp.
Displacement() [11/12]
template<typename NumericType = double> constexpr PhQ::Displacement< NumericType >::Displacement (Displacement< NumericType > && other) constexpr default noexcept
Move constructor. Constructs a displacement vector by moving another one.
Displacement() [12/12]
template<typename NumericType = double> constexpr PhQ::Displacement< NumericType >::Displacement (const Vector< NumericType > & value) inline explicit constexpr private
Constructor. Constructs a displacement vector with a given value expressed in the standard length unit.
Definition at line 237 of file Displacement.hpp.
Member Function Documentation
Angle()
template<typename NumericType = double> PhQ::Angle< NumericType > PhQ::Displacement< NumericType >::Angle (const Displacement< NumericType > & displacement) const inline
Returns the angle between this displacement vector and another one.
Definition at line 188 of file Displacement.hpp.
Create() [1/3]
template<typename NumericType = double> template<Unit::Length Unit> static constexpr Displacement< NumericType > PhQ::Displacement< NumericType >::Create (const NumericType x, const NumericType y, const NumericType z) inline static constexpr
Statically creates a displacement vector from the given x, y, and z Cartesian components expressed in a given length unit.
Definition at line 138 of file Displacement.hpp.
References PhQ::Displacement< NumericType >::x(), PhQ::Displacement< NumericType >::y(), and PhQ::Displacement< NumericType >::z().
Create() [2/3]
template<typename NumericType = double> template<Unit::Length Unit> static constexpr Displacement< NumericType > PhQ::Displacement< NumericType >::Create (const std::array< NumericType, 3 > & x_y_z) inline static constexpr
Statically creates a displacement vector from the given x, y, and z Cartesian components expressed in a given length unit.
Definition at line 147 of file Displacement.hpp.
Create() [3/3]
template<typename NumericType = double> template<Unit::Length Unit> static constexpr Displacement< NumericType > PhQ::Displacement< NumericType >::Create (const Vector< NumericType > & value) inline static constexpr
Statically creates a displacement vector with a given value expressed in a given length unit.
Definition at line 156 of file Displacement.hpp.
References PhQ::DimensionalVector< UnitType, NumericType >::value.
Dimensions()
template<typename UnitType , typename NumericType = double> static constexpr const PhQ::Dimensions & PhQ::DimensionalVector< UnitType, NumericType >::Dimensions () inline static constexpr inherited
Physical dimension set of this physical quantity.
Definition at line 50 of file DimensionalVector.hpp.
Direction()
template<typename NumericType = double> PhQ::Direction< NumericType > PhQ::Displacement< NumericType >::Direction () const inline
Returns the direction of this displacement vector.
Definition at line 183 of file Displacement.hpp.
References PhQ::DimensionalVector< UnitType, NumericType >::value.
JSON() [1/2]
template<typename UnitType , typename NumericType = double> std::string PhQ::DimensionalVector< UnitType, NumericType >::JSON () const inline inherited
Serializes this physical quantity as a JSON message. This physical quantity's value is expressed in its standard unit of measure.
Definition at line 103 of file DimensionalVector.hpp.
References PhQ::Abbreviation(), and PhQ::DimensionalVector< UnitType, NumericType >::value.
Referenced by PhQ::DimensionalVector< UnitType, NumericType >::JSON().
JSON() [2/2]
template<typename UnitType , typename NumericType = double> std::string PhQ::DimensionalVector< UnitType, NumericType >::JSON (const UnitType unit) const inline inherited
Serializes this physical quantity as a JSON message. This physical quantity's value is expressed in the given unit of measure.
Definition at line 113 of file DimensionalVector.hpp.
References PhQ::Abbreviation(), PhQ::DimensionalVector< UnitType, NumericType >::JSON(), and PhQ::DimensionalVector< UnitType, NumericType >::Value().
Magnitude()
template<typename NumericType = double> Length< NumericType > PhQ::Displacement< NumericType >::Magnitude () const inline
Returns the magnitude of this displacement vector.
Definition at line 178 of file Displacement.hpp.
References PhQ::DimensionalVector< UnitType, NumericType >::value.
MutableValue()
template<typename UnitType , typename NumericType = double> constexpr PhQ::Vector< NumericType > & PhQ::DimensionalVector< UnitType, NumericType >::MutableValue () inline constexpr noexcept inherited
Returns the value of this physical quantity expressed in its standard unit of measure as a mutable value.
Definition at line 79 of file DimensionalVector.hpp.
References PhQ::DimensionalVector< UnitType, NumericType >::value.
operator*() [1/2]
template<typename NumericType > constexpr Velocity< NumericType > PhQ::Displacement< NumericType >::operator* (const Frequency< NumericType > & frequency) const inline constexpr
Definition at line 333 of file Velocity.hpp.
operator*() [2/2]
template<typename NumericType = double> constexpr Displacement< NumericType > PhQ::Displacement< NumericType >::operator* (const NumericType number) const inline constexpr
Definition at line 206 of file Displacement.hpp.
References PhQ::DimensionalVector< UnitType, NumericType >::value.
operator*=()
template<typename NumericType = double> constexpr void PhQ::Displacement< NumericType >::operator*= (const NumericType number) inline constexpr noexcept
Definition at line 226 of file Displacement.hpp.
References PhQ::DimensionalVector< UnitType, NumericType >::value.
operator+() [1/2]
template<typename NumericType = double> constexpr Displacement< NumericType > PhQ::Displacement< NumericType >::operator+ (const Displacement< NumericType > & displacement) const inline constexpr
Definition at line 194 of file Displacement.hpp.
References PhQ::DimensionalVector< UnitType, NumericType >::value.
operator+() [2/2]
template<typename NumericType > constexpr Position< NumericType > PhQ::Displacement< NumericType >::operator+ (const Position< NumericType > & position) const inline constexpr
Definition at line 286 of file Position.hpp.
References PhQ::DimensionalVector< UnitType, NumericType >::Value().
operator+=()
template<typename NumericType = double> constexpr void PhQ::Displacement< NumericType >::operator+= (const Displacement< NumericType > & displacement) inline constexpr noexcept
Definition at line 218 of file Displacement.hpp.
References PhQ::DimensionalVector< UnitType, NumericType >::value.
operator-() [1/2]
template<typename NumericType = double> constexpr Displacement< NumericType > PhQ::Displacement< NumericType >::operator- (const Displacement< NumericType > & displacement) const inline constexpr
Definition at line 201 of file Displacement.hpp.
References PhQ::DimensionalVector< UnitType, NumericType >::value.
operator-() [2/2]
template<typename NumericType > constexpr Position< NumericType > PhQ::Displacement< NumericType >::operator- (const Position< NumericType > & position) const inline constexpr
Definition at line 292 of file Position.hpp.
References PhQ::DimensionalVector< UnitType, NumericType >::Value().
operator-=()
template<typename NumericType = double> constexpr void PhQ::Displacement< NumericType >::operator-= (const Displacement< NumericType > & displacement) inline constexpr noexcept
Definition at line 222 of file Displacement.hpp.
References PhQ::DimensionalVector< UnitType, NumericType >::value.
operator/() [1/2]
template<typename NumericType = double> constexpr Displacement< NumericType > PhQ::Displacement< NumericType >::operator/ (const NumericType number) const inline constexpr
Definition at line 212 of file Displacement.hpp.
References PhQ::DimensionalVector< UnitType, NumericType >::value.
operator/() [2/2]
template<typename NumericType > constexpr Velocity< NumericType > PhQ::Displacement< NumericType >::operator/ (const Time< NumericType > & time) const inline constexpr
Definition at line 339 of file Velocity.hpp.
operator/=()
template<typename NumericType = double> constexpr void PhQ::Displacement< NumericType >::operator/= (const NumericType number) inline constexpr noexcept
Definition at line 230 of file Displacement.hpp.
References PhQ::DimensionalVector< UnitType, NumericType >::value.
operator=() [1/3]
template<typename NumericType = double> constexpr Displacement< NumericType > & PhQ::Displacement< NumericType >::operator= (const Displacement< NumericType > & other) constexpr default
Copy assignment operator. Assigns this displacement vector by copying another one.
operator=() [2/3]
template<typename NumericType = double> template<typename OtherNumericType > constexpr Displacement< NumericType > & PhQ::Displacement< NumericType >::operator= (const Displacement< OtherNumericType > & other) inline constexpr
Copy assignment operator. Assigns this displacement by copying another one.
Definition at line 121 of file Displacement.hpp.
References PhQ::DimensionalVector< UnitType, NumericType >::Value(), and PhQ::DimensionalVector< UnitType, NumericType >::value.
operator=() [3/3]
template<typename NumericType = double> constexpr Displacement< NumericType > & PhQ::Displacement< NumericType >::operator= (Displacement< NumericType > && other) constexpr default noexcept
Move assignment operator. Assigns this displacement vector by moving another one.
Print() [1/2]
template<typename UnitType , typename NumericType = double> std::string PhQ::DimensionalVector< UnitType, NumericType >::Print () const inline inherited
Prints this physical quantity as a string. This physical quantity's value is expressed in its standard unit of measure.
Definition at line 91 of file DimensionalVector.hpp.
References PhQ::Abbreviation(), and PhQ::DimensionalVector< UnitType, NumericType >::value.
Referenced by PhQ::operator<<(), PhQ::operator<<(), PhQ::operator<<(), PhQ::operator<<(), PhQ::operator<<(), PhQ::operator<<(), PhQ::operator<<(), PhQ::operator<<(), and PhQ::operator<<().
Print() [2/2]
template<typename UnitType , typename NumericType = double> std::string PhQ::DimensionalVector< UnitType, NumericType >::Print (const UnitType unit) const inline inherited
Prints this physical quantity as a string. This physical quantity's value is expressed in the given unit of measure.
Definition at line 97 of file DimensionalVector.hpp.
References PhQ::Abbreviation(), and PhQ::DimensionalVector< UnitType, NumericType >::Value().
SetValue()
template<typename UnitType , typename NumericType = double> constexpr void PhQ::DimensionalVector< UnitType, NumericType >::SetValue (const PhQ::Vector< NumericType > & value) inline constexpr noexcept inherited
Sets the value of this physical quantity expressed in its standard unit of measure to the given value.
Definition at line 85 of file DimensionalVector.hpp.
References PhQ::DimensionalVector< UnitType, NumericType >::value.
StaticValue()
template<typename UnitType , typename NumericType = double> template<UnitType NewUnit> constexpr PhQ::Vector< NumericType > PhQ::DimensionalVector< UnitType, NumericType >::StaticValue () const inline constexpr inherited
Value of this physical quantity expressed in a given unit of measure. This method can be evaluated statically at compile-time.
Definition at line 73 of file DimensionalVector.hpp.
References PhQ::DimensionalVector< UnitType, NumericType >::value.
Unit()
template<typename UnitType , typename NumericType = double> static constexpr UnitType PhQ::DimensionalVector< UnitType, NumericType >::Unit () inline static constexpr inherited
Standard unit of measure for this physical quantity. This physical quantity's value is stored internally in this unit of measure.
Definition at line 56 of file DimensionalVector.hpp.
Value() [1/2]
template<typename UnitType , typename NumericType = double> constexpr const PhQ::Vector< NumericType > & PhQ::DimensionalVector< UnitType, NumericType >::Value () const inline constexpr noexcept inherited
Value of this physical quantity expressed in its standard unit of measure.
Definition at line 61 of file DimensionalVector.hpp.
References PhQ::DimensionalVector< UnitType, NumericType >::value.
Referenced by PhQ::DimensionalVector< UnitType, NumericType >::JSON(), PhQ::Position< NumericType >::operator+(), PhQ::Displacement< NumericType >::operator+(), PhQ::Position< NumericType >::operator-(), PhQ::Displacement< NumericType >::operator-(), PhQ::Acceleration< NumericType >::operator=(), PhQ::DimensionalVector< UnitType, NumericType >::operator=(), PhQ::Displacement< NumericType >::operator=(), PhQ::Force< NumericType >::operator=(), PhQ::HeatFlux< NumericType >::operator=(), PhQ::Position< NumericType >::operator=(), PhQ::TemperatureGradient< NumericType >::operator=(), PhQ::Traction< NumericType >::operator=(), PhQ::VectorArea< NumericType >::operator=(), PhQ::Velocity< NumericType >::operator=(), PhQ::operator==(), PhQ::operator==(), PhQ::operator==(), PhQ::operator==(), PhQ::operator==(), PhQ::operator==(), PhQ::operator==(), PhQ::operator==(), PhQ::operator==(), PhQ::operator==(), PhQ::operator==(), PhQ::operator==(), PhQ::operator==(), PhQ::operator==(), PhQ::operator==(), PhQ::operator==(), PhQ::PlanarAcceleration< NumericType >::PlanarAcceleration(), PhQ::PlanarDisplacement< NumericType >::PlanarDisplacement(), PhQ::PlanarForce< NumericType >::PlanarForce(), PhQ::PlanarHeatFlux< NumericType >::PlanarHeatFlux(), PhQ::PlanarPosition< NumericType >::PlanarPosition(), PhQ::PlanarTemperatureGradient< NumericType >::PlanarTemperatureGradient(), PhQ::PlanarTraction< NumericType >::PlanarTraction(), PhQ::PlanarVelocity< NumericType >::PlanarVelocity(), PhQ::DimensionalVector< UnitType, NumericType >::Print(), PhQ::DimensionalVector< UnitType, NumericType >::XML(), and PhQ::DimensionalVector< UnitType, NumericType >::YAML().
Value() [2/2]
template<typename UnitType , typename NumericType = double> PhQ::Vector< NumericType > PhQ::DimensionalVector< UnitType, NumericType >::Value (const UnitType unit) const inline inherited
Value of this physical quantity expressed in a given unit of measure.
Definition at line 66 of file DimensionalVector.hpp.
References PhQ::Convert(), and PhQ::DimensionalVector< UnitType, NumericType >::value.
x()
template<typename NumericType = double> constexpr Length< NumericType > PhQ::Displacement< NumericType >::x () const inline constexpr noexcept
Returns the x Cartesian component of this displacement vector.
Definition at line 163 of file Displacement.hpp.
References PhQ::DimensionalVector< UnitType, NumericType >::value.
Referenced by PhQ::Displacement< NumericType >::Create(), and PhQ::Displacement< NumericType >::Displacement().
XML() [1/2]
template<typename UnitType , typename NumericType = double> std::string PhQ::DimensionalVector< UnitType, NumericType >::XML () const inline inherited
Serializes this physical quantity as an XML message. This physical quantity's value is expressed in its standard unit of measure.
Definition at line 123 of file DimensionalVector.hpp.
References PhQ::Abbreviation(), and PhQ::DimensionalVector< UnitType, NumericType >::value.
Referenced by PhQ::DimensionalVector< UnitType, NumericType >::XML().
XML() [2/2]
template<typename UnitType , typename NumericType = double> std::string PhQ::DimensionalVector< UnitType, NumericType >::XML (const UnitType unit) const inline inherited
Serializes this physical quantity as an XML message. This physical quantity's value is expressed in the given unit of measure.
Definition at line 133 of file DimensionalVector.hpp.
References PhQ::Abbreviation(), PhQ::DimensionalVector< UnitType, NumericType >::Value(), and PhQ::DimensionalVector< UnitType, NumericType >::XML().
y()
template<typename NumericType = double> constexpr Length< NumericType > PhQ::Displacement< NumericType >::y () const inline constexpr noexcept
Returns the y Cartesian component of this displacement vector.
Definition at line 168 of file Displacement.hpp.
References PhQ::DimensionalVector< UnitType, NumericType >::value.
Referenced by PhQ::Displacement< NumericType >::Create(), and PhQ::Displacement< NumericType >::Displacement().
YAML() [1/2]
template<typename UnitType , typename NumericType = double> std::string PhQ::DimensionalVector< UnitType, NumericType >::YAML () const inline inherited
Serializes this physical quantity as a YAML message. This physical quantity's value is expressed in its standard unit of measure.
Definition at line 143 of file DimensionalVector.hpp.
References PhQ::Abbreviation(), and PhQ::DimensionalVector< UnitType, NumericType >::value.
Referenced by PhQ::DimensionalVector< UnitType, NumericType >::YAML().
YAML() [2/2]
template<typename UnitType , typename NumericType = double> std::string PhQ::DimensionalVector< UnitType, NumericType >::YAML (const UnitType unit) const inline inherited
Serializes this physical quantity as a YAML message. This physical quantity's value is expressed in the given unit of measure.
Definition at line 153 of file DimensionalVector.hpp.
References PhQ::Abbreviation(), PhQ::DimensionalVector< UnitType, NumericType >::Value(), and PhQ::DimensionalVector< UnitType, NumericType >::YAML().
z()
template<typename NumericType = double> constexpr Length< NumericType > PhQ::Displacement< NumericType >::z () const inline constexpr noexcept
Returns the z Cartesian component of this displacement vector.
Definition at line 173 of file Displacement.hpp.
References PhQ::DimensionalVector< UnitType, NumericType >::value.
Referenced by PhQ::Displacement< NumericType >::Create(), and PhQ::Displacement< NumericType >::Displacement().
Zero()
template<typename NumericType = double> static constexpr Displacement< NumericType > PhQ::Displacement< NumericType >::Zero () inline static constexpr
Statically creates a displacement vector of zero.
Definition at line 131 of file Displacement.hpp.
References PhQ::Vector< NumericType >::Zero().
Friends And Related Symbol Documentation
Position
template<typename NumericType = double> template<typename OtherNumericType > friend class Position friend
Definition at line 241 of file Displacement.hpp.
Member Data Documentation
value
template<typename UnitType , typename NumericType = double> PhQ::Vector<NumericType> PhQ::DimensionalVector< UnitType, NumericType >::value protected inherited
Value of this physical quantity expressed in its standard unit of measure.
Definition at line 217 of file DimensionalVector.hpp.
Referenced by PhQ::Acceleration< NumericType >::Create(), PhQ::Displacement< NumericType >::Create(), PhQ::Force< NumericType >::Create(), PhQ::HeatFlux< NumericType >::Create(), PhQ::Position< NumericType >::Create(), PhQ::TemperatureGradient< NumericType >::Create(), PhQ::Traction< NumericType >::Create(), PhQ::VectorArea< NumericType >::Create(), PhQ::Velocity< NumericType >::Create(), PhQ::Acceleration< NumericType >::Direction(), PhQ::Displacement< NumericType >::Direction(), PhQ::Force< NumericType >::Direction(), PhQ::HeatFlux< NumericType >::Direction(), PhQ::Position< NumericType >::Direction(), PhQ::TemperatureGradient< NumericType >::Direction(), PhQ::Traction< NumericType >::Direction(), PhQ::VectorArea< NumericType >::Direction(), PhQ::Velocity< NumericType >::Direction(), PhQ::DimensionalVector< UnitType, NumericType >::JSON(), PhQ::Acceleration< NumericType >::Magnitude(), PhQ::Displacement< NumericType >::Magnitude(), PhQ::Force< NumericType >::Magnitude(), PhQ::HeatFlux< NumericType >::Magnitude(), PhQ::Position< NumericType >::Magnitude(), PhQ::TemperatureGradient< NumericType >::Magnitude(), PhQ::Traction< NumericType >::Magnitude(), PhQ::VectorArea< NumericType >::Magnitude(), PhQ::Velocity< NumericType >::Magnitude(), PhQ::DimensionalVector< UnitType, NumericType >::MutableValue(), PhQ::Acceleration< NumericType >::operator*(), PhQ::Displacement< NumericType >::operator*(), PhQ::Force< NumericType >::operator*(), PhQ::HeatFlux< NumericType >::operator*(), PhQ::Position< NumericType >::operator*(), PhQ::TemperatureGradient< NumericType >::operator*(), PhQ::Traction< NumericType >::operator*(), PhQ::VectorArea< NumericType >::operator*(), PhQ::Velocity< NumericType >::operator*(), PhQ::Acceleration< NumericType >::operator*=(), PhQ::Displacement< NumericType >::operator*=(), PhQ::Force< NumericType >::operator*=(), PhQ::HeatFlux< NumericType >::operator*=(), PhQ::Position< NumericType >::operator*=(), PhQ::TemperatureGradient< NumericType >::operator*=(), PhQ::Traction< NumericType >::operator*=(), PhQ::VectorArea< NumericType >::operator*=(), PhQ::Velocity< NumericType >::operator*=(), PhQ::Acceleration< NumericType >::operator+(), PhQ::Displacement< NumericType >::operator+(), PhQ::Position< NumericType >::operator+(), PhQ::Force< NumericType >::operator+(), PhQ::HeatFlux< NumericType >::operator+(), PhQ::Position< NumericType >::operator+(), PhQ::TemperatureGradient< NumericType >::operator+(), PhQ::Traction< NumericType >::operator+(), PhQ::VectorArea< NumericType >::operator+(), PhQ::Velocity< NumericType >::operator+(), PhQ::Acceleration< NumericType >::operator+=(), PhQ::Displacement< NumericType >::operator+=(), PhQ::Position< NumericType >::operator+=(), PhQ::Force< NumericType >::operator+=(), PhQ::HeatFlux< NumericType >::operator+=(), PhQ::Position< NumericType >::operator+=(), PhQ::TemperatureGradient< NumericType >::operator+=(), PhQ::Traction< NumericType >::operator+=(), PhQ::VectorArea< NumericType >::operator+=(), PhQ::Velocity< NumericType >::operator+=(), PhQ::Acceleration< NumericType >::operator-(), PhQ::Displacement< NumericType >::operator-(), PhQ::Position< NumericType >::operator-(), PhQ::Force< NumericType >::operator-(), PhQ::HeatFlux< NumericType >::operator-(), PhQ::Position< NumericType >::operator-(), PhQ::TemperatureGradient< NumericType >::operator-(), PhQ::Traction< NumericType >::operator-(), PhQ::VectorArea< NumericType >::operator-(), PhQ::Velocity< NumericType >::operator-(), PhQ::Acceleration< NumericType >::operator-=(), PhQ::Displacement< NumericType >::operator-=(), PhQ::Position< NumericType >::operator-=(), PhQ::Force< NumericType >::operator-=(), PhQ::HeatFlux< NumericType >::operator-=(), PhQ::Position< NumericType >::operator-=(), PhQ::TemperatureGradient< NumericType >::operator-=(), PhQ::Traction< NumericType >::operator-=(), PhQ::VectorArea< NumericType >::operator-=(), PhQ::Velocity< NumericType >::operator-=(), PhQ::Acceleration< NumericType >::operator/(), PhQ::Displacement< NumericType >::operator/(), PhQ::Force< NumericType >::operator/(), PhQ::HeatFlux< NumericType >::operator/(), PhQ::Position< NumericType >::operator/(), PhQ::TemperatureGradient< NumericType >::operator/(), PhQ::Traction< NumericType >::operator/(), PhQ::VectorArea< NumericType >::operator/(), PhQ::Velocity< NumericType >::operator/(), PhQ::Acceleration< NumericType >::operator/=(), PhQ::Displacement< NumericType >::operator/=(), PhQ::Force< NumericType >::operator/=(), PhQ::HeatFlux< NumericType >::operator/=(), PhQ::Position< NumericType >::operator/=(), PhQ::TemperatureGradient< NumericType >::operator/=(), PhQ::Traction< NumericType >::operator/=(), PhQ::VectorArea< NumericType >::operator/=(), PhQ::Velocity< NumericType >::operator/=(), PhQ::Acceleration< NumericType >::operator=(), PhQ::DimensionalVector< UnitType, NumericType >::operator=(), PhQ::Displacement< NumericType >::operator=(), PhQ::Force< NumericType >::operator=(), PhQ::HeatFlux< NumericType >::operator=(), PhQ::Position< NumericType >::operator=(), PhQ::TemperatureGradient< NumericType >::operator=(), PhQ::Traction< NumericType >::operator=(), PhQ::VectorArea< NumericType >::operator=(), PhQ::Velocity< NumericType >::operator=(), PhQ::DimensionalVector< UnitType, NumericType >::Print(), PhQ::DimensionalVector< UnitType, NumericType >::SetValue(), PhQ::DimensionalVector< UnitType, NumericType >::StaticValue(), PhQ::DimensionalVector< UnitType, NumericType >::Value(), PhQ::DimensionalVector< UnitType, NumericType >::Value(), PhQ::Acceleration< NumericType >::x(), PhQ::Displacement< NumericType >::x(), PhQ::Force< NumericType >::x(), PhQ::HeatFlux< NumericType >::x(), PhQ::Position< NumericType >::x(), PhQ::TemperatureGradient< NumericType >::x(), PhQ::Traction< NumericType >::x(), PhQ::VectorArea< NumericType >::x(), PhQ::Velocity< NumericType >::x(), PhQ::DimensionalVector< UnitType, NumericType >::XML(), PhQ::Acceleration< NumericType >::y(), PhQ::Displacement< NumericType >::y(), PhQ::Force< NumericType >::y(), PhQ::HeatFlux< NumericType >::y(), PhQ::Position< NumericType >::y(), PhQ::TemperatureGradient< NumericType >::y(), PhQ::Traction< NumericType >::y(), PhQ::VectorArea< NumericType >::y(), PhQ::Velocity< NumericType >::y(), PhQ::DimensionalVector< UnitType, NumericType >::YAML(), PhQ::Acceleration< NumericType >::z(), PhQ::Displacement< NumericType >::z(), PhQ::Force< NumericType >::z(), PhQ::HeatFlux< NumericType >::z(), PhQ::Position< NumericType >::z(), PhQ::TemperatureGradient< NumericType >::z(), PhQ::Traction< NumericType >::z(), PhQ::VectorArea< NumericType >::z(), and PhQ::Velocity< NumericType >::z().
The documentation for this class was generated from the following files:
PhQ/Angle.hpp
PhQ/Displacement.hpp
PhQ/Position.hpp
PhQ/Velocity.hpp