Physical Quantities (PhQ): PhQ::Dimension::Temperature Class Reference
PhQ::Dimension::Temperature Class Reference
Base physical dimension of temperature. Typically denoted "Θ". One of seven independent base physical dimensions that form the physical dimension set of any unit of measure or physical quantity.
#include "Temperature.hpp"
Public Member Functions
constexpr Temperature ()=default
Default constructor. Constructs a base physical dimension of temperature with a value of zero.
constexpr Temperature (const int8_t value)
Constructor. Constructs a base physical dimension of temperature with a given value.
~Temperature () noexcept=default
Destructor. Destroys this base physical dimension of temperature.
constexpr Temperature (const Temperature &other)=default
Copy constructor. Constructs a base physical dimension of temperature by copying another one.
constexpr Temperature & operator= (const Temperature &other)=default
Copy assignment operator. Assigns the value of this base physical dimension of temperature by copying from another one.
constexpr Temperature (Temperature &&other) noexcept=default
Move constructor. Constructs a base physical dimension of temperature by moving another one.
constexpr Temperature & operator= (Temperature &&other) noexcept=default
Move assignment operator. Assigns the value of this base physical dimension of temperature by moving another one.
constexpr int8_t Value () const noexcept
Value of this base physical dimension.
std::string Print () const noexcept
Prints this base physical dimension as a string.
Static Public Member Functions
static std::string_view Abbreviation () noexcept
Abbreviation of this base physical dimension.
static std::string_view Label () noexcept
Label of this base physical dimension.
Private Attributes
int8_t value {0}
Value of this base physical dimension.
Detailed Description
Base physical dimension of temperature. Typically denoted "Θ". One of seven independent base physical dimensions that form the physical dimension set of any unit of measure or physical quantity.
Definition at line 42 of file Temperature.hpp.
Constructor & Destructor Documentation
Temperature() [1/4]
constexpr PhQ::Dimension::Temperature::Temperature () constexpr default
Default constructor. Constructs a base physical dimension of temperature with a value of zero.
Temperature() [2/4]
constexpr PhQ::Dimension::Temperature::Temperature (const int8_t value) inline explicit constexpr
Constructor. Constructs a base physical dimension of temperature with a given value.
Definition at line 49 of file Temperature.hpp.
~Temperature()
PhQ::Dimension::Temperature::~Temperature () default noexcept
Destructor. Destroys this base physical dimension of temperature.
Temperature() [3/4]
constexpr PhQ::Dimension::Temperature::Temperature (const Temperature & other) constexpr default
Copy constructor. Constructs a base physical dimension of temperature by copying another one.
Temperature() [4/4]
constexpr PhQ::Dimension::Temperature::Temperature (Temperature && other) constexpr default noexcept
Move constructor. Constructs a base physical dimension of temperature by moving another one.
Member Function Documentation
Abbreviation()
static std::string_view PhQ::Dimension::Temperature::Abbreviation () inline static noexcept
Abbreviation of this base physical dimension.
Definition at line 76 of file Temperature.hpp.
Referenced by Print().
Label()
static std::string_view PhQ::Dimension::Temperature::Label () inline static noexcept
Label of this base physical dimension.
Definition at line 81 of file Temperature.hpp.
Referenced by PhQ::Dimensions::JSON(), PhQ::Dimensions::XML(), and PhQ::Dimensions::YAML().
operator=() [1/2]
constexpr Temperature& PhQ::Dimension::Temperature::operator= (const Temperature & other) constexpr default
Copy assignment operator. Assigns the value of this base physical dimension of temperature by copying from another one.
operator=() [2/2]
constexpr Temperature& PhQ::Dimension::Temperature::operator= (Temperature && other) constexpr default noexcept
Move assignment operator. Assigns the value of this base physical dimension of temperature by moving another one.
Print()
std::string PhQ::Dimension::Temperature::Print () const inline noexcept
Prints this base physical dimension as a string.
Definition at line 86 of file Temperature.hpp.
References Abbreviation(), and value.
Referenced by PhQ::Dimension::operator<<(), and PhQ::Dimensions::Print().
Value()
constexpr int8_t PhQ::Dimension::Temperature::Value () const inline constexpr noexcept
Value of this base physical dimension.
Definition at line 71 of file Temperature.hpp.
References value.
Referenced by PhQ::Dimensions::JSON(), PhQ::Dimensions::XML(), and PhQ::Dimensions::YAML().
Member Data Documentation
value
int8_t PhQ::Dimension::Temperature::value {0} private
Value of this base physical dimension.
Definition at line 101 of file Temperature.hpp.
Referenced by Print(), and Value().
The documentation for this class was generated from the following file:
PhQ/Dimension/Temperature.hpp