Physical Quantities: PhQ::StrainRate< NumericType > Class Template Reference
PhQ::StrainRate< NumericType > Class Template Reference
Three-dimensional Euclidean strain rate symmetric dyadic tensor. Time rate of change of strain. Contains six components in Cartesian coordinates: xx, xy = yx, xz = zx, yy, yz = zy, and zz. For the scalar components or resultants of a strain rate tensor, see PhQ::ScalarStrainRate. See also PhQ::Strain, PhQ::Time, and PhQ::Frequency.
#include "StrainRate.hpp"
Public Member Functions
StrainRate ()=default
Default constructor. Constructs a strain rate tensor with an uninitialized value.
StrainRate (const SymmetricDyad< NumericType > &value, Unit::Frequency unit)
Constructor. Constructs a strain rate tensor with a given value expressed in a given frequency unit.
StrainRate (const ScalarStrainRate< NumericType > &xx, const ScalarStrainRate< NumericType > &xy, const ScalarStrainRate< NumericType > &xz, const ScalarStrainRate< NumericType > &yy, const ScalarStrainRate< NumericType > &yz, const ScalarStrainRate< NumericType > &zz)
Constructor. Constructs a strain rate tensor from a given set of scalar strain rate components.
constexpr StrainRate (const Strain< NumericType > &strain, const Time< NumericType > &time)
Constructor. Constructs a strain rate tensor from a given strain tensor and time using the definition of the strain rate tensor.
constexpr StrainRate (const Strain< NumericType > &strain, const Frequency< NumericType > &frequency)
Constructor. Constructs a strain rate tensor from a given strain tensor and frequency using the definition of the strain rate tensor.
constexpr StrainRate (const VelocityGradient< NumericType > &velocity_gradient)
Constructor. Constructs a strain rate tensor from a given velocity gradient using the definition of the strain rate tensor.
~StrainRate () noexcept=default
Destructor. Destroys this strain rate tensor.
constexpr StrainRate (const StrainRate< NumericType > &other)=default
Copy constructor. Constructs a strain rate tensor by copying another one.
template<typename OtherNumericType >
constexpr StrainRate (const StrainRate< OtherNumericType > &other)
Copy constructor. Constructs a strain rate tensor by copying another one.
constexpr StrainRate (StrainRate< NumericType > &&other) noexcept=default
Move constructor. Constructs a strain rate tensor by moving another one.
constexpr StrainRate< NumericType > & operator= (const StrainRate< NumericType > &other)=default
Copy assignment operator. Assigns this strain rate tensor by copying another one.
template<typename OtherNumericType >
constexpr StrainRate< NumericType > & operator= (const StrainRate< OtherNumericType > &other)
Copy assignment operator. Assigns this strain rate tensor by copying another one.
constexpr StrainRate< NumericType > & operator= (StrainRate< NumericType > &&other) noexcept=default
Move assignment operator. Assigns this strain rate tensor by moving another one.
constexpr ScalarStrainRate< NumericType > xx () const noexcept
Returns the xx Cartesian component of this strain rate tensor.
constexpr ScalarStrainRate< NumericType > xy () const noexcept
Returns the xy = yx Cartesian component of this strain rate tensor.
constexpr ScalarStrainRate< NumericType > xz () const noexcept
Returns the xz = zx Cartesian component of this strain rate tensor.
constexpr ScalarStrainRate< NumericType > yx () const noexcept
Returns the yx = xy Cartesian component of this strain rate tensor.
constexpr ScalarStrainRate< NumericType > yy () const noexcept
Returns the yy Cartesian component of this strain rate tensor.
constexpr ScalarStrainRate< NumericType > yz () const noexcept
Returns the yz = zy Cartesian component of this strain rate tensor.
constexpr ScalarStrainRate< NumericType > zx () const noexcept
Returns the zx = xz Cartesian component of this strain rate tensor.
constexpr ScalarStrainRate< NumericType > zy () const noexcept
Returns the zy = yz Cartesian component of this strain rate tensor.
constexpr ScalarStrainRate< NumericType > zz () const noexcept
Returns the zz Cartesian component of this strain rate tensor.
constexpr StrainRate operator+ (const StrainRate< NumericType > &strain_rate) const
constexpr StrainRate< NumericType > operator- (const StrainRate< NumericType > &strain_rate) const
constexpr StrainRate< NumericType > operator* (const NumericType number) const
constexpr Strain< NumericType > operator* (const Time< NumericType > &time) const
constexpr StrainRate< NumericType > operator/ (const NumericType number) const
constexpr Strain< NumericType > operator/ (const Frequency< NumericType > &frequency) const
constexpr void operator+= (const StrainRate< NumericType > &strain_rate) noexcept
constexpr void operator-= (const StrainRate< NumericType > &strain_rate) noexcept
constexpr void operator*= (const NumericType number) noexcept
constexpr void operator/= (const NumericType number) noexcept
constexpr const PhQ::SymmetricDyad< NumericType > & Value () const noexcept
Value of this physical quantity expressed in its standard unit of measure.
PhQ::SymmetricDyad< NumericType > Value (const UnitType unit) const
Value of this physical quantity expressed in a given unit of measure.
template<UnitType NewUnit>
constexpr PhQ::SymmetricDyad< NumericType > StaticValue () const
Value of this physical quantity expressed in a given unit of measure. This method can be evaluated statically at compile-time.
constexpr PhQ::SymmetricDyad< NumericType > & MutableValue () noexcept
Returns the value of this physical quantity expressed in its standard unit of measure as a mutable value.
constexpr void SetValue (const PhQ::SymmetricDyad< NumericType > &value) noexcept
Sets the value of this physical quantity expressed in its standard unit of measure to the given value.
std::string Print () const
Prints this physical quantity as a string. This physical quantity's value is expressed in its standard unit of measure.
std::string Print (const UnitType unit) const
Prints this physical quantity as a string. This physical quantity's value is expressed in the given unit of measure.
std::string JSON () const
Serializes this physical quantity as a JSON message. This physical quantity's value is expressed in its standard unit of measure.
std::string JSON (const UnitType unit) const
Serializes this physical quantity as a JSON message. This physical quantity's value is expressed in the given unit of measure.
std::string XML () const
Serializes this physical quantity as an XML message. This physical quantity's value is expressed in its standard unit of measure.
std::string XML (const UnitType unit) const
Serializes this physical quantity as an XML message. This physical quantity's value is expressed in the given unit of measure.
std::string YAML () const
Serializes this physical quantity as a YAML message. This physical quantity's value is expressed in its standard unit of measure.
std::string YAML (const UnitType unit) const
Serializes this physical quantity as a YAML message. This physical quantity's value is expressed in the given unit of measure.
Static Public Member Functions
static constexpr StrainRate< NumericType > Zero ()
Statically creates a strain rate tensor of zero.
template<Unit::Frequency Unit>
static constexpr StrainRate< NumericType > Create (const NumericType xx, const NumericType xy, const NumericType xz, const NumericType yy, const NumericType yz, const NumericType zz)
Statically creates a strain rate tensor from the given xx, xy, xz, yy, yz, and zz Cartesian components expressed in a given frequency unit.
template<Unit::Frequency Unit>
static constexpr StrainRate< NumericType > Create (const std::array< NumericType, 6 > &xx_xy_xz_yy_yz_zz)
Statically creates a strain rate tensor from the given xx, xy, xz, yy, yz, and zz Cartesian components expressed in a given frequency unit.
template<Unit::Frequency Unit>
static constexpr StrainRate< NumericType > Create (const SymmetricDyad< NumericType > &value)
Statically creates a strain rate tensor with a given value expressed in a given frequency unit.
static constexpr const PhQ::Dimensions & Dimensions ()
Physical dimension set of this physical quantity.
static constexpr UnitType Unit ()
Standard unit of measure for this physical quantity. This physical quantity's value is stored internally in this unit of measure.
Protected Attributes
PhQ::SymmetricDyad< NumericType > value
Value of this physical quantity expressed in its standard unit of measure.
Private Member Functions
constexpr StrainRate (const SymmetricDyad< NumericType > &value)
Constructor. Constructs a strain rate tensor with a given value expressed in the standard frequency unit.
Detailed Description
template<typename NumericType = double>
class PhQ::StrainRate< NumericType >
Three-dimensional Euclidean strain rate symmetric dyadic tensor. Time rate of change of strain. Contains six components in Cartesian coordinates: xx, xy = yx, xz = zx, yy, yz = zy, and zz. For the scalar components or resultants of a strain rate tensor, see PhQ::ScalarStrainRate. See also PhQ::Strain, PhQ::Time, and PhQ::Frequency.
Definition at line 51 of file StrainRate.hpp.
Constructor & Destructor Documentation
StrainRate() [1/10]
template<typename NumericType = double> PhQ::StrainRate< NumericType >::StrainRate () default
Default constructor. Constructs a strain rate tensor with an uninitialized value.
StrainRate() [2/10]
template<typename NumericType = double> PhQ::StrainRate< NumericType >::StrainRate (const SymmetricDyad< NumericType > & value, Unit::Frequency unit) inline
Constructor. Constructs a strain rate tensor with a given value expressed in a given frequency unit.
Definition at line 58 of file StrainRate.hpp.
StrainRate() [3/10]
template<typename NumericType = double> PhQ::StrainRate< NumericType >::StrainRate (const ScalarStrainRate< NumericType > & xx, const ScalarStrainRate< NumericType > & xy, const ScalarStrainRate< NumericType > & xz, const ScalarStrainRate< NumericType > & yy, const ScalarStrainRate< NumericType > & yz, const ScalarStrainRate< NumericType > & zz) inline
Constructor. Constructs a strain rate tensor from a given set of scalar strain rate components.
Definition at line 63 of file StrainRate.hpp.
References PhQ::StrainRate< NumericType >::xx(), PhQ::StrainRate< NumericType >::xy(), PhQ::StrainRate< NumericType >::xz(), PhQ::StrainRate< NumericType >::yy(), PhQ::StrainRate< NumericType >::yz(), and PhQ::StrainRate< NumericType >::zz().
StrainRate() [4/10]
template<typename NumericType = double> constexpr PhQ::StrainRate< NumericType >::StrainRate (const Strain< NumericType > & strain, const Time< NumericType > & time) inline constexpr
Constructor. Constructs a strain rate tensor from a given strain tensor and time using the definition of the strain rate tensor.
Definition at line 71 of file StrainRate.hpp.
StrainRate() [5/10]
template<typename NumericType = double> constexpr PhQ::StrainRate< NumericType >::StrainRate (const Strain< NumericType > & strain, const Frequency< NumericType > & frequency) inline constexpr
Constructor. Constructs a strain rate tensor from a given strain tensor and frequency using the definition of the strain rate tensor.
Definition at line 76 of file StrainRate.hpp.
StrainRate() [6/10]
template<typename NumericType > constexpr PhQ::StrainRate< NumericType >::StrainRate (const VelocityGradient< NumericType > & velocity_gradient) inline explicit constexpr
Constructor. Constructs a strain rate tensor from a given velocity gradient using the definition of the strain rate tensor.
Definition at line 300 of file VelocityGradient.hpp.
References PhQ::DimensionalDyad< UnitType, NumericType >::Value().
~StrainRate()
template<typename NumericType = double> PhQ::StrainRate< NumericType >::~StrainRate () default noexcept
Destructor. Destroys this strain rate tensor.
StrainRate() [7/10]
template<typename NumericType = double> constexpr PhQ::StrainRate< NumericType >::StrainRate (const StrainRate< NumericType > & other) constexpr default
Copy constructor. Constructs a strain rate tensor by copying another one.
StrainRate() [8/10]
template<typename NumericType = double> template<typename OtherNumericType > constexpr PhQ::StrainRate< NumericType >::StrainRate (const StrainRate< OtherNumericType > & other) inline explicit constexpr
Copy constructor. Constructs a strain rate tensor by copying another one.
Definition at line 91 of file StrainRate.hpp.
StrainRate() [9/10]
template<typename NumericType = double> constexpr PhQ::StrainRate< NumericType >::StrainRate (StrainRate< NumericType > && other) constexpr default noexcept
Move constructor. Constructs a strain rate tensor by moving another one.
StrainRate() [10/10]
template<typename NumericType = double> constexpr PhQ::StrainRate< NumericType >::StrainRate (const SymmetricDyad< NumericType > & value) inline explicit constexpr private
Constructor. Constructs a strain rate tensor with a given value expressed in the standard frequency unit.
Definition at line 233 of file StrainRate.hpp.
Member Function Documentation
Create() [1/3]
template<typename NumericType = double> template<Unit::Frequency Unit> static constexpr StrainRate< NumericType > PhQ::StrainRate< NumericType >::Create (const NumericType xx, const NumericType xy, const NumericType xz, const NumericType yy, const NumericType yz, const NumericType zz) inline static constexpr
Statically creates a strain rate tensor from the given xx, xy, xz, yy, yz, and zz Cartesian components expressed in a given frequency unit.
Definition at line 118 of file StrainRate.hpp.
References PhQ::StrainRate< NumericType >::xx(), PhQ::StrainRate< NumericType >::xy(), PhQ::StrainRate< NumericType >::xz(), PhQ::StrainRate< NumericType >::yy(), PhQ::StrainRate< NumericType >::yz(), and PhQ::StrainRate< NumericType >::zz().
Create() [2/3]
template<typename NumericType = double> template<Unit::Frequency Unit> static constexpr StrainRate< NumericType > PhQ::StrainRate< NumericType >::Create (const std::array< NumericType, 6 > & xx_xy_xz_yy_yz_zz) inline static constexpr
Statically creates a strain rate tensor from the given xx, xy, xz, yy, yz, and zz Cartesian components expressed in a given frequency unit.
Definition at line 129 of file StrainRate.hpp.
Create() [3/3]
template<typename NumericType = double> template<Unit::Frequency Unit> static constexpr StrainRate< NumericType > PhQ::StrainRate< NumericType >::Create (const SymmetricDyad< NumericType > & value) inline static constexpr
Statically creates a strain rate tensor with a given value expressed in a given frequency unit.
Definition at line 139 of file StrainRate.hpp.
References PhQ::DimensionalSymmetricDyad< UnitType, NumericType >::value.
Dimensions()
template<typename UnitType , typename NumericType = double> static constexpr const PhQ::Dimensions & PhQ::DimensionalSymmetricDyad< UnitType, NumericType >::Dimensions () inline static constexpr inherited
Physical dimension set of this physical quantity.
Definition at line 50 of file DimensionalSymmetricDyad.hpp.
JSON() [1/2]
template<typename UnitType , typename NumericType = double> std::string PhQ::DimensionalSymmetricDyad< UnitType, NumericType >::JSON () const inline inherited
Serializes this physical quantity as a JSON message. This physical quantity's value is expressed in its standard unit of measure.
Definition at line 103 of file DimensionalSymmetricDyad.hpp.
References PhQ::Abbreviation(), and PhQ::DimensionalSymmetricDyad< UnitType, NumericType >::value.
Referenced by PhQ::DimensionalSymmetricDyad< UnitType, NumericType >::JSON().
JSON() [2/2]
template<typename UnitType , typename NumericType = double> std::string PhQ::DimensionalSymmetricDyad< UnitType, NumericType >::JSON (const UnitType unit) const inline inherited
Serializes this physical quantity as a JSON message. This physical quantity's value is expressed in the given unit of measure.
Definition at line 113 of file DimensionalSymmetricDyad.hpp.
References PhQ::Abbreviation(), PhQ::DimensionalSymmetricDyad< UnitType, NumericType >::JSON(), and PhQ::DimensionalSymmetricDyad< UnitType, NumericType >::Value().
MutableValue()
template<typename UnitType , typename NumericType = double> constexpr PhQ::SymmetricDyad< NumericType > & PhQ::DimensionalSymmetricDyad< UnitType, NumericType >::MutableValue () inline constexpr noexcept inherited
Returns the value of this physical quantity expressed in its standard unit of measure as a mutable value.
Definition at line 79 of file DimensionalSymmetricDyad.hpp.
References PhQ::DimensionalSymmetricDyad< UnitType, NumericType >::value.
operator*() [1/2]
template<typename NumericType = double> constexpr StrainRate< NumericType > PhQ::StrainRate< NumericType >::operator* (const NumericType number) const inline constexpr
Definition at line 198 of file StrainRate.hpp.
References PhQ::DimensionalSymmetricDyad< UnitType, NumericType >::value.
operator*() [2/2]
template<typename NumericType = double> constexpr Strain< NumericType > PhQ::StrainRate< NumericType >::operator* (const Time< NumericType > & time) const inline constexpr
Definition at line 202 of file StrainRate.hpp.
operator*=()
template<typename NumericType = double> constexpr void PhQ::StrainRate< NumericType >::operator*= (const NumericType number) inline constexpr noexcept
Definition at line 222 of file StrainRate.hpp.
References PhQ::DimensionalSymmetricDyad< UnitType, NumericType >::value.
operator+()
template<typename NumericType = double> constexpr StrainRate PhQ::StrainRate< NumericType >::operator+ (const StrainRate< NumericType > & strain_rate) const inline constexpr
Definition at line 190 of file StrainRate.hpp.
References PhQ::DimensionalSymmetricDyad< UnitType, NumericType >::value.
operator+=()
template<typename NumericType = double> constexpr void PhQ::StrainRate< NumericType >::operator+= (const StrainRate< NumericType > & strain_rate) inline constexpr noexcept
Definition at line 214 of file StrainRate.hpp.
References PhQ::DimensionalSymmetricDyad< UnitType, NumericType >::value.
operator-()
template<typename NumericType = double> constexpr StrainRate< NumericType > PhQ::StrainRate< NumericType >::operator- (const StrainRate< NumericType > & strain_rate) const inline constexpr
Definition at line 194 of file StrainRate.hpp.
References PhQ::DimensionalSymmetricDyad< UnitType, NumericType >::value.
operator-=()
template<typename NumericType = double> constexpr void PhQ::StrainRate< NumericType >::operator-= (const StrainRate< NumericType > & strain_rate) inline constexpr noexcept
Definition at line 218 of file StrainRate.hpp.
References PhQ::DimensionalSymmetricDyad< UnitType, NumericType >::value.
operator/() [1/2]
template<typename NumericType = double> constexpr Strain< NumericType > PhQ::StrainRate< NumericType >::operator/ (const Frequency< NumericType > & frequency) const inline constexpr
Definition at line 210 of file StrainRate.hpp.
operator/() [2/2]
template<typename NumericType = double> constexpr StrainRate< NumericType > PhQ::StrainRate< NumericType >::operator/ (const NumericType number) const inline constexpr
Definition at line 206 of file StrainRate.hpp.
References PhQ::DimensionalSymmetricDyad< UnitType, NumericType >::value.
operator/=()
template<typename NumericType = double> constexpr void PhQ::StrainRate< NumericType >::operator/= (const NumericType number) inline constexpr noexcept
Definition at line 226 of file StrainRate.hpp.
References PhQ::DimensionalSymmetricDyad< UnitType, NumericType >::value.
operator=() [1/3]
template<typename NumericType = double> constexpr StrainRate< NumericType > & PhQ::StrainRate< NumericType >::operator= (const StrainRate< NumericType > & other) constexpr default
Copy assignment operator. Assigns this strain rate tensor by copying another one.
operator=() [2/3]
template<typename NumericType = double> template<typename OtherNumericType > constexpr StrainRate< NumericType > & PhQ::StrainRate< NumericType >::operator= (const StrainRate< OtherNumericType > & other) inline constexpr
Copy assignment operator. Assigns this strain rate tensor by copying another one.
Definition at line 102 of file StrainRate.hpp.
References PhQ::DimensionalSymmetricDyad< UnitType, NumericType >::Value(), and PhQ::DimensionalSymmetricDyad< UnitType, NumericType >::value.
operator=() [3/3]
template<typename NumericType = double> constexpr StrainRate< NumericType > & PhQ::StrainRate< NumericType >::operator= (StrainRate< NumericType > && other) constexpr default noexcept
Move assignment operator. Assigns this strain rate tensor by moving another one.
Print() [1/2]
template<typename UnitType , typename NumericType = double> std::string PhQ::DimensionalSymmetricDyad< UnitType, NumericType >::Print () const inline inherited
Prints this physical quantity as a string. This physical quantity's value is expressed in its standard unit of measure.
Definition at line 91 of file DimensionalSymmetricDyad.hpp.
References PhQ::Abbreviation(), and PhQ::DimensionalSymmetricDyad< UnitType, NumericType >::value.
Referenced by PhQ::operator<<(), PhQ::operator<<(), and PhQ::operator<<().
Print() [2/2]
template<typename UnitType , typename NumericType = double> std::string PhQ::DimensionalSymmetricDyad< UnitType, NumericType >::Print (const UnitType unit) const inline inherited
Prints this physical quantity as a string. This physical quantity's value is expressed in the given unit of measure.
Definition at line 97 of file DimensionalSymmetricDyad.hpp.
References PhQ::Abbreviation(), and PhQ::DimensionalSymmetricDyad< UnitType, NumericType >::Value().
SetValue()
template<typename UnitType , typename NumericType = double> constexpr void PhQ::DimensionalSymmetricDyad< UnitType, NumericType >::SetValue (const PhQ::SymmetricDyad< NumericType > & value) inline constexpr noexcept inherited
Sets the value of this physical quantity expressed in its standard unit of measure to the given value.
Definition at line 85 of file DimensionalSymmetricDyad.hpp.
References PhQ::DimensionalSymmetricDyad< UnitType, NumericType >::value.
StaticValue()
template<typename UnitType , typename NumericType = double> template<UnitType NewUnit> constexpr PhQ::SymmetricDyad< NumericType > PhQ::DimensionalSymmetricDyad< UnitType, NumericType >::StaticValue () const inline constexpr inherited
Value of this physical quantity expressed in a given unit of measure. This method can be evaluated statically at compile-time.
Definition at line 73 of file DimensionalSymmetricDyad.hpp.
References PhQ::DimensionalSymmetricDyad< UnitType, NumericType >::value.
Unit()
template<typename UnitType , typename NumericType = double> static constexpr UnitType PhQ::DimensionalSymmetricDyad< UnitType, NumericType >::Unit () inline static constexpr inherited
Standard unit of measure for this physical quantity. This physical quantity's value is stored internally in this unit of measure.
Definition at line 56 of file DimensionalSymmetricDyad.hpp.
Value() [1/2]
template<typename UnitType , typename NumericType = double> constexpr const PhQ::SymmetricDyad< NumericType > & PhQ::DimensionalSymmetricDyad< UnitType, NumericType >::Value () const inline constexpr noexcept inherited
Value of this physical quantity expressed in its standard unit of measure.
Definition at line 61 of file DimensionalSymmetricDyad.hpp.
References PhQ::DimensionalSymmetricDyad< UnitType, NumericType >::value.
Referenced by PhQ::DimensionalSymmetricDyad< UnitType, NumericType >::JSON(), PhQ::DimensionalSymmetricDyad< UnitType, NumericType >::operator=(), PhQ::StrainRate< NumericType >::operator=(), PhQ::Stress< NumericType >::operator=(), PhQ::ThermalConductivity< NumericType >::operator=(), PhQ::operator==(), PhQ::operator==(), PhQ::operator==(), PhQ::operator==(), PhQ::PlanarHeatFlux< NumericType >::PlanarHeatFlux(), PhQ::PlanarTraction< NumericType >::PlanarTraction(), PhQ::DimensionalSymmetricDyad< UnitType, NumericType >::Print(), PhQ::ConstitutiveModel::ElasticIsotropicSolid< NumericType >::Strain(), PhQ::ConstitutiveModel::ElasticIsotropicSolid< NumericType >::Strain(), PhQ::ConstitutiveModel::ElasticIsotropicSolid< NumericType >::Strain(), PhQ::ConstitutiveModel::CompressibleNewtonianFluid< NumericType >::StrainRate(), PhQ::ConstitutiveModel::IncompressibleNewtonianFluid< NumericType >::StrainRate(), PhQ::ConstitutiveModel::CompressibleNewtonianFluid< NumericType >::StrainRate(), PhQ::ConstitutiveModel::IncompressibleNewtonianFluid< NumericType >::StrainRate(), PhQ::ConstitutiveModel::CompressibleNewtonianFluid< NumericType >::StrainRate(), PhQ::ConstitutiveModel::IncompressibleNewtonianFluid< NumericType >::StrainRate(), PhQ::ConstitutiveModel::CompressibleNewtonianFluid< NumericType >::Stress(), PhQ::ConstitutiveModel::IncompressibleNewtonianFluid< NumericType >::Stress(), PhQ::ConstitutiveModel::CompressibleNewtonianFluid< NumericType >::Stress(), PhQ::ConstitutiveModel::IncompressibleNewtonianFluid< NumericType >::Stress(), PhQ::ConstitutiveModel::CompressibleNewtonianFluid< NumericType >::Stress(), PhQ::ConstitutiveModel::IncompressibleNewtonianFluid< NumericType >::Stress(), PhQ::Traction< NumericType >::Traction(), PhQ::DimensionalSymmetricDyad< UnitType, NumericType >::XML(), and PhQ::DimensionalSymmetricDyad< UnitType, NumericType >::YAML().
Value() [2/2]
template<typename UnitType , typename NumericType = double> PhQ::SymmetricDyad< NumericType > PhQ::DimensionalSymmetricDyad< UnitType, NumericType >::Value (const UnitType unit) const inline inherited
Value of this physical quantity expressed in a given unit of measure.
Definition at line 66 of file DimensionalSymmetricDyad.hpp.
References PhQ::Convert(), and PhQ::DimensionalSymmetricDyad< UnitType, NumericType >::value.
XML() [1/2]
template<typename UnitType , typename NumericType = double> std::string PhQ::DimensionalSymmetricDyad< UnitType, NumericType >::XML () const inline inherited
Serializes this physical quantity as an XML message. This physical quantity's value is expressed in its standard unit of measure.
Definition at line 123 of file DimensionalSymmetricDyad.hpp.
References PhQ::Abbreviation(), and PhQ::DimensionalSymmetricDyad< UnitType, NumericType >::value.
Referenced by PhQ::DimensionalSymmetricDyad< UnitType, NumericType >::XML().
XML() [2/2]
template<typename UnitType , typename NumericType = double> std::string PhQ::DimensionalSymmetricDyad< UnitType, NumericType >::XML (const UnitType unit) const inline inherited
Serializes this physical quantity as an XML message. This physical quantity's value is expressed in the given unit of measure.
Definition at line 133 of file DimensionalSymmetricDyad.hpp.
References PhQ::Abbreviation(), PhQ::DimensionalSymmetricDyad< UnitType, NumericType >::Value(), and PhQ::DimensionalSymmetricDyad< UnitType, NumericType >::XML().
xx()
template<typename NumericType = double> constexpr ScalarStrainRate< NumericType > PhQ::StrainRate< NumericType >::xx () const inline constexpr noexcept
Returns the xx Cartesian component of this strain rate tensor.
Definition at line 146 of file StrainRate.hpp.
References PhQ::DimensionalSymmetricDyad< UnitType, NumericType >::value.
Referenced by PhQ::StrainRate< NumericType >::Create(), and PhQ::StrainRate< NumericType >::StrainRate().
xy()
template<typename NumericType = double> constexpr ScalarStrainRate< NumericType > PhQ::StrainRate< NumericType >::xy () const inline constexpr noexcept
Returns the xy = yx Cartesian component of this strain rate tensor.
Definition at line 151 of file StrainRate.hpp.
References PhQ::DimensionalSymmetricDyad< UnitType, NumericType >::value.
Referenced by PhQ::StrainRate< NumericType >::Create(), and PhQ::StrainRate< NumericType >::StrainRate().
xz()
template<typename NumericType = double> constexpr ScalarStrainRate< NumericType > PhQ::StrainRate< NumericType >::xz () const inline constexpr noexcept
Returns the xz = zx Cartesian component of this strain rate tensor.
Definition at line 156 of file StrainRate.hpp.
References PhQ::DimensionalSymmetricDyad< UnitType, NumericType >::value.
Referenced by PhQ::StrainRate< NumericType >::Create(), and PhQ::StrainRate< NumericType >::StrainRate().
YAML() [1/2]
template<typename UnitType , typename NumericType = double> std::string PhQ::DimensionalSymmetricDyad< UnitType, NumericType >::YAML () const inline inherited
Serializes this physical quantity as a YAML message. This physical quantity's value is expressed in its standard unit of measure.
Definition at line 143 of file DimensionalSymmetricDyad.hpp.
References PhQ::Abbreviation(), and PhQ::DimensionalSymmetricDyad< UnitType, NumericType >::value.
Referenced by PhQ::DimensionalSymmetricDyad< UnitType, NumericType >::YAML().
YAML() [2/2]
template<typename UnitType , typename NumericType = double> std::string PhQ::DimensionalSymmetricDyad< UnitType, NumericType >::YAML (const UnitType unit) const inline inherited
Serializes this physical quantity as a YAML message. This physical quantity's value is expressed in the given unit of measure.
Definition at line 153 of file DimensionalSymmetricDyad.hpp.
References PhQ::Abbreviation(), PhQ::DimensionalSymmetricDyad< UnitType, NumericType >::Value(), and PhQ::DimensionalSymmetricDyad< UnitType, NumericType >::YAML().
yx()
template<typename NumericType = double> constexpr ScalarStrainRate< NumericType > PhQ::StrainRate< NumericType >::yx () const inline constexpr noexcept
Returns the yx = xy Cartesian component of this strain rate tensor.
Definition at line 161 of file StrainRate.hpp.
References PhQ::DimensionalSymmetricDyad< UnitType, NumericType >::value.
yy()
template<typename NumericType = double> constexpr ScalarStrainRate< NumericType > PhQ::StrainRate< NumericType >::yy () const inline constexpr noexcept
Returns the yy Cartesian component of this strain rate tensor.
Definition at line 166 of file StrainRate.hpp.
References PhQ::DimensionalSymmetricDyad< UnitType, NumericType >::value.
Referenced by PhQ::StrainRate< NumericType >::Create(), and PhQ::StrainRate< NumericType >::StrainRate().
yz()
template<typename NumericType = double> constexpr ScalarStrainRate< NumericType > PhQ::StrainRate< NumericType >::yz () const inline constexpr noexcept
Returns the yz = zy Cartesian component of this strain rate tensor.
Definition at line 171 of file StrainRate.hpp.
References PhQ::DimensionalSymmetricDyad< UnitType, NumericType >::value.
Referenced by PhQ::StrainRate< NumericType >::Create(), and PhQ::StrainRate< NumericType >::StrainRate().
Zero()
template<typename NumericType = double> static constexpr StrainRate< NumericType > PhQ::StrainRate< NumericType >::Zero () inline static constexpr
Statically creates a strain rate tensor of zero.
Definition at line 111 of file StrainRate.hpp.
References PhQ::SymmetricDyad< NumericType >::Zero().
Referenced by PhQ::ConstitutiveModel::ElasticIsotropicSolid< NumericType >::StrainRate(), PhQ::ConstitutiveModel::ElasticIsotropicSolid< NumericType >::StrainRate(), and PhQ::ConstitutiveModel::ElasticIsotropicSolid< NumericType >::StrainRate().
zx()
template<typename NumericType = double> constexpr ScalarStrainRate< NumericType > PhQ::StrainRate< NumericType >::zx () const inline constexpr noexcept
Returns the zx = xz Cartesian component of this strain rate tensor.
Definition at line 176 of file StrainRate.hpp.
References PhQ::DimensionalSymmetricDyad< UnitType, NumericType >::value.
zy()
template<typename NumericType = double> constexpr ScalarStrainRate< NumericType > PhQ::StrainRate< NumericType >::zy () const inline constexpr noexcept
Returns the zy = yz Cartesian component of this strain rate tensor.
Definition at line 181 of file StrainRate.hpp.
References PhQ::DimensionalSymmetricDyad< UnitType, NumericType >::value.
zz()
template<typename NumericType = double> constexpr ScalarStrainRate< NumericType > PhQ::StrainRate< NumericType >::zz () const inline constexpr noexcept
Returns the zz Cartesian component of this strain rate tensor.
Definition at line 186 of file StrainRate.hpp.
References PhQ::DimensionalSymmetricDyad< UnitType, NumericType >::value.
Referenced by PhQ::StrainRate< NumericType >::Create(), and PhQ::StrainRate< NumericType >::StrainRate().
Member Data Documentation
value
template<typename UnitType , typename NumericType = double> PhQ::SymmetricDyad<NumericType> PhQ::DimensionalSymmetricDyad< UnitType, NumericType >::value protected inherited
Value of this physical quantity expressed in its standard unit of measure.
Definition at line 222 of file DimensionalSymmetricDyad.hpp.
Referenced by PhQ::StrainRate< NumericType >::Create(), PhQ::Stress< NumericType >::Create(), PhQ::ThermalConductivity< NumericType >::Create(), PhQ::DimensionalSymmetricDyad< UnitType, NumericType >::JSON(), PhQ::DimensionalSymmetricDyad< UnitType, NumericType >::MutableValue(), PhQ::StrainRate< NumericType >::operator*(), PhQ::Stress< NumericType >::operator*(), PhQ::ThermalConductivity< NumericType >::operator*(), PhQ::StrainRate< NumericType >::operator*=(), PhQ::Stress< NumericType >::operator*=(), PhQ::ThermalConductivity< NumericType >::operator*=(), PhQ::StrainRate< NumericType >::operator+(), PhQ::Stress< NumericType >::operator+(), PhQ::ThermalConductivity< NumericType >::operator+(), PhQ::StrainRate< NumericType >::operator+=(), PhQ::Stress< NumericType >::operator+=(), PhQ::ThermalConductivity< NumericType >::operator+=(), PhQ::StrainRate< NumericType >::operator-(), PhQ::Stress< NumericType >::operator-(), PhQ::ThermalConductivity< NumericType >::operator-(), PhQ::StrainRate< NumericType >::operator-=(), PhQ::Stress< NumericType >::operator-=(), PhQ::ThermalConductivity< NumericType >::operator-=(), PhQ::StrainRate< NumericType >::operator/(), PhQ::Stress< NumericType >::operator/(), PhQ::ThermalConductivity< NumericType >::operator/(), PhQ::StrainRate< NumericType >::operator/=(), PhQ::Stress< NumericType >::operator/=(), PhQ::ThermalConductivity< NumericType >::operator/=(), PhQ::DimensionalSymmetricDyad< UnitType, NumericType >::operator=(), PhQ::StrainRate< NumericType >::operator=(), PhQ::Stress< NumericType >::operator=(), PhQ::ThermalConductivity< NumericType >::operator=(), PhQ::DimensionalSymmetricDyad< UnitType, NumericType >::Print(), PhQ::DimensionalSymmetricDyad< UnitType, NumericType >::SetValue(), PhQ::DimensionalSymmetricDyad< UnitType, NumericType >::StaticValue(), PhQ::DimensionalSymmetricDyad< UnitType, NumericType >::Value(), PhQ::DimensionalSymmetricDyad< UnitType, NumericType >::Value(), PhQ::Stress< NumericType >::VonMises(), PhQ::DimensionalSymmetricDyad< UnitType, NumericType >::XML(), PhQ::StrainRate< NumericType >::xx(), PhQ::Stress< NumericType >::xx(), PhQ::ThermalConductivity< NumericType >::xx(), PhQ::StrainRate< NumericType >::xy(), PhQ::Stress< NumericType >::xy(), PhQ::ThermalConductivity< NumericType >::xy(), PhQ::StrainRate< NumericType >::xz(), PhQ::Stress< NumericType >::xz(), PhQ::ThermalConductivity< NumericType >::xz(), PhQ::DimensionalSymmetricDyad< UnitType, NumericType >::YAML(), PhQ::StrainRate< NumericType >::yx(), PhQ::Stress< NumericType >::yx(), PhQ::ThermalConductivity< NumericType >::yx(), PhQ::StrainRate< NumericType >::yy(), PhQ::Stress< NumericType >::yy(), PhQ::ThermalConductivity< NumericType >::yy(), PhQ::StrainRate< NumericType >::yz(), PhQ::Stress< NumericType >::yz(), PhQ::ThermalConductivity< NumericType >::yz(), PhQ::StrainRate< NumericType >::zx(), PhQ::Stress< NumericType >::zx(), PhQ::ThermalConductivity< NumericType >::zx(), PhQ::StrainRate< NumericType >::zy(), PhQ::Stress< NumericType >::zy(), PhQ::ThermalConductivity< NumericType >::zy(), PhQ::StrainRate< NumericType >::zz(), PhQ::Stress< NumericType >::zz(), and PhQ::ThermalConductivity< NumericType >::zz().
The documentation for this class was generated from the following files:
PhQ/Strain.hpp
PhQ/StrainRate.hpp
PhQ/VelocityGradient.hpp