Physical Quantities: PhQ::Dimension::Mass Class Reference
PhQ::Dimension::Mass Class Reference
Base physical dimension of mass. Typically denoted "M". One of seven independent base physical dimensions that form the physical dimension set of any unit of measure or physical quantity. Part of PhQ::Dimensions.
#include "Mass.hpp"
Public Member Functions
constexpr Mass ()=default
Default constructor. Constructs a base physical dimension of mass with a value of zero.
constexpr Mass (const int8_t value)
Constructor. Constructs a base physical dimension of mass with a given value.
~Mass () noexcept=default
Destructor. Destroys this base physical dimension of mass.
constexpr Mass (const Mass &other)=default
Copy constructor. Constructs a base physical dimension of mass by copying another one.
constexpr Mass & operator= (const Mass &other)=default
Copy assignment operator. Assigns the value of this base physical dimension of mass by copying from another one.
constexpr Mass (Mass &&other) noexcept=default
Move constructor. Constructs a base physical dimension of mass by moving another one.
constexpr Mass & operator= (Mass &&other) noexcept=default
Move assignment operator. Assigns the value of this base physical dimension of mass by moving another one.
constexpr int8_t Value () const noexcept
Value of this base physical dimension.
std::string Print () const noexcept
Prints this base physical dimension as a string.
Static Public Member Functions
static std::string_view Abbreviation () noexcept
Abbreviation of this base physical dimension.
static std::string_view Label () noexcept
Label of this base physical dimension.
Private Attributes
int8_t value {0}
Value of this base physical dimension.
Detailed Description
Base physical dimension of mass. Typically denoted "M". One of seven independent base physical dimensions that form the physical dimension set of any unit of measure or physical quantity. Part of PhQ::Dimensions.
Definition at line 40 of file Mass.hpp.
Constructor & Destructor Documentation
Mass() [1/4]
constexpr PhQ::Dimension::Mass::Mass () constexpr default
Default constructor. Constructs a base physical dimension of mass with a value of zero.
Mass() [2/4]
constexpr PhQ::Dimension::Mass::Mass (const int8_t value) inline explicit constexpr
Constructor. Constructs a base physical dimension of mass with a given value.
Definition at line 46 of file Mass.hpp.
~Mass()
PhQ::Dimension::Mass::~Mass () default noexcept
Destructor. Destroys this base physical dimension of mass.
Mass() [3/4]
constexpr PhQ::Dimension::Mass::Mass (const Mass & other) constexpr default
Copy constructor. Constructs a base physical dimension of mass by copying another one.
Mass() [4/4]
constexpr PhQ::Dimension::Mass::Mass (Mass && other) constexpr default noexcept
Move constructor. Constructs a base physical dimension of mass by moving another one.
Member Function Documentation
Abbreviation()
static std::string_view PhQ::Dimension::Mass::Abbreviation () inline static noexcept
Abbreviation of this base physical dimension.
Definition at line 71 of file Mass.hpp.
Referenced by Print().
Label()
static std::string_view PhQ::Dimension::Mass::Label () inline static noexcept
Label of this base physical dimension.
Definition at line 76 of file Mass.hpp.
Referenced by PhQ::Dimensions::JSON(), PhQ::Dimensions::XML(), and PhQ::Dimensions::YAML().
operator=() [1/2]
constexpr Mass & PhQ::Dimension::Mass::operator= (const Mass & other) constexpr default
Copy assignment operator. Assigns the value of this base physical dimension of mass by copying from another one.
operator=() [2/2]
constexpr Mass & PhQ::Dimension::Mass::operator= (Mass && other) constexpr default noexcept
Move assignment operator. Assigns the value of this base physical dimension of mass by moving another one.
Print()
std::string PhQ::Dimension::Mass::Print () const inline noexcept
Prints this base physical dimension as a string.
Definition at line 81 of file Mass.hpp.
References Abbreviation(), and value.
Referenced by PhQ::Dimension::operator<<(), and PhQ::Dimensions::Print().
Value()
constexpr int8_t PhQ::Dimension::Mass::Value () const inline constexpr noexcept
Value of this base physical dimension.
Definition at line 66 of file Mass.hpp.
References value.
Referenced by PhQ::Dimensions::JSON(), PhQ::Dimensions::XML(), and PhQ::Dimensions::YAML().
Member Data Documentation
value
int8_t PhQ::Dimension::Mass::value {0} private
Value of this base physical dimension.
Definition at line 96 of file Mass.hpp.
Referenced by Print(), and Value().
The documentation for this class was generated from the following file:
PhQ/Dimension/Mass.hpp