Physical Quantities: PhQ::VectorArea< NumericType > Class Template Reference
PhQ::VectorArea< NumericType > Class Template Reference
Three-dimensional Euclidean vector area. Contains three components in Cartesian coordinates: x, y, and z. A vector area is an oriented area; it is the three-dimensional Euclidean vector representation of an area. Any closed surface has a vector area: it is the surface integral of its surface normal direction. For the scalar components of a vector area or for the magnitude of a vector area, see PhQ::Area.
#include "VectorArea.hpp"
Public Member Functions
VectorArea ()=default
Default constructor. Constructs a vector area with an uninitialized value.
VectorArea (const Vector< NumericType > &value, const Unit::Area unit)
Constructor. Constructs a vector area with a given value expressed in a given area unit.
VectorArea (const Area< NumericType > &x, const Area< NumericType > &y, const Area< NumericType > &z)
Constructor. Constructs a vector area from a given set of area components.
constexpr VectorArea (const Area< NumericType > &area, const Direction< NumericType > &direction)
Constructor. Constructs a vector area from a given area and direction.
~VectorArea () noexcept=default
Destructor. Destroys this vector area.
constexpr VectorArea (const VectorArea< NumericType > &other)=default
Copy constructor. Constructs a vector area by copying another one.
template<typename OtherNumericType >
constexpr VectorArea (const VectorArea< OtherNumericType > &other)
Copy constructor. Constructs a vector area by copying another one.
constexpr VectorArea (VectorArea< NumericType > &&other) noexcept=default
Move constructor. Constructs a vector area by moving another one.
constexpr VectorArea< NumericType > & operator= (const VectorArea< NumericType > &other)=default
Copy assignment operator. Assigns this vector area by copying another one.
template<typename OtherNumericType >
constexpr VectorArea< NumericType > & operator= (const VectorArea< OtherNumericType > &other)
Copy assignment operator. Assigns this vector area by copying another one.
constexpr VectorArea< NumericType > & operator= (VectorArea< NumericType > &&other) noexcept=default
Move assignment operator. Assigns this vector area by moving another one.
constexpr Area< NumericType > x () const noexcept
Returns the x Cartesian component of this vector area.
constexpr Area< NumericType > y () const noexcept
Returns the y Cartesian component of this vector area.
constexpr Area< NumericType > z () const noexcept
Returns the z Cartesian component of this vector area.
Area< NumericType > Magnitude () const
Returns the magnitude of this vector area.
PhQ::Direction< NumericType > Direction () const
Returns the direction of this vector area.
PhQ::Angle< NumericType > Angle (const VectorArea< NumericType > &vector_area) const
Returns the angle between this vector area and another one.
constexpr VectorArea< NumericType > operator+ (const VectorArea< NumericType > &vector_area) const
constexpr VectorArea< NumericType > operator- (const VectorArea< NumericType > &vector_area) const
constexpr VectorArea< NumericType > operator* (const NumericType number) const
constexpr VectorArea< NumericType > operator/ (const NumericType number) const
constexpr void operator+= (const VectorArea< NumericType > &vector_area) noexcept
constexpr void operator-= (const VectorArea< NumericType > &vector_area) noexcept
constexpr void operator*= (const NumericType number) noexcept
constexpr void operator/= (const NumericType number) noexcept
constexpr const PhQ::Vector< NumericType > & Value () const noexcept
Value of this physical quantity expressed in its standard unit of measure.
PhQ::Vector< NumericType > Value (const UnitType unit) const
Value of this physical quantity expressed in a given unit of measure.
template<UnitType NewUnit>
constexpr PhQ::Vector< NumericType > StaticValue () const
Value of this physical quantity expressed in a given unit of measure. This method can be evaluated statically at compile-time.
constexpr PhQ::Vector< NumericType > & MutableValue () noexcept
Returns the value of this physical quantity expressed in its standard unit of measure as a mutable value.
constexpr void SetValue (const PhQ::Vector< NumericType > &value) noexcept
Sets the value of this physical quantity expressed in its standard unit of measure to the given value.
std::string Print () const
Prints this physical quantity as a string. This physical quantity's value is expressed in its standard unit of measure.
std::string Print (const UnitType unit) const
Prints this physical quantity as a string. This physical quantity's value is expressed in the given unit of measure.
std::string JSON () const
Serializes this physical quantity as a JSON message. This physical quantity's value is expressed in its standard unit of measure.
std::string JSON (const UnitType unit) const
Serializes this physical quantity as a JSON message. This physical quantity's value is expressed in the given unit of measure.
std::string XML () const
Serializes this physical quantity as an XML message. This physical quantity's value is expressed in its standard unit of measure.
std::string XML (const UnitType unit) const
Serializes this physical quantity as an XML message. This physical quantity's value is expressed in the given unit of measure.
std::string YAML () const
Serializes this physical quantity as a YAML message. This physical quantity's value is expressed in its standard unit of measure.
std::string YAML (const UnitType unit) const
Serializes this physical quantity as a YAML message. This physical quantity's value is expressed in the given unit of measure.
Static Public Member Functions
static constexpr VectorArea< NumericType > Zero ()
Statically creates a vector area of zero.
template<Unit::Area Unit>
static constexpr VectorArea< NumericType > Create (const NumericType x, const NumericType y, const NumericType z)
Statically creates a vector area from the given x, y, and z Cartesian components expressed in a given area unit.
template<Unit::Area Unit>
static constexpr VectorArea< NumericType > Create (const std::array< NumericType, 3 > &x_y_z)
Statically creates a vector area from the given x, y, and z Cartesian components expressed in a given area unit.
template<Unit::Area Unit>
static constexpr VectorArea< NumericType > Create (const Vector< NumericType > &value)
Statically creates a vector area with a given value expressed in a given area unit.
static constexpr const PhQ::Dimensions & Dimensions ()
Physical dimension set of this physical quantity.
static constexpr UnitType Unit ()
Standard unit of measure for this physical quantity. This physical quantity's value is stored internally in this unit of measure.
Protected Attributes
PhQ::Vector< NumericType > value
Value of this physical quantity expressed in its standard unit of measure.
Private Member Functions
constexpr VectorArea (const Vector< NumericType > &value)
Constructor. Constructs a vector area with a given value expressed in the standard area unit.
Detailed Description
template<typename NumericType = double>
class PhQ::VectorArea< NumericType >
Three-dimensional Euclidean vector area. Contains three components in Cartesian coordinates: x, y, and z. A vector area is an oriented area; it is the three-dimensional Euclidean vector representation of an area. Any closed surface has a vector area: it is the surface integral of its surface normal direction. For the scalar components of a vector area or for the magnitude of a vector area, see PhQ::Area.
Definition at line 48 of file VectorArea.hpp.
Constructor & Destructor Documentation
VectorArea() [1/8]
template<typename NumericType = double> PhQ::VectorArea< NumericType >::VectorArea () default
Default constructor. Constructs a vector area with an uninitialized value.
VectorArea() [2/8]
template<typename NumericType = double> PhQ::VectorArea< NumericType >::VectorArea (const Vector< NumericType > & value, const Unit::Area unit) inline
Constructor. Constructs a vector area with a given value expressed in a given area unit.
Definition at line 55 of file VectorArea.hpp.
VectorArea() [3/8]
template<typename NumericType = double> PhQ::VectorArea< NumericType >::VectorArea (const Area< NumericType > & x, const Area< NumericType > & y, const Area< NumericType > & z) inline
Constructor. Constructs a vector area from a given set of area components.
Definition at line 59 of file VectorArea.hpp.
References PhQ::VectorArea< NumericType >::x(), PhQ::VectorArea< NumericType >::y(), and PhQ::VectorArea< NumericType >::z().
VectorArea() [4/8]
template<typename NumericType = double> constexpr PhQ::VectorArea< NumericType >::VectorArea (const Area< NumericType > & area, const Direction< NumericType > & direction) inline constexpr
Constructor. Constructs a vector area from a given area and direction.
Definition at line 63 of file VectorArea.hpp.
~VectorArea()
template<typename NumericType = double> PhQ::VectorArea< NumericType >::~VectorArea () default noexcept
Destructor. Destroys this vector area.
VectorArea() [5/8]
template<typename NumericType = double> constexpr PhQ::VectorArea< NumericType >::VectorArea (const VectorArea< NumericType > & other) constexpr default
Copy constructor. Constructs a vector area by copying another one.
VectorArea() [6/8]
template<typename NumericType = double> template<typename OtherNumericType > constexpr PhQ::VectorArea< NumericType >::VectorArea (const VectorArea< OtherNumericType > & other) inline explicit constexpr
Copy constructor. Constructs a vector area by copying another one.
Definition at line 74 of file VectorArea.hpp.
VectorArea() [7/8]
template<typename NumericType = double> constexpr PhQ::VectorArea< NumericType >::VectorArea (VectorArea< NumericType > && other) constexpr default noexcept
Move constructor. Constructs a vector area by moving another one.
VectorArea() [8/8]
template<typename NumericType = double> constexpr PhQ::VectorArea< NumericType >::VectorArea (const Vector< NumericType > & value) inline explicit constexpr private
Constructor. Constructs a vector area with a given value expressed in the standard area unit.
Definition at line 188 of file VectorArea.hpp.
Member Function Documentation
Angle()
template<typename NumericType = double> PhQ::Angle< NumericType > PhQ::VectorArea< NumericType >::Angle (const VectorArea< NumericType > & vector_area) const inline
Returns the angle between this vector area and another one.
Definition at line 149 of file VectorArea.hpp.
Create() [1/3]
template<typename NumericType = double> template<Unit::Area Unit> static constexpr VectorArea< NumericType > PhQ::VectorArea< NumericType >::Create (const NumericType x, const NumericType y, const NumericType z) inline static constexpr
Statically creates a vector area from the given x, y, and z Cartesian components expressed in a given area unit.
Definition at line 101 of file VectorArea.hpp.
References PhQ::VectorArea< NumericType >::x(), PhQ::VectorArea< NumericType >::y(), and PhQ::VectorArea< NumericType >::z().
Create() [2/3]
template<typename NumericType = double> template<Unit::Area Unit> static constexpr VectorArea< NumericType > PhQ::VectorArea< NumericType >::Create (const std::array< NumericType, 3 > & x_y_z) inline static constexpr
Statically creates a vector area from the given x, y, and z Cartesian components expressed in a given area unit.
Definition at line 110 of file VectorArea.hpp.
Create() [3/3]
template<typename NumericType = double> template<Unit::Area Unit> static constexpr VectorArea< NumericType > PhQ::VectorArea< NumericType >::Create (const Vector< NumericType > & value) inline static constexpr
Statically creates a vector area with a given value expressed in a given area unit.
Definition at line 118 of file VectorArea.hpp.
References PhQ::DimensionalVector< UnitType, NumericType >::value.
Dimensions()
template<typename UnitType , typename NumericType = double> static constexpr const PhQ::Dimensions & PhQ::DimensionalVector< UnitType, NumericType >::Dimensions () inline static constexpr inherited
Physical dimension set of this physical quantity.
Definition at line 50 of file DimensionalVector.hpp.
Direction()
template<typename NumericType = double> PhQ::Direction< NumericType > PhQ::VectorArea< NumericType >::Direction () const inline
Returns the direction of this vector area.
Definition at line 144 of file VectorArea.hpp.
References PhQ::DimensionalVector< UnitType, NumericType >::value.
JSON() [1/2]
template<typename UnitType , typename NumericType = double> std::string PhQ::DimensionalVector< UnitType, NumericType >::JSON () const inline inherited
Serializes this physical quantity as a JSON message. This physical quantity's value is expressed in its standard unit of measure.
Definition at line 103 of file DimensionalVector.hpp.
References PhQ::Abbreviation(), and PhQ::DimensionalVector< UnitType, NumericType >::value.
Referenced by PhQ::DimensionalVector< UnitType, NumericType >::JSON().
JSON() [2/2]
template<typename UnitType , typename NumericType = double> std::string PhQ::DimensionalVector< UnitType, NumericType >::JSON (const UnitType unit) const inline inherited
Serializes this physical quantity as a JSON message. This physical quantity's value is expressed in the given unit of measure.
Definition at line 113 of file DimensionalVector.hpp.
References PhQ::Abbreviation(), PhQ::DimensionalVector< UnitType, NumericType >::JSON(), and PhQ::DimensionalVector< UnitType, NumericType >::Value().
Magnitude()
template<typename NumericType = double> Area< NumericType > PhQ::VectorArea< NumericType >::Magnitude () const inline
Returns the magnitude of this vector area.
Definition at line 139 of file VectorArea.hpp.
References PhQ::DimensionalVector< UnitType, NumericType >::value.
MutableValue()
template<typename UnitType , typename NumericType = double> constexpr PhQ::Vector< NumericType > & PhQ::DimensionalVector< UnitType, NumericType >::MutableValue () inline constexpr noexcept inherited
Returns the value of this physical quantity expressed in its standard unit of measure as a mutable value.
Definition at line 79 of file DimensionalVector.hpp.
References PhQ::DimensionalVector< UnitType, NumericType >::value.
operator*()
template<typename NumericType = double> constexpr VectorArea< NumericType > PhQ::VectorArea< NumericType >::operator* (const NumericType number) const inline constexpr
Definition at line 161 of file VectorArea.hpp.
References PhQ::DimensionalVector< UnitType, NumericType >::value.
operator*=()
template<typename NumericType = double> constexpr void PhQ::VectorArea< NumericType >::operator*= (const NumericType number) inline constexpr noexcept
Definition at line 177 of file VectorArea.hpp.
References PhQ::DimensionalVector< UnitType, NumericType >::value.
operator+()
template<typename NumericType = double> constexpr VectorArea< NumericType > PhQ::VectorArea< NumericType >::operator+ (const VectorArea< NumericType > & vector_area) const inline constexpr
Definition at line 153 of file VectorArea.hpp.
References PhQ::DimensionalVector< UnitType, NumericType >::value.
operator+=()
template<typename NumericType = double> constexpr void PhQ::VectorArea< NumericType >::operator+= (const VectorArea< NumericType > & vector_area) inline constexpr noexcept
Definition at line 169 of file VectorArea.hpp.
References PhQ::DimensionalVector< UnitType, NumericType >::value.
operator-()
template<typename NumericType = double> constexpr VectorArea< NumericType > PhQ::VectorArea< NumericType >::operator- (const VectorArea< NumericType > & vector_area) const inline constexpr
Definition at line 157 of file VectorArea.hpp.
References PhQ::DimensionalVector< UnitType, NumericType >::value.
operator-=()
template<typename NumericType = double> constexpr void PhQ::VectorArea< NumericType >::operator-= (const VectorArea< NumericType > & vector_area) inline constexpr noexcept
Definition at line 173 of file VectorArea.hpp.
References PhQ::DimensionalVector< UnitType, NumericType >::value.
operator/()
template<typename NumericType = double> constexpr VectorArea< NumericType > PhQ::VectorArea< NumericType >::operator/ (const NumericType number) const inline constexpr
Definition at line 165 of file VectorArea.hpp.
References PhQ::DimensionalVector< UnitType, NumericType >::value.
operator/=()
template<typename NumericType = double> constexpr void PhQ::VectorArea< NumericType >::operator/= (const NumericType number) inline constexpr noexcept
Definition at line 181 of file VectorArea.hpp.
References PhQ::DimensionalVector< UnitType, NumericType >::value.
operator=() [1/3]
template<typename NumericType = double> constexpr VectorArea< NumericType > & PhQ::VectorArea< NumericType >::operator= (const VectorArea< NumericType > & other) constexpr default
Copy assignment operator. Assigns this vector area by copying another one.
operator=() [2/3]
template<typename NumericType = double> template<typename OtherNumericType > constexpr VectorArea< NumericType > & PhQ::VectorArea< NumericType >::operator= (const VectorArea< OtherNumericType > & other) inline constexpr
Copy assignment operator. Assigns this vector area by copying another one.
Definition at line 85 of file VectorArea.hpp.
References PhQ::DimensionalVector< UnitType, NumericType >::Value(), and PhQ::DimensionalVector< UnitType, NumericType >::value.
operator=() [3/3]
template<typename NumericType = double> constexpr VectorArea< NumericType > & PhQ::VectorArea< NumericType >::operator= (VectorArea< NumericType > && other) constexpr default noexcept
Move assignment operator. Assigns this vector area by moving another one.
Print() [1/2]
template<typename UnitType , typename NumericType = double> std::string PhQ::DimensionalVector< UnitType, NumericType >::Print () const inline inherited
Prints this physical quantity as a string. This physical quantity's value is expressed in its standard unit of measure.
Definition at line 91 of file DimensionalVector.hpp.
References PhQ::Abbreviation(), and PhQ::DimensionalVector< UnitType, NumericType >::value.
Referenced by PhQ::operator<<(), PhQ::operator<<(), PhQ::operator<<(), PhQ::operator<<(), PhQ::operator<<(), PhQ::operator<<(), PhQ::operator<<(), PhQ::operator<<(), and PhQ::operator<<().
Print() [2/2]
template<typename UnitType , typename NumericType = double> std::string PhQ::DimensionalVector< UnitType, NumericType >::Print (const UnitType unit) const inline inherited
Prints this physical quantity as a string. This physical quantity's value is expressed in the given unit of measure.
Definition at line 97 of file DimensionalVector.hpp.
References PhQ::Abbreviation(), and PhQ::DimensionalVector< UnitType, NumericType >::Value().
SetValue()
template<typename UnitType , typename NumericType = double> constexpr void PhQ::DimensionalVector< UnitType, NumericType >::SetValue (const PhQ::Vector< NumericType > & value) inline constexpr noexcept inherited
Sets the value of this physical quantity expressed in its standard unit of measure to the given value.
Definition at line 85 of file DimensionalVector.hpp.
References PhQ::DimensionalVector< UnitType, NumericType >::value.
StaticValue()
template<typename UnitType , typename NumericType = double> template<UnitType NewUnit> constexpr PhQ::Vector< NumericType > PhQ::DimensionalVector< UnitType, NumericType >::StaticValue () const inline constexpr inherited
Value of this physical quantity expressed in a given unit of measure. This method can be evaluated statically at compile-time.
Definition at line 73 of file DimensionalVector.hpp.
References PhQ::DimensionalVector< UnitType, NumericType >::value.
Unit()
template<typename UnitType , typename NumericType = double> static constexpr UnitType PhQ::DimensionalVector< UnitType, NumericType >::Unit () inline static constexpr inherited
Standard unit of measure for this physical quantity. This physical quantity's value is stored internally in this unit of measure.
Definition at line 56 of file DimensionalVector.hpp.
Value() [1/2]
template<typename UnitType , typename NumericType = double> constexpr const PhQ::Vector< NumericType > & PhQ::DimensionalVector< UnitType, NumericType >::Value () const inline constexpr noexcept inherited
Value of this physical quantity expressed in its standard unit of measure.
Definition at line 61 of file DimensionalVector.hpp.
References PhQ::DimensionalVector< UnitType, NumericType >::value.
Referenced by PhQ::DimensionalVector< UnitType, NumericType >::JSON(), PhQ::Position< NumericType >::operator+(), PhQ::Displacement< NumericType >::operator+(), PhQ::Position< NumericType >::operator-(), PhQ::Displacement< NumericType >::operator-(), PhQ::Acceleration< NumericType >::operator=(), PhQ::DimensionalVector< UnitType, NumericType >::operator=(), PhQ::Displacement< NumericType >::operator=(), PhQ::Force< NumericType >::operator=(), PhQ::HeatFlux< NumericType >::operator=(), PhQ::Position< NumericType >::operator=(), PhQ::TemperatureGradient< NumericType >::operator=(), PhQ::Traction< NumericType >::operator=(), PhQ::VectorArea< NumericType >::operator=(), PhQ::Velocity< NumericType >::operator=(), PhQ::operator==(), PhQ::operator==(), PhQ::operator==(), PhQ::operator==(), PhQ::operator==(), PhQ::operator==(), PhQ::operator==(), PhQ::operator==(), PhQ::operator==(), PhQ::operator==(), PhQ::operator==(), PhQ::operator==(), PhQ::operator==(), PhQ::operator==(), PhQ::operator==(), PhQ::operator==(), PhQ::PlanarAcceleration< NumericType >::PlanarAcceleration(), PhQ::PlanarDisplacement< NumericType >::PlanarDisplacement(), PhQ::PlanarForce< NumericType >::PlanarForce(), PhQ::PlanarHeatFlux< NumericType >::PlanarHeatFlux(), PhQ::PlanarPosition< NumericType >::PlanarPosition(), PhQ::PlanarTemperatureGradient< NumericType >::PlanarTemperatureGradient(), PhQ::PlanarTraction< NumericType >::PlanarTraction(), PhQ::PlanarVelocity< NumericType >::PlanarVelocity(), PhQ::DimensionalVector< UnitType, NumericType >::Print(), PhQ::DimensionalVector< UnitType, NumericType >::XML(), and PhQ::DimensionalVector< UnitType, NumericType >::YAML().
Value() [2/2]
template<typename UnitType , typename NumericType = double> PhQ::Vector< NumericType > PhQ::DimensionalVector< UnitType, NumericType >::Value (const UnitType unit) const inline inherited
Value of this physical quantity expressed in a given unit of measure.
Definition at line 66 of file DimensionalVector.hpp.
References PhQ::Convert(), and PhQ::DimensionalVector< UnitType, NumericType >::value.
x()
template<typename NumericType = double> constexpr Area< NumericType > PhQ::VectorArea< NumericType >::x () const inline constexpr noexcept
Returns the x Cartesian component of this vector area.
Definition at line 124 of file VectorArea.hpp.
References PhQ::DimensionalVector< UnitType, NumericType >::value.
Referenced by PhQ::VectorArea< NumericType >::Create(), and PhQ::VectorArea< NumericType >::VectorArea().
XML() [1/2]
template<typename UnitType , typename NumericType = double> std::string PhQ::DimensionalVector< UnitType, NumericType >::XML () const inline inherited
Serializes this physical quantity as an XML message. This physical quantity's value is expressed in its standard unit of measure.
Definition at line 123 of file DimensionalVector.hpp.
References PhQ::Abbreviation(), and PhQ::DimensionalVector< UnitType, NumericType >::value.
Referenced by PhQ::DimensionalVector< UnitType, NumericType >::XML().
XML() [2/2]
template<typename UnitType , typename NumericType = double> std::string PhQ::DimensionalVector< UnitType, NumericType >::XML (const UnitType unit) const inline inherited
Serializes this physical quantity as an XML message. This physical quantity's value is expressed in the given unit of measure.
Definition at line 133 of file DimensionalVector.hpp.
References PhQ::Abbreviation(), PhQ::DimensionalVector< UnitType, NumericType >::Value(), and PhQ::DimensionalVector< UnitType, NumericType >::XML().
y()
template<typename NumericType = double> constexpr Area< NumericType > PhQ::VectorArea< NumericType >::y () const inline constexpr noexcept
Returns the y Cartesian component of this vector area.
Definition at line 129 of file VectorArea.hpp.
References PhQ::DimensionalVector< UnitType, NumericType >::value.
Referenced by PhQ::VectorArea< NumericType >::Create(), and PhQ::VectorArea< NumericType >::VectorArea().
YAML() [1/2]
template<typename UnitType , typename NumericType = double> std::string PhQ::DimensionalVector< UnitType, NumericType >::YAML () const inline inherited
Serializes this physical quantity as a YAML message. This physical quantity's value is expressed in its standard unit of measure.
Definition at line 143 of file DimensionalVector.hpp.
References PhQ::Abbreviation(), and PhQ::DimensionalVector< UnitType, NumericType >::value.
Referenced by PhQ::DimensionalVector< UnitType, NumericType >::YAML().
YAML() [2/2]
template<typename UnitType , typename NumericType = double> std::string PhQ::DimensionalVector< UnitType, NumericType >::YAML (const UnitType unit) const inline inherited
Serializes this physical quantity as a YAML message. This physical quantity's value is expressed in the given unit of measure.
Definition at line 153 of file DimensionalVector.hpp.
References PhQ::Abbreviation(), PhQ::DimensionalVector< UnitType, NumericType >::Value(), and PhQ::DimensionalVector< UnitType, NumericType >::YAML().
z()
template<typename NumericType = double> constexpr Area< NumericType > PhQ::VectorArea< NumericType >::z () const inline constexpr noexcept
Returns the z Cartesian component of this vector area.
Definition at line 134 of file VectorArea.hpp.
References PhQ::DimensionalVector< UnitType, NumericType >::value.
Referenced by PhQ::VectorArea< NumericType >::Create(), and PhQ::VectorArea< NumericType >::VectorArea().
Zero()
template<typename NumericType = double> static constexpr VectorArea< NumericType > PhQ::VectorArea< NumericType >::Zero () inline static constexpr
Statically creates a vector area of zero.
Definition at line 94 of file VectorArea.hpp.
References PhQ::Vector< NumericType >::Zero().
Member Data Documentation
value
template<typename UnitType , typename NumericType = double> PhQ::Vector<NumericType> PhQ::DimensionalVector< UnitType, NumericType >::value protected inherited
Value of this physical quantity expressed in its standard unit of measure.
Definition at line 217 of file DimensionalVector.hpp.
Referenced by PhQ::Acceleration< NumericType >::Create(), PhQ::Displacement< NumericType >::Create(), PhQ::Force< NumericType >::Create(), PhQ::HeatFlux< NumericType >::Create(), PhQ::Position< NumericType >::Create(), PhQ::TemperatureGradient< NumericType >::Create(), PhQ::Traction< NumericType >::Create(), PhQ::VectorArea< NumericType >::Create(), PhQ::Velocity< NumericType >::Create(), PhQ::Acceleration< NumericType >::Direction(), PhQ::Displacement< NumericType >::Direction(), PhQ::Force< NumericType >::Direction(), PhQ::HeatFlux< NumericType >::Direction(), PhQ::Position< NumericType >::Direction(), PhQ::TemperatureGradient< NumericType >::Direction(), PhQ::Traction< NumericType >::Direction(), PhQ::VectorArea< NumericType >::Direction(), PhQ::Velocity< NumericType >::Direction(), PhQ::DimensionalVector< UnitType, NumericType >::JSON(), PhQ::Acceleration< NumericType >::Magnitude(), PhQ::Displacement< NumericType >::Magnitude(), PhQ::Force< NumericType >::Magnitude(), PhQ::HeatFlux< NumericType >::Magnitude(), PhQ::Position< NumericType >::Magnitude(), PhQ::TemperatureGradient< NumericType >::Magnitude(), PhQ::Traction< NumericType >::Magnitude(), PhQ::VectorArea< NumericType >::Magnitude(), PhQ::Velocity< NumericType >::Magnitude(), PhQ::DimensionalVector< UnitType, NumericType >::MutableValue(), PhQ::Acceleration< NumericType >::operator*(), PhQ::Displacement< NumericType >::operator*(), PhQ::Force< NumericType >::operator*(), PhQ::HeatFlux< NumericType >::operator*(), PhQ::Position< NumericType >::operator*(), PhQ::TemperatureGradient< NumericType >::operator*(), PhQ::Traction< NumericType >::operator*(), PhQ::VectorArea< NumericType >::operator*(), PhQ::Velocity< NumericType >::operator*(), PhQ::Acceleration< NumericType >::operator*=(), PhQ::Displacement< NumericType >::operator*=(), PhQ::Force< NumericType >::operator*=(), PhQ::HeatFlux< NumericType >::operator*=(), PhQ::Position< NumericType >::operator*=(), PhQ::TemperatureGradient< NumericType >::operator*=(), PhQ::Traction< NumericType >::operator*=(), PhQ::VectorArea< NumericType >::operator*=(), PhQ::Velocity< NumericType >::operator*=(), PhQ::Acceleration< NumericType >::operator+(), PhQ::Displacement< NumericType >::operator+(), PhQ::Position< NumericType >::operator+(), PhQ::Force< NumericType >::operator+(), PhQ::HeatFlux< NumericType >::operator+(), PhQ::Position< NumericType >::operator+(), PhQ::TemperatureGradient< NumericType >::operator+(), PhQ::Traction< NumericType >::operator+(), PhQ::VectorArea< NumericType >::operator+(), PhQ::Velocity< NumericType >::operator+(), PhQ::Acceleration< NumericType >::operator+=(), PhQ::Displacement< NumericType >::operator+=(), PhQ::Position< NumericType >::operator+=(), PhQ::Force< NumericType >::operator+=(), PhQ::HeatFlux< NumericType >::operator+=(), PhQ::Position< NumericType >::operator+=(), PhQ::TemperatureGradient< NumericType >::operator+=(), PhQ::Traction< NumericType >::operator+=(), PhQ::VectorArea< NumericType >::operator+=(), PhQ::Velocity< NumericType >::operator+=(), PhQ::Acceleration< NumericType >::operator-(), PhQ::Displacement< NumericType >::operator-(), PhQ::Position< NumericType >::operator-(), PhQ::Force< NumericType >::operator-(), PhQ::HeatFlux< NumericType >::operator-(), PhQ::Position< NumericType >::operator-(), PhQ::TemperatureGradient< NumericType >::operator-(), PhQ::Traction< NumericType >::operator-(), PhQ::VectorArea< NumericType >::operator-(), PhQ::Velocity< NumericType >::operator-(), PhQ::Acceleration< NumericType >::operator-=(), PhQ::Displacement< NumericType >::operator-=(), PhQ::Position< NumericType >::operator-=(), PhQ::Force< NumericType >::operator-=(), PhQ::HeatFlux< NumericType >::operator-=(), PhQ::Position< NumericType >::operator-=(), PhQ::TemperatureGradient< NumericType >::operator-=(), PhQ::Traction< NumericType >::operator-=(), PhQ::VectorArea< NumericType >::operator-=(), PhQ::Velocity< NumericType >::operator-=(), PhQ::Acceleration< NumericType >::operator/(), PhQ::Displacement< NumericType >::operator/(), PhQ::Force< NumericType >::operator/(), PhQ::HeatFlux< NumericType >::operator/(), PhQ::Position< NumericType >::operator/(), PhQ::TemperatureGradient< NumericType >::operator/(), PhQ::Traction< NumericType >::operator/(), PhQ::VectorArea< NumericType >::operator/(), PhQ::Velocity< NumericType >::operator/(), PhQ::Acceleration< NumericType >::operator/=(), PhQ::Displacement< NumericType >::operator/=(), PhQ::Force< NumericType >::operator/=(), PhQ::HeatFlux< NumericType >::operator/=(), PhQ::Position< NumericType >::operator/=(), PhQ::TemperatureGradient< NumericType >::operator/=(), PhQ::Traction< NumericType >::operator/=(), PhQ::VectorArea< NumericType >::operator/=(), PhQ::Velocity< NumericType >::operator/=(), PhQ::Acceleration< NumericType >::operator=(), PhQ::DimensionalVector< UnitType, NumericType >::operator=(), PhQ::Displacement< NumericType >::operator=(), PhQ::Force< NumericType >::operator=(), PhQ::HeatFlux< NumericType >::operator=(), PhQ::Position< NumericType >::operator=(), PhQ::TemperatureGradient< NumericType >::operator=(), PhQ::Traction< NumericType >::operator=(), PhQ::VectorArea< NumericType >::operator=(), PhQ::Velocity< NumericType >::operator=(), PhQ::DimensionalVector< UnitType, NumericType >::Print(), PhQ::DimensionalVector< UnitType, NumericType >::SetValue(), PhQ::DimensionalVector< UnitType, NumericType >::StaticValue(), PhQ::DimensionalVector< UnitType, NumericType >::Value(), PhQ::DimensionalVector< UnitType, NumericType >::Value(), PhQ::Acceleration< NumericType >::x(), PhQ::Displacement< NumericType >::x(), PhQ::Force< NumericType >::x(), PhQ::HeatFlux< NumericType >::x(), PhQ::Position< NumericType >::x(), PhQ::TemperatureGradient< NumericType >::x(), PhQ::Traction< NumericType >::x(), PhQ::VectorArea< NumericType >::x(), PhQ::Velocity< NumericType >::x(), PhQ::DimensionalVector< UnitType, NumericType >::XML(), PhQ::Acceleration< NumericType >::y(), PhQ::Displacement< NumericType >::y(), PhQ::Force< NumericType >::y(), PhQ::HeatFlux< NumericType >::y(), PhQ::Position< NumericType >::y(), PhQ::TemperatureGradient< NumericType >::y(), PhQ::Traction< NumericType >::y(), PhQ::VectorArea< NumericType >::y(), PhQ::Velocity< NumericType >::y(), PhQ::DimensionalVector< UnitType, NumericType >::YAML(), PhQ::Acceleration< NumericType >::z(), PhQ::Displacement< NumericType >::z(), PhQ::Force< NumericType >::z(), PhQ::HeatFlux< NumericType >::z(), PhQ::Position< NumericType >::z(), PhQ::TemperatureGradient< NumericType >::z(), PhQ::Traction< NumericType >::z(), PhQ::VectorArea< NumericType >::z(), and PhQ::Velocity< NumericType >::z().
The documentation for this class was generated from the following files:
PhQ/Angle.hpp
PhQ/VectorArea.hpp