Physical Quantities: PhQ::Acceleration< NumericType > Class Template Reference
PhQ::Acceleration< NumericType > Class Template Reference
Three-dimensional Euclidean acceleration vector. Contains three components in Cartesian coordinates: x, y, and z. For a two-dimensional Euclidean acceleration vector in the XY plane, see PhQ::PlanarAcceleration. For scalar acceleration components or for the magnitude of an acceleration vector, see PhQ::ScalarAcceleration.
#include "Acceleration.hpp"
Public Member Functions
Acceleration ()=default
Default constructor. Constructs an acceleration vector with an uninitialized value.
Acceleration (const Vector< NumericType > &value, const Unit::Acceleration unit)
Constructor. Constructs an acceleration vector with a given value expressed in a given acceleration unit.
Acceleration (const ScalarAcceleration< NumericType > &x, const ScalarAcceleration< NumericType > &y, const ScalarAcceleration< NumericType > &z)
Constructor. Constructs an acceleration vector from a given set of scalar acceleration components.
constexpr Acceleration (const ScalarAcceleration< NumericType > &scalar_acceleration, const Direction< NumericType > &direction)
Constructor. Constructs an acceleration vector from a given scalar acceleration magnitude and direction.
constexpr Acceleration (const PlanarAcceleration< NumericType > &planar_acceleration)
Constructor. Constructs an acceleration vector from a given planar acceleration vector in the XY plane. This acceleration vector's z-component is initialized to zero.
constexpr Acceleration (const Velocity< NumericType > &velocity, const Time< NumericType > &time)
Constructor. Constructs an acceleration vector from a given velocity and time using the definition of acceleration.
constexpr Acceleration (const Velocity< NumericType > &velocity, const Frequency< NumericType > &frequency)
Constructor. Constructs an acceleration vector from a given velocity and frequency using the definition of acceleration.
~Acceleration () noexcept=default
Destructor. Destroys this acceleration vector.
constexpr Acceleration (const Acceleration< NumericType > &other)=default
Copy constructor. Constructs an acceleration vector by copying another one.
template<typename OtherNumericType >
constexpr Acceleration (const Acceleration< OtherNumericType > &other)
Copy constructor. Constructs an acceleration vector by copying another one.
constexpr Acceleration (Acceleration< NumericType > &&other) noexcept=default
Move constructor. Constructs an acceleration vector by moving another one.
constexpr Acceleration< NumericType > & operator= (const Acceleration< NumericType > &other)=default
Copy assignment operator. Assigns this acceleration vector by copying another one.
template<typename OtherNumericType >
constexpr Acceleration< NumericType > & operator= (const Acceleration< OtherNumericType > &other)
Copy assignment operator. Assigns this acceleration vector by copying another one.
constexpr Acceleration< NumericType > & operator= (Acceleration< NumericType > &&other) noexcept=default
Move assignment operator. Assigns this acceleration vector by moving another one.
constexpr ScalarAcceleration< NumericType > x () const noexcept
Returns the x Cartesian component of this acceleration vector.
constexpr ScalarAcceleration< NumericType > y () const noexcept
Returns the y Cartesian component of this acceleration vector.
constexpr ScalarAcceleration< NumericType > z () const noexcept
Returns the z Cartesian component of this acceleration vector.
ScalarAcceleration< NumericType > Magnitude () const
Returns the magnitude of this acceleration vector.
PhQ::Direction< NumericType > Direction () const
Returns the direction of this acceleration vector.
PhQ::Angle< NumericType > Angle (const Acceleration< NumericType > &other) const
Returns the angle between this acceleration vector and another one.
constexpr Acceleration< NumericType > operator+ (const Acceleration< NumericType > &other) const
constexpr Acceleration< NumericType > operator- (const Acceleration< NumericType > &other) const
constexpr Acceleration< NumericType > operator* (const NumericType number) const
constexpr Velocity< NumericType > operator* (const Time< NumericType > &time) const
constexpr Acceleration< NumericType > operator/ (const NumericType number) const
constexpr Velocity< NumericType > operator/ (const Frequency< NumericType > &frequency) const
constexpr void operator+= (const Acceleration< NumericType > &other) noexcept
constexpr void operator-= (const Acceleration< NumericType > &other) noexcept
constexpr void operator*= (const NumericType number) noexcept
constexpr void operator/= (const NumericType number) noexcept
constexpr const PhQ::Vector< NumericType > & Value () const noexcept
Value of this physical quantity expressed in its standard unit of measure.
PhQ::Vector< NumericType > Value (const UnitType unit) const
Value of this physical quantity expressed in a given unit of measure.
template<UnitType NewUnit>
constexpr PhQ::Vector< NumericType > StaticValue () const
Value of this physical quantity expressed in a given unit of measure. This method can be evaluated statically at compile-time.
constexpr PhQ::Vector< NumericType > & MutableValue () noexcept
Returns the value of this physical quantity expressed in its standard unit of measure as a mutable value.
constexpr void SetValue (const PhQ::Vector< NumericType > &value) noexcept
Sets the value of this physical quantity expressed in its standard unit of measure to the given value.
std::string Print () const
Prints this physical quantity as a string. This physical quantity's value is expressed in its standard unit of measure.
std::string Print (const UnitType unit) const
Prints this physical quantity as a string. This physical quantity's value is expressed in the given unit of measure.
std::string JSON () const
Serializes this physical quantity as a JSON message. This physical quantity's value is expressed in its standard unit of measure.
std::string JSON (const UnitType unit) const
Serializes this physical quantity as a JSON message. This physical quantity's value is expressed in the given unit of measure.
std::string XML () const
Serializes this physical quantity as an XML message. This physical quantity's value is expressed in its standard unit of measure.
std::string XML (const UnitType unit) const
Serializes this physical quantity as an XML message. This physical quantity's value is expressed in the given unit of measure.
std::string YAML () const
Serializes this physical quantity as a YAML message. This physical quantity's value is expressed in its standard unit of measure.
std::string YAML (const UnitType unit) const
Serializes this physical quantity as a YAML message. This physical quantity's value is expressed in the given unit of measure.
Static Public Member Functions
static constexpr Acceleration< NumericType > Zero ()
Statically creates an acceleration vector of zero.
template<Unit::Acceleration Unit>
static constexpr Acceleration< NumericType > Create (const NumericType x, const NumericType y, const NumericType z)
Statically creates an acceleration vector from the given x, y, and z Cartesian components expressed in a given acceleration unit.
template<Unit::Acceleration Unit>
static constexpr Acceleration< NumericType > Create (const std::array< NumericType, 3 > &x_y_z)
Statically creates an acceleration vector from the given x, y, and z Cartesian components expressed in a given acceleration unit.
template<Unit::Acceleration Unit>
static constexpr Acceleration< NumericType > Create (const Vector< NumericType > &value)
Statically creates an acceleration vector with a given value expressed in a given acceleration unit.
static constexpr const PhQ::Dimensions & Dimensions ()
Physical dimension set of this physical quantity.
static constexpr UnitType Unit ()
Standard unit of measure for this physical quantity. This physical quantity's value is stored internally in this unit of measure.
Protected Attributes
PhQ::Vector< NumericType > value
Value of this physical quantity expressed in its standard unit of measure.
Private Member Functions
constexpr Acceleration (const Vector< NumericType > &value)
Constructor. Constructs an acceleration vector with a given value expressed in the standard acceleration unit.
Detailed Description
template<typename NumericType = double>
class PhQ::Acceleration< NumericType >
Three-dimensional Euclidean acceleration vector. Contains three components in Cartesian coordinates: x, y, and z. For a two-dimensional Euclidean acceleration vector in the XY plane, see PhQ::PlanarAcceleration. For scalar acceleration components or for the magnitude of an acceleration vector, see PhQ::ScalarAcceleration.
Definition at line 51 of file Acceleration.hpp.
Constructor & Destructor Documentation
Acceleration() [1/11]
template<typename NumericType = double> PhQ::Acceleration< NumericType >::Acceleration () default
Default constructor. Constructs an acceleration vector with an uninitialized value.
Acceleration() [2/11]
template<typename NumericType = double> PhQ::Acceleration< NumericType >::Acceleration (const Vector< NumericType > & value, const Unit::Acceleration< NumericType > unit) inline
Constructor. Constructs an acceleration vector with a given value expressed in a given acceleration unit.
Definition at line 58 of file Acceleration.hpp.
Acceleration() [3/11]
template<typename NumericType = double> PhQ::Acceleration< NumericType >::Acceleration (const ScalarAcceleration< NumericType > & x, const ScalarAcceleration< NumericType > & y, const ScalarAcceleration< NumericType > & z) inline
Constructor. Constructs an acceleration vector from a given set of scalar acceleration components.
Definition at line 63 of file Acceleration.hpp.
References PhQ::Acceleration< NumericType >::x(), PhQ::Acceleration< NumericType >::y(), and PhQ::Acceleration< NumericType >::z().
Acceleration() [4/11]
template<typename NumericType = double> constexpr PhQ::Acceleration< NumericType >::Acceleration (const ScalarAcceleration< NumericType > & scalar_acceleration, const Direction< NumericType > & direction) inline constexpr
Constructor. Constructs an acceleration vector from a given scalar acceleration magnitude and direction.
Definition at line 69 of file Acceleration.hpp.
Acceleration() [5/11]
template<typename NumericType = double> constexpr PhQ::Acceleration< NumericType >::Acceleration (const PlanarAcceleration< NumericType > & planar_acceleration) inline explicit constexpr
Constructor. Constructs an acceleration vector from a given planar acceleration vector in the XY plane. This acceleration vector's z-component is initialized to zero.
Definition at line 75 of file Acceleration.hpp.
References PhQ::DimensionalPlanarVector< UnitType, NumericType >::Value().
Acceleration() [6/11]
template<typename NumericType = double> constexpr PhQ::Acceleration< NumericType >::Acceleration (const Velocity< NumericType > & velocity, const Time< NumericType > & time) inline constexpr
Constructor. Constructs an acceleration vector from a given velocity and time using the definition of acceleration.
Definition at line 80 of file Acceleration.hpp.
Acceleration() [7/11]
template<typename NumericType = double> constexpr PhQ::Acceleration< NumericType >::Acceleration (const Velocity< NumericType > & velocity, const Frequency< NumericType > & frequency) inline constexpr
Constructor. Constructs an acceleration vector from a given velocity and frequency using the definition of acceleration.
Definition at line 85 of file Acceleration.hpp.
~Acceleration()
template<typename NumericType = double> PhQ::Acceleration< NumericType >::~Acceleration () default noexcept
Destructor. Destroys this acceleration vector.
Acceleration() [8/11]
template<typename NumericType = double> constexpr PhQ::Acceleration< NumericType >::Acceleration (const Acceleration< NumericType > & other) constexpr default
Copy constructor. Constructs an acceleration vector by copying another one.
Acceleration() [9/11]
template<typename NumericType = double> template<typename OtherNumericType > constexpr PhQ::Acceleration< NumericType >::Acceleration (const Acceleration< OtherNumericType > & other) inline explicit constexpr
Copy constructor. Constructs an acceleration vector by copying another one.
Definition at line 97 of file Acceleration.hpp.
Acceleration() [10/11]
template<typename NumericType = double> constexpr PhQ::Acceleration< NumericType >::Acceleration (Acceleration< NumericType > && other) constexpr default noexcept
Move constructor. Constructs an acceleration vector by moving another one.
Acceleration() [11/11]
template<typename NumericType = double> constexpr PhQ::Acceleration< NumericType >::Acceleration (const Vector< NumericType > & value) inline explicit constexpr private
Constructor. Constructs an acceleration vector with a given value expressed in the standard acceleration unit.
Definition at line 224 of file Acceleration.hpp.
Member Function Documentation
Angle()
template<typename NumericType = double> PhQ::Angle< NumericType > PhQ::Acceleration< NumericType >::Angle (const Acceleration< NumericType > & other) const inline
Returns the angle between this acceleration vector and another one.
Definition at line 177 of file Acceleration.hpp.
Create() [1/3]
template<typename NumericType = double> template<Unit::Acceleration Unit> static constexpr Acceleration< NumericType > PhQ::Acceleration< NumericType >::Create (const NumericType x, const NumericType y, const NumericType z) inline static constexpr
Statically creates an acceleration vector from the given x, y, and z Cartesian components expressed in a given acceleration unit.
Definition at line 125 of file Acceleration.hpp.
References PhQ::Acceleration< NumericType >::x(), PhQ::Acceleration< NumericType >::y(), and PhQ::Acceleration< NumericType >::z().
Create() [2/3]
template<typename NumericType = double> template<Unit::Acceleration Unit> static constexpr Acceleration< NumericType > PhQ::Acceleration< NumericType >::Create (const std::array< NumericType, 3 > & x_y_z) inline static constexpr
Statically creates an acceleration vector from the given x, y, and z Cartesian components expressed in a given acceleration unit.
Definition at line 135 of file Acceleration.hpp.
Create() [3/3]
template<typename NumericType = double> template<Unit::Acceleration Unit> static constexpr Acceleration< NumericType > PhQ::Acceleration< NumericType >::Create (const Vector< NumericType > & value) inline static constexpr
Statically creates an acceleration vector with a given value expressed in a given acceleration unit.
Definition at line 145 of file Acceleration.hpp.
References PhQ::DimensionalVector< UnitType, NumericType >::value.
Dimensions()
template<typename UnitType , typename NumericType = double> static constexpr const PhQ::Dimensions & PhQ::DimensionalVector< UnitType, NumericType >::Dimensions () inline static constexpr inherited
Physical dimension set of this physical quantity.
Definition at line 50 of file DimensionalVector.hpp.
Direction()
template<typename NumericType = double> PhQ::Direction< NumericType > PhQ::Acceleration< NumericType >::Direction () const inline
Returns the direction of this acceleration vector.
Definition at line 172 of file Acceleration.hpp.
References PhQ::DimensionalVector< UnitType, NumericType >::value.
JSON() [1/2]
template<typename UnitType , typename NumericType = double> std::string PhQ::DimensionalVector< UnitType, NumericType >::JSON () const inline inherited
Serializes this physical quantity as a JSON message. This physical quantity's value is expressed in its standard unit of measure.
Definition at line 103 of file DimensionalVector.hpp.
References PhQ::Abbreviation(), and PhQ::DimensionalVector< UnitType, NumericType >::value.
Referenced by PhQ::DimensionalVector< UnitType, NumericType >::JSON().
JSON() [2/2]
template<typename UnitType , typename NumericType = double> std::string PhQ::DimensionalVector< UnitType, NumericType >::JSON (const UnitType unit) const inline inherited
Serializes this physical quantity as a JSON message. This physical quantity's value is expressed in the given unit of measure.
Definition at line 113 of file DimensionalVector.hpp.
References PhQ::Abbreviation(), PhQ::DimensionalVector< UnitType, NumericType >::JSON(), and PhQ::DimensionalVector< UnitType, NumericType >::Value().
Magnitude()
template<typename NumericType = double> ScalarAcceleration< NumericType > PhQ::Acceleration< NumericType >::Magnitude () const inline
Returns the magnitude of this acceleration vector.
Definition at line 167 of file Acceleration.hpp.
References PhQ::DimensionalVector< UnitType, NumericType >::value.
MutableValue()
template<typename UnitType , typename NumericType = double> constexpr PhQ::Vector< NumericType > & PhQ::DimensionalVector< UnitType, NumericType >::MutableValue () inline constexpr noexcept inherited
Returns the value of this physical quantity expressed in its standard unit of measure as a mutable value.
Definition at line 79 of file DimensionalVector.hpp.
References PhQ::DimensionalVector< UnitType, NumericType >::value.
operator*() [1/2]
template<typename NumericType = double> constexpr Acceleration< NumericType > PhQ::Acceleration< NumericType >::operator* (const NumericType number) const inline constexpr
Definition at line 189 of file Acceleration.hpp.
References PhQ::DimensionalVector< UnitType, NumericType >::value.
operator*() [2/2]
template<typename NumericType = double> constexpr Velocity< NumericType > PhQ::Acceleration< NumericType >::operator* (const Time< NumericType > & time) const inline constexpr
Definition at line 193 of file Acceleration.hpp.
operator*=()
template<typename NumericType = double> constexpr void PhQ::Acceleration< NumericType >::operator*= (const NumericType number) inline constexpr noexcept
Definition at line 213 of file Acceleration.hpp.
References PhQ::DimensionalVector< UnitType, NumericType >::value.
operator+()
template<typename NumericType = double> constexpr Acceleration< NumericType > PhQ::Acceleration< NumericType >::operator+ (const Acceleration< NumericType > & other) const inline constexpr
Definition at line 181 of file Acceleration.hpp.
References PhQ::DimensionalVector< UnitType, NumericType >::value.
operator+=()
template<typename NumericType = double> constexpr void PhQ::Acceleration< NumericType >::operator+= (const Acceleration< NumericType > & other) inline constexpr noexcept
Definition at line 205 of file Acceleration.hpp.
References PhQ::DimensionalVector< UnitType, NumericType >::value.
operator-()
template<typename NumericType = double> constexpr Acceleration< NumericType > PhQ::Acceleration< NumericType >::operator- (const Acceleration< NumericType > & other) const inline constexpr
Definition at line 185 of file Acceleration.hpp.
References PhQ::DimensionalVector< UnitType, NumericType >::value.
operator-=()
template<typename NumericType = double> constexpr void PhQ::Acceleration< NumericType >::operator-= (const Acceleration< NumericType > & other) inline constexpr noexcept
Definition at line 209 of file Acceleration.hpp.
References PhQ::DimensionalVector< UnitType, NumericType >::value.
operator/() [1/2]
template<typename NumericType = double> constexpr Velocity< NumericType > PhQ::Acceleration< NumericType >::operator/ (const Frequency< NumericType > & frequency) const inline constexpr
Definition at line 201 of file Acceleration.hpp.
operator/() [2/2]
template<typename NumericType = double> constexpr Acceleration< NumericType > PhQ::Acceleration< NumericType >::operator/ (const NumericType number) const inline constexpr
Definition at line 197 of file Acceleration.hpp.
References PhQ::DimensionalVector< UnitType, NumericType >::value.
operator/=()
template<typename NumericType = double> constexpr void PhQ::Acceleration< NumericType >::operator/= (const NumericType number) inline constexpr noexcept
Definition at line 217 of file Acceleration.hpp.
References PhQ::DimensionalVector< UnitType, NumericType >::value.
operator=() [1/3]
template<typename NumericType = double> constexpr Acceleration< NumericType > & PhQ::Acceleration< NumericType >::operator= (Acceleration< NumericType > && other) constexpr default noexcept
Move assignment operator. Assigns this acceleration vector by moving another one.
operator=() [2/3]
template<typename NumericType = double> constexpr Acceleration< NumericType > & PhQ::Acceleration< NumericType >::operator= (const Acceleration< NumericType > & other) constexpr default
Copy assignment operator. Assigns this acceleration vector by copying another one.
operator=() [3/3]
template<typename NumericType = double> template<typename OtherNumericType > constexpr Acceleration< NumericType > & PhQ::Acceleration< NumericType >::operator= (const Acceleration< OtherNumericType > & other) inline constexpr
Copy assignment operator. Assigns this acceleration vector by copying another one.
Definition at line 108 of file Acceleration.hpp.
References PhQ::DimensionalVector< UnitType, NumericType >::Value(), and PhQ::DimensionalVector< UnitType, NumericType >::value.
Print() [1/2]
template<typename UnitType , typename NumericType = double> std::string PhQ::DimensionalVector< UnitType, NumericType >::Print () const inline inherited
Prints this physical quantity as a string. This physical quantity's value is expressed in its standard unit of measure.
Definition at line 91 of file DimensionalVector.hpp.
References PhQ::Abbreviation(), and PhQ::DimensionalVector< UnitType, NumericType >::value.
Referenced by PhQ::operator<<(), PhQ::operator<<(), PhQ::operator<<(), PhQ::operator<<(), PhQ::operator<<(), PhQ::operator<<(), PhQ::operator<<(), PhQ::operator<<(), and PhQ::operator<<().
Print() [2/2]
template<typename UnitType , typename NumericType = double> std::string PhQ::DimensionalVector< UnitType, NumericType >::Print (const UnitType unit) const inline inherited
Prints this physical quantity as a string. This physical quantity's value is expressed in the given unit of measure.
Definition at line 97 of file DimensionalVector.hpp.
References PhQ::Abbreviation(), and PhQ::DimensionalVector< UnitType, NumericType >::Value().
SetValue()
template<typename UnitType , typename NumericType = double> constexpr void PhQ::DimensionalVector< UnitType, NumericType >::SetValue (const PhQ::Vector< NumericType > & value) inline constexpr noexcept inherited
Sets the value of this physical quantity expressed in its standard unit of measure to the given value.
Definition at line 85 of file DimensionalVector.hpp.
References PhQ::DimensionalVector< UnitType, NumericType >::value.
StaticValue()
template<typename UnitType , typename NumericType = double> template<UnitType NewUnit> constexpr PhQ::Vector< NumericType > PhQ::DimensionalVector< UnitType, NumericType >::StaticValue () const inline constexpr inherited
Value of this physical quantity expressed in a given unit of measure. This method can be evaluated statically at compile-time.
Definition at line 73 of file DimensionalVector.hpp.
References PhQ::DimensionalVector< UnitType, NumericType >::value.
Unit()
template<typename UnitType , typename NumericType = double> static constexpr UnitType PhQ::DimensionalVector< UnitType, NumericType >::Unit () inline static constexpr inherited
Standard unit of measure for this physical quantity. This physical quantity's value is stored internally in this unit of measure.
Definition at line 56 of file DimensionalVector.hpp.
Value() [1/2]
template<typename UnitType , typename NumericType = double> constexpr const PhQ::Vector< NumericType > & PhQ::DimensionalVector< UnitType, NumericType >::Value () const inline constexpr noexcept inherited
Value of this physical quantity expressed in its standard unit of measure.
Definition at line 61 of file DimensionalVector.hpp.
References PhQ::DimensionalVector< UnitType, NumericType >::value.
Referenced by PhQ::DimensionalVector< UnitType, NumericType >::JSON(), PhQ::Position< NumericType >::operator+(), PhQ::Displacement< NumericType >::operator+(), PhQ::Position< NumericType >::operator-(), PhQ::Displacement< NumericType >::operator-(), PhQ::Acceleration< NumericType >::operator=(), PhQ::DimensionalVector< UnitType, NumericType >::operator=(), PhQ::Displacement< NumericType >::operator=(), PhQ::Force< NumericType >::operator=(), PhQ::HeatFlux< NumericType >::operator=(), PhQ::Position< NumericType >::operator=(), PhQ::TemperatureGradient< NumericType >::operator=(), PhQ::Traction< NumericType >::operator=(), PhQ::VectorArea< NumericType >::operator=(), PhQ::Velocity< NumericType >::operator=(), PhQ::operator==(), PhQ::operator==(), PhQ::operator==(), PhQ::operator==(), PhQ::operator==(), PhQ::operator==(), PhQ::operator==(), PhQ::operator==(), PhQ::operator==(), PhQ::operator==(), PhQ::operator==(), PhQ::operator==(), PhQ::operator==(), PhQ::operator==(), PhQ::operator==(), PhQ::operator==(), PhQ::PlanarAcceleration< NumericType >::PlanarAcceleration(), PhQ::PlanarDisplacement< NumericType >::PlanarDisplacement(), PhQ::PlanarForce< NumericType >::PlanarForce(), PhQ::PlanarHeatFlux< NumericType >::PlanarHeatFlux(), PhQ::PlanarPosition< NumericType >::PlanarPosition(), PhQ::PlanarTemperatureGradient< NumericType >::PlanarTemperatureGradient(), PhQ::PlanarTraction< NumericType >::PlanarTraction(), PhQ::PlanarVelocity< NumericType >::PlanarVelocity(), PhQ::DimensionalVector< UnitType, NumericType >::Print(), PhQ::DimensionalVector< UnitType, NumericType >::XML(), and PhQ::DimensionalVector< UnitType, NumericType >::YAML().
Value() [2/2]
template<typename UnitType , typename NumericType = double> PhQ::Vector< NumericType > PhQ::DimensionalVector< UnitType, NumericType >::Value (const UnitType unit) const inline inherited
Value of this physical quantity expressed in a given unit of measure.
Definition at line 66 of file DimensionalVector.hpp.
References PhQ::Convert(), and PhQ::DimensionalVector< UnitType, NumericType >::value.
x()
template<typename NumericType = double> constexpr ScalarAcceleration< NumericType > PhQ::Acceleration< NumericType >::x () const inline constexpr noexcept
Returns the x Cartesian component of this acceleration vector.
Definition at line 152 of file Acceleration.hpp.
References PhQ::DimensionalVector< UnitType, NumericType >::value.
Referenced by PhQ::Acceleration< NumericType >::Acceleration(), and PhQ::Acceleration< NumericType >::Create().
XML() [1/2]
template<typename UnitType , typename NumericType = double> std::string PhQ::DimensionalVector< UnitType, NumericType >::XML () const inline inherited
Serializes this physical quantity as an XML message. This physical quantity's value is expressed in its standard unit of measure.
Definition at line 123 of file DimensionalVector.hpp.
References PhQ::Abbreviation(), and PhQ::DimensionalVector< UnitType, NumericType >::value.
Referenced by PhQ::DimensionalVector< UnitType, NumericType >::XML().
XML() [2/2]
template<typename UnitType , typename NumericType = double> std::string PhQ::DimensionalVector< UnitType, NumericType >::XML (const UnitType unit) const inline inherited
Serializes this physical quantity as an XML message. This physical quantity's value is expressed in the given unit of measure.
Definition at line 133 of file DimensionalVector.hpp.
References PhQ::Abbreviation(), PhQ::DimensionalVector< UnitType, NumericType >::Value(), and PhQ::DimensionalVector< UnitType, NumericType >::XML().
y()
template<typename NumericType = double> constexpr ScalarAcceleration< NumericType > PhQ::Acceleration< NumericType >::y () const inline constexpr noexcept
Returns the y Cartesian component of this acceleration vector.
Definition at line 157 of file Acceleration.hpp.
References PhQ::DimensionalVector< UnitType, NumericType >::value.
Referenced by PhQ::Acceleration< NumericType >::Acceleration(), and PhQ::Acceleration< NumericType >::Create().
YAML() [1/2]
template<typename UnitType , typename NumericType = double> std::string PhQ::DimensionalVector< UnitType, NumericType >::YAML () const inline inherited
Serializes this physical quantity as a YAML message. This physical quantity's value is expressed in its standard unit of measure.
Definition at line 143 of file DimensionalVector.hpp.
References PhQ::Abbreviation(), and PhQ::DimensionalVector< UnitType, NumericType >::value.
Referenced by PhQ::DimensionalVector< UnitType, NumericType >::YAML().
YAML() [2/2]
template<typename UnitType , typename NumericType = double> std::string PhQ::DimensionalVector< UnitType, NumericType >::YAML (const UnitType unit) const inline inherited
Serializes this physical quantity as a YAML message. This physical quantity's value is expressed in the given unit of measure.
Definition at line 153 of file DimensionalVector.hpp.
References PhQ::Abbreviation(), PhQ::DimensionalVector< UnitType, NumericType >::Value(), and PhQ::DimensionalVector< UnitType, NumericType >::YAML().
z()
template<typename NumericType = double> constexpr ScalarAcceleration< NumericType > PhQ::Acceleration< NumericType >::z () const inline constexpr noexcept
Returns the z Cartesian component of this acceleration vector.
Definition at line 162 of file Acceleration.hpp.
References PhQ::DimensionalVector< UnitType, NumericType >::value.
Referenced by PhQ::Acceleration< NumericType >::Acceleration(), and PhQ::Acceleration< NumericType >::Create().
Zero()
template<typename NumericType = double> static constexpr Acceleration< NumericType > PhQ::Acceleration< NumericType >::Zero () inline static constexpr
Statically creates an acceleration vector of zero.
Definition at line 118 of file Acceleration.hpp.
References PhQ::Vector< NumericType >::Zero().
Member Data Documentation
value
template<typename UnitType , typename NumericType = double> PhQ::Vector<NumericType> PhQ::DimensionalVector< UnitType, NumericType >::value protected inherited
Value of this physical quantity expressed in its standard unit of measure.
Definition at line 217 of file DimensionalVector.hpp.
Referenced by PhQ::Acceleration< NumericType >::Create(), PhQ::Displacement< NumericType >::Create(), PhQ::Force< NumericType >::Create(), PhQ::HeatFlux< NumericType >::Create(), PhQ::Position< NumericType >::Create(), PhQ::TemperatureGradient< NumericType >::Create(), PhQ::Traction< NumericType >::Create(), PhQ::VectorArea< NumericType >::Create(), PhQ::Velocity< NumericType >::Create(), PhQ::Acceleration< NumericType >::Direction(), PhQ::Displacement< NumericType >::Direction(), PhQ::Force< NumericType >::Direction(), PhQ::HeatFlux< NumericType >::Direction(), PhQ::Position< NumericType >::Direction(), PhQ::TemperatureGradient< NumericType >::Direction(), PhQ::Traction< NumericType >::Direction(), PhQ::VectorArea< NumericType >::Direction(), PhQ::Velocity< NumericType >::Direction(), PhQ::DimensionalVector< UnitType, NumericType >::JSON(), PhQ::Acceleration< NumericType >::Magnitude(), PhQ::Displacement< NumericType >::Magnitude(), PhQ::Force< NumericType >::Magnitude(), PhQ::HeatFlux< NumericType >::Magnitude(), PhQ::Position< NumericType >::Magnitude(), PhQ::TemperatureGradient< NumericType >::Magnitude(), PhQ::Traction< NumericType >::Magnitude(), PhQ::VectorArea< NumericType >::Magnitude(), PhQ::Velocity< NumericType >::Magnitude(), PhQ::DimensionalVector< UnitType, NumericType >::MutableValue(), PhQ::Acceleration< NumericType >::operator*(), PhQ::Displacement< NumericType >::operator*(), PhQ::Force< NumericType >::operator*(), PhQ::HeatFlux< NumericType >::operator*(), PhQ::Position< NumericType >::operator*(), PhQ::TemperatureGradient< NumericType >::operator*(), PhQ::Traction< NumericType >::operator*(), PhQ::VectorArea< NumericType >::operator*(), PhQ::Velocity< NumericType >::operator*(), PhQ::Acceleration< NumericType >::operator*=(), PhQ::Displacement< NumericType >::operator*=(), PhQ::Force< NumericType >::operator*=(), PhQ::HeatFlux< NumericType >::operator*=(), PhQ::Position< NumericType >::operator*=(), PhQ::TemperatureGradient< NumericType >::operator*=(), PhQ::Traction< NumericType >::operator*=(), PhQ::VectorArea< NumericType >::operator*=(), PhQ::Velocity< NumericType >::operator*=(), PhQ::Acceleration< NumericType >::operator+(), PhQ::Displacement< NumericType >::operator+(), PhQ::Position< NumericType >::operator+(), PhQ::Force< NumericType >::operator+(), PhQ::HeatFlux< NumericType >::operator+(), PhQ::Position< NumericType >::operator+(), PhQ::TemperatureGradient< NumericType >::operator+(), PhQ::Traction< NumericType >::operator+(), PhQ::VectorArea< NumericType >::operator+(), PhQ::Velocity< NumericType >::operator+(), PhQ::Acceleration< NumericType >::operator+=(), PhQ::Displacement< NumericType >::operator+=(), PhQ::Position< NumericType >::operator+=(), PhQ::Force< NumericType >::operator+=(), PhQ::HeatFlux< NumericType >::operator+=(), PhQ::Position< NumericType >::operator+=(), PhQ::TemperatureGradient< NumericType >::operator+=(), PhQ::Traction< NumericType >::operator+=(), PhQ::VectorArea< NumericType >::operator+=(), PhQ::Velocity< NumericType >::operator+=(), PhQ::Acceleration< NumericType >::operator-(), PhQ::Displacement< NumericType >::operator-(), PhQ::Position< NumericType >::operator-(), PhQ::Force< NumericType >::operator-(), PhQ::HeatFlux< NumericType >::operator-(), PhQ::Position< NumericType >::operator-(), PhQ::TemperatureGradient< NumericType >::operator-(), PhQ::Traction< NumericType >::operator-(), PhQ::VectorArea< NumericType >::operator-(), PhQ::Velocity< NumericType >::operator-(), PhQ::Acceleration< NumericType >::operator-=(), PhQ::Displacement< NumericType >::operator-=(), PhQ::Position< NumericType >::operator-=(), PhQ::Force< NumericType >::operator-=(), PhQ::HeatFlux< NumericType >::operator-=(), PhQ::Position< NumericType >::operator-=(), PhQ::TemperatureGradient< NumericType >::operator-=(), PhQ::Traction< NumericType >::operator-=(), PhQ::VectorArea< NumericType >::operator-=(), PhQ::Velocity< NumericType >::operator-=(), PhQ::Acceleration< NumericType >::operator/(), PhQ::Displacement< NumericType >::operator/(), PhQ::Force< NumericType >::operator/(), PhQ::HeatFlux< NumericType >::operator/(), PhQ::Position< NumericType >::operator/(), PhQ::TemperatureGradient< NumericType >::operator/(), PhQ::Traction< NumericType >::operator/(), PhQ::VectorArea< NumericType >::operator/(), PhQ::Velocity< NumericType >::operator/(), PhQ::Acceleration< NumericType >::operator/=(), PhQ::Displacement< NumericType >::operator/=(), PhQ::Force< NumericType >::operator/=(), PhQ::HeatFlux< NumericType >::operator/=(), PhQ::Position< NumericType >::operator/=(), PhQ::TemperatureGradient< NumericType >::operator/=(), PhQ::Traction< NumericType >::operator/=(), PhQ::VectorArea< NumericType >::operator/=(), PhQ::Velocity< NumericType >::operator/=(), PhQ::Acceleration< NumericType >::operator=(), PhQ::DimensionalVector< UnitType, NumericType >::operator=(), PhQ::Displacement< NumericType >::operator=(), PhQ::Force< NumericType >::operator=(), PhQ::HeatFlux< NumericType >::operator=(), PhQ::Position< NumericType >::operator=(), PhQ::TemperatureGradient< NumericType >::operator=(), PhQ::Traction< NumericType >::operator=(), PhQ::VectorArea< NumericType >::operator=(), PhQ::Velocity< NumericType >::operator=(), PhQ::DimensionalVector< UnitType, NumericType >::Print(), PhQ::DimensionalVector< UnitType, NumericType >::SetValue(), PhQ::DimensionalVector< UnitType, NumericType >::StaticValue(), PhQ::DimensionalVector< UnitType, NumericType >::Value(), PhQ::DimensionalVector< UnitType, NumericType >::Value(), PhQ::Acceleration< NumericType >::x(), PhQ::Displacement< NumericType >::x(), PhQ::Force< NumericType >::x(), PhQ::HeatFlux< NumericType >::x(), PhQ::Position< NumericType >::x(), PhQ::TemperatureGradient< NumericType >::x(), PhQ::Traction< NumericType >::x(), PhQ::VectorArea< NumericType >::x(), PhQ::Velocity< NumericType >::x(), PhQ::DimensionalVector< UnitType, NumericType >::XML(), PhQ::Acceleration< NumericType >::y(), PhQ::Displacement< NumericType >::y(), PhQ::Force< NumericType >::y(), PhQ::HeatFlux< NumericType >::y(), PhQ::Position< NumericType >::y(), PhQ::TemperatureGradient< NumericType >::y(), PhQ::Traction< NumericType >::y(), PhQ::VectorArea< NumericType >::y(), PhQ::Velocity< NumericType >::y(), PhQ::DimensionalVector< UnitType, NumericType >::YAML(), PhQ::Acceleration< NumericType >::z(), PhQ::Displacement< NumericType >::z(), PhQ::Force< NumericType >::z(), PhQ::HeatFlux< NumericType >::z(), PhQ::Position< NumericType >::z(), PhQ::TemperatureGradient< NumericType >::z(), PhQ::Traction< NumericType >::z(), PhQ::VectorArea< NumericType >::z(), and PhQ::Velocity< NumericType >::z().
The documentation for this class was generated from the following file:
PhQ/Acceleration.hpp