Physical Quantities: PhQ::PlanarPosition< NumericType > Class Template Reference
PhQ::PlanarPosition< NumericType > Class Template Reference
Two-dimensional Euclidean position vector in the XY plane. Contains two components in Cartesian coordinates: x and y. Position is not to be confused with displacement; for a two-dimensional Euclidean displacement vector in the XY plane, see PhQ::PlanarDisplacement. For a three-dimensional Euclidean position vector, see PhQ::Position. For scalar position components or for the magnitude of a position vector, see PhQ::Length.
#include "PlanarPosition.hpp"
Public Member Functions
PlanarPosition ()=default
Default constructor. Constructs a planar position vector with an uninitialized value.
PlanarPosition (const PlanarVector< NumericType > &value, const Unit::Length unit)
Constructor. Constructs a planar position vector with a given value expressed in a given length unit.
PlanarPosition (const Length< NumericType > &x, const Length< NumericType > &y)
Constructor. Constructs a planar position vector from a given set of length components.
constexpr PlanarPosition (const Length< NumericType > &length, const PlanarDirection< NumericType > &planar_direction)
Constructor. Constructs a planar position vector from a given length and planar direction.
constexpr PlanarPosition (const Position< NumericType > &position)
Constructor. Constructs a planar position vector from a given position vector by projecting the position vector onto the XY plane.
constexpr PlanarPosition (const PlanarDisplacement< NumericType > &planar_displacement)
Constructor. Constructs a planar position vector from a given planar displacement vector from the origin.
~PlanarPosition () noexcept=default
Destructor. Destroys this planar position vector.
constexpr PlanarPosition (const PlanarPosition< NumericType > &other)=default
Copy constructor. Constructs a planar position vector by copying another one.
template<typename OtherNumericType >
constexpr PlanarPosition (const PlanarPosition< OtherNumericType > &other)
Copy constructor. Constructs a planar position by copying another one.
constexpr PlanarPosition (PlanarPosition< NumericType > &&other) noexcept=default
Move constructor. Constructs a planar position vector by moving another one.
constexpr PlanarPosition< NumericType > & operator= (const PlanarPosition< NumericType > &other)=default
Copy assignment operator. Assigns this planar position vector by copying another one.
template<typename OtherNumericType >
constexpr PlanarPosition< NumericType > & operator= (const PlanarPosition< OtherNumericType > &other)
Copy assignment operator. Assigns this planar position by copying another one.
constexpr PlanarPosition< NumericType > & operator= (PlanarPosition< NumericType > &&other) noexcept=default
Move assignment operator. Assigns this planar position vector by moving another one.
constexpr Length< NumericType > x () const noexcept
Returns the x Cartesian component of this planar position vector.
constexpr Length< NumericType > y () const noexcept
Returns the y Cartesian component of this planar position vector.
Length< NumericType > Magnitude () const
Returns the magnitude of this planar position vector.
PhQ::PlanarDirection< NumericType > PlanarDirection () const
Returns the planar direction of this planar position vector.
PhQ::Angle< NumericType > Angle (const PlanarPosition< NumericType > &planar_position) const
Returns the angle between this planar position vector and another one.
constexpr PlanarPosition< NumericType > operator+ (const PlanarPosition< NumericType > &planar_position) const
constexpr PlanarPosition< NumericType > operator+ (const PlanarDisplacement< NumericType > &planar_displacement) const
constexpr PlanarDisplacement< NumericType > operator- (const PlanarPosition< NumericType > &planar_position) const
constexpr PlanarPosition< NumericType > operator- (const PlanarDisplacement< NumericType > &planar_displacement) const
constexpr PlanarPosition< NumericType > operator* (const NumericType number) const
constexpr PlanarPosition< NumericType > operator/ (const NumericType number) const
constexpr void operator+= (const PlanarPosition< NumericType > &planar_position) noexcept
constexpr void operator+= (const PlanarDisplacement< NumericType > &planar_displacement) noexcept
constexpr void operator-= (const PlanarPosition< NumericType > &planar_position) noexcept
constexpr void operator-= (const PlanarDisplacement< NumericType > &planar_displacement) noexcept
constexpr void operator*= (const NumericType number) noexcept
constexpr void operator/= (const NumericType number) noexcept
constexpr const PhQ::PlanarVector< NumericType > & Value () const noexcept
Value of this physical quantity expressed in its standard unit of measure.
PhQ::PlanarVector< NumericType > Value (const UnitType unit) const
Value of this physical quantity expressed in a given unit of measure.
template<UnitType NewUnit>
constexpr PhQ::PlanarVector< NumericType > StaticValue () const
Value of this physical quantity expressed in a given unit of measure. This method can be evaluated statically at compile-time.
constexpr PhQ::PlanarVector< NumericType > & MutableValue () noexcept
Returns the value of this physical quantity expressed in its standard unit of measure as a mutable value.
constexpr void SetValue (const PhQ::PlanarVector< NumericType > &value) noexcept
Sets the value of this physical quantity expressed in its standard unit of measure to the given value.
std::string Print () const
Prints this physical quantity as a string. This physical quantity's value is expressed in its standard unit of measure.
std::string Print (const UnitType unit) const
Prints this physical quantity as a string. This physical quantity's value is expressed in the given unit of measure.
std::string JSON () const
Serializes this physical quantity as a JSON message. This physical quantity's value is expressed in its standard unit of measure.
std::string JSON (const UnitType unit) const
Serializes this physical quantity as a JSON message. This physical quantity's value is expressed in the given unit of measure.
std::string XML () const
Serializes this physical quantity as an XML message. This physical quantity's value is expressed in its standard unit of measure.
std::string XML (const UnitType unit) const
Serializes this physical quantity as an XML message. This physical quantity's value is expressed in the given unit of measure.
std::string YAML () const
Serializes this physical quantity as a YAML message. This physical quantity's value is expressed in its standard unit of measure.
std::string YAML (const UnitType unit) const
Serializes this physical quantity as a YAML message. This physical quantity's value is expressed in the given unit of measure.
Static Public Member Functions
static constexpr PlanarPosition< NumericType > Zero ()
Statically creates a planar position vector of zero.
template<Unit::Length Unit>
static constexpr PlanarPosition< NumericType > Create (const NumericType x, const NumericType y)
Statically creates a planar position vector from the given x and y Cartesian components expressed in a given length unit.
template<Unit::Length Unit>
static constexpr PlanarPosition< NumericType > Create (const std::array< NumericType, 2 > &x_y)
Statically creates a planar position vector from the given x and y Cartesian components expressed in a given length unit.
template<Unit::Length Unit>
static constexpr PlanarPosition< NumericType > Create (const PlanarVector< NumericType > &value)
Statically creates a planar position vector with a given value expressed in a given length unit.
static constexpr const PhQ::Dimensions & Dimensions ()
Physical dimension set of this physical quantity.
static constexpr UnitType Unit ()
Standard unit of measure for this physical quantity. This physical quantity's value is stored internally in this unit of measure.
Protected Attributes
PhQ::PlanarVector< NumericType > value
Value of this physical quantity expressed in its standard unit of measure.
Private Member Functions
constexpr PlanarPosition (const PlanarVector< NumericType > &value)
Constructor. Constructs a planar position vector with a given value expressed in the standard length unit.
Friends
template<typename OtherNumericType >
class PlanarDisplacement
Detailed Description
template<typename NumericType = double>
class PhQ::PlanarPosition< NumericType >
Two-dimensional Euclidean position vector in the XY plane. Contains two components in Cartesian coordinates: x and y. Position is not to be confused with displacement; for a two-dimensional Euclidean displacement vector in the XY plane, see PhQ::PlanarDisplacement. For a three-dimensional Euclidean position vector, see PhQ::Position. For scalar position components or for the magnitude of a position vector, see PhQ::Length.
Definition at line 49 of file PlanarPosition.hpp.
Constructor & Destructor Documentation
PlanarPosition() [1/10]
template<typename NumericType = double> PhQ::PlanarPosition< NumericType >::PlanarPosition () default
Default constructor. Constructs a planar position vector with an uninitialized value.
PlanarPosition() [2/10]
template<typename NumericType = double> PhQ::PlanarPosition< NumericType >::PlanarPosition (const PlanarVector< NumericType > & value, const Unit::Length unit) inline
Constructor. Constructs a planar position vector with a given value expressed in a given length unit.
Definition at line 56 of file PlanarPosition.hpp.
PlanarPosition() [3/10]
template<typename NumericType = double> PhQ::PlanarPosition< NumericType >::PlanarPosition (const Length< NumericType > & x, const Length< NumericType > & y) inline
Constructor. Constructs a planar position vector from a given set of length components.
Definition at line 60 of file PlanarPosition.hpp.
References PhQ::PlanarPosition< NumericType >::x(), and PhQ::PlanarPosition< NumericType >::y().
PlanarPosition() [4/10]
template<typename NumericType = double> constexpr PhQ::PlanarPosition< NumericType >::PlanarPosition (const Length< NumericType > & length, const PlanarDirection< NumericType > & planar_direction) inline constexpr
Constructor. Constructs a planar position vector from a given length and planar direction.
Definition at line 65 of file PlanarPosition.hpp.
PlanarPosition() [5/10]
template<typename NumericType > constexpr PhQ::PlanarPosition< NumericType >::PlanarPosition (const Position< NumericType > & position) inline explicit constexpr
Constructor. Constructs a planar position vector from a given position vector by projecting the position vector onto the XY plane.
Definition at line 310 of file Position.hpp.
References PhQ::DimensionalVector< UnitType, NumericType >::Value().
PlanarPosition() [6/10]
template<typename NumericType = double> constexpr PhQ::PlanarPosition< NumericType >::PlanarPosition (const PlanarDisplacement< NumericType > & planar_displacement) inline explicit constexpr
Constructor. Constructs a planar position vector from a given planar displacement vector from the origin.
Definition at line 75 of file PlanarPosition.hpp.
~PlanarPosition()
template<typename NumericType = double> PhQ::PlanarPosition< NumericType >::~PlanarPosition () default noexcept
Destructor. Destroys this planar position vector.
PlanarPosition() [7/10]
template<typename NumericType = double> constexpr PhQ::PlanarPosition< NumericType >::PlanarPosition (const PlanarPosition< NumericType > & other) constexpr default
Copy constructor. Constructs a planar position vector by copying another one.
PlanarPosition() [8/10]
template<typename NumericType = double> template<typename OtherNumericType > constexpr PhQ::PlanarPosition< NumericType >::PlanarPosition (const PlanarPosition< OtherNumericType > & other) inline explicit constexpr
Copy constructor. Constructs a planar position by copying another one.
Definition at line 86 of file PlanarPosition.hpp.
PlanarPosition() [9/10]
template<typename NumericType = double> constexpr PhQ::PlanarPosition< NumericType >::PlanarPosition (PlanarPosition< NumericType > && other) constexpr default noexcept
Move constructor. Constructs a planar position vector by moving another one.
PlanarPosition() [10/10]
template<typename NumericType = double> constexpr PhQ::PlanarPosition< NumericType >::PlanarPosition (const PlanarVector< NumericType > & value) inline explicit constexpr private
Constructor. Constructs a planar position vector with a given value expressed in the standard length unit.
Definition at line 222 of file PlanarPosition.hpp.
Member Function Documentation
Angle()
template<typename NumericType = double> PhQ::Angle< NumericType > PhQ::PlanarPosition< NumericType >::Angle (const PlanarPosition< NumericType > & planar_position) const inline
Returns the angle between this planar position vector and another one.
Definition at line 162 of file PlanarPosition.hpp.
Create() [1/3]
template<typename NumericType = double> template<Unit::Length Unit> static constexpr PlanarPosition< NumericType > PhQ::PlanarPosition< NumericType >::Create (const NumericType x, const NumericType y) inline static constexpr
Statically creates a planar position vector from the given x and y Cartesian components expressed in a given length unit.
Definition at line 115 of file PlanarPosition.hpp.
References PhQ::PlanarPosition< NumericType >::x(), and PhQ::PlanarPosition< NumericType >::y().
Create() [2/3]
template<typename NumericType = double> template<Unit::Length Unit> static constexpr PlanarPosition< NumericType > PhQ::PlanarPosition< NumericType >::Create (const PlanarVector< NumericType > & value) inline static constexpr
Statically creates a planar position vector with a given value expressed in a given length unit.
Definition at line 135 of file PlanarPosition.hpp.
References PhQ::DimensionalPlanarVector< UnitType, NumericType >::value.
Create() [3/3]
template<typename NumericType = double> template<Unit::Length Unit> static constexpr PlanarPosition< NumericType > PhQ::PlanarPosition< NumericType >::Create (const std::array< NumericType, 2 > & x_y) inline static constexpr
Statically creates a planar position vector from the given x and y Cartesian components expressed in a given length unit.
Definition at line 125 of file PlanarPosition.hpp.
Dimensions()
template<typename UnitType , typename NumericType = double> static constexpr const PhQ::Dimensions & PhQ::DimensionalPlanarVector< UnitType, NumericType >::Dimensions () inline static constexpr inherited
Physical dimension set of this physical quantity.
Definition at line 50 of file DimensionalPlanarVector.hpp.
JSON() [1/2]
template<typename UnitType , typename NumericType = double> std::string PhQ::DimensionalPlanarVector< UnitType, NumericType >::JSON () const inline inherited
Serializes this physical quantity as a JSON message. This physical quantity's value is expressed in its standard unit of measure.
Definition at line 103 of file DimensionalPlanarVector.hpp.
References PhQ::Abbreviation(), and PhQ::DimensionalPlanarVector< UnitType, NumericType >::value.
Referenced by PhQ::DimensionalPlanarVector< UnitType, NumericType >::JSON().
JSON() [2/2]
template<typename UnitType , typename NumericType = double> std::string PhQ::DimensionalPlanarVector< UnitType, NumericType >::JSON (const UnitType unit) const inline inherited
Serializes this physical quantity as a JSON message. This physical quantity's value is expressed in the given unit of measure.
Definition at line 113 of file DimensionalPlanarVector.hpp.
References PhQ::Abbreviation(), PhQ::DimensionalPlanarVector< UnitType, NumericType >::JSON(), and PhQ::DimensionalPlanarVector< UnitType, NumericType >::Value().
Magnitude()
template<typename NumericType = double> Length< NumericType > PhQ::PlanarPosition< NumericType >::Magnitude () const inline
Returns the magnitude of this planar position vector.
Definition at line 152 of file PlanarPosition.hpp.
References PhQ::DimensionalPlanarVector< UnitType, NumericType >::value.
MutableValue()
template<typename UnitType , typename NumericType = double> constexpr PhQ::PlanarVector< NumericType > & PhQ::DimensionalPlanarVector< UnitType, NumericType >::MutableValue () inline constexpr noexcept inherited
Returns the value of this physical quantity expressed in its standard unit of measure as a mutable value.
Definition at line 79 of file DimensionalPlanarVector.hpp.
References PhQ::DimensionalPlanarVector< UnitType, NumericType >::value.
operator*()
template<typename NumericType = double> constexpr PlanarPosition< NumericType > PhQ::PlanarPosition< NumericType >::operator* (const NumericType number) const inline constexpr
Definition at line 187 of file PlanarPosition.hpp.
References PhQ::DimensionalPlanarVector< UnitType, NumericType >::value.
operator*=()
template<typename NumericType = double> constexpr void PhQ::PlanarPosition< NumericType >::operator*= (const NumericType number) inline constexpr noexcept
Definition at line 211 of file PlanarPosition.hpp.
References PhQ::DimensionalPlanarVector< UnitType, NumericType >::value.
operator+() [1/2]
template<typename NumericType = double> constexpr PlanarPosition< NumericType > PhQ::PlanarPosition< NumericType >::operator+ (const PlanarDisplacement< NumericType > & planar_displacement) const inline constexpr
Definition at line 172 of file PlanarPosition.hpp.
References PhQ::DimensionalPlanarVector< UnitType, NumericType >::Value(), and PhQ::DimensionalPlanarVector< UnitType, NumericType >::value.
operator+() [2/2]
template<typename NumericType = double> constexpr PlanarPosition< NumericType > PhQ::PlanarPosition< NumericType >::operator+ (const PlanarPosition< NumericType > & planar_position) const inline constexpr
Definition at line 167 of file PlanarPosition.hpp.
References PhQ::DimensionalPlanarVector< UnitType, NumericType >::value.
operator+=() [1/2]
template<typename NumericType = double> constexpr void PhQ::PlanarPosition< NumericType >::operator+= (const PlanarDisplacement< NumericType > & planar_displacement) inline constexpr noexcept
Definition at line 199 of file PlanarPosition.hpp.
References PhQ::DimensionalPlanarVector< UnitType, NumericType >::value.
operator+=() [2/2]
template<typename NumericType = double> constexpr void PhQ::PlanarPosition< NumericType >::operator+= (const PlanarPosition< NumericType > & planar_position) inline constexpr noexcept
Definition at line 195 of file PlanarPosition.hpp.
References PhQ::DimensionalPlanarVector< UnitType, NumericType >::value.
operator-() [1/2]
template<typename NumericType = double> constexpr PlanarPosition< NumericType > PhQ::PlanarPosition< NumericType >::operator- (const PlanarDisplacement< NumericType > & planar_displacement) const inline constexpr
Definition at line 182 of file PlanarPosition.hpp.
References PhQ::DimensionalPlanarVector< UnitType, NumericType >::Value(), and PhQ::DimensionalPlanarVector< UnitType, NumericType >::value.
operator-() [2/2]
template<typename NumericType = double> constexpr PlanarDisplacement< NumericType > PhQ::PlanarPosition< NumericType >::operator- (const PlanarPosition< NumericType > & planar_position) const inline constexpr
Definition at line 177 of file PlanarPosition.hpp.
References PhQ::DimensionalPlanarVector< UnitType, NumericType >::value.
operator-=() [1/2]
template<typename NumericType = double> constexpr void PhQ::PlanarPosition< NumericType >::operator-= (const PlanarDisplacement< NumericType > & planar_displacement) inline constexpr noexcept
Definition at line 207 of file PlanarPosition.hpp.
References PhQ::DimensionalPlanarVector< UnitType, NumericType >::value.
operator-=() [2/2]
template<typename NumericType = double> constexpr void PhQ::PlanarPosition< NumericType >::operator-= (const PlanarPosition< NumericType > & planar_position) inline constexpr noexcept
Definition at line 203 of file PlanarPosition.hpp.
References PhQ::DimensionalPlanarVector< UnitType, NumericType >::value.
operator/()
template<typename NumericType = double> constexpr PlanarPosition< NumericType > PhQ::PlanarPosition< NumericType >::operator/ (const NumericType number) const inline constexpr
Definition at line 191 of file PlanarPosition.hpp.
References PhQ::DimensionalPlanarVector< UnitType, NumericType >::value.
operator/=()
template<typename NumericType = double> constexpr void PhQ::PlanarPosition< NumericType >::operator/= (const NumericType number) inline constexpr noexcept
Definition at line 215 of file PlanarPosition.hpp.
References PhQ::DimensionalPlanarVector< UnitType, NumericType >::value.
operator=() [1/3]
template<typename NumericType = double> constexpr PlanarPosition< NumericType > & PhQ::PlanarPosition< NumericType >::operator= (const PlanarPosition< NumericType > & other) constexpr default
Copy assignment operator. Assigns this planar position vector by copying another one.
operator=() [2/3]
template<typename NumericType = double> template<typename OtherNumericType > constexpr PlanarPosition< NumericType > & PhQ::PlanarPosition< NumericType >::operator= (const PlanarPosition< OtherNumericType > & other) inline constexpr
Copy assignment operator. Assigns this planar position by copying another one.
Definition at line 98 of file PlanarPosition.hpp.
References PhQ::DimensionalPlanarVector< UnitType, NumericType >::Value(), and PhQ::DimensionalPlanarVector< UnitType, NumericType >::value.
operator=() [3/3]
template<typename NumericType = double> constexpr PlanarPosition< NumericType > & PhQ::PlanarPosition< NumericType >::operator= (PlanarPosition< NumericType > && other) constexpr default noexcept
Move assignment operator. Assigns this planar position vector by moving another one.
PlanarDirection()
template<typename NumericType = double> PhQ::PlanarDirection< NumericType > PhQ::PlanarPosition< NumericType >::PlanarDirection () const inline
Returns the planar direction of this planar position vector.
Definition at line 157 of file PlanarPosition.hpp.
References PhQ::DimensionalPlanarVector< UnitType, NumericType >::value.
Print() [1/2]
template<typename UnitType , typename NumericType = double> std::string PhQ::DimensionalPlanarVector< UnitType, NumericType >::Print () const inline inherited
Prints this physical quantity as a string. This physical quantity's value is expressed in its standard unit of measure.
Definition at line 91 of file DimensionalPlanarVector.hpp.
References PhQ::Abbreviation(), and PhQ::DimensionalPlanarVector< UnitType, NumericType >::value.
Referenced by PhQ::operator<<(), PhQ::operator<<(), PhQ::operator<<(), PhQ::operator<<(), PhQ::operator<<(), PhQ::operator<<(), PhQ::operator<<(), and PhQ::operator<<().
Print() [2/2]
template<typename UnitType , typename NumericType = double> std::string PhQ::DimensionalPlanarVector< UnitType, NumericType >::Print (const UnitType unit) const inline inherited
Prints this physical quantity as a string. This physical quantity's value is expressed in the given unit of measure.
Definition at line 97 of file DimensionalPlanarVector.hpp.
References PhQ::Abbreviation(), and PhQ::DimensionalPlanarVector< UnitType, NumericType >::Value().
SetValue()
template<typename UnitType , typename NumericType = double> constexpr void PhQ::DimensionalPlanarVector< UnitType, NumericType >::SetValue (const PhQ::PlanarVector< NumericType > & value) inline constexpr noexcept inherited
Sets the value of this physical quantity expressed in its standard unit of measure to the given value.
Definition at line 85 of file DimensionalPlanarVector.hpp.
References PhQ::DimensionalPlanarVector< UnitType, NumericType >::value.
StaticValue()
template<typename UnitType , typename NumericType = double> template<UnitType NewUnit> constexpr PhQ::PlanarVector< NumericType > PhQ::DimensionalPlanarVector< UnitType, NumericType >::StaticValue () const inline constexpr inherited
Value of this physical quantity expressed in a given unit of measure. This method can be evaluated statically at compile-time.
Definition at line 73 of file DimensionalPlanarVector.hpp.
References PhQ::DimensionalPlanarVector< UnitType, NumericType >::value.
Unit()
template<typename UnitType , typename NumericType = double> static constexpr UnitType PhQ::DimensionalPlanarVector< UnitType, NumericType >::Unit () inline static constexpr inherited
Standard unit of measure for this physical quantity. This physical quantity's value is stored internally in this unit of measure.
Definition at line 56 of file DimensionalPlanarVector.hpp.
Value() [1/2]
template<typename UnitType , typename NumericType = double> constexpr const PhQ::PlanarVector< NumericType > & PhQ::DimensionalPlanarVector< UnitType, NumericType >::Value () const inline constexpr noexcept inherited
Value of this physical quantity expressed in its standard unit of measure.
Definition at line 61 of file DimensionalPlanarVector.hpp.
References PhQ::DimensionalPlanarVector< UnitType, NumericType >::value.
Referenced by PhQ::Acceleration< NumericType >::Acceleration(), PhQ::Displacement< NumericType >::Displacement(), PhQ::Force< NumericType >::Force(), PhQ::HeatFlux< NumericType >::HeatFlux(), PhQ::DimensionalPlanarVector< UnitType, NumericType >::JSON(), PhQ::PlanarPosition< NumericType >::operator+(), PhQ::PlanarDisplacement< NumericType >::operator+(), PhQ::PlanarPosition< NumericType >::operator-(), PhQ::PlanarDisplacement< NumericType >::operator-(), PhQ::DimensionalPlanarVector< UnitType, NumericType >::operator=(), PhQ::PlanarAcceleration< NumericType >::operator=(), PhQ::PlanarDisplacement< NumericType >::operator=(), PhQ::PlanarForce< NumericType >::operator=(), PhQ::PlanarHeatFlux< NumericType >::operator=(), PhQ::PlanarPosition< NumericType >::operator=(), PhQ::PlanarTemperatureGradient< NumericType >::operator=(), PhQ::PlanarTraction< NumericType >::operator=(), PhQ::PlanarVelocity< NumericType >::operator=(), PhQ::operator==(), PhQ::operator==(), PhQ::PlanarHeatFlux< NumericType >::PlanarHeatFlux(), PhQ::Position< NumericType >::Position(), PhQ::DimensionalPlanarVector< UnitType, NumericType >::Print(), PhQ::TemperatureGradient< NumericType >::TemperatureGradient(), PhQ::Traction< NumericType >::Traction(), PhQ::Velocity< NumericType >::Velocity(), PhQ::DimensionalPlanarVector< UnitType, NumericType >::XML(), and PhQ::DimensionalPlanarVector< UnitType, NumericType >::YAML().
Value() [2/2]
template<typename UnitType , typename NumericType = double> PhQ::PlanarVector< NumericType > PhQ::DimensionalPlanarVector< UnitType, NumericType >::Value (const UnitType unit) const inline inherited
Value of this physical quantity expressed in a given unit of measure.
Definition at line 66 of file DimensionalPlanarVector.hpp.
References PhQ::Convert(), and PhQ::DimensionalPlanarVector< UnitType, NumericType >::value.
x()
template<typename NumericType = double> constexpr Length< NumericType > PhQ::PlanarPosition< NumericType >::x () const inline constexpr noexcept
Returns the x Cartesian component of this planar position vector.
Definition at line 142 of file PlanarPosition.hpp.
References PhQ::DimensionalPlanarVector< UnitType, NumericType >::value.
Referenced by PhQ::PlanarPosition< NumericType >::Create(), and PhQ::PlanarPosition< NumericType >::PlanarPosition().
XML() [1/2]
template<typename UnitType , typename NumericType = double> std::string PhQ::DimensionalPlanarVector< UnitType, NumericType >::XML () const inline inherited
Serializes this physical quantity as an XML message. This physical quantity's value is expressed in its standard unit of measure.
Definition at line 123 of file DimensionalPlanarVector.hpp.
References PhQ::Abbreviation(), and PhQ::DimensionalPlanarVector< UnitType, NumericType >::value.
Referenced by PhQ::DimensionalPlanarVector< UnitType, NumericType >::XML().
XML() [2/2]
template<typename UnitType , typename NumericType = double> std::string PhQ::DimensionalPlanarVector< UnitType, NumericType >::XML (const UnitType unit) const inline inherited
Serializes this physical quantity as an XML message. This physical quantity's value is expressed in the given unit of measure.
Definition at line 133 of file DimensionalPlanarVector.hpp.
References PhQ::Abbreviation(), PhQ::DimensionalPlanarVector< UnitType, NumericType >::Value(), and PhQ::DimensionalPlanarVector< UnitType, NumericType >::XML().
y()
template<typename NumericType = double> constexpr Length< NumericType > PhQ::PlanarPosition< NumericType >::y () const inline constexpr noexcept
Returns the y Cartesian component of this planar position vector.
Definition at line 147 of file PlanarPosition.hpp.
References PhQ::DimensionalPlanarVector< UnitType, NumericType >::value.
Referenced by PhQ::PlanarPosition< NumericType >::Create(), and PhQ::PlanarPosition< NumericType >::PlanarPosition().
YAML() [1/2]
template<typename UnitType , typename NumericType = double> std::string PhQ::DimensionalPlanarVector< UnitType, NumericType >::YAML () const inline inherited
Serializes this physical quantity as a YAML message. This physical quantity's value is expressed in its standard unit of measure.
Definition at line 143 of file DimensionalPlanarVector.hpp.
References PhQ::Abbreviation(), and PhQ::DimensionalPlanarVector< UnitType, NumericType >::value.
Referenced by PhQ::DimensionalPlanarVector< UnitType, NumericType >::YAML().
YAML() [2/2]
template<typename UnitType , typename NumericType = double> std::string PhQ::DimensionalPlanarVector< UnitType, NumericType >::YAML (const UnitType unit) const inline inherited
Serializes this physical quantity as a YAML message. This physical quantity's value is expressed in the given unit of measure.
Definition at line 153 of file DimensionalPlanarVector.hpp.
References PhQ::Abbreviation(), PhQ::DimensionalPlanarVector< UnitType, NumericType >::Value(), and PhQ::DimensionalPlanarVector< UnitType, NumericType >::YAML().
Zero()
template<typename NumericType = double> static constexpr PlanarPosition< NumericType > PhQ::PlanarPosition< NumericType >::Zero () inline static constexpr
Statically creates a planar position vector of zero.
Definition at line 108 of file PlanarPosition.hpp.
References PhQ::PlanarVector< NumericType >::Zero().
Friends And Related Symbol Documentation
PlanarDisplacement
template<typename NumericType = double> template<typename OtherNumericType > friend class PlanarDisplacement friend
Definition at line 226 of file PlanarPosition.hpp.
Member Data Documentation
value
template<typename UnitType , typename NumericType = double> PhQ::PlanarVector<NumericType> PhQ::DimensionalPlanarVector< UnitType, NumericType >::value protected inherited
Value of this physical quantity expressed in its standard unit of measure.
Definition at line 222 of file DimensionalPlanarVector.hpp.
Referenced by PhQ::PlanarAcceleration< NumericType >::Create(), PhQ::PlanarDisplacement< NumericType >::Create(), PhQ::PlanarForce< NumericType >::Create(), PhQ::PlanarHeatFlux< NumericType >::Create(), PhQ::PlanarPosition< NumericType >::Create(), PhQ::PlanarTemperatureGradient< NumericType >::Create(), PhQ::PlanarTraction< NumericType >::Create(), PhQ::PlanarVelocity< NumericType >::Create(), PhQ::DimensionalPlanarVector< UnitType, NumericType >::JSON(), PhQ::PlanarAcceleration< NumericType >::Magnitude(), PhQ::PlanarDisplacement< NumericType >::Magnitude(), PhQ::PlanarForce< NumericType >::Magnitude(), PhQ::PlanarHeatFlux< NumericType >::Magnitude(), PhQ::PlanarPosition< NumericType >::Magnitude(), PhQ::PlanarTemperatureGradient< NumericType >::Magnitude(), PhQ::PlanarTraction< NumericType >::Magnitude(), PhQ::PlanarVelocity< NumericType >::Magnitude(), PhQ::DimensionalPlanarVector< UnitType, NumericType >::MutableValue(), PhQ::PlanarAcceleration< NumericType >::operator*(), PhQ::PlanarDisplacement< NumericType >::operator*(), PhQ::PlanarForce< NumericType >::operator*(), PhQ::PlanarHeatFlux< NumericType >::operator*(), PhQ::PlanarPosition< NumericType >::operator*(), PhQ::PlanarTemperatureGradient< NumericType >::operator*(), PhQ::PlanarTraction< NumericType >::operator*(), PhQ::PlanarVelocity< NumericType >::operator*(), PhQ::PlanarAcceleration< NumericType >::operator*=(), PhQ::PlanarDisplacement< NumericType >::operator*=(), PhQ::PlanarForce< NumericType >::operator*=(), PhQ::PlanarHeatFlux< NumericType >::operator*=(), PhQ::PlanarPosition< NumericType >::operator*=(), PhQ::PlanarTemperatureGradient< NumericType >::operator*=(), PhQ::PlanarTraction< NumericType >::operator*=(), PhQ::PlanarVelocity< NumericType >::operator*=(), PhQ::PlanarAcceleration< NumericType >::operator+(), PhQ::PlanarDisplacement< NumericType >::operator+(), PhQ::PlanarPosition< NumericType >::operator+(), PhQ::PlanarForce< NumericType >::operator+(), PhQ::PlanarHeatFlux< NumericType >::operator+(), PhQ::PlanarPosition< NumericType >::operator+(), PhQ::PlanarTemperatureGradient< NumericType >::operator+(), PhQ::PlanarTraction< NumericType >::operator+(), PhQ::PlanarVelocity< NumericType >::operator+(), PhQ::PlanarAcceleration< NumericType >::operator+=(), PhQ::PlanarDisplacement< NumericType >::operator+=(), PhQ::PlanarPosition< NumericType >::operator+=(), PhQ::PlanarForce< NumericType >::operator+=(), PhQ::PlanarHeatFlux< NumericType >::operator+=(), PhQ::PlanarPosition< NumericType >::operator+=(), PhQ::PlanarTemperatureGradient< NumericType >::operator+=(), PhQ::PlanarTraction< NumericType >::operator+=(), PhQ::PlanarVelocity< NumericType >::operator+=(), PhQ::PlanarAcceleration< NumericType >::operator-(), PhQ::PlanarDisplacement< NumericType >::operator-(), PhQ::PlanarPosition< NumericType >::operator-(), PhQ::PlanarForce< NumericType >::operator-(), PhQ::PlanarHeatFlux< NumericType >::operator-(), PhQ::PlanarPosition< NumericType >::operator-(), PhQ::PlanarTemperatureGradient< NumericType >::operator-(), PhQ::PlanarTraction< NumericType >::operator-(), PhQ::PlanarVelocity< NumericType >::operator-(), PhQ::PlanarAcceleration< NumericType >::operator-=(), PhQ::PlanarDisplacement< NumericType >::operator-=(), PhQ::PlanarPosition< NumericType >::operator-=(), PhQ::PlanarForce< NumericType >::operator-=(), PhQ::PlanarHeatFlux< NumericType >::operator-=(), PhQ::PlanarPosition< NumericType >::operator-=(), PhQ::PlanarTemperatureGradient< NumericType >::operator-=(), PhQ::PlanarTraction< NumericType >::operator-=(), PhQ::PlanarVelocity< NumericType >::operator-=(), PhQ::PlanarAcceleration< NumericType >::operator/(), PhQ::PlanarDisplacement< NumericType >::operator/(), PhQ::PlanarForce< NumericType >::operator/(), PhQ::PlanarHeatFlux< NumericType >::operator/(), PhQ::PlanarPosition< NumericType >::operator/(), PhQ::PlanarTemperatureGradient< NumericType >::operator/(), PhQ::PlanarTraction< NumericType >::operator/(), PhQ::PlanarVelocity< NumericType >::operator/(), PhQ::PlanarAcceleration< NumericType >::operator/=(), PhQ::PlanarDisplacement< NumericType >::operator/=(), PhQ::PlanarForce< NumericType >::operator/=(), PhQ::PlanarHeatFlux< NumericType >::operator/=(), PhQ::PlanarPosition< NumericType >::operator/=(), PhQ::PlanarTemperatureGradient< NumericType >::operator/=(), PhQ::PlanarTraction< NumericType >::operator/=(), PhQ::PlanarVelocity< NumericType >::operator/=(), PhQ::DimensionalPlanarVector< UnitType, NumericType >::operator=(), PhQ::PlanarAcceleration< NumericType >::operator=(), PhQ::PlanarDisplacement< NumericType >::operator=(), PhQ::PlanarForce< NumericType >::operator=(), PhQ::PlanarHeatFlux< NumericType >::operator=(), PhQ::PlanarPosition< NumericType >::operator=(), PhQ::PlanarTemperatureGradient< NumericType >::operator=(), PhQ::PlanarTraction< NumericType >::operator=(), PhQ::PlanarVelocity< NumericType >::operator=(), PhQ::PlanarAcceleration< NumericType >::PlanarDirection(), PhQ::PlanarDisplacement< NumericType >::PlanarDirection(), PhQ::PlanarForce< NumericType >::PlanarDirection(), PhQ::PlanarHeatFlux< NumericType >::PlanarDirection(), PhQ::PlanarPosition< NumericType >::PlanarDirection(), PhQ::PlanarTemperatureGradient< NumericType >::PlanarDirection(), PhQ::PlanarTraction< NumericType >::PlanarDirection(), PhQ::PlanarVelocity< NumericType >::PlanarDirection(), PhQ::DimensionalPlanarVector< UnitType, NumericType >::Print(), PhQ::DimensionalPlanarVector< UnitType, NumericType >::SetValue(), PhQ::DimensionalPlanarVector< UnitType, NumericType >::StaticValue(), PhQ::DimensionalPlanarVector< UnitType, NumericType >::Value(), PhQ::DimensionalPlanarVector< UnitType, NumericType >::Value(), PhQ::PlanarAcceleration< NumericType >::x(), PhQ::PlanarDisplacement< NumericType >::x(), PhQ::PlanarForce< NumericType >::x(), PhQ::PlanarHeatFlux< NumericType >::x(), PhQ::PlanarPosition< NumericType >::x(), PhQ::PlanarTemperatureGradient< NumericType >::x(), PhQ::PlanarTraction< NumericType >::x(), PhQ::PlanarVelocity< NumericType >::x(), PhQ::DimensionalPlanarVector< UnitType, NumericType >::XML(), PhQ::PlanarAcceleration< NumericType >::y(), PhQ::PlanarDisplacement< NumericType >::y(), PhQ::PlanarForce< NumericType >::y(), PhQ::PlanarHeatFlux< NumericType >::y(), PhQ::PlanarPosition< NumericType >::y(), PhQ::PlanarTemperatureGradient< NumericType >::y(), PhQ::PlanarTraction< NumericType >::y(), PhQ::PlanarVelocity< NumericType >::y(), PhQ::DimensionalPlanarVector< UnitType, NumericType >::YAML(), and PhQ::PlanarDisplacement< NumericType >::z().
The documentation for this class was generated from the following files:
PhQ/Angle.hpp
PhQ/PlanarPosition.hpp
PhQ/Position.hpp