Physical Quantities: PhQ::Position< NumericType > Class Template Reference
PhQ::Position< NumericType > Class Template Reference
Three-dimensional Euclidean position vector. Contains three components in Cartesian coordinates: x, y, and z. Position is not to be confused with displacement; for a three-dimensional Euclidean displacement vector, see PhQ::Displacement. For a two-dimensional Euclidean position vector in the XY plane, see PhQ::PlanarPosition. For scalar position components or for the magnitude of a position vector, see PhQ::Length.
#include "Position.hpp"
Public Member Functions
Position ()=default
Default constructor. Constructs a position vector with an uninitialized value.
Position (const Vector< NumericType > &value, const Unit::Length unit)
Constructor. Constructs a position vector with a given value expressed in a given length unit.
Position (const Length< NumericType > &x, const Length< NumericType > &y, const Length< NumericType > &z)
Constructor. Constructs a position vector from a given set of length components.
constexpr Position (const Length< NumericType > &length, const Direction< NumericType > &direction)
Constructor. Constructs a position vector from a given length and direction.
constexpr Position (const PlanarPosition< NumericType > &planar_force)
Constructor. Constructs a position vector from a given planar position vector in the XY plane. This position vector's z-component is initialized to zero.
constexpr Position (const Displacement< NumericType > &displacement)
Constructor. Constructs a position vector from a given displacement vector from the origin.
~Position () noexcept=default
Destructor. Destroys this position vector.
constexpr Position (const Position< NumericType > &other)=default
Copy constructor. Constructs a position vector by copying another one.
template<typename OtherNumericType >
constexpr Position (const Position< OtherNumericType > &other)
Copy constructor. Constructs a position by copying another one.
constexpr Position (Position< NumericType > &&other) noexcept=default
Move constructor. Constructs a position vector by moving another one.
constexpr Position< NumericType > & operator= (const Position< NumericType > &other)=default
Copy assignment operator. Assigns this position vector by copying another one.
template<typename OtherNumericType >
constexpr Position< NumericType > & operator= (const Position< OtherNumericType > &other)
Copy assignment operator. Assigns this position by copying another one.
constexpr Position< NumericType > & operator= (Position< NumericType > &&other) noexcept=default
Move assignment operator. Assigns this position vector by moving another one.
constexpr Length< NumericType > x () const noexcept
Returns the x Cartesian component of this position vector.
constexpr Length< NumericType > y () const noexcept
Returns the y Cartesian component of this position vector.
constexpr Length< NumericType > z () const noexcept
Returns the z Cartesian component of this position vector.
Length< NumericType > Magnitude () const
Returns the magnitude of this position vector.
PhQ::Direction< NumericType > Direction () const
Returns the direction of this position vector.
PhQ::Angle< NumericType > Angle (const Position< NumericType > &position) const
Returns the angle between this position vector and another one.
constexpr Position< NumericType > operator+ (const Position< NumericType > &position) const
constexpr Position< NumericType > operator+ (const Displacement< NumericType > &displacement) const
constexpr Displacement< NumericType > operator- (const Position< NumericType > &position) const
constexpr Position< NumericType > operator- (const Displacement< NumericType > &displacement) const
constexpr Position< NumericType > operator* (const NumericType number) const
constexpr Position< NumericType > operator/ (const NumericType number) const
constexpr void operator+= (const Position< NumericType > &position) noexcept
constexpr void operator+= (const Displacement< NumericType > &displacement) noexcept
constexpr void operator-= (const Position< NumericType > &position) noexcept
constexpr void operator-= (const Displacement< NumericType > &displacement) noexcept
constexpr void operator*= (const NumericType number) noexcept
constexpr void operator/= (const NumericType number) noexcept
constexpr const PhQ::Vector< NumericType > & Value () const noexcept
Value of this physical quantity expressed in its standard unit of measure.
PhQ::Vector< NumericType > Value (const UnitType unit) const
Value of this physical quantity expressed in a given unit of measure.
template<UnitType NewUnit>
constexpr PhQ::Vector< NumericType > StaticValue () const
Value of this physical quantity expressed in a given unit of measure. This method can be evaluated statically at compile-time.
constexpr PhQ::Vector< NumericType > & MutableValue () noexcept
Returns the value of this physical quantity expressed in its standard unit of measure as a mutable value.
constexpr void SetValue (const PhQ::Vector< NumericType > &value) noexcept
Sets the value of this physical quantity expressed in its standard unit of measure to the given value.
std::string Print () const
Prints this physical quantity as a string. This physical quantity's value is expressed in its standard unit of measure.
std::string Print (const UnitType unit) const
Prints this physical quantity as a string. This physical quantity's value is expressed in the given unit of measure.
std::string JSON () const
Serializes this physical quantity as a JSON message. This physical quantity's value is expressed in its standard unit of measure.
std::string JSON (const UnitType unit) const
Serializes this physical quantity as a JSON message. This physical quantity's value is expressed in the given unit of measure.
std::string XML () const
Serializes this physical quantity as an XML message. This physical quantity's value is expressed in its standard unit of measure.
std::string XML (const UnitType unit) const
Serializes this physical quantity as an XML message. This physical quantity's value is expressed in the given unit of measure.
std::string YAML () const
Serializes this physical quantity as a YAML message. This physical quantity's value is expressed in its standard unit of measure.
std::string YAML (const UnitType unit) const
Serializes this physical quantity as a YAML message. This physical quantity's value is expressed in the given unit of measure.
Static Public Member Functions
static constexpr Position< NumericType > Zero ()
Statically creates a position vector of zero.
template<Unit::Length Unit>
static constexpr Position< NumericType > Create (const NumericType x, const NumericType y, const NumericType z)
Statically creates a position vector from the given x, y, and z Cartesian components expressed in a given length unit.
template<Unit::Length Unit>
static constexpr Position< NumericType > Create (const std::array< NumericType, 3 > &x_y_z)
Statically creates a position vector from the given x, y, and z Cartesian components expressed in a given length unit.
template<Unit::Length Unit>
static constexpr Position< NumericType > Create (const Vector< NumericType > &value)
Statically creates a position vector with a given value expressed in a given length unit.
static constexpr const PhQ::Dimensions & Dimensions ()
Physical dimension set of this physical quantity.
static constexpr UnitType Unit ()
Standard unit of measure for this physical quantity. This physical quantity's value is stored internally in this unit of measure.
Protected Attributes
PhQ::Vector< NumericType > value
Value of this physical quantity expressed in its standard unit of measure.
Private Member Functions
constexpr Position (const Vector< NumericType > &value)
Constructor. Constructs a position vector with a given value expressed in the standard length unit.
Friends
template<typename OtherNumericType >
class Displacement
Detailed Description
template<typename NumericType = double>
class PhQ::Position< NumericType >
Three-dimensional Euclidean position vector. Contains three components in Cartesian coordinates: x, y, and z. Position is not to be confused with displacement; for a three-dimensional Euclidean displacement vector, see PhQ::Displacement. For a two-dimensional Euclidean position vector in the XY plane, see PhQ::PlanarPosition. For scalar position components or for the magnitude of a position vector, see PhQ::Length.
Definition at line 50 of file Position.hpp.
Constructor & Destructor Documentation
Position() [1/10]
template<typename NumericType = double> PhQ::Position< NumericType >::Position () default
Default constructor. Constructs a position vector with an uninitialized value.
Position() [2/10]
template<typename NumericType = double> PhQ::Position< NumericType >::Position (const Vector< NumericType > & value, const Unit::Length unit) inline
Constructor. Constructs a position vector with a given value expressed in a given length unit.
Definition at line 57 of file Position.hpp.
Position() [3/10]
template<typename NumericType = double> PhQ::Position< NumericType >::Position (const Length< NumericType > & x, const Length< NumericType > & y, const Length< NumericType > & z) inline
Constructor. Constructs a position vector from a given set of length components.
Definition at line 61 of file Position.hpp.
References PhQ::Position< NumericType >::x(), PhQ::Position< NumericType >::y(), and PhQ::Position< NumericType >::z().
Position() [4/10]
template<typename NumericType = double> constexpr PhQ::Position< NumericType >::Position (const Length< NumericType > & length, const Direction< NumericType > & direction) inline constexpr
Constructor. Constructs a position vector from a given length and direction.
Definition at line 65 of file Position.hpp.
Position() [5/10]
template<typename NumericType = double> constexpr PhQ::Position< NumericType >::Position (const PlanarPosition< NumericType > & planar_force) inline explicit constexpr
Constructor. Constructs a position vector from a given planar position vector in the XY plane. This position vector's z-component is initialized to zero.
Definition at line 70 of file Position.hpp.
References PhQ::DimensionalPlanarVector< UnitType, NumericType >::Value().
Position() [6/10]
template<typename NumericType = double> constexpr PhQ::Position< NumericType >::Position (const Displacement< NumericType > & displacement) inline explicit constexpr
Constructor. Constructs a position vector from a given displacement vector from the origin.
Definition at line 75 of file Position.hpp.
~Position()
template<typename NumericType = double> PhQ::Position< NumericType >::~Position () default noexcept
Destructor. Destroys this position vector.
Position() [7/10]
template<typename NumericType = double> constexpr PhQ::Position< NumericType >::Position (const Position< NumericType > & other) constexpr default
Copy constructor. Constructs a position vector by copying another one.
Position() [8/10]
template<typename NumericType = double> template<typename OtherNumericType > constexpr PhQ::Position< NumericType >::Position (const Position< OtherNumericType > & other) inline explicit constexpr
Copy constructor. Constructs a position by copying another one.
Definition at line 86 of file Position.hpp.
Position() [9/10]
template<typename NumericType = double> constexpr PhQ::Position< NumericType >::Position (Position< NumericType > && other) constexpr default noexcept
Move constructor. Constructs a position vector by moving another one.
Position() [10/10]
template<typename NumericType = double> constexpr PhQ::Position< NumericType >::Position (const Vector< NumericType > & value) inline explicit constexpr private
Constructor. Constructs a position vector with a given value expressed in the standard length unit.
Definition at line 217 of file Position.hpp.
Member Function Documentation
Angle()
template<typename NumericType = double> PhQ::Angle< NumericType > PhQ::Position< NumericType >::Angle (const Position< NumericType > & position) const inline
Returns the angle between this position vector and another one.
Definition at line 162 of file Position.hpp.
Create() [1/3]
template<typename NumericType = double> template<Unit::Length Unit> static constexpr Position< NumericType > PhQ::Position< NumericType >::Create (const NumericType x, const NumericType y, const NumericType z) inline static constexpr
Statically creates a position vector from the given x, y, and z Cartesian components expressed in a given length unit.
Definition at line 113 of file Position.hpp.
References PhQ::Position< NumericType >::x(), PhQ::Position< NumericType >::y(), and PhQ::Position< NumericType >::z().
Create() [2/3]
template<typename NumericType = double> template<Unit::Length Unit> static constexpr Position< NumericType > PhQ::Position< NumericType >::Create (const std::array< NumericType, 3 > & x_y_z) inline static constexpr
Statically creates a position vector from the given x, y, and z Cartesian components expressed in a given length unit.
Definition at line 122 of file Position.hpp.
Create() [3/3]
template<typename NumericType = double> template<Unit::Length Unit> static constexpr Position< NumericType > PhQ::Position< NumericType >::Create (const Vector< NumericType > & value) inline static constexpr
Statically creates a position vector with a given value expressed in a given length unit.
Definition at line 131 of file Position.hpp.
References PhQ::DimensionalVector< UnitType, NumericType >::value.
Dimensions()
template<typename UnitType , typename NumericType = double> static constexpr const PhQ::Dimensions & PhQ::DimensionalVector< UnitType, NumericType >::Dimensions () inline static constexpr inherited
Physical dimension set of this physical quantity.
Definition at line 50 of file DimensionalVector.hpp.
Direction()
template<typename NumericType = double> PhQ::Direction< NumericType > PhQ::Position< NumericType >::Direction () const inline
Returns the direction of this position vector.
Definition at line 157 of file Position.hpp.
References PhQ::DimensionalVector< UnitType, NumericType >::value.
JSON() [1/2]
template<typename UnitType , typename NumericType = double> std::string PhQ::DimensionalVector< UnitType, NumericType >::JSON () const inline inherited
Serializes this physical quantity as a JSON message. This physical quantity's value is expressed in its standard unit of measure.
Definition at line 103 of file DimensionalVector.hpp.
References PhQ::Abbreviation(), and PhQ::DimensionalVector< UnitType, NumericType >::value.
Referenced by PhQ::DimensionalVector< UnitType, NumericType >::JSON().
JSON() [2/2]
template<typename UnitType , typename NumericType = double> std::string PhQ::DimensionalVector< UnitType, NumericType >::JSON (const UnitType unit) const inline inherited
Serializes this physical quantity as a JSON message. This physical quantity's value is expressed in the given unit of measure.
Definition at line 113 of file DimensionalVector.hpp.
References PhQ::Abbreviation(), PhQ::DimensionalVector< UnitType, NumericType >::JSON(), and PhQ::DimensionalVector< UnitType, NumericType >::Value().
Magnitude()
template<typename NumericType = double> Length< NumericType > PhQ::Position< NumericType >::Magnitude () const inline
Returns the magnitude of this position vector.
Definition at line 152 of file Position.hpp.
References PhQ::DimensionalVector< UnitType, NumericType >::value.
MutableValue()
template<typename UnitType , typename NumericType = double> constexpr PhQ::Vector< NumericType > & PhQ::DimensionalVector< UnitType, NumericType >::MutableValue () inline constexpr noexcept inherited
Returns the value of this physical quantity expressed in its standard unit of measure as a mutable value.
Definition at line 79 of file DimensionalVector.hpp.
References PhQ::DimensionalVector< UnitType, NumericType >::value.
operator*()
template<typename NumericType = double> constexpr Position< NumericType > PhQ::Position< NumericType >::operator* (const NumericType number) const inline constexpr
Definition at line 182 of file Position.hpp.
References PhQ::DimensionalVector< UnitType, NumericType >::value.
operator*=()
template<typename NumericType = double> constexpr void PhQ::Position< NumericType >::operator*= (const NumericType number) inline constexpr noexcept
Definition at line 206 of file Position.hpp.
References PhQ::DimensionalVector< UnitType, NumericType >::value.
operator+() [1/2]
template<typename NumericType = double> constexpr Position< NumericType > PhQ::Position< NumericType >::operator+ (const Displacement< NumericType > & displacement) const inline constexpr
Definition at line 170 of file Position.hpp.
References PhQ::DimensionalVector< UnitType, NumericType >::Value(), and PhQ::DimensionalVector< UnitType, NumericType >::value.
operator+() [2/2]
template<typename NumericType = double> constexpr Position< NumericType > PhQ::Position< NumericType >::operator+ (const Position< NumericType > & position) const inline constexpr
Definition at line 166 of file Position.hpp.
References PhQ::DimensionalVector< UnitType, NumericType >::value.
operator+=() [1/2]
template<typename NumericType = double> constexpr void PhQ::Position< NumericType >::operator+= (const Displacement< NumericType > & displacement) inline constexpr noexcept
Definition at line 194 of file Position.hpp.
References PhQ::DimensionalVector< UnitType, NumericType >::value.
operator+=() [2/2]
template<typename NumericType = double> constexpr void PhQ::Position< NumericType >::operator+= (const Position< NumericType > & position) inline constexpr noexcept
Definition at line 190 of file Position.hpp.
References PhQ::DimensionalVector< UnitType, NumericType >::value.
operator-() [1/2]
template<typename NumericType = double> constexpr Position< NumericType > PhQ::Position< NumericType >::operator- (const Displacement< NumericType > & displacement) const inline constexpr
Definition at line 178 of file Position.hpp.
References PhQ::DimensionalVector< UnitType, NumericType >::Value(), and PhQ::DimensionalVector< UnitType, NumericType >::value.
operator-() [2/2]
template<typename NumericType = double> constexpr Displacement< NumericType > PhQ::Position< NumericType >::operator- (const Position< NumericType > & position) const inline constexpr
Definition at line 174 of file Position.hpp.
References PhQ::DimensionalVector< UnitType, NumericType >::value.
operator-=() [1/2]
template<typename NumericType = double> constexpr void PhQ::Position< NumericType >::operator-= (const Displacement< NumericType > & displacement) inline constexpr noexcept
Definition at line 202 of file Position.hpp.
References PhQ::DimensionalVector< UnitType, NumericType >::value.
operator-=() [2/2]
template<typename NumericType = double> constexpr void PhQ::Position< NumericType >::operator-= (const Position< NumericType > & position) inline constexpr noexcept
Definition at line 198 of file Position.hpp.
References PhQ::DimensionalVector< UnitType, NumericType >::value.
operator/()
template<typename NumericType = double> constexpr Position< NumericType > PhQ::Position< NumericType >::operator/ (const NumericType number) const inline constexpr
Definition at line 186 of file Position.hpp.
References PhQ::DimensionalVector< UnitType, NumericType >::value.
operator/=()
template<typename NumericType = double> constexpr void PhQ::Position< NumericType >::operator/= (const NumericType number) inline constexpr noexcept
Definition at line 210 of file Position.hpp.
References PhQ::DimensionalVector< UnitType, NumericType >::value.
operator=() [1/3]
template<typename NumericType = double> constexpr Position< NumericType > & PhQ::Position< NumericType >::operator= (const Position< NumericType > & other) constexpr default
Copy assignment operator. Assigns this position vector by copying another one.
operator=() [2/3]
template<typename NumericType = double> template<typename OtherNumericType > constexpr Position< NumericType > & PhQ::Position< NumericType >::operator= (const Position< OtherNumericType > & other) inline constexpr
Copy assignment operator. Assigns this position by copying another one.
Definition at line 97 of file Position.hpp.
References PhQ::DimensionalVector< UnitType, NumericType >::Value(), and PhQ::DimensionalVector< UnitType, NumericType >::value.
operator=() [3/3]
template<typename NumericType = double> constexpr Position< NumericType > & PhQ::Position< NumericType >::operator= (Position< NumericType > && other) constexpr default noexcept
Move assignment operator. Assigns this position vector by moving another one.
Print() [1/2]
template<typename UnitType , typename NumericType = double> std::string PhQ::DimensionalVector< UnitType, NumericType >::Print () const inline inherited
Prints this physical quantity as a string. This physical quantity's value is expressed in its standard unit of measure.
Definition at line 91 of file DimensionalVector.hpp.
References PhQ::Abbreviation(), and PhQ::DimensionalVector< UnitType, NumericType >::value.
Referenced by PhQ::operator<<(), PhQ::operator<<(), PhQ::operator<<(), PhQ::operator<<(), PhQ::operator<<(), PhQ::operator<<(), PhQ::operator<<(), PhQ::operator<<(), and PhQ::operator<<().
Print() [2/2]
template<typename UnitType , typename NumericType = double> std::string PhQ::DimensionalVector< UnitType, NumericType >::Print (const UnitType unit) const inline inherited
Prints this physical quantity as a string. This physical quantity's value is expressed in the given unit of measure.
Definition at line 97 of file DimensionalVector.hpp.
References PhQ::Abbreviation(), and PhQ::DimensionalVector< UnitType, NumericType >::Value().
SetValue()
template<typename UnitType , typename NumericType = double> constexpr void PhQ::DimensionalVector< UnitType, NumericType >::SetValue (const PhQ::Vector< NumericType > & value) inline constexpr noexcept inherited
Sets the value of this physical quantity expressed in its standard unit of measure to the given value.
Definition at line 85 of file DimensionalVector.hpp.
References PhQ::DimensionalVector< UnitType, NumericType >::value.
StaticValue()
template<typename UnitType , typename NumericType = double> template<UnitType NewUnit> constexpr PhQ::Vector< NumericType > PhQ::DimensionalVector< UnitType, NumericType >::StaticValue () const inline constexpr inherited
Value of this physical quantity expressed in a given unit of measure. This method can be evaluated statically at compile-time.
Definition at line 73 of file DimensionalVector.hpp.
References PhQ::DimensionalVector< UnitType, NumericType >::value.
Unit()
template<typename UnitType , typename NumericType = double> static constexpr UnitType PhQ::DimensionalVector< UnitType, NumericType >::Unit () inline static constexpr inherited
Standard unit of measure for this physical quantity. This physical quantity's value is stored internally in this unit of measure.
Definition at line 56 of file DimensionalVector.hpp.
Value() [1/2]
template<typename UnitType , typename NumericType = double> constexpr const PhQ::Vector< NumericType > & PhQ::DimensionalVector< UnitType, NumericType >::Value () const inline constexpr noexcept inherited
Value of this physical quantity expressed in its standard unit of measure.
Definition at line 61 of file DimensionalVector.hpp.
References PhQ::DimensionalVector< UnitType, NumericType >::value.
Referenced by PhQ::DimensionalVector< UnitType, NumericType >::JSON(), PhQ::Position< NumericType >::operator+(), PhQ::Displacement< NumericType >::operator+(), PhQ::Position< NumericType >::operator-(), PhQ::Displacement< NumericType >::operator-(), PhQ::Acceleration< NumericType >::operator=(), PhQ::DimensionalVector< UnitType, NumericType >::operator=(), PhQ::Displacement< NumericType >::operator=(), PhQ::Force< NumericType >::operator=(), PhQ::HeatFlux< NumericType >::operator=(), PhQ::Position< NumericType >::operator=(), PhQ::TemperatureGradient< NumericType >::operator=(), PhQ::Traction< NumericType >::operator=(), PhQ::VectorArea< NumericType >::operator=(), PhQ::Velocity< NumericType >::operator=(), PhQ::operator==(), PhQ::operator==(), PhQ::operator==(), PhQ::operator==(), PhQ::operator==(), PhQ::operator==(), PhQ::operator==(), PhQ::operator==(), PhQ::operator==(), PhQ::operator==(), PhQ::operator==(), PhQ::operator==(), PhQ::operator==(), PhQ::operator==(), PhQ::operator==(), PhQ::operator==(), PhQ::PlanarAcceleration< NumericType >::PlanarAcceleration(), PhQ::PlanarDisplacement< NumericType >::PlanarDisplacement(), PhQ::PlanarForce< NumericType >::PlanarForce(), PhQ::PlanarHeatFlux< NumericType >::PlanarHeatFlux(), PhQ::PlanarPosition< NumericType >::PlanarPosition(), PhQ::PlanarTemperatureGradient< NumericType >::PlanarTemperatureGradient(), PhQ::PlanarTraction< NumericType >::PlanarTraction(), PhQ::PlanarVelocity< NumericType >::PlanarVelocity(), PhQ::DimensionalVector< UnitType, NumericType >::Print(), PhQ::DimensionalVector< UnitType, NumericType >::XML(), and PhQ::DimensionalVector< UnitType, NumericType >::YAML().
Value() [2/2]
template<typename UnitType , typename NumericType = double> PhQ::Vector< NumericType > PhQ::DimensionalVector< UnitType, NumericType >::Value (const UnitType unit) const inline inherited
Value of this physical quantity expressed in a given unit of measure.
Definition at line 66 of file DimensionalVector.hpp.
References PhQ::Convert(), and PhQ::DimensionalVector< UnitType, NumericType >::value.
x()
template<typename NumericType = double> constexpr Length< NumericType > PhQ::Position< NumericType >::x () const inline constexpr noexcept
Returns the x Cartesian component of this position vector.
Definition at line 137 of file Position.hpp.
References PhQ::DimensionalVector< UnitType, NumericType >::value.
Referenced by PhQ::Position< NumericType >::Create(), and PhQ::Position< NumericType >::Position().
XML() [1/2]
template<typename UnitType , typename NumericType = double> std::string PhQ::DimensionalVector< UnitType, NumericType >::XML () const inline inherited
Serializes this physical quantity as an XML message. This physical quantity's value is expressed in its standard unit of measure.
Definition at line 123 of file DimensionalVector.hpp.
References PhQ::Abbreviation(), and PhQ::DimensionalVector< UnitType, NumericType >::value.
Referenced by PhQ::DimensionalVector< UnitType, NumericType >::XML().
XML() [2/2]
template<typename UnitType , typename NumericType = double> std::string PhQ::DimensionalVector< UnitType, NumericType >::XML (const UnitType unit) const inline inherited
Serializes this physical quantity as an XML message. This physical quantity's value is expressed in the given unit of measure.
Definition at line 133 of file DimensionalVector.hpp.
References PhQ::Abbreviation(), PhQ::DimensionalVector< UnitType, NumericType >::Value(), and PhQ::DimensionalVector< UnitType, NumericType >::XML().
y()
template<typename NumericType = double> constexpr Length< NumericType > PhQ::Position< NumericType >::y () const inline constexpr noexcept
Returns the y Cartesian component of this position vector.
Definition at line 142 of file Position.hpp.
References PhQ::DimensionalVector< UnitType, NumericType >::value.
Referenced by PhQ::Position< NumericType >::Create(), and PhQ::Position< NumericType >::Position().
YAML() [1/2]
template<typename UnitType , typename NumericType = double> std::string PhQ::DimensionalVector< UnitType, NumericType >::YAML () const inline inherited
Serializes this physical quantity as a YAML message. This physical quantity's value is expressed in its standard unit of measure.
Definition at line 143 of file DimensionalVector.hpp.
References PhQ::Abbreviation(), and PhQ::DimensionalVector< UnitType, NumericType >::value.
Referenced by PhQ::DimensionalVector< UnitType, NumericType >::YAML().
YAML() [2/2]
template<typename UnitType , typename NumericType = double> std::string PhQ::DimensionalVector< UnitType, NumericType >::YAML (const UnitType unit) const inline inherited
Serializes this physical quantity as a YAML message. This physical quantity's value is expressed in the given unit of measure.
Definition at line 153 of file DimensionalVector.hpp.
References PhQ::Abbreviation(), PhQ::DimensionalVector< UnitType, NumericType >::Value(), and PhQ::DimensionalVector< UnitType, NumericType >::YAML().
z()
template<typename NumericType = double> constexpr Length< NumericType > PhQ::Position< NumericType >::z () const inline constexpr noexcept
Returns the z Cartesian component of this position vector.
Definition at line 147 of file Position.hpp.
References PhQ::DimensionalVector< UnitType, NumericType >::value.
Referenced by PhQ::Position< NumericType >::Create(), and PhQ::Position< NumericType >::Position().
Zero()
template<typename NumericType = double> static constexpr Position< NumericType > PhQ::Position< NumericType >::Zero () inline static constexpr
Statically creates a position vector of zero.
Definition at line 106 of file Position.hpp.
References PhQ::Vector< NumericType >::Zero().
Friends And Related Symbol Documentation
Displacement
template<typename NumericType = double> template<typename OtherNumericType > friend class Displacement friend
Definition at line 221 of file Position.hpp.
Member Data Documentation
value
template<typename UnitType , typename NumericType = double> PhQ::Vector<NumericType> PhQ::DimensionalVector< UnitType, NumericType >::value protected inherited
Value of this physical quantity expressed in its standard unit of measure.
Definition at line 217 of file DimensionalVector.hpp.
Referenced by PhQ::Acceleration< NumericType >::Create(), PhQ::Displacement< NumericType >::Create(), PhQ::Force< NumericType >::Create(), PhQ::HeatFlux< NumericType >::Create(), PhQ::Position< NumericType >::Create(), PhQ::TemperatureGradient< NumericType >::Create(), PhQ::Traction< NumericType >::Create(), PhQ::VectorArea< NumericType >::Create(), PhQ::Velocity< NumericType >::Create(), PhQ::Acceleration< NumericType >::Direction(), PhQ::Displacement< NumericType >::Direction(), PhQ::Force< NumericType >::Direction(), PhQ::HeatFlux< NumericType >::Direction(), PhQ::Position< NumericType >::Direction(), PhQ::TemperatureGradient< NumericType >::Direction(), PhQ::Traction< NumericType >::Direction(), PhQ::VectorArea< NumericType >::Direction(), PhQ::Velocity< NumericType >::Direction(), PhQ::DimensionalVector< UnitType, NumericType >::JSON(), PhQ::Acceleration< NumericType >::Magnitude(), PhQ::Displacement< NumericType >::Magnitude(), PhQ::Force< NumericType >::Magnitude(), PhQ::HeatFlux< NumericType >::Magnitude(), PhQ::Position< NumericType >::Magnitude(), PhQ::TemperatureGradient< NumericType >::Magnitude(), PhQ::Traction< NumericType >::Magnitude(), PhQ::VectorArea< NumericType >::Magnitude(), PhQ::Velocity< NumericType >::Magnitude(), PhQ::DimensionalVector< UnitType, NumericType >::MutableValue(), PhQ::Acceleration< NumericType >::operator*(), PhQ::Displacement< NumericType >::operator*(), PhQ::Force< NumericType >::operator*(), PhQ::HeatFlux< NumericType >::operator*(), PhQ::Position< NumericType >::operator*(), PhQ::TemperatureGradient< NumericType >::operator*(), PhQ::Traction< NumericType >::operator*(), PhQ::VectorArea< NumericType >::operator*(), PhQ::Velocity< NumericType >::operator*(), PhQ::Acceleration< NumericType >::operator*=(), PhQ::Displacement< NumericType >::operator*=(), PhQ::Force< NumericType >::operator*=(), PhQ::HeatFlux< NumericType >::operator*=(), PhQ::Position< NumericType >::operator*=(), PhQ::TemperatureGradient< NumericType >::operator*=(), PhQ::Traction< NumericType >::operator*=(), PhQ::VectorArea< NumericType >::operator*=(), PhQ::Velocity< NumericType >::operator*=(), PhQ::Acceleration< NumericType >::operator+(), PhQ::Displacement< NumericType >::operator+(), PhQ::Position< NumericType >::operator+(), PhQ::Force< NumericType >::operator+(), PhQ::HeatFlux< NumericType >::operator+(), PhQ::Position< NumericType >::operator+(), PhQ::TemperatureGradient< NumericType >::operator+(), PhQ::Traction< NumericType >::operator+(), PhQ::VectorArea< NumericType >::operator+(), PhQ::Velocity< NumericType >::operator+(), PhQ::Acceleration< NumericType >::operator+=(), PhQ::Displacement< NumericType >::operator+=(), PhQ::Position< NumericType >::operator+=(), PhQ::Force< NumericType >::operator+=(), PhQ::HeatFlux< NumericType >::operator+=(), PhQ::Position< NumericType >::operator+=(), PhQ::TemperatureGradient< NumericType >::operator+=(), PhQ::Traction< NumericType >::operator+=(), PhQ::VectorArea< NumericType >::operator+=(), PhQ::Velocity< NumericType >::operator+=(), PhQ::Acceleration< NumericType >::operator-(), PhQ::Displacement< NumericType >::operator-(), PhQ::Position< NumericType >::operator-(), PhQ::Force< NumericType >::operator-(), PhQ::HeatFlux< NumericType >::operator-(), PhQ::Position< NumericType >::operator-(), PhQ::TemperatureGradient< NumericType >::operator-(), PhQ::Traction< NumericType >::operator-(), PhQ::VectorArea< NumericType >::operator-(), PhQ::Velocity< NumericType >::operator-(), PhQ::Acceleration< NumericType >::operator-=(), PhQ::Displacement< NumericType >::operator-=(), PhQ::Position< NumericType >::operator-=(), PhQ::Force< NumericType >::operator-=(), PhQ::HeatFlux< NumericType >::operator-=(), PhQ::Position< NumericType >::operator-=(), PhQ::TemperatureGradient< NumericType >::operator-=(), PhQ::Traction< NumericType >::operator-=(), PhQ::VectorArea< NumericType >::operator-=(), PhQ::Velocity< NumericType >::operator-=(), PhQ::Acceleration< NumericType >::operator/(), PhQ::Displacement< NumericType >::operator/(), PhQ::Force< NumericType >::operator/(), PhQ::HeatFlux< NumericType >::operator/(), PhQ::Position< NumericType >::operator/(), PhQ::TemperatureGradient< NumericType >::operator/(), PhQ::Traction< NumericType >::operator/(), PhQ::VectorArea< NumericType >::operator/(), PhQ::Velocity< NumericType >::operator/(), PhQ::Acceleration< NumericType >::operator/=(), PhQ::Displacement< NumericType >::operator/=(), PhQ::Force< NumericType >::operator/=(), PhQ::HeatFlux< NumericType >::operator/=(), PhQ::Position< NumericType >::operator/=(), PhQ::TemperatureGradient< NumericType >::operator/=(), PhQ::Traction< NumericType >::operator/=(), PhQ::VectorArea< NumericType >::operator/=(), PhQ::Velocity< NumericType >::operator/=(), PhQ::Acceleration< NumericType >::operator=(), PhQ::DimensionalVector< UnitType, NumericType >::operator=(), PhQ::Displacement< NumericType >::operator=(), PhQ::Force< NumericType >::operator=(), PhQ::HeatFlux< NumericType >::operator=(), PhQ::Position< NumericType >::operator=(), PhQ::TemperatureGradient< NumericType >::operator=(), PhQ::Traction< NumericType >::operator=(), PhQ::VectorArea< NumericType >::operator=(), PhQ::Velocity< NumericType >::operator=(), PhQ::DimensionalVector< UnitType, NumericType >::Print(), PhQ::DimensionalVector< UnitType, NumericType >::SetValue(), PhQ::DimensionalVector< UnitType, NumericType >::StaticValue(), PhQ::DimensionalVector< UnitType, NumericType >::Value(), PhQ::DimensionalVector< UnitType, NumericType >::Value(), PhQ::Acceleration< NumericType >::x(), PhQ::Displacement< NumericType >::x(), PhQ::Force< NumericType >::x(), PhQ::HeatFlux< NumericType >::x(), PhQ::Position< NumericType >::x(), PhQ::TemperatureGradient< NumericType >::x(), PhQ::Traction< NumericType >::x(), PhQ::VectorArea< NumericType >::x(), PhQ::Velocity< NumericType >::x(), PhQ::DimensionalVector< UnitType, NumericType >::XML(), PhQ::Acceleration< NumericType >::y(), PhQ::Displacement< NumericType >::y(), PhQ::Force< NumericType >::y(), PhQ::HeatFlux< NumericType >::y(), PhQ::Position< NumericType >::y(), PhQ::TemperatureGradient< NumericType >::y(), PhQ::Traction< NumericType >::y(), PhQ::VectorArea< NumericType >::y(), PhQ::Velocity< NumericType >::y(), PhQ::DimensionalVector< UnitType, NumericType >::YAML(), PhQ::Acceleration< NumericType >::z(), PhQ::Displacement< NumericType >::z(), PhQ::Force< NumericType >::z(), PhQ::HeatFlux< NumericType >::z(), PhQ::Position< NumericType >::z(), PhQ::TemperatureGradient< NumericType >::z(), PhQ::Traction< NumericType >::z(), PhQ::VectorArea< NumericType >::z(), and PhQ::Velocity< NumericType >::z().
The documentation for this class was generated from the following files:
PhQ/Angle.hpp
PhQ/Position.hpp