Physical Quantities: PhQ Namespace Reference
PhQ Namespace Reference
Namespace that encompasses all of the Physical Quantities library's content.
Namespaces
namespace Dimension
Namespace that contains base physical dimensions.
namespace Unit
Namespace that contains units of measure.
Classes
class Acceleration
Three-dimensional Euclidean acceleration vector. Contains three components in Cartesian coordinates: x, y, and z. For a two-dimensional Euclidean acceleration vector in the XY plane, see PhQ::PlanarAcceleration. For scalar acceleration components or for the magnitude of an acceleration vector, see PhQ::ScalarAcceleration.
class Angle
Plane angle between two lines or dihedral angle between two planes.
class AngularSpeed
Angular speed, also known as angular rate or angular frequency. Represents the time rate of change of an angle; see also PhQ::Angle, PhQ::ScalarAngularAcceleration, PhQ::Time, and PhQ::Frequency. Can also represent a component or the magnitude of an angular velocity pseudovector.
class Area
Surface area or cross-sectional area. Can also represent a scalar component of a vector area or the magnitude of a vector area. Any closed surface has a vector area: it is the surface integral of its surface normal direction. A vector area is an oriented area; it is the three-dimensional Euclidean vector representation of an area; see PhQ::VectorArea.
class BulkDynamicViscosity
Bulk dynamic viscosity, also known as volume dynamic viscosity or dilatational dynamic viscosity. Not to be confused with dynamic viscosity; see PhQ::DynamicViscosity.
class ConstitutiveModel
Abstract base class for a material's constitutive model, which is a model that defines the relationship between the stress and the strain and strain rate at any point in the material.
class DimensionalDyad
Abstract base class that represents any dimensional dyadic tensor physical quantity. Such a physical quantity is composed of a value and a unit of measure where the value is a three-dimensional dyadic tensor. The tensor may be non-symmetric.
class DimensionalPlanarVector
Abstract base class that represents any dimensional planar vector physical quantity. Such a physical quantity is composed of a value and a unit of measure where the value is a two- dimensional planar vector in the XY plane.
class DimensionalScalar
Abstract base class that represents any dimensional scalar physical quantity. Such a physical quantity is composed of a value and a unit of measure where the value is a scalar number.
class DimensionalSymmetricDyad
Abstract base class that represents any dimensional symmetric dyadic tensor physical quantity. Such a physical quantity is composed of a value and a unit of measure where the value is a three-dimensional symmetric dyadic tensor.
class DimensionalVector
Abstract base class that represents any dimensional vector physical quantity. Such a physical quantity is composed of a value and a unit of measure where the value is a three-dimensional vector.
class DimensionlessDyad
Abstract base class that represents any dimensionless dyadic tensor physical quantity. Such a physical quantity is composed only of a value where the value is a three-dimensional dyadic tensor. The tensor may be non-symmetric. Such a physical quantity has no unit of measure and no dimension set.
class DimensionlessPlanarVector
Abstract base class that represents any dimensionless planar vector physical quantity. Such a physical quantity is composed only of a value where the value is a two-dimensional planar vector in the XY plane. Such a physical quantity has no unit of measure and no dimension set.
class DimensionlessScalar
Abstract base class that represents any dimensionless scalar physical quantity. Such a physical quantity is composed only of a value where the value is a scalar number. Such a physical quantity has no unit of measure and no dimension set.
class DimensionlessSymmetricDyad
Abstract base class that represents any dimensionless symmetric dyadic tensor physical quantity. Such a physical quantity is composed only of a value where the value is a three-dimensional symmetric dyadic tensor. Such a physical quantity has no unit of measure and no dimension set.
class DimensionlessVector
Abstract base class that represents any dimensionless vector physical quantity. Such a physical quantity is composed only of a value where the value is a three-dimensional vector. Such a physical quantity has no unit of measure and no dimension set.
class Dimensions
Physical dimension set of a unit of measure or physical quantity. Composed of the seven independent base physical dimensions: time (T), length (L), mass (M), electric current (I), temperature (Θ), amount of substance (N), and luminous intensity (J). Units of measure that share the same physical dimension set are of the same type and can be converted between one another. For example, the metre per second and the mile per hour are both units of measure that have the same physical dimension set of T^(-1)·L, which is the physical dimension set of speed, so these two units of measure can be converted between one another. On the other hand, the kilogram per cubic metre is a unit of measure with physical dimension set L^(-3)·M, which is the physical dimension set of mass density, so this unit of measure cannot be converted to either the metre per second or the mile per hour, which have a different physical dimension set.
class Direction
Three-dimensional Euclidean direction vector. Contains three components in Cartesian coordinates: x, y, and z. Guaranteed to be either a unit vector or the zero vector (0, 0, 0). For a two-dimensional Euclidean direction vector in the XY plane, see PhQ::PlanarDirection.
class Displacement
Three-dimensional Euclidean displacement vector. Contains three components in Cartesian coordinates: x, y, and z. Displacement is not to be confused with position; for a three-dimensional Euclidean position vector, see PhQ::Position. For a two-dimensional Euclidean displacement vector in the XY plane, see PhQ::PlanarDisplacement. For scalar displacement components or for the magnitude of a displacement vector, see PhQ::Length.
class DisplacementGradient
Three-dimensional Euclidean displacement gradient dyadic tensor. Gradient of the displacement vector. May be symmetric or asymmetric. Contains nine components in Cartesian coordinates: xx, xy, xz, yx, yy, yz, zx, zy, and zz. For the scalar components or resultants of a displacement gradient tensor, see PhQ::ScalarDisplacementGradient. The time rate of change of a displacement gradient is a velocity gradient; see PhQ::VelocityGradient, PhQ::Time, and PhQ::Frequency.
class Dyad
Three-dimensional Euclidean dyadic tensor. Contains nine components in Cartesian coordinates: xx, xy, xz, yx, yy, yz, zx, zy, and zz. May be symmetric or asymmetric. For a symmetric three-dimensional Euclidean dyadic tensor, see PhQ::SymmetricDyad. For a three-dimensional Euclidean vector, see PhQ::Vector. For a two-dimensional Euclidean vector in the XY plane, see PhQ::PlanarVector.
class DynamicKinematicPressure
Dynamic kinematic pressure, which is dynamic pressure divided by mass density; see PhQ::DynamicPressure and PhQ::MassDensity.
class DynamicPressure
Dynamic pressure, which is the additional pressure arising from a flowing fluid's kinetic energy. Dynamic pressure can be thought of as a flowing fluid's kinetic energy per unit volume. Not to be confused with static pressure or total pressure; see PhQ::StaticPressure and PhQ::TotalPressure. For dynamic kinematic pressure, see PhQ::DynamicKinematicPressure.
class DynamicViscosity
Dynamic viscosity, also known as molecular dynamic viscosity. Dynamic viscosity is the relationship between the viscous stress of a material and its corresponding strain rate. Not to be confused with kinematic viscosity, which is dynamic viscosity divided by mass density; see PhQ::KinematicViscosity and PhQ::MassDensity. Also not to be confused with bulk dynamic viscosity; see PhQ::BulkDynamicViscosity.
class ElectricCharge
Electric charge.
class ElectricCurrent
Electric current, also known as amperage. Represents a flow of electric charge or a time rate of change of electric charge.
class Energy
Energy physical quantity. Can represent any kind of energy, such as kinetic energy, potential energy, internal energy, and so on. The time rate of change of energy is power; see PhQ::Power, PhQ::Time, and PhQ::Frequency.
class Force
Three-dimensional Euclidean force vector. Contains three components in Cartesian coordinates: x, y, and z. For a two-dimensional Euclidean force vector in the XY plane, see PhQ::PlanarForce. For scalar force components or for the magnitude of a force vector, see PhQ::ScalarForce.
class Frequency
Frequency. Inverse of a time duration. See also PhQ::Time.
class GasConstant
Gas constant of a gas. For the mass-specific gas constant, see PhQ::SpecificGasConstant.
class HeatCapacityRatio
Heat capacity ratio, also known as ratio of specific heats, adiabatic index, or Laplace's coefficient. A material's heat capacity ratio is the ratio of its isobaric heat capacity to its isochoric heat capacity; see PhQ::IsobaricHeatCapacity and PhQ::IsochoricHeatCapacity.
class HeatFlux
Three-dimensional Euclidean heat flux vector. Contains three components in Cartesian coordinates: x, y, and z. For a two-dimensional Euclidean heat flux vector in the XY plane, see PhQ::PlanarHeatFlux. For scalar heat flux components or for the magnitude of a heat flux vector, see PhQ::ScalarHeatFlux.
class IsentropicBulkModulus
Isentropic bulk modulus. Not to be confused with the isothermal bulk modulus; see PhQ::IsothermalBulkModulus. Solid materials usually have very similar isentropic and isothermal bulk moduli; however, in general, fluid materials have differing isentropic and isothermal bulk moduli.
class IsobaricHeatCapacity
Isobaric heat capacity, also known as heat capacity at constant pressure. For the mass-specific isobaric heat capacity, see PhQ::SpecificIsobaricHeatCapacity.
class IsochoricHeatCapacity
Isochoric heat capacity, also known as heat capacity at constant volume. For the mass-specific isochoric heat capacity, see PhQ::SpecificIsochoricHeatCapacity.
class IsothermalBulkModulus
Isothermal bulk modulus of a material. Not to be confused with the isentropic bulk modulus; see PhQ::IsentropicBulkModulus. Solid materials usually have very similar isentropic and isothermal bulk moduli; however, in general, fluid materials have differing isentropic and isothermal bulk moduli.
class KinematicViscosity
Kinematic viscosity, also known as molecular kinematic viscosity. Defined as dynamic viscosity divided by mass density; see PhQ::DynamicViscosity and PhQ::MassDensity. Also appears in the definition of the Prandtl number; see PhQ::PrandtlNumber and PhQ::ThermalDiffusivity.
class LameFirstModulus
Lamé's first modulus of elasticity of a deformable solid material. First of the two Lamé parameters. A measure of a deformable solid material's elastic modulus. For other measures of a material's elastic modulus, see PhQ::YoungModulus, PhQ::ShearModulus, PhQ::IsentropicBulkModulus, PhQ::IsothermalBulkModulus, PhQ::PWaveModulus, and PhQ::PoissonRatio.
class Length
Length, distance, or physical size. Can also represent a scalar component or magnitude of a position or displacement vector. For a three-dimensional Euclidean position vector, see PhQ::Position. For a three-dimensional Euclidean displacement vector, see PhQ::Displacement. For a two-dimensional Euclidean position vector in the XY plane, see PhQ::PlanarPosition. For a two-dimensional Euclidean displacement vector in the XY plane, see PhQ::PlanarDisplacement.
class LinearThermalExpansionCoefficient
Linear thermal expansion coefficient. Not to be confused with the volumetric thermal expansion coefficient; see PhQ::VolumetricThermalExpansionCoefficient. For isotropic materials, the volumetric thermal expansion coefficient is usually three times the linear thermal expansion coefficient.
class MachNumber
Mach number of a fluid flow. Measures the local compressibility of a fluid flow. Represents the ratio of a fluid's local speed to its local speed of sound. See also PhQ::Speed and PhQ::SoundSpeed.
class Mass
Mass. For the time rate of change of mass, see PhQ::MassRate; see also PhQ::Time and PhQ::Frequency.
class MassDensity
Mass density. Mass per unit volume; see PhQ::Mass and PhQ::Volume.
class MassRate
Mass rate. Can represent the time rate of change of a mass or a mass flow rate; see PhQ::Mass, PhQ::Time, and PhQ::Frequency.
class Memory
Computer memory. For the time rate of change of computer memory, see PhQ::MemoryRate; see also PhQ::Time and PhQ::Frequency.
class MemoryRate
Computer memory rate. Can represent the time rate of change of memory or a memory transfer speed; see PhQ::Memory, PhQ::Time, and PhQ::Frequency.
class PlanarAcceleration
Two-dimensional Euclidean acceleration vector in the XY plane. Contains two components in Cartesian coordinates: x and y. For a three-dimensional Euclidean acceleration vector, see PhQ::Acceleration. For scalar acceleration components or for the magnitude of an acceleration vector, see PhQ::ScalarAcceleration.
class PlanarDirection
two-dimensional Euclidean direction vector in the XY plane. Contains two components in Cartesian coordinates: x and y. Guaranteed to be either a unit vector or the zero vector (0, 0). For a three-dimensional Euclidean direction vector, see PhQ::Direction.
class PlanarDisplacement
Two-dimensional Euclidean displacement vector in the XY plane. Contains two components in Cartesian coordinates: x and y. Displacement is not to be confused with position; for a two-dimensional Euclidean position vector in the XY plane, see PhQ::PlanarPosition. For a three-dimensional Euclidean displacement vector, see PhQ::Displacement. For scalar displacement components or for the magnitude of a displacement vector, see PhQ::Length.
class PlanarForce
Two-dimensional Euclidean force vector in the XY plane. Contains two components in Cartesian coordinates: x and y. For a three-dimensional Euclidean force vector, see PhQ::Force. For scalar force components or for the magnitude of a force vector, see PhQ::ScalarForce.
class PlanarHeatFlux
Two-dimensional Euclidean heat flux vector in the XY plane. Contains two components in Cartesian coordinates: x and y. For a three-dimensional Euclidean heat flux vector, see PhQ::HeatFlux. For scalar heat flux components or for the magnitude of a heat flux vector, see PhQ::ScalarHeatFlux.
class PlanarPosition
Two-dimensional Euclidean position vector in the XY plane. Contains two components in Cartesian coordinates: x and y. Position is not to be confused with displacement; for a two-dimensional Euclidean displacement vector in the XY plane, see PhQ::PlanarDisplacement. For a three-dimensional Euclidean position vector, see PhQ::Position. For scalar position components or for the magnitude of a position vector, see PhQ::Length.
class PlanarTemperatureGradient
Two-dimensional Euclidean temperature gradient vector in the XY plane. Contains two components in Cartesian coordinates: x and y. For a three-dimensional Euclidean temperature gradient vector, see PhQ::TemperatureGradient. For scalar temperature gradient components or for the magnitude of a temperature gradient vector, see PhQ::ScalarTemperatureGradient.
class PlanarTraction
Two-dimensional Euclidean traction vector in the XY plane. Contains two components in Cartesian coordinates: x and y. Traction is similar to pressure; however, traction can act in any direction, whereas pressure always acts compressively perpendicular to a surface. For a three-dimensional Euclidean traction vector, see PhQ::Traction. For scalar traction components or for the magnitude of a traction vector, see PhQ::ScalarTraction.
class PlanarVector
Two-dimensional Euclidean vector in the XY plane. Contains two components in Cartesian coordinates: x and y. For a three-dimensional Euclidean vector, see PhQ::Vector. For a three-dimensional Euclidean dyadic tensor, see PhQ::Dyad. For a three-dimensional symmetric Euclidean dyadic tensor, see PhQ::SymmetricDyad.
class PlanarVelocity
Two-dimensional Euclidean velocity vector in the XY plane. Contains two components in Cartesian coordinates: x and y. For a three-dimensional Euclidean velocity vector, see PhQ::Velocity. For scalar velocity components or for the magnitude of a velocity vector, see PhQ::Speed.
class PoissonRatio
Poisson's ratio of a deformable solid material. Measures the deformation of a deformable solid material subjected to a load in directions perpendicular to the direction of loading. Poisson's ratios range from -1 to 0.5, though most deformable solid materials have a Poisson's ratio between 0 and 0.5.
class Position
Three-dimensional Euclidean position vector. Contains three components in Cartesian coordinates: x, y, and z. Position is not to be confused with displacement; for a three-dimensional Euclidean displacement vector, see PhQ::Displacement. For a two-dimensional Euclidean position vector in the XY plane, see PhQ::PlanarPosition. For scalar position components or for the magnitude of a position vector, see PhQ::Length.
class Power
Power. Time rate of change of energy or energy transfer rate; see PhQ::Energy, PhQ::Time, and PhQ::Frequency.
class PrandtlNumber
Prandtl number of a fluid. Represents the ratio of the momentum diffusivity to the thermal diffusivity of a fluid. See also PhQ::KinematicViscosity, PhQ::SpecificIsobaricHeatCapacity, PhQ::DynamicViscosity, PhQ::ScalarThermalConductivity, and PhQ::ThermalDiffusivity.
class PWaveModulus
P-wave modulus of elasticity of a deformable solid material. A measure of a deformable solid material's elastic modulus. For other measures of a material's elastic modulus, see PhQ::YoungModulus, PhQ::ShearModulus, PhQ::IsentropicBulkModulus, PhQ::IsothermalBulkModulus, PhQ::LameFirstModulus, and PhQ::PoissonRatio.
class ReynoldsNumber
Reynolds number of a fluid flow. Measures the local turbulence of a fluid flow. Represents the ratio of local inertial forces to local viscous forces in a fluid flow. See also PhQ::MassDensity, PhQ::Speed, PhQ::Length, PhQ::DynamicViscosity, and PhQ::KinematicViscosity.
class ScalarAcceleration
Scalar acceleration component or magnitude of an acceleration vector. For a three-dimensional Euclidean acceleration vector, see PhQ::Acceleration. For a two-dimensional Euclidean acceleration vector in the XY plane, see PhQ::PlanarAcceleration.
class ScalarAngularAcceleration
Scalar angular acceleration. Represents the time rate of change of an angular speed; see also PhQ::AngularSpeed, PhQ::Time, and PhQ::Frequency. Can also represent a component or the magnitude of an angular acceleration pseudovector.
class ScalarDisplacementGradient
Scalar component or resultant of a three-dimensional Euclidean displacement gradient dyadic tensor. For the related tensor, see PhQ::DisplacementGradient. The time rate of change of a scalar displacement gradient is a scalar velocity gradient; see PhQ::ScalarVelocityGradient, PhQ::Time, and PhQ::Frequency.
class ScalarForce
Scalar force component or magnitude of a force vector. For a three-dimensional Euclidean force vector, see PhQ::Force. For a two-dimensional Euclidean force vector in the XY plane, see PhQ::PlanarForce.
class ScalarHeatFlux
Scalar heat flux component or magnitude of a heat flux vector. For a three-dimensional Euclidean heat flux vector, see PhQ::HeatFlux. For a two-dimensional Euclidean heat flux vector in the XY plane, see PhQ::PlanarHeatFlux.
class ScalarStrain
Scalar component or resultant of a three-dimensional Euclidean strain symmetric dyadic tensor. For the related tensor, see PhQ::Strain. For the time rate of change of scalar strain, see PhQ::ScalarStrainRate, PhQ::Time, and PhQ::Frequency.
class ScalarStrainRate
Scalar component or resultant of a three-dimensional Euclidean strain rate symmetric dyadic tensor. For the related tensor, see PhQ::StrainRate. See also PhQ::ScalarStrain, PhQ::Time, and PhQ::Frequency.
class ScalarStress
Scalar component or resultant of a three-dimensional Euclidean Cauchy stress symmetric dyadic tensor. For the related tensor, see PhQ::Stress.
class ScalarTemperatureGradient
Scalar temperature gradient component or magnitude of a temperature gradient vector. For a three-dimensional Euclidean temperature gradient vector, see PhQ::TemperatureGradient. For a two-dimensional Euclidean temperature gradient vector in the XY plane, see PhQ::PlanarTemperatureGradient.
class ScalarThermalConductivity
Scalar component or resultant of a three-dimensional Euclidean thermal conductivity symmetric dyadic tensor. In general, thermal conductivity is a tensor; however, in isotropic materials, thermal conductivity simplifies to a scalar. For the related tensor, see PhQ::ThermalConductivity.
class ScalarTraction
Scalar traction component or magnitude of a traction vector. Traction is similar to pressure; however, traction can act in any direction, whereas pressure always acts compressively perpendicular to a surface. For a three-dimensional Euclidean traction vector, see PhQ::Traction. For a two-dimensional Euclidean traction vector in the XY plane, see PhQ::PlanarTraction.
class ScalarVelocityGradient
Scalar component or resultant of a three-dimensional Euclidean velocity gradient dyadic tensor. For the related tensor, see PhQ::VelocityGradient. Can also represent the time rate of change of a scalar displacement gradient; see PhQ::ScalarDisplacementGradient, PhQ::Time, and PhQ::Frequency.
class ShearModulus
Shear modulus of elasticity of a deformable solid material. A measure of a deformable solid material's elastic modulus. For other measures of a material's elastic modulus, see PhQ::YoungModulus, PhQ::IsentropicBulkModulus, PhQ::IsothermalBulkModulus, PhQ::LameFirstModulus, PhQ::PWaveModulus, and PhQ::PoissonRatio.
class SolidAngle
Solid angle. Measures the field of view of a portion of the surface of the unit sphere viewed from the center of the unit sphere. Typically measured in steradians (sr), which are square radians. The unit sphere has a total solid angle of 4π steradians.
class SoundSpeed
Speed of sound. Applies to any deformable material, including fluids and deformable solids. Defined as the ratio of a material's isentropic bulk modulus to its mass density; see PhQ::IsentropicBulkModulus and PhQ::MassDensity. The speed of sound also appears in the definition of the Mach number; see PhQ::MachNumber and PhQ::Speed.
class SpecificEnergy
Mass-specific energy. Energy per unit mass; see PhQ::Energy and PhQ::Mass.
class SpecificGasConstant
Mass-specific gas constant of a gas. Gas constant per unit mass; see PhQ::GasConstant and PhQ::Mass. PhQ::Mass.
class SpecificIsobaricHeatCapacity
Mass-specific isobaric heat capacity, also known as mass-specific heat capacity at constant pressure, or isobaric heat capacity per unit mass; see PhQ::IsobaricHeatCapacity and PhQ::Mass.
class SpecificIsochoricHeatCapacity
Mass-specific isochoric heat capacity, also known as mass-specific heat capacity at constant volume, or isochoric heat capacity per unit mass; see PhQ::IsochoricHeatCapacity and PhQ::Mass.
class SpecificPower
Mass-specific power. Power per unit mass; see PhQ::Power and PhQ::Mass.
class Speed
Scalar velocity component or magnitude of a velocity vector. For a three-dimensional Euclidean velocity vector, see PhQ::Velocity. For a two-dimensional Euclidean velocity vector in the XY plane, see PhQ::PlanarVelocity.
class StaticKinematicPressure
Static kinematic pressure, which is static pressure divided by mass density; see PhQ::StaticPressure and PhQ::MassDensity.
class StaticPressure
Static pressure. Pressure of a fluid at rest. Not to be confused with dynamic pressure, which is the additional pressure resulting from the kinetic energy of a flowing fluid, or total pressure, which is the sum of static pressure and dynamic pressure. See PhQ::DynamicPressure and PhQ::TotalPressure. Can represent either an absolute static pressure or a static pressure difference relative to another static pressure. For static kinematic pressure, see PhQ::StaticKinematicPressure.
class Strain
Three-dimensional Euclidean strain symmetric dyadic tensor. Contains six components in Cartesian coordinates: xx, xy = yx, xz = zx, yy, yz = zy, and zz. For the scalar components or resultants of a strain tensor, see PhQ::ScalarStrain. For the time rate of change of strain, see PhQ::StrainRate, PhQ::Time, and PhQ::Frequency.
class StrainRate
Three-dimensional Euclidean strain rate symmetric dyadic tensor. Time rate of change of strain. Contains six components in Cartesian coordinates: xx, xy = yx, xz = zx, yy, yz = zy, and zz. For the scalar components or resultants of a strain rate tensor, see PhQ::ScalarStrainRate. See also PhQ::Strain, PhQ::Time, and PhQ::Frequency.
class Stress
Three-dimensional Euclidean Cauchy stress symmetric dyadic tensor. Contains six components in Cartesian coordinates: xx, xy = yx, xz = zx, yy, yz = zy, and zz. For the scalar components or resultants of a Cauchy stress tensor, see PhQ::ScalarStress.
class SubstanceAmount
Amount of substance. Typically measured in moles (mol).
class SymmetricDyad
Symmetric three-dimensional Euclidean dyadic tensor. Contains six components in Cartesian coordinates: xx, xy = yx, xz = zx, yy, yz = zy, and zz. For the general case of a three-dimensional Euclidean dyadic tensor which may be symmetric or asymmetric, see PhQ::Dyad. For a three-dimensional Euclidean vector, see PhQ::Vector. For a two-dimensional Euclidean vector in the XY plane, see PhQ::PlanarVector.
class Temperature
Temperature. For a temperature difference, see PhQ::TemperatureDifference. For the gradient of temperature, see PhQ::TemperatureGradient.
class TemperatureDifference
Temperature difference. Not to be confused with temperature; see PhQ::Temperature. For example, a temperature difference of 20 kelvin is very different from a temperature of 20 kelvin.
class TemperatureGradient
Three-dimensional Euclidean temperature gradient vector. Contains three components in Cartesian coordinates: x, y, and z. For a two-dimensional Euclidean temperature gradient vector in the XY plane, see PhQ::PlanarTemperatureGradient. For scalar temperature gradient components or for the magnitude of a temperature gradient vector, see PhQ::ScalarTemperatureGradient.
class ThermalConductivity
Three-dimensional Euclidean Cauchy thermal conductivity symmetric dyadic tensor. Contains six components in Cartesian coordinates: xx, xy = yx, xz = zx, yy, yz = zy, and zz. In general, thermal conductivity is a tensor; however, in isotropic materials, thermal conductivity simplifies to a scalar. For the scalar components or resultants of a thermal conductivity tensor, see PhQ::ScalarThermalConductivity.
class ThermalDiffusivity
Thermal diffusivity of a material. Measures the rate of heat transfer inside a material. Equals the scalar thermal conductivity divided by the mass density and specific isobaric heat capacity; see PhQ::ScalarThermalConductivity, PhQ::MassDensity, and PhQ::SpecificIsobaricHeatCapacity. Also appears in the definition of the Prandtl number; see PhQ::PrandtlNumber and PhQ::KinematicViscosity.
class Time
Time. Can represent either a point in time, a time duration, or a period. For the inverse of time, see PhQ::Frequency.
class TotalKinematicPressure
Total kinematic pressure, which is total pressure divided by mass density; see PhQ::TotalPressure and PhQ::MassDensity.
class TotalPressure
Total pressure, which is the sum of static pressure and dynamic pressure; see PhQ::StaticPressure and PhQ::DynamicPressure. For total kinematic pressure, see PhQ::TotalKinematicPressure.
class Traction
Three-dimensional Euclidean traction vector. Contains three components in Cartesian coordinates: x, y, and z. Traction is similar to pressure; however, traction can act in any direction, whereas pressure always acts compressively perpendicular to a surface. For a two-dimensional Euclidean traction vector in the XY plane, see PhQ::PlanarTraction. For scalar traction components or for the magnitude of a traction vector, see PhQ::ScalarTraction.
class TransportEnergyConsumption
Transport energy consumption, also known as energy consumption in transport. A measure of energy use per distance traveled. Energy consumption in transport is often measured in joules per metre (J/m), kilowatt-hours per kilometre (kW·hr/km), or kilowatt-hours per mile (kW·hr/mi).
class Vector
Three-dimensional Euclidean vector. Contains three components in Cartesian coordinates: x, y, and z. For a two-dimensional Euclidean vector in the XY plane, see PhQ::PlanarVector. For a three-dimensional Euclidean dyadic tensor, see PhQ::Dyad. For a three-dimensional symmetric Euclidean dyadic tensor, see PhQ::SymmetricDyad.
class VectorArea
Three-dimensional Euclidean vector area. Contains three components in Cartesian coordinates: x, y, and z. A vector area is an oriented area; it is the three-dimensional Euclidean vector representation of an area. Any closed surface has a vector area: it is the surface integral of its surface normal direction. For the scalar components of a vector area or for the magnitude of a vector area, see PhQ::Area.
class Velocity
Three-dimensional Euclidean velocity vector. Contains three components in Cartesian coordinates: x, y, and z. For a two-dimensional Euclidean velocity vector in the XY plane, see PhQ::PlanarVelocity. For scalar velocity components or for the magnitude of a velocity vector, see PhQ::Speed.
class VelocityGradient
Three-dimensional Euclidean velocity gradient dyadic tensor. Gradient of the velocity vector. May be symmetric or asymmetric. Contains nine components in Cartesian coordinates: xx, xy, xz, yx, yy, yz, zx, zy, and zz. For the scalar components or resultants of a velocity gradient tensor, see PhQ::ScalarVelocityGradient. Can also represent the time rate of change of a displacement gradient; see PhQ::DisplacementGradient, PhQ::Time, and PhQ::Frequency.
class Volume
Volume. For the time rate of change of volume, see PhQ::VolumeRate; see also PhQ::Time and PhQ::Frequency.
class VolumeRate
Volume rate. Can represent a time rate of change of a volume or a volume flow rate. See also PhQ::Volume, PhQ::Time, and PhQ::Frequency.
class VolumetricThermalExpansionCoefficient
Volumetric thermal expansion coefficient. Not to be confused with the linear thermal expansion coefficient; see PhQ::LinearThermalExpansionCoefficient. For isotropic materials, the volumetric thermal expansion coefficient is usually three times the linear thermal expansion coefficient.
class YoungModulus
Young's modulus of elasticity of a deformable solid material. A measure of a deformable solid material's elastic modulus. For other measures of a material's elastic modulus, see PhQ::ShearModulus, PhQ::IsentropicBulkModulus, PhQ::IsothermalBulkModulus, PhQ::LameFirstModulus, PhQ::PWaveModulus, and PhQ::PoissonRatio.
Enumerations
enum class UnitSystem : int8_t { MetreKilogramSecondKelvin , MillimetreGramSecondKelvin , FootPoundSecondRankine , InchPoundSecondRankine }
Systems of units of measure. All units of measure in a unit system are standard units of measure. When a physical quantity is expressed in terms of a standard unit of measure, its value does not need to be converted when used in mathematical expressions with other physical quantities expressed in standard units of measure.
Functions
template<typename NumericType >
constexpr bool operator== (const Acceleration< NumericType > &left, const Acceleration< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator!= (const Acceleration< NumericType > &left, const Acceleration< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator< (const Acceleration< NumericType > &left, const Acceleration< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator> (const Acceleration< NumericType > &left, const Acceleration< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator<= (const Acceleration< NumericType > &left, const Acceleration< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator>= (const Acceleration< NumericType > &left, const Acceleration< NumericType > &right) noexcept
template<typename NumericType >
std::ostream & operator<< (std::ostream &stream, const Acceleration< NumericType > &acceleration)
template<typename NumericType >
constexpr Acceleration< NumericType > operator* (const NumericType number, const Acceleration< NumericType > &acceleration)
template<typename NumericType >
constexpr bool operator== (const Angle< NumericType > &left, const Angle< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator!= (const Angle< NumericType > &left, const Angle< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator< (const Angle< NumericType > &left, const Angle< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator> (const Angle< NumericType > &left, const Angle< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator<= (const Angle< NumericType > &left, const Angle< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator>= (const Angle< NumericType > &left, const Angle< NumericType > &right) noexcept
template<typename NumericType >
std::ostream & operator<< (std::ostream &stream, const Angle< NumericType > &angle)
template<typename NumericType >
constexpr Angle< NumericType > operator* (const NumericType number, const Angle< NumericType > &angle)
template<typename NumericType >
constexpr bool operator== (const AngularSpeed< NumericType > &left, const AngularSpeed< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator!= (const AngularSpeed< NumericType > &left, const AngularSpeed< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator< (const AngularSpeed< NumericType > &left, const AngularSpeed< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator> (const AngularSpeed< NumericType > &left, const AngularSpeed< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator<= (const AngularSpeed< NumericType > &left, const AngularSpeed< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator>= (const AngularSpeed< NumericType > &left, const AngularSpeed< NumericType > &right) noexcept
template<typename NumericType >
std::ostream & operator<< (std::ostream &stream, const AngularSpeed< NumericType > &angular_speed)
template<typename NumericType >
constexpr AngularSpeed< NumericType > operator* (const NumericType number, const AngularSpeed< NumericType > &angular_speed)
template<typename NumericType >
constexpr bool operator== (const Area< NumericType > &left, const Area< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator!= (const Area< NumericType > &left, const Area< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator< (const Area< NumericType > &left, const Area< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator> (const Area< NumericType > &left, const Area< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator<= (const Area< NumericType > &left, const Area< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator>= (const Area< NumericType > &left, const Area< NumericType > &right) noexcept
template<typename NumericType >
std::ostream & operator<< (std::ostream &stream, const Area< NumericType > &area)
template<typename NumericType >
constexpr Area< NumericType > operator* (const NumericType number, const Area< NumericType > &area)
template<typename Enumeration >
std::string_view Abbreviation (const Enumeration enumeration)
Returns the abbreviation of a given enumeration value. For example, PhQ::Abbreviation(PhQ::Unit::Time::Hour) returns "hr".
template<typename Enumeration >
std::optional< Enumeration > ParseEnumeration (const std::string_view spelling)
Attempts to parse the given string as an enumeration of the given type. Returns a std::optional container that contains the resulting enumeration if successful, or std::nullopt if the given string could not be parsed into an enumeration of the given type.
template<typename NumericType = double>
std::optional< NumericType > ParseNumber (const std::string &string)
Parses the given string as a number of the given numeric type. Returns a std::optional container that contains the resulting number if successful, or std::nullopt if the string could not be parsed into the given numeric type.
template<>
std::optional< float > ParseNumber (const std::string &string)
Parses the given string as a single-precision floating-point number (a float). Returns a std::optional container that contains the resulting number if successful, or std::nullopt if the string could not be parsed into a float.
template<>
std::optional< double > ParseNumber (const std::string &string)
Parses the given string as a double-precision floating-point number (a double). Returns a std::optional container that contains the resulting number if successful, or std::nullopt if the string could not be parsed into a double.
template<>
std::optional< long double > ParseNumber (const std::string &string)
Parses the given string as an extended-precision floating-point number (a long double). Returns a std::optional container that contains the resulting number if successful, or std::nullopt if the string could not be parsed into a long double.
template<typename NumericType >
std::string Print (const NumericType value)
Prints a given floating-point number as a string. Prints enough digits to represent the number exactly. The printed number of digits depends on the type of the floating-point number.
std::string Lowercase (const std::string_view string)
Returns a copy of the given string where all characters are lowercase.
std::string Uppercase (const std::string_view string)
Returns a copy of the given string where all characters are uppercase.
std::string SnakeCase (const std::string_view string)
Returns a copy of the given string in snake case: all characters are lowercase and all spaces are replaced with underscores.
template<typename NumericType >
constexpr bool operator== (const BulkDynamicViscosity< NumericType > &left, const BulkDynamicViscosity< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator!= (const BulkDynamicViscosity< NumericType > &left, const BulkDynamicViscosity< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator< (const BulkDynamicViscosity< NumericType > &left, const BulkDynamicViscosity< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator> (const BulkDynamicViscosity< NumericType > &left, const BulkDynamicViscosity< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator<= (const BulkDynamicViscosity< NumericType > &left, const BulkDynamicViscosity< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator>= (const BulkDynamicViscosity< NumericType > &left, const BulkDynamicViscosity< NumericType > &right) noexcept
template<typename NumericType >
std::ostream & operator<< (std::ostream &stream, const BulkDynamicViscosity< NumericType > &mass_density)
template<typename NumericType >
constexpr BulkDynamicViscosity< NumericType > operator* (const NumericType number, const BulkDynamicViscosity< NumericType > &mass_density)
std::ostream & operator<< (std::ostream &stream, const ConstitutiveModel &model)
template<typename NumericType >
constexpr bool operator== (const typename ConstitutiveModel::CompressibleNewtonianFluid< NumericType > &left, const typename ConstitutiveModel::CompressibleNewtonianFluid< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator!= (const typename ConstitutiveModel::CompressibleNewtonianFluid< NumericType > &left, const typename ConstitutiveModel::CompressibleNewtonianFluid< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator< (const typename ConstitutiveModel::CompressibleNewtonianFluid< NumericType > &left, const typename ConstitutiveModel::CompressibleNewtonianFluid< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator> (const typename ConstitutiveModel::CompressibleNewtonianFluid< NumericType > &left, const typename ConstitutiveModel::CompressibleNewtonianFluid< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator<= (const typename ConstitutiveModel::CompressibleNewtonianFluid< NumericType > &left, const typename ConstitutiveModel::CompressibleNewtonianFluid< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator>= (const typename ConstitutiveModel::CompressibleNewtonianFluid< NumericType > &left, const typename ConstitutiveModel::CompressibleNewtonianFluid< NumericType > &right) noexcept
template<typename NumericType >
std::ostream & operator<< (std::ostream &stream, const typename ConstitutiveModel::CompressibleNewtonianFluid< NumericType > &model)
template<typename NumericType >
constexpr bool operator== (const typename ConstitutiveModel::ElasticIsotropicSolid< NumericType > &left, const typename ConstitutiveModel::ElasticIsotropicSolid< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator!= (const typename ConstitutiveModel::ElasticIsotropicSolid< NumericType > &left, const typename ConstitutiveModel::ElasticIsotropicSolid< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator< (const typename ConstitutiveModel::ElasticIsotropicSolid< NumericType > &left, const typename ConstitutiveModel::ElasticIsotropicSolid< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator> (const typename ConstitutiveModel::ElasticIsotropicSolid< NumericType > &left, const typename ConstitutiveModel::ElasticIsotropicSolid< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator<= (const typename ConstitutiveModel::ElasticIsotropicSolid< NumericType > &left, const typename ConstitutiveModel::ElasticIsotropicSolid< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator>= (const typename ConstitutiveModel::ElasticIsotropicSolid< NumericType > &left, const typename ConstitutiveModel::ElasticIsotropicSolid< NumericType > &right) noexcept
template<typename NumericType >
std::ostream & operator<< (std::ostream &stream, const typename ConstitutiveModel::ElasticIsotropicSolid< NumericType > &model)
template<typename NumericType >
constexpr bool operator== (const typename ConstitutiveModel::IncompressibleNewtonianFluid< NumericType > &left, const typename ConstitutiveModel::IncompressibleNewtonianFluid< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator!= (const typename ConstitutiveModel::IncompressibleNewtonianFluid< NumericType > &left, const typename ConstitutiveModel::IncompressibleNewtonianFluid< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator< (const typename ConstitutiveModel::IncompressibleNewtonianFluid< NumericType > &left, const typename ConstitutiveModel::IncompressibleNewtonianFluid< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator> (const typename ConstitutiveModel::IncompressibleNewtonianFluid< NumericType > &left, const typename ConstitutiveModel::IncompressibleNewtonianFluid< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator<= (const typename ConstitutiveModel::IncompressibleNewtonianFluid< NumericType > &left, const typename ConstitutiveModel::IncompressibleNewtonianFluid< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator>= (const typename ConstitutiveModel::IncompressibleNewtonianFluid< NumericType > &left, const typename ConstitutiveModel::IncompressibleNewtonianFluid< NumericType > &right) noexcept
template<typename NumericType >
std::ostream & operator<< (std::ostream &stream, const typename ConstitutiveModel::IncompressibleNewtonianFluid< NumericType > &model)
constexpr bool operator== (const Dimensions &left, const Dimensions &right) noexcept
constexpr bool operator!= (const Dimensions &left, const Dimensions &right) noexcept
constexpr bool operator< (const Dimensions &left, const Dimensions &right) noexcept
constexpr bool operator> (const Dimensions &left, const Dimensions &right) noexcept
constexpr bool operator<= (const Dimensions &left, const Dimensions &right) noexcept
constexpr bool operator>= (const Dimensions &left, const Dimensions &right) noexcept
std::ostream & operator<< (std::ostream &stream, const Dimensions &dimensions)
template<typename NumericType >
constexpr bool operator== (const Direction< NumericType > &left, const Direction< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator!= (const Direction< NumericType > &left, const Direction< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator< (const Direction< NumericType > &left, const Direction< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator> (const Direction< NumericType > &left, const Direction< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator<= (const Direction< NumericType > &left, const Direction< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator>= (const Direction< NumericType > &left, const Direction< NumericType > &right) noexcept
template<typename NumericType >
std::ostream & operator<< (std::ostream &stream, const PhQ::Direction< NumericType > &direction)
template<typename NumericType >
constexpr Vector< NumericType > operator* (const SymmetricDyad< NumericType > &symmetric_dyad, const Direction< NumericType > &direction)
template<typename NumericType >
constexpr Vector< NumericType > operator* (const Dyad< NumericType > &dyad, const Direction< NumericType > &direction)
template<typename NumericType >
constexpr bool operator== (const Displacement< NumericType > &left, const Displacement< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator!= (const Displacement< NumericType > &left, const Displacement< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator< (const Displacement< NumericType > &left, const Displacement< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator> (const Displacement< NumericType > &left, const Displacement< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator<= (const Displacement< NumericType > &left, const Displacement< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator>= (const Displacement< NumericType > &left, const Displacement< NumericType > &right) noexcept
template<typename NumericType >
std::ostream & operator<< (std::ostream &stream, const Displacement< NumericType > &displacement)
template<typename NumericType >
constexpr Displacement< NumericType > operator* (const NumericType number, const Displacement< NumericType > &displacement)
template<typename NumericType >
constexpr bool operator== (const DisplacementGradient< NumericType > &left, const DisplacementGradient< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator!= (const DisplacementGradient< NumericType > &left, const DisplacementGradient< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator< (const DisplacementGradient< NumericType > &left, const DisplacementGradient< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator> (const DisplacementGradient< NumericType > &left, const DisplacementGradient< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator<= (const DisplacementGradient< NumericType > &left, const DisplacementGradient< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator>= (const DisplacementGradient< NumericType > &left, const DisplacementGradient< NumericType > &right) noexcept
template<typename NumericType >
std::ostream & operator<< (std::ostream &stream, const DisplacementGradient< NumericType > &displacement_gradient)
template<typename NumericType >
constexpr DisplacementGradient< NumericType > operator* (const NumericType number, const DisplacementGradient< NumericType > &displacement_gradient)
template<typename NumericType >
constexpr bool operator== (const Dyad< NumericType > &left, const Dyad< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator!= (const Dyad< NumericType > &left, const Dyad< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator< (const Dyad< NumericType > &left, const Dyad< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator> (const Dyad< NumericType > &left, const Dyad< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator<= (const Dyad< NumericType > &left, const Dyad< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator>= (const Dyad< NumericType > &left, const Dyad< NumericType > &right) noexcept
template<typename NumericType >
constexpr Dyad< NumericType > operator+ (const Dyad< NumericType > &left, const Dyad< NumericType > &right)
template<typename NumericType >
constexpr Dyad< NumericType > operator- (const Dyad< NumericType > &left, const Dyad< NumericType > &right)
template<typename NumericType , typename OtherNumericType >
constexpr Dyad< NumericType > operator* (const Dyad< NumericType > &dyad, const OtherNumericType number)
template<typename NumericType , typename OtherNumericType >
constexpr Dyad< NumericType > operator* (const OtherNumericType number, const Dyad< NumericType > &dyad)
template<typename NumericType >
constexpr Vector< NumericType > operator* (const Dyad< NumericType > &dyad, const PlanarVector< NumericType > &planar_vector)
template<typename NumericType >
constexpr Vector< NumericType > operator* (const Dyad< NumericType > &dyad, const Vector< NumericType > &vector)
template<typename NumericType >
constexpr Dyad< NumericType > operator* (const SymmetricDyad< NumericType > &left, const SymmetricDyad< NumericType > &right)
template<typename NumericType >
constexpr Dyad< NumericType > operator* (const SymmetricDyad< NumericType > &symmetric_dyad, const Dyad< NumericType > &dyad)
template<typename NumericType >
constexpr Dyad< NumericType > operator* (const Dyad< NumericType > &dyad, const SymmetricDyad< NumericType > &symmetric_dyad)
template<typename NumericType >
constexpr Dyad< NumericType > operator* (const Dyad< NumericType > &left, const Dyad< NumericType > &right)
template<typename NumericType , typename OtherNumericType >
constexpr Dyad< NumericType > operator/ (const Dyad< NumericType > &dyad, const OtherNumericType number)
template<typename NumericType >
std::ostream & operator<< (std::ostream &stream, const Dyad< NumericType > &dyad)
template<typename NumericType >
constexpr bool operator== (const DynamicKinematicPressure< NumericType > &left, const DynamicKinematicPressure< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator!= (const DynamicKinematicPressure< NumericType > &left, const DynamicKinematicPressure< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator< (const DynamicKinematicPressure< NumericType > &left, const DynamicKinematicPressure< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator> (const DynamicKinematicPressure< NumericType > &left, const DynamicKinematicPressure< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator<= (const DynamicKinematicPressure< NumericType > &left, const DynamicKinematicPressure< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator>= (const DynamicKinematicPressure< NumericType > &left, const DynamicKinematicPressure< NumericType > &right) noexcept
template<typename NumericType >
std::ostream & operator<< (std::ostream &stream, const DynamicKinematicPressure< NumericType > &dynamic_kinematic_pressure)
template<typename NumericType >
constexpr DynamicKinematicPressure< NumericType > operator* (const NumericType number, const DynamicKinematicPressure< NumericType > &dynamic_kinematic_pressure)
template<typename NumericType >
constexpr bool operator== (const DynamicPressure< NumericType > &left, const DynamicPressure< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator!= (const DynamicPressure< NumericType > &left, const DynamicPressure< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator< (const DynamicPressure< NumericType > &left, const DynamicPressure< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator> (const DynamicPressure< NumericType > &left, const DynamicPressure< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator<= (const DynamicPressure< NumericType > &left, const DynamicPressure< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator>= (const DynamicPressure< NumericType > &left, const DynamicPressure< NumericType > &right) noexcept
template<typename NumericType >
std::ostream & operator<< (std::ostream &stream, const DynamicPressure< NumericType > &dynamic_pressure)
template<typename NumericType >
constexpr DynamicPressure< NumericType > operator* (const NumericType number, const DynamicPressure< NumericType > &dynamic_pressure)
template<typename NumericType >
constexpr bool operator== (const DynamicViscosity< NumericType > &left, const DynamicViscosity< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator!= (const DynamicViscosity< NumericType > &left, const DynamicViscosity< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator< (const DynamicViscosity< NumericType > &left, const DynamicViscosity< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator> (const DynamicViscosity< NumericType > &left, const DynamicViscosity< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator<= (const DynamicViscosity< NumericType > &left, const DynamicViscosity< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator>= (const DynamicViscosity< NumericType > &left, const DynamicViscosity< NumericType > &right) noexcept
template<typename NumericType >
std::ostream & operator<< (std::ostream &stream, const DynamicViscosity< NumericType > &dynamic_viscosity)
template<typename NumericType >
constexpr DynamicViscosity< NumericType > operator* (const NumericType number, const DynamicViscosity< NumericType > &dynamic_viscosity)
template<typename NumericType >
constexpr bool operator== (const ElectricCharge< NumericType > &left, const ElectricCharge< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator!= (const ElectricCharge< NumericType > &left, const ElectricCharge< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator< (const ElectricCharge< NumericType > &left, const ElectricCharge< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator> (const ElectricCharge< NumericType > &left, const ElectricCharge< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator<= (const ElectricCharge< NumericType > &left, const ElectricCharge< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator>= (const ElectricCharge< NumericType > &left, const ElectricCharge< NumericType > &right) noexcept
template<typename NumericType >
std::ostream & operator<< (std::ostream &stream, const ElectricCharge< NumericType > &electric_charge)
template<typename NumericType >
constexpr ElectricCharge< NumericType > operator* (const NumericType number, const ElectricCharge< NumericType > &electric_charge)
template<typename NumericType >
constexpr bool operator== (const ElectricCurrent< NumericType > &left, const ElectricCurrent< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator!= (const ElectricCurrent< NumericType > &left, const ElectricCurrent< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator< (const ElectricCurrent< NumericType > &left, const ElectricCurrent< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator> (const ElectricCurrent< NumericType > &left, const ElectricCurrent< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator<= (const ElectricCurrent< NumericType > &left, const ElectricCurrent< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator>= (const ElectricCurrent< NumericType > &left, const ElectricCurrent< NumericType > &right) noexcept
template<typename NumericType >
std::ostream & operator<< (std::ostream &stream, const ElectricCurrent< NumericType > &electric_current)
template<typename NumericType >
constexpr ElectricCurrent< NumericType > operator* (const NumericType number, const ElectricCurrent< NumericType > &electric_current)
template<typename NumericType >
constexpr bool operator== (const Energy< NumericType > &left, const Energy< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator!= (const Energy< NumericType > &left, const Energy< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator< (const Energy< NumericType > &left, const Energy< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator> (const Energy< NumericType > &left, const Energy< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator<= (const Energy< NumericType > &left, const Energy< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator>= (const Energy< NumericType > &left, const Energy< NumericType > &right) noexcept
template<typename NumericType >
std::ostream & operator<< (std::ostream &stream, const Energy< NumericType > &energy)
template<typename NumericType >
constexpr Energy< NumericType > operator* (const NumericType number, const Energy< NumericType > &energy)
template<typename NumericType >
constexpr bool operator== (const Force< NumericType > &left, const Force< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator!= (const Force< NumericType > &left, const Force< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator< (const Force< NumericType > &left, const Force< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator> (const Force< NumericType > &left, const Force< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator<= (const Force< NumericType > &left, const Force< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator>= (const Force< NumericType > &left, const Force< NumericType > &right) noexcept
template<typename NumericType >
std::ostream & operator<< (std::ostream &stream, const Force< NumericType > &force)
template<typename NumericType >
constexpr Force< NumericType > operator* (const NumericType number, const Force< NumericType > &force)
template<typename NumericType >
constexpr bool operator== (const Frequency< NumericType > &left, const Frequency< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator!= (const Frequency< NumericType > &left, const Frequency< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator< (const Frequency< NumericType > &left, const Frequency< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator> (const Frequency< NumericType > &left, const Frequency< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator<= (const Frequency< NumericType > &left, const Frequency< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator>= (const Frequency< NumericType > &left, const Frequency< NumericType > &right) noexcept
template<typename NumericType >
std::ostream & operator<< (std::ostream &stream, const Frequency< NumericType > &frequency)
template<typename NumericType >
constexpr Frequency< NumericType > operator* (const NumericType number, const Frequency< NumericType > &frequency)
template<typename NumericType >
constexpr bool operator== (const GasConstant< NumericType > &left, const GasConstant< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator!= (const GasConstant< NumericType > &left, const GasConstant< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator< (const GasConstant< NumericType > &left, const GasConstant< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator> (const GasConstant< NumericType > &left, const GasConstant< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator<= (const GasConstant< NumericType > &left, const GasConstant< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator>= (const GasConstant< NumericType > &left, const GasConstant< NumericType > &right) noexcept
template<typename NumericType >
std::ostream & operator<< (std::ostream &stream, const GasConstant< NumericType > &gas_constant)
template<typename NumericType >
constexpr GasConstant< NumericType > operator* (const NumericType number, const GasConstant< NumericType > &gas_constant)
template<typename NumericType >
constexpr bool operator== (const HeatCapacityRatio< NumericType > &left, const HeatCapacityRatio< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator!= (const HeatCapacityRatio< NumericType > &left, const HeatCapacityRatio< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator< (const HeatCapacityRatio< NumericType > &left, const HeatCapacityRatio< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator> (const HeatCapacityRatio< NumericType > &left, const HeatCapacityRatio< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator<= (const HeatCapacityRatio< NumericType > &left, const HeatCapacityRatio< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator>= (const HeatCapacityRatio< NumericType > &left, const HeatCapacityRatio< NumericType > &right) noexcept
template<typename NumericType >
std::ostream & operator<< (std::ostream &stream, const HeatCapacityRatio< NumericType > &heat_capacity_ratio)
template<typename NumericType >
constexpr HeatCapacityRatio< NumericType > operator* (const NumericType number, const HeatCapacityRatio< NumericType > &heat_capacity_ratio)
template<typename NumericType >
constexpr bool operator== (const HeatFlux< NumericType > &left, const HeatFlux< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator!= (const HeatFlux< NumericType > &left, const HeatFlux< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator< (const HeatFlux< NumericType > &left, const HeatFlux< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator> (const HeatFlux< NumericType > &left, const HeatFlux< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator<= (const HeatFlux< NumericType > &left, const HeatFlux< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator>= (const HeatFlux< NumericType > &left, const HeatFlux< NumericType > &right) noexcept
template<typename NumericType >
std::ostream & operator<< (std::ostream &stream, const HeatFlux< NumericType > &heat_flux)
template<typename NumericType >
constexpr HeatFlux< NumericType > operator* (const NumericType number, const HeatFlux< NumericType > &heat_flux)
template<typename NumericType >
constexpr bool operator== (const IsentropicBulkModulus< NumericType > &left, const IsentropicBulkModulus< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator!= (const IsentropicBulkModulus< NumericType > &left, const IsentropicBulkModulus< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator< (const IsentropicBulkModulus< NumericType > &left, const IsentropicBulkModulus< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator> (const IsentropicBulkModulus< NumericType > &left, const IsentropicBulkModulus< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator<= (const IsentropicBulkModulus< NumericType > &left, const IsentropicBulkModulus< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator>= (const IsentropicBulkModulus< NumericType > &left, const IsentropicBulkModulus< NumericType > &right) noexcept
template<typename NumericType >
std::ostream & operator<< (std::ostream &stream, const IsentropicBulkModulus< NumericType > &isentropic_bulk_modulus)
template<typename NumericType >
constexpr IsentropicBulkModulus< NumericType > operator* (const NumericType number, const IsentropicBulkModulus< NumericType > &isentropic_bulk_modulus)
template<typename NumericType >
constexpr bool operator== (const IsobaricHeatCapacity< NumericType > &left, const IsobaricHeatCapacity< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator!= (const IsobaricHeatCapacity< NumericType > &left, const IsobaricHeatCapacity< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator< (const IsobaricHeatCapacity< NumericType > &left, const IsobaricHeatCapacity< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator> (const IsobaricHeatCapacity< NumericType > &left, const IsobaricHeatCapacity< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator<= (const IsobaricHeatCapacity< NumericType > &left, const IsobaricHeatCapacity< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator>= (const IsobaricHeatCapacity< NumericType > &left, const IsobaricHeatCapacity< NumericType > &right) noexcept
template<typename NumericType >
std::ostream & operator<< (std::ostream &stream, const IsobaricHeatCapacity< NumericType > &isobaric_heat_capacity)
template<typename NumericType >
constexpr IsobaricHeatCapacity< NumericType > operator* (const NumericType number, const IsobaricHeatCapacity< NumericType > &isobaric_heat_capacity)
template<typename NumericType >
constexpr bool operator== (const IsochoricHeatCapacity< NumericType > &left, const IsochoricHeatCapacity< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator!= (const IsochoricHeatCapacity< NumericType > &left, const IsochoricHeatCapacity< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator< (const IsochoricHeatCapacity< NumericType > &left, const IsochoricHeatCapacity< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator> (const IsochoricHeatCapacity< NumericType > &left, const IsochoricHeatCapacity< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator<= (const IsochoricHeatCapacity< NumericType > &left, const IsochoricHeatCapacity< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator>= (const IsochoricHeatCapacity< NumericType > &left, const IsochoricHeatCapacity< NumericType > &right) noexcept
template<typename NumericType >
std::ostream & operator<< (std::ostream &stream, const IsochoricHeatCapacity< NumericType > &isochoric_heat_capacity)
template<typename NumericType >
constexpr IsochoricHeatCapacity< NumericType > operator* (const NumericType number, const IsochoricHeatCapacity< NumericType > &isochoric_heat_capacity)
template<typename NumericType >
constexpr bool operator== (const IsothermalBulkModulus< NumericType > &left, const IsothermalBulkModulus< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator!= (const IsothermalBulkModulus< NumericType > &left, const IsothermalBulkModulus< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator< (const IsothermalBulkModulus< NumericType > &left, const IsothermalBulkModulus< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator> (const IsothermalBulkModulus< NumericType > &left, const IsothermalBulkModulus< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator<= (const IsothermalBulkModulus< NumericType > &left, const IsothermalBulkModulus< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator>= (const IsothermalBulkModulus< NumericType > &left, const IsothermalBulkModulus< NumericType > &right) noexcept
template<typename NumericType >
std::ostream & operator<< (std::ostream &stream, const IsothermalBulkModulus< NumericType > &isothermal_bulk_modulus)
template<typename NumericType >
constexpr IsothermalBulkModulus< NumericType > operator* (const NumericType number, const IsothermalBulkModulus< NumericType > &isothermal_bulk_modulus)
template<typename NumericType >
constexpr bool operator== (const KinematicViscosity< NumericType > &left, const KinematicViscosity< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator!= (const KinematicViscosity< NumericType > &left, const KinematicViscosity< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator< (const KinematicViscosity< NumericType > &left, const KinematicViscosity< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator> (const KinematicViscosity< NumericType > &left, const KinematicViscosity< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator<= (const KinematicViscosity< NumericType > &left, const KinematicViscosity< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator>= (const KinematicViscosity< NumericType > &left, const KinematicViscosity< NumericType > &right) noexcept
template<typename NumericType >
std::ostream & operator<< (std::ostream &stream, const KinematicViscosity< NumericType > &kinematic_viscosity)
template<typename NumericType >
constexpr KinematicViscosity< NumericType > operator* (const NumericType number, const KinematicViscosity< NumericType > &kinematic_viscosity)
template<typename NumericType >
constexpr bool operator== (const LameFirstModulus< NumericType > &left, const LameFirstModulus< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator!= (const LameFirstModulus< NumericType > &left, const LameFirstModulus< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator< (const LameFirstModulus< NumericType > &left, const LameFirstModulus< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator> (const LameFirstModulus< NumericType > &left, const LameFirstModulus< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator<= (const LameFirstModulus< NumericType > &left, const LameFirstModulus< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator>= (const LameFirstModulus< NumericType > &left, const LameFirstModulus< NumericType > &right) noexcept
template<typename NumericType >
std::ostream & operator<< (std::ostream &stream, const LameFirstModulus< NumericType > &lame_first_modulus)
template<typename NumericType >
constexpr LameFirstModulus< NumericType > operator* (const NumericType number, const LameFirstModulus< NumericType > &lame_first_modulus)
template<typename NumericType >
constexpr bool operator== (const Length< NumericType > &left, const Length< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator!= (const Length< NumericType > &left, const Length< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator< (const Length< NumericType > &left, const Length< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator> (const Length< NumericType > &left, const Length< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator<= (const Length< NumericType > &left, const Length< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator>= (const Length< NumericType > &left, const Length< NumericType > &right) noexcept
template<typename NumericType >
std::ostream & operator<< (std::ostream &stream, const Length< NumericType > &length)
template<typename NumericType >
constexpr Length< NumericType > operator* (const NumericType number, const Length< NumericType > &length)
template<typename NumericType >
constexpr bool operator== (const LinearThermalExpansionCoefficient< NumericType > &left, const LinearThermalExpansionCoefficient< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator!= (const LinearThermalExpansionCoefficient< NumericType > &left, const LinearThermalExpansionCoefficient< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator< (const LinearThermalExpansionCoefficient< NumericType > &left, const LinearThermalExpansionCoefficient< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator> (const LinearThermalExpansionCoefficient< NumericType > &left, const LinearThermalExpansionCoefficient< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator<= (const LinearThermalExpansionCoefficient< NumericType > &left, const LinearThermalExpansionCoefficient< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator>= (const LinearThermalExpansionCoefficient< NumericType > &left, const LinearThermalExpansionCoefficient< NumericType > &right) noexcept
template<typename NumericType >
std::ostream & operator<< (std::ostream &stream, const LinearThermalExpansionCoefficient< NumericType > &linear_thermal_expansion_coefficient)
template<typename NumericType >
constexpr LinearThermalExpansionCoefficient< NumericType > operator* (const NumericType number, const LinearThermalExpansionCoefficient< NumericType > &linear_thermal_expansion_coefficient)
template<typename NumericType >
constexpr bool operator== (const MachNumber< NumericType > &left, const MachNumber< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator!= (const MachNumber< NumericType > &left, const MachNumber< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator< (const MachNumber< NumericType > &left, const MachNumber< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator> (const MachNumber< NumericType > &left, const MachNumber< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator<= (const MachNumber< NumericType > &left, const MachNumber< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator>= (const MachNumber< NumericType > &left, const MachNumber< NumericType > &right) noexcept
template<typename NumericType >
std::ostream & operator<< (std::ostream &stream, const MachNumber< NumericType > &mach_number)
template<typename NumericType >
constexpr MachNumber< NumericType > operator* (const NumericType number, const MachNumber< NumericType > &mach_number)
template<typename NumericType >
constexpr bool operator== (const Mass< NumericType > &left, const Mass< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator!= (const Mass< NumericType > &left, const Mass< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator< (const Mass< NumericType > &left, const Mass< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator> (const Mass< NumericType > &left, const Mass< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator<= (const Mass< NumericType > &left, const Mass< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator>= (const Mass< NumericType > &left, const Mass< NumericType > &right) noexcept
template<typename NumericType >
std::ostream & operator<< (std::ostream &stream, const Mass< NumericType > &mass)
template<typename NumericType >
constexpr Mass< NumericType > operator* (const NumericType number, const Mass< NumericType > &mass)
template<typename NumericType >
constexpr bool operator== (const MassDensity< NumericType > &left, const MassDensity< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator!= (const MassDensity< NumericType > &left, const MassDensity< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator< (const MassDensity< NumericType > &left, const MassDensity< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator> (const MassDensity< NumericType > &left, const MassDensity< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator<= (const MassDensity< NumericType > &left, const MassDensity< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator>= (const MassDensity< NumericType > &left, const MassDensity< NumericType > &right) noexcept
template<typename NumericType >
std::ostream & operator<< (std::ostream &stream, const MassDensity< NumericType > &mass_density)
template<typename NumericType >
constexpr MassDensity< NumericType > operator* (const NumericType number, const MassDensity< NumericType > &mass_density)
template<typename NumericType >
constexpr bool operator== (const MassRate< NumericType > &left, const MassRate< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator!= (const MassRate< NumericType > &left, const MassRate< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator< (const MassRate< NumericType > &left, const MassRate< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator> (const MassRate< NumericType > &left, const MassRate< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator<= (const MassRate< NumericType > &left, const MassRate< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator>= (const MassRate< NumericType > &left, const MassRate< NumericType > &right) noexcept
template<typename NumericType >
std::ostream & operator<< (std::ostream &stream, const MassRate< NumericType > &mass_rate)
template<typename NumericType >
constexpr MassRate< NumericType > operator* (const NumericType number, const MassRate< NumericType > &mass_rate)
template<typename NumericType >
constexpr bool operator== (const Memory< NumericType > &left, const Memory< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator!= (const Memory< NumericType > &left, const Memory< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator< (const Memory< NumericType > &left, const Memory< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator> (const Memory< NumericType > &left, const Memory< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator<= (const Memory< NumericType > &left, const Memory< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator>= (const Memory< NumericType > &left, const Memory< NumericType > &right) noexcept
template<typename NumericType >
std::ostream & operator<< (std::ostream &stream, const Memory< NumericType > &memory)
template<typename NumericType >
constexpr Memory< NumericType > operator* (const NumericType number, const Memory< NumericType > &memory)
template<typename NumericType >
constexpr bool operator== (const MemoryRate< NumericType > &left, const MemoryRate< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator!= (const MemoryRate< NumericType > &left, const MemoryRate< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator< (const MemoryRate< NumericType > &left, const MemoryRate< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator> (const MemoryRate< NumericType > &left, const MemoryRate< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator<= (const MemoryRate< NumericType > &left, const MemoryRate< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator>= (const MemoryRate< NumericType > &left, const MemoryRate< NumericType > &right) noexcept
template<typename NumericType >
std::ostream & operator<< (std::ostream &stream, const MemoryRate< NumericType > &memory_rate)
template<typename NumericType >
constexpr MemoryRate< NumericType > operator* (const NumericType number, const MemoryRate< NumericType > &memory_rate)
template<typename NumericType >
constexpr bool operator== (const PlanarAcceleration< NumericType > &left, const PlanarAcceleration< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator!= (const PlanarAcceleration< NumericType > &left, const PlanarAcceleration< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator< (const PlanarAcceleration< NumericType > &left, const PlanarAcceleration< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator> (const PlanarAcceleration< NumericType > &left, const PlanarAcceleration< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator<= (const PlanarAcceleration< NumericType > &left, const PlanarAcceleration< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator>= (const PlanarAcceleration< NumericType > &left, const PlanarAcceleration< NumericType > &right) noexcept
template<typename NumericType >
std::ostream & operator<< (std::ostream &stream, const PlanarAcceleration< NumericType > &planar_acceleration)
template<typename NumericType >
constexpr PlanarAcceleration< NumericType > operator* (const NumericType number, const PlanarAcceleration< NumericType > &planar_acceleration)
template<typename NumericType >
constexpr bool operator== (const PlanarDirection< NumericType > &left, const PlanarDirection< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator!= (const PlanarDirection< NumericType > &left, const PlanarDirection< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator< (const PlanarDirection< NumericType > &left, const PlanarDirection< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator> (const PlanarDirection< NumericType > &left, const PlanarDirection< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator<= (const PlanarDirection< NumericType > &left, const PlanarDirection< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator>= (const PlanarDirection< NumericType > &left, const PlanarDirection< NumericType > &right) noexcept
template<typename NumericType >
std::ostream & operator<< (std::ostream &stream, const PhQ::PlanarDirection< NumericType > &planar_direction)
template<typename NumericType >
constexpr Vector< NumericType > operator* (const SymmetricDyad< NumericType > &symmetric_dyad, const PlanarDirection< NumericType > &planar_direction)
template<typename NumericType >
constexpr Vector< NumericType > operator* (const Dyad< NumericType > &dyad, const PlanarDirection< NumericType > &planar_direction)
template<typename NumericType >
constexpr bool operator== (const PlanarDisplacement< NumericType > &left, const PlanarDisplacement< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator!= (const PlanarDisplacement< NumericType > &left, const PlanarDisplacement< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator< (const PlanarDisplacement< NumericType > &left, const PlanarDisplacement< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator> (const PlanarDisplacement< NumericType > &left, const PlanarDisplacement< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator<= (const PlanarDisplacement< NumericType > &left, const PlanarDisplacement< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator>= (const PlanarDisplacement< NumericType > &left, const PlanarDisplacement< NumericType > &right) noexcept
template<typename NumericType >
std::ostream & operator<< (std::ostream &stream, const PlanarDisplacement< NumericType > &planar_displacement)
template<typename NumericType >
constexpr PlanarDisplacement< NumericType > operator* (const NumericType number, const PlanarDisplacement< NumericType > &planar_displacement)
template<typename NumericType >
constexpr bool operator== (const PlanarForce< NumericType > &left, const PlanarForce< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator!= (const PlanarForce< NumericType > &left, const PlanarForce< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator< (const PlanarForce< NumericType > &left, const PlanarForce< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator> (const PlanarForce< NumericType > &left, const PlanarForce< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator<= (const PlanarForce< NumericType > &left, const PlanarForce< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator>= (const PlanarForce< NumericType > &left, const PlanarForce< NumericType > &right) noexcept
template<typename NumericType >
std::ostream & operator<< (std::ostream &stream, const PlanarForce< NumericType > &planar_force)
template<typename NumericType >
constexpr PlanarForce< NumericType > operator* (const NumericType number, const PlanarForce< NumericType > &planar_force)
template<typename NumericType >
constexpr bool operator== (const PlanarHeatFlux< NumericType > &left, const PlanarHeatFlux< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator!= (const PlanarHeatFlux< NumericType > &left, const PlanarHeatFlux< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator< (const PlanarHeatFlux< NumericType > &left, const PlanarHeatFlux< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator> (const PlanarHeatFlux< NumericType > &left, const PlanarHeatFlux< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator<= (const PlanarHeatFlux< NumericType > &left, const PlanarHeatFlux< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator>= (const PlanarHeatFlux< NumericType > &left, const PlanarHeatFlux< NumericType > &right) noexcept
template<typename NumericType >
std::ostream & operator<< (std::ostream &stream, const PlanarHeatFlux< NumericType > &planar_heat_flux)
template<typename NumericType >
constexpr PlanarHeatFlux< NumericType > operator* (const NumericType number, const PlanarHeatFlux< NumericType > &planar_heat_flux)
template<typename NumericType >
constexpr bool operator== (const PlanarPosition< NumericType > &left, const PlanarPosition< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator!= (const PlanarPosition< NumericType > &left, const PlanarPosition< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator< (const PlanarPosition< NumericType > &left, const PlanarPosition< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator> (const PlanarPosition< NumericType > &left, const PlanarPosition< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator<= (const PlanarPosition< NumericType > &left, const PlanarPosition< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator>= (const PlanarPosition< NumericType > &left, const PlanarPosition< NumericType > &right) noexcept
template<typename NumericType >
std::ostream & operator<< (std::ostream &stream, const PlanarPosition< NumericType > &planar_position)
template<typename NumericType >
constexpr PlanarPosition< NumericType > operator* (const NumericType number, const PlanarPosition< NumericType > &planar_position)
template<typename NumericType >
constexpr bool operator== (const PlanarTemperatureGradient< NumericType > &left, const PlanarTemperatureGradient< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator!= (const PlanarTemperatureGradient< NumericType > &left, const PlanarTemperatureGradient< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator< (const PlanarTemperatureGradient< NumericType > &left, const PlanarTemperatureGradient< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator> (const PlanarTemperatureGradient< NumericType > &left, const PlanarTemperatureGradient< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator<= (const PlanarTemperatureGradient< NumericType > &left, const PlanarTemperatureGradient< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator>= (const PlanarTemperatureGradient< NumericType > &left, const PlanarTemperatureGradient< NumericType > &right) noexcept
template<typename NumericType >
std::ostream & operator<< (std::ostream &stream, const PlanarTemperatureGradient< NumericType > &planar_temperature_gradient)
template<typename NumericType >
constexpr PlanarTemperatureGradient< NumericType > operator* (const NumericType number, const PlanarTemperatureGradient< NumericType > &planar_temperature_gradient)
template<typename NumericType >
constexpr bool operator== (const PlanarTraction< NumericType > &left, const PlanarTraction< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator!= (const PlanarTraction< NumericType > &left, const PlanarTraction< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator< (const PlanarTraction< NumericType > &left, const PlanarTraction< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator> (const PlanarTraction< NumericType > &left, const PlanarTraction< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator<= (const PlanarTraction< NumericType > &left, const PlanarTraction< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator>= (const PlanarTraction< NumericType > &left, const PlanarTraction< NumericType > &right) noexcept
template<typename NumericType >
std::ostream & operator<< (std::ostream &stream, const PlanarTraction< NumericType > &planar_traction)
template<typename NumericType >
constexpr PlanarTraction< NumericType > operator* (const NumericType number, const PlanarTraction< NumericType > &planar_traction)
template<typename NumericType >
constexpr bool operator== (const PlanarVector< NumericType > &left, const PlanarVector< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator!= (const PlanarVector< NumericType > &left, const PlanarVector< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator< (const PlanarVector< NumericType > &left, const PlanarVector< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator> (const PlanarVector< NumericType > &left, const PlanarVector< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator<= (const PlanarVector< NumericType > &left, const PlanarVector< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator>= (const PlanarVector< NumericType > &left, const PlanarVector< NumericType > &right) noexcept
template<typename NumericType >
constexpr PlanarVector< NumericType > operator+ (const PlanarVector< NumericType > &left, const PlanarVector< NumericType > &right)
template<typename NumericType >
constexpr PlanarVector< NumericType > operator- (const PlanarVector< NumericType > &left, const PlanarVector< NumericType > &right)
template<typename NumericType , typename OtherNumericType >
constexpr PlanarVector< NumericType > operator* (const PlanarVector< NumericType > &planar_vector, const OtherNumericType number)
template<typename NumericType , typename OtherNumericType >
constexpr PlanarVector< NumericType > operator* (const OtherNumericType number, const PlanarVector< NumericType > &planar_vector)
template<typename NumericType , typename OtherNumericType >
constexpr PlanarVector< NumericType > operator/ (const PlanarVector< NumericType > &planar_vector, const OtherNumericType number)
template<typename NumericType >
std::ostream & operator<< (std::ostream &stream, const PlanarVector< NumericType > &planar_vector)
template<typename NumericType >
constexpr bool operator== (const PlanarVelocity< NumericType > &left, const PlanarVelocity< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator!= (const PlanarVelocity< NumericType > &left, const PlanarVelocity< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator< (const PlanarVelocity< NumericType > &left, const PlanarVelocity< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator> (const PlanarVelocity< NumericType > &left, const PlanarVelocity< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator<= (const PlanarVelocity< NumericType > &left, const PlanarVelocity< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator>= (const PlanarVelocity< NumericType > &left, const PlanarVelocity< NumericType > &right) noexcept
template<typename NumericType >
std::ostream & operator<< (std::ostream &stream, const PlanarVelocity< NumericType > &planar_velocity)
template<typename NumericType >
constexpr PlanarVelocity< NumericType > operator* (const NumericType number, const PlanarVelocity< NumericType > &planar_velocity)
template<typename NumericType >
constexpr bool operator== (const PoissonRatio< NumericType > &left, const PoissonRatio< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator!= (const PoissonRatio< NumericType > &left, const PoissonRatio< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator< (const PoissonRatio< NumericType > &left, const PoissonRatio< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator> (const PoissonRatio< NumericType > &left, const PoissonRatio< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator<= (const PoissonRatio< NumericType > &left, const PoissonRatio< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator>= (const PoissonRatio< NumericType > &left, const PoissonRatio< NumericType > &right) noexcept
template<typename NumericType >
std::ostream & operator<< (std::ostream &stream, const PoissonRatio< NumericType > &poisson_ratio)
template<typename NumericType >
constexpr PoissonRatio< NumericType > operator* (const NumericType number, const PoissonRatio< NumericType > &poisson_ratio)
template<typename NumericType >
constexpr bool operator== (const Position< NumericType > &left, const Position< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator!= (const Position< NumericType > &left, const Position< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator< (const Position< NumericType > &left, const Position< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator> (const Position< NumericType > &left, const Position< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator<= (const Position< NumericType > &left, const Position< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator>= (const Position< NumericType > &left, const Position< NumericType > &right) noexcept
template<typename NumericType >
std::ostream & operator<< (std::ostream &stream, const Position< NumericType > &position)
template<typename NumericType >
constexpr Position< NumericType > operator* (const NumericType number, const Position< NumericType > &position)
template<typename NumericType >
constexpr bool operator== (const Power< NumericType > &left, const Power< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator!= (const Power< NumericType > &left, const Power< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator< (const Power< NumericType > &left, const Power< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator> (const Power< NumericType > &left, const Power< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator<= (const Power< NumericType > &left, const Power< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator>= (const Power< NumericType > &left, const Power< NumericType > &right) noexcept
template<typename NumericType >
std::ostream & operator<< (std::ostream &stream, const Power< NumericType > &power)
template<typename NumericType >
constexpr Power< NumericType > operator* (const NumericType number, const Power< NumericType > &power)
template<typename NumericType >
constexpr bool operator== (const PrandtlNumber< NumericType > &left, const PrandtlNumber< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator!= (const PrandtlNumber< NumericType > &left, const PrandtlNumber< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator< (const PrandtlNumber< NumericType > &left, const PrandtlNumber< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator> (const PrandtlNumber< NumericType > &left, const PrandtlNumber< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator<= (const PrandtlNumber< NumericType > &left, const PrandtlNumber< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator>= (const PrandtlNumber< NumericType > &left, const PrandtlNumber< NumericType > &right) noexcept
template<typename NumericType >
std::ostream & operator<< (std::ostream &stream, const PrandtlNumber< NumericType > &prandtl_number)
template<typename NumericType >
constexpr PrandtlNumber< NumericType > operator* (const NumericType number, const PrandtlNumber< NumericType > &prandtl_number)
template<typename NumericType >
constexpr bool operator== (const PWaveModulus< NumericType > &left, const PWaveModulus< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator!= (const PWaveModulus< NumericType > &left, const PWaveModulus< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator< (const PWaveModulus< NumericType > &left, const PWaveModulus< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator> (const PWaveModulus< NumericType > &left, const PWaveModulus< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator<= (const PWaveModulus< NumericType > &left, const PWaveModulus< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator>= (const PWaveModulus< NumericType > &left, const PWaveModulus< NumericType > &right) noexcept
template<typename NumericType >
std::ostream & operator<< (std::ostream &stream, const PWaveModulus< NumericType > &p_wave_modulus)
template<typename NumericType >
constexpr PWaveModulus< NumericType > operator* (const NumericType number, const PWaveModulus< NumericType > &p_wave_modulus)
template<typename NumericType >
constexpr bool operator== (const ReynoldsNumber< NumericType > &left, const ReynoldsNumber< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator!= (const ReynoldsNumber< NumericType > &left, const ReynoldsNumber< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator< (const ReynoldsNumber< NumericType > &left, const ReynoldsNumber< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator> (const ReynoldsNumber< NumericType > &left, const ReynoldsNumber< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator<= (const ReynoldsNumber< NumericType > &left, const ReynoldsNumber< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator>= (const ReynoldsNumber< NumericType > &left, const ReynoldsNumber< NumericType > &right) noexcept
template<typename NumericType >
std::ostream & operator<< (std::ostream &stream, const ReynoldsNumber< NumericType > &reynolds_number)
template<typename NumericType >
constexpr ReynoldsNumber< NumericType > operator* (const NumericType number, const ReynoldsNumber< NumericType > &reynolds_number)
template<typename NumericType >
constexpr bool operator== (const ScalarAcceleration< NumericType > &left, const ScalarAcceleration< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator!= (const ScalarAcceleration< NumericType > &left, const ScalarAcceleration< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator< (const ScalarAcceleration< NumericType > &left, const ScalarAcceleration< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator> (const ScalarAcceleration< NumericType > &left, const ScalarAcceleration< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator<= (const ScalarAcceleration< NumericType > &left, const ScalarAcceleration< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator>= (const ScalarAcceleration< NumericType > &left, const ScalarAcceleration< NumericType > &right) noexcept
template<typename NumericType >
std::ostream & operator<< (std::ostream &stream, const ScalarAcceleration< NumericType > &scalar_acceleration)
template<typename NumericType >
constexpr ScalarAcceleration< NumericType > operator* (const NumericType number, const ScalarAcceleration< NumericType > &scalar_acceleration)
template<typename NumericType >
constexpr bool operator== (const ScalarAngularAcceleration< NumericType > &left, const ScalarAngularAcceleration< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator!= (const ScalarAngularAcceleration< NumericType > &left, const ScalarAngularAcceleration< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator< (const ScalarAngularAcceleration< NumericType > &left, const ScalarAngularAcceleration< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator> (const ScalarAngularAcceleration< NumericType > &left, const ScalarAngularAcceleration< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator<= (const ScalarAngularAcceleration< NumericType > &left, const ScalarAngularAcceleration< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator>= (const ScalarAngularAcceleration< NumericType > &left, const ScalarAngularAcceleration< NumericType > &right) noexcept
template<typename NumericType >
std::ostream & operator<< (std::ostream &stream, const ScalarAngularAcceleration< NumericType > &scalar_angular_acceleration)
template<typename NumericType >
constexpr ScalarAngularAcceleration< NumericType > operator* (const NumericType number, const ScalarAngularAcceleration< NumericType > &scalar_angular_acceleration)
template<typename NumericType >
constexpr bool operator== (const ScalarDisplacementGradient< NumericType > &left, const ScalarDisplacementGradient< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator!= (const ScalarDisplacementGradient< NumericType > &left, const ScalarDisplacementGradient< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator< (const ScalarDisplacementGradient< NumericType > &left, const ScalarDisplacementGradient< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator> (const ScalarDisplacementGradient< NumericType > &left, const ScalarDisplacementGradient< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator<= (const ScalarDisplacementGradient< NumericType > &left, const ScalarDisplacementGradient< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator>= (const ScalarDisplacementGradient< NumericType > &left, const ScalarDisplacementGradient< NumericType > &right) noexcept
template<typename NumericType >
std::ostream & operator<< (std::ostream &stream, const ScalarDisplacementGradient< NumericType > &scalar_displacement_gradient)
template<typename NumericType >
constexpr ScalarDisplacementGradient< NumericType > operator* (const NumericType number, const ScalarDisplacementGradient< NumericType > &scalar_displacement_gradient)
template<typename NumericType >
constexpr bool operator== (const ScalarForce< NumericType > &left, const ScalarForce< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator!= (const ScalarForce< NumericType > &left, const ScalarForce< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator< (const ScalarForce< NumericType > &left, const ScalarForce< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator> (const ScalarForce< NumericType > &left, const ScalarForce< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator<= (const ScalarForce< NumericType > &left, const ScalarForce< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator>= (const ScalarForce< NumericType > &left, const ScalarForce< NumericType > &right) noexcept
template<typename NumericType >
std::ostream & operator<< (std::ostream &stream, const ScalarForce< NumericType > &scalar_force)
template<typename NumericType >
constexpr ScalarForce< NumericType > operator* (const NumericType number, const ScalarForce< NumericType > &scalar_force)
template<typename NumericType >
constexpr bool operator== (const ScalarHeatFlux< NumericType > &left, const ScalarHeatFlux< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator!= (const ScalarHeatFlux< NumericType > &left, const ScalarHeatFlux< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator< (const ScalarHeatFlux< NumericType > &left, const ScalarHeatFlux< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator> (const ScalarHeatFlux< NumericType > &left, const ScalarHeatFlux< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator<= (const ScalarHeatFlux< NumericType > &left, const ScalarHeatFlux< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator>= (const ScalarHeatFlux< NumericType > &left, const ScalarHeatFlux< NumericType > &right) noexcept
template<typename NumericType >
std::ostream & operator<< (std::ostream &stream, const ScalarHeatFlux< NumericType > &scalar_heat_flux)
template<typename NumericType >
constexpr ScalarHeatFlux< NumericType > operator* (const NumericType number, const ScalarHeatFlux< NumericType > &scalar_heat_flux)
template<typename NumericType >
constexpr bool operator== (const ScalarStrain< NumericType > &left, const ScalarStrain< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator!= (const ScalarStrain< NumericType > &left, const ScalarStrain< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator< (const ScalarStrain< NumericType > &left, const ScalarStrain< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator> (const ScalarStrain< NumericType > &left, const ScalarStrain< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator<= (const ScalarStrain< NumericType > &left, const ScalarStrain< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator>= (const ScalarStrain< NumericType > &left, const ScalarStrain< NumericType > &right) noexcept
template<typename NumericType >
std::ostream & operator<< (std::ostream &stream, const ScalarStrain< NumericType > &scalar_strain)
template<typename NumericType >
constexpr ScalarStrain< NumericType > operator* (const NumericType number, const ScalarStrain< NumericType > &scalar_strain)
template<typename NumericType >
constexpr bool operator== (const ScalarStrainRate< NumericType > &left, const ScalarStrainRate< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator!= (const ScalarStrainRate< NumericType > &left, const ScalarStrainRate< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator< (const ScalarStrainRate< NumericType > &left, const ScalarStrainRate< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator> (const ScalarStrainRate< NumericType > &left, const ScalarStrainRate< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator<= (const ScalarStrainRate< NumericType > &left, const ScalarStrainRate< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator>= (const ScalarStrainRate< NumericType > &left, const ScalarStrainRate< NumericType > &right) noexcept
template<typename NumericType >
std::ostream & operator<< (std::ostream &stream, const ScalarStrainRate< NumericType > &scalar_strain_rate)
template<typename NumericType >
constexpr ScalarStrainRate< NumericType > operator* (const NumericType number, const ScalarStrainRate< NumericType > &scalar_strain_rate)
template<typename NumericType >
constexpr bool operator== (const ScalarStress< NumericType > &left, const ScalarStress< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator!= (const ScalarStress< NumericType > &left, const ScalarStress< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator< (const ScalarStress< NumericType > &left, const ScalarStress< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator> (const ScalarStress< NumericType > &left, const ScalarStress< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator<= (const ScalarStress< NumericType > &left, const ScalarStress< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator>= (const ScalarStress< NumericType > &left, const ScalarStress< NumericType > &right) noexcept
template<typename NumericType >
std::ostream & operator<< (std::ostream &stream, const ScalarStress< NumericType > &scalar_stress)
template<typename NumericType >
constexpr ScalarStress< NumericType > operator* (const NumericType number, const ScalarStress< NumericType > &scalar_stress)
template<typename NumericType >
constexpr bool operator== (const ScalarTemperatureGradient< NumericType > &left, const ScalarTemperatureGradient< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator!= (const ScalarTemperatureGradient< NumericType > &left, const ScalarTemperatureGradient< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator< (const ScalarTemperatureGradient< NumericType > &left, const ScalarTemperatureGradient< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator> (const ScalarTemperatureGradient< NumericType > &left, const ScalarTemperatureGradient< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator<= (const ScalarTemperatureGradient< NumericType > &left, const ScalarTemperatureGradient< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator>= (const ScalarTemperatureGradient< NumericType > &left, const ScalarTemperatureGradient< NumericType > &right) noexcept
template<typename NumericType >
std::ostream & operator<< (std::ostream &stream, const ScalarTemperatureGradient< NumericType > &scalar_temperature_gradient)
template<typename NumericType >
constexpr ScalarTemperatureGradient< NumericType > operator* (const NumericType number, const ScalarTemperatureGradient< NumericType > &scalar_temperature_gradient)
template<typename NumericType >
constexpr bool operator== (const ScalarThermalConductivity< NumericType > &left, const ScalarThermalConductivity< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator!= (const ScalarThermalConductivity< NumericType > &left, const ScalarThermalConductivity< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator< (const ScalarThermalConductivity< NumericType > &left, const ScalarThermalConductivity< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator> (const ScalarThermalConductivity< NumericType > &left, const ScalarThermalConductivity< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator<= (const ScalarThermalConductivity< NumericType > &left, const ScalarThermalConductivity< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator>= (const ScalarThermalConductivity< NumericType > &left, const ScalarThermalConductivity< NumericType > &right) noexcept
template<typename NumericType >
std::ostream & operator<< (std::ostream &stream, const ScalarThermalConductivity< NumericType > &thermal_conductivity_scalar)
template<typename NumericType >
constexpr ScalarThermalConductivity< NumericType > operator* (const NumericType number, const ScalarThermalConductivity< NumericType > &thermal_conductivity_scalar)
template<typename NumericType >
constexpr bool operator== (const ScalarTraction< NumericType > &left, const ScalarTraction< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator!= (const ScalarTraction< NumericType > &left, const ScalarTraction< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator< (const ScalarTraction< NumericType > &left, const ScalarTraction< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator> (const ScalarTraction< NumericType > &left, const ScalarTraction< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator<= (const ScalarTraction< NumericType > &left, const ScalarTraction< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator>= (const ScalarTraction< NumericType > &left, const ScalarTraction< NumericType > &right) noexcept
template<typename NumericType >
std::ostream & operator<< (std::ostream &stream, const ScalarTraction< NumericType > &static_pressure)
template<typename NumericType >
constexpr ScalarTraction< NumericType > operator* (const NumericType number, const ScalarTraction< NumericType > &static_pressure)
template<typename NumericType >
constexpr bool operator== (const ScalarVelocityGradient< NumericType > &left, const ScalarVelocityGradient< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator!= (const ScalarVelocityGradient< NumericType > &left, const ScalarVelocityGradient< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator< (const ScalarVelocityGradient< NumericType > &left, const ScalarVelocityGradient< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator> (const ScalarVelocityGradient< NumericType > &left, const ScalarVelocityGradient< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator<= (const ScalarVelocityGradient< NumericType > &left, const ScalarVelocityGradient< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator>= (const ScalarVelocityGradient< NumericType > &left, const ScalarVelocityGradient< NumericType > &right) noexcept
template<typename NumericType >
std::ostream & operator<< (std::ostream &stream, const ScalarVelocityGradient< NumericType > &scalar_velocity_gradient)
template<typename NumericType >
constexpr ScalarVelocityGradient< NumericType > operator* (const NumericType number, const ScalarVelocityGradient< NumericType > &scalar_velocity_gradient)
template<typename NumericType >
constexpr bool operator== (const ShearModulus< NumericType > &left, const ShearModulus< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator!= (const ShearModulus< NumericType > &left, const ShearModulus< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator< (const ShearModulus< NumericType > &left, const ShearModulus< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator> (const ShearModulus< NumericType > &left, const ShearModulus< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator<= (const ShearModulus< NumericType > &left, const ShearModulus< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator>= (const ShearModulus< NumericType > &left, const ShearModulus< NumericType > &right) noexcept
template<typename NumericType >
std::ostream & operator<< (std::ostream &stream, const ShearModulus< NumericType > &shear_modulus)
template<typename NumericType >
constexpr ShearModulus< NumericType > operator* (const NumericType number, const ShearModulus< NumericType > &shear_modulus)
template<typename NumericType >
constexpr bool operator== (const SolidAngle< NumericType > &left, const SolidAngle< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator!= (const SolidAngle< NumericType > &left, const SolidAngle< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator< (const SolidAngle< NumericType > &left, const SolidAngle< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator> (const SolidAngle< NumericType > &left, const SolidAngle< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator<= (const SolidAngle< NumericType > &left, const SolidAngle< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator>= (const SolidAngle< NumericType > &left, const SolidAngle< NumericType > &right) noexcept
template<typename NumericType >
std::ostream & operator<< (std::ostream &stream, const SolidAngle< NumericType > &solid_angle)
template<typename NumericType >
constexpr SolidAngle< NumericType > operator* (const NumericType number, const SolidAngle< NumericType > &solid_angle)
template<typename NumericType >
constexpr bool operator== (const SoundSpeed< NumericType > &left, const SoundSpeed< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator!= (const SoundSpeed< NumericType > &left, const SoundSpeed< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator< (const SoundSpeed< NumericType > &left, const SoundSpeed< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator> (const SoundSpeed< NumericType > &left, const SoundSpeed< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator<= (const SoundSpeed< NumericType > &left, const SoundSpeed< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator>= (const SoundSpeed< NumericType > &left, const SoundSpeed< NumericType > &right) noexcept
template<typename NumericType >
std::ostream & operator<< (std::ostream &stream, const SoundSpeed< NumericType > &sound_speed)
template<typename NumericType >
constexpr SoundSpeed< NumericType > operator* (const NumericType number, const SoundSpeed< NumericType > &sound_speed)
template<typename NumericType >
constexpr bool operator== (const SpecificEnergy< NumericType > &left, const SpecificEnergy< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator!= (const SpecificEnergy< NumericType > &left, const SpecificEnergy< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator< (const SpecificEnergy< NumericType > &left, const SpecificEnergy< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator> (const SpecificEnergy< NumericType > &left, const SpecificEnergy< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator<= (const SpecificEnergy< NumericType > &left, const SpecificEnergy< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator>= (const SpecificEnergy< NumericType > &left, const SpecificEnergy< NumericType > &right) noexcept
template<typename NumericType >
std::ostream & operator<< (std::ostream &stream, const SpecificEnergy< NumericType > &specific_energy)
template<typename NumericType >
constexpr SpecificEnergy< NumericType > operator* (const NumericType number, const SpecificEnergy< NumericType > &specific_energy)
template<typename NumericType >
constexpr bool operator== (const SpecificGasConstant< NumericType > &left, const SpecificGasConstant< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator!= (const SpecificGasConstant< NumericType > &left, const SpecificGasConstant< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator< (const SpecificGasConstant< NumericType > &left, const SpecificGasConstant< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator> (const SpecificGasConstant< NumericType > &left, const SpecificGasConstant< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator<= (const SpecificGasConstant< NumericType > &left, const SpecificGasConstant< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator>= (const SpecificGasConstant< NumericType > &left, const SpecificGasConstant< NumericType > &right) noexcept
template<typename NumericType >
std::ostream & operator<< (std::ostream &stream, const SpecificGasConstant< NumericType > &specific_gas_constant)
template<typename NumericType >
constexpr SpecificGasConstant< NumericType > operator* (const NumericType number, const SpecificGasConstant< NumericType > &specific_gas_constant)
template<typename NumericType >
constexpr bool operator== (const SpecificIsobaricHeatCapacity< NumericType > &left, const SpecificIsobaricHeatCapacity< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator!= (const SpecificIsobaricHeatCapacity< NumericType > &left, const SpecificIsobaricHeatCapacity< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator< (const SpecificIsobaricHeatCapacity< NumericType > &left, const SpecificIsobaricHeatCapacity< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator> (const SpecificIsobaricHeatCapacity< NumericType > &left, const SpecificIsobaricHeatCapacity< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator<= (const SpecificIsobaricHeatCapacity< NumericType > &left, const SpecificIsobaricHeatCapacity< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator>= (const SpecificIsobaricHeatCapacity< NumericType > &left, const SpecificIsobaricHeatCapacity< NumericType > &right) noexcept
template<typename NumericType >
std::ostream & operator<< (std::ostream &stream, const SpecificIsobaricHeatCapacity< NumericType > &specific_isobaric_heat_capacity)
template<typename NumericType >
constexpr SpecificIsobaricHeatCapacity< NumericType > operator* (const NumericType number, const SpecificIsobaricHeatCapacity< NumericType > &specific_isobaric_heat_capacity)
template<typename NumericType >
constexpr bool operator== (const SpecificIsochoricHeatCapacity< NumericType > &left, const SpecificIsochoricHeatCapacity< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator!= (const SpecificIsochoricHeatCapacity< NumericType > &left, const SpecificIsochoricHeatCapacity< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator< (const SpecificIsochoricHeatCapacity< NumericType > &left, const SpecificIsochoricHeatCapacity< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator> (const SpecificIsochoricHeatCapacity< NumericType > &left, const SpecificIsochoricHeatCapacity< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator<= (const SpecificIsochoricHeatCapacity< NumericType > &left, const SpecificIsochoricHeatCapacity< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator>= (const SpecificIsochoricHeatCapacity< NumericType > &left, const SpecificIsochoricHeatCapacity< NumericType > &right) noexcept
template<typename NumericType >
std::ostream & operator<< (std::ostream &stream, const SpecificIsochoricHeatCapacity< NumericType > &specific_isochoric_heat_capacity)
template<typename NumericType >
constexpr SpecificIsochoricHeatCapacity< NumericType > operator* (const NumericType number, const SpecificIsochoricHeatCapacity< NumericType > &specific_isochoric_heat_capacity)
template<typename NumericType >
constexpr bool operator== (const SpecificPower< NumericType > &left, const SpecificPower< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator!= (const SpecificPower< NumericType > &left, const SpecificPower< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator< (const SpecificPower< NumericType > &left, const SpecificPower< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator> (const SpecificPower< NumericType > &left, const SpecificPower< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator<= (const SpecificPower< NumericType > &left, const SpecificPower< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator>= (const SpecificPower< NumericType > &left, const SpecificPower< NumericType > &right) noexcept
template<typename NumericType >
std::ostream & operator<< (std::ostream &stream, const SpecificPower< NumericType > &specific_power)
template<typename NumericType >
constexpr SpecificPower< NumericType > operator* (const NumericType number, const SpecificPower< NumericType > &specific_power)
template<typename NumericType >
constexpr bool operator== (const Speed< NumericType > &left, const Speed< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator!= (const Speed< NumericType > &left, const Speed< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator< (const Speed< NumericType > &left, const Speed< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator> (const Speed< NumericType > &left, const Speed< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator<= (const Speed< NumericType > &left, const Speed< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator>= (const Speed< NumericType > &left, const Speed< NumericType > &right) noexcept
template<typename NumericType >
std::ostream & operator<< (std::ostream &stream, const Speed< NumericType > &speed)
template<typename NumericType >
constexpr Speed< NumericType > operator* (const NumericType number, const Speed< NumericType > &speed)
template<typename NumericType >
constexpr bool operator== (const StaticKinematicPressure< NumericType > &left, const StaticKinematicPressure< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator!= (const StaticKinematicPressure< NumericType > &left, const StaticKinematicPressure< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator< (const StaticKinematicPressure< NumericType > &left, const StaticKinematicPressure< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator> (const StaticKinematicPressure< NumericType > &left, const StaticKinematicPressure< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator<= (const StaticKinematicPressure< NumericType > &left, const StaticKinematicPressure< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator>= (const StaticKinematicPressure< NumericType > &left, const StaticKinematicPressure< NumericType > &right) noexcept
template<typename NumericType >
std::ostream & operator<< (std::ostream &stream, const StaticKinematicPressure< NumericType > &static_kinematic_pressure)
template<typename NumericType >
constexpr StaticKinematicPressure< NumericType > operator* (const NumericType number, const StaticKinematicPressure< NumericType > &static_kinematic_pressure)
template<typename NumericType >
constexpr bool operator== (const StaticPressure< NumericType > &left, const StaticPressure< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator!= (const StaticPressure< NumericType > &left, const StaticPressure< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator< (const StaticPressure< NumericType > &left, const StaticPressure< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator> (const StaticPressure< NumericType > &left, const StaticPressure< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator<= (const StaticPressure< NumericType > &left, const StaticPressure< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator>= (const StaticPressure< NumericType > &left, const StaticPressure< NumericType > &right) noexcept
template<typename NumericType >
std::ostream & operator<< (std::ostream &stream, const StaticPressure< NumericType > &static_pressure)
template<typename NumericType >
constexpr StaticPressure< NumericType > operator* (const NumericType number, const StaticPressure< NumericType > &static_pressure)
template<typename NumericType >
constexpr bool operator== (const Strain< NumericType > &left, const Strain< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator!= (const Strain< NumericType > &left, const Strain< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator< (const Strain< NumericType > &left, const Strain< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator> (const Strain< NumericType > &left, const Strain< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator<= (const Strain< NumericType > &left, const Strain< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator>= (const Strain< NumericType > &left, const Strain< NumericType > &right) noexcept
template<typename NumericType >
std::ostream & operator<< (std::ostream &stream, const Strain< NumericType > &strain)
template<typename NumericType >
constexpr Strain< NumericType > operator* (const NumericType number, const Strain< NumericType > &strain)
template<typename NumericType >
constexpr bool operator== (const StrainRate< NumericType > &left, const StrainRate< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator!= (const StrainRate< NumericType > &left, const StrainRate< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator< (const StrainRate< NumericType > &left, const StrainRate< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator> (const StrainRate< NumericType > &left, const StrainRate< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator<= (const StrainRate< NumericType > &left, const StrainRate< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator>= (const StrainRate< NumericType > &left, const StrainRate< NumericType > &right) noexcept
template<typename NumericType >
std::ostream & operator<< (std::ostream &stream, const StrainRate< NumericType > &strain_rate)
template<typename NumericType >
constexpr StrainRate< NumericType > operator* (const NumericType number, const StrainRate< NumericType > &strain_rate)
template<typename NumericType >
constexpr bool operator== (const Stress< NumericType > &left, const Stress< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator!= (const Stress< NumericType > &left, const Stress< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator< (const Stress< NumericType > &left, const Stress< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator> (const Stress< NumericType > &left, const Stress< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator<= (const Stress< NumericType > &left, const Stress< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator>= (const Stress< NumericType > &left, const Stress< NumericType > &right) noexcept
template<typename NumericType >
std::ostream & operator<< (std::ostream &stream, const Stress< NumericType > &stress)
template<typename NumericType >
constexpr Stress< NumericType > operator* (const NumericType number, const Stress< NumericType > &stress)
template<typename NumericType >
constexpr bool operator== (const SubstanceAmount< NumericType > &left, const SubstanceAmount< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator!= (const SubstanceAmount< NumericType > &left, const SubstanceAmount< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator< (const SubstanceAmount< NumericType > &left, const SubstanceAmount< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator> (const SubstanceAmount< NumericType > &left, const SubstanceAmount< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator<= (const SubstanceAmount< NumericType > &left, const SubstanceAmount< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator>= (const SubstanceAmount< NumericType > &left, const SubstanceAmount< NumericType > &right) noexcept
template<typename NumericType >
std::ostream & operator<< (std::ostream &stream, const SubstanceAmount< NumericType > &substance_amount)
template<typename NumericType >
constexpr SubstanceAmount< NumericType > operator* (const NumericType number, const SubstanceAmount< NumericType > &substance_amount)
template<typename NumericType >
constexpr bool operator== (const SymmetricDyad< NumericType > &left, const SymmetricDyad< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator!= (const SymmetricDyad< NumericType > &left, const SymmetricDyad< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator< (const SymmetricDyad< NumericType > &left, const SymmetricDyad< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator> (const SymmetricDyad< NumericType > &left, const SymmetricDyad< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator<= (const SymmetricDyad< NumericType > &left, const SymmetricDyad< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator>= (const SymmetricDyad< NumericType > &left, const SymmetricDyad< NumericType > &right) noexcept
template<typename NumericType >
constexpr SymmetricDyad< NumericType > operator+ (const SymmetricDyad< NumericType > &left, const SymmetricDyad< NumericType > &right)
template<typename NumericType >
constexpr SymmetricDyad< NumericType > operator- (const SymmetricDyad< NumericType > &left, const SymmetricDyad< NumericType > &right)
template<typename NumericType , typename OtherNumericType >
constexpr SymmetricDyad< NumericType > operator* (const SymmetricDyad< NumericType > &symmetric_dyad, const OtherNumericType number)
template<typename NumericType , typename OtherNumericType >
constexpr SymmetricDyad< NumericType > operator* (const OtherNumericType number, const SymmetricDyad< NumericType > &symmetric_dyad)
template<typename NumericType >
constexpr Vector< NumericType > operator* (const SymmetricDyad< NumericType > &symmetric_dyad, const PlanarVector< NumericType > &planar_vector)
template<typename NumericType >
constexpr Vector< NumericType > operator* (const SymmetricDyad< NumericType > &symmetric_dyad, const Vector< NumericType > &vector)
template<typename NumericType , typename OtherNumericType >
constexpr SymmetricDyad< NumericType > operator/ (const SymmetricDyad< NumericType > &symmetric_dyad, const OtherNumericType number)
template<typename NumericType >
std::ostream & operator<< (std::ostream &stream, const SymmetricDyad< NumericType > &symmetric)
template<typename NumericType >
constexpr bool operator== (const Temperature< NumericType > &left, const Temperature< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator!= (const Temperature< NumericType > &left, const Temperature< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator< (const Temperature< NumericType > &left, const Temperature< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator> (const Temperature< NumericType > &left, const Temperature< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator<= (const Temperature< NumericType > &left, const Temperature< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator>= (const Temperature< NumericType > &left, const Temperature< NumericType > &right) noexcept
template<typename NumericType >
std::ostream & operator<< (std::ostream &stream, const Temperature< NumericType > &temperature)
template<typename NumericType >
constexpr Temperature< NumericType > operator* (const NumericType number, const Temperature< NumericType > &temperature)
template<typename NumericType >
constexpr bool operator== (const TemperatureDifference< NumericType > &left, const TemperatureDifference< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator!= (const TemperatureDifference< NumericType > &left, const TemperatureDifference< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator< (const TemperatureDifference< NumericType > &left, const TemperatureDifference< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator> (const TemperatureDifference< NumericType > &left, const TemperatureDifference< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator<= (const TemperatureDifference< NumericType > &left, const TemperatureDifference< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator>= (const TemperatureDifference< NumericType > &left, const TemperatureDifference< NumericType > &right) noexcept
template<typename NumericType >
std::ostream & operator<< (std::ostream &stream, const TemperatureDifference< NumericType > &temperature_difference)
template<typename NumericType >
constexpr TemperatureDifference< NumericType > operator* (const NumericType number, const TemperatureDifference< NumericType > &temperature_difference)
template<typename NumericType >
constexpr bool operator== (const TemperatureGradient< NumericType > &left, const TemperatureGradient< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator!= (const TemperatureGradient< NumericType > &left, const TemperatureGradient< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator< (const TemperatureGradient< NumericType > &left, const TemperatureGradient< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator> (const TemperatureGradient< NumericType > &left, const TemperatureGradient< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator<= (const TemperatureGradient< NumericType > &left, const TemperatureGradient< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator>= (const TemperatureGradient< NumericType > &left, const TemperatureGradient< NumericType > &right) noexcept
template<typename NumericType >
std::ostream & operator<< (std::ostream &stream, const TemperatureGradient< NumericType > &temperature_gradient)
template<typename NumericType >
constexpr TemperatureGradient< NumericType > operator* (const NumericType number, const TemperatureGradient< NumericType > &temperature_gradient)
template<typename NumericType >
constexpr bool operator== (const ThermalConductivity< NumericType > &left, const ThermalConductivity< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator!= (const ThermalConductivity< NumericType > &left, const ThermalConductivity< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator< (const ThermalConductivity< NumericType > &left, const ThermalConductivity< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator> (const ThermalConductivity< NumericType > &left, const ThermalConductivity< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator<= (const ThermalConductivity< NumericType > &left, const ThermalConductivity< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator>= (const ThermalConductivity< NumericType > &left, const ThermalConductivity< NumericType > &right) noexcept
template<typename NumericType >
std::ostream & operator<< (std::ostream &stream, const ThermalConductivity< NumericType > &thermal_conductivity)
template<typename NumericType >
constexpr ThermalConductivity< NumericType > operator* (const NumericType number, const ThermalConductivity< NumericType > &thermal_conductivity)
template<typename NumericType >
constexpr bool operator== (const ThermalDiffusivity< NumericType > &left, const ThermalDiffusivity< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator!= (const ThermalDiffusivity< NumericType > &left, const ThermalDiffusivity< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator< (const ThermalDiffusivity< NumericType > &left, const ThermalDiffusivity< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator> (const ThermalDiffusivity< NumericType > &left, const ThermalDiffusivity< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator<= (const ThermalDiffusivity< NumericType > &left, const ThermalDiffusivity< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator>= (const ThermalDiffusivity< NumericType > &left, const ThermalDiffusivity< NumericType > &right) noexcept
template<typename NumericType >
std::ostream & operator<< (std::ostream &stream, const ThermalDiffusivity< NumericType > &thermal_diffusivity)
template<typename NumericType >
constexpr ThermalDiffusivity< NumericType > operator* (const NumericType number, const ThermalDiffusivity< NumericType > &thermal_diffusivity)
template<typename NumericType >
constexpr bool operator== (const Time< NumericType > &left, const Time< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator!= (const Time< NumericType > &left, const Time< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator< (const Time< NumericType > &left, const Time< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator> (const Time< NumericType > &left, const Time< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator<= (const Time< NumericType > &left, const Time< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator>= (const Time< NumericType > &left, const Time< NumericType > &right) noexcept
template<typename NumericType >
std::ostream & operator<< (std::ostream &stream, const Time< NumericType > &time)
template<typename NumericType >
constexpr Time< NumericType > operator* (const NumericType number, const Time< NumericType > &time)
template<typename NumericType >
constexpr bool operator== (const TotalKinematicPressure< NumericType > &left, const TotalKinematicPressure< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator!= (const TotalKinematicPressure< NumericType > &left, const TotalKinematicPressure< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator< (const TotalKinematicPressure< NumericType > &left, const TotalKinematicPressure< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator> (const TotalKinematicPressure< NumericType > &left, const TotalKinematicPressure< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator<= (const TotalKinematicPressure< NumericType > &left, const TotalKinematicPressure< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator>= (const TotalKinematicPressure< NumericType > &left, const TotalKinematicPressure< NumericType > &right) noexcept
template<typename NumericType >
std::ostream & operator<< (std::ostream &stream, const TotalKinematicPressure< NumericType > &total_kinematic_pressure)
template<typename NumericType >
constexpr TotalKinematicPressure< NumericType > operator* (const NumericType number, const TotalKinematicPressure< NumericType > &total_kinematic_pressure)
template<typename NumericType >
constexpr bool operator== (const TotalPressure< NumericType > &left, const TotalPressure< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator!= (const TotalPressure< NumericType > &left, const TotalPressure< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator< (const TotalPressure< NumericType > &left, const TotalPressure< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator> (const TotalPressure< NumericType > &left, const TotalPressure< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator<= (const TotalPressure< NumericType > &left, const TotalPressure< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator>= (const TotalPressure< NumericType > &left, const TotalPressure< NumericType > &right) noexcept
template<typename NumericType >
std::ostream & operator<< (std::ostream &stream, const TotalPressure< NumericType > &total_pressure)
template<typename NumericType >
constexpr TotalPressure< NumericType > operator* (const NumericType number, const TotalPressure< NumericType > &total_pressure)
template<typename NumericType >
constexpr bool operator== (const Traction< NumericType > &left, const Traction< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator!= (const Traction< NumericType > &left, const Traction< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator< (const Traction< NumericType > &left, const Traction< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator> (const Traction< NumericType > &left, const Traction< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator<= (const Traction< NumericType > &left, const Traction< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator>= (const Traction< NumericType > &left, const Traction< NumericType > &right) noexcept
template<typename NumericType >
std::ostream & operator<< (std::ostream &stream, const Traction< NumericType > &traction)
template<typename NumericType >
constexpr Traction< NumericType > operator* (const NumericType number, const Traction< NumericType > &traction)
template<typename NumericType >
constexpr bool operator== (const TransportEnergyConsumption< NumericType > &left, const TransportEnergyConsumption< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator!= (const TransportEnergyConsumption< NumericType > &left, const TransportEnergyConsumption< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator< (const TransportEnergyConsumption< NumericType > &left, const TransportEnergyConsumption< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator> (const TransportEnergyConsumption< NumericType > &left, const TransportEnergyConsumption< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator<= (const TransportEnergyConsumption< NumericType > &left, const TransportEnergyConsumption< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator>= (const TransportEnergyConsumption< NumericType > &left, const TransportEnergyConsumption< NumericType > &right) noexcept
template<typename NumericType >
std::ostream & operator<< (std::ostream &stream, const TransportEnergyConsumption< NumericType > &transport_energy_consumption)
template<typename NumericType >
constexpr TransportEnergyConsumption< NumericType > operator* (const NumericType number, const TransportEnergyConsumption< NumericType > &transport_energy_consumption)
template<typename Unit , typename NumericType >
void ConvertInPlace (NumericType &value, const Unit original_unit, const Unit new_unit)
Converts a value expressed in a given unit of measure to a new unit of measure. The conversion is performed in-place.
template<typename Unit , std::size_t Size, typename NumericType >
void ConvertInPlace (std::array< NumericType, Size > &values, const Unit original_unit, const Unit new_unit)
Converts an array of values expressed in a given unit of measure to a new unit of measure. The conversion is performed in-place.
template<typename Unit , typename NumericType >
void ConvertInPlace (std::vector< NumericType > &values, const Unit original_unit, const Unit new_unit)
Converts a vector of values expressed in a given unit of measure to a new unit of measure. The conversion is performed in-place.
template<typename Unit , typename NumericType >
void ConvertInPlace (PlanarVector< NumericType > &planar_vector, const Unit original_unit, const Unit new_unit)
Converts a two-dimensional Euclidean planar vector in the XY plane expressed in a given unit of measure to a new unit of measure. The conversion is performed in-place.
template<typename Unit , typename NumericType >
void ConvertInPlace (Vector< NumericType > &vector, const Unit original_unit, const Unit new_unit)
Converts a three-dimensional Euclidean vector expressed in a given unit of measure to a new unit of measure. The conversion is performed in-place.
template<typename Unit , typename NumericType >
void ConvertInPlace (SymmetricDyad< NumericType > &symmetric_dyad, const Unit original_unit, const Unit new_unit)
Converts a three-dimensional Euclidean symmetric dyadic tensor expressed in a given unit of measure to a new unit of measure. The conversion is performed in-place.
template<typename Unit , typename NumericType >
void ConvertInPlace (Dyad< NumericType > &dyad, const Unit original_unit, const Unit new_unit)
Converts a three-dimensional Euclidean dyadic tensor expressed in a given unit of measure to a new unit of measure. The conversion is performed in-place.
template<typename Unit , typename NumericType >
NumericType Convert (const NumericType value, const Unit original_unit, const Unit new_unit)
Converts a value expressed in a given unit of measure to a new unit of measure. Returns the converted value. The original value remains unchanged.
template<typename Unit , std::size_t Size, typename NumericType >
std::array< NumericType, Size > Convert (const std::array< NumericType, Size > &values, const Unit original_unit, const Unit new_unit)
Converts an array of values expressed in a given unit of measure to a new unit of measure. Returns the converted values. The original values remain unchanged.
template<typename Unit , typename NumericType >
std::vector< NumericType > Convert (const std::vector< NumericType > &values, const Unit original_unit, const Unit new_unit)
Converts a vector of values expressed in a given unit of measure to a new unit of measure. Returns the converted values. The original values remain unchanged.
template<typename Unit , typename NumericType >
PlanarVector< NumericType > Convert (const PlanarVector< NumericType > &planar_vector, const Unit original_unit, const Unit new_unit)
Converts a two-dimensional Euclidean planar vector in the XY plane expressed in a given unit of measure to a new unit of measure. Returns the converted vector. The original vector remains unchanged.
template<typename Unit , typename NumericType >
Vector< NumericType > Convert (const Vector< NumericType > &vector, const Unit original_unit, const Unit new_unit)
Converts a three-dimensional Euclidean vector expressed in a given unit of measure to a new unit of measure. Returns the converted vector. The original vector remains unchanged.
template<typename Unit , typename NumericType >
SymmetricDyad< NumericType > Convert (const SymmetricDyad< NumericType > &symmetric_dyad, const Unit original_unit, const Unit new_unit)
Converts a three-dimensional Euclidean symmetric dyadic tensor expressed in a given unit of measure to a new unit of measure. Returns the converted tensor. The original tensor remains unchanged.
template<typename Unit , typename NumericType >
Dyad< NumericType > Convert (const Dyad< NumericType > &dyad, const Unit original_unit, const Unit new_unit)
Converts a three-dimensional Euclidean dyadic tensor expressed in a given unit of measure to a new unit of measure. Returns the converted tensor. The original tensor remains unchanged.
template<typename Unit , Unit OriginalUnit, Unit NewUnit, typename NumericType >
constexpr NumericType ConvertStatically (const NumericType value)
Converts a value expressed in a given unit of measure to a new unit of measure. Returns the converted value. The original value remains unchanged. This function can be evaluated at compile time.
template<typename Unit , Unit OriginalUnit, Unit NewUnit, std::size_t Size, typename NumericType >
constexpr std::array< NumericType, Size > ConvertStatically (const std::array< NumericType, Size > &values)
Converts an array of values expressed in a given unit of measure to a new unit of measure. Returns the converted values. The original values remain unchanged. This function can be evaluated at compile time.
template<typename Unit , Unit OriginalUnit, Unit NewUnit, typename NumericType >
constexpr PlanarVector< NumericType > ConvertStatically (const PlanarVector< NumericType > &planar_vector)
Converts a two-dimensional Euclidean planar vector in the XY plane expressed in a given unit of measure to a new unit of measure. Returns the converted vector. The original vector remains unchanged. This function can be evaluated at compile time.
template<typename Unit , Unit OriginalUnit, Unit NewUnit, typename NumericType >
constexpr Vector< NumericType > ConvertStatically (const Vector< NumericType > &vector)
Converts a three-dimensional Euclidean vector expressed in a given unit of measure to a new unit of measure. Returns the converted vector. The original vector remains unchanged. This function can be evaluated at compile time.
template<typename Unit , Unit OriginalUnit, Unit NewUnit, typename NumericType >
constexpr SymmetricDyad< NumericType > ConvertStatically (const SymmetricDyad< NumericType > &symmetric_dyad)
Converts a three-dimensional Euclidean symmetric dyadic tensor expressed in a given unit of measure to a new unit of measure. Returns the converted tensor. The original tensor remains unchanged. This function can be evaluated at compile time.
template<typename Unit , Unit OriginalUnit, Unit NewUnit, typename NumericType >
constexpr Dyad< NumericType > ConvertStatically (const Dyad< NumericType > &dyad)
Converts a three-dimensional Euclidean dyadic tensor expressed in a given unit of measure to a new unit of measure. Returns the converted tensor. The original tensor remains unchanged. This function can be evaluated at compile time.
std::ostream & operator<< (std::ostream &stream, const Unit::Acceleration unit)
std::ostream & operator<< (std::ostream &stream, const Unit::Angle unit)
std::ostream & operator<< (std::ostream &stream, const Unit::AngularAcceleration unit)
std::ostream & operator<< (std::ostream &stream, const Unit::AngularSpeed unit)
std::ostream & operator<< (std::ostream &stream, const Unit::Area unit)
std::ostream & operator<< (std::ostream &stream, const Unit::Diffusivity unit)
std::ostream & operator<< (std::ostream &stream, const Unit::DynamicViscosity unit)
std::ostream & operator<< (std::ostream &stream, const Unit::ElectricCharge unit)
std::ostream & operator<< (std::ostream &stream, const Unit::ElectricCurrent unit)
std::ostream & operator<< (std::ostream &stream, const Unit::Energy unit)
std::ostream & operator<< (std::ostream &stream, const Unit::EnergyFlux unit)
std::ostream & operator<< (std::ostream &stream, const Unit::Force unit)
std::ostream & operator<< (std::ostream &stream, const Unit::Frequency unit)
std::ostream & operator<< (std::ostream &stream, const Unit::HeatCapacity unit)
std::ostream & operator<< (std::ostream &stream, const Unit::Length unit)
std::ostream & operator<< (std::ostream &stream, const Unit::Mass unit)
std::ostream & operator<< (std::ostream &stream, const Unit::MassDensity unit)
std::ostream & operator<< (std::ostream &stream, const Unit::MassRate unit)
std::ostream & operator<< (std::ostream &stream, const Unit::Memory unit)
std::ostream & operator<< (std::ostream &stream, const Unit::MemoryRate unit)
std::ostream & operator<< (std::ostream &stream, const Unit::Power unit)
std::ostream & operator<< (std::ostream &stream, const Unit::Pressure unit)
std::ostream & operator<< (std::ostream &stream, const Unit::ReciprocalTemperature unit)
std::ostream & operator<< (std::ostream &stream, const Unit::SolidAngle unit)
std::ostream & operator<< (std::ostream &stream, const Unit::SpecificEnergy unit)
std::ostream & operator<< (std::ostream &stream, const Unit::SpecificHeatCapacity unit)
std::ostream & operator<< (std::ostream &stream, const Unit::SpecificPower unit)
std::ostream & operator<< (std::ostream &stream, const Unit::Speed unit)
std::ostream & operator<< (std::ostream &stream, const Unit::SubstanceAmount unit)
std::ostream & operator<< (std::ostream &stream, const Unit::Temperature unit)
std::ostream & operator<< (std::ostream &stream, const Unit::TemperatureDifference unit)
std::ostream & operator<< (std::ostream &stream, const Unit::TemperatureGradient unit)
std::ostream & operator<< (std::ostream &stream, const Unit::ThermalConductivity unit)
std::ostream & operator<< (std::ostream &stream, const Unit::Time unit)
std::ostream & operator<< (std::ostream &stream, const Unit::TransportEnergyConsumption unit)
std::ostream & operator<< (std::ostream &stream, const Unit::Volume unit)
std::ostream & operator<< (std::ostream &stream, const Unit::VolumeRate unit)
template<typename Unit >
Unit ConsistentUnit (const UnitSystem &system)
Returns the unit of a given type that corresponds to a given unit system. For example, PhQ::ConsistentUnit<Force>(PhQ::UnitSystem::MetreKilogramSecondKelvin) returns PhQ::Unit::Force::Newton.
template<typename Unit >
std::optional< UnitSystem > RelatedUnitSystem (const Unit &unit)
Returns the unit system, if any, that corresponds to a given unit, or std::nullptr otherwise. For example, PhQ::RelatedUnitSystem(PhQ::Unit::Length::Millimetre) returns PhQ::UnitSystem::MillimetreGramSecondKelvin.
std::ostream & operator<< (std::ostream &stream, const UnitSystem unit_system)
template<typename NumericType >
constexpr bool operator== (const Vector< NumericType > &left, const Vector< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator!= (const Vector< NumericType > &left, const Vector< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator< (const Vector< NumericType > &left, const Vector< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator> (const Vector< NumericType > &left, const Vector< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator<= (const Vector< NumericType > &left, const Vector< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator>= (const Vector< NumericType > &left, const Vector< NumericType > &right) noexcept
template<typename NumericType >
constexpr Vector< NumericType > operator+ (const Vector< NumericType > &left, const Vector< NumericType > &right)
template<typename NumericType >
constexpr Vector< NumericType > operator- (const Vector< NumericType > &left, const Vector< NumericType > &right)
template<typename NumericType , typename OtherNumericType >
constexpr Vector< NumericType > operator* (const Vector< NumericType > &vector, const OtherNumericType number)
template<typename NumericType , typename OtherNumericType >
constexpr Vector< NumericType > operator* (const OtherNumericType number, const Vector< NumericType > &vector)
template<typename NumericType , typename OtherNumericType >
constexpr Vector< NumericType > operator/ (const Vector< NumericType > &vector, const OtherNumericType number)
template<typename NumericType >
std::ostream & operator<< (std::ostream &stream, const Vector< NumericType > &vector)
template<typename NumericType >
constexpr bool operator== (const VectorArea< NumericType > &left, const VectorArea< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator!= (const VectorArea< NumericType > &left, const VectorArea< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator< (const VectorArea< NumericType > &left, const VectorArea< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator> (const VectorArea< NumericType > &left, const VectorArea< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator<= (const VectorArea< NumericType > &left, const VectorArea< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator>= (const VectorArea< NumericType > &left, const VectorArea< NumericType > &right) noexcept
template<typename NumericType >
std::ostream & operator<< (std::ostream &stream, const VectorArea< NumericType > &vector_area)
template<typename NumericType >
constexpr VectorArea< NumericType > operator* (const NumericType number, const VectorArea< NumericType > &vector_area)
template<typename NumericType >
constexpr bool operator== (const Velocity< NumericType > &left, const Velocity< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator!= (const Velocity< NumericType > &left, const Velocity< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator< (const Velocity< NumericType > &left, const Velocity< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator> (const Velocity< NumericType > &left, const Velocity< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator<= (const Velocity< NumericType > &left, const Velocity< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator>= (const Velocity< NumericType > &left, const Velocity< NumericType > &right) noexcept
template<typename NumericType >
std::ostream & operator<< (std::ostream &stream, const Velocity< NumericType > &velocity)
template<typename NumericType >
constexpr Velocity< NumericType > operator* (const NumericType number, const Velocity< NumericType > &velocity)
template<typename NumericType >
constexpr bool operator== (const VelocityGradient< NumericType > &left, const VelocityGradient< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator!= (const VelocityGradient< NumericType > &left, const VelocityGradient< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator< (const VelocityGradient< NumericType > &left, const VelocityGradient< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator> (const VelocityGradient< NumericType > &left, const VelocityGradient< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator<= (const VelocityGradient< NumericType > &left, const VelocityGradient< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator>= (const VelocityGradient< NumericType > &left, const VelocityGradient< NumericType > &right) noexcept
template<typename NumericType >
std::ostream & operator<< (std::ostream &stream, const VelocityGradient< NumericType > &velocity_gradient)
template<typename NumericType >
constexpr VelocityGradient< NumericType > operator* (const NumericType number, const VelocityGradient< NumericType > &velocity_gradient)
template<typename NumericType >
constexpr bool operator== (const Volume< NumericType > &left, const Volume< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator!= (const Volume< NumericType > &left, const Volume< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator< (const Volume< NumericType > &left, const Volume< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator> (const Volume< NumericType > &left, const Volume< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator<= (const Volume< NumericType > &left, const Volume< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator>= (const Volume< NumericType > &left, const Volume< NumericType > &right) noexcept
template<typename NumericType >
std::ostream & operator<< (std::ostream &stream, const Volume< NumericType > &volume)
template<typename NumericType >
constexpr Volume< NumericType > operator* (const NumericType number, const Volume< NumericType > &volume)
template<typename NumericType >
constexpr bool operator== (const VolumeRate< NumericType > &left, const VolumeRate< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator!= (const VolumeRate< NumericType > &left, const VolumeRate< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator< (const VolumeRate< NumericType > &left, const VolumeRate< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator> (const VolumeRate< NumericType > &left, const VolumeRate< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator<= (const VolumeRate< NumericType > &left, const VolumeRate< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator>= (const VolumeRate< NumericType > &left, const VolumeRate< NumericType > &right) noexcept
template<typename NumericType >
std::ostream & operator<< (std::ostream &stream, const VolumeRate< NumericType > &volume_rate)
template<typename NumericType >
constexpr VolumeRate< NumericType > operator* (const NumericType number, const VolumeRate< NumericType > &volume_rate)
template<typename NumericType >
constexpr bool operator== (const VolumetricThermalExpansionCoefficient< NumericType > &left, const VolumetricThermalExpansionCoefficient< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator!= (const VolumetricThermalExpansionCoefficient< NumericType > &left, const VolumetricThermalExpansionCoefficient< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator< (const VolumetricThermalExpansionCoefficient< NumericType > &left, const VolumetricThermalExpansionCoefficient< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator> (const VolumetricThermalExpansionCoefficient< NumericType > &left, const VolumetricThermalExpansionCoefficient< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator<= (const VolumetricThermalExpansionCoefficient< NumericType > &left, const VolumetricThermalExpansionCoefficient< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator>= (const VolumetricThermalExpansionCoefficient< NumericType > &left, const VolumetricThermalExpansionCoefficient< NumericType > &right) noexcept
template<typename NumericType >
std::ostream & operator<< (std::ostream &stream, const VolumetricThermalExpansionCoefficient< NumericType > &volumetric_thermal_expansion_coefficient)
template<typename NumericType >
constexpr VolumetricThermalExpansionCoefficient< NumericType > operator* (const NumericType number, const VolumetricThermalExpansionCoefficient< NumericType > &volumetric_thermal_expansion_coefficient)
template<typename NumericType >
constexpr bool operator== (const YoungModulus< NumericType > &left, const YoungModulus< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator!= (const YoungModulus< NumericType > &left, const YoungModulus< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator< (const YoungModulus< NumericType > &left, const YoungModulus< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator> (const YoungModulus< NumericType > &left, const YoungModulus< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator<= (const YoungModulus< NumericType > &left, const YoungModulus< NumericType > &right) noexcept
template<typename NumericType >
constexpr bool operator>= (const YoungModulus< NumericType > &left, const YoungModulus< NumericType > &right) noexcept
template<typename NumericType >
std::ostream & operator<< (std::ostream &stream, const YoungModulus< NumericType > &young_modulus)
template<typename NumericType >
constexpr YoungModulus< NumericType > operator* (const NumericType number, const YoungModulus< NumericType > &young_modulus)
Variables
template<typename NumericType = double>
constexpr NumericType Pi
The mathematical constant π = 3.14...
template<>
constexpr float Pi< float > {3.1415927F}
The mathematical constant π = 3.14... expressed as a single-precision 32-bit binary floating-point number.
template<>
constexpr double Pi< double > {3.14159265358979323846}
The mathematical constant π = 3.14... expressed as a double-precision 64-bit binary floating-point number.
template<>
constexpr const long double Pi< long double > {3.141592653589793238462643383279502884L}
The mathematical constant π = 3.14... expressed as an extended-precision binary floating-point number. The exact implementation of the extended-precision type varies; the most common implementations are 64-bit, 80-bit, 96-bit, or 128-bit binary floating-point numbers.
constexpr Dimensions Dimensionless
Dimensionless physical dimension set. This dimension set has all base dimensions of zero. Applies to all dimensionless units of measure and dimensionless physical quantities.
template<typename Unit >
constexpr Dimensions RelatedDimensions
Physical dimension set of a given type of unit of measure. Units of measure are organized into types that share the same physical dimension set.
template<typename Type >
constexpr const Type Standard
Standard unit of measure of a given type. Standard units of measure of different types can be combined with each other without the need for conversions. When a physical quantity is expressed in terms of a standard unit of measure, its value does not need to be converted when used in mathematical expressions with other physical quantities expressed in standard units of measure. For example, the standard unit of time is the second and the standard unit of length is the metre. Correspondingly, the standard unit of speed is the metre per second. Thus, when forming a speed quantity from a length quantity and a time quantity, if all quantities are expressed in these standard units, no unit conversions are needed.
template<>
constexpr const UnitSystem Standard< UnitSystem > {UnitSystem::MetreKilogramSecondKelvin}
The standard unit system: the International System of Units (SI). It uses the following standard units: second (s) for time, metre (m) for length, kilogram (kg) for mass, ampere (A) for electric current, kelvin (K) for temperature, mole (mol) for substance amount, and candela (cd) for luminous intensity.
Detailed Description
Namespace that encompasses all of the Physical Quantities library's content.
Enumeration Type Documentation
UnitSystem
enum class PhQ::UnitSystem : int8_t strong
Systems of units of measure. All units of measure in a unit system are standard units of measure. When a physical quantity is expressed in terms of a standard unit of measure, its value does not need to be converted when used in mathematical expressions with other physical quantities expressed in standard units of measure.
Enumerator
MetreKilogramSecondKelvin
Metre-kilogram-second-kelvin (m·kg·s·K) system.
MillimetreGramSecondKelvin
Millimetre-gram-second-kelvin (mm·g·s·K) system.
FootPoundSecondRankine
Foot-pound-second-rankine (ft·lbf·s·°R) system.
InchPoundSecondRankine
Inch-pound-second-rankine (in·lbf·s·°R) system.
Definition at line 43 of file UnitSystem.hpp.
Function Documentation
Abbreviation()
template<typename Enumeration > std::string_view PhQ::Abbreviation (const Enumeration enumeration) inline
Returns the abbreviation of a given enumeration value. For example, PhQ::Abbreviation(PhQ::Unit::Time::Hour) returns "hr".
Definition at line 89 of file Base.hpp.
Referenced by PhQ::DimensionalDyad< UnitType, NumericType >::JSON(), PhQ::DimensionalPlanarVector< UnitType, NumericType >::JSON(), PhQ::DimensionalScalar< UnitType, NumericType >::JSON(), PhQ::DimensionalSymmetricDyad< UnitType, NumericType >::JSON(), PhQ::DimensionalVector< UnitType, NumericType >::JSON(), PhQ::ConstitutiveModel::CompressibleNewtonianFluid< NumericType >::JSON(), PhQ::ConstitutiveModel::ElasticIsotropicSolid< NumericType >::JSON(), PhQ::ConstitutiveModel::IncompressibleNewtonianFluid< NumericType >::JSON(), PhQ::DimensionalDyad< UnitType, NumericType >::JSON(), PhQ::DimensionalPlanarVector< UnitType, NumericType >::JSON(), PhQ::DimensionalScalar< UnitType, NumericType >::JSON(), PhQ::DimensionalSymmetricDyad< UnitType, NumericType >::JSON(), PhQ::DimensionalVector< UnitType, NumericType >::JSON(), operator<<(), operator<<(), operator<<(), operator<<(), operator<<(), operator<<(), operator<<(), operator<<(), operator<<(), operator<<(), operator<<(), operator<<(), operator<<(), operator<<(), operator<<(), operator<<(), operator<<(), operator<<(), operator<<(), operator<<(), operator<<(), operator<<(), operator<<(), operator<<(), operator<<(), operator<<(), operator<<(), operator<<(), operator<<(), operator<<(), operator<<(), operator<<(), operator<<(), operator<<(), operator<<(), operator<<(), operator<<(), operator<<(), PhQ::DimensionalDyad< UnitType, NumericType >::Print(), PhQ::DimensionalPlanarVector< UnitType, NumericType >::Print(), PhQ::DimensionalScalar< UnitType, NumericType >::Print(), PhQ::DimensionalSymmetricDyad< UnitType, NumericType >::Print(), PhQ::DimensionalVector< UnitType, NumericType >::Print(), PhQ::ConstitutiveModel::CompressibleNewtonianFluid< NumericType >::Print(), PhQ::ConstitutiveModel::ElasticIsotropicSolid< NumericType >::Print(), PhQ::ConstitutiveModel::IncompressibleNewtonianFluid< NumericType >::Print(), PhQ::DimensionalDyad< UnitType, NumericType >::Print(), PhQ::DimensionalPlanarVector< UnitType, NumericType >::Print(), PhQ::DimensionalScalar< UnitType, NumericType >::Print(), PhQ::DimensionalSymmetricDyad< UnitType, NumericType >::Print(), PhQ::DimensionalVector< UnitType, NumericType >::Print(), PhQ::DimensionalDyad< UnitType, NumericType >::XML(), PhQ::DimensionalPlanarVector< UnitType, NumericType >::XML(), PhQ::DimensionalScalar< UnitType, NumericType >::XML(), PhQ::DimensionalSymmetricDyad< UnitType, NumericType >::XML(), PhQ::DimensionalVector< UnitType, NumericType >::XML(), PhQ::ConstitutiveModel::CompressibleNewtonianFluid< NumericType >::XML(), PhQ::ConstitutiveModel::ElasticIsotropicSolid< NumericType >::XML(), PhQ::DimensionalDyad< UnitType, NumericType >::XML(), PhQ::DimensionalPlanarVector< UnitType, NumericType >::XML(), PhQ::DimensionalScalar< UnitType, NumericType >::XML(), PhQ::DimensionalSymmetricDyad< UnitType, NumericType >::XML(), PhQ::DimensionalVector< UnitType, NumericType >::XML(), PhQ::DimensionalDyad< UnitType, NumericType >::YAML(), PhQ::DimensionalPlanarVector< UnitType, NumericType >::YAML(), PhQ::DimensionalScalar< UnitType, NumericType >::YAML(), PhQ::DimensionalSymmetricDyad< UnitType, NumericType >::YAML(), PhQ::DimensionalVector< UnitType, NumericType >::YAML(), PhQ::ConstitutiveModel::CompressibleNewtonianFluid< NumericType >::YAML(), PhQ::ConstitutiveModel::ElasticIsotropicSolid< NumericType >::YAML(), PhQ::DimensionalDyad< UnitType, NumericType >::YAML(), PhQ::DimensionalPlanarVector< UnitType, NumericType >::YAML(), PhQ::DimensionalScalar< UnitType, NumericType >::YAML(), PhQ::DimensionalSymmetricDyad< UnitType, NumericType >::YAML(), and PhQ::DimensionalVector< UnitType, NumericType >::YAML().
ConsistentUnit()
template<typename Unit > Unit PhQ::ConsistentUnit (const UnitSystem & system) inline
Returns the unit of a given type that corresponds to a given unit system. For example, PhQ::ConsistentUnit<Force>(PhQ::UnitSystem::MetreKilogramSecondKelvin) returns PhQ::Unit::Force::Newton.
Definition at line 225 of file UnitSystem.hpp.
Convert() [1/7]
template<typename Unit , typename NumericType > Dyad< NumericType > PhQ::Convert (const Dyad< NumericType > & dyad, const Unit original_unit, const Unit new_unit) inline
Converts a three-dimensional Euclidean dyadic tensor expressed in a given unit of measure to a new unit of measure. Returns the converted tensor. The original tensor remains unchanged.
Definition at line 268 of file Unit.hpp.
References PhQ::Dyad< NumericType >::xx_xy_xz_yx_yy_yz_zx_zy_zz().
Convert() [2/7]
template<typename Unit , typename NumericType > NumericType PhQ::Convert (const NumericType value, const Unit original_unit, const Unit new_unit) inline
Converts a value expressed in a given unit of measure to a new unit of measure. Returns the converted value. The original value remains unchanged.
Definition at line 210 of file Unit.hpp.
Referenced by PhQ::DimensionalDyad< UnitType, NumericType >::Value(), PhQ::DimensionalPlanarVector< UnitType, NumericType >::Value(), PhQ::DimensionalScalar< UnitType, NumericType >::Value(), PhQ::DimensionalSymmetricDyad< UnitType, NumericType >::Value(), and PhQ::DimensionalVector< UnitType, NumericType >::Value().
Convert() [3/7]
template<typename Unit , typename NumericType > PlanarVector< NumericType > PhQ::Convert (const PlanarVector< NumericType > & planar_vector, const Unit original_unit, const Unit new_unit) inline
Converts a two-dimensional Euclidean planar vector in the XY plane expressed in a given unit of measure to a new unit of measure. Returns the converted vector. The original vector remains unchanged.
Definition at line 241 of file Unit.hpp.
References PhQ::PlanarVector< NumericType >::x_y().
Convert() [4/7]
template<typename Unit , std::size_t Size, typename NumericType > std::array< NumericType, Size > PhQ::Convert (const std::array< NumericType, Size > & values, const Unit original_unit, const Unit new_unit) inline
Converts an array of values expressed in a given unit of measure to a new unit of measure. Returns the converted values. The original values remain unchanged.
Definition at line 220 of file Unit.hpp.
Convert() [5/7]
template<typename Unit , typename NumericType > std::vector< NumericType > PhQ::Convert (const std::vector< NumericType > & values, const Unit original_unit, const Unit new_unit) inline
Converts a vector of values expressed in a given unit of measure to a new unit of measure. Returns the converted values. The original values remain unchanged.
Definition at line 230 of file Unit.hpp.
Convert() [6/7]
template<typename Unit , typename NumericType > SymmetricDyad< NumericType > PhQ::Convert (const SymmetricDyad< NumericType > & symmetric_dyad, const Unit original_unit, const Unit new_unit) inline
Converts a three-dimensional Euclidean symmetric dyadic tensor expressed in a given unit of measure to a new unit of measure. Returns the converted tensor. The original tensor remains unchanged.
Definition at line 258 of file Unit.hpp.
References PhQ::SymmetricDyad< NumericType >::xx_xy_xz_yy_yz_zz().
Convert() [7/7]
template<typename Unit , typename NumericType > Vector< NumericType > PhQ::Convert (const Vector< NumericType > & vector, const Unit original_unit, const Unit new_unit) inline
Converts a three-dimensional Euclidean vector expressed in a given unit of measure to a new unit of measure. Returns the converted vector. The original vector remains unchanged.
Definition at line 249 of file Unit.hpp.
References PhQ::Vector< NumericType >::x_y_z().
ConvertInPlace() [1/7]
template<typename Unit , typename NumericType > void PhQ::ConvertInPlace (Dyad< NumericType > & dyad, const Unit original_unit, const Unit new_unit) inline
Converts a three-dimensional Euclidean dyadic tensor expressed in a given unit of measure to a new unit of measure. The conversion is performed in-place.
Definition at line 202 of file Unit.hpp.
References PhQ::Dyad< NumericType >::Mutable_xx_xy_xz_yx_yy_yz_zx_zy_zz().
ConvertInPlace() [2/7]
template<typename Unit , typename NumericType > void PhQ::ConvertInPlace (NumericType & value, const Unit original_unit, const Unit new_unit) inline
Converts a value expressed in a given unit of measure to a new unit of measure. The conversion is performed in-place.
Definition at line 128 of file Unit.hpp.
Referenced by PhQ::DimensionalDyad< UnitType, NumericType >::DimensionalDyad(), PhQ::DimensionalPlanarVector< UnitType, NumericType >::DimensionalPlanarVector(), PhQ::DimensionalScalar< UnitType, NumericType >::DimensionalScalar(), PhQ::DimensionalSymmetricDyad< UnitType, NumericType >::DimensionalSymmetricDyad(), and PhQ::DimensionalVector< UnitType, NumericType >::DimensionalVector().
ConvertInPlace() [3/7]
template<typename Unit , typename NumericType > void PhQ::ConvertInPlace (PlanarVector< NumericType > & planar_vector, const Unit original_unit, const Unit new_unit) inline
Converts a two-dimensional Euclidean planar vector in the XY plane expressed in a given unit of measure to a new unit of measure. The conversion is performed in-place.
Definition at line 177 of file Unit.hpp.
References PhQ::PlanarVector< NumericType >::Mutable_x_y().
ConvertInPlace() [4/7]
template<typename Unit , std::size_t Size, typename NumericType > void PhQ::ConvertInPlace (std::array< NumericType, Size > & values, const Unit original_unit, const Unit new_unit) inline
Converts an array of values expressed in a given unit of measure to a new unit of measure. The conversion is performed in-place.
Definition at line 143 of file Unit.hpp.
ConvertInPlace() [5/7]
template<typename Unit , typename NumericType > void PhQ::ConvertInPlace (std::vector< NumericType > & values, const Unit original_unit, const Unit new_unit) inline
Converts a vector of values expressed in a given unit of measure to a new unit of measure. The conversion is performed in-place.
Definition at line 160 of file Unit.hpp.
ConvertInPlace() [6/7]
template<typename Unit , typename NumericType > void PhQ::ConvertInPlace (SymmetricDyad< NumericType > & symmetric_dyad, const Unit original_unit, const Unit new_unit) inline
Converts a three-dimensional Euclidean symmetric dyadic tensor expressed in a given unit of measure to a new unit of measure. The conversion is performed in-place.
Definition at line 193 of file Unit.hpp.
References PhQ::SymmetricDyad< NumericType >::Mutable_xx_xy_xz_yy_yz_zz().
ConvertInPlace() [7/7]
template<typename Unit , typename NumericType > void PhQ::ConvertInPlace (Vector< NumericType > & vector, const Unit original_unit, const Unit new_unit) inline
Converts a three-dimensional Euclidean vector expressed in a given unit of measure to a new unit of measure. The conversion is performed in-place.
Definition at line 185 of file Unit.hpp.
References PhQ::Vector< NumericType >::Mutable_x_y_z().
ConvertStatically() [1/6]
template<typename Unit , Unit OriginalUnit, Unit NewUnit, typename NumericType > constexpr Dyad< NumericType > PhQ::ConvertStatically (const Dyad< NumericType > & dyad) inline constexpr
Converts a three-dimensional Euclidean dyadic tensor expressed in a given unit of measure to a new unit of measure. Returns the converted tensor. The original tensor remains unchanged. This function can be evaluated at compile time.
Definition at line 336 of file Unit.hpp.
References PhQ::Dyad< NumericType >::xx_xy_xz_yx_yy_yz_zx_zy_zz().
ConvertStatically() [2/6]
template<typename Unit , Unit OriginalUnit, Unit NewUnit, typename NumericType > constexpr NumericType PhQ::ConvertStatically (const NumericType value) inline constexpr
Converts a value expressed in a given unit of measure to a new unit of measure. Returns the converted value. The original value remains unchanged. This function can be evaluated at compile time.
Definition at line 278 of file Unit.hpp.
Referenced by PhQ::TransportEnergyConsumption< NumericType >::Create().
ConvertStatically() [3/6]
template<typename Unit , Unit OriginalUnit, Unit NewUnit, typename NumericType > constexpr PlanarVector< NumericType > PhQ::ConvertStatically (const PlanarVector< NumericType > & planar_vector) inline constexpr
Converts a two-dimensional Euclidean planar vector in the XY plane expressed in a given unit of measure to a new unit of measure. Returns the converted vector. The original vector remains unchanged. This function can be evaluated at compile time.
Definition at line 307 of file Unit.hpp.
References PhQ::PlanarVector< NumericType >::x_y().
ConvertStatically() [4/6]
template<typename Unit , Unit OriginalUnit, Unit NewUnit, std::size_t Size, typename NumericType > constexpr std::array< NumericType, Size > PhQ::ConvertStatically (const std::array< NumericType, Size > & values) inline constexpr
Converts an array of values expressed in a given unit of measure to a new unit of measure. Returns the converted values. The original values remain unchanged. This function can be evaluated at compile time.
Definition at line 292 of file Unit.hpp.
ConvertStatically() [5/6]
template<typename Unit , Unit OriginalUnit, Unit NewUnit, typename NumericType > constexpr SymmetricDyad< NumericType > PhQ::ConvertStatically (const SymmetricDyad< NumericType > & symmetric_dyad) inline constexpr
Converts a three-dimensional Euclidean symmetric dyadic tensor expressed in a given unit of measure to a new unit of measure. Returns the converted tensor. The original tensor remains unchanged. This function can be evaluated at compile time.
Definition at line 326 of file Unit.hpp.
References PhQ::SymmetricDyad< NumericType >::xx_xy_xz_yy_yz_zz().
ConvertStatically() [6/6]
template<typename Unit , Unit OriginalUnit, Unit NewUnit, typename NumericType > constexpr Vector< NumericType > PhQ::ConvertStatically (const Vector< NumericType > & vector) inline constexpr
Converts a three-dimensional Euclidean vector expressed in a given unit of measure to a new unit of measure. Returns the converted vector. The original vector remains unchanged. This function can be evaluated at compile time.
Definition at line 317 of file Unit.hpp.
References PhQ::Vector< NumericType >::x_y_z().
Lowercase()
std::string PhQ::Lowercase (const std::string_view string) inline
Returns a copy of the given string where all characters are lowercase.
Definition at line 244 of file Base.hpp.
Referenced by SnakeCase().
operator!=() [1/100]
template<typename NumericType > constexpr bool PhQ::operator!= (const Acceleration< NumericType > & left, const Acceleration< NumericType > & right) inline constexpr noexcept
Definition at line 235 of file Acceleration.hpp.
operator!=() [2/100]
template<typename NumericType > constexpr bool PhQ::operator!= (const Angle< NumericType > & left, const Angle< NumericType > & right) inline constexpr noexcept
Definition at line 352 of file Angle.hpp.
operator!=() [3/100]
template<typename NumericType > constexpr bool PhQ::operator!= (const AngularSpeed< NumericType > & left, const AngularSpeed< NumericType > & right) inline constexpr noexcept
Definition at line 192 of file AngularSpeed.hpp.
operator!=() [4/100]
template<typename NumericType > constexpr bool PhQ::operator!= (const Area< NumericType > & left, const Area< NumericType > & right) inline constexpr noexcept
Definition at line 201 of file Area.hpp.
operator!=() [5/100]
template<typename NumericType > constexpr bool PhQ::operator!= (const BulkDynamicViscosity< NumericType > & left, const BulkDynamicViscosity< NumericType > & right) inline constexpr noexcept
Definition at line 150 of file BulkDynamicViscosity.hpp.
operator!=() [6/100]
constexpr bool PhQ::operator!= (const Dimensions & left, const Dimensions & right) inline constexpr noexcept
Definition at line 339 of file Dimensions.hpp.
operator!=() [7/100]
template<typename NumericType > constexpr bool PhQ::operator!= (const Direction< NumericType > & left, const Direction< NumericType > & right) inline constexpr noexcept
Definition at line 335 of file Direction.hpp.
operator!=() [8/100]
template<typename NumericType > constexpr bool PhQ::operator!= (const Displacement< NumericType > & left, const Displacement< NumericType > & right) inline constexpr noexcept
Definition at line 251 of file Displacement.hpp.
operator!=() [9/100]
template<typename NumericType > constexpr bool PhQ::operator!= (const DisplacementGradient< NumericType > & left, const DisplacementGradient< NumericType > & right) inline constexpr noexcept
Definition at line 221 of file DisplacementGradient.hpp.
operator!=() [10/100]
template<typename NumericType > constexpr bool PhQ::operator!= (const Dyad< NumericType > & left, const Dyad< NumericType > & right) inline constexpr noexcept
Definition at line 488 of file Dyad.hpp.
operator!=() [11/100]
template<typename NumericType > constexpr bool PhQ::operator!= (const DynamicKinematicPressure< NumericType > & left, const DynamicKinematicPressure< NumericType > & right) inline constexpr noexcept
Definition at line 180 of file DynamicKinematicPressure.hpp.
operator!=() [12/100]
template<typename NumericType > constexpr bool PhQ::operator!= (const DynamicPressure< NumericType > & left, const DynamicPressure< NumericType > & right) inline constexpr noexcept
Definition at line 177 of file DynamicPressure.hpp.
operator!=() [13/100]
template<typename NumericType > constexpr bool PhQ::operator!= (const DynamicViscosity< NumericType > & left, const DynamicViscosity< NumericType > & right) inline constexpr noexcept
Definition at line 192 of file DynamicViscosity.hpp.
operator!=() [14/100]
template<typename NumericType > constexpr bool PhQ::operator!= (const ElectricCharge< NumericType > & left, const ElectricCharge< NumericType > & right) inline constexpr noexcept
Definition at line 172 of file ElectricCharge.hpp.
operator!=() [15/100]
template<typename NumericType > constexpr bool PhQ::operator!= (const ElectricCurrent< NumericType > & left, const ElectricCurrent< NumericType > & right) inline constexpr noexcept
Definition at line 174 of file ElectricCurrent.hpp.
operator!=() [16/100]
template<typename NumericType > constexpr bool PhQ::operator!= (const Energy< NumericType > & left, const Energy< NumericType > & right) inline constexpr noexcept
Definition at line 207 of file Energy.hpp.
operator!=() [17/100]
template<typename NumericType > constexpr bool PhQ::operator!= (const Force< NumericType > & left, const Force< NumericType > & right) inline constexpr noexcept
Definition at line 216 of file Force.hpp.
operator!=() [18/100]
template<typename NumericType > constexpr bool PhQ::operator!= (const Frequency< NumericType > & left, const Frequency< NumericType > & right) inline constexpr noexcept
Definition at line 244 of file Frequency.hpp.
operator!=() [19/100]
template<typename NumericType > constexpr bool PhQ::operator!= (const GasConstant< NumericType > & left, const GasConstant< NumericType > & right) inline constexpr noexcept
Definition at line 182 of file GasConstant.hpp.
operator!=() [20/100]
template<typename NumericType > constexpr bool PhQ::operator!= (const HeatCapacityRatio< NumericType > & left, const HeatCapacityRatio< NumericType > & right) inline constexpr noexcept
Definition at line 201 of file HeatCapacityRatio.hpp.
operator!=() [21/100]
template<typename NumericType > constexpr bool PhQ::operator!= (const HeatFlux< NumericType > & left, const HeatFlux< NumericType > & right) inline constexpr noexcept
Definition at line 229 of file HeatFlux.hpp.
operator!=() [22/100]
template<typename NumericType > constexpr bool PhQ::operator!= (const IsentropicBulkModulus< NumericType > & left, const IsentropicBulkModulus< NumericType > & right) inline constexpr noexcept
Definition at line 164 of file IsentropicBulkModulus.hpp.
operator!=() [23/100]
template<typename NumericType > constexpr bool PhQ::operator!= (const IsobaricHeatCapacity< NumericType > & left, const IsobaricHeatCapacity< NumericType > & right) inline constexpr noexcept
Definition at line 195 of file IsobaricHeatCapacity.hpp.
operator!=() [24/100]
template<typename NumericType > constexpr bool PhQ::operator!= (const IsochoricHeatCapacity< NumericType > & left, const IsochoricHeatCapacity< NumericType > & right) inline constexpr noexcept
Definition at line 183 of file IsochoricHeatCapacity.hpp.
operator!=() [25/100]
template<typename NumericType > constexpr bool PhQ::operator!= (const IsothermalBulkModulus< NumericType > & left, const IsothermalBulkModulus< NumericType > & right) inline constexpr noexcept
Definition at line 151 of file IsothermalBulkModulus.hpp.
operator!=() [26/100]
template<typename NumericType > constexpr bool PhQ::operator!= (const KinematicViscosity< NumericType > & left, const KinematicViscosity< NumericType > & right) inline constexpr noexcept
Definition at line 194 of file KinematicViscosity.hpp.
operator!=() [27/100]
template<typename NumericType > constexpr bool PhQ::operator!= (const LameFirstModulus< NumericType > & left, const LameFirstModulus< NumericType > & right) inline constexpr noexcept
Definition at line 151 of file LameFirstModulus.hpp.
operator!=() [28/100]
template<typename NumericType > constexpr bool PhQ::operator!= (const Length< NumericType > & left, const Length< NumericType > & right) inline constexpr noexcept
Definition at line 270 of file Length.hpp.
operator!=() [29/100]
template<typename NumericType > constexpr bool PhQ::operator!= (const LinearThermalExpansionCoefficient< NumericType > & left, const LinearThermalExpansionCoefficient< NumericType > & right) inline constexpr noexcept
Definition at line 178 of file LinearThermalExpansionCoefficient.hpp.
operator!=() [30/100]
template<typename NumericType > constexpr bool PhQ::operator!= (const MachNumber< NumericType > & left, const MachNumber< NumericType > & right) inline constexpr noexcept
Definition at line 136 of file MachNumber.hpp.
operator!=() [31/100]
template<typename NumericType > constexpr bool PhQ::operator!= (const Mass< NumericType > & left, const Mass< NumericType > & right) inline constexpr noexcept
Definition at line 256 of file Mass.hpp.
operator!=() [32/100]
template<typename NumericType > constexpr bool PhQ::operator!= (const MassDensity< NumericType > & left, const MassDensity< NumericType > & right) inline constexpr noexcept
Definition at line 235 of file MassDensity.hpp.
operator!=() [33/100]
template<typename NumericType > constexpr bool PhQ::operator!= (const MassRate< NumericType > & left, const MassRate< NumericType > & right) inline constexpr noexcept
Definition at line 181 of file MassRate.hpp.
operator!=() [34/100]
template<typename NumericType > constexpr bool PhQ::operator!= (const Memory< NumericType > & left, const Memory< NumericType > & right) inline constexpr noexcept
Definition at line 167 of file Memory.hpp.
operator!=() [35/100]
template<typename NumericType > constexpr bool PhQ::operator!= (const MemoryRate< NumericType > & left, const MemoryRate< NumericType > & right) inline constexpr noexcept
Definition at line 165 of file MemoryRate.hpp.
operator!=() [36/100]
template<typename NumericType > constexpr bool PhQ::operator!= (const PlanarAcceleration< NumericType > & left, const PlanarAcceleration< NumericType > & right) inline constexpr noexcept
Definition at line 234 of file PlanarAcceleration.hpp.
operator!=() [37/100]
template<typename NumericType > constexpr bool PhQ::operator!= (const PlanarDirection< NumericType > & left, const PlanarDirection< NumericType > & right) inline constexpr noexcept
Definition at line 339 of file PlanarDirection.hpp.
operator!=() [38/100]
template<typename NumericType > constexpr bool PhQ::operator!= (const PlanarDisplacement< NumericType > & left, const PlanarDisplacement< NumericType > & right) inline constexpr noexcept
Definition at line 263 of file PlanarDisplacement.hpp.
operator!=() [39/100]
template<typename NumericType > constexpr bool PhQ::operator!= (const PlanarForce< NumericType > & left, const PlanarForce< NumericType > & right) inline constexpr noexcept
Definition at line 213 of file PlanarForce.hpp.
operator!=() [40/100]
template<typename NumericType > constexpr bool PhQ::operator!= (const PlanarHeatFlux< NumericType > & left, const PlanarHeatFlux< NumericType > & right) inline constexpr noexcept
Definition at line 231 of file PlanarHeatFlux.hpp.
operator!=() [41/100]
template<typename NumericType > constexpr bool PhQ::operator!= (const PlanarPosition< NumericType > & left, const PlanarPosition< NumericType > & right) inline constexpr noexcept
Definition at line 236 of file PlanarPosition.hpp.
operator!=() [42/100]
template<typename NumericType > constexpr bool PhQ::operator!= (const PlanarTemperatureGradient< NumericType > & left, const PlanarTemperatureGradient< NumericType > & right) inline constexpr noexcept
Definition at line 229 of file PlanarTemperatureGradient.hpp.
operator!=() [43/100]
template<typename NumericType > constexpr bool PhQ::operator!= (const PlanarTraction< NumericType > & left, const PlanarTraction< NumericType > & right) inline constexpr noexcept
Definition at line 230 of file PlanarTraction.hpp.
operator!=() [44/100]
template<typename NumericType > constexpr bool PhQ::operator!= (const PlanarVector< NumericType > & left, const PlanarVector< NumericType > & right) inline constexpr noexcept
Definition at line 303 of file PlanarVector.hpp.
operator!=() [45/100]
template<typename NumericType > constexpr bool PhQ::operator!= (const PlanarVelocity< NumericType > & left, const PlanarVelocity< NumericType > & right) inline constexpr noexcept
Definition at line 249 of file PlanarVelocity.hpp.
operator!=() [46/100]
template<typename NumericType > constexpr bool PhQ::operator!= (const PoissonRatio< NumericType > & left, const PoissonRatio< NumericType > & right) inline constexpr noexcept
Definition at line 129 of file PoissonRatio.hpp.
operator!=() [47/100]
template<typename NumericType > constexpr bool PhQ::operator!= (const Position< NumericType > & left, const Position< NumericType > & right) inline constexpr noexcept
Definition at line 231 of file Position.hpp.
operator!=() [48/100]
template<typename NumericType > constexpr bool PhQ::operator!= (const Power< NumericType > & left, const Power< NumericType > & right) inline constexpr noexcept
Definition at line 184 of file Power.hpp.
operator!=() [49/100]
template<typename NumericType > constexpr bool PhQ::operator!= (const PrandtlNumber< NumericType > & left, const PrandtlNumber< NumericType > & right) inline constexpr noexcept
Definition at line 182 of file PrandtlNumber.hpp.
operator!=() [50/100]
template<typename NumericType > constexpr bool PhQ::operator!= (const PWaveModulus< NumericType > & left, const PWaveModulus< NumericType > & right) inline constexpr noexcept
Definition at line 145 of file PWaveModulus.hpp.
operator!=() [51/100]
template<typename NumericType > constexpr bool PhQ::operator!= (const ReynoldsNumber< NumericType > & left, const ReynoldsNumber< NumericType > & right) inline constexpr noexcept
Definition at line 192 of file ReynoldsNumber.hpp.
operator!=() [52/100]
template<typename NumericType > constexpr bool PhQ::operator!= (const ScalarAcceleration< NumericType > & left, const ScalarAcceleration< NumericType > & right) inline constexpr noexcept
Definition at line 200 of file ScalarAcceleration.hpp.
operator!=() [53/100]
template<typename NumericType > constexpr bool PhQ::operator!= (const ScalarAngularAcceleration< NumericType > & left, const ScalarAngularAcceleration< NumericType > & right) inline constexpr noexcept
Definition at line 185 of file ScalarAngularAcceleration.hpp.
operator!=() [54/100]
template<typename NumericType > constexpr bool PhQ::operator!= (const ScalarDisplacementGradient< NumericType > & left, const ScalarDisplacementGradient< NumericType > & right) inline constexpr noexcept
Definition at line 172 of file ScalarDisplacementGradient.hpp.
operator!=() [55/100]
template<typename NumericType > constexpr bool PhQ::operator!= (const ScalarForce< NumericType > & left, const ScalarForce< NumericType > & right) inline constexpr noexcept
Definition at line 189 of file ScalarForce.hpp.
operator!=() [56/100]
template<typename NumericType > constexpr bool PhQ::operator!= (const ScalarHeatFlux< NumericType > & left, const ScalarHeatFlux< NumericType > & right) inline constexpr noexcept
Definition at line 176 of file ScalarHeatFlux.hpp.
operator!=() [57/100]
template<typename NumericType > constexpr bool PhQ::operator!= (const ScalarStrain< NumericType > & left, const ScalarStrain< NumericType > & right) inline constexpr noexcept
Definition at line 169 of file ScalarStrain.hpp.
operator!=() [58/100]
template<typename NumericType > constexpr bool PhQ::operator!= (const ScalarStrainRate< NumericType > & left, const ScalarStrainRate< NumericType > & right) inline constexpr noexcept
Definition at line 172 of file ScalarStrainRate.hpp.
operator!=() [59/100]
template<typename NumericType > constexpr bool PhQ::operator!= (const ScalarStress< NumericType > & left, const ScalarStress< NumericType > & right) inline constexpr noexcept
Definition at line 150 of file ScalarStress.hpp.
operator!=() [60/100]
template<typename NumericType > constexpr bool PhQ::operator!= (const ScalarTemperatureGradient< NumericType > & left, const ScalarTemperatureGradient< NumericType > & right) inline constexpr noexcept
Definition at line 200 of file ScalarTemperatureGradient.hpp.
operator!=() [61/100]
template<typename NumericType > constexpr bool PhQ::operator!= (const ScalarThermalConductivity< NumericType > & left, const ScalarThermalConductivity< NumericType > & right) inline constexpr noexcept
Definition at line 198 of file ScalarThermalConductivity.hpp.
operator!=() [62/100]
template<typename NumericType > constexpr bool PhQ::operator!= (const ScalarTraction< NumericType > & left, const ScalarTraction< NumericType > & right) inline constexpr noexcept
Definition at line 184 of file ScalarTraction.hpp.
operator!=() [63/100]
template<typename NumericType > constexpr bool PhQ::operator!= (const ScalarVelocityGradient< NumericType > & left, const ScalarVelocityGradient< NumericType > & right) inline constexpr noexcept
Definition at line 178 of file ScalarVelocityGradient.hpp.
operator!=() [64/100]
template<typename NumericType > constexpr bool PhQ::operator!= (const ShearModulus< NumericType > & left, const ShearModulus< NumericType > & right) inline constexpr noexcept
Definition at line 147 of file ShearModulus.hpp.
operator!=() [65/100]
template<typename NumericType > constexpr bool PhQ::operator!= (const SolidAngle< NumericType > & left, const SolidAngle< NumericType > & right) inline constexpr noexcept
Definition at line 142 of file SolidAngle.hpp.
operator!=() [66/100]
template<typename NumericType > constexpr bool PhQ::operator!= (const SoundSpeed< NumericType > & left, const SoundSpeed< NumericType > & right) inline constexpr noexcept
Definition at line 198 of file SoundSpeed.hpp.
operator!=() [67/100]
template<typename NumericType > constexpr bool PhQ::operator!= (const SpecificEnergy< NumericType > & left, const SpecificEnergy< NumericType > & right) inline constexpr noexcept
Definition at line 178 of file SpecificEnergy.hpp.
operator!=() [68/100]
template<typename NumericType > constexpr bool PhQ::operator!= (const SpecificGasConstant< NumericType > & left, const SpecificGasConstant< NumericType > & right) inline constexpr noexcept
Definition at line 195 of file SpecificGasConstant.hpp.
operator!=() [69/100]
template<typename NumericType > constexpr bool PhQ::operator!= (const SpecificIsobaricHeatCapacity< NumericType > & left, const SpecificIsobaricHeatCapacity< NumericType > & right) inline constexpr noexcept
Definition at line 249 of file SpecificIsobaricHeatCapacity.hpp.
operator!=() [70/100]
template<typename NumericType > constexpr bool PhQ::operator!= (const SpecificIsochoricHeatCapacity< NumericType > & left, const SpecificIsochoricHeatCapacity< NumericType > & right) inline constexpr noexcept
Definition at line 202 of file SpecificIsochoricHeatCapacity.hpp.
operator!=() [71/100]
template<typename NumericType > constexpr bool PhQ::operator!= (const SpecificPower< NumericType > & left, const SpecificPower< NumericType > & right) inline constexpr noexcept
Definition at line 182 of file SpecificPower.hpp.
operator!=() [72/100]
template<typename NumericType > constexpr bool PhQ::operator!= (const Speed< NumericType > & left, const Speed< NumericType > & right) inline constexpr noexcept
Definition at line 290 of file Speed.hpp.
operator!=() [73/100]
template<typename NumericType > constexpr bool PhQ::operator!= (const StaticKinematicPressure< NumericType > & left, const StaticKinematicPressure< NumericType > & right) inline constexpr noexcept
Definition at line 181 of file StaticKinematicPressure.hpp.
operator!=() [74/100]
template<typename NumericType > constexpr bool PhQ::operator!= (const StaticPressure< NumericType > & left, const StaticPressure< NumericType > & right) inline constexpr noexcept
Definition at line 200 of file StaticPressure.hpp.
operator!=() [75/100]
template<typename NumericType > constexpr bool PhQ::operator!= (const Strain< NumericType > & left, const Strain< NumericType > & right) inline constexpr noexcept
Definition at line 229 of file Strain.hpp.
operator!=() [76/100]
template<typename NumericType > constexpr bool PhQ::operator!= (const StrainRate< NumericType > & left, const StrainRate< NumericType > & right) inline constexpr noexcept
Definition at line 244 of file StrainRate.hpp.
operator!=() [77/100]
template<typename NumericType > constexpr bool PhQ::operator!= (const Stress< NumericType > & left, const Stress< NumericType > & right) inline constexpr noexcept
Definition at line 255 of file Stress.hpp.
operator!=() [78/100]
template<typename NumericType > constexpr bool PhQ::operator!= (const SubstanceAmount< NumericType > & left, const SubstanceAmount< NumericType > & right) inline constexpr noexcept
Definition at line 145 of file SubstanceAmount.hpp.
operator!=() [79/100]
template<typename NumericType > constexpr bool PhQ::operator!= (const SymmetricDyad< NumericType > & left, const SymmetricDyad< NumericType > & right) inline constexpr noexcept
Definition at line 448 of file SymmetricDyad.hpp.
operator!=() [80/100]
template<typename NumericType > constexpr bool PhQ::operator!= (const Temperature< NumericType > & left, const Temperature< NumericType > & right) inline constexpr noexcept
Definition at line 166 of file Temperature.hpp.
operator!=() [81/100]
template<typename NumericType > constexpr bool PhQ::operator!= (const TemperatureDifference< NumericType > & left, const TemperatureDifference< NumericType > & right) inline constexpr noexcept
Definition at line 202 of file TemperatureDifference.hpp.
operator!=() [82/100]
template<typename NumericType > constexpr bool PhQ::operator!= (const TemperatureGradient< NumericType > & left, const TemperatureGradient< NumericType > & right) inline constexpr noexcept
Definition at line 227 of file TemperatureGradient.hpp.
operator!=() [83/100]
template<typename NumericType > constexpr bool PhQ::operator!= (const ThermalConductivity< NumericType > & left, const ThermalConductivity< NumericType > & right) inline constexpr noexcept
Definition at line 228 of file ThermalConductivity.hpp.
operator!=() [84/100]
template<typename NumericType > constexpr bool PhQ::operator!= (const ThermalDiffusivity< NumericType > & left, const ThermalDiffusivity< NumericType > & right) inline constexpr noexcept
Definition at line 172 of file ThermalDiffusivity.hpp.
operator!=() [85/100]
template<typename NumericType > constexpr bool PhQ::operator!= (const Time< NumericType > & left, const Time< NumericType > & right) inline constexpr noexcept
Definition at line 362 of file Time.hpp.
operator!=() [86/100]
template<typename NumericType > constexpr bool PhQ::operator!= (const TotalKinematicPressure< NumericType > & left, const TotalKinematicPressure< NumericType > & right) inline constexpr noexcept
Definition at line 177 of file TotalKinematicPressure.hpp.
operator!=() [87/100]
template<typename NumericType > constexpr bool PhQ::operator!= (const TotalPressure< NumericType > & left, const TotalPressure< NumericType > & right) inline constexpr noexcept
Definition at line 176 of file TotalPressure.hpp.
operator!=() [88/100]
template<typename NumericType > constexpr bool PhQ::operator!= (const Traction< NumericType > & left, const Traction< NumericType > & right) inline constexpr noexcept
Definition at line 227 of file Traction.hpp.
operator!=() [89/100]
template<typename NumericType > constexpr bool PhQ::operator!= (const TransportEnergyConsumption< NumericType > & left, const TransportEnergyConsumption< NumericType > & right) inline constexpr noexcept
Definition at line 178 of file TransportEnergyConsumption.hpp.
operator!=() [90/100]
template<typename NumericType > constexpr bool PhQ::operator!= (const typename ConstitutiveModel::CompressibleNewtonianFluid< NumericType > & left, const typename ConstitutiveModel::CompressibleNewtonianFluid< NumericType > & right) inline constexpr noexcept
Definition at line 351 of file CompressibleNewtonianFluid.hpp.
operator!=() [91/100]
template<typename NumericType > constexpr bool PhQ::operator!= (const typename ConstitutiveModel::ElasticIsotropicSolid< NumericType > & left, const typename ConstitutiveModel::ElasticIsotropicSolid< NumericType > & right) inline constexpr noexcept
Definition at line 594 of file ElasticIsotropicSolid.hpp.
operator!=() [92/100]
template<typename NumericType > constexpr bool PhQ::operator!= (const typename ConstitutiveModel::IncompressibleNewtonianFluid< NumericType > & left, const typename ConstitutiveModel::IncompressibleNewtonianFluid< NumericType > & right) inline constexpr noexcept
Definition at line 262 of file IncompressibleNewtonianFluid.hpp.
operator!=() [93/100]
template<typename NumericType > constexpr bool PhQ::operator!= (const Vector< NumericType > & left, const Vector< NumericType > & right) inline constexpr noexcept
Definition at line 325 of file Vector.hpp.
operator!=() [94/100]
template<typename NumericType > constexpr bool PhQ::operator!= (const VectorArea< NumericType > & left, const VectorArea< NumericType > & right) inline constexpr noexcept
Definition at line 199 of file VectorArea.hpp.
operator!=() [95/100]
template<typename NumericType > constexpr bool PhQ::operator!= (const Velocity< NumericType > & left, const Velocity< NumericType > & right) inline constexpr noexcept
Definition at line 244 of file Velocity.hpp.
operator!=() [96/100]
template<typename NumericType > constexpr bool PhQ::operator!= (const VelocityGradient< NumericType > & left, const VelocityGradient< NumericType > & right) inline constexpr noexcept
Definition at line 257 of file VelocityGradient.hpp.
operator!=() [97/100]
template<typename NumericType > constexpr bool PhQ::operator!= (const Volume< NumericType > & left, const Volume< NumericType > & right) inline constexpr noexcept
Definition at line 193 of file Volume.hpp.
operator!=() [98/100]
template<typename NumericType > constexpr bool PhQ::operator!= (const VolumeRate< NumericType > & left, const VolumeRate< NumericType > & right) inline constexpr noexcept
Definition at line 180 of file VolumeRate.hpp.
operator!=() [99/100]
template<typename NumericType > constexpr bool PhQ::operator!= (const VolumetricThermalExpansionCoefficient< NumericType > & left, const VolumetricThermalExpansionCoefficient< NumericType > & right) inline constexpr noexcept
Definition at line 178 of file VolumetricThermalExpansionCoefficient.hpp.
operator!=() [100/100]
template<typename NumericType > constexpr bool PhQ::operator!= (const YoungModulus< NumericType > & left, const YoungModulus< NumericType > & right) inline constexpr noexcept
Definition at line 145 of file YoungModulus.hpp.
operator*() [1/110]
template<typename NumericType > constexpr Vector< NumericType > PhQ::operator* (const Dyad< NumericType > & dyad, const Direction< NumericType > & direction) inline constexpr
Definition at line 406 of file Direction.hpp.
References PhQ::DimensionlessVector< NumericType >::Value().
operator*() [2/110]
template<typename NumericType , typename OtherNumericType > constexpr Dyad< NumericType > PhQ::operator* (const Dyad< NumericType > & dyad, const OtherNumericType number) inline constexpr
Definition at line 584 of file Dyad.hpp.
References PhQ::Dyad< NumericType >::xx(), PhQ::Dyad< NumericType >::xy(), PhQ::Dyad< NumericType >::xz(), PhQ::Dyad< NumericType >::yx(), PhQ::Dyad< NumericType >::yy(), PhQ::Dyad< NumericType >::yz(), PhQ::Dyad< NumericType >::zx(), PhQ::Dyad< NumericType >::zy(), and PhQ::Dyad< NumericType >::zz().
operator*() [3/110]
template<typename NumericType > constexpr Vector< NumericType > PhQ::operator* (const Dyad< NumericType > & dyad, const PlanarDirection< NumericType > & planar_direction) inline constexpr
Definition at line 411 of file PlanarDirection.hpp.
References PhQ::DimensionlessPlanarVector< NumericType >::Value().
operator*() [4/110]
template<typename NumericType > constexpr Vector< NumericType > PhQ::operator* (const Dyad< NumericType > & dyad, const PlanarVector< NumericType > & planar_vector) inline constexpr
Definition at line 601 of file Dyad.hpp.
References PhQ::PlanarVector< NumericType >::x(), PhQ::Dyad< NumericType >::xx(), PhQ::Dyad< NumericType >::xy(), PhQ::PlanarVector< NumericType >::y(), PhQ::Dyad< NumericType >::yx(), PhQ::Dyad< NumericType >::yy(), PhQ::Dyad< NumericType >::zx(), and PhQ::Dyad< NumericType >::zy().
operator*() [5/110]
template<typename NumericType > constexpr Dyad< NumericType > PhQ::operator* (const Dyad< NumericType > & dyad, const SymmetricDyad< NumericType > & symmetric_dyad) inline constexpr
Definition at line 657 of file Dyad.hpp.
References PhQ::Dyad< NumericType >::xx(), PhQ::SymmetricDyad< NumericType >::xx(), PhQ::Dyad< NumericType >::xy(), PhQ::SymmetricDyad< NumericType >::xy(), PhQ::Dyad< NumericType >::xz(), PhQ::SymmetricDyad< NumericType >::xz(), PhQ::Dyad< NumericType >::yx(), PhQ::SymmetricDyad< NumericType >::yx(), PhQ::Dyad< NumericType >::yy(), PhQ::SymmetricDyad< NumericType >::yy(), PhQ::Dyad< NumericType >::yz(), PhQ::SymmetricDyad< NumericType >::yz(), PhQ::Dyad< NumericType >::zx(), PhQ::SymmetricDyad< NumericType >::zx(), PhQ::Dyad< NumericType >::zy(), PhQ::SymmetricDyad< NumericType >::zy(), PhQ::Dyad< NumericType >::zz(), and PhQ::SymmetricDyad< NumericType >::zz().
operator*() [6/110]
template<typename NumericType > constexpr Vector< NumericType > PhQ::operator* (const Dyad< NumericType > & dyad, const Vector< NumericType > & vector) inline constexpr
Definition at line 609 of file Dyad.hpp.
References PhQ::Vector< NumericType >::x(), PhQ::Dyad< NumericType >::xx(), PhQ::Dyad< NumericType >::xy(), PhQ::Dyad< NumericType >::xz(), PhQ::Vector< NumericType >::y(), PhQ::Dyad< NumericType >::yx(), PhQ::Dyad< NumericType >::yy(), PhQ::Dyad< NumericType >::yz(), PhQ::Vector< NumericType >::z(), PhQ::Dyad< NumericType >::zx(), PhQ::Dyad< NumericType >::zy(), and PhQ::Dyad< NumericType >::zz().
operator*() [7/110]
template<typename NumericType > constexpr Dyad< NumericType > PhQ::operator* (const Dyad< NumericType > & left, const Dyad< NumericType > & right) inline constexpr
Definition at line 681 of file Dyad.hpp.
References PhQ::Dyad< NumericType >::xx(), PhQ::Dyad< NumericType >::xy(), PhQ::Dyad< NumericType >::xz(), PhQ::Dyad< NumericType >::yx(), PhQ::Dyad< NumericType >::yy(), PhQ::Dyad< NumericType >::yz(), PhQ::Dyad< NumericType >::zx(), PhQ::Dyad< NumericType >::zy(), and PhQ::Dyad< NumericType >::zz().
operator*() [8/110]
template<typename NumericType > constexpr Acceleration< NumericType > PhQ::operator* (const NumericType number, const Acceleration< NumericType > & acceleration) inline constexpr
Definition at line 272 of file Acceleration.hpp.
operator*() [9/110]
template<typename NumericType > constexpr Angle< NumericType > PhQ::operator* (const NumericType number, const Angle< NumericType > & angle) inline constexpr
Definition at line 388 of file Angle.hpp.
operator*() [10/110]
template<typename NumericType > constexpr AngularSpeed< NumericType > PhQ::operator* (const NumericType number, const AngularSpeed< NumericType > & angular_speed) inline constexpr
Definition at line 229 of file AngularSpeed.hpp.
operator*() [11/110]
template<typename NumericType > constexpr Area< NumericType > PhQ::operator* (const NumericType number, const Area< NumericType > & area) inline constexpr
Definition at line 237 of file Area.hpp.
operator*() [12/110]
template<typename NumericType > constexpr BulkDynamicViscosity< NumericType > PhQ::operator* (const NumericType number, const BulkDynamicViscosity< NumericType > & mass_density) inline constexpr
Definition at line 187 of file BulkDynamicViscosity.hpp.
operator*() [13/110]
template<typename NumericType > constexpr Displacement< NumericType > PhQ::operator* (const NumericType number, const Displacement< NumericType > & displacement) inline constexpr
Definition at line 288 of file Displacement.hpp.
operator*() [14/110]
template<typename NumericType > constexpr DisplacementGradient< NumericType > PhQ::operator* (const NumericType number, const DisplacementGradient< NumericType > & displacement_gradient) inline constexpr
Definition at line 258 of file DisplacementGradient.hpp.
operator*() [15/110]
template<typename NumericType > constexpr DynamicKinematicPressure< NumericType > PhQ::operator* (const NumericType number, const DynamicKinematicPressure< NumericType > & dynamic_kinematic_pressure) inline constexpr
Definition at line 217 of file DynamicKinematicPressure.hpp.
operator*() [16/110]
template<typename NumericType > constexpr DynamicPressure< NumericType > PhQ::operator* (const NumericType number, const DynamicPressure< NumericType > & dynamic_pressure) inline constexpr
Definition at line 214 of file DynamicPressure.hpp.
operator*() [17/110]
template<typename NumericType > constexpr DynamicViscosity< NumericType > PhQ::operator* (const NumericType number, const DynamicViscosity< NumericType > & dynamic_viscosity) inline constexpr
Definition at line 229 of file DynamicViscosity.hpp.
operator*() [18/110]
template<typename NumericType > constexpr ElectricCharge< NumericType > PhQ::operator* (const NumericType number, const ElectricCharge< NumericType > & electric_charge) inline constexpr
Definition at line 209 of file ElectricCharge.hpp.
operator*() [19/110]
template<typename NumericType > constexpr ElectricCurrent< NumericType > PhQ::operator* (const NumericType number, const ElectricCurrent< NumericType > & electric_current) inline constexpr
Definition at line 211 of file ElectricCurrent.hpp.
operator*() [20/110]
template<typename NumericType > constexpr Energy< NumericType > PhQ::operator* (const NumericType number, const Energy< NumericType > & energy) inline constexpr
Definition at line 243 of file Energy.hpp.
operator*() [21/110]
template<typename NumericType > constexpr Force< NumericType > PhQ::operator* (const NumericType number, const Force< NumericType > & force) inline constexpr
Definition at line 252 of file Force.hpp.
operator*() [22/110]
template<typename NumericType > constexpr Frequency< NumericType > PhQ::operator* (const NumericType number, const Frequency< NumericType > & frequency) inline constexpr
Definition at line 280 of file Frequency.hpp.
operator*() [23/110]
template<typename NumericType > constexpr GasConstant< NumericType > PhQ::operator* (const NumericType number, const GasConstant< NumericType > & gas_constant) inline constexpr
Definition at line 219 of file GasConstant.hpp.
operator*() [24/110]
template<typename NumericType > constexpr HeatCapacityRatio< NumericType > PhQ::operator* (const NumericType number, const HeatCapacityRatio< NumericType > & heat_capacity_ratio) inline constexpr
Definition at line 238 of file HeatCapacityRatio.hpp.
References PhQ::DimensionlessScalar< NumericType >::Value().
operator*() [25/110]
template<typename NumericType > constexpr HeatFlux< NumericType > PhQ::operator* (const NumericType number, const HeatFlux< NumericType > & heat_flux) inline constexpr
Definition at line 265 of file HeatFlux.hpp.
operator*() [26/110]
template<typename NumericType > constexpr IsentropicBulkModulus< NumericType > PhQ::operator* (const NumericType number, const IsentropicBulkModulus< NumericType > & isentropic_bulk_modulus) inline constexpr
Definition at line 201 of file IsentropicBulkModulus.hpp.
operator*() [27/110]
template<typename NumericType > constexpr IsobaricHeatCapacity< NumericType > PhQ::operator* (const NumericType number, const IsobaricHeatCapacity< NumericType > & isobaric_heat_capacity) inline constexpr
Definition at line 232 of file IsobaricHeatCapacity.hpp.
operator*() [28/110]
template<typename NumericType > constexpr IsochoricHeatCapacity< NumericType > PhQ::operator* (const NumericType number, const IsochoricHeatCapacity< NumericType > & isochoric_heat_capacity) inline constexpr
Definition at line 220 of file IsochoricHeatCapacity.hpp.
operator*() [29/110]
template<typename NumericType > constexpr IsothermalBulkModulus< NumericType > PhQ::operator* (const NumericType number, const IsothermalBulkModulus< NumericType > & isothermal_bulk_modulus) inline constexpr
Definition at line 188 of file IsothermalBulkModulus.hpp.
operator*() [30/110]
template<typename NumericType > constexpr KinematicViscosity< NumericType > PhQ::operator* (const NumericType number, const KinematicViscosity< NumericType > & kinematic_viscosity) inline constexpr
Definition at line 231 of file KinematicViscosity.hpp.
operator*() [31/110]
template<typename NumericType > constexpr LameFirstModulus< NumericType > PhQ::operator* (const NumericType number, const LameFirstModulus< NumericType > & lame_first_modulus) inline constexpr
Definition at line 188 of file LameFirstModulus.hpp.
operator*() [32/110]
template<typename NumericType > constexpr Length< NumericType > PhQ::operator* (const NumericType number, const Length< NumericType > & length) inline constexpr
Definition at line 306 of file Length.hpp.
operator*() [33/110]
template<typename NumericType > constexpr LinearThermalExpansionCoefficient< NumericType > PhQ::operator* (const NumericType number, const LinearThermalExpansionCoefficient< NumericType > & linear_thermal_expansion_coefficient) inline constexpr
Definition at line 221 of file LinearThermalExpansionCoefficient.hpp.
operator*() [34/110]
template<typename NumericType > constexpr MachNumber< NumericType > PhQ::operator* (const NumericType number, const MachNumber< NumericType > & mach_number) inline constexpr
Definition at line 172 of file MachNumber.hpp.
References PhQ::DimensionlessScalar< NumericType >::Value().
operator*() [35/110]
template<typename NumericType > constexpr Mass< NumericType > PhQ::operator* (const NumericType number, const Mass< NumericType > & mass) inline constexpr
Definition at line 292 of file Mass.hpp.
operator*() [36/110]
template<typename NumericType > constexpr MassDensity< NumericType > PhQ::operator* (const NumericType number, const MassDensity< NumericType > & mass_density) inline constexpr
Definition at line 272 of file MassDensity.hpp.
operator*() [37/110]
template<typename NumericType > constexpr MassRate< NumericType > PhQ::operator* (const NumericType number, const MassRate< NumericType > & mass_rate) inline constexpr
Definition at line 217 of file MassRate.hpp.
operator*() [38/110]
template<typename NumericType > constexpr Memory< NumericType > PhQ::operator* (const NumericType number, const Memory< NumericType > & memory) inline constexpr
Definition at line 203 of file Memory.hpp.
operator*() [39/110]
template<typename NumericType > constexpr MemoryRate< NumericType > PhQ::operator* (const NumericType number, const MemoryRate< NumericType > & memory_rate) inline constexpr
Definition at line 201 of file MemoryRate.hpp.
operator*() [40/110]
template<typename NumericType > constexpr PlanarAcceleration< NumericType > PhQ::operator* (const NumericType number, const PlanarAcceleration< NumericType > & planar_acceleration) inline constexpr
Definition at line 271 of file PlanarAcceleration.hpp.
operator*() [41/110]
template<typename NumericType > constexpr PlanarDisplacement< NumericType > PhQ::operator* (const NumericType number, const PlanarDisplacement< NumericType > & planar_displacement) inline constexpr
Definition at line 300 of file PlanarDisplacement.hpp.
operator*() [42/110]
template<typename NumericType > constexpr PlanarForce< NumericType > PhQ::operator* (const NumericType number, const PlanarForce< NumericType > & planar_force) inline constexpr
Definition at line 250 of file PlanarForce.hpp.
operator*() [43/110]
template<typename NumericType > constexpr PlanarHeatFlux< NumericType > PhQ::operator* (const NumericType number, const PlanarHeatFlux< NumericType > & planar_heat_flux) inline constexpr
Definition at line 268 of file PlanarHeatFlux.hpp.
operator*() [44/110]
template<typename NumericType > constexpr PlanarPosition< NumericType > PhQ::operator* (const NumericType number, const PlanarPosition< NumericType > & planar_position) inline constexpr
Definition at line 273 of file PlanarPosition.hpp.
operator*() [45/110]
template<typename NumericType > constexpr PlanarTemperatureGradient< NumericType > PhQ::operator* (const NumericType number, const PlanarTemperatureGradient< NumericType > & planar_temperature_gradient) inline constexpr
Definition at line 267 of file PlanarTemperatureGradient.hpp.
operator*() [46/110]
template<typename NumericType > constexpr PlanarTraction< NumericType > PhQ::operator* (const NumericType number, const PlanarTraction< NumericType > & planar_traction) inline constexpr
Definition at line 267 of file PlanarTraction.hpp.
operator*() [47/110]
template<typename NumericType > constexpr PlanarVelocity< NumericType > PhQ::operator* (const NumericType number, const PlanarVelocity< NumericType > & planar_velocity) inline constexpr
Definition at line 286 of file PlanarVelocity.hpp.
operator*() [48/110]
template<typename NumericType > constexpr PoissonRatio< NumericType > PhQ::operator* (const NumericType number, const PoissonRatio< NumericType > & poisson_ratio) inline constexpr
Definition at line 166 of file PoissonRatio.hpp.
References PhQ::DimensionlessScalar< NumericType >::Value().
operator*() [49/110]
template<typename NumericType > constexpr Position< NumericType > PhQ::operator* (const NumericType number, const Position< NumericType > & position) inline constexpr
Definition at line 267 of file Position.hpp.
operator*() [50/110]
template<typename NumericType > constexpr Power< NumericType > PhQ::operator* (const NumericType number, const Power< NumericType > & power) inline constexpr
Definition at line 220 of file Power.hpp.
operator*() [51/110]
template<typename NumericType > constexpr PrandtlNumber< NumericType > PhQ::operator* (const NumericType number, const PrandtlNumber< NumericType > & prandtl_number) inline constexpr
Definition at line 219 of file PrandtlNumber.hpp.
References PhQ::DimensionlessScalar< NumericType >::Value().
operator*() [52/110]
template<typename NumericType > constexpr PWaveModulus< NumericType > PhQ::operator* (const NumericType number, const PWaveModulus< NumericType > & p_wave_modulus) inline constexpr
Definition at line 182 of file PWaveModulus.hpp.
operator*() [53/110]
template<typename NumericType > constexpr ReynoldsNumber< NumericType > PhQ::operator* (const NumericType number, const ReynoldsNumber< NumericType > & reynolds_number) inline constexpr
Definition at line 229 of file ReynoldsNumber.hpp.
References PhQ::DimensionlessScalar< NumericType >::Value().
operator*() [54/110]
template<typename NumericType > constexpr ScalarAcceleration< NumericType > PhQ::operator* (const NumericType number, const ScalarAcceleration< NumericType > & scalar_acceleration) inline constexpr
Definition at line 237 of file ScalarAcceleration.hpp.
operator*() [55/110]
template<typename NumericType > constexpr ScalarAngularAcceleration< NumericType > PhQ::operator* (const NumericType number, const ScalarAngularAcceleration< NumericType > & scalar_angular_acceleration) inline constexpr
Definition at line 223 of file ScalarAngularAcceleration.hpp.
operator*() [56/110]
template<typename NumericType > constexpr ScalarDisplacementGradient< NumericType > PhQ::operator* (const NumericType number, const ScalarDisplacementGradient< NumericType > & scalar_displacement_gradient) inline constexpr
Definition at line 210 of file ScalarDisplacementGradient.hpp.
References PhQ::DimensionlessScalar< NumericType >::Value().
operator*() [57/110]
template<typename NumericType > constexpr ScalarForce< NumericType > PhQ::operator* (const NumericType number, const ScalarForce< NumericType > & scalar_force) inline constexpr
Definition at line 226 of file ScalarForce.hpp.
operator*() [58/110]
template<typename NumericType > constexpr ScalarHeatFlux< NumericType > PhQ::operator* (const NumericType number, const ScalarHeatFlux< NumericType > & scalar_heat_flux) inline constexpr
Definition at line 213 of file ScalarHeatFlux.hpp.
operator*() [59/110]
template<typename NumericType > constexpr ScalarStrain< NumericType > PhQ::operator* (const NumericType number, const ScalarStrain< NumericType > & scalar_strain) inline constexpr
Definition at line 206 of file ScalarStrain.hpp.
References PhQ::DimensionlessScalar< NumericType >::Value().
operator*() [60/110]
template<typename NumericType > constexpr ScalarStrainRate< NumericType > PhQ::operator* (const NumericType number, const ScalarStrainRate< NumericType > & scalar_strain_rate) inline constexpr
Definition at line 209 of file ScalarStrainRate.hpp.
operator*() [61/110]
template<typename NumericType > constexpr ScalarStress< NumericType > PhQ::operator* (const NumericType number, const ScalarStress< NumericType > & scalar_stress) inline constexpr
Definition at line 187 of file ScalarStress.hpp.
operator*() [62/110]
template<typename NumericType > constexpr ScalarTemperatureGradient< NumericType > PhQ::operator* (const NumericType number, const ScalarTemperatureGradient< NumericType > & scalar_temperature_gradient) inline constexpr
Definition at line 238 of file ScalarTemperatureGradient.hpp.
operator*() [63/110]
template<typename NumericType > constexpr ScalarThermalConductivity< NumericType > PhQ::operator* (const NumericType number, const ScalarThermalConductivity< NumericType > & thermal_conductivity_scalar) inline constexpr
Definition at line 236 of file ScalarThermalConductivity.hpp.
operator*() [64/110]
template<typename NumericType > constexpr ScalarTraction< NumericType > PhQ::operator* (const NumericType number, const ScalarTraction< NumericType > & static_pressure) inline constexpr
Definition at line 221 of file ScalarTraction.hpp.
operator*() [65/110]
template<typename NumericType > constexpr ScalarVelocityGradient< NumericType > PhQ::operator* (const NumericType number, const ScalarVelocityGradient< NumericType > & scalar_velocity_gradient) inline constexpr
Definition at line 215 of file ScalarVelocityGradient.hpp.
operator*() [66/110]
template<typename NumericType > constexpr ShearModulus< NumericType > PhQ::operator* (const NumericType number, const ShearModulus< NumericType > & shear_modulus) inline constexpr
Definition at line 184 of file ShearModulus.hpp.
operator*() [67/110]
template<typename NumericType > constexpr SolidAngle< NumericType > PhQ::operator* (const NumericType number, const SolidAngle< NumericType > & solid_angle) inline constexpr
Definition at line 178 of file SolidAngle.hpp.
operator*() [68/110]
template<typename NumericType > constexpr SoundSpeed< NumericType > PhQ::operator* (const NumericType number, const SoundSpeed< NumericType > & sound_speed) inline constexpr
Definition at line 234 of file SoundSpeed.hpp.
operator*() [69/110]
template<typename NumericType > constexpr SpecificEnergy< NumericType > PhQ::operator* (const NumericType number, const SpecificEnergy< NumericType > & specific_energy) inline constexpr
Definition at line 215 of file SpecificEnergy.hpp.
operator*() [70/110]
template<typename NumericType > constexpr SpecificGasConstant< NumericType > PhQ::operator* (const NumericType number, const SpecificGasConstant< NumericType > & specific_gas_constant) inline constexpr
Definition at line 232 of file SpecificGasConstant.hpp.
operator*() [71/110]
template<typename NumericType > constexpr SpecificIsobaricHeatCapacity< NumericType > PhQ::operator* (const NumericType number, const SpecificIsobaricHeatCapacity< NumericType > & specific_isobaric_heat_capacity) inline constexpr
Definition at line 287 of file SpecificIsobaricHeatCapacity.hpp.
operator*() [72/110]
template<typename NumericType > constexpr SpecificIsochoricHeatCapacity< NumericType > PhQ::operator* (const NumericType number, const SpecificIsochoricHeatCapacity< NumericType > & specific_isochoric_heat_capacity) inline constexpr
Definition at line 240 of file SpecificIsochoricHeatCapacity.hpp.
operator*() [73/110]
template<typename NumericType > constexpr SpecificPower< NumericType > PhQ::operator* (const NumericType number, const SpecificPower< NumericType > & specific_power) inline constexpr
Definition at line 219 of file SpecificPower.hpp.
operator*() [74/110]
template<typename NumericType > constexpr Speed< NumericType > PhQ::operator* (const NumericType number, const Speed< NumericType > & speed) inline constexpr
Definition at line 326 of file Speed.hpp.
operator*() [75/110]
template<typename NumericType > constexpr StaticKinematicPressure< NumericType > PhQ::operator* (const NumericType number, const StaticKinematicPressure< NumericType > & static_kinematic_pressure) inline constexpr
Definition at line 218 of file StaticKinematicPressure.hpp.
operator*() [76/110]
template<typename NumericType > constexpr StaticPressure< NumericType > PhQ::operator* (const NumericType number, const StaticPressure< NumericType > & static_pressure) inline constexpr
Definition at line 237 of file StaticPressure.hpp.
operator*() [77/110]
template<typename NumericType > constexpr Strain< NumericType > PhQ::operator* (const NumericType number, const Strain< NumericType > & strain) inline constexpr
Definition at line 265 of file Strain.hpp.
operator*() [78/110]
template<typename NumericType > constexpr StrainRate< NumericType > PhQ::operator* (const NumericType number, const StrainRate< NumericType > & strain_rate) inline constexpr
Definition at line 280 of file StrainRate.hpp.
operator*() [79/110]
template<typename NumericType > constexpr Stress< NumericType > PhQ::operator* (const NumericType number, const Stress< NumericType > & stress) inline constexpr
Definition at line 291 of file Stress.hpp.
operator*() [80/110]
template<typename NumericType > constexpr SubstanceAmount< NumericType > PhQ::operator* (const NumericType number, const SubstanceAmount< NumericType > & substance_amount) inline constexpr
Definition at line 182 of file SubstanceAmount.hpp.
operator*() [81/110]
template<typename NumericType > constexpr Temperature< NumericType > PhQ::operator* (const NumericType number, const Temperature< NumericType > & temperature) inline constexpr
Definition at line 202 of file Temperature.hpp.
operator*() [82/110]
template<typename NumericType > constexpr TemperatureDifference< NumericType > PhQ::operator* (const NumericType number, const TemperatureDifference< NumericType > & temperature_difference) inline constexpr
Definition at line 239 of file TemperatureDifference.hpp.
operator*() [83/110]
template<typename NumericType > constexpr TemperatureGradient< NumericType > PhQ::operator* (const NumericType number, const TemperatureGradient< NumericType > & temperature_gradient) inline constexpr
Definition at line 264 of file TemperatureGradient.hpp.
operator*() [84/110]
template<typename NumericType > constexpr ThermalConductivity< NumericType > PhQ::operator* (const NumericType number, const ThermalConductivity< NumericType > & thermal_conductivity) inline constexpr
Definition at line 265 of file ThermalConductivity.hpp.
operator*() [85/110]
template<typename NumericType > constexpr ThermalDiffusivity< NumericType > PhQ::operator* (const NumericType number, const ThermalDiffusivity< NumericType > & thermal_diffusivity) inline constexpr
Definition at line 209 of file ThermalDiffusivity.hpp.
operator*() [86/110]
template<typename NumericType > constexpr Time< NumericType > PhQ::operator* (const NumericType number, const Time< NumericType > & time) inline constexpr
Definition at line 398 of file Time.hpp.
operator*() [87/110]
template<typename NumericType > constexpr TotalKinematicPressure< NumericType > PhQ::operator* (const NumericType number, const TotalKinematicPressure< NumericType > & total_kinematic_pressure) inline constexpr
Definition at line 214 of file TotalKinematicPressure.hpp.
operator*() [88/110]
template<typename NumericType > constexpr TotalPressure< NumericType > PhQ::operator* (const NumericType number, const TotalPressure< NumericType > & total_pressure) inline constexpr
Definition at line 213 of file TotalPressure.hpp.
operator*() [89/110]
template<typename NumericType > constexpr Traction< NumericType > PhQ::operator* (const NumericType number, const Traction< NumericType > & traction) inline constexpr
Definition at line 263 of file Traction.hpp.
operator*() [90/110]
template<typename NumericType > constexpr TransportEnergyConsumption< NumericType > PhQ::operator* (const NumericType number, const TransportEnergyConsumption< NumericType > & transport_energy_consumption) inline constexpr
Definition at line 216 of file TransportEnergyConsumption.hpp.
operator*() [91/110]
template<typename NumericType > constexpr VectorArea< NumericType > PhQ::operator* (const NumericType number, const VectorArea< NumericType > & vector_area) inline constexpr
Definition at line 235 of file VectorArea.hpp.
operator*() [92/110]
template<typename NumericType > constexpr Velocity< NumericType > PhQ::operator* (const NumericType number, const Velocity< NumericType > & velocity) inline constexpr
Definition at line 280 of file Velocity.hpp.
operator*() [93/110]
template<typename NumericType > constexpr VelocityGradient< NumericType > PhQ::operator* (const NumericType number, const VelocityGradient< NumericType > & velocity_gradient) inline constexpr
Definition at line 294 of file VelocityGradient.hpp.
operator*() [94/110]
template<typename NumericType > constexpr Volume< NumericType > PhQ::operator* (const NumericType number, const Volume< NumericType > & volume) inline constexpr
Definition at line 229 of file Volume.hpp.
operator*() [95/110]
template<typename NumericType > constexpr VolumeRate< NumericType > PhQ::operator* (const NumericType number, const VolumeRate< NumericType > & volume_rate) inline constexpr
Definition at line 216 of file VolumeRate.hpp.
operator*() [96/110]
template<typename NumericType > constexpr VolumetricThermalExpansionCoefficient< NumericType > PhQ::operator* (const NumericType number, const VolumetricThermalExpansionCoefficient< NumericType > & volumetric_thermal_expansion_coefficient) inline constexpr
Definition at line 221 of file VolumetricThermalExpansionCoefficient.hpp.
operator*() [97/110]
template<typename NumericType > constexpr YoungModulus< NumericType > PhQ::operator* (const NumericType number, const YoungModulus< NumericType > & young_modulus) inline constexpr
Definition at line 182 of file YoungModulus.hpp.
operator*() [98/110]
template<typename NumericType , typename OtherNumericType > constexpr Dyad< NumericType > PhQ::operator* (const OtherNumericType number, const Dyad< NumericType > & dyad) inline constexpr
Definition at line 595 of file Dyad.hpp.
operator*() [99/110]
template<typename NumericType , typename OtherNumericType > constexpr PlanarVector< NumericType > PhQ::operator* (const OtherNumericType number, const PlanarVector< NumericType > & planar_vector) inline constexpr
Definition at line 358 of file PlanarVector.hpp.
operator*() [100/110]
template<typename NumericType , typename OtherNumericType > constexpr SymmetricDyad< NumericType > PhQ::operator* (const OtherNumericType number, const SymmetricDyad< NumericType > & symmetric_dyad) inline constexpr
Definition at line 537 of file SymmetricDyad.hpp.
operator*() [101/110]
template<typename NumericType , typename OtherNumericType > constexpr Vector< NumericType > PhQ::operator* (const OtherNumericType number, const Vector< NumericType > & vector) inline constexpr
Definition at line 387 of file Vector.hpp.
operator*() [102/110]
template<typename NumericType , typename OtherNumericType > constexpr PlanarVector< NumericType > PhQ::operator* (const PlanarVector< NumericType > & planar_vector, const OtherNumericType number) inline constexpr
Definition at line 351 of file PlanarVector.hpp.
References PhQ::PlanarVector< NumericType >::x(), and PhQ::PlanarVector< NumericType >::y().
operator*() [103/110]
template<typename NumericType > constexpr Dyad< NumericType > PhQ::operator* (const SymmetricDyad< NumericType > & left, const SymmetricDyad< NumericType > & right) inline constexpr
Definition at line 618 of file Dyad.hpp.
References PhQ::SymmetricDyad< NumericType >::xx(), PhQ::SymmetricDyad< NumericType >::xy(), PhQ::SymmetricDyad< NumericType >::xz(), PhQ::SymmetricDyad< NumericType >::yy(), PhQ::SymmetricDyad< NumericType >::yz(), and PhQ::SymmetricDyad< NumericType >::zz().
operator*() [104/110]
template<typename NumericType > constexpr Vector< NumericType > PhQ::operator* (const SymmetricDyad< NumericType > & symmetric_dyad, const Direction< NumericType > & direction) inline constexpr
Definition at line 400 of file Direction.hpp.
References PhQ::DimensionlessVector< NumericType >::Value().
operator*() [105/110]
template<typename NumericType > constexpr Dyad< NumericType > PhQ::operator* (const SymmetricDyad< NumericType > & symmetric_dyad, const Dyad< NumericType > & dyad) inline constexpr
Definition at line 633 of file Dyad.hpp.
References PhQ::Dyad< NumericType >::xx(), PhQ::SymmetricDyad< NumericType >::xx(), PhQ::Dyad< NumericType >::xy(), PhQ::SymmetricDyad< NumericType >::xy(), PhQ::Dyad< NumericType >::xz(), PhQ::SymmetricDyad< NumericType >::xz(), PhQ::Dyad< NumericType >::yx(), PhQ::Dyad< NumericType >::yy(), PhQ::SymmetricDyad< NumericType >::yy(), PhQ::Dyad< NumericType >::yz(), PhQ::SymmetricDyad< NumericType >::yz(), PhQ::Dyad< NumericType >::zx(), PhQ::Dyad< NumericType >::zy(), PhQ::Dyad< NumericType >::zz(), and PhQ::SymmetricDyad< NumericType >::zz().
operator*() [106/110]
template<typename NumericType , typename OtherNumericType > constexpr SymmetricDyad< NumericType > PhQ::operator* (const SymmetricDyad< NumericType > & symmetric_dyad, const OtherNumericType number) inline constexpr
Definition at line 525 of file SymmetricDyad.hpp.
References PhQ::SymmetricDyad< NumericType >::xx(), PhQ::SymmetricDyad< NumericType >::xy(), PhQ::SymmetricDyad< NumericType >::xz(), PhQ::SymmetricDyad< NumericType >::yy(), PhQ::SymmetricDyad< NumericType >::yz(), and PhQ::SymmetricDyad< NumericType >::zz().
operator*() [107/110]
template<typename NumericType > constexpr Vector< NumericType > PhQ::operator* (const SymmetricDyad< NumericType > & symmetric_dyad, const PlanarDirection< NumericType > & planar_direction) inline constexpr
Definition at line 404 of file PlanarDirection.hpp.
References PhQ::DimensionlessPlanarVector< NumericType >::Value().
operator*() [108/110]
template<typename NumericType > constexpr Vector< NumericType > PhQ::operator* (const SymmetricDyad< NumericType > & symmetric_dyad, const PlanarVector< NumericType > & planar_vector) inline constexpr
Definition at line 543 of file SymmetricDyad.hpp.
References PhQ::PlanarVector< NumericType >::x(), PhQ::SymmetricDyad< NumericType >::xx(), PhQ::SymmetricDyad< NumericType >::xy(), PhQ::SymmetricDyad< NumericType >::xz(), PhQ::PlanarVector< NumericType >::y(), PhQ::SymmetricDyad< NumericType >::yy(), and PhQ::SymmetricDyad< NumericType >::yz().
operator*() [109/110]
template<typename NumericType > constexpr Vector< NumericType > PhQ::operator* (const SymmetricDyad< NumericType > & symmetric_dyad, const Vector< NumericType > & vector) inline constexpr
Definition at line 552 of file SymmetricDyad.hpp.
References PhQ::Vector< NumericType >::x(), PhQ::SymmetricDyad< NumericType >::xx(), PhQ::SymmetricDyad< NumericType >::xy(), PhQ::SymmetricDyad< NumericType >::xz(), PhQ::Vector< NumericType >::y(), PhQ::SymmetricDyad< NumericType >::yy(), PhQ::SymmetricDyad< NumericType >::yz(), PhQ::Vector< NumericType >::z(), and PhQ::SymmetricDyad< NumericType >::zz().
operator*() [110/110]
template<typename NumericType , typename OtherNumericType > constexpr Vector< NumericType > PhQ::operator* (const Vector< NumericType > & vector, const OtherNumericType number) inline constexpr
Definition at line 379 of file Vector.hpp.
References PhQ::Vector< NumericType >::x(), PhQ::Vector< NumericType >::y(), and PhQ::Vector< NumericType >::z().
operator+() [1/4]
template<typename NumericType > constexpr Dyad< NumericType > PhQ::operator+ (const Dyad< NumericType > & left, const Dyad< NumericType > & right) inline constexpr
Definition at line 568 of file Dyad.hpp.
References PhQ::Dyad< NumericType >::xx(), PhQ::Dyad< NumericType >::xy(), PhQ::Dyad< NumericType >::xz(), PhQ::Dyad< NumericType >::yx(), PhQ::Dyad< NumericType >::yy(), PhQ::Dyad< NumericType >::yz(), PhQ::Dyad< NumericType >::zx(), PhQ::Dyad< NumericType >::zy(), and PhQ::Dyad< NumericType >::zz().
operator+() [2/4]
template<typename NumericType > constexpr PlanarVector< NumericType > PhQ::operator+ (const PlanarVector< NumericType > & left, const PlanarVector< NumericType > & right) inline constexpr
Definition at line 339 of file PlanarVector.hpp.
References PhQ::PlanarVector< NumericType >::x(), and PhQ::PlanarVector< NumericType >::y().
operator+() [3/4]
template<typename NumericType > constexpr SymmetricDyad< NumericType > PhQ::operator+ (const SymmetricDyad< NumericType > & left, const SymmetricDyad< NumericType > & right) inline constexpr
Definition at line 509 of file SymmetricDyad.hpp.
References PhQ::SymmetricDyad< NumericType >::xx(), PhQ::SymmetricDyad< NumericType >::xy(), PhQ::SymmetricDyad< NumericType >::xz(), PhQ::SymmetricDyad< NumericType >::yy(), PhQ::SymmetricDyad< NumericType >::yz(), and PhQ::SymmetricDyad< NumericType >::zz().
operator+() [4/4]
template<typename NumericType > constexpr Vector< NumericType > PhQ::operator+ (const Vector< NumericType > & left, const Vector< NumericType > & right) inline constexpr
Definition at line 367 of file Vector.hpp.
References PhQ::Vector< NumericType >::x(), PhQ::Vector< NumericType >::y(), and PhQ::Vector< NumericType >::z().
operator-() [1/4]
template<typename NumericType > constexpr Dyad< NumericType > PhQ::operator- (const Dyad< NumericType > & left, const Dyad< NumericType > & right) inline constexpr
Definition at line 576 of file Dyad.hpp.
References PhQ::Dyad< NumericType >::xx(), PhQ::Dyad< NumericType >::xy(), PhQ::Dyad< NumericType >::xz(), PhQ::Dyad< NumericType >::yx(), PhQ::Dyad< NumericType >::yy(), PhQ::Dyad< NumericType >::yz(), PhQ::Dyad< NumericType >::zx(), PhQ::Dyad< NumericType >::zy(), and PhQ::Dyad< NumericType >::zz().
operator-() [2/4]
template<typename NumericType > constexpr PlanarVector< NumericType > PhQ::operator- (const PlanarVector< NumericType > & left, const PlanarVector< NumericType > & right) inline constexpr
Definition at line 345 of file PlanarVector.hpp.
References PhQ::PlanarVector< NumericType >::x(), and PhQ::PlanarVector< NumericType >::y().
operator-() [3/4]
template<typename NumericType > constexpr SymmetricDyad< NumericType > PhQ::operator- (const SymmetricDyad< NumericType > & left, const SymmetricDyad< NumericType > & right) inline constexpr
Definition at line 517 of file SymmetricDyad.hpp.
References PhQ::SymmetricDyad< NumericType >::xx(), PhQ::SymmetricDyad< NumericType >::xy(), PhQ::SymmetricDyad< NumericType >::xz(), PhQ::SymmetricDyad< NumericType >::yy(), PhQ::SymmetricDyad< NumericType >::yz(), and PhQ::SymmetricDyad< NumericType >::zz().
operator-() [4/4]
template<typename NumericType > constexpr Vector< NumericType > PhQ::operator- (const Vector< NumericType > & left, const Vector< NumericType > & right) inline constexpr
Definition at line 373 of file Vector.hpp.
References PhQ::Vector< NumericType >::x(), PhQ::Vector< NumericType >::y(), and PhQ::Vector< NumericType >::z().
operator/() [1/4]
template<typename NumericType , typename OtherNumericType > constexpr Dyad< NumericType > PhQ::operator/ (const Dyad< NumericType > & dyad, const OtherNumericType number) inline constexpr
Definition at line 696 of file Dyad.hpp.
References PhQ::Dyad< NumericType >::xx(), PhQ::Dyad< NumericType >::xy(), PhQ::Dyad< NumericType >::xz(), PhQ::Dyad< NumericType >::yx(), PhQ::Dyad< NumericType >::yy(), PhQ::Dyad< NumericType >::yz(), PhQ::Dyad< NumericType >::zx(), PhQ::Dyad< NumericType >::zy(), and PhQ::Dyad< NumericType >::zz().
operator/() [2/4]
template<typename NumericType , typename OtherNumericType > constexpr PlanarVector< NumericType > PhQ::operator/ (const PlanarVector< NumericType > & planar_vector, const OtherNumericType number) inline constexpr
Definition at line 364 of file PlanarVector.hpp.
References PhQ::PlanarVector< NumericType >::x(), and PhQ::PlanarVector< NumericType >::y().
operator/() [3/4]
template<typename NumericType , typename OtherNumericType > constexpr SymmetricDyad< NumericType > PhQ::operator/ (const SymmetricDyad< NumericType > & symmetric_dyad, const OtherNumericType number) inline constexpr
Definition at line 572 of file SymmetricDyad.hpp.
References PhQ::SymmetricDyad< NumericType >::xx(), PhQ::SymmetricDyad< NumericType >::xy(), PhQ::SymmetricDyad< NumericType >::xz(), PhQ::SymmetricDyad< NumericType >::yy(), PhQ::SymmetricDyad< NumericType >::yz(), and PhQ::SymmetricDyad< NumericType >::zz().
operator/() [4/4]
template<typename NumericType , typename OtherNumericType > constexpr Vector< NumericType > PhQ::operator/ (const Vector< NumericType > & vector, const OtherNumericType number) inline constexpr
Definition at line 393 of file Vector.hpp.
References PhQ::Vector< NumericType >::x(), PhQ::Vector< NumericType >::y(), and PhQ::Vector< NumericType >::z().
operator<() [1/100]
template<typename NumericType > constexpr bool PhQ::operator< (const Acceleration< NumericType > & left, const Acceleration< NumericType > & right) inline constexpr noexcept
Definition at line 241 of file Acceleration.hpp.
operator<() [2/100]
template<typename NumericType > constexpr bool PhQ::operator< (const Angle< NumericType > & left, const Angle< NumericType > & right) inline constexpr noexcept
Definition at line 358 of file Angle.hpp.
operator<() [3/100]
template<typename NumericType > constexpr bool PhQ::operator< (const AngularSpeed< NumericType > & left, const AngularSpeed< NumericType > & right) inline constexpr noexcept
Definition at line 198 of file AngularSpeed.hpp.
operator<() [4/100]
template<typename NumericType > constexpr bool PhQ::operator< (const Area< NumericType > & left, const Area< NumericType > & right) inline constexpr noexcept
Definition at line 207 of file Area.hpp.
operator<() [5/100]
template<typename NumericType > constexpr bool PhQ::operator< (const BulkDynamicViscosity< NumericType > & left, const BulkDynamicViscosity< NumericType > & right) inline constexpr noexcept
Definition at line 156 of file BulkDynamicViscosity.hpp.
operator<() [6/100]
constexpr bool PhQ::operator< (const Dimensions & left, const Dimensions & right) inline constexpr noexcept
Definition at line 347 of file Dimensions.hpp.
operator<() [7/100]
template<typename NumericType > constexpr bool PhQ::operator< (const Direction< NumericType > & left, const Direction< NumericType > & right) inline constexpr noexcept
Definition at line 341 of file Direction.hpp.
operator<() [8/100]
template<typename NumericType > constexpr bool PhQ::operator< (const Displacement< NumericType > & left, const Displacement< NumericType > & right) inline constexpr noexcept
Definition at line 257 of file Displacement.hpp.
operator<() [9/100]
template<typename NumericType > constexpr bool PhQ::operator< (const DisplacementGradient< NumericType > & left, const DisplacementGradient< NumericType > & right) inline constexpr noexcept
Definition at line 227 of file DisplacementGradient.hpp.
operator<() [10/100]
template<typename NumericType > constexpr bool PhQ::operator< (const Dyad< NumericType > & left, const Dyad< NumericType > & right) inline constexpr noexcept
Definition at line 496 of file Dyad.hpp.
operator<() [11/100]
template<typename NumericType > constexpr bool PhQ::operator< (const DynamicKinematicPressure< NumericType > & left, const DynamicKinematicPressure< NumericType > & right) inline constexpr noexcept
Definition at line 186 of file DynamicKinematicPressure.hpp.
operator<() [12/100]
template<typename NumericType > constexpr bool PhQ::operator< (const DynamicPressure< NumericType > & left, const DynamicPressure< NumericType > & right) inline constexpr noexcept
Definition at line 183 of file DynamicPressure.hpp.
operator<() [13/100]
template<typename NumericType > constexpr bool PhQ::operator< (const DynamicViscosity< NumericType > & left, const DynamicViscosity< NumericType > & right) inline constexpr noexcept
Definition at line 198 of file DynamicViscosity.hpp.
operator<() [14/100]
template<typename NumericType > constexpr bool PhQ::operator< (const ElectricCharge< NumericType > & left, const ElectricCharge< NumericType > & right) inline constexpr noexcept
Definition at line 178 of file ElectricCharge.hpp.
operator<() [15/100]
template<typename NumericType > constexpr bool PhQ::operator< (const ElectricCurrent< NumericType > & left, const ElectricCurrent< NumericType > & right) inline constexpr noexcept
Definition at line 180 of file ElectricCurrent.hpp.
operator<() [16/100]
template<typename NumericType > constexpr bool PhQ::operator< (const Energy< NumericType > & left, const Energy< NumericType > & right) inline constexpr noexcept
Definition at line 213 of file Energy.hpp.
operator<() [17/100]
template<typename NumericType > constexpr bool PhQ::operator< (const Force< NumericType > & left, const Force< NumericType > & right) inline constexpr noexcept
Definition at line 222 of file Force.hpp.
operator<() [18/100]
template<typename NumericType > constexpr bool PhQ::operator< (const Frequency< NumericType > & left, const Frequency< NumericType > & right) inline constexpr noexcept
Definition at line 250 of file Frequency.hpp.
operator<() [19/100]
template<typename NumericType > constexpr bool PhQ::operator< (const GasConstant< NumericType > & left, const GasConstant< NumericType > & right) inline constexpr noexcept
Definition at line 188 of file GasConstant.hpp.
operator<() [20/100]
template<typename NumericType > constexpr bool PhQ::operator< (const HeatCapacityRatio< NumericType > & left, const HeatCapacityRatio< NumericType > & right) inline constexpr noexcept
Definition at line 207 of file HeatCapacityRatio.hpp.
operator<() [21/100]
template<typename NumericType > constexpr bool PhQ::operator< (const HeatFlux< NumericType > & left, const HeatFlux< NumericType > & right) inline constexpr noexcept
Definition at line 235 of file HeatFlux.hpp.
operator<() [22/100]
template<typename NumericType > constexpr bool PhQ::operator< (const IsentropicBulkModulus< NumericType > & left, const IsentropicBulkModulus< NumericType > & right) inline constexpr noexcept
Definition at line 170 of file IsentropicBulkModulus.hpp.
operator<() [23/100]
template<typename NumericType > constexpr bool PhQ::operator< (const IsobaricHeatCapacity< NumericType > & left, const IsobaricHeatCapacity< NumericType > & right) inline constexpr noexcept
Definition at line 201 of file IsobaricHeatCapacity.hpp.
operator<() [24/100]
template<typename NumericType > constexpr bool PhQ::operator< (const IsochoricHeatCapacity< NumericType > & left, const IsochoricHeatCapacity< NumericType > & right) inline constexpr noexcept
Definition at line 189 of file IsochoricHeatCapacity.hpp.
operator<() [25/100]
template<typename NumericType > constexpr bool PhQ::operator< (const IsothermalBulkModulus< NumericType > & left, const IsothermalBulkModulus< NumericType > & right) inline constexpr noexcept
Definition at line 157 of file IsothermalBulkModulus.hpp.
operator<() [26/100]
template<typename NumericType > constexpr bool PhQ::operator< (const KinematicViscosity< NumericType > & left, const KinematicViscosity< NumericType > & right) inline constexpr noexcept
Definition at line 200 of file KinematicViscosity.hpp.
operator<() [27/100]
template<typename NumericType > constexpr bool PhQ::operator< (const LameFirstModulus< NumericType > & left, const LameFirstModulus< NumericType > & right) inline constexpr noexcept
Definition at line 157 of file LameFirstModulus.hpp.
operator<() [28/100]
template<typename NumericType > constexpr bool PhQ::operator< (const Length< NumericType > & left, const Length< NumericType > & right) inline constexpr noexcept
Definition at line 276 of file Length.hpp.
operator<() [29/100]
template<typename NumericType > constexpr bool PhQ::operator< (const LinearThermalExpansionCoefficient< NumericType > & left, const LinearThermalExpansionCoefficient< NumericType > & right) inline constexpr noexcept
Definition at line 185 of file LinearThermalExpansionCoefficient.hpp.
operator<() [30/100]
template<typename NumericType > constexpr bool PhQ::operator< (const MachNumber< NumericType > & left, const MachNumber< NumericType > & right) inline constexpr noexcept
Definition at line 142 of file MachNumber.hpp.
operator<() [31/100]
template<typename NumericType > constexpr bool PhQ::operator< (const Mass< NumericType > & left, const Mass< NumericType > & right) inline constexpr noexcept
Definition at line 262 of file Mass.hpp.
operator<() [32/100]
template<typename NumericType > constexpr bool PhQ::operator< (const MassDensity< NumericType > & left, const MassDensity< NumericType > & right) inline constexpr noexcept
Definition at line 241 of file MassDensity.hpp.
operator<() [33/100]
template<typename NumericType > constexpr bool PhQ::operator< (const MassRate< NumericType > & left, const MassRate< NumericType > & right) inline constexpr noexcept
Definition at line 187 of file MassRate.hpp.
operator<() [34/100]
template<typename NumericType > constexpr bool PhQ::operator< (const Memory< NumericType > & left, const Memory< NumericType > & right) inline constexpr noexcept
Definition at line 173 of file Memory.hpp.
operator<() [35/100]
template<typename NumericType > constexpr bool PhQ::operator< (const MemoryRate< NumericType > & left, const MemoryRate< NumericType > & right) inline constexpr noexcept
Definition at line 171 of file MemoryRate.hpp.
operator<() [36/100]
template<typename NumericType > constexpr bool PhQ::operator< (const PlanarAcceleration< NumericType > & left, const PlanarAcceleration< NumericType > & right) inline constexpr noexcept
Definition at line 240 of file PlanarAcceleration.hpp.
operator<() [37/100]
template<typename NumericType > constexpr bool PhQ::operator< (const PlanarDirection< NumericType > & left, const PlanarDirection< NumericType > & right) inline constexpr noexcept
Definition at line 345 of file PlanarDirection.hpp.
operator<() [38/100]
template<typename NumericType > constexpr bool PhQ::operator< (const PlanarDisplacement< NumericType > & left, const PlanarDisplacement< NumericType > & right) inline constexpr noexcept
Definition at line 269 of file PlanarDisplacement.hpp.
operator<() [39/100]
template<typename NumericType > constexpr bool PhQ::operator< (const PlanarForce< NumericType > & left, const PlanarForce< NumericType > & right) inline constexpr noexcept
Definition at line 219 of file PlanarForce.hpp.
operator<() [40/100]
template<typename NumericType > constexpr bool PhQ::operator< (const PlanarHeatFlux< NumericType > & left, const PlanarHeatFlux< NumericType > & right) inline constexpr noexcept
Definition at line 237 of file PlanarHeatFlux.hpp.
operator<() [41/100]
template<typename NumericType > constexpr bool PhQ::operator< (const PlanarPosition< NumericType > & left, const PlanarPosition< NumericType > & right) inline constexpr noexcept
Definition at line 242 of file PlanarPosition.hpp.
operator<() [42/100]
template<typename NumericType > constexpr bool PhQ::operator< (const PlanarTemperatureGradient< NumericType > & left, const PlanarTemperatureGradient< NumericType > & right) inline constexpr noexcept
Definition at line 235 of file PlanarTemperatureGradient.hpp.
operator<() [43/100]
template<typename NumericType > constexpr bool PhQ::operator< (const PlanarTraction< NumericType > & left, const PlanarTraction< NumericType > & right) inline constexpr noexcept
Definition at line 236 of file PlanarTraction.hpp.
operator<() [44/100]
template<typename NumericType > constexpr bool PhQ::operator< (const PlanarVector< NumericType > & left, const PlanarVector< NumericType > & right) inline constexpr noexcept
Definition at line 309 of file PlanarVector.hpp.
operator<() [45/100]
template<typename NumericType > constexpr bool PhQ::operator< (const PlanarVelocity< NumericType > & left, const PlanarVelocity< NumericType > & right) inline constexpr noexcept
Definition at line 255 of file PlanarVelocity.hpp.
operator<() [46/100]
template<typename NumericType > constexpr bool PhQ::operator< (const PoissonRatio< NumericType > & left, const PoissonRatio< NumericType > & right) inline constexpr noexcept
Definition at line 135 of file PoissonRatio.hpp.
operator<() [47/100]
template<typename NumericType > constexpr bool PhQ::operator< (const Position< NumericType > & left, const Position< NumericType > & right) inline constexpr noexcept
Definition at line 237 of file Position.hpp.
operator<() [48/100]
template<typename NumericType > constexpr bool PhQ::operator< (const Power< NumericType > & left, const Power< NumericType > & right) inline constexpr noexcept
Definition at line 190 of file Power.hpp.
operator<() [49/100]
template<typename NumericType > constexpr bool PhQ::operator< (const PrandtlNumber< NumericType > & left, const PrandtlNumber< NumericType > & right) inline constexpr noexcept
Definition at line 188 of file PrandtlNumber.hpp.
operator<() [50/100]
template<typename NumericType > constexpr bool PhQ::operator< (const PWaveModulus< NumericType > & left, const PWaveModulus< NumericType > & right) inline constexpr noexcept
Definition at line 151 of file PWaveModulus.hpp.
operator<() [51/100]
template<typename NumericType > constexpr bool PhQ::operator< (const ReynoldsNumber< NumericType > & left, const ReynoldsNumber< NumericType > & right) inline constexpr noexcept
Definition at line 198 of file ReynoldsNumber.hpp.
operator<() [52/100]
template<typename NumericType > constexpr bool PhQ::operator< (const ScalarAcceleration< NumericType > & left, const ScalarAcceleration< NumericType > & right) inline constexpr noexcept
Definition at line 206 of file ScalarAcceleration.hpp.
operator<() [53/100]
template<typename NumericType > constexpr bool PhQ::operator< (const ScalarAngularAcceleration< NumericType > & left, const ScalarAngularAcceleration< NumericType > & right) inline constexpr noexcept
Definition at line 191 of file ScalarAngularAcceleration.hpp.
operator<() [54/100]
template<typename NumericType > constexpr bool PhQ::operator< (const ScalarDisplacementGradient< NumericType > & left, const ScalarDisplacementGradient< NumericType > & right) inline constexpr noexcept
Definition at line 178 of file ScalarDisplacementGradient.hpp.
operator<() [55/100]
template<typename NumericType > constexpr bool PhQ::operator< (const ScalarForce< NumericType > & left, const ScalarForce< NumericType > & right) inline constexpr noexcept
Definition at line 195 of file ScalarForce.hpp.
operator<() [56/100]
template<typename NumericType > constexpr bool PhQ::operator< (const ScalarHeatFlux< NumericType > & left, const ScalarHeatFlux< NumericType > & right) inline constexpr noexcept
Definition at line 182 of file ScalarHeatFlux.hpp.
operator<() [57/100]
template<typename NumericType > constexpr bool PhQ::operator< (const ScalarStrain< NumericType > & left, const ScalarStrain< NumericType > & right) inline constexpr noexcept
Definition at line 175 of file ScalarStrain.hpp.
operator<() [58/100]
template<typename NumericType > constexpr bool PhQ::operator< (const ScalarStrainRate< NumericType > & left, const ScalarStrainRate< NumericType > & right) inline constexpr noexcept
Definition at line 178 of file ScalarStrainRate.hpp.
operator<() [59/100]
template<typename NumericType > constexpr bool PhQ::operator< (const ScalarStress< NumericType > & left, const ScalarStress< NumericType > & right) inline constexpr noexcept
Definition at line 156 of file ScalarStress.hpp.
operator<() [60/100]
template<typename NumericType > constexpr bool PhQ::operator< (const ScalarTemperatureGradient< NumericType > & left, const ScalarTemperatureGradient< NumericType > & right) inline constexpr noexcept
Definition at line 206 of file ScalarTemperatureGradient.hpp.
operator<() [61/100]
template<typename NumericType > constexpr bool PhQ::operator< (const ScalarThermalConductivity< NumericType > & left, const ScalarThermalConductivity< NumericType > & right) inline constexpr noexcept
Definition at line 204 of file ScalarThermalConductivity.hpp.
operator<() [62/100]
template<typename NumericType > constexpr bool PhQ::operator< (const ScalarTraction< NumericType > & left, const ScalarTraction< NumericType > & right) inline constexpr noexcept
Definition at line 190 of file ScalarTraction.hpp.
operator<() [63/100]
template<typename NumericType > constexpr bool PhQ::operator< (const ScalarVelocityGradient< NumericType > & left, const ScalarVelocityGradient< NumericType > & right) inline constexpr noexcept
Definition at line 184 of file ScalarVelocityGradient.hpp.
operator<() [64/100]
template<typename NumericType > constexpr bool PhQ::operator< (const ShearModulus< NumericType > & left, const ShearModulus< NumericType > & right) inline constexpr noexcept
Definition at line 153 of file ShearModulus.hpp.
operator<() [65/100]
template<typename NumericType > constexpr bool PhQ::operator< (const SolidAngle< NumericType > & left, const SolidAngle< NumericType > & right) inline constexpr noexcept
Definition at line 148 of file SolidAngle.hpp.
operator<() [66/100]
template<typename NumericType > constexpr bool PhQ::operator< (const SoundSpeed< NumericType > & left, const SoundSpeed< NumericType > & right) inline constexpr noexcept
Definition at line 204 of file SoundSpeed.hpp.
operator<() [67/100]
template<typename NumericType > constexpr bool PhQ::operator< (const SpecificEnergy< NumericType > & left, const SpecificEnergy< NumericType > & right) inline constexpr noexcept
Definition at line 184 of file SpecificEnergy.hpp.
operator<() [68/100]
template<typename NumericType > constexpr bool PhQ::operator< (const SpecificGasConstant< NumericType > & left, const SpecificGasConstant< NumericType > & right) inline constexpr noexcept
Definition at line 201 of file SpecificGasConstant.hpp.
operator<() [69/100]
template<typename NumericType > constexpr bool PhQ::operator< (const SpecificIsobaricHeatCapacity< NumericType > & left, const SpecificIsobaricHeatCapacity< NumericType > & right) inline constexpr noexcept
Definition at line 255 of file SpecificIsobaricHeatCapacity.hpp.
operator<() [70/100]
template<typename NumericType > constexpr bool PhQ::operator< (const SpecificIsochoricHeatCapacity< NumericType > & left, const SpecificIsochoricHeatCapacity< NumericType > & right) inline constexpr noexcept
Definition at line 208 of file SpecificIsochoricHeatCapacity.hpp.
operator<() [71/100]
template<typename NumericType > constexpr bool PhQ::operator< (const SpecificPower< NumericType > & left, const SpecificPower< NumericType > & right) inline constexpr noexcept
Definition at line 188 of file SpecificPower.hpp.
operator<() [72/100]
template<typename NumericType > constexpr bool PhQ::operator< (const Speed< NumericType > & left, const Speed< NumericType > & right) inline constexpr noexcept
Definition at line 296 of file Speed.hpp.
operator<() [73/100]
template<typename NumericType > constexpr bool PhQ::operator< (const StaticKinematicPressure< NumericType > & left, const StaticKinematicPressure< NumericType > & right) inline constexpr noexcept
Definition at line 187 of file StaticKinematicPressure.hpp.
operator<() [74/100]
template<typename NumericType > constexpr bool PhQ::operator< (const StaticPressure< NumericType > & left, const StaticPressure< NumericType > & right) inline constexpr noexcept
Definition at line 206 of file StaticPressure.hpp.
operator<() [75/100]
template<typename NumericType > constexpr bool PhQ::operator< (const Strain< NumericType > & left, const Strain< NumericType > & right) inline constexpr noexcept
Definition at line 235 of file Strain.hpp.
operator<() [76/100]
template<typename NumericType > constexpr bool PhQ::operator< (const StrainRate< NumericType > & left, const StrainRate< NumericType > & right) inline constexpr noexcept
Definition at line 250 of file StrainRate.hpp.
operator<() [77/100]
template<typename NumericType > constexpr bool PhQ::operator< (const Stress< NumericType > & left, const Stress< NumericType > & right) inline constexpr noexcept
Definition at line 261 of file Stress.hpp.
operator<() [78/100]
template<typename NumericType > constexpr bool PhQ::operator< (const SubstanceAmount< NumericType > & left, const SubstanceAmount< NumericType > & right) inline constexpr noexcept
Definition at line 151 of file SubstanceAmount.hpp.
operator<() [79/100]
template<typename NumericType > constexpr bool PhQ::operator< (const SymmetricDyad< NumericType > & left, const SymmetricDyad< NumericType > & right) inline constexpr noexcept
Definition at line 455 of file SymmetricDyad.hpp.
operator<() [80/100]
template<typename NumericType > constexpr bool PhQ::operator< (const Temperature< NumericType > & left, const Temperature< NumericType > & right) inline constexpr noexcept
Definition at line 172 of file Temperature.hpp.
operator<() [81/100]
template<typename NumericType > constexpr bool PhQ::operator< (const TemperatureDifference< NumericType > & left, const TemperatureDifference< NumericType > & right) inline constexpr noexcept
Definition at line 208 of file TemperatureDifference.hpp.
operator<() [82/100]
template<typename NumericType > constexpr bool PhQ::operator< (const TemperatureGradient< NumericType > & left, const TemperatureGradient< NumericType > & right) inline constexpr noexcept
Definition at line 233 of file TemperatureGradient.hpp.
operator<() [83/100]
template<typename NumericType > constexpr bool PhQ::operator< (const ThermalConductivity< NumericType > & left, const ThermalConductivity< NumericType > & right) inline constexpr noexcept
Definition at line 234 of file ThermalConductivity.hpp.
operator<() [84/100]
template<typename NumericType > constexpr bool PhQ::operator< (const ThermalDiffusivity< NumericType > & left, const ThermalDiffusivity< NumericType > & right) inline constexpr noexcept
Definition at line 178 of file ThermalDiffusivity.hpp.
operator<() [85/100]
template<typename NumericType > constexpr bool PhQ::operator< (const Time< NumericType > & left, const Time< NumericType > & right) inline constexpr noexcept
Definition at line 368 of file Time.hpp.
operator<() [86/100]
template<typename NumericType > constexpr bool PhQ::operator< (const TotalKinematicPressure< NumericType > & left, const TotalKinematicPressure< NumericType > & right) inline constexpr noexcept
Definition at line 183 of file TotalKinematicPressure.hpp.
operator<() [87/100]
template<typename NumericType > constexpr bool PhQ::operator< (const TotalPressure< NumericType > & left, const TotalPressure< NumericType > & right) inline constexpr noexcept
Definition at line 182 of file TotalPressure.hpp.
operator<() [88/100]
template<typename NumericType > constexpr bool PhQ::operator< (const Traction< NumericType > & left, const Traction< NumericType > & right) inline constexpr noexcept
Definition at line 233 of file Traction.hpp.
operator<() [89/100]
template<typename NumericType > constexpr bool PhQ::operator< (const TransportEnergyConsumption< NumericType > & left, const TransportEnergyConsumption< NumericType > & right) inline constexpr noexcept
Definition at line 184 of file TransportEnergyConsumption.hpp.
operator<() [90/100]
template<typename NumericType > constexpr bool PhQ::operator< (const typename ConstitutiveModel::CompressibleNewtonianFluid< NumericType > & left, const typename ConstitutiveModel::CompressibleNewtonianFluid< NumericType > & right) inline constexpr noexcept
Definition at line 359 of file CompressibleNewtonianFluid.hpp.
operator<() [91/100]
template<typename NumericType > constexpr bool PhQ::operator< (const typename ConstitutiveModel::ElasticIsotropicSolid< NumericType > & left, const typename ConstitutiveModel::ElasticIsotropicSolid< NumericType > & right) inline constexpr noexcept
Definition at line 602 of file ElasticIsotropicSolid.hpp.
operator<() [92/100]
template<typename NumericType > constexpr bool PhQ::operator< (const typename ConstitutiveModel::IncompressibleNewtonianFluid< NumericType > & left, const typename ConstitutiveModel::IncompressibleNewtonianFluid< NumericType > & right) inline constexpr noexcept
Definition at line 269 of file IncompressibleNewtonianFluid.hpp.
operator<() [93/100]
template<typename NumericType > constexpr bool PhQ::operator< (const Vector< NumericType > & left, const Vector< NumericType > & right) inline constexpr noexcept
Definition at line 331 of file Vector.hpp.
operator<() [94/100]
template<typename NumericType > constexpr bool PhQ::operator< (const VectorArea< NumericType > & left, const VectorArea< NumericType > & right) inline constexpr noexcept
Definition at line 205 of file VectorArea.hpp.
operator<() [95/100]
template<typename NumericType > constexpr bool PhQ::operator< (const Velocity< NumericType > & left, const Velocity< NumericType > & right) inline constexpr noexcept
Definition at line 250 of file Velocity.hpp.
operator<() [96/100]
template<typename NumericType > constexpr bool PhQ::operator< (const VelocityGradient< NumericType > & left, const VelocityGradient< NumericType > & right) inline constexpr noexcept
Definition at line 263 of file VelocityGradient.hpp.
operator<() [97/100]
template<typename NumericType > constexpr bool PhQ::operator< (const Volume< NumericType > & left, const Volume< NumericType > & right) inline constexpr noexcept
Definition at line 199 of file Volume.hpp.
operator<() [98/100]
template<typename NumericType > constexpr bool PhQ::operator< (const VolumeRate< NumericType > & left, const VolumeRate< NumericType > & right) inline constexpr noexcept
Definition at line 186 of file VolumeRate.hpp.
operator<() [99/100]
template<typename NumericType > constexpr bool PhQ::operator< (const VolumetricThermalExpansionCoefficient< NumericType > & left, const VolumetricThermalExpansionCoefficient< NumericType > & right) inline constexpr noexcept
Definition at line 185 of file VolumetricThermalExpansionCoefficient.hpp.
operator<() [100/100]
template<typename NumericType > constexpr bool PhQ::operator< (const YoungModulus< NumericType > & left, const YoungModulus< NumericType > & right) inline constexpr noexcept
Definition at line 151 of file YoungModulus.hpp.
operator<<() [1/139]
template<typename NumericType > std::ostream & PhQ::operator<< (std::ostream & stream, const Acceleration< NumericType > & acceleration) inline
Definition at line 265 of file Acceleration.hpp.
References PhQ::DimensionalVector< UnitType, NumericType >::Print().
operator<<() [2/139]
template<typename NumericType > std::ostream & PhQ::operator<< (std::ostream & stream, const Angle< NumericType > & angle) inline
Definition at line 382 of file Angle.hpp.
References PhQ::DimensionalScalar< UnitType, NumericType >::Print().
operator<<() [3/139]
template<typename NumericType > std::ostream & PhQ::operator<< (std::ostream & stream, const AngularSpeed< NumericType > & angular_speed) inline
Definition at line 222 of file AngularSpeed.hpp.
References PhQ::DimensionalScalar< UnitType, NumericType >::Print().
operator<<() [4/139]
template<typename NumericType > std::ostream & PhQ::operator<< (std::ostream & stream, const Area< NumericType > & area) inline
Definition at line 231 of file Area.hpp.
References PhQ::DimensionalScalar< UnitType, NumericType >::Print().
operator<<() [5/139]
template<typename NumericType > std::ostream & PhQ::operator<< (std::ostream & stream, const BulkDynamicViscosity< NumericType > & mass_density) inline
Definition at line 180 of file BulkDynamicViscosity.hpp.
References PhQ::DimensionalScalar< UnitType, NumericType >::Print().
operator<<() [6/139]
std::ostream & PhQ::operator<< (std::ostream & stream, const ConstitutiveModel & model) inline
Definition at line 194 of file ConstitutiveModel.hpp.
References PhQ::ConstitutiveModel::Print().
operator<<() [7/139]
std::ostream & PhQ::operator<< (std::ostream & stream, const Dimensions & dimensions) inline
Definition at line 399 of file Dimensions.hpp.
References PhQ::Dimensions::Print().
operator<<() [8/139]
template<typename NumericType > std::ostream & PhQ::operator<< (std::ostream & stream, const Displacement< NumericType > & displacement) inline
Definition at line 281 of file Displacement.hpp.
References PhQ::DimensionalVector< UnitType, NumericType >::Print().
operator<<() [9/139]
template<typename NumericType > std::ostream & PhQ::operator<< (std::ostream & stream, const DisplacementGradient< NumericType > & displacement_gradient) inline
Definition at line 251 of file DisplacementGradient.hpp.
References PhQ::DimensionlessDyad< NumericType >::Print().
operator<<() [10/139]
template<typename NumericType > std::ostream & PhQ::operator<< (std::ostream & stream, const Dyad< NumericType > & dyad) inline
Definition at line 707 of file Dyad.hpp.
References PhQ::Dyad< NumericType >::Print().
operator<<() [11/139]
template<typename NumericType > std::ostream & PhQ::operator<< (std::ostream & stream, const DynamicKinematicPressure< NumericType > & dynamic_kinematic_pressure) inline
Definition at line 210 of file DynamicKinematicPressure.hpp.
References PhQ::DimensionalScalar< UnitType, NumericType >::Print().
operator<<() [12/139]
template<typename NumericType > std::ostream & PhQ::operator<< (std::ostream & stream, const DynamicPressure< NumericType > & dynamic_pressure) inline
Definition at line 207 of file DynamicPressure.hpp.
References PhQ::DimensionalScalar< UnitType, NumericType >::Print().
operator<<() [13/139]
template<typename NumericType > std::ostream & PhQ::operator<< (std::ostream & stream, const DynamicViscosity< NumericType > & dynamic_viscosity) inline
Definition at line 222 of file DynamicViscosity.hpp.
References PhQ::DimensionalScalar< UnitType, NumericType >::Print().
operator<<() [14/139]
template<typename NumericType > std::ostream & PhQ::operator<< (std::ostream & stream, const ElectricCharge< NumericType > & electric_charge) inline
Definition at line 202 of file ElectricCharge.hpp.
References PhQ::DimensionalScalar< UnitType, NumericType >::Print().
operator<<() [15/139]
template<typename NumericType > std::ostream & PhQ::operator<< (std::ostream & stream, const ElectricCurrent< NumericType > & electric_current) inline
Definition at line 204 of file ElectricCurrent.hpp.
References PhQ::DimensionalScalar< UnitType, NumericType >::Print().
operator<<() [16/139]
template<typename NumericType > std::ostream & PhQ::operator<< (std::ostream & stream, const Energy< NumericType > & energy) inline
Definition at line 237 of file Energy.hpp.
References PhQ::DimensionalScalar< UnitType, NumericType >::Print().
operator<<() [17/139]
template<typename NumericType > std::ostream & PhQ::operator<< (std::ostream & stream, const Force< NumericType > & force) inline
Definition at line 246 of file Force.hpp.
References PhQ::DimensionalVector< UnitType, NumericType >::Print().
operator<<() [18/139]
template<typename NumericType > std::ostream & PhQ::operator<< (std::ostream & stream, const Frequency< NumericType > & frequency) inline
Definition at line 274 of file Frequency.hpp.
References PhQ::DimensionalScalar< UnitType, NumericType >::Print().
operator<<() [19/139]
template<typename NumericType > std::ostream & PhQ::operator<< (std::ostream & stream, const GasConstant< NumericType > & gas_constant) inline
Definition at line 212 of file GasConstant.hpp.
References PhQ::DimensionalScalar< UnitType, NumericType >::Print().
operator<<() [20/139]
template<typename NumericType > std::ostream & PhQ::operator<< (std::ostream & stream, const HeatCapacityRatio< NumericType > & heat_capacity_ratio) inline
Definition at line 231 of file HeatCapacityRatio.hpp.
References PhQ::DimensionlessScalar< NumericType >::Print().
operator<<() [21/139]
template<typename NumericType > std::ostream & PhQ::operator<< (std::ostream & stream, const HeatFlux< NumericType > & heat_flux) inline
Definition at line 259 of file HeatFlux.hpp.
References PhQ::DimensionalVector< UnitType, NumericType >::Print().
operator<<() [22/139]
template<typename NumericType > std::ostream & PhQ::operator<< (std::ostream & stream, const IsentropicBulkModulus< NumericType > & isentropic_bulk_modulus) inline
Definition at line 194 of file IsentropicBulkModulus.hpp.
References PhQ::DimensionalScalar< UnitType, NumericType >::Print().
operator<<() [23/139]
template<typename NumericType > std::ostream & PhQ::operator<< (std::ostream & stream, const IsobaricHeatCapacity< NumericType > & isobaric_heat_capacity) inline
Definition at line 225 of file IsobaricHeatCapacity.hpp.
References PhQ::DimensionalScalar< UnitType, NumericType >::Print().
operator<<() [24/139]
template<typename NumericType > std::ostream & PhQ::operator<< (std::ostream & stream, const IsochoricHeatCapacity< NumericType > & isochoric_heat_capacity) inline
Definition at line 213 of file IsochoricHeatCapacity.hpp.
References PhQ::DimensionalScalar< UnitType, NumericType >::Print().
operator<<() [25/139]
template<typename NumericType > std::ostream & PhQ::operator<< (std::ostream & stream, const IsothermalBulkModulus< NumericType > & isothermal_bulk_modulus) inline
Definition at line 181 of file IsothermalBulkModulus.hpp.
References PhQ::DimensionalScalar< UnitType, NumericType >::Print().
operator<<() [26/139]
template<typename NumericType > std::ostream & PhQ::operator<< (std::ostream & stream, const KinematicViscosity< NumericType > & kinematic_viscosity) inline
Definition at line 224 of file KinematicViscosity.hpp.
References PhQ::DimensionalScalar< UnitType, NumericType >::Print().
operator<<() [27/139]
template<typename NumericType > std::ostream & PhQ::operator<< (std::ostream & stream, const LameFirstModulus< NumericType > & lame_first_modulus) inline
Definition at line 181 of file LameFirstModulus.hpp.
References PhQ::DimensionalScalar< UnitType, NumericType >::Print().
operator<<() [28/139]
template<typename NumericType > std::ostream & PhQ::operator<< (std::ostream & stream, const Length< NumericType > & length) inline
Definition at line 300 of file Length.hpp.
References PhQ::DimensionalScalar< UnitType, NumericType >::Print().
operator<<() [29/139]
template<typename NumericType > std::ostream & PhQ::operator<< (std::ostream & stream, const LinearThermalExpansionCoefficient< NumericType > & linear_thermal_expansion_coefficient) inline
Definition at line 213 of file LinearThermalExpansionCoefficient.hpp.
References PhQ::DimensionalScalar< UnitType, NumericType >::Print().
operator<<() [30/139]
template<typename NumericType > std::ostream & PhQ::operator<< (std::ostream & stream, const MachNumber< NumericType > & mach_number) inline
Definition at line 166 of file MachNumber.hpp.
References PhQ::DimensionlessScalar< NumericType >::Print().
operator<<() [31/139]
template<typename NumericType > std::ostream & PhQ::operator<< (std::ostream & stream, const Mass< NumericType > & mass) inline
Definition at line 286 of file Mass.hpp.
References PhQ::DimensionalScalar< UnitType, NumericType >::Print().
operator<<() [32/139]
template<typename NumericType > std::ostream & PhQ::operator<< (std::ostream & stream, const MassDensity< NumericType > & mass_density) inline
Definition at line 265 of file MassDensity.hpp.
References PhQ::DimensionalScalar< UnitType, NumericType >::Print().
operator<<() [33/139]
template<typename NumericType > std::ostream & PhQ::operator<< (std::ostream & stream, const MassRate< NumericType > & mass_rate) inline
Definition at line 211 of file MassRate.hpp.
References PhQ::DimensionalScalar< UnitType, NumericType >::Print().
operator<<() [34/139]
template<typename NumericType > std::ostream & PhQ::operator<< (std::ostream & stream, const Memory< NumericType > & memory) inline
Definition at line 197 of file Memory.hpp.
References PhQ::DimensionalScalar< UnitType, NumericType >::Print().
operator<<() [35/139]
template<typename NumericType > std::ostream & PhQ::operator<< (std::ostream & stream, const MemoryRate< NumericType > & memory_rate) inline
Definition at line 195 of file MemoryRate.hpp.
References PhQ::DimensionalScalar< UnitType, NumericType >::Print().
operator<<() [36/139]
template<typename NumericType > std::ostream & PhQ::operator<< (std::ostream & stream, const PhQ::Direction< NumericType > & direction) inline
Definition at line 365 of file Direction.hpp.
References PhQ::DimensionlessVector< NumericType >::Print().
operator<<() [37/139]
template<typename NumericType > std::ostream & PhQ::operator<< (std::ostream & stream, const PhQ::PlanarDirection< NumericType > & planar_direction) inline
Definition at line 369 of file PlanarDirection.hpp.
References PhQ::DimensionlessPlanarVector< NumericType >::Print().
operator<<() [38/139]
template<typename NumericType > std::ostream & PhQ::operator<< (std::ostream & stream, const PlanarAcceleration< NumericType > & planar_acceleration) inline
Definition at line 264 of file PlanarAcceleration.hpp.
References PhQ::DimensionalPlanarVector< UnitType, NumericType >::Print().
operator<<() [39/139]
template<typename NumericType > std::ostream & PhQ::operator<< (std::ostream & stream, const PlanarDisplacement< NumericType > & planar_displacement) inline
Definition at line 293 of file PlanarDisplacement.hpp.
References PhQ::DimensionalPlanarVector< UnitType, NumericType >::Print().
operator<<() [40/139]
template<typename NumericType > std::ostream & PhQ::operator<< (std::ostream & stream, const PlanarForce< NumericType > & planar_force) inline
Definition at line 243 of file PlanarForce.hpp.
References PhQ::DimensionalPlanarVector< UnitType, NumericType >::Print().
operator<<() [41/139]
template<typename NumericType > std::ostream & PhQ::operator<< (std::ostream & stream, const PlanarHeatFlux< NumericType > & planar_heat_flux) inline
Definition at line 261 of file PlanarHeatFlux.hpp.
References PhQ::DimensionalPlanarVector< UnitType, NumericType >::Print().
operator<<() [42/139]
template<typename NumericType > std::ostream & PhQ::operator<< (std::ostream & stream, const PlanarPosition< NumericType > & planar_position) inline
Definition at line 266 of file PlanarPosition.hpp.
References PhQ::DimensionalPlanarVector< UnitType, NumericType >::Print().
operator<<() [43/139]
template<typename NumericType > std::ostream & PhQ::operator<< (std::ostream & stream, const PlanarTemperatureGradient< NumericType > & planar_temperature_gradient) inline
Definition at line 259 of file PlanarTemperatureGradient.hpp.
References PhQ::DimensionalPlanarVector< UnitType, NumericType >::Print().
operator<<() [44/139]
template<typename NumericType > std::ostream & PhQ::operator<< (std::ostream & stream, const PlanarTraction< NumericType > & planar_traction) inline
Definition at line 260 of file PlanarTraction.hpp.
References PhQ::DimensionalPlanarVector< UnitType, NumericType >::Print().
operator<<() [45/139]
template<typename NumericType > std::ostream & PhQ::operator<< (std::ostream & stream, const PlanarVector< NumericType > & planar_vector) inline
Definition at line 371 of file PlanarVector.hpp.
References PhQ::PlanarVector< NumericType >::Print().
operator<<() [46/139]
template<typename NumericType > std::ostream & PhQ::operator<< (std::ostream & stream, const PlanarVelocity< NumericType > & planar_velocity) inline
Definition at line 279 of file PlanarVelocity.hpp.
References PhQ::DimensionalPlanarVector< UnitType, NumericType >::Print().
operator<<() [47/139]
template<typename NumericType > std::ostream & PhQ::operator<< (std::ostream & stream, const PoissonRatio< NumericType > & poisson_ratio) inline
Definition at line 159 of file PoissonRatio.hpp.
References PhQ::DimensionlessScalar< NumericType >::Print().
operator<<() [48/139]
template<typename NumericType > std::ostream & PhQ::operator<< (std::ostream & stream, const Position< NumericType > & position) inline
Definition at line 261 of file Position.hpp.
References PhQ::DimensionalVector< UnitType, NumericType >::Print().
operator<<() [49/139]
template<typename NumericType > std::ostream & PhQ::operator<< (std::ostream & stream, const Power< NumericType > & power) inline
Definition at line 214 of file Power.hpp.
References PhQ::DimensionalScalar< UnitType, NumericType >::Print().
operator<<() [50/139]
template<typename NumericType > std::ostream & PhQ::operator<< (std::ostream & stream, const PrandtlNumber< NumericType > & prandtl_number) inline
Definition at line 212 of file PrandtlNumber.hpp.
References PhQ::DimensionlessScalar< NumericType >::Print().
operator<<() [51/139]
template<typename NumericType > std::ostream & PhQ::operator<< (std::ostream & stream, const PWaveModulus< NumericType > & p_wave_modulus) inline
Definition at line 175 of file PWaveModulus.hpp.
References PhQ::DimensionalScalar< UnitType, NumericType >::Print().
operator<<() [52/139]
template<typename NumericType > std::ostream & PhQ::operator<< (std::ostream & stream, const ReynoldsNumber< NumericType > & reynolds_number) inline
Definition at line 222 of file ReynoldsNumber.hpp.
References PhQ::DimensionlessScalar< NumericType >::Print().
operator<<() [53/139]
template<typename NumericType > std::ostream & PhQ::operator<< (std::ostream & stream, const ScalarAcceleration< NumericType > & scalar_acceleration) inline
Definition at line 230 of file ScalarAcceleration.hpp.
References PhQ::DimensionalScalar< UnitType, NumericType >::Print().
operator<<() [54/139]
template<typename NumericType > std::ostream & PhQ::operator<< (std::ostream & stream, const ScalarAngularAcceleration< NumericType > & scalar_angular_acceleration) inline
Definition at line 215 of file ScalarAngularAcceleration.hpp.
References PhQ::DimensionalScalar< UnitType, NumericType >::Print().
operator<<() [55/139]
template<typename NumericType > std::ostream & PhQ::operator<< (std::ostream & stream, const ScalarDisplacementGradient< NumericType > & scalar_displacement_gradient) inline
Definition at line 202 of file ScalarDisplacementGradient.hpp.
References PhQ::DimensionlessScalar< NumericType >::Print().
operator<<() [56/139]
template<typename NumericType > std::ostream & PhQ::operator<< (std::ostream & stream, const ScalarForce< NumericType > & scalar_force) inline
Definition at line 219 of file ScalarForce.hpp.
References PhQ::DimensionalScalar< UnitType, NumericType >::Print().
operator<<() [57/139]
template<typename NumericType > std::ostream & PhQ::operator<< (std::ostream & stream, const ScalarHeatFlux< NumericType > & scalar_heat_flux) inline
Definition at line 206 of file ScalarHeatFlux.hpp.
References PhQ::DimensionalScalar< UnitType, NumericType >::Print().
operator<<() [58/139]
template<typename NumericType > std::ostream & PhQ::operator<< (std::ostream & stream, const ScalarStrain< NumericType > & scalar_strain) inline
Definition at line 199 of file ScalarStrain.hpp.
References PhQ::DimensionlessScalar< NumericType >::Print().
operator<<() [59/139]
template<typename NumericType > std::ostream & PhQ::operator<< (std::ostream & stream, const ScalarStrainRate< NumericType > & scalar_strain_rate) inline
Definition at line 202 of file ScalarStrainRate.hpp.
References PhQ::DimensionalScalar< UnitType, NumericType >::Print().
operator<<() [60/139]
template<typename NumericType > std::ostream & PhQ::operator<< (std::ostream & stream, const ScalarStress< NumericType > & scalar_stress) inline
Definition at line 180 of file ScalarStress.hpp.
References PhQ::DimensionalScalar< UnitType, NumericType >::Print().
operator<<() [61/139]
template<typename NumericType > std::ostream & PhQ::operator<< (std::ostream & stream, const ScalarTemperatureGradient< NumericType > & scalar_temperature_gradient) inline
Definition at line 230 of file ScalarTemperatureGradient.hpp.
References PhQ::DimensionalScalar< UnitType, NumericType >::Print().
operator<<() [62/139]
template<typename NumericType > std::ostream & PhQ::operator<< (std::ostream & stream, const ScalarThermalConductivity< NumericType > & thermal_conductivity_scalar) inline
Definition at line 228 of file ScalarThermalConductivity.hpp.
References PhQ::DimensionalScalar< UnitType, NumericType >::Print().
operator<<() [63/139]
template<typename NumericType > std::ostream & PhQ::operator<< (std::ostream & stream, const ScalarTraction< NumericType > & static_pressure) inline
Definition at line 214 of file ScalarTraction.hpp.
References PhQ::DimensionalScalar< UnitType, NumericType >::Print().
operator<<() [64/139]
template<typename NumericType > std::ostream & PhQ::operator<< (std::ostream & stream, const ScalarVelocityGradient< NumericType > & scalar_velocity_gradient) inline
Definition at line 208 of file ScalarVelocityGradient.hpp.
References PhQ::DimensionalScalar< UnitType, NumericType >::Print().
operator<<() [65/139]
template<typename NumericType > std::ostream & PhQ::operator<< (std::ostream & stream, const ShearModulus< NumericType > & shear_modulus) inline
Definition at line 177 of file ShearModulus.hpp.
References PhQ::DimensionalScalar< UnitType, NumericType >::Print().
operator<<() [66/139]
template<typename NumericType > std::ostream & PhQ::operator<< (std::ostream & stream, const SolidAngle< NumericType > & solid_angle) inline
Definition at line 172 of file SolidAngle.hpp.
References PhQ::DimensionalScalar< UnitType, NumericType >::Print().
operator<<() [67/139]
template<typename NumericType > std::ostream & PhQ::operator<< (std::ostream & stream, const SoundSpeed< NumericType > & sound_speed) inline
Definition at line 228 of file SoundSpeed.hpp.
References PhQ::DimensionalScalar< UnitType, NumericType >::Print().
operator<<() [68/139]
template<typename NumericType > std::ostream & PhQ::operator<< (std::ostream & stream, const SpecificEnergy< NumericType > & specific_energy) inline
Definition at line 208 of file SpecificEnergy.hpp.
References PhQ::DimensionalScalar< UnitType, NumericType >::Print().
operator<<() [69/139]
template<typename NumericType > std::ostream & PhQ::operator<< (std::ostream & stream, const SpecificGasConstant< NumericType > & specific_gas_constant) inline
Definition at line 225 of file SpecificGasConstant.hpp.
References PhQ::DimensionalScalar< UnitType, NumericType >::Print().
operator<<() [70/139]
template<typename NumericType > std::ostream & PhQ::operator<< (std::ostream & stream, const SpecificIsobaricHeatCapacity< NumericType > & specific_isobaric_heat_capacity) inline
Definition at line 279 of file SpecificIsobaricHeatCapacity.hpp.
References PhQ::DimensionalScalar< UnitType, NumericType >::Print().
operator<<() [71/139]
template<typename NumericType > std::ostream & PhQ::operator<< (std::ostream & stream, const SpecificIsochoricHeatCapacity< NumericType > & specific_isochoric_heat_capacity) inline
Definition at line 232 of file SpecificIsochoricHeatCapacity.hpp.
References PhQ::DimensionalScalar< UnitType, NumericType >::Print().
operator<<() [72/139]
template<typename NumericType > std::ostream & PhQ::operator<< (std::ostream & stream, const SpecificPower< NumericType > & specific_power) inline
Definition at line 212 of file SpecificPower.hpp.
References PhQ::DimensionalScalar< UnitType, NumericType >::Print().
operator<<() [73/139]
template<typename NumericType > std::ostream & PhQ::operator<< (std::ostream & stream, const Speed< NumericType > & speed) inline
Definition at line 320 of file Speed.hpp.
References PhQ::DimensionalScalar< UnitType, NumericType >::Print().
operator<<() [74/139]
template<typename NumericType > std::ostream & PhQ::operator<< (std::ostream & stream, const StaticKinematicPressure< NumericType > & static_kinematic_pressure) inline
Definition at line 211 of file StaticKinematicPressure.hpp.
References PhQ::DimensionalScalar< UnitType, NumericType >::Print().
operator<<() [75/139]
template<typename NumericType > std::ostream & PhQ::operator<< (std::ostream & stream, const StaticPressure< NumericType > & static_pressure) inline
Definition at line 230 of file StaticPressure.hpp.
References PhQ::DimensionalScalar< UnitType, NumericType >::Print().
operator<<() [76/139]
template<typename NumericType > std::ostream & PhQ::operator<< (std::ostream & stream, const Strain< NumericType > & strain) inline
Definition at line 259 of file Strain.hpp.
References PhQ::DimensionlessSymmetricDyad< NumericType >::Print().
operator<<() [77/139]
template<typename NumericType > std::ostream & PhQ::operator<< (std::ostream & stream, const StrainRate< NumericType > & strain_rate) inline
Definition at line 274 of file StrainRate.hpp.
References PhQ::DimensionalSymmetricDyad< UnitType, NumericType >::Print().
operator<<() [78/139]
template<typename NumericType > std::ostream & PhQ::operator<< (std::ostream & stream, const Stress< NumericType > & stress) inline
Definition at line 285 of file Stress.hpp.
References PhQ::DimensionalSymmetricDyad< UnitType, NumericType >::Print().
operator<<() [79/139]
template<typename NumericType > std::ostream & PhQ::operator<< (std::ostream & stream, const SubstanceAmount< NumericType > & substance_amount) inline
Definition at line 175 of file SubstanceAmount.hpp.
References PhQ::DimensionalScalar< UnitType, NumericType >::Print().
operator<<() [80/139]
template<typename NumericType > std::ostream & PhQ::operator<< (std::ostream & stream, const SymmetricDyad< NumericType > & symmetric) inline
Definition at line 593 of file SymmetricDyad.hpp.
References PhQ::SymmetricDyad< NumericType >::Print().
operator<<() [81/139]
template<typename NumericType > std::ostream & PhQ::operator<< (std::ostream & stream, const Temperature< NumericType > & temperature) inline
Definition at line 196 of file Temperature.hpp.
References PhQ::DimensionalScalar< UnitType, NumericType >::Print().
operator<<() [82/139]
template<typename NumericType > std::ostream & PhQ::operator<< (std::ostream & stream, const TemperatureDifference< NumericType > & temperature_difference) inline
Definition at line 232 of file TemperatureDifference.hpp.
References PhQ::DimensionalScalar< UnitType, NumericType >::Print().
operator<<() [83/139]
template<typename NumericType > std::ostream & PhQ::operator<< (std::ostream & stream, const TemperatureGradient< NumericType > & temperature_gradient) inline
Definition at line 257 of file TemperatureGradient.hpp.
References PhQ::DimensionalVector< UnitType, NumericType >::Print().
operator<<() [84/139]
template<typename NumericType > std::ostream & PhQ::operator<< (std::ostream & stream, const ThermalConductivity< NumericType > & thermal_conductivity) inline
Definition at line 258 of file ThermalConductivity.hpp.
References PhQ::DimensionalSymmetricDyad< UnitType, NumericType >::Print().
operator<<() [85/139]
template<typename NumericType > std::ostream & PhQ::operator<< (std::ostream & stream, const ThermalDiffusivity< NumericType > & thermal_diffusivity) inline
Definition at line 202 of file ThermalDiffusivity.hpp.
References PhQ::DimensionalScalar< UnitType, NumericType >::Print().
operator<<() [86/139]
template<typename NumericType > std::ostream & PhQ::operator<< (std::ostream & stream, const Time< NumericType > & time) inline
Definition at line 392 of file Time.hpp.
References PhQ::DimensionalScalar< UnitType, NumericType >::Print().
operator<<() [87/139]
template<typename NumericType > std::ostream & PhQ::operator<< (std::ostream & stream, const TotalKinematicPressure< NumericType > & total_kinematic_pressure) inline
Definition at line 207 of file TotalKinematicPressure.hpp.
References PhQ::DimensionalScalar< UnitType, NumericType >::Print().
operator<<() [88/139]
template<typename NumericType > std::ostream & PhQ::operator<< (std::ostream & stream, const TotalPressure< NumericType > & total_pressure) inline
Definition at line 206 of file TotalPressure.hpp.
References PhQ::DimensionalScalar< UnitType, NumericType >::Print().
operator<<() [89/139]
template<typename NumericType > std::ostream & PhQ::operator<< (std::ostream & stream, const Traction< NumericType > & traction) inline
Definition at line 257 of file Traction.hpp.
References PhQ::DimensionalVector< UnitType, NumericType >::Print().
operator<<() [90/139]
template<typename NumericType > std::ostream & PhQ::operator<< (std::ostream & stream, const TransportEnergyConsumption< NumericType > & transport_energy_consumption) inline
Definition at line 208 of file TransportEnergyConsumption.hpp.
References PhQ::DimensionalScalar< UnitType, NumericType >::Print().
operator<<() [91/139]
template<typename NumericType > std::ostream & PhQ::operator<< (std::ostream & stream, const typename ConstitutiveModel::CompressibleNewtonianFluid< NumericType > & model) inline
Definition at line 393 of file CompressibleNewtonianFluid.hpp.
References PhQ::ConstitutiveModel::CompressibleNewtonianFluid< NumericType >::Print().
operator<<() [92/139]
template<typename NumericType > std::ostream & PhQ::operator<< (std::ostream & stream, const typename ConstitutiveModel::ElasticIsotropicSolid< NumericType > & model) inline
Definition at line 636 of file ElasticIsotropicSolid.hpp.
References PhQ::ConstitutiveModel::ElasticIsotropicSolid< NumericType >::Print().
operator<<() [93/139]
template<typename NumericType > std::ostream & PhQ::operator<< (std::ostream & stream, const typename ConstitutiveModel::IncompressibleNewtonianFluid< NumericType > & model) inline
Definition at line 297 of file IncompressibleNewtonianFluid.hpp.
References PhQ::ConstitutiveModel::IncompressibleNewtonianFluid< NumericType >::Print().
operator<<() [94/139]
std::ostream & PhQ::operator<< (std::ostream & stream, const Unit::Acceleration unit) inline
Definition at line 187 of file Acceleration.hpp.
References Abbreviation().
operator<<() [95/139]
std::ostream & PhQ::operator<< (std::ostream & stream, const Unit::Angle unit) inline
Definition at line 80 of file Angle.hpp.
References Abbreviation().
operator<<() [96/139]
std::ostream & PhQ::operator<< (std::ostream & stream, const Unit::AngularAcceleration unit) inline
Definition at line 115 of file AngularAcceleration.hpp.
References Abbreviation().
operator<<() [97/139]
std::ostream & PhQ::operator<< (std::ostream & stream, const Unit::AngularSpeed unit) inline
Definition at line 115 of file AngularSpeed.hpp.
References Abbreviation().
operator<<() [98/139]
std::ostream & PhQ::operator<< (std::ostream & stream, const Unit::Area unit) inline
Definition at line 114 of file Area.hpp.
References Abbreviation().
operator<<() [99/139]
std::ostream & PhQ::operator<< (std::ostream & stream, const Unit::Diffusivity unit) inline
Definition at line 115 of file Diffusivity.hpp.
References Abbreviation().
operator<<() [100/139]
std::ostream & PhQ::operator<< (std::ostream & stream, const Unit::DynamicViscosity unit) inline
Definition at line 91 of file DynamicViscosity.hpp.
References Abbreviation().
operator<<() [101/139]
std::ostream & PhQ::operator<< (std::ostream & stream, const Unit::ElectricCharge unit) inline
Definition at line 145 of file ElectricCharge.hpp.
References Abbreviation().
operator<<() [102/139]
std::ostream & PhQ::operator<< (std::ostream & stream, const Unit::ElectricCurrent unit) inline
Definition at line 103 of file ElectricCurrent.hpp.
References Abbreviation().
operator<<() [103/139]
std::ostream & PhQ::operator<< (std::ostream & stream, const Unit::Energy unit) inline
Definition at line 165 of file Energy.hpp.
References Abbreviation().
operator<<() [104/139]
std::ostream & PhQ::operator<< (std::ostream & stream, const Unit::EnergyFlux unit) inline
Definition at line 82 of file EnergyFlux.hpp.
References Abbreviation().
operator<<() [105/139]
std::ostream & PhQ::operator<< (std::ostream & stream, const Unit::Force unit) inline
Definition at line 96 of file Force.hpp.
References Abbreviation().
operator<<() [106/139]
std::ostream & PhQ::operator<< (std::ostream & stream, const Unit::Frequency unit) inline
Definition at line 87 of file Frequency.hpp.
References Abbreviation().
operator<<() [107/139]
std::ostream & PhQ::operator<< (std::ostream & stream, const Unit::HeatCapacity unit) inline
Definition at line 82 of file HeatCapacity.hpp.
References Abbreviation().
operator<<() [108/139]
std::ostream & PhQ::operator<< (std::ostream & stream, const Unit::Length unit) inline
Definition at line 108 of file Length.hpp.
References Abbreviation().
operator<<() [109/139]
std::ostream & PhQ::operator<< (std::ostream & stream, const Unit::Mass unit) inline
Definition at line 84 of file Mass.hpp.
References Abbreviation().
operator<<() [110/139]
std::ostream & PhQ::operator<< (std::ostream & stream, const Unit::MassDensity unit) inline
Definition at line 89 of file MassDensity.hpp.
References Abbreviation().
operator<<() [111/139]
std::ostream & PhQ::operator<< (std::ostream & stream, const Unit::MassRate unit) inline
Definition at line 114 of file MassRate.hpp.
References Abbreviation().
operator<<() [112/139]
std::ostream & PhQ::operator<< (std::ostream & stream, const Unit::Memory unit) inline
Definition at line 131 of file Memory.hpp.
References Abbreviation().
operator<<() [113/139]
std::ostream & PhQ::operator<< (std::ostream & stream, const Unit::MemoryRate unit) inline
Definition at line 268 of file MemoryRate.hpp.
References Abbreviation().
operator<<() [114/139]
std::ostream & PhQ::operator<< (std::ostream & stream, const Unit::Power unit) inline
Definition at line 96 of file Power.hpp.
References Abbreviation().
operator<<() [115/139]
std::ostream & PhQ::operator<< (std::ostream & stream, const Unit::Pressure unit) inline
Definition at line 93 of file Pressure.hpp.
References Abbreviation().
operator<<() [116/139]
std::ostream & PhQ::operator<< (std::ostream & stream, const Unit::ReciprocalTemperature unit) inline
Definition at line 82 of file ReciprocalTemperature.hpp.
References Abbreviation().
operator<<() [117/139]
std::ostream & PhQ::operator<< (std::ostream & stream, const Unit::SolidAngle unit) inline
Definition at line 79 of file SolidAngle.hpp.
References Abbreviation().
operator<<() [118/139]
std::ostream & PhQ::operator<< (std::ostream & stream, const Unit::SpecificEnergy unit) inline
Definition at line 82 of file SpecificEnergy.hpp.
References Abbreviation().
operator<<() [119/139]
std::ostream & PhQ::operator<< (std::ostream & stream, const Unit::SpecificHeatCapacity unit) inline
Definition at line 83 of file SpecificHeatCapacity.hpp.
References Abbreviation().
operator<<() [120/139]
std::ostream & PhQ::operator<< (std::ostream & stream, const Unit::SpecificPower unit) inline
Definition at line 82 of file SpecificPower.hpp.
References Abbreviation().
operator<<() [121/139]
std::ostream & PhQ::operator<< (std::ostream & stream, const Unit::Speed unit) inline
Definition at line 186 of file Speed.hpp.
References Abbreviation().
operator<<() [122/139]
std::ostream & PhQ::operator<< (std::ostream & stream, const Unit::SubstanceAmount unit) inline
Definition at line 85 of file SubstanceAmount.hpp.
References Abbreviation().
operator<<() [123/139]
std::ostream & PhQ::operator<< (std::ostream & stream, const Unit::Temperature unit) inline
Definition at line 83 of file Temperature.hpp.
References Abbreviation().
operator<<() [124/139]
std::ostream & PhQ::operator<< (std::ostream & stream, const Unit::TemperatureDifference unit) inline
Definition at line 84 of file TemperatureDifference.hpp.
References Abbreviation().
operator<<() [125/139]
std::ostream & PhQ::operator<< (std::ostream & stream, const Unit::TemperatureGradient unit) inline
Definition at line 94 of file TemperatureGradient.hpp.
References Abbreviation().
operator<<() [126/139]
std::ostream & PhQ::operator<< (std::ostream & stream, const Unit::ThermalConductivity unit) inline
Definition at line 79 of file ThermalConductivity.hpp.
References Abbreviation().
operator<<() [127/139]
std::ostream & PhQ::operator<< (std::ostream & stream, const Unit::Time unit) inline
Definition at line 87 of file Time.hpp.
References Abbreviation().
operator<<() [128/139]
std::ostream & PhQ::operator<< (std::ostream & stream, const Unit::TransportEnergyConsumption unit) inline
Definition at line 127 of file TransportEnergyConsumption.hpp.
References Abbreviation().
operator<<() [129/139]
std::ostream & PhQ::operator<< (std::ostream & stream, const Unit::Volume unit) inline
Definition at line 114 of file Volume.hpp.
References Abbreviation().
operator<<() [130/139]
std::ostream & PhQ::operator<< (std::ostream & stream, const Unit::VolumeRate unit) inline
Definition at line 205 of file VolumeRate.hpp.
References Abbreviation().
operator<<() [131/139]
std::ostream & PhQ::operator<< (std::ostream & stream, const UnitSystem unit_system) inline
Definition at line 242 of file UnitSystem.hpp.
References Abbreviation().
operator<<() [132/139]
template<typename NumericType > std::ostream & PhQ::operator<< (std::ostream & stream, const Vector< NumericType > & vector) inline
Definition at line 401 of file Vector.hpp.
References PhQ::Vector< NumericType >::Print().
operator<<() [133/139]
template<typename NumericType > std::ostream & PhQ::operator<< (std::ostream & stream, const VectorArea< NumericType > & vector_area) inline
Definition at line 229 of file VectorArea.hpp.
References PhQ::DimensionalVector< UnitType, NumericType >::Print().
operator<<() [134/139]
template<typename NumericType > std::ostream & PhQ::operator<< (std::ostream & stream, const Velocity< NumericType > & velocity) inline
Definition at line 274 of file Velocity.hpp.
References PhQ::DimensionalVector< UnitType, NumericType >::Print().
operator<<() [135/139]
template<typename NumericType > std::ostream & PhQ::operator<< (std::ostream & stream, const VelocityGradient< NumericType > & velocity_gradient) inline
Definition at line 287 of file VelocityGradient.hpp.
References PhQ::DimensionalDyad< UnitType, NumericType >::Print().
operator<<() [136/139]
template<typename NumericType > std::ostream & PhQ::operator<< (std::ostream & stream, const Volume< NumericType > & volume) inline
Definition at line 223 of file Volume.hpp.
References PhQ::DimensionalScalar< UnitType, NumericType >::Print().
operator<<() [137/139]
template<typename NumericType > std::ostream & PhQ::operator<< (std::ostream & stream, const VolumeRate< NumericType > & volume_rate) inline
Definition at line 210 of file VolumeRate.hpp.
References PhQ::DimensionalScalar< UnitType, NumericType >::Print().
operator<<() [138/139]
template<typename NumericType > std::ostream & PhQ::operator<< (std::ostream & stream, const VolumetricThermalExpansionCoefficient< NumericType > & volumetric_thermal_expansion_coefficient) inline
Definition at line 213 of file VolumetricThermalExpansionCoefficient.hpp.
References PhQ::DimensionalScalar< UnitType, NumericType >::Print().
operator<<() [139/139]
template<typename NumericType > std::ostream & PhQ::operator<< (std::ostream & stream, const YoungModulus< NumericType > & young_modulus) inline
Definition at line 175 of file YoungModulus.hpp.
References PhQ::DimensionalScalar< UnitType, NumericType >::Print().
operator<=() [1/100]
template<typename NumericType > constexpr bool PhQ::operator<= (const Acceleration< NumericType > & left, const Acceleration< NumericType > & right) inline constexpr noexcept
Definition at line 253 of file Acceleration.hpp.
operator<=() [2/100]
template<typename NumericType > constexpr bool PhQ::operator<= (const Angle< NumericType > & left, const Angle< NumericType > & right) inline constexpr noexcept
Definition at line 370 of file Angle.hpp.
operator<=() [3/100]
template<typename NumericType > constexpr bool PhQ::operator<= (const AngularSpeed< NumericType > & left, const AngularSpeed< NumericType > & right) inline constexpr noexcept
Definition at line 210 of file AngularSpeed.hpp.
operator<=() [4/100]
template<typename NumericType > constexpr bool PhQ::operator<= (const Area< NumericType > & left, const Area< NumericType > & right) inline constexpr noexcept
Definition at line 219 of file Area.hpp.
operator<=() [5/100]
template<typename NumericType > constexpr bool PhQ::operator<= (const BulkDynamicViscosity< NumericType > & left, const BulkDynamicViscosity< NumericType > & right) inline constexpr noexcept
Definition at line 168 of file BulkDynamicViscosity.hpp.
operator<=() [6/100]
constexpr bool PhQ::operator<= (const Dimensions & left, const Dimensions & right) inline constexpr noexcept
Definition at line 391 of file Dimensions.hpp.
operator<=() [7/100]
template<typename NumericType > constexpr bool PhQ::operator<= (const Direction< NumericType > & left, const Direction< NumericType > & right) inline constexpr noexcept
Definition at line 353 of file Direction.hpp.
operator<=() [8/100]
template<typename NumericType > constexpr bool PhQ::operator<= (const Displacement< NumericType > & left, const Displacement< NumericType > & right) inline constexpr noexcept
Definition at line 269 of file Displacement.hpp.
operator<=() [9/100]
template<typename NumericType > constexpr bool PhQ::operator<= (const DisplacementGradient< NumericType > & left, const DisplacementGradient< NumericType > & right) inline constexpr noexcept
Definition at line 239 of file DisplacementGradient.hpp.
operator<=() [10/100]
template<typename NumericType > constexpr bool PhQ::operator<= (const Dyad< NumericType > & left, const Dyad< NumericType > & right) inline constexpr noexcept
Definition at line 556 of file Dyad.hpp.
operator<=() [11/100]
template<typename NumericType > constexpr bool PhQ::operator<= (const DynamicKinematicPressure< NumericType > & left, const DynamicKinematicPressure< NumericType > & right) inline constexpr noexcept
Definition at line 198 of file DynamicKinematicPressure.hpp.
operator<=() [12/100]
template<typename NumericType > constexpr bool PhQ::operator<= (const DynamicPressure< NumericType > & left, const DynamicPressure< NumericType > & right) inline constexpr noexcept
Definition at line 195 of file DynamicPressure.hpp.
operator<=() [13/100]
template<typename NumericType > constexpr bool PhQ::operator<= (const DynamicViscosity< NumericType > & left, const DynamicViscosity< NumericType > & right) inline constexpr noexcept
Definition at line 210 of file DynamicViscosity.hpp.
operator<=() [14/100]
template<typename NumericType > constexpr bool PhQ::operator<= (const ElectricCharge< NumericType > & left, const ElectricCharge< NumericType > & right) inline constexpr noexcept
Definition at line 190 of file ElectricCharge.hpp.
operator<=() [15/100]
template<typename NumericType > constexpr bool PhQ::operator<= (const ElectricCurrent< NumericType > & left, const ElectricCurrent< NumericType > & right) inline constexpr noexcept
Definition at line 192 of file ElectricCurrent.hpp.
operator<=() [16/100]
template<typename NumericType > constexpr bool PhQ::operator<= (const Energy< NumericType > & left, const Energy< NumericType > & right) inline constexpr noexcept
Definition at line 225 of file Energy.hpp.
operator<=() [17/100]
template<typename NumericType > constexpr bool PhQ::operator<= (const Force< NumericType > & left, const Force< NumericType > & right) inline constexpr noexcept
Definition at line 234 of file Force.hpp.
operator<=() [18/100]
template<typename NumericType > constexpr bool PhQ::operator<= (const Frequency< NumericType > & left, const Frequency< NumericType > & right) inline constexpr noexcept
Definition at line 262 of file Frequency.hpp.
operator<=() [19/100]
template<typename NumericType > constexpr bool PhQ::operator<= (const GasConstant< NumericType > & left, const GasConstant< NumericType > & right) inline constexpr noexcept
Definition at line 200 of file GasConstant.hpp.
operator<=() [20/100]
template<typename NumericType > constexpr bool PhQ::operator<= (const HeatCapacityRatio< NumericType > & left, const HeatCapacityRatio< NumericType > & right) inline constexpr noexcept
Definition at line 219 of file HeatCapacityRatio.hpp.
operator<=() [21/100]
template<typename NumericType > constexpr bool PhQ::operator<= (const HeatFlux< NumericType > & left, const HeatFlux< NumericType > & right) inline constexpr noexcept
Definition at line 247 of file HeatFlux.hpp.
operator<=() [22/100]
template<typename NumericType > constexpr bool PhQ::operator<= (const IsentropicBulkModulus< NumericType > & left, const IsentropicBulkModulus< NumericType > & right) inline constexpr noexcept
Definition at line 182 of file IsentropicBulkModulus.hpp.
operator<=() [23/100]
template<typename NumericType > constexpr bool PhQ::operator<= (const IsobaricHeatCapacity< NumericType > & left, const IsobaricHeatCapacity< NumericType > & right) inline constexpr noexcept
Definition at line 213 of file IsobaricHeatCapacity.hpp.
operator<=() [24/100]
template<typename NumericType > constexpr bool PhQ::operator<= (const IsochoricHeatCapacity< NumericType > & left, const IsochoricHeatCapacity< NumericType > & right) inline constexpr noexcept
Definition at line 201 of file IsochoricHeatCapacity.hpp.
operator<=() [25/100]
template<typename NumericType > constexpr bool PhQ::operator<= (const IsothermalBulkModulus< NumericType > & left, const IsothermalBulkModulus< NumericType > & right) inline constexpr noexcept
Definition at line 169 of file IsothermalBulkModulus.hpp.
operator<=() [26/100]
template<typename NumericType > constexpr bool PhQ::operator<= (const KinematicViscosity< NumericType > & left, const KinematicViscosity< NumericType > & right) inline constexpr noexcept
Definition at line 212 of file KinematicViscosity.hpp.
operator<=() [27/100]
template<typename NumericType > constexpr bool PhQ::operator<= (const LameFirstModulus< NumericType > & left, const LameFirstModulus< NumericType > & right) inline constexpr noexcept
Definition at line 169 of file LameFirstModulus.hpp.
operator<=() [28/100]
template<typename NumericType > constexpr bool PhQ::operator<= (const Length< NumericType > & left, const Length< NumericType > & right) inline constexpr noexcept
Definition at line 288 of file Length.hpp.
operator<=() [29/100]
template<typename NumericType > constexpr bool PhQ::operator<= (const LinearThermalExpansionCoefficient< NumericType > & left, const LinearThermalExpansionCoefficient< NumericType > & right) inline constexpr noexcept
Definition at line 199 of file LinearThermalExpansionCoefficient.hpp.
operator<=() [30/100]
template<typename NumericType > constexpr bool PhQ::operator<= (const MachNumber< NumericType > & left, const MachNumber< NumericType > & right) inline constexpr noexcept
Definition at line 154 of file MachNumber.hpp.
operator<=() [31/100]
template<typename NumericType > constexpr bool PhQ::operator<= (const Mass< NumericType > & left, const Mass< NumericType > & right) inline constexpr noexcept
Definition at line 274 of file Mass.hpp.
operator<=() [32/100]
template<typename NumericType > constexpr bool PhQ::operator<= (const MassDensity< NumericType > & left, const MassDensity< NumericType > & right) inline constexpr noexcept
Definition at line 253 of file MassDensity.hpp.
operator<=() [33/100]
template<typename NumericType > constexpr bool PhQ::operator<= (const MassRate< NumericType > & left, const MassRate< NumericType > & right) inline constexpr noexcept
Definition at line 199 of file MassRate.hpp.
operator<=() [34/100]
template<typename NumericType > constexpr bool PhQ::operator<= (const Memory< NumericType > & left, const Memory< NumericType > & right) inline constexpr noexcept
Definition at line 185 of file Memory.hpp.
operator<=() [35/100]
template<typename NumericType > constexpr bool PhQ::operator<= (const MemoryRate< NumericType > & left, const MemoryRate< NumericType > & right) inline constexpr noexcept
Definition at line 183 of file MemoryRate.hpp.
operator<=() [36/100]
template<typename NumericType > constexpr bool PhQ::operator<= (const PlanarAcceleration< NumericType > & left, const PlanarAcceleration< NumericType > & right) inline constexpr noexcept
Definition at line 252 of file PlanarAcceleration.hpp.
operator<=() [37/100]
template<typename NumericType > constexpr bool PhQ::operator<= (const PlanarDirection< NumericType > & left, const PlanarDirection< NumericType > & right) inline constexpr noexcept
Definition at line 357 of file PlanarDirection.hpp.
operator<=() [38/100]
template<typename NumericType > constexpr bool PhQ::operator<= (const PlanarDisplacement< NumericType > & left, const PlanarDisplacement< NumericType > & right) inline constexpr noexcept
Definition at line 281 of file PlanarDisplacement.hpp.
operator<=() [39/100]
template<typename NumericType > constexpr bool PhQ::operator<= (const PlanarForce< NumericType > & left, const PlanarForce< NumericType > & right) inline constexpr noexcept
Definition at line 231 of file PlanarForce.hpp.
operator<=() [40/100]
template<typename NumericType > constexpr bool PhQ::operator<= (const PlanarHeatFlux< NumericType > & left, const PlanarHeatFlux< NumericType > & right) inline constexpr noexcept
Definition at line 249 of file PlanarHeatFlux.hpp.
operator<=() [41/100]
template<typename NumericType > constexpr bool PhQ::operator<= (const PlanarPosition< NumericType > & left, const PlanarPosition< NumericType > & right) inline constexpr noexcept
Definition at line 254 of file PlanarPosition.hpp.
operator<=() [42/100]
template<typename NumericType > constexpr bool PhQ::operator<= (const PlanarTemperatureGradient< NumericType > & left, const PlanarTemperatureGradient< NumericType > & right) inline constexpr noexcept
Definition at line 247 of file PlanarTemperatureGradient.hpp.
operator<=() [43/100]
template<typename NumericType > constexpr bool PhQ::operator<= (const PlanarTraction< NumericType > & left, const PlanarTraction< NumericType > & right) inline constexpr noexcept
Definition at line 248 of file PlanarTraction.hpp.
operator<=() [44/100]
template<typename NumericType > constexpr bool PhQ::operator<= (const PlanarVector< NumericType > & left, const PlanarVector< NumericType > & right) inline constexpr noexcept
Definition at line 327 of file PlanarVector.hpp.
operator<=() [45/100]
template<typename NumericType > constexpr bool PhQ::operator<= (const PlanarVelocity< NumericType > & left, const PlanarVelocity< NumericType > & right) inline constexpr noexcept
Definition at line 267 of file PlanarVelocity.hpp.
operator<=() [46/100]
template<typename NumericType > constexpr bool PhQ::operator<= (const PoissonRatio< NumericType > & left, const PoissonRatio< NumericType > & right) inline constexpr noexcept
Definition at line 147 of file PoissonRatio.hpp.
operator<=() [47/100]
template<typename NumericType > constexpr bool PhQ::operator<= (const Position< NumericType > & left, const Position< NumericType > & right) inline constexpr noexcept
Definition at line 249 of file Position.hpp.
operator<=() [48/100]
template<typename NumericType > constexpr bool PhQ::operator<= (const Power< NumericType > & left, const Power< NumericType > & right) inline constexpr noexcept
Definition at line 202 of file Power.hpp.
operator<=() [49/100]
template<typename NumericType > constexpr bool PhQ::operator<= (const PrandtlNumber< NumericType > & left, const PrandtlNumber< NumericType > & right) inline constexpr noexcept
Definition at line 200 of file PrandtlNumber.hpp.
operator<=() [50/100]
template<typename NumericType > constexpr bool PhQ::operator<= (const PWaveModulus< NumericType > & left, const PWaveModulus< NumericType > & right) inline constexpr noexcept
Definition at line 163 of file PWaveModulus.hpp.
operator<=() [51/100]
template<typename NumericType > constexpr bool PhQ::operator<= (const ReynoldsNumber< NumericType > & left, const ReynoldsNumber< NumericType > & right) inline constexpr noexcept
Definition at line 210 of file ReynoldsNumber.hpp.
operator<=() [52/100]
template<typename NumericType > constexpr bool PhQ::operator<= (const ScalarAcceleration< NumericType > & left, const ScalarAcceleration< NumericType > & right) inline constexpr noexcept
Definition at line 218 of file ScalarAcceleration.hpp.
operator<=() [53/100]
template<typename NumericType > constexpr bool PhQ::operator<= (const ScalarAngularAcceleration< NumericType > & left, const ScalarAngularAcceleration< NumericType > & right) inline constexpr noexcept
Definition at line 203 of file ScalarAngularAcceleration.hpp.
operator<=() [54/100]
template<typename NumericType > constexpr bool PhQ::operator<= (const ScalarDisplacementGradient< NumericType > & left, const ScalarDisplacementGradient< NumericType > & right) inline constexpr noexcept
Definition at line 190 of file ScalarDisplacementGradient.hpp.
operator<=() [55/100]
template<typename NumericType > constexpr bool PhQ::operator<= (const ScalarForce< NumericType > & left, const ScalarForce< NumericType > & right) inline constexpr noexcept
Definition at line 207 of file ScalarForce.hpp.
operator<=() [56/100]
template<typename NumericType > constexpr bool PhQ::operator<= (const ScalarHeatFlux< NumericType > & left, const ScalarHeatFlux< NumericType > & right) inline constexpr noexcept
Definition at line 194 of file ScalarHeatFlux.hpp.
operator<=() [57/100]
template<typename NumericType > constexpr bool PhQ::operator<= (const ScalarStrain< NumericType > & left, const ScalarStrain< NumericType > & right) inline constexpr noexcept
Definition at line 187 of file ScalarStrain.hpp.
operator<=() [58/100]
template<typename NumericType > constexpr bool PhQ::operator<= (const ScalarStrainRate< NumericType > & left, const ScalarStrainRate< NumericType > & right) inline constexpr noexcept
Definition at line 190 of file ScalarStrainRate.hpp.
operator<=() [59/100]
template<typename NumericType > constexpr bool PhQ::operator<= (const ScalarStress< NumericType > & left, const ScalarStress< NumericType > & right) inline constexpr noexcept
Definition at line 168 of file ScalarStress.hpp.
operator<=() [60/100]
template<typename NumericType > constexpr bool PhQ::operator<= (const ScalarTemperatureGradient< NumericType > & left, const ScalarTemperatureGradient< NumericType > & right) inline constexpr noexcept
Definition at line 218 of file ScalarTemperatureGradient.hpp.
operator<=() [61/100]
template<typename NumericType > constexpr bool PhQ::operator<= (const ScalarThermalConductivity< NumericType > & left, const ScalarThermalConductivity< NumericType > & right) inline constexpr noexcept
Definition at line 216 of file ScalarThermalConductivity.hpp.
operator<=() [62/100]
template<typename NumericType > constexpr bool PhQ::operator<= (const ScalarTraction< NumericType > & left, const ScalarTraction< NumericType > & right) inline constexpr noexcept
Definition at line 202 of file ScalarTraction.hpp.
operator<=() [63/100]
template<typename NumericType > constexpr bool PhQ::operator<= (const ScalarVelocityGradient< NumericType > & left, const ScalarVelocityGradient< NumericType > & right) inline constexpr noexcept
Definition at line 196 of file ScalarVelocityGradient.hpp.
operator<=() [64/100]
template<typename NumericType > constexpr bool PhQ::operator<= (const ShearModulus< NumericType > & left, const ShearModulus< NumericType > & right) inline constexpr noexcept
Definition at line 165 of file ShearModulus.hpp.
operator<=() [65/100]
template<typename NumericType > constexpr bool PhQ::operator<= (const SolidAngle< NumericType > & left, const SolidAngle< NumericType > & right) inline constexpr noexcept
Definition at line 160 of file SolidAngle.hpp.
operator<=() [66/100]
template<typename NumericType > constexpr bool PhQ::operator<= (const SoundSpeed< NumericType > & left, const SoundSpeed< NumericType > & right) inline constexpr noexcept
Definition at line 216 of file SoundSpeed.hpp.
operator<=() [67/100]
template<typename NumericType > constexpr bool PhQ::operator<= (const SpecificEnergy< NumericType > & left, const SpecificEnergy< NumericType > & right) inline constexpr noexcept
Definition at line 196 of file SpecificEnergy.hpp.
operator<=() [68/100]
template<typename NumericType > constexpr bool PhQ::operator<= (const SpecificGasConstant< NumericType > & left, const SpecificGasConstant< NumericType > & right) inline constexpr noexcept
Definition at line 213 of file SpecificGasConstant.hpp.
operator<=() [69/100]
template<typename NumericType > constexpr bool PhQ::operator<= (const SpecificIsobaricHeatCapacity< NumericType > & left, const SpecificIsobaricHeatCapacity< NumericType > & right) inline constexpr noexcept
Definition at line 267 of file SpecificIsobaricHeatCapacity.hpp.
operator<=() [70/100]
template<typename NumericType > constexpr bool PhQ::operator<= (const SpecificIsochoricHeatCapacity< NumericType > & left, const SpecificIsochoricHeatCapacity< NumericType > & right) inline constexpr noexcept
Definition at line 220 of file SpecificIsochoricHeatCapacity.hpp.
operator<=() [71/100]
template<typename NumericType > constexpr bool PhQ::operator<= (const SpecificPower< NumericType > & left, const SpecificPower< NumericType > & right) inline constexpr noexcept
Definition at line 200 of file SpecificPower.hpp.
operator<=() [72/100]
template<typename NumericType > constexpr bool PhQ::operator<= (const Speed< NumericType > & left, const Speed< NumericType > & right) inline constexpr noexcept
Definition at line 308 of file Speed.hpp.
operator<=() [73/100]
template<typename NumericType > constexpr bool PhQ::operator<= (const StaticKinematicPressure< NumericType > & left, const StaticKinematicPressure< NumericType > & right) inline constexpr noexcept
Definition at line 199 of file StaticKinematicPressure.hpp.
operator<=() [74/100]
template<typename NumericType > constexpr bool PhQ::operator<= (const StaticPressure< NumericType > & left, const StaticPressure< NumericType > & right) inline constexpr noexcept
Definition at line 218 of file StaticPressure.hpp.
operator<=() [75/100]
template<typename NumericType > constexpr bool PhQ::operator<= (const Strain< NumericType > & left, const Strain< NumericType > & right) inline constexpr noexcept
Definition at line 247 of file Strain.hpp.
operator<=() [76/100]
template<typename NumericType > constexpr bool PhQ::operator<= (const StrainRate< NumericType > & left, const StrainRate< NumericType > & right) inline constexpr noexcept
Definition at line 262 of file StrainRate.hpp.
operator<=() [77/100]
template<typename NumericType > constexpr bool PhQ::operator<= (const Stress< NumericType > & left, const Stress< NumericType > & right) inline constexpr noexcept
Definition at line 273 of file Stress.hpp.
operator<=() [78/100]
template<typename NumericType > constexpr bool PhQ::operator<= (const SubstanceAmount< NumericType > & left, const SubstanceAmount< NumericType > & right) inline constexpr noexcept
Definition at line 163 of file SubstanceAmount.hpp.
operator<=() [79/100]
template<typename NumericType > constexpr bool PhQ::operator<= (const SymmetricDyad< NumericType > & left, const SymmetricDyad< NumericType > & right) inline constexpr noexcept
Definition at line 497 of file SymmetricDyad.hpp.
operator<=() [80/100]
template<typename NumericType > constexpr bool PhQ::operator<= (const Temperature< NumericType > & left, const Temperature< NumericType > & right) inline constexpr noexcept
Definition at line 184 of file Temperature.hpp.
operator<=() [81/100]
template<typename NumericType > constexpr bool PhQ::operator<= (const TemperatureDifference< NumericType > & left, const TemperatureDifference< NumericType > & right) inline constexpr noexcept
Definition at line 220 of file TemperatureDifference.hpp.
operator<=() [82/100]
template<typename NumericType > constexpr bool PhQ::operator<= (const TemperatureGradient< NumericType > & left, const TemperatureGradient< NumericType > & right) inline constexpr noexcept
Definition at line 245 of file TemperatureGradient.hpp.
operator<=() [83/100]
template<typename NumericType > constexpr bool PhQ::operator<= (const ThermalConductivity< NumericType > & left, const ThermalConductivity< NumericType > & right) inline constexpr noexcept
Definition at line 246 of file ThermalConductivity.hpp.
operator<=() [84/100]
template<typename NumericType > constexpr bool PhQ::operator<= (const ThermalDiffusivity< NumericType > & left, const ThermalDiffusivity< NumericType > & right) inline constexpr noexcept
Definition at line 190 of file ThermalDiffusivity.hpp.
operator<=() [85/100]
template<typename NumericType > constexpr bool PhQ::operator<= (const Time< NumericType > & left, const Time< NumericType > & right) inline constexpr noexcept
Definition at line 380 of file Time.hpp.
operator<=() [86/100]
template<typename NumericType > constexpr bool PhQ::operator<= (const TotalKinematicPressure< NumericType > & left, const TotalKinematicPressure< NumericType > & right) inline constexpr noexcept
Definition at line 195 of file TotalKinematicPressure.hpp.
operator<=() [87/100]
template<typename NumericType > constexpr bool PhQ::operator<= (const TotalPressure< NumericType > & left, const TotalPressure< NumericType > & right) inline constexpr noexcept
Definition at line 194 of file TotalPressure.hpp.
operator<=() [88/100]
template<typename NumericType > constexpr bool PhQ::operator<= (const Traction< NumericType > & left, const Traction< NumericType > & right) inline constexpr noexcept
Definition at line 245 of file Traction.hpp.
operator<=() [89/100]
template<typename NumericType > constexpr bool PhQ::operator<= (const TransportEnergyConsumption< NumericType > & left, const TransportEnergyConsumption< NumericType > & right) inline constexpr noexcept
Definition at line 196 of file TransportEnergyConsumption.hpp.
operator<=() [90/100]
template<typename NumericType > constexpr bool PhQ::operator<= (const typename ConstitutiveModel::CompressibleNewtonianFluid< NumericType > & left, const typename ConstitutiveModel::CompressibleNewtonianFluid< NumericType > & right) inline constexpr noexcept
Definition at line 379 of file CompressibleNewtonianFluid.hpp.
operator<=() [91/100]
template<typename NumericType > constexpr bool PhQ::operator<= (const typename ConstitutiveModel::ElasticIsotropicSolid< NumericType > & left, const typename ConstitutiveModel::ElasticIsotropicSolid< NumericType > & right) inline constexpr noexcept
Definition at line 622 of file ElasticIsotropicSolid.hpp.
operator<=() [92/100]
template<typename NumericType > constexpr bool PhQ::operator<= (const typename ConstitutiveModel::IncompressibleNewtonianFluid< NumericType > & left, const typename ConstitutiveModel::IncompressibleNewtonianFluid< NumericType > & right) inline constexpr noexcept
Definition at line 283 of file IncompressibleNewtonianFluid.hpp.
operator<=() [93/100]
template<typename NumericType > constexpr bool PhQ::operator<= (const Vector< NumericType > & left, const Vector< NumericType > & right) inline constexpr noexcept
Definition at line 355 of file Vector.hpp.
operator<=() [94/100]
template<typename NumericType > constexpr bool PhQ::operator<= (const VectorArea< NumericType > & left, const VectorArea< NumericType > & right) inline constexpr noexcept
Definition at line 217 of file VectorArea.hpp.
operator<=() [95/100]
template<typename NumericType > constexpr bool PhQ::operator<= (const Velocity< NumericType > & left, const Velocity< NumericType > & right) inline constexpr noexcept
Definition at line 262 of file Velocity.hpp.
operator<=() [96/100]
template<typename NumericType > constexpr bool PhQ::operator<= (const VelocityGradient< NumericType > & left, const VelocityGradient< NumericType > & right) inline constexpr noexcept
Definition at line 275 of file VelocityGradient.hpp.
operator<=() [97/100]
template<typename NumericType > constexpr bool PhQ::operator<= (const Volume< NumericType > & left, const Volume< NumericType > & right) inline constexpr noexcept
Definition at line 211 of file Volume.hpp.
operator<=() [98/100]
template<typename NumericType > constexpr bool PhQ::operator<= (const VolumeRate< NumericType > & left, const VolumeRate< NumericType > & right) inline constexpr noexcept
Definition at line 198 of file VolumeRate.hpp.
operator<=() [99/100]
template<typename NumericType > constexpr bool PhQ::operator<= (const VolumetricThermalExpansionCoefficient< NumericType > & left, const VolumetricThermalExpansionCoefficient< NumericType > & right) inline constexpr noexcept
Definition at line 199 of file VolumetricThermalExpansionCoefficient.hpp.
operator<=() [100/100]
template<typename NumericType > constexpr bool PhQ::operator<= (const YoungModulus< NumericType > & left, const YoungModulus< NumericType > & right) inline constexpr noexcept
Definition at line 163 of file YoungModulus.hpp.
operator==() [1/100]
template<typename NumericType > constexpr bool PhQ::operator== (const Acceleration< NumericType > & left, const Acceleration< NumericType > & right) inline constexpr noexcept
Definition at line 229 of file Acceleration.hpp.
References PhQ::DimensionalVector< UnitType, NumericType >::Value().
operator==() [2/100]
template<typename NumericType > constexpr bool PhQ::operator== (const Angle< NumericType > & left, const Angle< NumericType > & right) inline constexpr noexcept
Definition at line 346 of file Angle.hpp.
References PhQ::DimensionalScalar< UnitType, NumericType >::Value().
operator==() [3/100]
template<typename NumericType > constexpr bool PhQ::operator== (const AngularSpeed< NumericType > & left, const AngularSpeed< NumericType > & right) inline constexpr noexcept
Definition at line 186 of file AngularSpeed.hpp.
References PhQ::DimensionalScalar< UnitType, NumericType >::Value().
operator==() [4/100]
template<typename NumericType > constexpr bool PhQ::operator== (const Area< NumericType > & left, const Area< NumericType > & right) inline constexpr noexcept
Definition at line 195 of file Area.hpp.
References PhQ::DimensionalVector< UnitType, NumericType >::Value().
operator==() [5/100]
template<typename NumericType > constexpr bool PhQ::operator== (const BulkDynamicViscosity< NumericType > & left, const BulkDynamicViscosity< NumericType > & right) inline constexpr noexcept
Definition at line 144 of file BulkDynamicViscosity.hpp.
operator==() [6/100]
constexpr bool PhQ::operator== (const Dimensions & left, const Dimensions & right) inline constexpr noexcept
Definition at line 331 of file Dimensions.hpp.
References PhQ::Dimension::LuminousIntensity::LuminousIntensity().
operator==() [7/100]
template<typename NumericType > constexpr bool PhQ::operator== (const Direction< NumericType > & left, const Direction< NumericType > & right) inline constexpr noexcept
Definition at line 329 of file Direction.hpp.
operator==() [8/100]
template<typename NumericType > constexpr bool PhQ::operator== (const Displacement< NumericType > & left, const Displacement< NumericType > & right) inline constexpr noexcept
Definition at line 245 of file Displacement.hpp.
References PhQ::DimensionalVector< UnitType, NumericType >::Value().
operator==() [9/100]
template<typename NumericType > constexpr bool PhQ::operator== (const DisplacementGradient< NumericType > & left, const DisplacementGradient< NumericType > & right) inline constexpr noexcept
Definition at line 215 of file DisplacementGradient.hpp.
operator==() [10/100]
template<typename NumericType > constexpr bool PhQ::operator== (const Dyad< NumericType > & left, const Dyad< NumericType > & right) inline constexpr noexcept
Definition at line 480 of file Dyad.hpp.
operator==() [11/100]
template<typename NumericType > constexpr bool PhQ::operator== (const DynamicKinematicPressure< NumericType > & left, const DynamicKinematicPressure< NumericType > & right) inline constexpr noexcept
Definition at line 174 of file DynamicKinematicPressure.hpp.
References PhQ::DimensionalScalar< UnitType, NumericType >::Value().
operator==() [12/100]
template<typename NumericType > constexpr bool PhQ::operator== (const DynamicPressure< NumericType > & left, const DynamicPressure< NumericType > & right) inline constexpr noexcept
Definition at line 171 of file DynamicPressure.hpp.
operator==() [13/100]
template<typename NumericType > constexpr bool PhQ::operator== (const DynamicViscosity< NumericType > & left, const DynamicViscosity< NumericType > & right) inline constexpr noexcept
Definition at line 186 of file DynamicViscosity.hpp.
References PhQ::DimensionalScalar< UnitType, NumericType >::Value().
operator==() [14/100]
template<typename NumericType > constexpr bool PhQ::operator== (const ElectricCharge< NumericType > & left, const ElectricCharge< NumericType > & right) inline constexpr noexcept
Definition at line 166 of file ElectricCharge.hpp.
References PhQ::DimensionalScalar< UnitType, NumericType >::Value().
operator==() [15/100]
template<typename NumericType > constexpr bool PhQ::operator== (const ElectricCurrent< NumericType > & left, const ElectricCurrent< NumericType > & right) inline constexpr noexcept
Definition at line 168 of file ElectricCurrent.hpp.
References PhQ::DimensionalScalar< UnitType, NumericType >::Value().
operator==() [16/100]
template<typename NumericType > constexpr bool PhQ::operator== (const Energy< NumericType > & left, const Energy< NumericType > & right) inline constexpr noexcept
Definition at line 201 of file Energy.hpp.
References PhQ::DimensionalScalar< UnitType, NumericType >::Value().
operator==() [17/100]
template<typename NumericType > constexpr bool PhQ::operator== (const Force< NumericType > & left, const Force< NumericType > & right) inline constexpr noexcept
Definition at line 210 of file Force.hpp.
References PhQ::DimensionalVector< UnitType, NumericType >::Value().
operator==() [18/100]
template<typename NumericType > constexpr bool PhQ::operator== (const Frequency< NumericType > & left, const Frequency< NumericType > & right) inline constexpr noexcept
Definition at line 238 of file Frequency.hpp.
References PhQ::DimensionalScalar< UnitType, NumericType >::Value().
operator==() [19/100]
template<typename NumericType > constexpr bool PhQ::operator== (const GasConstant< NumericType > & left, const GasConstant< NumericType > & right) inline constexpr noexcept
Definition at line 176 of file GasConstant.hpp.
operator==() [20/100]
template<typename NumericType > constexpr bool PhQ::operator== (const HeatCapacityRatio< NumericType > & left, const HeatCapacityRatio< NumericType > & right) inline constexpr noexcept
Definition at line 195 of file HeatCapacityRatio.hpp.
operator==() [21/100]
template<typename NumericType > constexpr bool PhQ::operator== (const HeatFlux< NumericType > & left, const HeatFlux< NumericType > & right) inline constexpr noexcept
Definition at line 223 of file HeatFlux.hpp.
operator==() [22/100]
template<typename NumericType > constexpr bool PhQ::operator== (const IsentropicBulkModulus< NumericType > & left, const IsentropicBulkModulus< NumericType > & right) inline constexpr noexcept
Definition at line 158 of file IsentropicBulkModulus.hpp.
operator==() [23/100]
template<typename NumericType > constexpr bool PhQ::operator== (const IsobaricHeatCapacity< NumericType > & left, const IsobaricHeatCapacity< NumericType > & right) inline constexpr noexcept
Definition at line 189 of file IsobaricHeatCapacity.hpp.
operator==() [24/100]
template<typename NumericType > constexpr bool PhQ::operator== (const IsochoricHeatCapacity< NumericType > & left, const IsochoricHeatCapacity< NumericType > & right) inline constexpr noexcept
Definition at line 177 of file IsochoricHeatCapacity.hpp.
operator==() [25/100]
template<typename NumericType > constexpr bool PhQ::operator== (const IsothermalBulkModulus< NumericType > & left, const IsothermalBulkModulus< NumericType > & right) inline constexpr noexcept
Definition at line 145 of file IsothermalBulkModulus.hpp.
operator==() [26/100]
template<typename NumericType > constexpr bool PhQ::operator== (const KinematicViscosity< NumericType > & left, const KinematicViscosity< NumericType > & right) inline constexpr noexcept
Definition at line 188 of file KinematicViscosity.hpp.
operator==() [27/100]
template<typename NumericType > constexpr bool PhQ::operator== (const LameFirstModulus< NumericType > & left, const LameFirstModulus< NumericType > & right) inline constexpr noexcept
Definition at line 145 of file LameFirstModulus.hpp.
operator==() [28/100]
template<typename NumericType > constexpr bool PhQ::operator== (const Length< NumericType > & left, const Length< NumericType > & right) inline constexpr noexcept
Definition at line 264 of file Length.hpp.
References PhQ::DimensionalVector< UnitType, NumericType >::Value().
operator==() [29/100]
template<typename NumericType > constexpr bool PhQ::operator== (const LinearThermalExpansionCoefficient< NumericType > & left, const LinearThermalExpansionCoefficient< NumericType > & right) inline constexpr noexcept
Definition at line 171 of file LinearThermalExpansionCoefficient.hpp.
operator==() [30/100]
template<typename NumericType > constexpr bool PhQ::operator== (const MachNumber< NumericType > & left, const MachNumber< NumericType > & right) inline constexpr noexcept
Definition at line 130 of file MachNumber.hpp.
operator==() [31/100]
template<typename NumericType > constexpr bool PhQ::operator== (const Mass< NumericType > & left, const Mass< NumericType > & right) inline constexpr noexcept
Definition at line 250 of file Mass.hpp.
References PhQ::DimensionalScalar< UnitType, NumericType >::Value().
operator==() [32/100]
template<typename NumericType > constexpr bool PhQ::operator== (const MassDensity< NumericType > & left, const MassDensity< NumericType > & right) inline constexpr noexcept
Definition at line 229 of file MassDensity.hpp.
References PhQ::DimensionalScalar< UnitType, NumericType >::Value().
operator==() [33/100]
template<typename NumericType > constexpr bool PhQ::operator== (const MassRate< NumericType > & left, const MassRate< NumericType > & right) inline constexpr noexcept
Definition at line 175 of file MassRate.hpp.
References PhQ::DimensionalScalar< UnitType, NumericType >::Value().
operator==() [34/100]
template<typename NumericType > constexpr bool PhQ::operator== (const Memory< NumericType > & left, const Memory< NumericType > & right) inline constexpr noexcept
Definition at line 161 of file Memory.hpp.
References PhQ::DimensionalScalar< UnitType, NumericType >::Value().
operator==() [35/100]
template<typename NumericType > constexpr bool PhQ::operator== (const MemoryRate< NumericType > & left, const MemoryRate< NumericType > & right) inline constexpr noexcept
Definition at line 159 of file MemoryRate.hpp.
References PhQ::DimensionalScalar< UnitType, NumericType >::Value().
operator==() [36/100]
template<typename NumericType > constexpr bool PhQ::operator== (const PlanarAcceleration< NumericType > & left, const PlanarAcceleration< NumericType > & right) inline constexpr noexcept
Definition at line 228 of file PlanarAcceleration.hpp.
References PhQ::DimensionalVector< UnitType, NumericType >::Value().
operator==() [37/100]
template<typename NumericType > constexpr bool PhQ::operator== (const PlanarDirection< NumericType > & left, const PlanarDirection< NumericType > & right) inline constexpr noexcept
Definition at line 333 of file PlanarDirection.hpp.
operator==() [38/100]
template<typename NumericType > constexpr bool PhQ::operator== (const PlanarDisplacement< NumericType > & left, const PlanarDisplacement< NumericType > & right) inline constexpr noexcept
Definition at line 257 of file PlanarDisplacement.hpp.
References PhQ::DimensionalPlanarVector< UnitType, NumericType >::Value().
operator==() [39/100]
template<typename NumericType > constexpr bool PhQ::operator== (const PlanarForce< NumericType > & left, const PlanarForce< NumericType > & right) inline constexpr noexcept
Definition at line 207 of file PlanarForce.hpp.
References PhQ::DimensionalVector< UnitType, NumericType >::Value().
operator==() [40/100]
template<typename NumericType > constexpr bool PhQ::operator== (const PlanarHeatFlux< NumericType > & left, const PlanarHeatFlux< NumericType > & right) inline constexpr noexcept
Definition at line 225 of file PlanarHeatFlux.hpp.
operator==() [41/100]
template<typename NumericType > constexpr bool PhQ::operator== (const PlanarPosition< NumericType > & left, const PlanarPosition< NumericType > & right) inline constexpr noexcept
Definition at line 230 of file PlanarPosition.hpp.
References PhQ::DimensionalPlanarVector< UnitType, NumericType >::Value().
operator==() [42/100]
template<typename NumericType > constexpr bool PhQ::operator== (const PlanarTemperatureGradient< NumericType > & left, const PlanarTemperatureGradient< NumericType > & right) inline constexpr noexcept
Definition at line 223 of file PlanarTemperatureGradient.hpp.
References PhQ::DimensionalVector< UnitType, NumericType >::Value().
operator==() [43/100]
template<typename NumericType > constexpr bool PhQ::operator== (const PlanarTraction< NumericType > & left, const PlanarTraction< NumericType > & right) inline constexpr noexcept
Definition at line 224 of file PlanarTraction.hpp.
operator==() [44/100]
template<typename NumericType > constexpr bool PhQ::operator== (const PlanarVector< NumericType > & left, const PlanarVector< NumericType > & right) inline constexpr noexcept
Definition at line 297 of file PlanarVector.hpp.
operator==() [45/100]
template<typename NumericType > constexpr bool PhQ::operator== (const PlanarVelocity< NumericType > & left, const PlanarVelocity< NumericType > & right) inline constexpr noexcept
Definition at line 243 of file PlanarVelocity.hpp.
References PhQ::DimensionalScalar< UnitType, NumericType >::Value().
operator==() [46/100]
template<typename NumericType > constexpr bool PhQ::operator== (const PoissonRatio< NumericType > & left, const PoissonRatio< NumericType > & right) inline constexpr noexcept
Definition at line 123 of file PoissonRatio.hpp.
operator==() [47/100]
template<typename NumericType > constexpr bool PhQ::operator== (const Position< NumericType > & left, const Position< NumericType > & right) inline constexpr noexcept
Definition at line 225 of file Position.hpp.
References PhQ::DimensionalVector< UnitType, NumericType >::Value().
operator==() [48/100]
template<typename NumericType > constexpr bool PhQ::operator== (const Power< NumericType > & left, const Power< NumericType > & right) inline constexpr noexcept
Definition at line 178 of file Power.hpp.
References PhQ::DimensionalScalar< UnitType, NumericType >::Value().
operator==() [49/100]
template<typename NumericType > constexpr bool PhQ::operator== (const PrandtlNumber< NumericType > & left, const PrandtlNumber< NumericType > & right) inline constexpr noexcept
Definition at line 176 of file PrandtlNumber.hpp.
operator==() [50/100]
template<typename NumericType > constexpr bool PhQ::operator== (const PWaveModulus< NumericType > & left, const PWaveModulus< NumericType > & right) inline constexpr noexcept
Definition at line 139 of file PWaveModulus.hpp.
operator==() [51/100]
template<typename NumericType > constexpr bool PhQ::operator== (const ReynoldsNumber< NumericType > & left, const ReynoldsNumber< NumericType > & right) inline constexpr noexcept
Definition at line 186 of file ReynoldsNumber.hpp.
operator==() [52/100]
template<typename NumericType > constexpr bool PhQ::operator== (const ScalarAcceleration< NumericType > & left, const ScalarAcceleration< NumericType > & right) inline constexpr noexcept
Definition at line 194 of file ScalarAcceleration.hpp.
References PhQ::DimensionalVector< UnitType, NumericType >::Value().
operator==() [53/100]
template<typename NumericType > constexpr bool PhQ::operator== (const ScalarAngularAcceleration< NumericType > & left, const ScalarAngularAcceleration< NumericType > & right) inline constexpr noexcept
Definition at line 179 of file ScalarAngularAcceleration.hpp.
operator==() [54/100]
template<typename NumericType > constexpr bool PhQ::operator== (const ScalarDisplacementGradient< NumericType > & left, const ScalarDisplacementGradient< NumericType > & right) inline constexpr noexcept
Definition at line 166 of file ScalarDisplacementGradient.hpp.
operator==() [55/100]
template<typename NumericType > constexpr bool PhQ::operator== (const ScalarForce< NumericType > & left, const ScalarForce< NumericType > & right) inline constexpr noexcept
Definition at line 183 of file ScalarForce.hpp.
References PhQ::DimensionalVector< UnitType, NumericType >::Value().
operator==() [56/100]
template<typename NumericType > constexpr bool PhQ::operator== (const ScalarHeatFlux< NumericType > & left, const ScalarHeatFlux< NumericType > & right) inline constexpr noexcept
Definition at line 170 of file ScalarHeatFlux.hpp.
References PhQ::DimensionalVector< UnitType, NumericType >::Value().
operator==() [57/100]
template<typename NumericType > constexpr bool PhQ::operator== (const ScalarStrain< NumericType > & left, const ScalarStrain< NumericType > & right) inline constexpr noexcept
Definition at line 163 of file ScalarStrain.hpp.
operator==() [58/100]
template<typename NumericType > constexpr bool PhQ::operator== (const ScalarStrainRate< NumericType > & left, const ScalarStrainRate< NumericType > & right) inline constexpr noexcept
Definition at line 166 of file ScalarStrainRate.hpp.
References PhQ::DimensionalSymmetricDyad< UnitType, NumericType >::Value().
operator==() [59/100]
template<typename NumericType > constexpr bool PhQ::operator== (const ScalarStress< NumericType > & left, const ScalarStress< NumericType > & right) inline constexpr noexcept
Definition at line 144 of file ScalarStress.hpp.
References PhQ::DimensionalSymmetricDyad< UnitType, NumericType >::Value().
operator==() [60/100]
template<typename NumericType > constexpr bool PhQ::operator== (const ScalarTemperatureGradient< NumericType > & left, const ScalarTemperatureGradient< NumericType > & right) inline constexpr noexcept
Definition at line 194 of file ScalarTemperatureGradient.hpp.
References PhQ::DimensionalVector< UnitType, NumericType >::Value().
operator==() [61/100]
template<typename NumericType > constexpr bool PhQ::operator== (const ScalarThermalConductivity< NumericType > & left, const ScalarThermalConductivity< NumericType > & right) inline constexpr noexcept
Definition at line 192 of file ScalarThermalConductivity.hpp.
References PhQ::DimensionalSymmetricDyad< UnitType, NumericType >::Value().
operator==() [62/100]
template<typename NumericType > constexpr bool PhQ::operator== (const ScalarTraction< NumericType > & left, const ScalarTraction< NumericType > & right) inline constexpr noexcept
Definition at line 178 of file ScalarTraction.hpp.
References PhQ::DimensionalVector< UnitType, NumericType >::Value().
operator==() [63/100]
template<typename NumericType > constexpr bool PhQ::operator== (const ScalarVelocityGradient< NumericType > & left, const ScalarVelocityGradient< NumericType > & right) inline constexpr noexcept
Definition at line 172 of file ScalarVelocityGradient.hpp.
References PhQ::DimensionalDyad< UnitType, NumericType >::Value().
operator==() [64/100]
template<typename NumericType > constexpr bool PhQ::operator== (const ShearModulus< NumericType > & left, const ShearModulus< NumericType > & right) inline constexpr noexcept
Definition at line 141 of file ShearModulus.hpp.
operator==() [65/100]
template<typename NumericType > constexpr bool PhQ::operator== (const SolidAngle< NumericType > & left, const SolidAngle< NumericType > & right) inline constexpr noexcept
Definition at line 136 of file SolidAngle.hpp.
References PhQ::DimensionalScalar< UnitType, NumericType >::Value().
operator==() [66/100]
template<typename NumericType > constexpr bool PhQ::operator== (const SoundSpeed< NumericType > & left, const SoundSpeed< NumericType > & right) inline constexpr noexcept
Definition at line 192 of file SoundSpeed.hpp.
References PhQ::DimensionalScalar< UnitType, NumericType >::Value().
operator==() [67/100]
template<typename NumericType > constexpr bool PhQ::operator== (const SpecificEnergy< NumericType > & left, const SpecificEnergy< NumericType > & right) inline constexpr noexcept
Definition at line 172 of file SpecificEnergy.hpp.
References PhQ::DimensionalScalar< UnitType, NumericType >::Value().
operator==() [68/100]
template<typename NumericType > constexpr bool PhQ::operator== (const SpecificGasConstant< NumericType > & left, const SpecificGasConstant< NumericType > & right) inline constexpr noexcept
Definition at line 189 of file SpecificGasConstant.hpp.
operator==() [69/100]
template<typename NumericType > constexpr bool PhQ::operator== (const SpecificIsobaricHeatCapacity< NumericType > & left, const SpecificIsobaricHeatCapacity< NumericType > & right) inline constexpr noexcept
Definition at line 243 of file SpecificIsobaricHeatCapacity.hpp.
operator==() [70/100]
template<typename NumericType > constexpr bool PhQ::operator== (const SpecificIsochoricHeatCapacity< NumericType > & left, const SpecificIsochoricHeatCapacity< NumericType > & right) inline constexpr noexcept
Definition at line 196 of file SpecificIsochoricHeatCapacity.hpp.
operator==() [71/100]
template<typename NumericType > constexpr bool PhQ::operator== (const SpecificPower< NumericType > & left, const SpecificPower< NumericType > & right) inline constexpr noexcept
Definition at line 176 of file SpecificPower.hpp.
References PhQ::DimensionalScalar< UnitType, NumericType >::Value().
operator==() [72/100]
template<typename NumericType > constexpr bool PhQ::operator== (const Speed< NumericType > & left, const Speed< NumericType > & right) inline constexpr noexcept
Definition at line 284 of file Speed.hpp.
References PhQ::DimensionalVector< UnitType, NumericType >::Value().
operator==() [73/100]
template<typename NumericType > constexpr bool PhQ::operator== (const StaticKinematicPressure< NumericType > & left, const StaticKinematicPressure< NumericType > & right) inline constexpr noexcept
Definition at line 175 of file StaticKinematicPressure.hpp.
References PhQ::DimensionalScalar< UnitType, NumericType >::Value().
operator==() [74/100]
template<typename NumericType > constexpr bool PhQ::operator== (const StaticPressure< NumericType > & left, const StaticPressure< NumericType > & right) inline constexpr noexcept
Definition at line 194 of file StaticPressure.hpp.
operator==() [75/100]
template<typename NumericType > constexpr bool PhQ::operator== (const Strain< NumericType > & left, const Strain< NumericType > & right) inline constexpr noexcept
Definition at line 223 of file Strain.hpp.
operator==() [76/100]
template<typename NumericType > constexpr bool PhQ::operator== (const StrainRate< NumericType > & left, const StrainRate< NumericType > & right) inline constexpr noexcept
Definition at line 238 of file StrainRate.hpp.
References PhQ::DimensionalScalar< UnitType, NumericType >::Value().
operator==() [77/100]
template<typename NumericType > constexpr bool PhQ::operator== (const Stress< NumericType > & left, const Stress< NumericType > & right) inline constexpr noexcept
Definition at line 249 of file Stress.hpp.
operator==() [78/100]
template<typename NumericType > constexpr bool PhQ::operator== (const SubstanceAmount< NumericType > & left, const SubstanceAmount< NumericType > & right) inline constexpr noexcept
Definition at line 139 of file SubstanceAmount.hpp.
References PhQ::DimensionalScalar< UnitType, NumericType >::Value().
operator==() [79/100]
template<typename NumericType > constexpr bool PhQ::operator== (const SymmetricDyad< NumericType > & left, const SymmetricDyad< NumericType > & right) inline constexpr noexcept
Definition at line 441 of file SymmetricDyad.hpp.
operator==() [80/100]
template<typename NumericType > constexpr bool PhQ::operator== (const Temperature< NumericType > & left, const Temperature< NumericType > & right) inline constexpr noexcept
Definition at line 160 of file Temperature.hpp.
References PhQ::DimensionalScalar< UnitType, NumericType >::Value().
operator==() [81/100]
template<typename NumericType > constexpr bool PhQ::operator== (const TemperatureDifference< NumericType > & left, const TemperatureDifference< NumericType > & right) inline constexpr noexcept
Definition at line 196 of file TemperatureDifference.hpp.
References PhQ::DimensionalScalar< UnitType, NumericType >::Value().
operator==() [82/100]
template<typename NumericType > constexpr bool PhQ::operator== (const TemperatureGradient< NumericType > & left, const TemperatureGradient< NumericType > & right) inline constexpr noexcept
Definition at line 221 of file TemperatureGradient.hpp.
References PhQ::DimensionalVector< UnitType, NumericType >::Value().
operator==() [83/100]
template<typename NumericType > constexpr bool PhQ::operator== (const ThermalConductivity< NumericType > & left, const ThermalConductivity< NumericType > & right) inline constexpr noexcept
Definition at line 222 of file ThermalConductivity.hpp.
References PhQ::DimensionalSymmetricDyad< UnitType, NumericType >::Value().
operator==() [84/100]
template<typename NumericType > constexpr bool PhQ::operator== (const ThermalDiffusivity< NumericType > & left, const ThermalDiffusivity< NumericType > & right) inline constexpr noexcept
Definition at line 166 of file ThermalDiffusivity.hpp.
operator==() [85/100]
template<typename NumericType > constexpr bool PhQ::operator== (const Time< NumericType > & left, const Time< NumericType > & right) inline constexpr noexcept
Definition at line 356 of file Time.hpp.
References PhQ::DimensionalScalar< UnitType, NumericType >::Value().
operator==() [86/100]
template<typename NumericType > constexpr bool PhQ::operator== (const TotalKinematicPressure< NumericType > & left, const TotalKinematicPressure< NumericType > & right) inline constexpr noexcept
Definition at line 171 of file TotalKinematicPressure.hpp.
References PhQ::DimensionalScalar< UnitType, NumericType >::Value().
operator==() [87/100]
template<typename NumericType > constexpr bool PhQ::operator== (const TotalPressure< NumericType > & left, const TotalPressure< NumericType > & right) inline constexpr noexcept
Definition at line 170 of file TotalPressure.hpp.
operator==() [88/100]
template<typename NumericType > constexpr bool PhQ::operator== (const Traction< NumericType > & left, const Traction< NumericType > & right) inline constexpr noexcept
Definition at line 221 of file Traction.hpp.
operator==() [89/100]
template<typename NumericType > constexpr bool PhQ::operator== (const TransportEnergyConsumption< NumericType > & left, const TransportEnergyConsumption< NumericType > & right) inline constexpr noexcept
Definition at line 172 of file TransportEnergyConsumption.hpp.
References PhQ::DimensionalScalar< UnitType, NumericType >::Value().
operator==() [90/100]
template<typename NumericType > constexpr bool PhQ::operator== (const typename ConstitutiveModel::CompressibleNewtonianFluid< NumericType > & left, const typename ConstitutiveModel::CompressibleNewtonianFluid< NumericType > & right) inline constexpr noexcept
Definition at line 343 of file CompressibleNewtonianFluid.hpp.
operator==() [91/100]
template<typename NumericType > constexpr bool PhQ::operator== (const typename ConstitutiveModel::ElasticIsotropicSolid< NumericType > & left, const typename ConstitutiveModel::ElasticIsotropicSolid< NumericType > & right) inline constexpr noexcept
Definition at line 586 of file ElasticIsotropicSolid.hpp.
operator==() [92/100]
template<typename NumericType > constexpr bool PhQ::operator== (const typename ConstitutiveModel::IncompressibleNewtonianFluid< NumericType > & left, const typename ConstitutiveModel::IncompressibleNewtonianFluid< NumericType > & right) inline constexpr noexcept
Definition at line 255 of file IncompressibleNewtonianFluid.hpp.
operator==() [93/100]
template<typename NumericType > constexpr bool PhQ::operator== (const Vector< NumericType > & left, const Vector< NumericType > & right) inline constexpr noexcept
Definition at line 319 of file Vector.hpp.
operator==() [94/100]
template<typename NumericType > constexpr bool PhQ::operator== (const VectorArea< NumericType > & left, const VectorArea< NumericType > & right) inline constexpr noexcept
Definition at line 193 of file VectorArea.hpp.
References PhQ::DimensionalScalar< UnitType, NumericType >::Value().
operator==() [95/100]
template<typename NumericType > constexpr bool PhQ::operator== (const Velocity< NumericType > & left, const Velocity< NumericType > & right) inline constexpr noexcept
Definition at line 238 of file Velocity.hpp.
References PhQ::DimensionalScalar< UnitType, NumericType >::Value().
operator==() [96/100]
template<typename NumericType > constexpr bool PhQ::operator== (const VelocityGradient< NumericType > & left, const VelocityGradient< NumericType > & right) inline constexpr noexcept
Definition at line 251 of file VelocityGradient.hpp.
References PhQ::DimensionalScalar< UnitType, NumericType >::Value().
operator==() [97/100]
template<typename NumericType > constexpr bool PhQ::operator== (const Volume< NumericType > & left, const Volume< NumericType > & right) inline constexpr noexcept
Definition at line 187 of file Volume.hpp.
References PhQ::DimensionalScalar< UnitType, NumericType >::Value().
operator==() [98/100]
template<typename NumericType > constexpr bool PhQ::operator== (const VolumeRate< NumericType > & left, const VolumeRate< NumericType > & right) inline constexpr noexcept
Definition at line 174 of file VolumeRate.hpp.
References PhQ::DimensionalScalar< UnitType, NumericType >::Value().
operator==() [99/100]
template<typename NumericType > constexpr bool PhQ::operator== (const VolumetricThermalExpansionCoefficient< NumericType > & left, const VolumetricThermalExpansionCoefficient< NumericType > & right) inline constexpr noexcept
Definition at line 171 of file VolumetricThermalExpansionCoefficient.hpp.
operator==() [100/100]
template<typename NumericType > constexpr bool PhQ::operator== (const YoungModulus< NumericType > & left, const YoungModulus< NumericType > & right) inline constexpr noexcept
Definition at line 139 of file YoungModulus.hpp.
operator>() [1/100]
template<typename NumericType > constexpr bool PhQ::operator> (const Acceleration< NumericType > & left, const Acceleration< NumericType > & right) inline constexpr noexcept
Definition at line 247 of file Acceleration.hpp.
operator>() [2/100]
template<typename NumericType > constexpr bool PhQ::operator> (const Angle< NumericType > & left, const Angle< NumericType > & right) inline constexpr noexcept
Definition at line 364 of file Angle.hpp.
operator>() [3/100]
template<typename NumericType > constexpr bool PhQ::operator> (const AngularSpeed< NumericType > & left, const AngularSpeed< NumericType > & right) inline constexpr noexcept
Definition at line 204 of file AngularSpeed.hpp.
operator>() [4/100]
template<typename NumericType > constexpr bool PhQ::operator> (const Area< NumericType > & left, const Area< NumericType > & right) inline constexpr noexcept
Definition at line 213 of file Area.hpp.
operator>() [5/100]
template<typename NumericType > constexpr bool PhQ::operator> (const BulkDynamicViscosity< NumericType > & left, const BulkDynamicViscosity< NumericType > & right) inline constexpr noexcept
Definition at line 162 of file BulkDynamicViscosity.hpp.
operator>() [6/100]
constexpr bool PhQ::operator> (const Dimensions & left, const Dimensions & right) inline constexpr noexcept
Definition at line 369 of file Dimensions.hpp.
operator>() [7/100]
template<typename NumericType > constexpr bool PhQ::operator> (const Direction< NumericType > & left, const Direction< NumericType > & right) inline constexpr noexcept
Definition at line 347 of file Direction.hpp.
operator>() [8/100]
template<typename NumericType > constexpr bool PhQ::operator> (const Displacement< NumericType > & left, const Displacement< NumericType > & right) inline constexpr noexcept
Definition at line 263 of file Displacement.hpp.
operator>() [9/100]
template<typename NumericType > constexpr bool PhQ::operator> (const DisplacementGradient< NumericType > & left, const DisplacementGradient< NumericType > & right) inline constexpr noexcept
Definition at line 233 of file DisplacementGradient.hpp.
operator>() [10/100]
template<typename NumericType > constexpr bool PhQ::operator> (const Dyad< NumericType > & left, const Dyad< NumericType > & right) inline constexpr noexcept
Definition at line 526 of file Dyad.hpp.
operator>() [11/100]
template<typename NumericType > constexpr bool PhQ::operator> (const DynamicKinematicPressure< NumericType > & left, const DynamicKinematicPressure< NumericType > & right) inline constexpr noexcept
Definition at line 192 of file DynamicKinematicPressure.hpp.
operator>() [12/100]
template<typename NumericType > constexpr bool PhQ::operator> (const DynamicPressure< NumericType > & left, const DynamicPressure< NumericType > & right) inline constexpr noexcept
Definition at line 189 of file DynamicPressure.hpp.
operator>() [13/100]
template<typename NumericType > constexpr bool PhQ::operator> (const DynamicViscosity< NumericType > & left, const DynamicViscosity< NumericType > & right) inline constexpr noexcept
Definition at line 204 of file DynamicViscosity.hpp.
operator>() [14/100]
template<typename NumericType > constexpr bool PhQ::operator> (const ElectricCharge< NumericType > & left, const ElectricCharge< NumericType > & right) inline constexpr noexcept
Definition at line 184 of file ElectricCharge.hpp.
operator>() [15/100]
template<typename NumericType > constexpr bool PhQ::operator> (const ElectricCurrent< NumericType > & left, const ElectricCurrent< NumericType > & right) inline constexpr noexcept
Definition at line 186 of file ElectricCurrent.hpp.
operator>() [16/100]
template<typename NumericType > constexpr bool PhQ::operator> (const Energy< NumericType > & left, const Energy< NumericType > & right) inline constexpr noexcept
Definition at line 219 of file Energy.hpp.
operator>() [17/100]
template<typename NumericType > constexpr bool PhQ::operator> (const Force< NumericType > & left, const Force< NumericType > & right) inline constexpr noexcept
Definition at line 228 of file Force.hpp.
operator>() [18/100]
template<typename NumericType > constexpr bool PhQ::operator> (const Frequency< NumericType > & left, const Frequency< NumericType > & right) inline constexpr noexcept
Definition at line 256 of file Frequency.hpp.
operator>() [19/100]
template<typename NumericType > constexpr bool PhQ::operator> (const GasConstant< NumericType > & left, const GasConstant< NumericType > & right) inline constexpr noexcept
Definition at line 194 of file GasConstant.hpp.
operator>() [20/100]
template<typename NumericType > constexpr bool PhQ::operator> (const HeatCapacityRatio< NumericType > & left, const HeatCapacityRatio< NumericType > & right) inline constexpr noexcept
Definition at line 213 of file HeatCapacityRatio.hpp.
operator>() [21/100]
template<typename NumericType > constexpr bool PhQ::operator> (const HeatFlux< NumericType > & left, const HeatFlux< NumericType > & right) inline constexpr noexcept
Definition at line 241 of file HeatFlux.hpp.
operator>() [22/100]
template<typename NumericType > constexpr bool PhQ::operator> (const IsentropicBulkModulus< NumericType > & left, const IsentropicBulkModulus< NumericType > & right) inline constexpr noexcept
Definition at line 176 of file IsentropicBulkModulus.hpp.
operator>() [23/100]
template<typename NumericType > constexpr bool PhQ::operator> (const IsobaricHeatCapacity< NumericType > & left, const IsobaricHeatCapacity< NumericType > & right) inline constexpr noexcept
Definition at line 207 of file IsobaricHeatCapacity.hpp.
operator>() [24/100]
template<typename NumericType > constexpr bool PhQ::operator> (const IsochoricHeatCapacity< NumericType > & left, const IsochoricHeatCapacity< NumericType > & right) inline constexpr noexcept
Definition at line 195 of file IsochoricHeatCapacity.hpp.
operator>() [25/100]
template<typename NumericType > constexpr bool PhQ::operator> (const IsothermalBulkModulus< NumericType > & left, const IsothermalBulkModulus< NumericType > & right) inline constexpr noexcept
Definition at line 163 of file IsothermalBulkModulus.hpp.
operator>() [26/100]
template<typename NumericType > constexpr bool PhQ::operator> (const KinematicViscosity< NumericType > & left, const KinematicViscosity< NumericType > & right) inline constexpr noexcept
Definition at line 206 of file KinematicViscosity.hpp.
operator>() [27/100]
template<typename NumericType > constexpr bool PhQ::operator> (const LameFirstModulus< NumericType > & left, const LameFirstModulus< NumericType > & right) inline constexpr noexcept
Definition at line 163 of file LameFirstModulus.hpp.
operator>() [28/100]
template<typename NumericType > constexpr bool PhQ::operator> (const Length< NumericType > & left, const Length< NumericType > & right) inline constexpr noexcept
Definition at line 282 of file Length.hpp.
operator>() [29/100]
template<typename NumericType > constexpr bool PhQ::operator> (const LinearThermalExpansionCoefficient< NumericType > & left, const LinearThermalExpansionCoefficient< NumericType > & right) inline constexpr noexcept
Definition at line 192 of file LinearThermalExpansionCoefficient.hpp.
operator>() [30/100]
template<typename NumericType > constexpr bool PhQ::operator> (const MachNumber< NumericType > & left, const MachNumber< NumericType > & right) inline constexpr noexcept
Definition at line 148 of file MachNumber.hpp.
operator>() [31/100]
template<typename NumericType > constexpr bool PhQ::operator> (const Mass< NumericType > & left, const Mass< NumericType > & right) inline constexpr noexcept
Definition at line 268 of file Mass.hpp.
operator>() [32/100]
template<typename NumericType > constexpr bool PhQ::operator> (const MassDensity< NumericType > & left, const MassDensity< NumericType > & right) inline constexpr noexcept
Definition at line 247 of file MassDensity.hpp.
operator>() [33/100]
template<typename NumericType > constexpr bool PhQ::operator> (const MassRate< NumericType > & left, const MassRate< NumericType > & right) inline constexpr noexcept
Definition at line 193 of file MassRate.hpp.
operator>() [34/100]
template<typename NumericType > constexpr bool PhQ::operator> (const Memory< NumericType > & left, const Memory< NumericType > & right) inline constexpr noexcept
Definition at line 179 of file Memory.hpp.
operator>() [35/100]
template<typename NumericType > constexpr bool PhQ::operator> (const MemoryRate< NumericType > & left, const MemoryRate< NumericType > & right) inline constexpr noexcept
Definition at line 177 of file MemoryRate.hpp.
operator>() [36/100]
template<typename NumericType > constexpr bool PhQ::operator> (const PlanarAcceleration< NumericType > & left, const PlanarAcceleration< NumericType > & right) inline constexpr noexcept
Definition at line 246 of file PlanarAcceleration.hpp.
operator>() [37/100]
template<typename NumericType > constexpr bool PhQ::operator> (const PlanarDirection< NumericType > & left, const PlanarDirection< NumericType > & right) inline constexpr noexcept
Definition at line 351 of file PlanarDirection.hpp.
operator>() [38/100]
template<typename NumericType > constexpr bool PhQ::operator> (const PlanarDisplacement< NumericType > & left, const PlanarDisplacement< NumericType > & right) inline constexpr noexcept
Definition at line 275 of file PlanarDisplacement.hpp.
operator>() [39/100]
template<typename NumericType > constexpr bool PhQ::operator> (const PlanarForce< NumericType > & left, const PlanarForce< NumericType > & right) inline constexpr noexcept
Definition at line 225 of file PlanarForce.hpp.
operator>() [40/100]
template<typename NumericType > constexpr bool PhQ::operator> (const PlanarHeatFlux< NumericType > & left, const PlanarHeatFlux< NumericType > & right) inline constexpr noexcept
Definition at line 243 of file PlanarHeatFlux.hpp.
operator>() [41/100]
template<typename NumericType > constexpr bool PhQ::operator> (const PlanarPosition< NumericType > & left, const PlanarPosition< NumericType > & right) inline constexpr noexcept
Definition at line 248 of file PlanarPosition.hpp.
operator>() [42/100]
template<typename NumericType > constexpr bool PhQ::operator> (const PlanarTemperatureGradient< NumericType > & left, const PlanarTemperatureGradient< NumericType > & right) inline constexpr noexcept
Definition at line 241 of file PlanarTemperatureGradient.hpp.
operator>() [43/100]
template<typename NumericType > constexpr bool PhQ::operator> (const PlanarTraction< NumericType > & left, const PlanarTraction< NumericType > & right) inline constexpr noexcept
Definition at line 242 of file PlanarTraction.hpp.
operator>() [44/100]
template<typename NumericType > constexpr bool PhQ::operator> (const PlanarVector< NumericType > & left, const PlanarVector< NumericType > & right) inline constexpr noexcept
Definition at line 318 of file PlanarVector.hpp.
operator>() [45/100]
template<typename NumericType > constexpr bool PhQ::operator> (const PlanarVelocity< NumericType > & left, const PlanarVelocity< NumericType > & right) inline constexpr noexcept
Definition at line 261 of file PlanarVelocity.hpp.
operator>() [46/100]
template<typename NumericType > constexpr bool PhQ::operator> (const PoissonRatio< NumericType > & left, const PoissonRatio< NumericType > & right) inline constexpr noexcept
Definition at line 141 of file PoissonRatio.hpp.
operator>() [47/100]
template<typename NumericType > constexpr bool PhQ::operator> (const Position< NumericType > & left, const Position< NumericType > & right) inline constexpr noexcept
Definition at line 243 of file Position.hpp.
operator>() [48/100]
template<typename NumericType > constexpr bool PhQ::operator> (const Power< NumericType > & left, const Power< NumericType > & right) inline constexpr noexcept
Definition at line 196 of file Power.hpp.
operator>() [49/100]
template<typename NumericType > constexpr bool PhQ::operator> (const PrandtlNumber< NumericType > & left, const PrandtlNumber< NumericType > & right) inline constexpr noexcept
Definition at line 194 of file PrandtlNumber.hpp.
operator>() [50/100]
template<typename NumericType > constexpr bool PhQ::operator> (const PWaveModulus< NumericType > & left, const PWaveModulus< NumericType > & right) inline constexpr noexcept
Definition at line 157 of file PWaveModulus.hpp.
operator>() [51/100]
template<typename NumericType > constexpr bool PhQ::operator> (const ReynoldsNumber< NumericType > & left, const ReynoldsNumber< NumericType > & right) inline constexpr noexcept
Definition at line 204 of file ReynoldsNumber.hpp.
operator>() [52/100]
template<typename NumericType > constexpr bool PhQ::operator> (const ScalarAcceleration< NumericType > & left, const ScalarAcceleration< NumericType > & right) inline constexpr noexcept
Definition at line 212 of file ScalarAcceleration.hpp.
operator>() [53/100]
template<typename NumericType > constexpr bool PhQ::operator> (const ScalarAngularAcceleration< NumericType > & left, const ScalarAngularAcceleration< NumericType > & right) inline constexpr noexcept
Definition at line 197 of file ScalarAngularAcceleration.hpp.
operator>() [54/100]
template<typename NumericType > constexpr bool PhQ::operator> (const ScalarDisplacementGradient< NumericType > & left, const ScalarDisplacementGradient< NumericType > & right) inline constexpr noexcept
Definition at line 184 of file ScalarDisplacementGradient.hpp.
operator>() [55/100]
template<typename NumericType > constexpr bool PhQ::operator> (const ScalarForce< NumericType > & left, const ScalarForce< NumericType > & right) inline constexpr noexcept
Definition at line 201 of file ScalarForce.hpp.
operator>() [56/100]
template<typename NumericType > constexpr bool PhQ::operator> (const ScalarHeatFlux< NumericType > & left, const ScalarHeatFlux< NumericType > & right) inline constexpr noexcept
Definition at line 188 of file ScalarHeatFlux.hpp.
operator>() [57/100]
template<typename NumericType > constexpr bool PhQ::operator> (const ScalarStrain< NumericType > & left, const ScalarStrain< NumericType > & right) inline constexpr noexcept
Definition at line 181 of file ScalarStrain.hpp.
operator>() [58/100]
template<typename NumericType > constexpr bool PhQ::operator> (const ScalarStrainRate< NumericType > & left, const ScalarStrainRate< NumericType > & right) inline constexpr noexcept
Definition at line 184 of file ScalarStrainRate.hpp.
operator>() [59/100]
template<typename NumericType > constexpr bool PhQ::operator> (const ScalarStress< NumericType > & left, const ScalarStress< NumericType > & right) inline constexpr noexcept
Definition at line 162 of file ScalarStress.hpp.
operator>() [60/100]
template<typename NumericType > constexpr bool PhQ::operator> (const ScalarTemperatureGradient< NumericType > & left, const ScalarTemperatureGradient< NumericType > & right) inline constexpr noexcept
Definition at line 212 of file ScalarTemperatureGradient.hpp.
operator>() [61/100]
template<typename NumericType > constexpr bool PhQ::operator> (const ScalarThermalConductivity< NumericType > & left, const ScalarThermalConductivity< NumericType > & right) inline constexpr noexcept
Definition at line 210 of file ScalarThermalConductivity.hpp.
operator>() [62/100]
template<typename NumericType > constexpr bool PhQ::operator> (const ScalarTraction< NumericType > & left, const ScalarTraction< NumericType > & right) inline constexpr noexcept
Definition at line 196 of file ScalarTraction.hpp.
operator>() [63/100]
template<typename NumericType > constexpr bool PhQ::operator> (const ScalarVelocityGradient< NumericType > & left, const ScalarVelocityGradient< NumericType > & right) inline constexpr noexcept
Definition at line 190 of file ScalarVelocityGradient.hpp.
operator>() [64/100]
template<typename NumericType > constexpr bool PhQ::operator> (const ShearModulus< NumericType > & left, const ShearModulus< NumericType > & right) inline constexpr noexcept
Definition at line 159 of file ShearModulus.hpp.
operator>() [65/100]
template<typename NumericType > constexpr bool PhQ::operator> (const SolidAngle< NumericType > & left, const SolidAngle< NumericType > & right) inline constexpr noexcept
Definition at line 154 of file SolidAngle.hpp.
operator>() [66/100]
template<typename NumericType > constexpr bool PhQ::operator> (const SoundSpeed< NumericType > & left, const SoundSpeed< NumericType > & right) inline constexpr noexcept
Definition at line 210 of file SoundSpeed.hpp.
operator>() [67/100]
template<typename NumericType > constexpr bool PhQ::operator> (const SpecificEnergy< NumericType > & left, const SpecificEnergy< NumericType > & right) inline constexpr noexcept
Definition at line 190 of file SpecificEnergy.hpp.
operator>() [68/100]
template<typename NumericType > constexpr bool PhQ::operator> (const SpecificGasConstant< NumericType > & left, const SpecificGasConstant< NumericType > & right) inline constexpr noexcept
Definition at line 207 of file SpecificGasConstant.hpp.
operator>() [69/100]
template<typename NumericType > constexpr bool PhQ::operator> (const SpecificIsobaricHeatCapacity< NumericType > & left, const SpecificIsobaricHeatCapacity< NumericType > & right) inline constexpr noexcept
Definition at line 261 of file SpecificIsobaricHeatCapacity.hpp.
operator>() [70/100]
template<typename NumericType > constexpr bool PhQ::operator> (const SpecificIsochoricHeatCapacity< NumericType > & left, const SpecificIsochoricHeatCapacity< NumericType > & right) inline constexpr noexcept
Definition at line 214 of file SpecificIsochoricHeatCapacity.hpp.
operator>() [71/100]
template<typename NumericType > constexpr bool PhQ::operator> (const SpecificPower< NumericType > & left, const SpecificPower< NumericType > & right) inline constexpr noexcept
Definition at line 194 of file SpecificPower.hpp.
operator>() [72/100]
template<typename NumericType > constexpr bool PhQ::operator> (const Speed< NumericType > & left, const Speed< NumericType > & right) inline constexpr noexcept
Definition at line 302 of file Speed.hpp.
operator>() [73/100]
template<typename NumericType > constexpr bool PhQ::operator> (const StaticKinematicPressure< NumericType > & left, const StaticKinematicPressure< NumericType > & right) inline constexpr noexcept
Definition at line 193 of file StaticKinematicPressure.hpp.
operator>() [74/100]
template<typename NumericType > constexpr bool PhQ::operator> (const StaticPressure< NumericType > & left, const StaticPressure< NumericType > & right) inline constexpr noexcept
Definition at line 212 of file StaticPressure.hpp.
operator>() [75/100]
template<typename NumericType > constexpr bool PhQ::operator> (const Strain< NumericType > & left, const Strain< NumericType > & right) inline constexpr noexcept
Definition at line 241 of file Strain.hpp.
operator>() [76/100]
template<typename NumericType > constexpr bool PhQ::operator> (const StrainRate< NumericType > & left, const StrainRate< NumericType > & right) inline constexpr noexcept
Definition at line 256 of file StrainRate.hpp.
operator>() [77/100]
template<typename NumericType > constexpr bool PhQ::operator> (const Stress< NumericType > & left, const Stress< NumericType > & right) inline constexpr noexcept
Definition at line 267 of file Stress.hpp.
operator>() [78/100]
template<typename NumericType > constexpr bool PhQ::operator> (const SubstanceAmount< NumericType > & left, const SubstanceAmount< NumericType > & right) inline constexpr noexcept
Definition at line 157 of file SubstanceAmount.hpp.
operator>() [79/100]
template<typename NumericType > constexpr bool PhQ::operator> (const SymmetricDyad< NumericType > & left, const SymmetricDyad< NumericType > & right) inline constexpr noexcept
Definition at line 476 of file SymmetricDyad.hpp.
operator>() [80/100]
template<typename NumericType > constexpr bool PhQ::operator> (const Temperature< NumericType > & left, const Temperature< NumericType > & right) inline constexpr noexcept
Definition at line 178 of file Temperature.hpp.
operator>() [81/100]
template<typename NumericType > constexpr bool PhQ::operator> (const TemperatureDifference< NumericType > & left, const TemperatureDifference< NumericType > & right) inline constexpr noexcept
Definition at line 214 of file TemperatureDifference.hpp.
operator>() [82/100]
template<typename NumericType > constexpr bool PhQ::operator> (const TemperatureGradient< NumericType > & left, const TemperatureGradient< NumericType > & right) inline constexpr noexcept
Definition at line 239 of file TemperatureGradient.hpp.
operator>() [83/100]
template<typename NumericType > constexpr bool PhQ::operator> (const ThermalConductivity< NumericType > & left, const ThermalConductivity< NumericType > & right) inline constexpr noexcept
Definition at line 240 of file ThermalConductivity.hpp.
operator>() [84/100]
template<typename NumericType > constexpr bool PhQ::operator> (const ThermalDiffusivity< NumericType > & left, const ThermalDiffusivity< NumericType > & right) inline constexpr noexcept
Definition at line 184 of file ThermalDiffusivity.hpp.
operator>() [85/100]
template<typename NumericType > constexpr bool PhQ::operator> (const Time< NumericType > & left, const Time< NumericType > & right) inline constexpr noexcept
Definition at line 374 of file Time.hpp.
operator>() [86/100]
template<typename NumericType > constexpr bool PhQ::operator> (const TotalKinematicPressure< NumericType > & left, const TotalKinematicPressure< NumericType > & right) inline constexpr noexcept
Definition at line 189 of file TotalKinematicPressure.hpp.
operator>() [87/100]
template<typename NumericType > constexpr bool PhQ::operator> (const TotalPressure< NumericType > & left, const TotalPressure< NumericType > & right) inline constexpr noexcept
Definition at line 188 of file TotalPressure.hpp.
operator>() [88/100]
template<typename NumericType > constexpr bool PhQ::operator> (const Traction< NumericType > & left, const Traction< NumericType > & right) inline constexpr noexcept
Definition at line 239 of file Traction.hpp.
operator>() [89/100]
template<typename NumericType > constexpr bool PhQ::operator> (const TransportEnergyConsumption< NumericType > & left, const TransportEnergyConsumption< NumericType > & right) inline constexpr noexcept
Definition at line 190 of file TransportEnergyConsumption.hpp.
operator>() [90/100]
template<typename NumericType > constexpr bool PhQ::operator> (const typename ConstitutiveModel::CompressibleNewtonianFluid< NumericType > & left, const typename ConstitutiveModel::CompressibleNewtonianFluid< NumericType > & right) inline constexpr noexcept
Definition at line 369 of file CompressibleNewtonianFluid.hpp.
operator>() [91/100]
template<typename NumericType > constexpr bool PhQ::operator> (const typename ConstitutiveModel::ElasticIsotropicSolid< NumericType > & left, const typename ConstitutiveModel::ElasticIsotropicSolid< NumericType > & right) inline constexpr noexcept
Definition at line 612 of file ElasticIsotropicSolid.hpp.
operator>() [92/100]
template<typename NumericType > constexpr bool PhQ::operator> (const typename ConstitutiveModel::IncompressibleNewtonianFluid< NumericType > & left, const typename ConstitutiveModel::IncompressibleNewtonianFluid< NumericType > & right) inline constexpr noexcept
Definition at line 276 of file IncompressibleNewtonianFluid.hpp.
operator>() [93/100]
template<typename NumericType > constexpr bool PhQ::operator> (const Vector< NumericType > & left, const Vector< NumericType > & right) inline constexpr noexcept
Definition at line 343 of file Vector.hpp.
operator>() [94/100]
template<typename NumericType > constexpr bool PhQ::operator> (const VectorArea< NumericType > & left, const VectorArea< NumericType > & right) inline constexpr noexcept
Definition at line 211 of file VectorArea.hpp.
operator>() [95/100]
template<typename NumericType > constexpr bool PhQ::operator> (const Velocity< NumericType > & left, const Velocity< NumericType > & right) inline constexpr noexcept
Definition at line 256 of file Velocity.hpp.
operator>() [96/100]
template<typename NumericType > constexpr bool PhQ::operator> (const VelocityGradient< NumericType > & left, const VelocityGradient< NumericType > & right) inline constexpr noexcept
Definition at line 269 of file VelocityGradient.hpp.
operator>() [97/100]
template<typename NumericType > constexpr bool PhQ::operator> (const Volume< NumericType > & left, const Volume< NumericType > & right) inline constexpr noexcept
Definition at line 205 of file Volume.hpp.
operator>() [98/100]
template<typename NumericType > constexpr bool PhQ::operator> (const VolumeRate< NumericType > & left, const VolumeRate< NumericType > & right) inline constexpr noexcept
Definition at line 192 of file VolumeRate.hpp.
operator>() [99/100]
template<typename NumericType > constexpr bool PhQ::operator> (const VolumetricThermalExpansionCoefficient< NumericType > & left, const VolumetricThermalExpansionCoefficient< NumericType > & right) inline constexpr noexcept
Definition at line 192 of file VolumetricThermalExpansionCoefficient.hpp.
operator>() [100/100]
template<typename NumericType > constexpr bool PhQ::operator> (const YoungModulus< NumericType > & left, const YoungModulus< NumericType > & right) inline constexpr noexcept
Definition at line 157 of file YoungModulus.hpp.
operator>=() [1/100]
template<typename NumericType > constexpr bool PhQ::operator>= (const Acceleration< NumericType > & left, const Acceleration< NumericType > & right) inline constexpr noexcept
Definition at line 259 of file Acceleration.hpp.
operator>=() [2/100]
template<typename NumericType > constexpr bool PhQ::operator>= (const Angle< NumericType > & left, const Angle< NumericType > & right) inline constexpr noexcept
Definition at line 376 of file Angle.hpp.
operator>=() [3/100]
template<typename NumericType > constexpr bool PhQ::operator>= (const AngularSpeed< NumericType > & left, const AngularSpeed< NumericType > & right) inline constexpr noexcept
Definition at line 216 of file AngularSpeed.hpp.
operator>=() [4/100]
template<typename NumericType > constexpr bool PhQ::operator>= (const Area< NumericType > & left, const Area< NumericType > & right) inline constexpr noexcept
Definition at line 225 of file Area.hpp.
operator>=() [5/100]
template<typename NumericType > constexpr bool PhQ::operator>= (const BulkDynamicViscosity< NumericType > & left, const BulkDynamicViscosity< NumericType > & right) inline constexpr noexcept
Definition at line 174 of file BulkDynamicViscosity.hpp.
operator>=() [6/100]
constexpr bool PhQ::operator>= (const Dimensions & left, const Dimensions & right) inline constexpr noexcept
Definition at line 395 of file Dimensions.hpp.
operator>=() [7/100]
template<typename NumericType > constexpr bool PhQ::operator>= (const Direction< NumericType > & left, const Direction< NumericType > & right) inline constexpr noexcept
Definition at line 359 of file Direction.hpp.
operator>=() [8/100]
template<typename NumericType > constexpr bool PhQ::operator>= (const Displacement< NumericType > & left, const Displacement< NumericType > & right) inline constexpr noexcept
Definition at line 275 of file Displacement.hpp.
operator>=() [9/100]
template<typename NumericType > constexpr bool PhQ::operator>= (const DisplacementGradient< NumericType > & left, const DisplacementGradient< NumericType > & right) inline constexpr noexcept
Definition at line 245 of file DisplacementGradient.hpp.
operator>=() [10/100]
template<typename NumericType > constexpr bool PhQ::operator>= (const Dyad< NumericType > & left, const Dyad< NumericType > & right) inline constexpr noexcept
Definition at line 562 of file Dyad.hpp.
operator>=() [11/100]
template<typename NumericType > constexpr bool PhQ::operator>= (const DynamicKinematicPressure< NumericType > & left, const DynamicKinematicPressure< NumericType > & right) inline constexpr noexcept
Definition at line 204 of file DynamicKinematicPressure.hpp.
operator>=() [12/100]
template<typename NumericType > constexpr bool PhQ::operator>= (const DynamicPressure< NumericType > & left, const DynamicPressure< NumericType > & right) inline constexpr noexcept
Definition at line 201 of file DynamicPressure.hpp.
operator>=() [13/100]
template<typename NumericType > constexpr bool PhQ::operator>= (const DynamicViscosity< NumericType > & left, const DynamicViscosity< NumericType > & right) inline constexpr noexcept
Definition at line 216 of file DynamicViscosity.hpp.
operator>=() [14/100]
template<typename NumericType > constexpr bool PhQ::operator>= (const ElectricCharge< NumericType > & left, const ElectricCharge< NumericType > & right) inline constexpr noexcept
Definition at line 196 of file ElectricCharge.hpp.
operator>=() [15/100]
template<typename NumericType > constexpr bool PhQ::operator>= (const ElectricCurrent< NumericType > & left, const ElectricCurrent< NumericType > & right) inline constexpr noexcept
Definition at line 198 of file ElectricCurrent.hpp.
operator>=() [16/100]
template<typename NumericType > constexpr bool PhQ::operator>= (const Energy< NumericType > & left, const Energy< NumericType > & right) inline constexpr noexcept
Definition at line 231 of file Energy.hpp.
operator>=() [17/100]
template<typename NumericType > constexpr bool PhQ::operator>= (const Force< NumericType > & left, const Force< NumericType > & right) inline constexpr noexcept
Definition at line 240 of file Force.hpp.
operator>=() [18/100]
template<typename NumericType > constexpr bool PhQ::operator>= (const Frequency< NumericType > & left, const Frequency< NumericType > & right) inline constexpr noexcept
Definition at line 268 of file Frequency.hpp.
operator>=() [19/100]
template<typename NumericType > constexpr bool PhQ::operator>= (const GasConstant< NumericType > & left, const GasConstant< NumericType > & right) inline constexpr noexcept
Definition at line 206 of file GasConstant.hpp.
operator>=() [20/100]
template<typename NumericType > constexpr bool PhQ::operator>= (const HeatCapacityRatio< NumericType > & left, const HeatCapacityRatio< NumericType > & right) inline constexpr noexcept
Definition at line 225 of file HeatCapacityRatio.hpp.
operator>=() [21/100]
template<typename NumericType > constexpr bool PhQ::operator>= (const HeatFlux< NumericType > & left, const HeatFlux< NumericType > & right) inline constexpr noexcept
Definition at line 253 of file HeatFlux.hpp.
operator>=() [22/100]
template<typename NumericType > constexpr bool PhQ::operator>= (const IsentropicBulkModulus< NumericType > & left, const IsentropicBulkModulus< NumericType > & right) inline constexpr noexcept
Definition at line 188 of file IsentropicBulkModulus.hpp.
operator>=() [23/100]
template<typename NumericType > constexpr bool PhQ::operator>= (const IsobaricHeatCapacity< NumericType > & left, const IsobaricHeatCapacity< NumericType > & right) inline constexpr noexcept
Definition at line 219 of file IsobaricHeatCapacity.hpp.
operator>=() [24/100]
template<typename NumericType > constexpr bool PhQ::operator>= (const IsochoricHeatCapacity< NumericType > & left, const IsochoricHeatCapacity< NumericType > & right) inline constexpr noexcept
Definition at line 207 of file IsochoricHeatCapacity.hpp.
operator>=() [25/100]
template<typename NumericType > constexpr bool PhQ::operator>= (const IsothermalBulkModulus< NumericType > & left, const IsothermalBulkModulus< NumericType > & right) inline constexpr noexcept
Definition at line 175 of file IsothermalBulkModulus.hpp.
operator>=() [26/100]
template<typename NumericType > constexpr bool PhQ::operator>= (const KinematicViscosity< NumericType > & left, const KinematicViscosity< NumericType > & right) inline constexpr noexcept
Definition at line 218 of file KinematicViscosity.hpp.
operator>=() [27/100]
template<typename NumericType > constexpr bool PhQ::operator>= (const LameFirstModulus< NumericType > & left, const LameFirstModulus< NumericType > & right) inline constexpr noexcept
Definition at line 175 of file LameFirstModulus.hpp.
operator>=() [28/100]
template<typename NumericType > constexpr bool PhQ::operator>= (const Length< NumericType > & left, const Length< NumericType > & right) inline constexpr noexcept
Definition at line 294 of file Length.hpp.
operator>=() [29/100]
template<typename NumericType > constexpr bool PhQ::operator>= (const LinearThermalExpansionCoefficient< NumericType > & left, const LinearThermalExpansionCoefficient< NumericType > & right) inline constexpr noexcept
Definition at line 206 of file LinearThermalExpansionCoefficient.hpp.
operator>=() [30/100]
template<typename NumericType > constexpr bool PhQ::operator>= (const MachNumber< NumericType > & left, const MachNumber< NumericType > & right) inline constexpr noexcept
Definition at line 160 of file MachNumber.hpp.
operator>=() [31/100]
template<typename NumericType > constexpr bool PhQ::operator>= (const Mass< NumericType > & left, const Mass< NumericType > & right) inline constexpr noexcept
Definition at line 280 of file Mass.hpp.
operator>=() [32/100]
template<typename NumericType > constexpr bool PhQ::operator>= (const MassDensity< NumericType > & left, const MassDensity< NumericType > & right) inline constexpr noexcept
Definition at line 259 of file MassDensity.hpp.
operator>=() [33/100]
template<typename NumericType > constexpr bool PhQ::operator>= (const MassRate< NumericType > & left, const MassRate< NumericType > & right) inline constexpr noexcept
Definition at line 205 of file MassRate.hpp.
operator>=() [34/100]
template<typename NumericType > constexpr bool PhQ::operator>= (const Memory< NumericType > & left, const Memory< NumericType > & right) inline constexpr noexcept
Definition at line 191 of file Memory.hpp.
operator>=() [35/100]
template<typename NumericType > constexpr bool PhQ::operator>= (const MemoryRate< NumericType > & left, const MemoryRate< NumericType > & right) inline constexpr noexcept
Definition at line 189 of file MemoryRate.hpp.
operator>=() [36/100]
template<typename NumericType > constexpr bool PhQ::operator>= (const PlanarAcceleration< NumericType > & left, const PlanarAcceleration< NumericType > & right) inline constexpr noexcept
Definition at line 258 of file PlanarAcceleration.hpp.
operator>=() [37/100]
template<typename NumericType > constexpr bool PhQ::operator>= (const PlanarDirection< NumericType > & left, const PlanarDirection< NumericType > & right) inline constexpr noexcept
Definition at line 363 of file PlanarDirection.hpp.
operator>=() [38/100]
template<typename NumericType > constexpr bool PhQ::operator>= (const PlanarDisplacement< NumericType > & left, const PlanarDisplacement< NumericType > & right) inline constexpr noexcept
Definition at line 287 of file PlanarDisplacement.hpp.
operator>=() [39/100]
template<typename NumericType > constexpr bool PhQ::operator>= (const PlanarForce< NumericType > & left, const PlanarForce< NumericType > & right) inline constexpr noexcept
Definition at line 237 of file PlanarForce.hpp.
operator>=() [40/100]
template<typename NumericType > constexpr bool PhQ::operator>= (const PlanarHeatFlux< NumericType > & left, const PlanarHeatFlux< NumericType > & right) inline constexpr noexcept
Definition at line 255 of file PlanarHeatFlux.hpp.
operator>=() [41/100]
template<typename NumericType > constexpr bool PhQ::operator>= (const PlanarPosition< NumericType > & left, const PlanarPosition< NumericType > & right) inline constexpr noexcept
Definition at line 260 of file PlanarPosition.hpp.
operator>=() [42/100]
template<typename NumericType > constexpr bool PhQ::operator>= (const PlanarTemperatureGradient< NumericType > & left, const PlanarTemperatureGradient< NumericType > & right) inline constexpr noexcept
Definition at line 253 of file PlanarTemperatureGradient.hpp.
operator>=() [43/100]
template<typename NumericType > constexpr bool PhQ::operator>= (const PlanarTraction< NumericType > & left, const PlanarTraction< NumericType > & right) inline constexpr noexcept
Definition at line 254 of file PlanarTraction.hpp.
operator>=() [44/100]
template<typename NumericType > constexpr bool PhQ::operator>= (const PlanarVector< NumericType > & left, const PlanarVector< NumericType > & right) inline constexpr noexcept
Definition at line 333 of file PlanarVector.hpp.
operator>=() [45/100]
template<typename NumericType > constexpr bool PhQ::operator>= (const PlanarVelocity< NumericType > & left, const PlanarVelocity< NumericType > & right) inline constexpr noexcept
Definition at line 273 of file PlanarVelocity.hpp.
operator>=() [46/100]
template<typename NumericType > constexpr bool PhQ::operator>= (const PoissonRatio< NumericType > & left, const PoissonRatio< NumericType > & right) inline constexpr noexcept
Definition at line 153 of file PoissonRatio.hpp.
operator>=() [47/100]
template<typename NumericType > constexpr bool PhQ::operator>= (const Position< NumericType > & left, const Position< NumericType > & right) inline constexpr noexcept
Definition at line 255 of file Position.hpp.
operator>=() [48/100]
template<typename NumericType > constexpr bool PhQ::operator>= (const Power< NumericType > & left, const Power< NumericType > & right) inline constexpr noexcept
Definition at line 208 of file Power.hpp.
operator>=() [49/100]
template<typename NumericType > constexpr bool PhQ::operator>= (const PrandtlNumber< NumericType > & left, const PrandtlNumber< NumericType > & right) inline constexpr noexcept
Definition at line 206 of file PrandtlNumber.hpp.
operator>=() [50/100]
template<typename NumericType > constexpr bool PhQ::operator>= (const PWaveModulus< NumericType > & left, const PWaveModulus< NumericType > & right) inline constexpr noexcept
Definition at line 169 of file PWaveModulus.hpp.
operator>=() [51/100]
template<typename NumericType > constexpr bool PhQ::operator>= (const ReynoldsNumber< NumericType > & left, const ReynoldsNumber< NumericType > & right) inline constexpr noexcept
Definition at line 216 of file ReynoldsNumber.hpp.
operator>=() [52/100]
template<typename NumericType > constexpr bool PhQ::operator>= (const ScalarAcceleration< NumericType > & left, const ScalarAcceleration< NumericType > & right) inline constexpr noexcept
Definition at line 224 of file ScalarAcceleration.hpp.
operator>=() [53/100]
template<typename NumericType > constexpr bool PhQ::operator>= (const ScalarAngularAcceleration< NumericType > & left, const ScalarAngularAcceleration< NumericType > & right) inline constexpr noexcept
Definition at line 209 of file ScalarAngularAcceleration.hpp.
operator>=() [54/100]
template<typename NumericType > constexpr bool PhQ::operator>= (const ScalarDisplacementGradient< NumericType > & left, const ScalarDisplacementGradient< NumericType > & right) inline constexpr noexcept
Definition at line 196 of file ScalarDisplacementGradient.hpp.
operator>=() [55/100]
template<typename NumericType > constexpr bool PhQ::operator>= (const ScalarForce< NumericType > & left, const ScalarForce< NumericType > & right) inline constexpr noexcept
Definition at line 213 of file ScalarForce.hpp.
operator>=() [56/100]
template<typename NumericType > constexpr bool PhQ::operator>= (const ScalarHeatFlux< NumericType > & left, const ScalarHeatFlux< NumericType > & right) inline constexpr noexcept
Definition at line 200 of file ScalarHeatFlux.hpp.
operator>=() [57/100]
template<typename NumericType > constexpr bool PhQ::operator>= (const ScalarStrain< NumericType > & left, const ScalarStrain< NumericType > & right) inline constexpr noexcept
Definition at line 193 of file ScalarStrain.hpp.
operator>=() [58/100]
template<typename NumericType > constexpr bool PhQ::operator>= (const ScalarStrainRate< NumericType > & left, const ScalarStrainRate< NumericType > & right) inline constexpr noexcept
Definition at line 196 of file ScalarStrainRate.hpp.
operator>=() [59/100]
template<typename NumericType > constexpr bool PhQ::operator>= (const ScalarStress< NumericType > & left, const ScalarStress< NumericType > & right) inline constexpr noexcept
Definition at line 174 of file ScalarStress.hpp.
operator>=() [60/100]
template<typename NumericType > constexpr bool PhQ::operator>= (const ScalarTemperatureGradient< NumericType > & left, const ScalarTemperatureGradient< NumericType > & right) inline constexpr noexcept
Definition at line 224 of file ScalarTemperatureGradient.hpp.
operator>=() [61/100]
template<typename NumericType > constexpr bool PhQ::operator>= (const ScalarThermalConductivity< NumericType > & left, const ScalarThermalConductivity< NumericType > & right) inline constexpr noexcept
Definition at line 222 of file ScalarThermalConductivity.hpp.
operator>=() [62/100]
template<typename NumericType > constexpr bool PhQ::operator>= (const ScalarTraction< NumericType > & left, const ScalarTraction< NumericType > & right) inline constexpr noexcept
Definition at line 208 of file ScalarTraction.hpp.
operator>=() [63/100]
template<typename NumericType > constexpr bool PhQ::operator>= (const ScalarVelocityGradient< NumericType > & left, const ScalarVelocityGradient< NumericType > & right) inline constexpr noexcept
Definition at line 202 of file ScalarVelocityGradient.hpp.
operator>=() [64/100]
template<typename NumericType > constexpr bool PhQ::operator>= (const ShearModulus< NumericType > & left, const ShearModulus< NumericType > & right) inline constexpr noexcept
Definition at line 171 of file ShearModulus.hpp.
operator>=() [65/100]
template<typename NumericType > constexpr bool PhQ::operator>= (const SolidAngle< NumericType > & left, const SolidAngle< NumericType > & right) inline constexpr noexcept
Definition at line 166 of file SolidAngle.hpp.
operator>=() [66/100]
template<typename NumericType > constexpr bool PhQ::operator>= (const SoundSpeed< NumericType > & left, const SoundSpeed< NumericType > & right) inline constexpr noexcept
Definition at line 222 of file SoundSpeed.hpp.
operator>=() [67/100]
template<typename NumericType > constexpr bool PhQ::operator>= (const SpecificEnergy< NumericType > & left, const SpecificEnergy< NumericType > & right) inline constexpr noexcept
Definition at line 202 of file SpecificEnergy.hpp.
operator>=() [68/100]
template<typename NumericType > constexpr bool PhQ::operator>= (const SpecificGasConstant< NumericType > & left, const SpecificGasConstant< NumericType > & right) inline constexpr noexcept
Definition at line 219 of file SpecificGasConstant.hpp.
operator>=() [69/100]
template<typename NumericType > constexpr bool PhQ::operator>= (const SpecificIsobaricHeatCapacity< NumericType > & left, const SpecificIsobaricHeatCapacity< NumericType > & right) inline constexpr noexcept
Definition at line 273 of file SpecificIsobaricHeatCapacity.hpp.
operator>=() [70/100]
template<typename NumericType > constexpr bool PhQ::operator>= (const SpecificIsochoricHeatCapacity< NumericType > & left, const SpecificIsochoricHeatCapacity< NumericType > & right) inline constexpr noexcept
Definition at line 226 of file SpecificIsochoricHeatCapacity.hpp.
operator>=() [71/100]
template<typename NumericType > constexpr bool PhQ::operator>= (const SpecificPower< NumericType > & left, const SpecificPower< NumericType > & right) inline constexpr noexcept
Definition at line 206 of file SpecificPower.hpp.
operator>=() [72/100]
template<typename NumericType > constexpr bool PhQ::operator>= (const Speed< NumericType > & left, const Speed< NumericType > & right) inline constexpr noexcept
Definition at line 314 of file Speed.hpp.
operator>=() [73/100]
template<typename NumericType > constexpr bool PhQ::operator>= (const StaticKinematicPressure< NumericType > & left, const StaticKinematicPressure< NumericType > & right) inline constexpr noexcept
Definition at line 205 of file StaticKinematicPressure.hpp.
operator>=() [74/100]
template<typename NumericType > constexpr bool PhQ::operator>= (const StaticPressure< NumericType > & left, const StaticPressure< NumericType > & right) inline constexpr noexcept
Definition at line 224 of file StaticPressure.hpp.
operator>=() [75/100]
template<typename NumericType > constexpr bool PhQ::operator>= (const Strain< NumericType > & left, const Strain< NumericType > & right) inline constexpr noexcept
Definition at line 253 of file Strain.hpp.
operator>=() [76/100]
template<typename NumericType > constexpr bool PhQ::operator>= (const StrainRate< NumericType > & left, const StrainRate< NumericType > & right) inline constexpr noexcept
Definition at line 268 of file StrainRate.hpp.
operator>=() [77/100]
template<typename NumericType > constexpr bool PhQ::operator>= (const Stress< NumericType > & left, const Stress< NumericType > & right) inline constexpr noexcept
Definition at line 279 of file Stress.hpp.
operator>=() [78/100]
template<typename NumericType > constexpr bool PhQ::operator>= (const SubstanceAmount< NumericType > & left, const SubstanceAmount< NumericType > & right) inline constexpr noexcept
Definition at line 169 of file SubstanceAmount.hpp.
operator>=() [79/100]
template<typename NumericType > constexpr bool PhQ::operator>= (const SymmetricDyad< NumericType > & left, const SymmetricDyad< NumericType > & right) inline constexpr noexcept
Definition at line 503 of file SymmetricDyad.hpp.
operator>=() [80/100]
template<typename NumericType > constexpr bool PhQ::operator>= (const Temperature< NumericType > & left, const Temperature< NumericType > & right) inline constexpr noexcept
Definition at line 190 of file Temperature.hpp.
operator>=() [81/100]
template<typename NumericType > constexpr bool PhQ::operator>= (const TemperatureDifference< NumericType > & left, const TemperatureDifference< NumericType > & right) inline constexpr noexcept
Definition at line 226 of file TemperatureDifference.hpp.
operator>=() [82/100]
template<typename NumericType > constexpr bool PhQ::operator>= (const TemperatureGradient< NumericType > & left, const TemperatureGradient< NumericType > & right) inline constexpr noexcept
Definition at line 251 of file TemperatureGradient.hpp.
operator>=() [83/100]
template<typename NumericType > constexpr bool PhQ::operator>= (const ThermalConductivity< NumericType > & left, const ThermalConductivity< NumericType > & right) inline constexpr noexcept
Definition at line 252 of file ThermalConductivity.hpp.
operator>=() [84/100]
template<typename NumericType > constexpr bool PhQ::operator>= (const ThermalDiffusivity< NumericType > & left, const ThermalDiffusivity< NumericType > & right) inline constexpr noexcept
Definition at line 196 of file ThermalDiffusivity.hpp.
operator>=() [85/100]
template<typename NumericType > constexpr bool PhQ::operator>= (const Time< NumericType > & left, const Time< NumericType > & right) inline constexpr noexcept
Definition at line 386 of file Time.hpp.
operator>=() [86/100]
template<typename NumericType > constexpr bool PhQ::operator>= (const TotalKinematicPressure< NumericType > & left, const TotalKinematicPressure< NumericType > & right) inline constexpr noexcept
Definition at line 201 of file TotalKinematicPressure.hpp.
operator>=() [87/100]
template<typename NumericType > constexpr bool PhQ::operator>= (const TotalPressure< NumericType > & left, const TotalPressure< NumericType > & right) inline constexpr noexcept
Definition at line 200 of file TotalPressure.hpp.
operator>=() [88/100]
template<typename NumericType > constexpr bool PhQ::operator>= (const Traction< NumericType > & left, const Traction< NumericType > & right) inline constexpr noexcept
Definition at line 251 of file Traction.hpp.
operator>=() [89/100]
template<typename NumericType > constexpr bool PhQ::operator>= (const TransportEnergyConsumption< NumericType > & left, const TransportEnergyConsumption< NumericType > & right) inline constexpr noexcept
Definition at line 202 of file TransportEnergyConsumption.hpp.
operator>=() [90/100]
template<typename NumericType > constexpr bool PhQ::operator>= (const typename ConstitutiveModel::CompressibleNewtonianFluid< NumericType > & left, const typename ConstitutiveModel::CompressibleNewtonianFluid< NumericType > & right) inline constexpr noexcept
Definition at line 386 of file CompressibleNewtonianFluid.hpp.
operator>=() [91/100]
template<typename NumericType > constexpr bool PhQ::operator>= (const typename ConstitutiveModel::ElasticIsotropicSolid< NumericType > & left, const typename ConstitutiveModel::ElasticIsotropicSolid< NumericType > & right) inline constexpr noexcept
Definition at line 629 of file ElasticIsotropicSolid.hpp.
operator>=() [92/100]
template<typename NumericType > constexpr bool PhQ::operator>= (const typename ConstitutiveModel::IncompressibleNewtonianFluid< NumericType > & left, const typename ConstitutiveModel::IncompressibleNewtonianFluid< NumericType > & right) inline constexpr noexcept
Definition at line 290 of file IncompressibleNewtonianFluid.hpp.
operator>=() [93/100]
template<typename NumericType > constexpr bool PhQ::operator>= (const Vector< NumericType > & left, const Vector< NumericType > & right) inline constexpr noexcept
Definition at line 361 of file Vector.hpp.
operator>=() [94/100]
template<typename NumericType > constexpr bool PhQ::operator>= (const VectorArea< NumericType > & left, const VectorArea< NumericType > & right) inline constexpr noexcept
Definition at line 223 of file VectorArea.hpp.
operator>=() [95/100]
template<typename NumericType > constexpr bool PhQ::operator>= (const Velocity< NumericType > & left, const Velocity< NumericType > & right) inline constexpr noexcept
Definition at line 268 of file Velocity.hpp.
operator>=() [96/100]
template<typename NumericType > constexpr bool PhQ::operator>= (const VelocityGradient< NumericType > & left, const VelocityGradient< NumericType > & right) inline constexpr noexcept
Definition at line 281 of file VelocityGradient.hpp.
operator>=() [97/100]
template<typename NumericType > constexpr bool PhQ::operator>= (const Volume< NumericType > & left, const Volume< NumericType > & right) inline constexpr noexcept
Definition at line 217 of file Volume.hpp.
operator>=() [98/100]
template<typename NumericType > constexpr bool PhQ::operator>= (const VolumeRate< NumericType > & left, const VolumeRate< NumericType > & right) inline constexpr noexcept
Definition at line 204 of file VolumeRate.hpp.
operator>=() [99/100]
template<typename NumericType > constexpr bool PhQ::operator>= (const VolumetricThermalExpansionCoefficient< NumericType > & left, const VolumetricThermalExpansionCoefficient< NumericType > & right) inline constexpr noexcept
Definition at line 206 of file VolumetricThermalExpansionCoefficient.hpp.
operator>=() [100/100]
template<typename NumericType > constexpr bool PhQ::operator>= (const YoungModulus< NumericType > & left, const YoungModulus< NumericType > & right) inline constexpr noexcept
Definition at line 169 of file YoungModulus.hpp.
ParseEnumeration()
template<typename Enumeration > std::optional< Enumeration > PhQ::ParseEnumeration (const std::string_view spelling)
Attempts to parse the given string as an enumeration of the given type. Returns a std::optional container that contains the resulting enumeration if successful, or std::nullopt if the given string could not be parsed into an enumeration of the given type.
Definition at line 107 of file Base.hpp.
ParseNumber() [1/4]
template<typename NumericType = double> std::optional< NumericType > PhQ::ParseNumber (const std::string & string) inline
Parses the given string as a number of the given numeric type. Returns a std::optional container that contains the resulting number if successful, or std::nullopt if the string could not be parsed into the given numeric type.
Template Parameters
NumericType Floating-point numeric type: float, double, or long double. Defaults to double if unspecified.
ParseNumber() [2/4]
template<> std::optional< float > PhQ::ParseNumber (const std::string & string) inline
Parses the given string as a single-precision floating-point number (a float). Returns a std::optional container that contains the resulting number if successful, or std::nullopt if the string could not be parsed into a float.
Definition at line 128 of file Base.hpp.
ParseNumber() [3/4]
template<> std::optional< double > PhQ::ParseNumber (const std::string & string) inline
Parses the given string as a double-precision floating-point number (a double). Returns a std::optional container that contains the resulting number if successful, or std::nullopt if the string could not be parsed into a double.
Definition at line 142 of file Base.hpp.
ParseNumber() [4/4]
template<> std::optional< long double > PhQ::ParseNumber (const std::string & string) inline
Parses the given string as an extended-precision floating-point number (a long double). Returns a std::optional container that contains the resulting number if successful, or std::nullopt if the string could not be parsed into a long double.
Definition at line 156 of file Base.hpp.
Print()
template<typename NumericType > std::string PhQ::Print (const NumericType value) inline
Prints a given floating-point number as a string. Prints enough digits to represent the number exactly. The printed number of digits depends on the type of the floating-point number.
Template Parameters
NumericType Floating-point numeric type of the given value. Deduced automatically.
Definition at line 170 of file Base.hpp.
Referenced by PhQ::DimensionalScalar< UnitType, NumericType >::JSON(), PhQ::DimensionlessScalar< NumericType >::JSON(), PhQ::Dyad< NumericType >::JSON(), PhQ::PlanarVector< NumericType >::JSON(), PhQ::SymmetricDyad< NumericType >::JSON(), PhQ::Vector< NumericType >::JSON(), PhQ::DimensionalScalar< UnitType, NumericType >::JSON(), PhQ::DimensionalScalar< UnitType, NumericType >::Print(), PhQ::DimensionlessScalar< NumericType >::Print(), PhQ::Dyad< NumericType >::Print(), PhQ::PlanarVector< NumericType >::Print(), PhQ::SymmetricDyad< NumericType >::Print(), PhQ::Vector< NumericType >::Print(), PhQ::DimensionalScalar< UnitType, NumericType >::Print(), PhQ::DimensionalScalar< UnitType, NumericType >::XML(), PhQ::DimensionlessScalar< NumericType >::XML(), PhQ::Dyad< NumericType >::XML(), PhQ::PlanarVector< NumericType >::XML(), PhQ::SymmetricDyad< NumericType >::XML(), PhQ::Vector< NumericType >::XML(), PhQ::DimensionalScalar< UnitType, NumericType >::XML(), PhQ::DimensionalScalar< UnitType, NumericType >::YAML(), PhQ::DimensionlessScalar< NumericType >::YAML(), PhQ::Dyad< NumericType >::YAML(), PhQ::PlanarVector< NumericType >::YAML(), PhQ::SymmetricDyad< NumericType >::YAML(), PhQ::Vector< NumericType >::YAML(), and PhQ::DimensionalScalar< UnitType, NumericType >::YAML().
RelatedUnitSystem()
template<typename Unit > std::optional< UnitSystem > PhQ::RelatedUnitSystem (const Unit & unit) inline
Returns the unit system, if any, that corresponds to a given unit, or std::nullptr otherwise. For example, PhQ::RelatedUnitSystem(PhQ::Unit::Length::Millimetre) returns PhQ::UnitSystem::MillimetreGramSecondKelvin.
Definition at line 233 of file UnitSystem.hpp.
SnakeCase()
std::string PhQ::SnakeCase (const std::string_view string) inline
Returns a copy of the given string in snake case: all characters are lowercase and all spaces are replaced with underscores.
Definition at line 263 of file Base.hpp.
References Lowercase().
Referenced by PhQ::Dimensions::JSON(), PhQ::ConstitutiveModel::CompressibleNewtonianFluid< NumericType >::JSON(), PhQ::ConstitutiveModel::ElasticIsotropicSolid< NumericType >::JSON(), PhQ::ConstitutiveModel::IncompressibleNewtonianFluid< NumericType >::JSON(), PhQ::Dimensions::XML(), PhQ::ConstitutiveModel::CompressibleNewtonianFluid< NumericType >::XML(), PhQ::ConstitutiveModel::ElasticIsotropicSolid< NumericType >::XML(), PhQ::Dimensions::YAML(), PhQ::ConstitutiveModel::CompressibleNewtonianFluid< NumericType >::YAML(), and PhQ::ConstitutiveModel::ElasticIsotropicSolid< NumericType >::YAML().
Uppercase()
std::string PhQ::Uppercase (const std::string_view string) inline
Returns a copy of the given string where all characters are uppercase.
Definition at line 253 of file Base.hpp.
Variable Documentation
Dimensionless
constexpr Dimensions PhQ::Dimensionless inline constexpr
Dimensionless physical dimension set. This dimension set has all base dimensions of zero. Applies to all dimensionless units of measure and dimensionless physical quantities.
Definition at line 406 of file Dimensions.hpp.
Referenced by PhQ::DimensionlessDyad< NumericType >::Dimensions(), PhQ::DimensionlessPlanarVector< NumericType >::Dimensions(), PhQ::DimensionlessScalar< NumericType >::Dimensions(), PhQ::DimensionlessSymmetricDyad< NumericType >::Dimensions(), and PhQ::DimensionlessVector< NumericType >::Dimensions().
Pi
template<typename NumericType = double> constexpr NumericType PhQ::Pi inline constexpr
The mathematical constant π = 3.14...
Template Parameters
NumericType Floating-point numeric type: float, double, or long double. Defaults to double if unspecified.
Definition at line 53 of file Base.hpp.
Pi< double >
template<> constexpr double PhQ::Pi< double > {3.14159265358979323846} inline constexpr
The mathematical constant π = 3.14... expressed as a double-precision 64-bit binary floating-point number.
Definition at line 63 of file Base.hpp.
Pi< float >
template<> constexpr float PhQ::Pi< float > {3.1415927F} inline constexpr
The mathematical constant π = 3.14... expressed as a single-precision 32-bit binary floating-point number.
Definition at line 58 of file Base.hpp.
Pi< long double >
template<> constexpr const long double PhQ::Pi< long double > {3.141592653589793238462643383279502884L} inline constexpr
The mathematical constant π = 3.14... expressed as an extended-precision binary floating-point number. The exact implementation of the extended-precision type varies; the most common implementations are 64-bit, 80-bit, 96-bit, or 128-bit binary floating-point numbers.
Definition at line 69 of file Base.hpp.
RelatedDimensions
template<typename Unit > constexpr Dimensions PhQ::RelatedDimensions inline constexpr
Physical dimension set of a given type of unit of measure. Units of measure are organized into types that share the same physical dimension set.
Definition at line 47 of file Unit.hpp.
Standard
template<typename Type > constexpr const Type PhQ::Standard inline constexpr
Standard unit of measure of a given type. Standard units of measure of different types can be combined with each other without the need for conversions. When a physical quantity is expressed in terms of a standard unit of measure, its value does not need to be converted when used in mathematical expressions with other physical quantities expressed in standard units of measure. For example, the standard unit of time is the second and the standard unit of length is the metre. Correspondingly, the standard unit of speed is the metre per second. Thus, when forming a speed quantity from a length quantity and a time quantity, if all quantities are expressed in these standard units, no unit conversions are needed.
Definition at line 66 of file UnitSystem.hpp.
Standard< UnitSystem >
template<> constexpr const UnitSystem PhQ::Standard< UnitSystem > {UnitSystem::MetreKilogramSecondKelvin} inline constexpr
The standard unit system: the International System of Units (SI). It uses the following standard units: second (s) for time, metre (m) for length, kilogram (kg) for mass, ampere (A) for electric current, kelvin (K) for temperature, mole (mol) for substance amount, and candela (cd) for luminous intensity.
Definition at line 73 of file UnitSystem.hpp.