Physical Quantities (PhQ): PhQ::Dimension Namespace Reference
PhQ::Dimension Namespace Reference
Namespace that contains base physical dimensions.
Classes
class ElectricCurrent
Base physical dimension of electric current. Typically denoted "I". One of seven independent base physical dimensions that form the physical dimension set of any unit of measure or physical quantity. Part of PhQ::Dimensions.
class Length
Base physical dimension of length. Typically denoted "L". One of seven independent base physical dimensions that form the physical dimension set of any unit of measure or physical quantity. Part of PhQ::Dimensions.
class LuminousIntensity
Base physical dimension of luminous intensity. Typically denoted "J". One of seven independent base physical dimensions that form the physical dimension set of any unit of measure or physical quantity. Part of PhQ::Dimensions.
class Mass
Base physical dimension of mass. Typically denoted "M". One of seven independent base physical dimensions that form the physical dimension set of any unit of measure or physical quantity. Part of PhQ::Dimensions.
class SubstanceAmount
Base physical dimension of amount of substance. Typically denoted "N". One of seven independent base physical dimensions that form the physical dimension set of any unit of measure or physical quantity. Part of PhQ::Dimensions.
class Temperature
Base physical dimension of temperature. Typically denoted "Θ". One of seven independent base physical dimensions that form the physical dimension set of any unit of measure or physical quantity. Part of PhQ::Dimensions.
class Time
Base physical dimension of time. Typically denoted "T". One of seven independent base physical dimensions that form the physical dimension set of any unit of measure or physical quantity. Part of PhQ::Dimensions.
Functions
constexpr bool operator== (const ElectricCurrent &left, const ElectricCurrent &right) noexcept
constexpr bool operator!= (const ElectricCurrent &left, const ElectricCurrent &right) noexcept
constexpr bool operator< (const ElectricCurrent &left, const ElectricCurrent &right) noexcept
constexpr bool operator> (const ElectricCurrent &left, const ElectricCurrent &right) noexcept
constexpr bool operator<= (const ElectricCurrent &left, const ElectricCurrent &right) noexcept
constexpr bool operator>= (const ElectricCurrent &left, const ElectricCurrent &right) noexcept
std::ostream & operator<< (std::ostream &stream, const ElectricCurrent &current)
constexpr bool operator== (const Length &left, const Length &right) noexcept
constexpr bool operator!= (const Length &left, const Length &right) noexcept
constexpr bool operator< (const Length &left, const Length &right) noexcept
constexpr bool operator> (const Length &left, const Length &right) noexcept
constexpr bool operator<= (const Length &left, const Length &right) noexcept
constexpr bool operator>= (const Length &left, const Length &right) noexcept
std::ostream & operator<< (std::ostream &stream, const Length &length)
constexpr bool operator== (const LuminousIntensity &left, const LuminousIntensity &right) noexcept
constexpr bool operator!= (const LuminousIntensity &left, const LuminousIntensity &right) noexcept
constexpr bool operator< (const LuminousIntensity &left, const LuminousIntensity &right) noexcept
constexpr bool operator> (const LuminousIntensity &left, const LuminousIntensity &right) noexcept
constexpr bool operator<= (const LuminousIntensity &left, const LuminousIntensity &right) noexcept
constexpr bool operator>= (const LuminousIntensity &left, const LuminousIntensity &right) noexcept
std::ostream & operator<< (std::ostream &stream, const LuminousIntensity &intensity)
constexpr bool operator== (const Mass &left, const Mass &right) noexcept
constexpr bool operator!= (const Mass &left, const Mass &right) noexcept
constexpr bool operator< (const Mass &left, const Mass &right) noexcept
constexpr bool operator> (const Mass &left, const Mass &right) noexcept
constexpr bool operator<= (const Mass &left, const Mass &right) noexcept
constexpr bool operator>= (const Mass &left, const Mass &right) noexcept
std::ostream & operator<< (std::ostream &stream, const Mass &mass)
constexpr bool operator== (const SubstanceAmount &left, const SubstanceAmount &right) noexcept
constexpr bool operator!= (const SubstanceAmount &left, const SubstanceAmount &right) noexcept
constexpr bool operator< (const SubstanceAmount &left, const SubstanceAmount &right) noexcept
constexpr bool operator> (const SubstanceAmount &left, const SubstanceAmount &right) noexcept
constexpr bool operator<= (const SubstanceAmount &left, const SubstanceAmount &right) noexcept
constexpr bool operator>= (const SubstanceAmount &left, const SubstanceAmount &right) noexcept
std::ostream & operator<< (std::ostream &stream, const SubstanceAmount &amount)
constexpr bool operator== (const Temperature &left, const Temperature &right) noexcept
constexpr bool operator!= (const Temperature &left, const Temperature &right) noexcept
constexpr bool operator< (const Temperature &left, const Temperature &right) noexcept
constexpr bool operator> (const Temperature &left, const Temperature &right) noexcept
constexpr bool operator<= (const Temperature &left, const Temperature &right) noexcept
constexpr bool operator>= (const Temperature &left, const Temperature &right) noexcept
std::ostream & operator<< (std::ostream &stream, const Temperature &temperature)
constexpr bool operator== (const Time &left, const Time &right) noexcept
constexpr bool operator!= (const Time &left, const Time &right) noexcept
constexpr bool operator< (const Time &left, const Time &right) noexcept
constexpr bool operator> (const Time &left, const Time &right) noexcept
constexpr bool operator<= (const Time &left, const Time &right) noexcept
constexpr bool operator>= (const Time &left, const Time &right) noexcept
std::ostream & operator<< (std::ostream &stream, const Time &time)
Detailed Description
Namespace that contains base physical dimensions.
Function Documentation
operator!=() [1/7]
constexpr bool PhQ::Dimension::operator!= (const ElectricCurrent & left, const ElectricCurrent & right) inline constexpr noexcept
Definition at line 108 of file ElectricCurrent.hpp.
operator!=() [2/7]
constexpr bool PhQ::Dimension::operator!= (const Length & left, const Length & right) inline constexpr noexcept
Definition at line 105 of file Length.hpp.
operator!=() [3/7]
constexpr bool PhQ::Dimension::operator!= (const LuminousIntensity & left, const LuminousIntensity & right) inline constexpr noexcept
Definition at line 108 of file LuminousIntensity.hpp.
operator!=() [4/7]
constexpr bool PhQ::Dimension::operator!= (const Mass & left, const Mass & right) inline constexpr noexcept
Definition at line 103 of file Mass.hpp.
operator!=() [5/7]
constexpr bool PhQ::Dimension::operator!= (const SubstanceAmount & left, const SubstanceAmount & right) inline constexpr noexcept
Definition at line 108 of file SubstanceAmount.hpp.
operator!=() [6/7]
constexpr bool PhQ::Dimension::operator!= (const Temperature & left, const Temperature & right) inline constexpr noexcept
Definition at line 106 of file Temperature.hpp.
operator!=() [7/7]
constexpr bool PhQ::Dimension::operator!= (const Time & left, const Time & right) inline constexpr noexcept
Definition at line 103 of file Time.hpp.
operator<() [1/7]
constexpr bool PhQ::Dimension::operator< (const ElectricCurrent & left, const ElectricCurrent & right) inline constexpr noexcept
Definition at line 113 of file ElectricCurrent.hpp.
operator<() [2/7]
constexpr bool PhQ::Dimension::operator< (const Length & left, const Length & right) inline constexpr noexcept
Definition at line 109 of file Length.hpp.
operator<() [3/7]
constexpr bool PhQ::Dimension::operator< (const LuminousIntensity & left, const LuminousIntensity & right) inline constexpr noexcept
Definition at line 113 of file LuminousIntensity.hpp.
operator<() [4/7]
constexpr bool PhQ::Dimension::operator< (const Mass & left, const Mass & right) inline constexpr noexcept
Definition at line 107 of file Mass.hpp.
operator<() [5/7]
constexpr bool PhQ::Dimension::operator< (const SubstanceAmount & left, const SubstanceAmount & right) inline constexpr noexcept
Definition at line 113 of file SubstanceAmount.hpp.
operator<() [6/7]
constexpr bool PhQ::Dimension::operator< (const Temperature & left, const Temperature & right) inline constexpr noexcept
Definition at line 110 of file Temperature.hpp.
operator<() [7/7]
constexpr bool PhQ::Dimension::operator< (const Time & left, const Time & right) inline constexpr noexcept
Definition at line 107 of file Time.hpp.
operator<<() [1/7]
std::ostream& PhQ::Dimension::operator<< (std::ostream & stream, const ElectricCurrent & current) inline
Definition at line 133 of file ElectricCurrent.hpp.
References PhQ::Dimension::ElectricCurrent::Print().
operator<<() [2/7]
std::ostream& PhQ::Dimension::operator<< (std::ostream & stream, const Length & length) inline
Definition at line 125 of file Length.hpp.
References PhQ::Dimension::Length::Print().
operator<<() [3/7]
std::ostream& PhQ::Dimension::operator<< (std::ostream & stream, const LuminousIntensity & intensity) inline
Definition at line 133 of file LuminousIntensity.hpp.
References PhQ::Dimension::LuminousIntensity::Print().
operator<<() [4/7]
std::ostream& PhQ::Dimension::operator<< (std::ostream & stream, const Mass & mass) inline
Definition at line 123 of file Mass.hpp.
References PhQ::Dimension::Mass::Print().
operator<<() [5/7]
std::ostream& PhQ::Dimension::operator<< (std::ostream & stream, const SubstanceAmount & amount) inline
Definition at line 133 of file SubstanceAmount.hpp.
References PhQ::Dimension::SubstanceAmount::Print().
operator<<() [6/7]
std::ostream& PhQ::Dimension::operator<< (std::ostream & stream, const Temperature & temperature) inline
Definition at line 126 of file Temperature.hpp.
References PhQ::Dimension::Temperature::Print().
operator<<() [7/7]
std::ostream& PhQ::Dimension::operator<< (std::ostream & stream, const Time & time) inline
Definition at line 123 of file Time.hpp.
References PhQ::Dimension::Time::Print().
operator<=() [1/7]
constexpr bool PhQ::Dimension::operator<= (const ElectricCurrent & left, const ElectricCurrent & right) inline constexpr noexcept
Definition at line 123 of file ElectricCurrent.hpp.
operator<=() [2/7]
constexpr bool PhQ::Dimension::operator<= (const Length & left, const Length & right) inline constexpr noexcept
Definition at line 117 of file Length.hpp.
operator<=() [3/7]
constexpr bool PhQ::Dimension::operator<= (const LuminousIntensity & left, const LuminousIntensity & right) inline constexpr noexcept
Definition at line 123 of file LuminousIntensity.hpp.
operator<=() [4/7]
constexpr bool PhQ::Dimension::operator<= (const Mass & left, const Mass & right) inline constexpr noexcept
Definition at line 115 of file Mass.hpp.
operator<=() [5/7]
constexpr bool PhQ::Dimension::operator<= (const SubstanceAmount & left, const SubstanceAmount & right) inline constexpr noexcept
Definition at line 123 of file SubstanceAmount.hpp.
operator<=() [6/7]
constexpr bool PhQ::Dimension::operator<= (const Temperature & left, const Temperature & right) inline constexpr noexcept
Definition at line 118 of file Temperature.hpp.
operator<=() [7/7]
constexpr bool PhQ::Dimension::operator<= (const Time & left, const Time & right) inline constexpr noexcept
Definition at line 115 of file Time.hpp.
operator==() [1/7]
constexpr bool PhQ::Dimension::operator== (const ElectricCurrent & left, const ElectricCurrent & right) inline constexpr noexcept
Definition at line 103 of file ElectricCurrent.hpp.
operator==() [2/7]
constexpr bool PhQ::Dimension::operator== (const Length & left, const Length & right) inline constexpr noexcept
Definition at line 101 of file Length.hpp.
operator==() [3/7]
constexpr bool PhQ::Dimension::operator== (const LuminousIntensity & left, const LuminousIntensity & right) inline constexpr noexcept
Definition at line 103 of file LuminousIntensity.hpp.
operator==() [4/7]
constexpr bool PhQ::Dimension::operator== (const Mass & left, const Mass & right) inline constexpr noexcept
Definition at line 99 of file Mass.hpp.
operator==() [5/7]
constexpr bool PhQ::Dimension::operator== (const SubstanceAmount & left, const SubstanceAmount & right) inline constexpr noexcept
Definition at line 103 of file SubstanceAmount.hpp.
operator==() [6/7]
constexpr bool PhQ::Dimension::operator== (const Temperature & left, const Temperature & right) inline constexpr noexcept
Definition at line 102 of file Temperature.hpp.
operator==() [7/7]
constexpr bool PhQ::Dimension::operator== (const Time & left, const Time & right) inline constexpr noexcept
Definition at line 99 of file Time.hpp.
operator>() [1/7]
constexpr bool PhQ::Dimension::operator> (const ElectricCurrent & left, const ElectricCurrent & right) inline constexpr noexcept
Definition at line 118 of file ElectricCurrent.hpp.
operator>() [2/7]
constexpr bool PhQ::Dimension::operator> (const Length & left, const Length & right) inline constexpr noexcept
Definition at line 113 of file Length.hpp.
operator>() [3/7]
constexpr bool PhQ::Dimension::operator> (const LuminousIntensity & left, const LuminousIntensity & right) inline constexpr noexcept
Definition at line 118 of file LuminousIntensity.hpp.
operator>() [4/7]
constexpr bool PhQ::Dimension::operator> (const Mass & left, const Mass & right) inline constexpr noexcept
Definition at line 111 of file Mass.hpp.
operator>() [5/7]
constexpr bool PhQ::Dimension::operator> (const SubstanceAmount & left, const SubstanceAmount & right) inline constexpr noexcept
Definition at line 118 of file SubstanceAmount.hpp.
operator>() [6/7]
constexpr bool PhQ::Dimension::operator> (const Temperature & left, const Temperature & right) inline constexpr noexcept
Definition at line 114 of file Temperature.hpp.
operator>() [7/7]
constexpr bool PhQ::Dimension::operator> (const Time & left, const Time & right) inline constexpr noexcept
Definition at line 111 of file Time.hpp.
operator>=() [1/7]
constexpr bool PhQ::Dimension::operator>= (const ElectricCurrent & left, const ElectricCurrent & right) inline constexpr noexcept
Definition at line 128 of file ElectricCurrent.hpp.
operator>=() [2/7]
constexpr bool PhQ::Dimension::operator>= (const Length & left, const Length & right) inline constexpr noexcept
Definition at line 121 of file Length.hpp.
operator>=() [3/7]
constexpr bool PhQ::Dimension::operator>= (const LuminousIntensity & left, const LuminousIntensity & right) inline constexpr noexcept
Definition at line 128 of file LuminousIntensity.hpp.
operator>=() [4/7]
constexpr bool PhQ::Dimension::operator>= (const Mass & left, const Mass & right) inline constexpr noexcept
Definition at line 119 of file Mass.hpp.
operator>=() [5/7]
constexpr bool PhQ::Dimension::operator>= (const SubstanceAmount & left, const SubstanceAmount & right) inline constexpr noexcept
Definition at line 128 of file SubstanceAmount.hpp.
operator>=() [6/7]
constexpr bool PhQ::Dimension::operator>= (const Temperature & left, const Temperature & right) inline constexpr noexcept
Definition at line 122 of file Temperature.hpp.
operator>=() [7/7]
constexpr bool PhQ::Dimension::operator>= (const Time & left, const Time & right) inline constexpr noexcept
Definition at line 119 of file Time.hpp.